### ISSUE TITLE
🐝 [Bug] Incorrect quest requirement for Scarab Shells pre 1.3

### ISSUE THREAD

**Issue by ghost** [vmangos/core#1002]
The quest Scarab Shells should require nine scarab shells instead of five pre 1.3

### Expected behavior
Should require nine scarab shells and not five. See the wiki patch notes for 1.3. https://wowwiki.fandom.com/wiki/Patch_1.3.0#Quests

"The Scarab Shells quest in Zul'Farrak's item requirement was reduced from nine Uncracked Scarab Shells to five"

### Steps to reproduce
1. Accept quest Scarab Shells
2. Check requirements

**Comment by ghost** [comment]
```
REPLACE INTO `quest_template` VALUES (2865, 0, 2, 978, 40, 0, 45, 81, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 2864, 0, 0, 0, 0, 0, 0, 'Scarab Shells', 'The scarabs of Tanaris have very hard shells!  Hard enough to use as a building material for lots of things.  So many things!$B$BIn fact, those shells are so useful... the scarabs were hunted all to near extinction!$B$BI know where there are more scarabs, and if you promise to bring me their shells then I\'ll tell you where they are.  Promise?$B$BOk, the scarabs have a colony in Zul\'Farrak.  I guess the trolls don\'t hunt them for their shells.$B$BBut you can!  Go to Zul\'Farrak and get me uncracked shells!', 'Bring 9 Uncracked Scarab Shells to Tran\'rek in Gadgetzan.', 'Oh, great!  You got them!$B$BThanks, $N.  You\'re a real lifesaver!', 'Do you have the shells?  My cousin in Booty Bay is waiting for a load of them, and he\'s getting impatient!', '', '', '', '', '', 9238, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 369, 0, 0, 0, 0, 100, 0, 0, 0, 0, 3900, 6500, 2340, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `quest_template` VALUES (2865, 1, 2, 978, 40, 0, 45, 81, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 2864, 0, 0, 0, 0, 0, 0, 'Scarab Shells', 'The scarabs of Tanaris have very hard shells!  Hard enough to use as a building material for lots of things.  So many things!$B$BIn fact, those shells are so useful... the scarabs were hunted all to near extinction!$B$BI know where there are more scarabs, and if you promise to bring me their shells then I\'ll tell you where they are.  Promise?$B$BOk, the scarabs have a colony in Zul\'Farrak.  I guess the trolls don\'t hunt them for their shells.$B$BBut you can!  Go to Zul\'Farrak and get me uncracked shells!', 'Bring 5 Uncracked Scarab Shells to Tran\'rek in Gadgetzan.', 'Oh, great!  You got them!$B$BThanks, $N.  You\'re a real lifesaver!', 'Do you have the shells?  My cousin in Booty Bay is waiting for a load of them, and he\'s getting impatient!', '', '', '', '', '', 9238, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 369, 0, 0, 0, 0, 100, 0, 0, 0, 0, 3900, 6500, 2340, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0);
```

**Comment by ulfgebhardt** [comment]
Please make a PR for this @thenewblock cheers

**Comment by ghost** [comment]
I don't know how

**Comment by ulfgebhardt** [comment]
Do the following:
1. Fork the repo 

![image](https://user-images.githubusercontent.com/1238238/104854818-33965500-5909-11eb-99bf-846917a5dbc3.png)
![image](https://user-images.githubusercontent.com/1238238/104854827-3e50ea00-5909-11eb-945e-76a68a704b17.png)

2. Clone your fork `git clone git@github.com:USER/core.git` to your local machine (install git or use [smartgit](https://www.syntevo.com/smartgit/))
3. Create a new branch `git branch fix_scarabshell_pre_1_3`
4. Make your fix (there is a [script](https://github.com/vmangos/core/blob/development/sql/make_migration.bat) to create migrations) - add your SQL-Lines in the  created file
5. add your new file to your stash `git add .`
6. Commit your change in stash onto your local branch `git commit -m "Fixed XY"`
7. Push to your local branch to the remote on Github which will create the branch there: `git push`
8. Make a PR from your fork (yellow box will pop up on your fork)

At first glance this seems a bit complicated - but you will get the hang of it very easily and your understanding of git will level doing this. If you use Smartgit it keeps you from doing all those nasty commands in comandline, but comes with the same complexity packed in an UI.

If you have 1h consider to try this. The next fix will take 10min max after you have done it once properly and have all required infrastructure set up.

Your PR will then show up [here](https://github.com/vmangos/core/pulls) and will allow responsible people `/wave @ratkosrb ` to merge it via button press. Also it allows a conversation if changes are needed.

9. Once you have pushed all your stuff and opened the PR to this repo, make sure to switch back to the main branch on your local machine so you have a clean work environment for your next fix: `git checkout development`
10. For the next fix you start with `git pull` and then go on with 3.

If you have questions or trouble, we can also talk or chat on discord

<3 Ulf
