### ISSUE TITLE
🐛 Lava elementals should be immune to Nature

### ISSUE THREAD

**Issue by T1ti** [vmangos/core#1019]
## 🐛 Bug report
I only tested this one : 
https://classic.wowhead.com/npc=5855/magma-elemental
On classic he is immune to nature damages, on vmangos he is not.

### Expected behavior
Proofs : 
Wowhead comments : 
https://www.wowhead.com/npc=5855/magma-elemental#comments:id=222489
I tried it myself on classic : with a nature wand : 
![image](https://user-images.githubusercontent.com/40864460/105768856-4a6a2680-5f5d-11eb-9bf5-c43eed1d435f.png)
(sorry for the shitty screenshot, that's because it was for someone else)

I don't know if this applies to ALL lava elementals like the annihilators in MC, or only this one in searing gorge, but probably all.

### Steps to reproduce
1. test damaging it with nature dmg on classic and vmangos

### Version & Environment
  Client Version:
  - 1.12.1.5875

Commit Hash:  b51cdeb98ea831faee477df90327546ee8916f6f

**Comment by Velite12** [comment]
https://www.youtube.com/watch?v=gWLw9lpMDeQ

This video shows a warrior using thunderfury on MC trash mobs. No immunity on Garr in classic.

**Comment by T1ti** [comment]
https://youtu.be/gWLw9lpMDeQ?t=1804

The normal ones are immune

**Comment by Velite12** [comment]
But wouldn't they be immune to the thunderfury proc then? It's nature

Edit: That could be the Perdition's proc.

Edit2: I was talking about the thunderfury debuffs, since they are all classed as nature.

**Comment by T1ti** [comment]
Lava surgers are not immune to fire, verified from my guild logs which has some fire mages

![image](https://user-images.githubusercontent.com/40864460/105772663-d3d02780-5f62-11eb-886f-38e14a9914ba.png)

None of my warrior tanks have any thunderfury dmg on them, which should prove they are immune to nature and not to fire.

I can confirm this is the same for all other lava elementals in MC (annihilators, lava elementals)

**Comment by Velite12** [comment]
So how were the warriors doing thunderfury procs on them? Also the shamans were hitting them with stormstrike . Is it just a check for damage immunity?
![fff17d6be58ddb00ab0ca5bec27cf418](https://user-images.githubusercontent.com/45871932/105774576-6789ff80-5f33-11eb-82b6-24e501551a78.png)

**Comment by T1ti** [comment]
Sorry, my raid had no thunderfury in the logs I was looking at 🤔 

i can't tell from logs if the "lava elemental" ones are immune to fire, as they are always pulled in packs, but some other are not immune to fire

**Comment by Velite12** [comment]
I am 100% sure that if the mob is immune to the damage, it has to be immune to the debuff, since they are technically the same spell with the same resistance type. So while it is possible that these specific mobs are nature immune, I think it's just a case for these ones and not all lava elementals.

In the case of thunderfury, the -25 nr is in the same spell as the 300 damage. So it is immune to both or neither.

**Comment by T1ti** [comment]
![image](https://user-images.githubusercontent.com/40864460/105775280-da609e00-5f66-11eb-9270-ab933c33a480.png)
Looking at some random guys logs, they aren't immune to fire.

**Comment by Velite12** [comment]
![12f49bf153139f4246732262297630b0](https://user-images.githubusercontent.com/45871932/105775851-85f0fa80-5f35-11eb-8244-6374bdb30fc2.png)
It could have been that his heroic strike was using a macro to use hamstring, which they would be immune to.

Keep an eye for 300/450 when thunderfury proc refreshes.

Almost certain this 300 proc is that warrior's thunderfury that was just applied to the mob.

**Comment by Velite12** [comment]
Deep wounds. Elementals are immune to it, that is what was listed as immune. It procs when dps warriors crit.

So specifically that mob in searing gorge is nature immune, perhaps. But not the mc elementals.

**Comment by T1ti** [comment]
This is the list of all lava elementals in the game (model id ElementalEarth + texture variation = RockElementalSkinBlack)

![image](https://user-images.githubusercontent.com/40864460/105777458-b0a97600-5f6a-11eb-91b7-200901575bf4.png)

None of them have an immune mask. It might be worth verifying them on classic, I think the MC creatures are an exception

The querry used : 
_SELECT  `entry`,  `name`,  `school_immune_mask` FROM `mangos`.`creature_template` WHERE  display_id1 IN (2075, 2169, 2170, 4759, 5781, 8109,12110,12163,12164,12239,16021)
ORDER BY `entry`_

**Comment by Velite12** [comment]
Logically, all wind elementals are nature immune. As for rock elementals (lava and regular), I'm not so sure that they should all be (again thematically speaking) immune but they should be highly resistant, but I think blizzard was a bit inconsistent so I'm sure that some of these are. I would test if i had a classic account and character myself :(

**Comment by T1ti** [comment]
Tested some on Classic : 
Obsidian Elemental : Not immune
Greater Obsidian elemental : Not immune
Magma Lord Bokk : Immune to nature
Smoldar : Immune to nature
Molten elemental : Immune to Nature
Magma elemental : immune to nature
Enraged Stone Spirit : Immune to nature
Furious Stone Spirit : Immune to nature
_Minor Manifestation of Earth : They are friendly NPCs_

**Comment by T1ti** [comment]
Tested all of them except the searing gorge rare.

5 out of 7 are immune to nature.

**Comment by T1ti** [comment]
Finally found Smoldar, he is indeed immune to nature, so 6 out of 8 are immune. 
![image](https://user-images.githubusercontent.com/40864460/106404326-bc95ac00-6432-11eb-8fc6-449f6309e062.png)
