### ISSUE TITLE
some error infomation about quest "The Battle of Darrowshire"

### ISSUE THREAD

**Issue by hyphenz** [vmangos/core#102]
when players doing quest "The Battle of Darrowshire"
"info.log" has something like those:  ("mangosd" program not crash)
[Crash/Auras] Deleting aura 13555 in use (Creature (Entry: 10940 Guid: 2541319))
./mangosd(_ZN3Map21AddObjectToRemoveListEP11WorldObject+0xfa) [0x82049a]
./mangosd(_ZN11WorldObject21AddObjectToRemoveListEv+0x24) [0x8ccca4]
./mangosd(_ZN3Map29ScriptCommand_DespawnCreatureERK10ScriptInfoP11WorldObjectS4_+0x63) [0x8514b3]
./mangosd(_ZN3Map24ScriptCommandStartDirectERK10ScriptInfoP11WorldObjectS4_+0x71) [0x82a5d1]
./mangosd() [0x6b103d]
./mangosd(_ZN15CreatureEventAI8JustDiedEP4Unit+0x10d) [0x6b1c4d]
./mangosd(_ZN4Unit4KillEPS_PK10SpellEntryb+0x119f) [0x97dcbf]
./mangosd(_ZN4Unit10DealDamageEPS_jPK11CleanDamage16DamageEffectType15SpellSchoolMaskPK10SpellEntrybP5Spell+0x7a1) [0x97e661]
./mangosd(_ZN4Aura12PeriodicTickEPK10SpellEntry8AuraTypej+0x754) [0x9f1724]
./mangosd(_ZN15SpellAuraHolder6UpdateEj+0xb9) [0x9ea649]
./mangosd(_ZN4Unit13_UpdateSpellsEj+0x1ef) [0x96999f]
./mangosd(_ZN4Unit6UpdateEjj+0x47a) [0x9825da]
./mangosd(_ZN8Creature6UpdateEjj+0xb7) [0x8ab397]
./mangosd(_ZN6MaNGOS13ObjectUpdater5VisitER14GridRefManagerI8CreatureE+0xe2) [0x82f062]
./mangosd(_ZN3Map5VisitIN6MaNGOS13ObjectUpdaterE16TypeMapContainerI8TypeListI10GameObjectS4_I8CreatureS4_I13DynamicObjectS4_I6Corpse8TypeNullEEEEEEEvRK4CellR20TypeContainerVisitorIT_T0_E+0xd2) [0x8305a2]
./mangosd(_ZN3Map11UpdateCellsEj+0x27b) [0x833b0b]
./mangosd(_ZN3Map6UpdateEj+0x127) [0x82a977]
./mangosd(_ZN21ContinentAsyncUpdater3runEv+0x1a) [0x83e2ba]
./mangosd(_ZN9ACE_Based6Thread10ThreadTaskEPv+0x25) [0xd03cc5]
/usr/local/lib/libACE.so.6.5.0(_ZN21ACE_OS_Thread_Adapter6invokeEv+0xc6) [0x7fa1d26d54d6]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7fa1d151f6ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fa1d09b441d]

**Comment by ratkosrb** [comment]
Should be fixed by this commit, removed the event mentioned in the log https://github.com/vmangos/core/commit/cc9f80733b5ce66277147942af339dbac81b09a8
