### ISSUE TITLE
Many bosses in Temple of Ahn'Qiraj have incorrect or non-existent gold drop values. 🐛 [Bug]

### ISSUE THREAD

**Issue by faralynn** [vmangos/core#1021]
## 🐛 Bug report
The following bosses in AQ40 have incorrect gold drop values:

- Yauj | Current gold drop (if killed LAST): 2.9 Gold
- Vem | Current gold drop (if killed LAST): 0 Gold
- Kri | Current gold drop (if killed LAST): 2.9 Gold
- Emperor Vek'nilash | Current gold drop: 0 Gold
- Ouro | Current gold drop: 0 Gold

### Expected behavior
- Yauj | Expected gold drop (if killed LAST): 50-89.5 Gold
- Vem | Expected gold drop (if killed LAST): 50-89.5 Gold
- Kri | Expected gold drop (if killed LAST): 50-89.5 Gold
- Emperor Vek'nilash | Expected gold drop: Same amount as his brother. Yes, both are supposed to drop gold - not just ONE.
- Ouro | Expected gold drop: Roughly 89-105 Gold

### Proof that gold should be otherwise (All from 2006 / Vanilla!)

**Bug Trio**
Full raid of 40. Individual gold gain of 2 gold, 23 silver, 68 copper. (The sum is about 89g total if shared evenly with whole raid!)
[Video proof](https://www.youtube.com/watch?t=528&v=uA4rFph4S7s&feature=youtu.be)

[French] Full raid of 40. Individual gold gain of 1 or, 45 argent, 25 cuivre. Gold, silver, copper. (The sum is about 58g for the raid)
[Video proof](https://www.youtube.com/watch?t=415&v=C3H1Lcq1Gqs&feature=youtu.be)

**Emperor Vek'nilash**

You can see in this video BOTH Emperor's being looted for their gold. Estimated raid size is 40. Vek'lor drops 1 gold, 95 silver, about 79 gold total on his body. Vek'nilash drops 75 gold, 85 silver, 42 copper.
[Video proof](https://youtu.be/aHPOSHqa018?t=526)

Yet another Twin Emperor's kill video here. This one is much higher quality and you can see the gold share in the chat itself, which reads: 1 gold, 93 silver, 51 copper AND 1 gold, 90 silver, 24 copper. Raid size is again a full 40 man, so each Emperor dropped roughly 79 gold each.
[Video proof](https://www.youtube.com/watch?t=367&v=NgmPLus96IQ&feature=youtu.be)

**Ouro**
Unknown raid size. In this video you get to see Ouro's body looted directly. Total gold on its body is 104 gold, 90 silver, 40 copper.
[Video proof](https://youtu.be/hJXUVjlFNqQ?t=581)

**NOTE: ALL PROOF IS FROM 2006 AND NOT CLASSIC.**

### Steps to reproduce

Just kill the bosses on a test server and see for yourself.

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  

OS Client: Windows 10
OS Server: NA

### Crashlog

- None

**Comment by faralynn** [comment]
Whoops. For expected behavior, nevermind the "current gold drop text" I just copy+pasted the bullet list. Everything else is in line though

**Comment by faralynn** [comment]
Is there any data that this bug report is lacking? I can try digging it up should a developer need it.

For further proof this is an issue, here's some of the SQL data for some of the AQ40 bosses.

> INSERT INTO `creature_template` (`entry`, `KillCredit1`, `KillCredit2`, `modelid_1`, `modelid_2`, `modelid_3`, `modelid_4`, `name`, `subname`, `gossip_menu_id`, `minlevel`, `maxlevel`, `minhealth`, `maxhealth`, `minmana`, `maxmana`, `armor`, `faction_A`, `faction_H`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `PetSpellDataId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `Civilian`, `RacialLeader`, `RegenHealth`, `equipment_id`, `trainer_id`, `vendor_id`, `MechanicImmuneMask`, `SchoolImmuneMask`, `flags_extra`, `ScriptName`) VALUES
> (15544, 0,  0,  15658,  0,  0,  0,  'Vem',  '', 0,  63, 63, 430338, 430338, 0,  0,  4691,   14, 14, 0,  4,  2.14286,    0,  3,  2272,   2472,   0,  290,    1,  1250,   1750,   0,  0,  0,  0,  0,  0,  0,  0,  220.81, 320.77, 100,    10, 76, 15544,  0,  0,  0,  15, 15, 15, 15, 15, 18670,  26561,  19128,  26662,  0,  **0,  0,**  '', 0,  3,  0,  0,  1,  0,  0,  0,  617299803,  0,  513,    'boss_vem'),
> (15517, 0,  0,  15509,  0,  0,  0,  'Ouro', '', 0,  63, 63, 1934097,    1934097,    0,  0,  4691,   14, 14, 0,  1,  1.14286,    0,  3,  5293,   6476,   0,  290,    1,  1750,   1750,   0,  0,  0,  0,  0,  0,  0,  0,  220.81, 320.77, 100,    10, 76, 15517,  0,  0,  0,  15, 15, 15, 15, 15, 0,  0,  0,  0,  0,  **0,  0,**  '', 0,  3,  0,  0,  1,  0,  0,  0,  617299803,  0,  769,    'boss_ouro'),
> (15511, 0,  0,  15656,  0,  0,  0,  'Lord Kri', '', 0,  63, 63, 264407, 264407, 0,  0,  4691,   14, 14, 0,  2.4,    2.14286,    0,  3,  2601,   3026,   0,  290,    1,  1100,   1750,   0,  0,  0,  0,  0,  0,  0,  0,  220.81, 320.77, 100,    10, 76, 15511,  0,  0,  0,  15, 15, 15, 15, 15, 0,  0,  0,  0,  0,  **24055,  31418,**  '', 0,  3,  0,  0,  1,  0,  0,  0,  617299803,  0,  513,    'boss_kri'),
> (15543, 0,  0,  15657,  0,  0,  0,  'Princess Yauj',    '', 0,  63, 63, 291329, 291329, 0,  0,  4691,   14, 14, 0,  2.4,    2.14286,    0,  3,  3032,   3426,   0,  290,    1,  1450,   1750,   0,  0,  0,  0,  0,  0,  0,  0,  220.81, 320.77, 100,    10, 76, 15543,  0,  0,  0,  15, 15, 15, 15, 15, 25807,  25808,  3242,   26580,  0,  **28305,  36968,**  '', 0,  3,  0,  0,  1,  0,  0,  0,  617299803,  0,  513,    'boss_yauj'),
> (15275, 0,  0,  15761,  0,  0,  0,  'Emperor Vek\'nilash',  '', 0,  63, 63, 1624014,    1624014,    0,  0,  4691,   14, 14, 0,  1,  1.14286,    0,  3,  3360,   4111,   0,  290,    1,  1500,   1650,   0,  0,  0,  0,  0,  0,  0,  0,  220.81, 320.77, 100,    10, 76, 15275,  0,  0,  0,  15, 15, 15, 15, 15, 26613,  26007,  7393,   27680,  0,  **0,  0,**  '', 0,  3,  0,  0,  1,  1480,   0,  0,  617299803,  0,  769,    'boss_veknilash'),

**Bold text** = the data entries for gold drop, minimum and maximum values. File used as reference: 
https://github.com/vmangos/core/blob/4ba6a87d197242aa5546ddbf438589b23efd9704/sql/old_migrations/20170425172815_world.sql

Vem killed last
![image](https://user-images.githubusercontent.com/2092314/107485065-48a18500-6b51-11eb-842f-d62f447ef466.png)

Princess Yauj killed last
![image](https://user-images.githubusercontent.com/2092314/107485127-61119f80-6b51-11eb-9b91-9d99dc139d0c.png)

Lord Kri killed last
![image](https://user-images.githubusercontent.com/2092314/107485209-771f6000-6b51-11eb-8a30-e46ef713c2e9.png)

**Comment by GrenderG** [comment]
Confirmed.

**Comment by NickTyrer** [comment]
Closed in https://github.com/vmangos/core/commit/37b12caeb9becf4473096b319e1d69a105e2233f
