### ISSUE TITLE
🐛 [Bug] Tanaris mobs inside tent pathing bug.

### ISSUE THREAD

**Issue by jaywalker15262** [vmangos/core#1025]
## 🐛 Bug report

(pathing) Mobs in tanaris who spawns inside the tents will stand stacked inside the tent engaged in combat, unable to chase you & evade attacks. This might be a general pathing bug and not exclusively an issue with just mobs in Tanaris.

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by Gamemechanicwow** [comment]
Is this still a new problem with new mmaps? I couldn't find any mobs that would get stuck.

If it still is. Could you supply a GUID or coords?

**Comment by Gamemechanicwow** [comment]
Nevermind. Found one. This one is still stuck: https://github.com/vmangos/core/issues/439

**Comment by NickTyrer** [comment]
@ratkosrb Can this be closed now?
