### ISSUE TITLE
🐛 [Bug] Ore in Jangelode mine way out of position.

### ISSUE THREAD

**Issue by jaywalker15262** [vmangos/core#1026]
## 🐛 Bug report

bug: in jangolode mine, a piece of ore is detected waaay out of position by the "find minerals" miner ability (you can see one in front of me: it's marked as being at the end of the cave)

[SS](https://imgur.com/a/UmUuQJT) 
### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by NickTyrer** [comment]
Closed in  #1498
