### ISSUE TITLE
🦂 [Bug] Moira Thaurissan dropping loot when she's not suppost to.

### ISSUE THREAD

**Issue by jaywalker15262** [vmangos/core#1027]
## 🦂 Bug report - Dungeon

- moira thaurissan is dropping loot even if no one has finished the questline to deal with her. on classic, you have to finish the quest chain to be eligible for loot. 

- shadowforge dragoons and peasants (?) sometimes start shooting random ranged players with no care for threat whatsoever

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by NickTyrer** [comment]
closed here https://github.com/vmangos/core/commit/0af0ce7616af4c1253b1686a79c88d80db96dfaa
