### ISSUE TITLE
🐛 [Bug] Innkeeper Grosk Wrong Gossip Menu Option

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#1029]
## 🐛 Bug report
He currently has the wrong gossip menu option:
![vman](https://user-images.githubusercontent.com/22723839/106114068-105c7880-6147-11eb-8598-f11f56f0b9c9.png)

### Expected behavior
classic:
![classic](https://user-images.githubusercontent.com/22723839/106114086-16eaf000-6147-11eb-91e1-7ee1aa6cd349.png)

Client Version: 
1.12.1
Commit Hash:  
175258a

**Comment by NickTyrer** [comment]
UPDATE: all of the innkeepers in the starting zones have the wrong gossip menu options. Mosto of them have "tell me about the dungeons I could explore" when they shouldnt.

**Comment by NickTyrer** [comment]
UPDATE: The inkeeper in Goldshire has some weird custom menus when you have GM mode enabled.

**Comment by NickTyrer** [comment]
UPDATE: some innkeepers have these gossip_menu_options:
![1](https://user-images.githubusercontent.com/22723839/106285069-ec2e9380-623b-11eb-934b-b9c753a3c57d.png)
 
Whilst some have:
![2](https://user-images.githubusercontent.com/22723839/106285091-f51f6500-623b-11eb-827a-83ed77e02bd8.png)

Is this correct or are they missing the seasonal entries?

**Comment by ratkosrb** [comment]
> UPDATE: all of the innkeepers in the starting zones have the wrong gossip menu options. Mosto of them have "tell me about the dungeons I could explore" when they shouldnt.

Did you talk to them on a character above level 15? That option only appears when you are high enough to do dungeons. If you are testing the starting zone innkeepers on a level 1 character, then ofc u wont see it.

**Comment by NickTyrer** [comment]
@ratkosrb I tested with a lvl 60, none of the innkeepers in the starting zones had the dungeon menu.

**Comment by NickTyrer** [comment]
> 
> 
> UPDATE: some innkeepers have these gossip_menu_options:
> ![1](https://user-images.githubusercontent.com/22723839/106285069-ec2e9380-623b-11eb-934b-b9c753a3c57d.png)
> 
> Whilst some have:
> ![2](https://user-images.githubusercontent.com/22723839/106285091-f51f6500-623b-11eb-827a-83ed77e02bd8.png)
> 
> Is this correct or are they missing the seasonal entries?

The "Let me browse your seasonal fare" option seems to activate on all innkeepers during Love is in the Air event which is incorrect.

**Comment by ratkosrb** [comment]
I've seen the option in game so i know it exists. Also have it in sniffs for these gossip menus: 343, 5181, 6768

**Comment by NickTyrer** [comment]
Yes, The menu_option "Let me browse your seasonal fare" is active in some gossip menus when events are actve (e.g orgrimmar innkeeper has this option). However when this option is available the option "Let me browse your goods" is removed.
