### ISSUE TITLE
Crashlog world console

### ISSUE THREAD

**Issue by darkmord1991** [vmangos/core#104]
**Current behavior**: 
Creature (Entry: 14393 Guid: 54003) targeted home
Creature (Entry: 14390 Guid: 54001) targeted home
Spell 8873 Effect0 : 2 Targets: Creature (Entry: 14393 Guid: 1246469), -, -
Condition-System: Check condition 458, type -1 - called from EventAI with params target: Creature (Entry: 7395 Guid: 41826), map 0, source Creature (Entry: 8403 Guid: 31804)
Condition-System: Check condition 451, type -2 - called from EventAI with params target: Creature (Entry: 7395 Guid: 41826), map 0, source Creature (Entry: 8403 Guid: 31804)
Condition-System: Check condition 441, type 1 - called from EventAI with params target: Creature (Entry: 7395 Guid: 41826), map 0, source Creature (Entry: 8403 Guid: 31804)
Condition-System: Check condition 442, type 1 - called from EventAI with params target: Creature (Entry: 7395 Guid: 41826), map 0, source Creature (Entry: 8403 Guid: 31804)
WalkHitPos: Start poly not found
CHAT: packet received. type 1, lang 4294967295
RollMeleeOutcomeAgainst: MISS
WORLD: Sending SMSG_ATTACKERSTATEUPDATE
AttackerStateUpdate: (Player) 524 attacked 2165 (TypeId: 3) for 0 dmg, absorbed 0, blocked 0, resisted 0.
RollMeleeOutcomeAgainst: CRUSHING <700, 9200)
WORLD: Sending SMSG_ATTACKERSTATEUPDATE
AttackerStateUpdate: (NPC)    53996 attacked 1246473 (TypeId: 3) for 265 dmg, absorbed 0, blocked 0, resisted 0.
RollMeleeOutcomeAgainst: BLOCK <120, 840)
WORLD: Sending SMSG_ATTACKERSTATEUPDATE
AttackerStateUpdate: (NPC)    53997 attacked 1246471 (TypeId: 3) for 194 dmg, absorbed 0, blocked 20, resisted 0.
get value from nonexistent value field: 0 (count: 0) for object typeid: 1 type mask: 0
C:\Users\Administrator\Desktop\Sources\vmangos\src\game\Objects\Object.h:388: Error: Assertion in Object::GetUInt64Value failed: index + 1 < m_valuesCount || PrintIndexError( index , false)
Object::GetGUIDLow()+0xb [0x159bb]
Creature::canStartAttack()+0x4fee [0x10544e]
Map::RemoveOldBones()+0xb1 [0x115ed1]
Map::Update()+0x41e [0x1190fe]
GetSpellRangeStore()+0x67c1 [0x1b3dd1]
BarGoLink::step()+0xc2f [0x4c186f]
ACE_OS_Thread_Adapter::invoke() c:\ace_wrappers\ace\os_thread_adapter.cpp: 109 + 0x0
o__realloc_base()+0x60 [0x1cd70]
BaseThreadInitThunk()+0x14 [0x8364]
RtlUserThreadStart()+0x21 [0x6e851]
**Expected behavior**: 
Crash, worldserver stopps
**Steps to reproduce**:

dont know what was happening
Players were somewhere in Tanaris
Same happened yesterday, but I had not activated full log in console.
1.  
2. 
3. 

**Client version**: 
1.12.1
**Commit hash**: 
Core revision: ab298bd7763eb3e39262 / 2019-01-01 19:55:13 +0200 / Win64 (little-endian)
**Operating system**: 
Win Server 2016

**Comment by mpfans** [comment]
It is recommended to upgrade to the latest edition and try again.

**Comment by darkmord1991** [comment]
Never happened again with Core revision: 39ec7426030aaf6ecdce / 2019-01-08 18:36:37 +0200 / Win64 (little-endian) [realm-daemon]
