### ISSUE TITLE
🦂 [Bug] Naxxramas: Razuvious resets at the bottom of the stairs

### ISSUE THREAD

**Issue by insunaa** [vmangos/core#1044]
## 🦂 Bug report - Naxxramas

Razuvious resets at the bottom of the stairs towards the stables.

### Expected behavior

He should reset at the half-way point/platform instead as seen here:
https://www.youtube.com/watch?v=JAaxF_U-7Qk

https://github.com/vmangos/core/blob/9dba4ccf31b076f48163d792c5b0b4f623acf79c/src/scripts/eastern_kingdoms/eastern_plaguelands/naxxramas/instance_naxxramas.cpp#L155
=> 275.0f should be 285.0f

### Steps to reproduce

1. Aggro Razuvious
2. Pull him towards the stairs
3. Hope he doesn't kill you on the way
4. ...
5. Profit

### Version & Environment

Client Version: Probably 1.12.1.5875, I don't actually have VMaNGOS running, this is just from the code alone.

Commit Hash:  N/A

OS Client: N/A
OS Server: N/A

**Comment by ulfgebhardt** [comment]
Could you make a PR for this @insunaa <3

**Comment by insunaa** [comment]
Done.
Please test it yourself, @ulfgebhardt as I don't have a 1.12 client to test this with, currently.

**Comment by ulfgebhardt** [comment]
Thank you @insunaa <3
