### ISSUE TITLE
🐛 [Bug] creating a character consumes 2 guids for each default item

### ISSUE THREAD

**Issue by schell244** [vmangos/core#1054]
## 🐛 Bug report
Creating a new character consumes 2 guids at `item_instance` for each default item. 

### Expected behavior
each item should only consume 1 guid

### Steps to reproduce
1. clear character db 
2. create new character
3. check guid counter at `item_instance`
4. instead of 1,2,3... the guid's are 2,4,6,8,....

<img width="442" alt="guid" src="https://user-images.githubusercontent.com/9536270/107232449-b484d000-6a21-11eb-90f7-d0f557ae3cc0.PNG">

Commit Hash:  
efd51cc

**Comment by ratkosrb** [comment]
The folks at trinitycore found why this happens:
![Untitled](https://user-images.githubusercontent.com/35845488/107887301-bfea6680-6f0d-11eb-9581-8372e79a9599.jpg)

**Comment by mserajnik** [comment]
~~`Player::CanEquipNewItem()` and `Player::EquipNewItem()` don't do much besides creating an item and then calling `Player::CanEquipItem()` and `Player::EquipItem()` respectively.~~

~~Maybe I'm missing something obvious, but is there a reason why we can't just create the item beforehand and then use `Player::CanEquipItem()` and `Player::EquipItem()` directly instead?~~

~~Something like this (compiles, but untested): https://github.com/vmangos/core/commit/5185d749bbcac64df12f74d4dcfc186fd21f65da?diff=unified&w=1~~

__Edit:__ Aaaand he fixed it 😄
