### ISSUE TITLE
🐛 [Bug] Incorrect damage stats for two Winterfall Furbolgs

### ISSUE THREAD

**Issue by ulfgebhardt** [vmangos/core#1056]
## 🐛 Bug report

Current behavior:
The damage stats for Winterfall Ursa and High Chief Winterfall are incorrect.

Expected behavior:
see https://github.com/cmangos/classic-db/commit/84c51311be881c44c186c0bf610e74f91e2bc1c4

Client version:
1.12.1
Commit hash:
ea0f0ee
Operating system:
Win 10

[This PR](https://github.com/vmangos/core/issues/669) was closed by @mikemenasi when its unclear why

**Comment by NickTyrer** [comment]
Closed in #1467
