### ISSUE TITLE
🐞 [Bug] Shadowform cancel and GCD

### ISSUE THREAD

**Issue by CosminPOP** [vmangos/core#1064]
## 🐞 Bug report - Spell
Cancelling Shadowform triggers gcd.

### Expected behavior
Should not trigger gcd.

### Steps to reproduce

1. Cast Shadowform
2. Cast Shadowform again, or rightclick the Shadowform buff

### Steps to reproduce - to not trigger gcd
1. Cast Shadowform
2. Logout
3. Login
4. Cancel Shadowform

### Version & Environment
  Client Version:
  - 1.12.1.5875

**Comment by Daribon** [comment]
source?

**Comment by Gamemechanicwow** [comment]
I do believe it should trigger GCD and is working as intended. 

https://youtu.be/sALZHCmAMVo?t=1423
https://youtu.be/L0OOMntF01Y?t=173
https://youtu.be/AcdjrFuleMo?t=300
https://youtu.be/LbnTgXYJj7Q?t=491

**Comment by CosminPOP** [comment]
Some videos from **classic** show that it doesnt trigger

https://youtu.be/AK6RVibj_sU?t=261 - renew out of shadow form
https://youtu.be/DBFMaz0UCTk?t=34 - flash heal out of shadow form
https://youtu.be/9D_m8zOZejs?t=620 - no gcd animation on spells

**Comment by NickTyrer** [comment]
Confirmed
Classic: https://youtu.be/kLUbR9pXSc8

vMangos: https://youtu.be/sEJXxD_KYjA

**Comment by CosminPOP** [comment]
> vMangos: https://youtu.be/sEJXxD_KYjA

I'm not sure if the behaviour is still active in vMangos but you could get no gcd on shadow form fade **once** after you loged in with shadowform is active.

**Comment by NickTyrer** [comment]
This works correctly when using the new client, so I guess this is a client issue?

**Comment by Zebouski** [comment]
Nick is right. I tested on the latest vmangos dev branch with both the 1.12.1 client and the 1.14.0 client + hermesproxy. It's a classic clientside bug that went unfixed through the entirety of classic. 

https://www.youtube.com/watch?v=MyWNW40a5IA

A shame, I really enjoyed how this bug buffed pvp spriest by a bit.

But yeah, i've come to the conclusion from the 2006 footage confirming the 1.12 client behavior, this is not a vmangos bug and I think this issue can be closed.
