### ISSUE TITLE
[Event] Missing Training Event in Bloodhoof Village - Mulgore

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#1069]
See: https://github.com/cmangos/classic-db/commit/2d7071b6e842a188bb491d0466ace9e497937593

Client Version: 1.12.1
Commit Hash:  088d004

**Comment by offl** [comment]
SAI version https://github.com/TrinityCore/TrinityCore/issues/24847

**Comment by NickTyrer** [comment]
closed in https://github.com/vmangos/core/pull/1101
