### ISSUE TITLE
Servent of Grol is immortal🐛 [Bug]

### ISSUE THREAD

**Issue by tonymmm1** [vmangos/core#1072]
## 🐛 Bug report

NPC is protected and is unable to die. Dreadmaul Hold, Blasted Lands. 

![screenshot_2021-02-18_18-14-46](https://user-images.githubusercontent.com/20303853/108438840-b286f200-7215-11eb-9959-70824e9f4c3e.png)

### Expected behavior

Should be able to be killed like regular npc. 

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  https://github.com/vmangos/core/commit/4ee22bb33fb8dd4868f96f8001a4ac441e62aa1b

OS Client:  Fedora 32 under wine 4.6
OS Server:  CentOS 7

**Comment by tonymmm1** [comment]
https://classic.wowhead.com/npc=7669/servant-of-grol

**Comment by Velite12** [comment]
Are you doing the quest and using the item to make him killable? 

to quote wowwiki:
The cannot be killed by normal means, to kill them you'll have to damage them down to about 5% of their hp, and then click the crystal near them (this can only be done if you have accepted the quest - N [57] The Stones That Bind Us).

**Comment by tonymmm1** [comment]
I was just killing the ogres if that is the case then I will retract this issue.

**Comment by Velite12** [comment]
Yeah they have the unique property of being the only target dummies in vanilla

**Comment by tonymmm1** [comment]
Ok I will be closing this issue now.
