### ISSUE TITLE
🐞 [Bug] Grim Reach does not increase range of Drain Soul despite being affliction spell.

### ISSUE THREAD

**Issue by jaywalker15262** [vmangos/core#1073]
### Expected behavior

Guess they got all spells but missed Drain Soul. Here is the new mask:
`UPDATE `spell_affect` SET `SpellFamilyMask` = '6447547418' WHERE (`entry` = '18218') and (`effectId` = '0');
UPDATE `spell_affect` SET `SpellFamilyMask` = '6447547418' WHERE (`entry` = '18219') and (`effectId` = '0');`

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by ulfgebhardt** [comment]
Can you make a PR for your changes pretty please? @jaywalker15262

**Comment by GrenderG** [comment]
Full list of affected spells can be checked [here](https://classic.wowhead.com/spell=18219/grim-reach), just in case we are missing any other one.

**Comment by jaywalker15262** [comment]
> Can you make a PR for your changes pretty please? @jaywalker15262

I dunno how they do PR's for sql stuff. I'm not familiar with it.

**Comment by NickTyrer** [comment]
This is the guide I used when I started https://github.com/vmangos/wiki/wiki/Contribution-guide.

**Comment by NickTyrer** [comment]
closed here https://github.com/vmangos/core/pull/1097

**Comment by Daribon** [comment]
Can confirm that grim reach should affect drain soul on classic.
