### ISSUE TITLE
🐛 Missing rare creature : Trigore the Lasher

### ISSUE THREAD

**Issue by T1ti** [vmangos/core#1082]
## 🐛 Bug report
Trigore the Lasher deosn't have a spawn point

### Expected behavior
He should spawn in the pool next to the wailing caverns entrance portal
https://classic.wowhead.com/npc=3652/trigore-the-lasher#comments
https://www.wowhead.com/npc=3652/trigore-the-lasher
His respawn should be about 24 hours
![image](https://user-images.githubusercontent.com/40864460/108652060-7bd60380-74c3-11eb-910d-f78f035be3cf.png)

### Steps to reproduce
1. .tele wailing caverns and check the pool.

### Version & Environment

  Client Version:
  - 1.12.1.5875

**Comment by NickTyrer** [comment]
closed in #1036
