### ISSUE TITLE
🐛 Rare elite Veyzhak the Cannibal is missing abilities

### ISSUE THREAD

**Issue by T1ti** [vmangos/core#1086]
## 🐛 Bug report
[Veyzhak the cannibal](https://classic.wowhead.com/npc=5399/veyzhak-the-cannibal) currently doesn't have any ability

### Expected behavior
He should have an enrage and rend https://classic.wowhead.com/npc=5399/veyzhak-the-cannibal#abilities
![image](https://user-images.githubusercontent.com/40864460/108781708-9911dd00-756a-11eb-9ee3-58a6e85db19e.png)
![image](https://user-images.githubusercontent.com/40864460/108783261-7208da80-756d-11eb-8897-8697ef10a045.png)

### Version & Environment

  Client Version:
  - 1.12.1.5875

Client Version: 

  Commit Hash:
03a2e108babd7d6049ae1da431e8fe8420d91476

**Comment by NickTyrer** [comment]
closed in #1280
