### ISSUE TITLE
🐛 rare creature Zekkis has wrong abilities

### ISSUE THREAD

**Issue by T1ti** [vmangos/core#1087]
## 🐛 Bug report
He currently has those two abilities 
![image](https://user-images.githubusercontent.com/40864460/108783426-c2803800-756d-11eb-89ed-9e88dce0872a.png)
https://classic.wowhead.com/spell=7102/contagion-of-rot
and https://classic.wowhead.com/spell=10893/shadow-word-pain

### Expected behavior
![image](https://user-images.githubusercontent.com/40864460/108783652-2440a200-756e-11eb-844c-9a3f0c12d920.png)
https://classic.wowhead.com/npc=5400/zekkis#abilities

https://classic.wowhead.com/spell=7102/contagion-of-rot is correct but the shadow word pain spell should be repalced by a curse of blood spell.
 Not sure which ID, I couldn't find one that increases by 24 like in the book, but azeroth core uses this one Id : 8282 . perhaps it's bugged.
Also it uses generic spell_ai which is pretty much spam on cd, consider updating to a timed spells list.

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by NickTyrer** [comment]
closed in #1197
