### ISSUE TITLE
"A Strange Fruit" Quest (Teldrassil) incorrect mobs spawn 🐝 [Bug]

### ISSUE THREAD

**Issue by Pmt112** [vmangos/core#1089]
Hi,
A Strange Fruit quest in Teldrassil has you collect a fruit item from a tree with a purple glow and return it to the botanist NPC by the lake near Dolanaar. When you give him that fruit he will plant it in his garden to test it and this will spawn a few boglings which attack the player. The only problem is that these boglings are of a incorrect type currently as far as I know : they are big instead of small, and deal big damage instead of small damage, making them way too strong at that quest level : they will most definitely kill the player with little or no chance to run away if he didn't predict the spawn.

The normal behavior should be afaik : the boglings are small like about a third of a character's height, and they are quite killable by a level 8~ character even though there are about 3 of them, because they don't have a lot of hp or damage. I think they even get killed by thorns aura alone (?). It's possible their level should be lower too. 

This is their classicdb entry https://classicdb.ch/?npc=3569
I suppose you could just check their stats against this they should be level 5 and deal 22-23 damage and have 48hp. I believe they should also be small size if I remember correctly.

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by NickTyrer** [comment]
Closed in #1467
