### ISSUE TITLE
Bazil Thredd - Aggro texts

### ISSUE THREAD

**Issue by alexkulya** [vmangos/core#109]
Bazil Thredd - Add missing aggro texts, remove dublicate texts
[TC Commit](https://github.com/TrinityCore/TrinityCore/commit/6abdd57a61987eaaaff35c4db882f72663748885)

<pre>
DELETE FROM `creature_ai_scripts` WHERE `id` IN (171622, 171624);
INSERT INTO `creature_ai_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `target_param1`, `target_param2`, `target_type`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `condition_id`, `comments`) VALUES
(171622, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 964, 1391, 1394, 1386, 0, 0, 0, 0, 0, 'Bazil Thredd - Say Text'),
(171624, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1387, 1388, 1392, 0, 0, 0, 0, 0, 0, 'Bazil Thredd - Say Text');
</pre>

**Comment by ratkosrb** [comment]
You appear to have left the wrong text id 964 that was removed in the trinity commit..

**Comment by alexkulya** [comment]
Sorry. My bad.
