### ISSUE TITLE
🐝 [Bug]

### ISSUE THREAD

**Issue by nonameform** [vmangos/core#1092]
## 🐝 Bug report - Quest
I am using pfQuest addon which is powered by VMaNGOS database and I have noticed that some quests in the database (and at classicdb.ch) have wrong IDs compared to the ones that were on Thottbot.

The quests in question are Beached Sea Creature/Beached Sea Turtle found at Darkshore. There are nine quests in total and only one quest actually has proper ID: 4722 ([classicdb](https://classicdb.ch/?quest=4722), (https://web.archive.org/web/20071116171221/http://thottbot.com/q4722)) - 37,62.

### Expected behavior
The other eight quests are all mixed up (there is a comment by Thortok2000 at Thottbot for each quest with coordinates):

4723
[classicdb](https://classicdb.ch/?quest=4723) - 36,70 (4728 location)
[thottbot](https://web.archive.org/web/20071116171221/http://thottbot.com/q4723) - 41,31

4725
[classicdb](https://classicdb.ch/?quest=4725) - 32,80 (4730 location)
[thottbot](https://web.archive.org/web/20071116171221/http://thottbot.com/q4725) - 44,20

4727
[classicdb](https://classicdb.ch/?quest=4725) - 31,83 (4731 location)
[thottbot](https://web.archive.org/web/20071116171221/http://thottbot.com/q4727) - 53,18

4728
[classicdb](https://classicdb.ch/?quest=4728) - 31,85 (4732 location)
[thottbot](https://web.archive.org/web/20071116171221/http://thottbot.com/q4728) - 36,70

4730
[classicdb](https://classicdb.ch/?quest=4730) - 31,87 (4733 location)
[thottbot](https://web.archive.org/web/20071116171221/http://thottbot.com/q4730) - 32,80

4731
[classicdb](https://classicdb.ch/?quest=4731) - 41,31 (4723 location)
[thottbot](https://web.archive.org/web/20071116171221/http://thottbot.com/q4731) - 31,83

4732
[classicdb](https://classicdb.ch/?quest=4732) - 44,20 (4725 location)
[thottbot](https://web.archive.org/web/20071116171221/http://thottbot.com/q4732) - 31,85

4733
[classicdb](https://classicdb.ch/?quest=4733) - 53,18 (4727 location)
[thottbot](https://web.archive.org/web/20071116171221/http://thottbot.com/q4733) - 31,87

### Version & Environment
Client Version: 1.12.1.5875
OS Client: Win 10
OS Server: ???

### Crashlog
- None

**Comment by NickTyrer** [comment]
The quest order are correct in the DB in accordance with https://classic.wowhead.com/quest=3524/washed-ashore

**Comment by nonameform** [comment]
Sorry, I have used completely wrong wording and I have no idea how that happened. Instead of ID I meant to write coordinates.

So what I actually meant: quests in VMaNGOS (from what I can tell by looking at classicdb.ch) have wrong coordinates. Thottbot has right coordinates and classic.wowhead.com has the right coordinates as well. The only quest that has proper coordinates is 4722 and the other eight are mixed up.

**Comment by NickTyrer** [comment]
They all seem correct to me. For example this quest https://classic.wowhead.com/quest=4723/beached-sea-creature if you go to the coords and get the gameobject using '.gobject near' then check the database using 'SELECT * FROM gameobject_questrelation WHERE id = 175233' you will see that it is linked to the correct quest, as are all the rest.
