### ISSUE TITLE
🐝 [Bug] Guardians of the Altar

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#1102]
## 🐝 Bug report - Quest
You are no longer able to interact with the Altar of Elune (49182, 177404) at the end of the quest. This only happens on the second run of the quest because from what I can see this flag is not reset:

pGo->RemoveFlag(GAMEOBJECT_FLAGS, GO_FLAG_INTERACT_COND);

Also the NPC escortee seems to spin around a lot when you are in combat, here is a video for ref https://youtu.be/M9p3lglIlyE

Client Version: 1.12.1

 Commit Hash:d8f60ba

**Comment by NickTyrer** [comment]
This issue seems related https://github.com/the-hyjal-project/bugtracker/issues/416

**Comment by ratkosrb** [comment]
It is not related to another script. I plan on re-scripting this quest in DB.
