### ISSUE TITLE
🐞 [Bug] Doomguard's Rain of Fire

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#1103]
## 🐞 Bug report - Spell
You cannot cast his rain of fire ability when enslaved. Also ritual of doom does not sacrifice a player.

### Expected behavior
He should behave as a normal pet and be able to cast rain of fire

Client Version: 1.12.1

Commit Hash: d8f60ba

**Comment by ratkosrb** [comment]
Can you provide a video from classic?

**Comment by NickTyrer** [comment]
Here is a video of him being healed and buffed https://youtu.be/M9XSMrKUrP0

**Comment by NickTyrer** [comment]
@ratkosrb I cant find a video of him casting rain of fire, however all his other abilities work. Is there a reason why rain of fire should not work? also wowhead does mention the spell as one of his abilities https://classic.wowhead.com/guides/wow-classic-warlock-demon-pets

**Comment by Daribon** [comment]
I tested in classic after summoning a Doomguard from Curse of Doom.
Can confirm, Doomguards are able to cast Rain of Fire in classic.
![WowClassicT_pHqouI1PNa](https://user-images.githubusercontent.com/6137576/111040076-bf23f200-8431-11eb-9c89-5d2b36ff0de5.png)
![WowClassicT_qJVL2g3eIL](https://user-images.githubusercontent.com/6137576/111040078-c3e8a600-8431-11eb-8336-b05e9bf739e8.png)
