### ISSUE TITLE
🐛 [Bug] [Unix] Pathfinding of NPCs etc. not working. Units stuck, no aggroing of mobs. [Can be closed]

### ISSUE THREAD

**Issue by radiix** [vmangos/core#1112]
NPCs, mobs etc. stuck. No movement at all. No aggroing. Seems like the pathfinding is broken.
Using latest vmaps/mmaps after unix fix. I tried to disable them all, but still the same issue.
Using completely clean mangosd.conf.

### Expected behavior
Run upto mob and get aggroed.

### Steps to reproduce

1. Build latest commit
2. run up to mobs
3. Profit

### Version & Environment

  Client Version:
  - 1.12.1.5875

Commit Hash:  https://github.com/vmangos/core/commit/2ecd2979d2a9425e7b4233cde9588a7d901cac1f
![InstantGif_2021 03 10-03 30](https://user-images.githubusercontent.com/7096803/110567374-b097bb00-8151-11eb-9c05-397e99029092.gif)

OS Client:  W10x64
OS Server: Debian 10 x64

**Comment by ratkosrb** [comment]
I cannot reproduce the issue.

**Comment by radiix** [comment]
> I cannot reproduce the issue.

Issue can be closed. The error was on my end. I screwed up something in mangosd.conf. Used a clean mangosd.conf and it works again.
