### ISSUE TITLE
🐜 Load older set bonuses with older patch

### ISSUE THREAD

**Issue by T1ti** [vmangos/core#1116]
## 🐜 Bug report - Progression
The items stats change if you select the older patches, BUT the set effects don't change

### Expected behavior
We need a new table in the database to change the tier set spell based on which patch is selected. Most sets got changed in patch 1.4
Example of an older set bonus : 
https://web.archive.org/web/20050207013827/http://wow.allakhazam.com/db/itemset.html?setid=208
Those older set effects should most still be unchanged in 1.12, like this one which was the old T2 https://classicdb.ch/?spell=21882

### Steps to reproduce

1. compare set effects to archives like https://web.archive.org/web/20050207013120/http://wow.allakhazam.com/db/itemset.html?setid=207

### Version & Environment

Client Version: 
Below 1.12

Commit Hash:  
afb56896e9d757ed6c5ebc6f925023fb956a412b

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by ratkosrb** [comment]
So you want to have a mismatch between what you see on the screen, and what the bonuses actually are? You know the set bonuses are read from ItemSet.dbc right? If people are playing using the 1.12 client, but the server is using the 1.6 dbc file, **everyone will still see the 1.12 set bonuses** listed on the item, and you will have a mismatch between what the item tooltip says, and what bonuses you are actually getting.

Anything that introduced a mismatch between tooltips visible in game, and what things actually do server side is a non-starter. This is the same reason we cannot do spell and talent progression in 1.12 client. These things are part of the client data, and thus we tie them to client progression, as we have no way of changing what the client sees.

If you want set bonus progression, then just play with a client that's on the appropriate patch, and all will be as it should be. This is not a missing feature.

**Comment by T1ti** [comment]
I might be wrong but doesn't the DBC just define which spell ID appears on the items tooltip ? Just replace which spell u choose the set to use server side
If that spell ID is still there on 1.12 then it should work ?

**Comment by ratkosrb** [comment]
And how will you make the old spell ids assigned to the item set appear on the tooltip in the 1.12 client?

Do you see item set spells being send individually here?
https://github.com/vmangos/core/blob/development/src/game/Handlers/ItemHandler.cpp#L296

No you don't, the server sends just the Item Set Id, and the client will load and display spells for that item set from ItemSet.dbc. That is the whole point of having the data be in a DBC file, the server does not have to send it, it just has to say which row from the dbc to load.
