### ISSUE TITLE
Rok'Alim the Pounder Movement

### ISSUE THREAD

**Issue by alexkulya** [vmangos/core#113]
Rok'Alim the Pounder - Add Waypoints
Credits - cmangos

<pre>
UPDATE `creature` SET `spawndist` = 0, `MovementType` = 2, `position_x` = -5204.92, `position_y` = -1565.98, `position_z` = -48.1972 WHERE `guid` = 21591;
DELETE FROM `creature_movement` WHERE `id` = 21591;
INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`) VALUES
(21591, 1, -5204.92, -1565.98, -48.1972),
(21591, 2, -5214.62, -1555.88, -49.2243),
(21591, 3, -5230.7, -1546.65, -49.3283),
(21591, 4, -5241.37, -1540.68, -50.6353),
(21591, 5, -5257.24, -1534.29, -51.2466),
(21591, 6, -5269.84, -1529.99, -52.025),
(21591, 7, -5282.4, -1525.82, -53.1763),
(21591, 8, -5288.3, -1522.98, -56.4051),
(21591, 9, -5286.83, -1503.93, -56.481),
(21591, 10, -5270.15, -1482.05, -56.3993),
(21591, 11, -5254.26, -1461.2, -56.0616),
(21591, 12, -5241.19, -1442.79, -55.4567),
(21591, 13, -5221.53, -1416.03, -53.8072),
(21591, 14, -5198.85, -1395.52, -52.7577),
(21591, 15, -5181.67, -1374.63, -51.8565),
(21591, 16, -5169.68, -1349.39, -50.6463),
(21591, 17, -5154.09, -1328.35, -49.6798),
(21591, 18, -5133.36, -1309.61, -49.4684),
(21591, 19, -5128.83, -1305.52, -49.5074),
(21591, 20, -5116.85, -1280.28, -49.9129),
(21591, 21, -5102.61, -1250.27, -49.9234),
(21591, 22, -5092.12, -1228.17, -52.6244),
(21591, 23, -5069.58, -1197.09, -55.3233),
(21591, 24, -5062.96, -1184.76, -56.1412),
(21591, 25, -5039.98, -1165.97, -56.9965),
(21591, 26, -5016.58, -1158.92, -55.1305),
(21591, 27, -5006.19, -1139.71, -52.2228),
(21591, 28, -4991.9, -1125.57, -50.647),
(21591, 29, -4960.86, -1102.84, -52.0625),
(21591, 30, -4946.76, -1092.52, -52.4456),
(21591, 31, -4928.1, -1087.96, -53.0811),
(21591, 32, -4911.55, -1088.84, -54.6845),
(21591, 33, -4892.69, -1085.17, -58.7394),
(21591, 34, -4862.62, -1069.22, -58.5493),
(21591, 35, -4841.79, -1058.18, -58.3265),
(21591, 36, -4832.77, -1054.99, -58.5381),
(21591, 37, -4810.17, -1040.02, -58.7495),
(21591, 38, -4781.03, -1020.73, -58.7479),
(21591, 39, -4763.55, -1010.94, -58.3438),
(21591, 40, -4745.84, -1003.38, -58.7489),
(21591, 41, -4731.81, -989.059, -56.4676),
(21591, 42, -4718.22, -969.831, -52.847),
(21591, 43, -4702.23, -952.577, -50.7703),
(21591, 44, -4687.36, -943.465, -49.807),
(21591, 45, -4676.14, -938.654, -49.1061),
(21591, 46, -4664.32, -929.672, -50.7595),
(21591, 47, -4638.64, -916.618, -56.6334),
(21591, 48, -4625.96, -902.198, -54.0504),
(21591, 49, -4617.08, -882.245, -51.521),
(21591, 50, -4597.35, -850.377, -53.6356),
(21591, 51, -4579.89, -855.902, -52.0292),
(21591, 52, -4589.98, -867.978, -52.0226),
(21591, 53, -4601.74, -889.439, -50.6814),
(21591, 54, -4605.17, -901.682, -52.4203),
(21591, 55, -4610.44, -918.339, -57.6121),
(21591, 56, -4606.58, -931.714, -56.7672),
(21591, 57, -4596.94, -945.123, -52.9157),
(21591, 58, -4581.9, -955.52, -50.9032),
(21591, 59, -4572.11, -966.669, -49.0426),
(21591, 60, -4560.31, -987.143, -54.2615),
(21591, 61, -4541.68, -1003.01, -54.449),
(21591, 62, -4552.6, -1011.68, -55.3938),
(21591, 63, -4553.95, -1015.83, -55.5415),
(21591, 64, -4551.73, -1033.16, -56.3598),
(21591, 65, -4554.74, -1051.2, -55.7008),
(21591, 66, -4576.43, -1062.38, -52.3882),
(21591, 67, -4595.78, -1072.35, -47.8427),
(21591, 68, -4614.09, -1084.25, -50.2251),
(21591, 69, -4635.17, -1096.57, -53.1295),
(21591, 70, -4655.15, -1116.11, -54.7833),
(21591, 71, -4670.11, -1111.43, -52.6073),
(21591, 72, -4696.82, -1098.49, -52.938),
(21591, 73, -4708.96, -1097.21, -54.7856),
(21591, 74, -4727.26, -1112.01, -50.8514),
(21591, 75, -4730.2, -1135.72, -42.7862),
(21591, 76, -4734.1, -1146.39, -39.9821),
(21591, 77, -4742.57, -1153.98, -39.8057),
(21591, 78, -4748.47, -1163.7, -41.1494),
(21591, 79, -4753.23, -1182.36, -46.3681),
(21591, 80, -4754.96, -1211.99, -53.963),
(21591, 81, -4745.96, -1249.27, -54.0574),
(21591, 82, -4746.93, -1265.88, -52.9851),
(21591, 83, -4754.48, -1290.02, -48.5838),
(21591, 84, -4764.33, -1304.45, -48.6753),
(21591, 85, -4769.15, -1327.53, -49.0466),
(21591, 86, -4775, -1341.23, -53.1682),
(21591, 87, -4778.21, -1369.85, -53.8389),
(21591, 88, -4786.3, -1377.76, -53.4634),
(21591, 89, -4804.32, -1371.1, -54.4526),
(21591, 90, -4830.07, -1375.97, -53.9953),
(21591, 91, -4863.88, -1412.53, -52.4747),
(21591, 92, -4876.27, -1423.62, -50.5087),
(21591, 93, -4883.91, -1453.15, -50.5943),
(21591, 94, -4875.09, -1489.66, -47.697),
(21591, 95, -4868.9, -1500.25, -47.3607),
(21591, 96, -4864.04, -1520.62, -47.5608),
(21591, 97, -4840.64, -1540.3, -47.1878),
(21591, 98, -4813.21, -1563.37, -49.0607),
(21591, 99, -4798.37, -1586.05, -51.2704),
(21591, 100, -4797.3, -1611.32, -49.8867),
(21591, 101, -4802.75, -1637.81, -49.9839),
(21591, 102, -4811.28, -1665.36, -50.9323),
(21591, 103, -4829.82, -1672.43, -47.6692),
(21591, 104, -4850.17, -1677.41, -38.4677),
(21591, 105, -4868.01, -1681.78, -33.1823),
(21591, 106, -4885.85, -1686.15, -35.8888),
(21591, 107, -4907.88, -1691.54, -45.483),
(21591, 108, -4922.81, -1704.92, -53.1108),
(21591, 109, -4937.51, -1726.61, -57.509),
(21591, 110, -4969.21, -1749.86, -60.1434),
(21591, 111, -4994.72, -1763.31, -64.3609),
(21591, 112, -5028.79, -1764.86, -65.5336),
(21591, 113, -5065.95, -1759.59, -66.5919),
(21591, 114, -5093.52, -1770.39, -62.2996),
(21591, 115, -5105.65, -1775.34, -61.0208),
(21591, 116, -5123.93, -1792.82, -57.2378),
(21591, 117, -5149.56, -1806.05, -57.8151),
(21591, 118, -5173.42, -1831.56, -58.1518),
(21591, 119, -5186.01, -1870.63, -57.7254),
(21591, 120, -5197.27, -1905.54, -57.034),
(21591, 121, -5211.94, -1929.84, -62.5757),
(21591, 122, -5217.61, -1963.41, -63.2077),
(21591, 123, -5213.49, -1995.46, -61.1058),
(21591, 124, -5224.94, -2025.67, -60.3056),
(21591, 125, -5267.7, -2047.58, -61.7613),
(21591, 126, -5298.28, -2054.79, -60.6321),
(21591, 127, -5335.13, -2041.09, -61.2567),
(21591, 128, -5370.89, -2042.4, -62.2819),
(21591, 129, -5404.02, -2043.62, -63.9917),
(21591, 130, -5427.96, -2038.56, -64.7203),
(21591, 131, -5443.81, -2022.38, -63.5722),
(21591, 132, -5460.12, -1994.54, -58.3875),
(21591, 133, -5478.17, -1979.38, -58.9688),
(21591, 134, -5501.73, -1950.11, -60.4141),
(21591, 135, -5524.73, -1937.53, -59.9879),
(21591, 136, -5533.82, -1917.68, -59.0687),
(21591, 137, -5530.9, -1890.73, -58.5037),
(21591, 138, -5520.29, -1865.83, -57.9582),
(21591, 139, -5516.68, -1848.78, -57.2414),
(21591, 140, -5506.58, -1830.44, -56.6996),
(21591, 141, -5491.7, -1830.59, -56.4063),
(21591, 142, -5470.03, -1839.83, -54.3328),
(21591, 143, -5457.09, -1829.48, -50.7656),
(21591, 144, -5463.51, -1817.04, -48.0715),
(21591, 145, -5481.32, -1806.02, -49.6301),
(21591, 146, -5483.3, -1791.35, -45.245),
(21591, 147, -5480.45, -1769.64, -33.9141),
(21591, 148, -5475.24, -1759.54, -25.6579),
(21591, 149, -5471.3, -1747.98, -19.724),
(21591, 150, -5469.04, -1741.36, -17.7276),
(21591, 151, -5465.97, -1728.89, -21.8808),
(21591, 152, -5452.89, -1712.47, -31.4806),
(21591, 153, -5438.73, -1694.68, -39.2293),
(21591, 154, -5415, -1665.24, -52.9235),
(21591, 155, -5404.21, -1650.38, -54.0433),
(21591, 156, -5382.14, -1619.96, -55.4564),
(21591, 157, -5359.21, -1581.86, -54.3701),
(21591, 158, -5335.16, -1551.91, -54.5505),
(21591, 159, -5307.35, -1526.65, -56.18),
(21591, 160, -5277.19, -1490.33, -56.4778),
(21591, 161, -5254.46, -1467.41, -56.1179),
(21591, 162, -5234.6, -1435.62, -54.6556),
(21591, 163, -5208.81, -1408.3, -52.7023),
(21591, 164, -5186.86, -1376.82, -52.0997),
(21591, 165, -5161.9, -1341.03, -50.2505),
(21591, 166, -5111.66, -1355.74, -50.9843),
(21591, 167, -5094.4, -1380.98, -51.8489),
(21591, 168, -5073.89, -1397.17, -52.37),
(21591, 169, -5064.51, -1427.11, -52.3102),
(21591, 170, -5052.49, -1465.43, -50.1334),
(21591, 171, -5033.77, -1492.85, -49.7627),
(21591, 172, -5044.56, -1524.25, -48.7018),
(21591, 173, -5066.05, -1540.68, -48.0147),
(21591, 174, -5084.74, -1554.96, -47.1104),
(21591, 175, -5105.14, -1565.01, -46.4026),
(21591, 176, -5129.66, -1571.52, -49.5441),
(21591, 177, -5154.97, -1578.25, -54.2102),
(21591, 178, -5181.09, -1576.09, -53.6363);
</pre>

**Comment by ratkosrb** [comment]
This retail wotlk video shows him doing random movement at the position he is currently spawned at.
https://youtu.be/_QI3SbSWQ3M?t=149

**Comment by AnonXS** [comment]
https://www.wowhead.com/npc=4499/rokalim-the-pounder#comments:id=59808:reply=40943

```Actually, he respawns pretty quickly, but has four or five different places where he can spawn.```

the npc might be missing related pooling and additional spawns.
