### ISSUE TITLE
🐛 [Bug] NPC Movement and player interaction

### ISSUE THREAD

**Issue by GrenderG** [vmangos/core#1138]
## 🐛 Bug report
When you interact with a patrolling NPC and stop talking, it will only wait for about 30 seconds before continuing the movement. When you interact with a wandering NPC, it won't stop moving even if the window is still open.

### Expected behavior
(Tested in Classic) Both patrolling and wandering NPCs should stop while you are interacting with them, and remain stopped for 3 exact minutes after the interaction.

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/628ca5e81f0925fc0a10888778498a8404373c6c
