### ISSUE TITLE
🐛 [Bug]MC Garr can respawn infinitely

### ISSUE THREAD

**Issue by gamelgs** [vmangos/core#1139]
### Expected behavior

MC Garr can respawn infinitely
### Steps to reproduce

1.Kill Garr without killing Firestorm
2.Players let Firestorm kill, and Garr respawn at the same time
3.Garr can respawn infinitely
4.Repeat the above steps to get loot infinitely

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  7ae9da2d9e07adf48cabeb341921ba9442c033b6

OS Client: Win 10
OS Server: Win 10

### Crashlog

- None

**Comment by ratkosrb** [comment]
Fixed here - https://github.com/vmangos/core/commit/2642fe0341ea269a1d5de4f7cf50cab02bc0865d
