### ISSUE TITLE
🐞 [Bug] Force Target - Bow

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#1141]
The spell should force the target to bow. Currently it does nothing.

**Comment by GrenderG** [comment]
Where is it used?

**Comment by NickTyrer** [comment]
I am using it in a quest end script https://github.com/vmangos/core/pull/1140

**Comment by NickTyrer** [comment]
It should work like the force salute spell
.cast 6245

**Comment by GrenderG** [comment]
https://github.com/vmangos/core/pull/1143
