### ISSUE TITLE
🚀 [Feature] Batch food/water

### ISSUE THREAD

**Issue by rosen40** [vmangos/core#1148]
🚀 Feature

Seeing as recently batching was implemented for most spells, i'd like to report that food and water should be batched too and it makes a big difference, which is why i am requesting it.

On Classic food, water and regular mana/health ticks all are batched and ALL happen together every 2 seconds ALWAYS. It doesn't matter if you just started eating or drinking 1ms before the next batch, once the batch happens, if you are drinking or eating, you tick for your base regen + the bonus from the food/water. This makes it so you can run at 100% speed and just stop for a fraction of a second to drink every 2 seconds and you receive full regen value. 

On vmangos food/water ticks happen separately from the base regen ticks and they are not batched in anyway and you always need to wait like 2-3 seconds to receive any health from the food/water. 

Expected behavior:
Base health/mana ticks should happen every 2 seconds at the same time and if you are drinking/eating then you should instantly receive the bonus together with the regular tick, you should not have to wait 2-3 seconds to receive hp from your food if you just ticked.

**Comment by GrenderG** [comment]
Was this working like that in original Vanilla? Classic should only be used as a reference when we lack Vanilla data.

**Comment by rosen40** [comment]
I dont think its likely to find a video of a player "abusing" this back then, monitoring your health ticks and sitting to eat just for half a second or less just to get a tick and continue running. 

EDIT: But i guess some info can be inferred just by looking at health ticks on vanilla videos. If they happen together with regular ticks.

**Comment by rosen40** [comment]
It seems like its the same as Classic. +> https://youtu.be/SwLjJH8LXfc?list=PL49Ga_-r7iKkxrbckm9CkUhWzxqrOnw-n&t=2616

 Joana starts receiving bonus health on the very next health regen tick after starting to eat and the ticks happen together, there is only 1 tick every 2 seconds. On vmangos you would have 2 separate unsynchronized ticks and you end up waiting very long sometimes before receiving any health from your food. Its honestly frustrating after having experienced the original regen.
