### ISSUE TITLE
Recipe missing from trainers

### ISSUE THREAD

**Issue by darkmord1991** [vmangos/core#115]
**Current behavior**: 
no https://de.wowhead.com/spell=19788/dichtes-sprengpulver trainable from Engineering trainers

No spell id used in npc_trainers table
**Expected behavior**: 
should be trainable, please add to trainers
I am not sure, what ids the trainers had at this time.
**Steps to reproduce**:

1. 
2. 
3. 

**Client version**: 
1.12.1
**Commit hash**: 
Core revision: 39ec7426030aaf6ecdce / 2019-01-08 18:36:37 +0200 / Win64 (little-endian) [realm-daemon]
**Operating system**: 
Win Server 2016

**Comment by alexkulya** [comment]
This spell teaches [NPC Link](https://classic.wowhead.com/npc=8736/buzzek-bracketswing) (250 Prof. lvl)

**Comment by ratkosrb** [comment]
Invalid report.
![wowscrnshot_011419_042321](https://user-images.githubusercontent.com/35845488/51094275-314a0f00-17b4-11e9-9b5b-374b982085b8.jpg)
