### ISSUE TITLE
🐝 [Bug] The Howling Vale (1022) and The Scythe of Elune quest (1043), wrong NPC position

### ISSUE THREAD

**Issue by GrenderG** [vmangos/core#1152]
## 🐝 Bug report - Quest
~~Velinde Starsong (3946) is spawned in the wrong position during The Howling Vale (1022) quest.~~ https://github.com/vmangos/core/commit/5d9518c1e99bde6ba5b8fa6cc68fb77758f896b7

**EDIT: Her position during The Scythe of Elune quest (1043) is also wrong.** 

### Expected behavior
~~She should be spawned on top of the book:~~
~~https://user-images.githubusercontent.com/8654362/113632989-6c260f00-966c-11eb-8f4b-70de72cbc6f2.png~~
~~https://youtu.be/CObmpfkPHwY?t=949~~

**Comment by ratkosrb** [comment]
I fixed the first part of the issue. I have not done the second quest yet.

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/f1567deab746ff8bfb745296c53923389f5d0066
