### ISSUE TITLE
🐛 [Bug] Missing Brill Zeppelin bat mini-event

### ISSUE THREAD

**Issue by GrenderG** [vmangos/core#1156]
## 🐛 Bug report
There's a mini event happening on top of the roof of Brill's Zeppelin tower involving "[Belfy Bat](https://classic.wowhead.com/npc=10716/)" NPCs that's missing.

> 12 of these bats spawn on top of Brill's clocktower at the same time as the tower's bell starts tolling (every hour at XX:00). The bell startles them, and they fly away, playing sound [BatsInFlight](https://classic.wowhead.com/sound=6596/batsinflight). They fly in the direction of the zeppelin tower, play the sound again mid-path, and land on the roof of that small building at the base of the tower. After most of them land, they play the sound yet again and despawn. Occasionally, due to server lag or lack of players nearby, not all bats might land in time. Those that didn't land will not despawn together with the rest, and will remain on that roof until the next hour, which leads to some players noticing them and wondering why is there a seemingly random number of untargetable bats at different times.

Source: https://classic.wowhead.com/npc=10716/belfry-bat#comments
![image](https://user-images.githubusercontent.com/8654362/114050801-df0dd080-988c-11eb-8ee2-7c0cbca3ec25.png)
![image](https://user-images.githubusercontent.com/8654362/114050871-eaf99280-988c-11eb-8758-37995c71e0e0.png)

**Comment by Kittnz** [comment]
Ill sniff it

**Comment by Kittnz** [comment]
Sniffed it, so they just spawn and a little bit later just despawn. Never noticed this event ^^

**Comment by GrenderG** [comment]
> Sniffed it, so they just spawn and a little bit later just despawn. Never noticed this event ^^

Thanks a lot! I don't think I ever noticed it either even after so many years!
