### ISSUE TITLE
🐝 [Bug] The Curse of the Tides quest

### ISSUE THREAD

**Issue by GrenderG** [vmangos/core#1173]
## 🐝 Bug report - Quest

- Gazban seems to be spawning in the wrong location.
- Gazban seems to be using the wrong faction.
- You can continuously click the Altar making it possible to spawn infinite copies of Gazban.

### Expected behavior
https://www.youtube.com/watch?v=SDIoxfPCaGw

**Comment by LEO33SoFo** [comment]
I confirm this issue, as of 7b83d9952f32559b72f7094e389631f4a30ef7b0.
