### ISSUE TITLE
The program crashed after killing Maws.

### ISSUE THREAD

**Issue by wthslw001** [vmangos/core#118]
**Current behavior**: 
The program crashed after killing Maws.
Quest Name: The Wrath of Neptulon 
Quest ID:8729
Crea ID：15571
Cannot pick up after the kill and cause the game to crash.
**Expected behavior**: 

**Steps to reproduce**:

1.   \core\src\scripts\kalimdor\azshara\azshara.cpp
2. 
3. 

**Client version**: 

**Commit hash**: 

**Operating system**: 
![image](https://user-images.githubusercontent.com/8679316/51126277-b2111580-185d-11e9-9d13-59fd5f2d5c79.png)

**Comment by ghost** [comment]
No crash for me on ubuntu rev f371a194ce9204d35777baf127f181e5469bb6e0

**Comment by wthslw001** [comment]
> No crash for me on ubuntu rev [f371a19](https://github.com/vmangos/core/commit/f371a194ce9204d35777baf127f181e5469bb6e0)

I only used the AQ-SET_GATES_CLOSED.sql patch. Is the program crashing for this reason?

**Comment by ghost** [comment]
I don't know, I didin't apply any custom SQL, only updates

**Comment by DarkmoonRabbit** [comment]
mangosd.exe var:2019-01-04 16:03:26 +0200 / Win64
Test pass

-------------
Please print out the cpu, memory, and system version of your server. . . specification

**Comment by wthslw001** [comment]
> mangosd.exe var:2019-01-04 16:03:26 +0200 / Win64
> Test pass
> 
> Please print out the cpu, memory, and system version of your server. . . specification

I found that the program I compiled with any version will crash. The compiler environment I am using is CMake 3.13.1 + ACE_wrappers6.4.3 +tbb2017 Is there something wrong?

I would like to ask Master to see if there is a problem.Thank you very much.

![image](https://user-images.githubusercontent.com/8679316/51290286-5f428400-1a3e-11e9-84a3-2db381d88ab0.png)
![image](https://user-images.githubusercontent.com/8679316/51290321-71bcbd80-1a3e-11e9-93f6-5302af93cf08.png)
![image](https://user-images.githubusercontent.com/8679316/51290437-d1b36400-1a3e-11e9-864b-fce220a7f35f.png)
![image](https://user-images.githubusercontent.com/8679316/51290469-ec85d880-1a3e-11e9-8ee9-f76033ae14b7.png)
![image](https://user-images.githubusercontent.com/8679316/51290627-366ebe80-1a3f-11e9-83ee-296417963bd2.png)

**Comment by wthslw001** [comment]
There are no changes to the source code and database.
![boss](https://user-images.githubusercontent.com/8679316/51296012-08947480-1a55-11e9-933d-05d4ad719074.gif)

**Comment by ratkosrb** [comment]
Compile in Debug mode instead of Release, and then when it crashes click the Debug button to open it with Visual Studio and see on what line of the code it crashed.

**Comment by DarkmoonRabbit** [comment]
print your wowPatch version

**Comment by wthslw001** [comment]
> Compile in Debug mode instead of Release, and then when it crashes click the Debug button to open it with Visual Studio and see on what line of the code it crashed.

Hello, this problem has been solved.
