### ISSUE TITLE
🐛 [Bug] Battlebots are doing a reverse graveyard jump

### ISSUE THREAD

**Issue by schell244** [vmangos/core#1181]
## 🐛 Bug report
Warsong battlebots climb up the graveyard wall once one of them carries a flag (both horde and alliance bots do that)

<img width="295" alt="battlebots" src="https://user-images.githubusercontent.com/9536270/116812952-abebf380-ab51-11eb-81e6-f4caba53ffcd.PNG">

### Expected behavior
battlebots should not climb the graveyard wall

### Steps to reproduce
1. run warsong with battlebots 
2. wait until a bot catches a flag
3. watch bot returning the flag

Commit Hash:  
d9ffe46

Operating System:
- Win 10

**Comment by NickTyrer** [comment]
@ratkosrb do the new maps fix this?

**Comment by ratkosrb** [comment]
Not related to map at all. The problem is that this is the shortest route to base. I did some fixes to similar problems in AV, not sure if the WSG issue still happens.

**Comment by nellyeo** [comment]
Can confirm that the issue still exists on the latest version (992b380). It happens for both horde and alliance bots in WSG.

Usually occurs when;
1 - Horde/Alliance bot carrying flag to their base
2 - Horde/Alliance bot chasing opposite factions FC
3 - Horde/Alliance bot chasing any target above them

**Comment by oowow-core** [comment]
yes, still there
