### ISSUE TITLE
🐛 [Bug] Missing dialog for Itharius NPC

### ISSUE THREAD

**Issue by GrenderG** [vmangos/core#1182]
## 🐛 Bug report
The dialog of Itharius changes depending if you have https://classic.wowhead.com/item=10455/ in your bags or not. At this moment in vMaNGOS the dialog that should appear ONLY when you have the item, is always appearing even if you don't have it.

### Expected behavior
Missing dialog when you DO NOT have the item (taken from Classic):

![image](https://user-images.githubusercontent.com/8654362/117016974-872f8180-acf3-11eb-8a15-35941d2d5a2a.png)
![image](https://user-images.githubusercontent.com/8654362/117017018-8f87bc80-acf3-11eb-9a67-f75344c8b86a.png)

Note: When you press the gossip option, Itharius does a clap emote.

EDIT: Seems like he has both dialogs active when you have the trinket: <https://youtu.be/PUfB_ZCrEaM?t=51>

**Comment by NickTyrer** [comment]
Closed in #1197
