### ISSUE TITLE
🐛 [Bug] Missing waypoints in Swamp of Sorrows

### ISSUE THREAD

**Issue by GrenderG** [vmangos/core#1183]
- Missing waypoints for Noboru the Cudgel, If I'm not wrong, two NPCs should also patrol with him. 
- Missing waypoints for Stonard Explorer with guid 38858, I think there's a missing spawn of another Explorer near this one (could also be another that's missing waypoints too).

**Comment by NickTyrer** [comment]
Some relevant data is here https://github.com/cmangos/classic-db/commit/4b9651b6d282032608292f8cffbf2ba4d3cf5bb1

**Comment by NickTyrer** [comment]
Noboru the Cudgel WP's added here #1197
