### ISSUE TITLE
pet login out

### ISSUE THREAD

**Issue by w5860363** [vmangos/core#119]
@ratkosrb https://github.com/vmangos/core/commit/8561eace01f499272e5688498a91088ed43c8606 
This submission is not stable
When a pet is killed, it causes the hunter to disconnect himself.

Please forgive my English

**Comment by ratkosrb** [comment]
There is no way this disconnects the player, its about preventing looting a creature if it was killed by the pet alone.

**Comment by w5860363** [comment]
@ratkosrb test spell 126 and Hunter spell 1002 
pet is killed login out

**Comment by coolzoom** [comment]
you probably implanted the anthcieat from elysium, that version will consider the hunter beast eye control and warlock eye control as teleport cheat sometimes, adding ignore for these two aura into the ignore list in the teleport cheat check in cheat.cpp would solve the issue. hack fix, i know
