### ISSUE TITLE
🐛 [Bug] Incorrect orientation of mobs during stun effects or when they die

### ISSUE THREAD

**Issue by Marcelo20XX** [vmangos/core#1199]
## 🐛 Bug report
Mobs face a random orientation when they are stunned or killed. This bug is an ancient one and occurs in any mangos based core too.

### Expected behavior
mobs should have the same orientation value previous to the stun effect and while displaying the death animation too.

### Steps to reproduce
Engage in combat with any mob and use a stun spell or kill the mob to trigger the bug
 
  Operating System:
  - Win 10

**Comment by ratkosrb** [comment]
This is blizzlike.
https://eu.forums.blizzard.com/en/wow/t/rogue-mobs-turning-when-gouged/84071/13
https://us.forums.blizzard.com/en/wow/t/weird-rogue-thing/305852/15
