### ISSUE TITLE
 How to set the timing system broadcast message to players？

### ISSUE THREAD

**Issue by chenps10** [vmangos/core#120]
Sorry to bother again。
How to set the timing system broadcast message to all players？
like this gm command：.announce $Message；but can broadcast automatically？
i try to set "game_event" and "broadcast_text" table in database world,but it is not working
tks for help

**Comment by ratkosrb** [comment]
You can add texts to be said periodically in the `autobroadcast` table. The stringId is from the `mangos_string` table.
