### ISSUE TITLE
🐛 [Bug] Player stealth detection range for creatures

### ISSUE THREAD

**Issue by Marcelo20XX** [vmangos/core#1203]
Players cant detect stealthed mobs further than 5 yards making some quests very difficult to complete

### Expected behavior
In Classic WoW I could detect stealthed mobs at somewhere between 15 or 20 yards of distance even if they were 3 levels above mine without any detect ability

### Steps to reproduce
Go near a stealthed mob like Shadowmaw Panthers or whatever mob that has a 22766 aura in creature template

**Comment by NickTyrer** [comment]
Is this fixed by https://github.com/vmangos/core/commit/a5775dec0aaeb1655dae1e59b1ac590027d10e38 ?

**Comment by Marcelo20XX** [comment]
It seems so, I successfully detected stealthed mobs at at least 15 yards, before they will only appear if I was at melee range or 5 yards. Only thing that remains and this must be another unrelated problem: whenever a stealthed mob appears, it seems like he spawns half a meter above the ground whereas in classic they appear at the same height of the terrain...

**Comment by NickTyrer** [comment]
e378b92641a66d5da45a31154f81431fedd63d60
