### ISSUE TITLE
🐛 [Bug]about partybot clone~~~

### ISSUE THREAD

**Issue by gamelgs** [vmangos/core#1205]
## 🐛 Bug report

Some equipment and buff can not be cloned.

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  76d60488e0011f26d1c9b91968340e01b084ad51

OS Client: Win 10
OS Server: Win 10

### Crashlog

- None

**Comment by ratkosrb** [comment]
Provide more information.

**Comment by gamelgs** [comment]
> Provide more information.

Equipment with reputation conditions cannot be cloned.
Buff seems that none of them can be cloned.

**Comment by gamelgs** [comment]
ITEM
ID:19885 Jin'do's Evil Eye
ID:19382 Pure Elementium Band
Neither of these can be cloned

**Comment by ratkosrb** [comment]
![Untitled](https://user-images.githubusercontent.com/35845488/119411663-6f945900-bcf3-11eb-9cba-150c56d2d201.jpg)

I can clone them without an issue.

**Comment by ratkosrb** [comment]
Fixed the reputation requirement problem here: https://github.com/vmangos/core/commit/8ccba9d4f087af0dd5be20754120dc2f75f10715

The fact buffs are not copied is not a bug. There was never any intention to copy buffs.
