### ISSUE TITLE
🐞 [Bug] Mind Flay

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#1207]
## 🐞 Bug report - Spell
Mind Flay should not be dispellable

### Version & Environment
Client Version: 1.12.1
Commit Hash:  2368e04

**Comment by ratkosrb** [comment]
It seems to have been made dispellable on purpose by somebody from Nost, the dispel type is overridden in the `spell_mod` table.
The comment reads "Fouet mental, rang1 : magique et non physique."

Is there any proof from Classic whether it can be dispelled or not?

**Comment by NickTyrer** [comment]
I played spreist in classic and it cannot be dispelled. I dont have an active account to get proof though.

**Comment by NickTyrer** [comment]
The only way I have noticed it being removed is with bubble and shapeshifting.
