### ISSUE TITLE
Warlock talent cannot made Healthstone

### ISSUE THREAD

**Issue by chenps10** [vmangos/core#121]
player level 22
Warlock
talent +Improved Healthstone will result  cannot made Healthstone like this：
![qq 20190116181838](https://user-images.githubusercontent.com/39617409/51244036-08e23080-19bf-11e9-9d0f-f01099cde88c.png)
![qq 20190116181901](https://user-images.githubusercontent.com/39617409/51244052-17304c80-19bf-11e9-885b-7b564f15aca8.png)

i try clean client wdb file relogin has not solved，and try reset player talent it can made，Until then add talent again，and it cannot made again。

i think its a bug

**Comment by chenps10** [comment]
error: The specified item was not found

**Comment by DarkmoonRabbit** [comment]
mangosd var:2019-01-16 01:15:55 +0200 / Win64
Tested, no such bug.

**Comment by ratkosrb** [comment]
Issue happens only before patch 1.5 because that is when the talent was added. We will have to remove the correct patch from the new Healthstone items.

**Comment by chenps10** [comment]
> mangosd var:2019-01-16 01:15:55 +0200 / Win64
> Tested, no such bug.

你把版本降至1.5以下1.2-1.4就可以重现我提的这些bug

**Comment by chenps10** [comment]
> Issue happens only before patch 1.5 because that is when the talent was added. We will have to remove the correct patch from the new Healthstone items.

so，can we fix it，or only upgrade to 1.5+？

**Comment by ratkosrb** [comment]
I will fix it later.

**Comment by chenps10** [comment]
> I will fix it later.

thanks very much for your work，can't express my gratitude
