### ISSUE TITLE
🐝 [Bug] Repeatable Mark of Honor quests not granting Experience each time.

### ISSUE THREAD

**Issue by sweetloo32** [vmangos/core#1211]
## 🐝 Bug report - Quest
Currently the repeatable quests where you turn in marks of honor pre 60 do not give XP after your first and second turn in.(Which is when it first becomes repeatable). This should NOT be the case.

### Expected behavior
The quests where you turn in marks of honor pre 60 should give EXP the first turn in then for each and every turn in after will also give experience although not as much as the very first. The quest links I'll provide should have the correct amounts and even though not explicitly stated by Blizzard or Wowhead themselves at least not that I could find the comments on popular forums and sites state this to be true and through my own experience through classic wow noticed this is the way these quests work. 

https://classic.wowhead.com/quest=8372/fight-for-warsong-gulch#comments
Comment by Dhorgan from 2006. Search Dhorgan on the page to find it.

https://www.icy-veins.com/forums/topic/52091-rank-14-on-a-level-59-character/
In the first paragraph it explains that you can't do the repeatable Battleground Mark quests if you twink
as they give experience.

https://xpoff.com/threads/warsong-gulch-mark-of-honor-quest.91253/
XP Off is a popular Twinking thread and this just like the thread above were made in classic wow and mentions
how Twinks can't do the Battleground Mark repeatable quests as if you continue doing so you will level up.

https://www.reddit.com/r/classicwow/comments/cq18rk/classic_battleground_xp/
This last one is less reliable as it is reddit but two people corrected others saying 
that what I have stated in this bug report to be true. Toward the bottom you will find them 
Their names are ryvenn and mguttor.

There are a total of 26 quests that this effects. I will be linking the affected quests for each bracket:10-19, 20-29, 30-39, 40-49, 50-59, 60. As well as each battleground and faction. I am including the level 60 quests only because Classic Wowhead says the level 60 quest has experience which would mean extra money on turn in at max level. These quests also include the quests where upon reaching a certain level you unlock the quest to turn in all three marks from the battlegrounds and this too becomes repeatable and grants experience. 

I will now post the quest links (Quest ID in link) of the repeatable quests in this following order descending.
Faction>Warsong Gulch >Arathi Basin > Alterac Valley >All 3 marks
Quests will be descending by bracket levels. Lowest Level to Highest Level
HORDE
Warsong Gulch
https://classic.wowhead.com/quest=8389/battle-of-warsong-gulch
https://classic.wowhead.com/quest=8431/battle-of-warsong-gulch
https://classic.wowhead.com/quest=8432/battle-of-warsong-gulch
https://classic.wowhead.com/quest=8433/battle-of-warsong-gulch
https://classic.wowhead.com/quest=8434/battle-of-warsong-gulch
https://classic.wowhead.com/quest=8435/battle-of-warsong-gulch

Arathi Basin
https://classic.wowhead.com/quest=8390/conquering-arathi-basin
https://classic.wowhead.com/quest=8440/conquering-arathi-basin
https://classic.wowhead.com/quest=8441/conquering-arathi-basin
https://classic.wowhead.com/quest=8442/conquering-arathi-basin
https://classic.wowhead.com/quest=8443/conquering-arathi-basin

Alterac Valley
https://classic.wowhead.com/quest=8387/invaders-of-alterac-valley

All 3 Marks
https://classic.wowhead.com/quest=8388/for-great-honor

ALLIANCE
Warsong Gulch
https://classic.wowhead.com/quest=8386/fight-for-warsong-gulch
https://classic.wowhead.com/quest=8404/fight-for-warsong-gulch
https://classic.wowhead.com/quest=8405/fight-for-warsong-gulch
https://classic.wowhead.com/quest=8406/fight-for-warsong-gulch
https://classic.wowhead.com/quest=8407/fight-for-warsong-gulch
https://classic.wowhead.com/quest=8408/fight-for-warsong-gulch

Arathi Basin
https://classic.wowhead.com/quest=8384/claiming-arathi-basin
https://classic.wowhead.com/quest=8391/claiming-arathi-basin
https://classic.wowhead.com/quest=8392/claiming-arathi-basin
https://classic.wowhead.com/quest=8397/claiming-arathi-basin
https://classic.wowhead.com/quest=8398/claiming-arathi-basin

Alterac Valley
https://classic.wowhead.com/quest=8383/remember-alterac-valley

All 3 Marks
https://classic.wowhead.com/quest=8385/concerted-efforts

### Version & Environment
  Client Version:
  - 1.12.1.5875

Commit Hash:  Unknown Messaged the Owner and a Dev will update if the info becomes available.

Operating System:
  - Win 10 (This is mine as I do not know the server owners specifications.)

**Comment by Daribon** [comment]
I did it in classic when I was leveling up one of my alts, so can confirm at least from classic that Mark of Honor gave XP on repeated turn in.

**Comment by ratkosrb** [comment]
This is the code responsible for not giving XP on second completion.
https://github.com/vmangos/core/blob/development/src/game/Objects/Player.cpp#L13372

We need to test with other repeatable quests if XP is still given the second time, or is it just the mark quests.

It was changed in cmangos back in 2012.
https://github.com/cmangos/mangos-classic/commit/afadd1c5b2cf0556300706f22f387c0a302404eb

Other repeatable quests we can test with:
https://classic.wowhead.com/quest=1878/water-pouch-bounty
https://classic.wowhead.com/quest=2881/troll-necklace-bounty

**Comment by sweetloo32** [comment]
Tested https://classic.wowhead.com/quest=2881/troll-necklace-bounty Also doesn't give XP for the repeatable like it should. So it does seem to be more than just the honor quests.

**Comment by ratkosrb** [comment]
That is not what I meant. All repeatable quests do not give XP after the first time in vmangos. I was saying we must test on the official Classic-Era servers if those quests give XP there on repeat completion.

**Comment by sweetloo32** [comment]
Thats why I linked that quest because it is one I have done repeatedly on classic after collecting them while doing the questline to save Sharpbeak (not relevant but starts with quest 2988). If you sort comments by classic posts on the link to the quest I provided someone mentions it still gives the 390 on repeat even at level 50 in classic 2019.

**Comment by sweetloo32** [comment]
Made my way to Tanaris on Classic today and the pouches give 380xp on each additional turn in

**Comment by Schmoha** [comment]
I found a video where they turn in quest for xp.

https://www.youtube.com/watch?v=MZqtA3qwOE0

hope it helps.
