### ISSUE TITLE
🐛 [Bug] Build is broken for client version 1.8.4 and below

### ISSUE THREAD

**Issue by codestothestars** [vmangos/core#1215]
## 🐛 Bug report
The build fails at [Object.cpp#528](https://github.com/vmangos/core/blob/fb91e33eb92d1aa34c86caff83a0fc73c6141ac0/src/game/Objects/Object.cpp#L528).
> 'time': is not a member of 'MovementInfo'

This started occurring at commit 39afde5.

### Expected behavior
Build should succeed.

### Steps to reproduce
1. Set `SUPPORTED_CLIENT_BUILD` to `CLIENT_BUILD_1_8_4`.
2. Attempt to build.

### Version & Environment
Client Version: 1.8.4.4878

Commit Hash: fb91e33

OS Client: Windows 10.0.19043
OS Server: Windows 10.0.19043

### Crashlog
- None

**Comment by den13501** [comment]
The template solution I do is modify  `Object.cpp`
```
#else
    Unit const* unit = ToUnit();
    if (unit)
    {
        WorldObject const* wobject = (WorldObject*)this;
        MovementInfo m = wobject->m_movementInfo;
        if (!m.ctime)
        {
            m.time = WorldTimer::getMSTime() + 1000;  <--issue
```  
change `m.time` to `m.stime` ,then I can compile successfully

**Comment by ratkosrb** [comment]
Fixed here https://github.com/vmangos/core/commit/cae13812cc3c36856c40e2aa7b78a1e229894a19
