### ISSUE TITLE
Druid  talent BUG

### ISSUE THREAD

**Issue by chenps10** [vmangos/core#122]
wowpatch=1.4
Level limit 45

talent “leader of the pack” need 30 talent points to open it and add 1 point to it itself，so i need 31 points to open it。

but now when i add 1 point to “faerie fire(feral)” and 1 point to "nature's grasp" and then they all disappeared。

so in the end I can actually use 30 points to open  “leader of the pack” 

like this：

![qq 20190118134400](https://user-images.githubusercontent.com/39617409/51368233-7a3df280-1b29-11e9-86af-954080b569cc.jpg)

or this

![qq 20190118134318](https://user-images.githubusercontent.com/39617409/51368240-86c24b00-1b29-11e9-80bc-f0ebbfc64690.jpg)

this picture is the talent in the actual game, not the simulator。

**Comment by chenps10** [comment]
in this bug，wildfire talent actually needs 31 talent points to open，but now it just takes 30 points.

**Comment by ratkosrb** [comment]
Should be fixed by https://github.com/vmangos/core/commit/8bc932b5c80368ddd507ba7a2068fd8c50f8a171
