### ISSUE TITLE
🐝 [Bug] quest 6085 - Taming the Beast 3/3

### ISSUE THREAD

**Issue by den13501** [vmangos/core#1225]
### Expected behavior

When you tame an ice craw bear, the quest should be complete
https://www.youtube.com/watch?v=VYw3sLLW-Eo
### Steps to reproduce

1. create a Dwarf hunter, level up to lv.10
2. .quest add 6085
3. try to tam an ice craw bear by quest item - taming rod
4. when you taming ice craw bear successfully, quest doesn't show as complete.

### Version & Environment

Client Version: 
1.6.1.4544

Server Patch: 1.2

Commit Hash:  

OS Client: Windows 10
OS Server: Windows server 2008 r2
### Crashlog

- None

**Comment by ratkosrb** [comment]
It works for me.

![WoWScrnShot_061421_095155](https://user-images.githubusercontent.com/35845488/121850971-3c435980-ccf6-11eb-97b3-5a3b2aa91682.jpg)

**Comment by den13501** [comment]
> It works for me.
> 
> ![WoWScrnShot_061421_095155](https://user-images.githubusercontent.com/35845488/121850971-3c435980-ccf6-11eb-97b3-5a3b2aa91682.jpg)

Sorry, I forgot add more description.
This issue will happen on CLIENT_BUILD_1_6_1, when I reconfigure as CLIENT_BUILD_1_12_1, then the result is work, no issue.
So I thought it happen on server 1.6.1 and client 1.6.1
