### ISSUE TITLE
🐛 [Bug] Warlock minion Voidwalker & Succubus loot

### ISSUE THREAD

**Issue by Rantala42** [vmangos/core#1226]
If warlock Voidwalker or Succubus minion gets first hit and dies during combat, player cant loot the npc after combat. This bug didn't occur with Imp & Felhunter minions.

Client Version: 1.12.1.5875

OS Client: WIN 10
OS Server:  WIN 10

**Comment by ratkosrb** [comment]
I can't reproduce the issue. I send my pet to attack first, then i kill it with .die once it has hit the enemy mob, but I am still able to loot the enemy mob after killing it.

**Comment by Rantala42** [comment]
I tested this further.

Seems like the bug happens if warlock minion dies during combat, and player hasn't taken any damage from the npc during combat. If player gets hit by npc, player can loot npc normally. 

To reproduce this bug:

Put your minion to attack npc.
Cast shadowbolt/ auto attack npc to deal some damage.
.die command your minion
.die command the npc before it deals any damage to player.

**Comment by Gelori** [comment]
Just tested the issue by my self on
" Core revision: b00b1f4ca4fac047be4f / 2022-06-17 15:32:44 +0300 / Linux_x64 (little-endian)"

Everything works as intended with both Voidwalker and Succubus (tested both), followed all steps shown in comment above:

Put your minion to attack npc.
Cast shadowbolt/ auto attack npc to deal some damage.
.die command your minion
.die command the npc before it deals any damage to player.

Video of test: https://youtu.be/v89MGMQgtCo

Issue can be closed.
