### ISSUE TITLE
🐜 [Bug] deep tram would stop in the middle of rail somtimes.

### ISSUE THREAD

**Issue by den13501** [vmangos/core#1229]
### Steps to reproduce

1. try to take a deep tram in ironforge or stormwind.
2. then there is chance the tram stopped in the middle , see screen below
![image](https://media.discordapp.net/attachments/850683200745111562/853883400804237322/unknown.png)
### Version & Environment

Client Version: 1.6.1.4544
CLIENT_BUILD_1_6_1
Server Patch: 1.2

Commit Hash:  

OS Client: Windows 10
OS Server: Windows server 2008 r2

### Crashlog

- None

**Comment by NickTyrer** [comment]
@ratkosrb can this be closed

**Comment by ratkosrb** [comment]
I don't know. I fixed an issue with the middle tram car being desynced from the others, but this issue could still be happening. I also had an issue with the tram sometimes disappearing when i step off from it.

**Comment by ratkosrb** [comment]
Possibly fixed by https://github.com/vmangos/core/commit/7aaa9c34d653a8b54b9ec8f6a1fd757ff610af32

**Comment by den13501** [comment]
After build with latest commit ,I test on 1.6 client, the deeprun tram has move very normally 👍 
https://github.com/vmangos/core/commit/e776319fc455e68eb707bc197bfb42f49f235276
