### ISSUE TITLE
🐛 [Bug] Target Dummy

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#1232]
See https://github.com/the-hyjal-project/bugtracker/issues/423

**Comment by Simp-N** [comment]
@NickTyrer Sorry to necro an old post. I was about to report this issue, because they still give XP and the droprates are still off on vmangos, but I see that you've already referenced my earlier report on that other project. Was this ever fixed, or shall it be ignored?

**Comment by NickTyrer** [comment]
If the bug is still present feel free to re-open the issue. Honestly I can't remember what happened with this bug.
