### ISSUE TITLE
🐛 [Bug] Unable to build gameobject models during mmap generation due to missing files

### ISSUE THREAD

**Issue by mserajnik** [vmangos/core#1239]
## 🐛 Bug report

When running all the client data extractors in order [according to the Wiki](https://github.com/vmangos/wiki/wiki/Getting-it-working#2-extracting-data-from-the-client) (`mapextractor`, `vmapextractor`, `vmap_assembler`, `MoveMapGen`) on a 1.12.1.5875 client, building two gameobject models currently fails during mmap generation (`MoveMapGen`):

```
Building GameObject model Transportship.wmo.vmo
* Unable to open file
Building GameObject model Transport_Zeppelin.wmo.vmo
* Unable to open file
```

Checking the `vmaps` directory, the two referenced files don't exist, which explains the error message.
I do have the files `Transportship.wmo0.vmo` and `Transport_Zeppelin.wmo0.vmo` instead (note that it's `wmo0` and not `wmo` in the filenames), in case those are related or supposed to be the correct ones.

Relevant code: https://github.com/vmangos/core/blob/6ab5a4dcf4c66a8fe14f0a959527e683b42d4cd6/contrib/mmap/src/MapBuilder.cpp#L1466-L1467

### Expected behavior

Building these gameobjects probably shouldn't fail. Or, if this is old code and building these two gameobject models is no longer required, it should probably be removed to avoid confusion.

### Steps to reproduce

1. Run the client data extractors in the correct order [according to the Wiki](https://github.com/vmangos/wiki/wiki/Getting-it-working#2-extracting-data-from-the-client) on a 1.12.1.5875 client
2. Observe that building the gameobject models `Transportship.wmo.vmo` and `Transport_Zeppelin.wmo.vmo` fails during mmap generation (`MoveMapGen`) because these two files don't exist in the `vmaps` directory

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  https://github.com/vmangos/core/commit/6ab5a4dcf4c66a8fe14f0a959527e683b42d4cd6

OS Client: -
OS Server: Ubuntu 20.04.2 LTS

### Crashlog

- None

**Comment by ratkosrb** [comment]
I had the same problem, and had to extract those using the cmangos extractors.

**Comment by mserajnik** [comment]
> I had the same problem, and had to extract those using the cmangos extractors.

Oh, interesting. Could you explain how you went about doing that?
Because from what I can see, CMaNGOS also tries to build the same gameobject models: https://github.com/cmangos/mangos-classic/blob/c2da8c7594e5a2a1f312c24e1f50bb4032f9cb37/contrib/mmap/src/MapBuilder.cpp#L393-L394 (as well as `Transportship_Ne.wmo.vmo`, which isn't referended in VMaNGOS altogether).

So, I assume you ran the CMaNGOS vmap extractor instead of the VMaNGOS one and got `Transportship.wmo.vmo` and `Transport_Zeppelin.wmo.vmo`? Or are you saying you somehow managed to build the two files that _do_ exist, `Transportship.wmo0.vmo` and `Transport_Zeppelin.wmo0.vmo`, instead?

If it works correctly using the CMaNGOS extractors, do you think it would be easy to fix in VMaNGOS? I'm pretty new to WoW server emulation in general (and also not a C++ programmer), so I'm not really aware how far the projects are apart code-wise (but I saw some things getting ported from CMaNGOS in the past, looking through the commits here).

**Comment by ratkosrb** [comment]
Our extractors have all kinds of bugs that don't exist in cmangos, due to changes that were made back in the nolstarius days. I'm considering just replacing ours completely with theirs. You can copy mmap files generated by the cmangos extractors and they work in vmangos, and usually solve whatever pathing issue there was in our version.

**Comment by mserajnik** [comment]
> You can copy mmap files generated by the cmangos extractors and they work in vmangos, and usually solve whatever pathing issue there was in our version.

Thanks for the explanation!
Is that true only for mmap files or can you (compatibility-wise) use _all_ of the client data extracted/generated by CMaNGOS? If yes, is that something you would currently recommend doing?

On a sidenote, thank you very much for your work in maintaining VMaNGOS! It's really nice to see people still passionate about server emulation. While it's good to have official classic servers now (in general, although I'm personally not super interested in playing on them), VMaNGOS (and other projects) are imo really important for game preservation; I doubt Blizzard will ever publish their server software under an open source license, even after all official servers have been shut down.

**Comment by ratkosrb** [comment]
The maps and vmaps have a different version string so u can't use those, but you can use their mmaps. I am only taking tiles for specific bugged spots though.

**Comment by mserajnik** [comment]
Thanks for clarifying. I think for now I'll just extract those two missing objects then and otherwise see if I encounter any issues/bugs elsewhere.

I'll leave this issue open for you to close (in case you want to leave it open until you replace the mmap generation (or client data extraction in general), as you suggested above).
