### ISSUE TITLE
🐛 [Regression] Pet doesn't use pathfinding on the way to "Stay point".

### ISSUE THREAD

**Issue by kampeador** [vmangos/core#1242]
Hello. It is good to see that someone still maintains this fork.
I've recenly updated to the lastest version from my 4 year old version.

Pet doesn't use pathfinding on the way to "Stay point".

Steps to reproduce:
1. Pet stay
2. Send pet to attack.
3. Pet passive. (Pet will run back to "Stay point" ignoring height and obstacles).

**Comment by Yuukiring** [comment]
Pet doesn't use pathfinding on the way to attack target，how to solve this

**Comment by Yuukiring** [comment]
Control the pet to jump into the air，Then attack the selected target
The pet will fly directly to attack the target，ignoring height and obstacles

**Comment by ratkosrb** [comment]
Can you make a video of the problem?

**Comment by Yuukiring** [comment]
> a
https://www.bilibili.com/video/BV1LU4y1k7FM/?vd_source=95a01d14f12e277bae712a4cb641ecb6

**Comment by Yuukiring** [comment]
> Can you make a video of the problem?

https://www.bilibili.com/video/BV1pe4y1f7bU/?vd_source=95a01d14f12e277bae712a4cb641ecb6
