### ISSUE TITLE
🐜 [Bug] The elevator 「Great Lift」 in Thousand Needles won't stop on wait area

### ISSUE THREAD

**Issue by den13501** [vmangos/core#1243]
### Steps to reproduce

1. .go xyz -4692 -1811 -54
2. watch behavior of the Great Lift
3. You would find sometimes the two elevators just top in the middle way, sometime they rises up and over the stop area, but sometime do not...
 
video 1 [![Please watch the video](https://static.wikia.nocookie.net/wowwiki/images/9/9f/The_Great_Lift.jpg/revision/latest/scale-to-width-down/600?cb=20061103170503)](https://streamable.com/z1frow)
video 2  [![Please watch the video](https://static.wikia.nocookie.net/wowwiki/images/9/9f/The_Great_Lift.jpg/revision/latest/scale-to-width-down/600?cb=20061103170503)](https://streamable.com/byndgb) 
### Version & Environment

Client Version: 1.6.1.4544
CLIENT_BUILD_1_6_1
Server Patch: 1.2

Commit Hash:  

OS Client: Windows 10
OS Server: Windows server 2008 r2

### Crashlog

- None

**Comment by ratkosrb** [comment]
Should be fixed by https://github.com/vmangos/core/commit/7aaa9c34d653a8b54b9ec8f6a1fd757ff610af32

**Comment by den13501** [comment]
Thank you, it fixed, proof : https://streamable.com/814jcn
this issue can be closed.
