### ISSUE TITLE
🐞 [Bug] ST boss - Jammal'an the Prophet

### ISSUE THREAD

**Issue by Agney-gt** [vmangos/core#1246]
## 🐞 Bug report - Spell

https://www.wowhead.com/spell=12480/hex-of-jammalan
![11](https://user-images.githubusercontent.com/84612798/123232058-6830bd00-d4f6-11eb-93a2-e1602f420922.png)

This is only chatlogs but im sure you can easily reproduce it with GM commands.
### Expected behavior

The spell should act like a MC and the player should be transformed (works correctly) and attack allies (does not work). Instead, the player can control their char and negate this spell.

https://www.youtube.com/watch?v=oDg9BR8w0B4
### Steps to reproduce

1. Go to the boss in ST Jammalan the prophet
2. Wait till he cast the curse on you
3. You will transform but will be able to move the character around
4. This is not the case as it should be MC and you should be attacking allies (Otherwise it defeats the purpose)
5. Profit

### Version & Environment

Client Version: 
1.12.1.587

Commit Hash:  

OS Client: Win 10
OS Server: 

### Crashlog

- None

**Comment by T1ti** [comment]
He should use spell https://classic.wowhead.com/spell=12479/hex-of-jammalan
which is a scripted spell that triggers both 
https://classic.wowhead.com/spell=12483/hex-of-jammalan (charm+slow)
and
https://classic.wowhead.com/spell=12480/hex-of-jammalan (dmg increase+model swap)
and also say some text

https://youtu.be/oDg9BR8w0B4?t=42
