### ISSUE TITLE
hunter uses the markup spell in a state where the target is dead or has no target, it will cause other spells to be unreleased

### ISSUE THREAD

**Issue by chenps10** [vmangos/core#125]
If the hunter uses the markup spell in a state where the target is dead or has no target, it will cause other spells to be unreleased. You need to press the esc key to continue the operation.

this causes some macros to be unusable.

**Comment by DarkmoonRabbit** [comment]
最好把你当前的WowPatch带上

**Comment by ratkosrb** [comment]
Can you give the spell id of the spell you are talking about.

**Comment by chenps10** [comment]
> 最好把你当前的WowPatch带上

好的，谢谢提醒，刚刚提交快了，没把环境交代清楚。
centos7x64，mysql5.5，自编译，目前用的是patch1.4，等级上限控制45级。

**Comment by chenps10** [comment]
> Can you give the spell id of the spell you are talking about.

Sorry for my carelessness。
current patch 1.4
spell name：Hunter's Mark 
If the hunter uses the this spell to a state where the target is dead or has no target, it will cause other spells to be unreleased. need to press the esc key to continue other spells。

Error message：another action is in progress

![qq 20190118124742](https://user-images.githubusercontent.com/39617409/51366249-8e7cf200-1b1f-11e9-8bca-ad14a1a571eb.png)

![qq 20190118124823](https://user-images.githubusercontent.com/39617409/51366258-9472d300-1b1f-11e9-83a4-d3fb4cbd411a.png)

**Comment by w5860363** [comment]
这个问题可能是cmangos就有的一个BUG 当快速切换目标的时候 自动射击会卡住
需要手动取消

The problem may be that a BUG in cmangos can get stuck in automatic shooting when switching targets quickly.

Need to cancel manually

**Comment by w5860363** [comment]
https://github.com/lh-server/core/blob/d1ec3f31ab9fc07cf4b6fac240d53ca8d002b387/src/game/Spells/SpellAuras.cpp#3973L

**Comment by w5860363** [comment]
@ratkosrb 
spell id:https://www.wowdb.com/spells/1130-hunters-mark
code:
https://github.com/vmangos/core/blob/development/src/game/Spells/SpellAuras.cpp#L3931
https://github.com/vmangos/core/blob/development/src/game/Spells/Spell.cpp#L6523

But I think that's the problem. https://github.com/cmangos/issues/issues/895

**Comment by chenps10** [comment]
> 这个问题可能是cmangos就有的一个BUG 当快速切换目标的时候 自动射击会卡住
> 需要手动取消
> 
> The problem may be that a BUG in cmangos can get stuck in automatic shooting when switching targets quickly.
> 
> Need to cancel manually

是的，所以才希望能修复，不然猎人的自动标记宏和很多其他猎人宏基本就是不能用的
