### ISSUE TITLE
🐛 [Bug] NEARBYY_CREATURE Condition

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#1252]
## 🐛 Bug report
Example: If I assign a condition to a quest for it to only be active when a creature is nearby the condition works initially. The bug occurs if you go out of range and go back again in that the condition is no longer applied

see: https://youtu.be/rTYSWg3Cupg

Client Version: 1.12.1

Commit Hash:  a99d5c2

**Comment by ratkosrb** [comment]
What are you trying to do here? Why would u assign this type of condition to a quest?

**Comment by NickTyrer** [comment]
I had to do it this way because you can't assign a quest to a creature based on guid.

**Comment by ratkosrb** [comment]
Explain what you want to do please. What quest is it, and why should it only be offered by a specific guid, and not all creatures with this entry.

**Comment by NickTyrer** [comment]
Only one of the lunar festival emissarys in each city offer the quest The Lunar Festival. I think I can solve it by removing the quest giver flag combined with a db_guid condition.

**Comment by ratkosrb** [comment]
Yes I think removing the quest giver flag is the right approach.

**Comment by NickTyrer** [comment]
Actually that won't work either as each quest giver has a unique quest. So 
guid 91688 has quest 8872
guid 91623 has quest 8880
etc...
all of the creatures are creature id 15892

**Comment by NickTyrer** [comment]
Maybe I can add an `AREAID` condition to the quests in addition to removing the flags

**Comment by ratkosrb** [comment]
Sounds like assigning a source guid condition to the quest_template might be the simplest option.

**Comment by NickTyrer** [comment]
`DB_GUID` doesnt work with quests ATM

**Comment by ratkosrb** [comment]
That makes no sense.

**Comment by NickTyrer** [comment]
`CONDITION 8870 type 52 used with bad parameters, called from quest template, used with target: Player Test (Guid: 2), map 0, source <nullptr>`

**Comment by ratkosrb** [comment]
Ah I see why it doesn't work. The quest giver is not know in the function that checks the condition, so it can only check the player.

**Comment by ratkosrb** [comment]
You are right then, use the zone id condition to restrict each quest to a specific city.
