### ISSUE TITLE
🐝 [Quest] Suntara Stones (3367)

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#1256]
## 🐝 Bug report - Quest
The waypoints used for the quest are completely wrong, also the waypoints are missing their scripts. The NPC Dorius Stonetender is also missing a few of his aggro texts see:
https://classic.wowhead.com/npc=8284/dorius-stonetender
https://www.youtube.com/watch?v=s8qTBCDPJIU

Client Version: 1.12.1

Commit Hash:  dc8300c

**Comment by LEO33SoFo** [comment]
This issue should be have remained opened, it still exists as of c8cef536eb7af0c2bab9d945d9e974fcfa7d63b9.
