### ISSUE TITLE
🐝 [Bug] [Quest 2561] Druid of the Claw  - quest item Voodoo Charm is not functional

### ISSUE THREAD

**Issue by den13501** [vmangos/core#1258]
### Expected behavior

reference: https://classic.wowhead.com/quest=2561/druid-of-the-claw
use quest item on claw's dead body, then it will show quest completed on screen
https://youtu.be/UdoidA8Vcp4
### Steps to reproduce

1. .quest add 2561
2. .go xyzo 9872 1521 1257 3
3. kill Rageclaw , use  the quest item `Voodoo Charm` on his dead body, there is nothing happened, quest doesn't completed.
![screenshot](https://i.imgur.com/SzAOj1v.png)

### Version & Environment

Client Version: 1.6.1.4544
CLIENT_BUILD_1_6_1
Server Patch: 1.2

Commit Hash:  

OS Client: Windows 10
OS Server: Windows server 2008 r2

### Crashlog

- None

**Comment by Daribon** [comment]
Can confirm that nothing is happening on 1.6.1

**Comment by den13501** [comment]
> 
> 
> Can confirm that nothing is happening on 1.6.1
Yeah,I think this is same issue as https://github.com/vmangos/core/commit/dd101b872f461a6a03276f75781305bc49404dc1
this [Spell: Release Rageclaw](https://classic.wowhead.com/spell=10617/release-rageclaw) is not available on 1.6.1

**Comment by Daribon** [comment]
I just checked, Release Rageclaw spell exists in the 1.6.1 client.
