### ISSUE TITLE
🐛 [Bug]The trams in storm city and railway fort are not running normally

### ISSUE THREAD

**Issue by zzjty001** [vmangos/core#1263]
The trams in storm city and railway fort are not running normally. One of them will get stuck and the other will disappear! The client version used is 1.12.3! Vanilla v18 tram seems to be more stable than v19.

**Comment by ratkosrb** [comment]
I think this will fix it.
https://github.com/vmangos/core/commit/e776319fc455e68eb707bc197bfb42f49f235276

**Comment by zzjty001** [comment]
thank you very much

**Comment by den13501** [comment]
> I think this will fix it.
> [e776319](https://github.com/vmangos/core/commit/e776319fc455e68eb707bc197bfb42f49f235276)

After build with latest commit ,I test on 1.6 client, the deeprun tram has move very normally 👍
