### ISSUE TITLE
🐝 [Bug] The Blackwood Corrupted quest

### ISSUE THREAD

**Issue by LEO33SoFo** [vmangos/core#1269]
## 🐝 Bug report - Quest

A _Blackwood Warrior_ does not spawn after successful interaction with each of the containers.
The nearby furbolgs do not gather around and become friendly after using the _Filled Cleansing Bowl_ in the _Bonfire_.
### Expected behavior

After each successful interaction of any container, a _Blackwood Warrior_ should spawn.
After using the _Filled Cleansing Bow_ in the _Bonfire_, the nearby furbolgs should gather around and become friendly, except the aforementioned spawned *Blackwood Warrior*s.
Information based on [Wowpedia](https://wowpedia.fandom.com/wiki/The_Blackwood_Corrupted) and [Wowhead](https://classic.wowhead.com/quest=4763/the-blackwood-corrupted) comments.
Definite proof is in this [YouTube](https://www.youtube.com/watch?v=O0skyfDp_tQ) video.
### Steps to reproduce

1. `.quest add 4763`
2. `.go xyzo 6785.480957 -350.452942 41.106300 5.489847 1`
and/or
`.go xyzo 6848.819336 -440.173828 43.452827 5.792214 1`
and/or
`.go xyzo 6894.718262 -540.500671 42.851578 2.454265 1`
3. Interact with _Blackwood Grain Stores_, _Blackwood Nut Stores_ or _Blackwood Fruit Stores_, depending on your location.
4. Go to the _Bonfire_ responsible for the _Filled Cleansing Bowl_ usage, and use that item.
5. Check the behavior of nearby furbolgs.

### Version & Environment

Client Version: 
  - 1.12.1.6005

Commit Hash:  
002997578eb07995da1b7f680c6fcfd741771eb5

OS Client and Server:
  - Windows XP Professional

### Crashlog

- None

**Comment by NickTyrer** [comment]
Blackwood Warriors not spawning fixed here #1467
