### ISSUE TITLE
how to control some instances open or closed？

### ISSUE THREAD

**Issue by chenps10** [vmangos/core#127]
i try to found instance_template to control instance status。but  there is no instance_template table in the world database，so how do I control some instances open or closed in current patch？

**Comment by ratkosrb** [comment]
You can remove the area trigger for the instance in the `areatrigger_teleport` table. To find the trigger id type ".trigger near" while standing next to the entrance.

**Comment by chenps10** [comment]
> You can remove the area trigger for the instance in the `areatrigger_teleport` table. To find the trigger id type ".trigger near" while standing next to the entrance.

ok,tks
