### ISSUE TITLE
🐝 [Bug] A Lost Master (2) quest

### ISSUE THREAD

**Issue by LEO33SoFo** [vmangos/core#1271]
## 🐝 Bug report - Quest

_Grimclaw_ does not point to where _Volcor_ is hiding when waving at him, according to [Wowpedia](https://wowpedia.fandom.com/wiki/A_Lost_Master_(2)) and [Wowhead](https://classic.wowhead.com/quest=993/a-lost-master) comments.
### Expected behavior

_Grimclaw_ should point to where _Volcor_ is hiding when waving at him.
### Steps to reproduce

1. `.quest add 993`
2. `.go creature id 3695`
3. `/wave` at Grimclaw.
4. Check his behavior.

### Version & Environment

Client Version: 
  - 1.12.1.6005

Commit Hash:  
002997578eb07995da1b7f680c6fcfd741771eb5

OS Client and Server:
  - Windows XP Professional

### Crashlog

- None

**Comment by NickTyrer** [comment]
Closed  #1467
