### ISSUE TITLE
🐛 [Bug] Thousand Needles, Shimmering Flats didnt have car races with gnomes and goblins

### ISSUE THREAD

**Issue by sdpHTF9173** [vmangos/core#1272]
## 🐛 Bug report

Thousand Needles, Shimmering Flats didnt have car races with gnomes and goblins，Official, like this
![hcQ5-bkq2XjZ5fT3cS2vw-1j2 jpg medium](https://user-images.githubusercontent.com/87078856/124771943-25e39300-df6e-11eb-9535-5e3e7cfbbd9a.jpg)
![hcQ5-le6fXcZ3hT3cS2vw-1j2 jpeg medium](https://user-images.githubusercontent.com/87078856/124771958-28de8380-df6e-11eb-8622-521a7d74f0b8.jpg)
![hcQ5-bkq2XjZ5fT3cS2vw-1j2 jpg medium (1)](https://user-images.githubusercontent.com/87078856/124771966-2a0fb080-df6e-11eb-884f-a8b378928c0f.jpg)
![hcQ5-gq6dXlZ5vT3cS2vw-1j2 jpg medium](https://user-images.githubusercontent.com/87078856/124771979-2c720a80-df6e-11eb-84f6-d64edc25811e.jpg)

### Crashlog

- None

**Comment by NickTyrer** [comment]
see #1154

**Comment by sdpHTF9173** [comment]
> see #1154

Thanks！
