### ISSUE TITLE
After vmangos v19 discards the hash password, the registered account on the web mangos V4 website cannot login to the Warcraft game🔧 [Support]

### ISSUE THREAD

**Issue by zzjty001** [vmangos/core#1283]
After vmangos v19 discards the hash password, where is the password stored? In which data sheet? Which field to store? Web mangos V4, which used to be well used, can't match v19 perfectly now. The website can register, but cannot log in to the Warcraft game.

**Comment by ratkosrb** [comment]
We do not store the whole password. If we did, then the server owner could decrypt the passwords of players. The `sha_pass_hash` field was removed to make sure this won't happen. The only information needed to know if the user logged in with the right password is the `s` and `v` fields. The new repack contains an example registration page you can use. It works using SOAP to create accounts from the mangosd process.

**Comment by edhzdzGit** [comment]
The new repack contains an example registration page you can use. Where can i download this repack comrade?. Thank you!

**Comment by wsh123321** [comment]
The new repack contains an example registration page you can use. Where can i download this repack comrade?. Thank you!
