### ISSUE TITLE
🦂 [Bug] DME: Alzzin's door not opening

### ISSUE THREAD

**Issue by Marcelo20XX** [vmangos/core#1291]
## 🦂 Bug report - Dungeon
After speaking with Old Ironbark the door to Alzzin The Wildshaper doesn't open

### Expected behavior
After speaking with Old Ironbark the door to Alzzin The Wildshaper should open

### Steps to reproduce
1. Do one time the instance, the script will work and the door will  open
2. Reset the instance and talk to Old Ironbark
3. Old IronBark will walk through its waypoint and collapse at the door 
4. The door will bug out and will remain closed

Note: I looked at the source and notice that  the value for GO_DOOR_ALZZIN_IN = 181496,
is wrong, it should be GO_DOOR_ALZZIN_IN = 179549, then the door its fixed and you can rerun the instance. Still the console shows this error:
ERROR:FindScriptTargets: Failed to find target for script with id 560100 (target_param1: 179549), (target_param2: 10), (target_type: 11).

Tested on
Client: 1.12.1.5875

**Comment by NickTyrer** [comment]
Possibly Closed in #1467
