### ISSUE TITLE
🐛 [Quest] Spawn of Jubjub (7946)

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#1297]
ISSUES
2. Jubjub's quest is missing https://www.youtube.com/watch?v=cLiXqxd7HZU also this spell may be usefull https://classic.wowhead.com/spell=23845/attract-jubjub

Client Version: 1.12.1
Commit Hash:  c228b43

**Comment by Daribon** [comment]
Since when has the cooldown for sayges buff ever been 7 hours?
From classic the cooldown was 4 hours, or 8 hours logged out inside city/inn.

**Comment by ratkosrb** [comment]
Normally debuffs do not tick while you are offline, unless they have the real time duration attribute, which only Deserter has to my knowledge, but maybe there is a max limit, and after 8 hours they are dropped?

**Comment by Daribon** [comment]
> Normally debuffs do not tick while you are offline, unless they have the real time duration attribute, which only Deserter has to my knowledge, but maybe there is a max limit, and after 8 hours they are dropped?

yes its plausible that all debuffs after dropped after 8 hours.

**Comment by NickTyrer** [comment]
@Daribon You are correct, have updated accordingly.
