### ISSUE TITLE
about mysql set

### ISSUE THREAD

**Issue by DarkmoonRabbit** [vmangos/core#130]
@ratkosrb hi brother, is your mysql configuration file (my.ini) set:

sql_mode=NO_ENGINE_SUBSTITUTION, STRICT_TRANS_TABLES 
default-storage-engine = MyISAM or INNODB?

This option? Is it necessary to set it?

**Comment by ratkosrb** [comment]
I use mysql 5.5 with default settings. I have not modified my.ini at all. The only option i specify to mysql.exe on startup is --max_allowed_packet=128M so that i can run large sql files without splitting the queries.
