### ISSUE TITLE
🐝 [Bug] Pyrewood Ambush

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#1300]
## 🐝 Bug report - Quest
Once the quest is completed or failed the questgiver flag is not re added to the creature Deathstalker Faerleia
https://classic.wowhead.com/quest=452/pyrewood-ambush

### Version & Environment
Commit Hash:  60c8057

**Comment by GrenderG** [comment]
Related: https://github.com/vmangos/core/issues/223

**Comment by NickTyrer** [comment]
Diddnt see that
