### ISSUE TITLE
🐞 [Bug] Gnomish Net-o-Matic Projector

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#1304]
## 🐞 Bug report - Spell
When the Projector backfires you cannot escape from the net using shapeshifting or escape artist. (This was possible in classic)
see: https://youtu.be/VdPdEfihOL0

Client Version: 1.12.1

Commit Hash: 60c8057

**Comment by ratkosrb** [comment]
Do you have any video showing it removes it in classic? It can't be removed due to this commit ported from cmangos.
https://github.com/vmangos/core/commit/013805197670c8068101c852b58cbe229b7dc9dc

**Comment by NickTyrer** [comment]
Comments here backing my claim:
https://classic.wowhead.com/item=10720/gnomish-net-o-matic-projector#comments
https://us.forums.blizzard.com/en/wow/t/ok-i-deleted-my-gnomish-net-o-matic-projector/624365
It is wrong currently.

**Comment by NickTyrer** [comment]
Also the spell keeps getting applied at login https://youtu.be/B2y5RLcwAOA

**Comment by killerwife** [comment]
I linked a commit, recheck pls.

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/4e5d73693819fadb3bde48e81d17f59a0b29fdeb
