### ISSUE TITLE
🐞 [Bug] Amplify Curse

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#1307]
## 🐞 Bug report - Spell
Amplify Curse is not consumed when Curse of Exhaustion is cast
see: https://youtu.be/iO4PMfAMdZA

Client Version: 1.12.1
Commit Hash: aa50cc3

**Comment by Daribon** [comment]
Is the bonus from amplify curse being applied to Curse of Exhaustion?

**Comment by LEO33SoFo** [comment]
I confirm this issue, as of 7b83d9952f32559b72f7094e389631f4a30ef7b0.

**Comment by vetu104** [comment]
Faintly remember it being this way in Classic as well.

**Comment by NickTyrer** [comment]
Tested in SoM and Amplify Curse is consumed by Curse of Exhaustion

**Comment by Gelori** [comment]
tested in on "Core revision: b00b1f4ca4fac047be4f / 2022-06-17 15:32:44 +0300 / Linux_x64 (little-endian)"

Amplify Curse is actually Amplifying the Curse of Exhaustion - making target moving slower than without Buff, Only "not consumed part" has to be fixed.

**Comment by Daribon** [comment]
Tested on https://github.com/vmangos/core/commit/b00b1f4ca4fac047be4fecfb8500f888540bf928.
Amplify Curse buff is not removed upon using Curse of Exhaustion.
