### ISSUE TITLE
🐝 [Bug] Attunement to the Core

### ISSUE THREAD

**Issue by Vanheden** [vmangos/core#1313]
## 🐝 Bug report - Quest
As a Dwarf I cannot take the quest Attunement to the Core

https://classic.wowhead.com/quest=7848/attunement-to-the-core

### Expected behavior
Dwarf should be able to take it

### Steps to reproduce
Make a Dwarf and try to get the quest at the Blood Elf

### Version & Environment
  - 1.12.1.5875
  - 1.3 & 1.4
  
Commit Hash:  5591fba5315c48f0c8aaafe366ff7a1ddb443ad8
OS Client: Windows 10
OS Server: Windows 10

**Comment by ratkosrb** [comment]
```
World of Warcraft Client Patch 1.5.0 (2005-06-07)
- Dwarven Priests may now undertake the Molten Core discovery quest; 
  "Attunement to the Core." By fixing this bug, we had to open the 
  quest to all players once more. If you have already done the quest, 
  you will not be required to do it again in order to access the Molten 
  Core via the portal.
  ```

This is from the official 1.5 patch notes, so I believe this bug is blizzlike.

**Comment by Vanheden** [comment]
> ```
> World of Warcraft Client Patch 1.5.0 (2005-06-07)
> - Dwarven Priests may now undertake the Molten Core discovery quest; 
>   "Attunement to the Core." By fixing this bug, we had to open the 
>   quest to all players once more. If you have already done the quest, 
>   you will not be required to do it again in order to access the Molten 
>   Core via the portal.
> ```
> 
> This is from the official 1.5 patch notes, so I believe this bug is blizzlike.

I tested now with patch 1.5 and it works with Dwarf. Is there a way to get around this before patch 1.5?

**Comment by Daribon** [comment]
Before patch 1.5 in vanilla, all dwarves are auto attuned to molten core.

![firefox_6BGJWez41w](https://user-images.githubusercontent.com/6137576/130221979-492dddd5-865e-43a5-b52a-1a860337fae8.png)

We do know that all dwarves were auto attuned to Molten Core before at least April 28th 2005. The patch that would "fix" this the other user says would come at the end of May 2005, Patch 1.5.0 was released in June 7 2005.

The only possible bug here is that all dwarves except dwarf priest would still be able to do the quests, even if they were auto attuned. However I haven't seen any post really mentioning a dwarf doing the quest pre 1.5.0, so I can't be certain if dwarves were still able to do the quest. 

By reading the patch 1.5.0 patch notes and reading the wowhead comment it does seem like all other classes of dwarf were still able to do the quest, even if auto attuned before patch 1.5.0

**Comment by ratkosrb** [comment]
Oh, the auto attunement for dwarfs is already implemented.
https://github.com/vmangos/core/commit/d62ac66d981c31d1478e5e5cec14aff91f0a51eb

Also found some forum discussions on this topic.
https://www.lurkerlounge.com/forums/thread-6394.html?highlight=attunement

![attune1](https://user-images.githubusercontent.com/35845488/130226816-1a38ecbd-2413-42c6-bcab-11132f10fe8e.jpg)

![attune2](https://user-images.githubusercontent.com/35845488/130226821-196ad26f-5675-43db-8560-beea71721f03.jpg)

![attune3](https://user-images.githubusercontent.com/35845488/130226827-783c6265-d312-402b-8e6b-b106305cef54.jpg)

![attune4](https://user-images.githubusercontent.com/35845488/130226832-17ae3c8c-128f-4e10-bf54-ac03e3504255.jpg)

![attune6](https://user-images.githubusercontent.com/35845488/130226849-397d1071-e7b6-453a-943e-4d048390e191.jpg)

**Comment by Vanheden** [comment]
I tested **Patch 1.3** with all classes as **Dwarf** and I managed to get in without doing the quest in a **Raid** by jumping through the window but when jumping through you get the message even tho you get inside the raid "**You must be attuned and in a raid group to enter"** so I guess it's working as intended :)

**Comment by ratkosrb** [comment]
You get that message because there are 2 area triggers. One is for players who have done the quest, the other is for dwarves. In this case the quest trigger activated first, and gave you that error message, and then the dwarf trigger activated and ported you inside.

**Comment by Vanheden** [comment]
> You get that message because there are 2 area triggers. One is for players who have done the quest, the other is for dwarves. In this case the quest trigger activated first, and gave you that error message, and then the dwarf trigger activated and ported you inside.

Okay :) I think this issue can be closed if it works as intended 👍
