### ISSUE TITLE
🐝 [Bug] Gazban NPC

### ISSUE THREAD

**Issue by LEO33SoFo** [vmangos/core#1317]
## 🐝 Bug report

_Gazban_ does not turn into a water elemental during the fight when doing the quest _The Curse of the Tides_.
### Expected behavior

_Gazban_ should turn into a water elemental during the fight when doing the quest _The Curse of the Tides_, according to [Wowpedia](https://wowpedia.fandom.com/wiki/Gazban) and this [video](https://youtu.be/MBuykjMlpJ8?t=147).
### Steps to reproduce

1. `.quest add 611`
2. `.go object id 2576`
3. Use the _Catelyn's Blade_ in the _Altar of the Tides_ to summon _Gazban_.
4. Fight him until the end.

### Version & Environment

Client Version: 
  - 1.12.1.6005

Commit Hash:  
7b83d9952f32559b72f7094e389631f4a30ef7b0

OS Client and Server:
  - Windows XP Professional

### Crashlog

- None

**Comment by GrenderG** [comment]
Related: https://github.com/vmangos/core/issues/1173
