### ISSUE TITLE
Human  Priest should not  be created with a pet.

### ISSUE THREAD

**Issue by caicaicai** [vmangos/core#133]
**Current behavior**: 
when i create a human priest , i got a pet of Warlock's.
**Expected behavior**: 
no pet
**Steps to reproduce**:

1. create a human priest.

**Client version**: 
1.12
**Commit hash**: 
latest developer
**Operating system**: 
win7 server & osx client

**Comment by milestorme** [comment]
cannot repeat , latest revision , windows compile

**Comment by caicaicai** [comment]
after restart server , i can not repeat too... lol
