### ISSUE TITLE
🐛 [Bug] Zeppelins & Boat sometimes not appearing

### ISSUE THREAD

**Issue by Vanheden** [vmangos/core#1336]
🐛 **Bug report**
Sometimes the Boats & Zeppelins don't appear for some reason.
I believe if there's only one faction online and not both they wont work for some reason.

**Expected behavior**
They should appear.

**Steps to reproduce**
Don't really know how, it seems random.

**Client Version:** 1.12.1.5875
**Patch:** 1.4

**Commit Hash:**  f654b36edc476acaf0e6fae2f86abff55b557179

**OS Client:** Windows 10
**OS Server:** Ubuntu 20.04

**Comment by ghost** [comment]
duplicate
