### ISSUE TITLE
🐝 [Bug] In Dreams

### ISSUE THREAD

**Issue by Vanheden** [vmangos/core#1348]
🐝 **Bug report - Quest**
You should be able to complete In Dreams quest by yourself by not aggroing the mobs when Highlord Taelan Fordring dies, when he dies the mob aggro you from far away so you cannot hide from them.

**Expected behavior**
You should be able to hide until Lord Tirion Fordring respawn and kill the mobs.
You should also be able to "die" during the quest and be able to run back in time without the quest being Failed according to wowhead comments.
https://classic.wowhead.com/quest=5944/in-dreams
https://www.youtube.com/watch?t=384&v=qcg8zsEBbM4&feature=youtu.be

**Steps to reproduce**
1. q add 5944
2. Follow Highlord Taelan Fordring.
3. Wait until he dies.

**Version & Environment**
Client Version:  1.12.1.5875
Patch: 1.4

**Commit Hash:**  fdc46ca15c99efc122b604c30694c0f288a8b8d9

**OS Client:** Windows 10
**OS Server:**  Ubuntu 20.04

**Comment by LEO33SoFo** [comment]
I can not complete this quest as of cb5c6020d66be2ed2b1811e4b067bf284aa37614.

I am able to do the quest normally up to _Taelan's Tower_ part, in which _Grand Inquisitor Isillien_ talks with _Highlord Taelan Fordring_. After they finish their conversation, four *Crimson Elite*s attack me, but they don't attack _Highlord Taelan Fordring_. And _Grand Inquisitor Isillien_ does not fight and can not be attacked. Both him and _Highlord Taelan Fordring_ are stuck, which in turn the quest event can't progress.

In **Server.log** I get:
```
ERROR:SCRIPT_COMMAND_ATTACK_START (script id 1212801) for an invalid attack target, skipping.
ERROR:SCRIPT_COMMAND_ATTACK_START (script id 184002) for an invalid attack target, skipping.
```

EDIT: The quest can be completed, but I had to stay in the south side of the road in order for *Crimson Elite*s to target _Highlord Taelan Fordring_.
Also the bugs mentioned by OP still exist.

**Comment by ratkosrb** [comment]
@LEO33SoFo Fixed the attack command failing here https://github.com/vmangos/core/commit/2dd80d81796c0440b12b9fca49298cefaa29e5c1

Also when i did this quest in classic, I did try running away from the mobs, and the quest failed when they evaded. It also failed once I died in the middle and released spirit. But when i died at the end and did NOT release spirit, it completed.

**Comment by ratkosrb** [comment]
You can now die after Tirion starts attacking Isillien. https://github.com/vmangos/core/commit/eb34abed1ce7d103974f3bcdec881a0b551fd415

**Comment by ghost** [comment]
Works as intended now
