### ISSUE TITLE
🐛 [Bug] Tauren hunter graphics bugged (male or female)

### ISSUE THREAD

**Issue by xyphergrim** [vmangos/core#1355]
## 🐛 Bug report

I can create male/female taurens of other classes, but when I create a hunter (male/female) it is bugged graphically.

![image](https://user-images.githubusercontent.com/23463778/136645255-5b052f2c-48f2-4c6a-a291-bc1bb92731bd.png)
![image](https://user-images.githubusercontent.com/23463778/136645259-eea5ff2b-294b-498d-9662-6c2de78e7551.png)

### Expected behavior

Should be able to create a Tauren Hunter (male/female) and see the avatar in game.

### Steps to reproduce

1. Create a new Tauren Hunter (male or female)
5. Profit

### Version & Environment

1.12.1

OS Client: Win 10
OS Server:  Win 10

**Comment by Daribon** [comment]
I would assume that this is a client issue on your end, since it does appear to use the correct displayid.
Try with a different client and check if the issue remains.
