### ISSUE TITLE
🐛 [Bug]The partybot will cause the server to crash~

### ISSUE THREAD

**Issue by gamelgs** [vmangos/core#1357]
## 🐛 Bug report

.partybot cometome

### Expected behavior

When the partybot is in combat, the player goes to other maps and calls them come to me with commands.The server will crash~

### Version & Environment

Client Version: - 1.12.1.5875

Commit Hash:  edcc1065b4b4220e24db209c26a78dd690651227

OS Client: Win10
OS Server: Win10

### Crashlog

- None

**Comment by ratkosrb** [comment]
I cannot reproduce the issue. I send the bots to attack something, i teleport to another map, and spam .partybot cometome but nothing happens. The server does not crash.

**Comment by gamelgs** [comment]
> I cannot reproduce the issue. I send the bots to attack something, i teleport to another map, and spam .partybot cometome but nothing happens. The server does not crash.

Clone 39 Rogue partybot Attack Training Dummy.

**Comment by ratkosrb** [comment]
What training dummy?

**Comment by gamelgs** [comment]
> What training dummy?
![1](https://user-images.githubusercontent.com/54333950/139572856-f428127b-a2a7-47e2-835d-e3d2e1ccd01a.png)
![2](https://user-images.githubusercontent.com/54333950/139572861-356b522d-1826-4356-970b-ed6861469f08.png)
Here

**Comment by ratkosrb** [comment]
So it crashes only when fighting the custom training dummy? That sounds like a bug in the dummy's script, not with the party bots.
