### ISSUE TITLE
🐛 [Bug] Hammertoe Grez NPC

### ISSUE THREAD

**Issue by LEO33SoFo** [vmangos/core#1360]
## 🦂 Bug report - Dungeon

- _Hammertoe Grez_ is kneeling.
- _Hammertoe Grez_ does not say a specific quote and does not die after accepting the _Prospect of Faith_ (1) quest.
### Expected behavior

- _Hammertoe Grez_ should be sitting instead of kneeling, as per _Classic_, according to _Wowhead_ [comments](https://classic.wowhead.com/npc=2909/hammertoe-grez#comments) and this [video](https://www.youtube.com/watch?v=x1GulbpV0FM).
- _Hammertoe Grez_ should say a specific quote and die after accepting the _Prospect of Faith_ (1) quest, according to this [video](https://www.youtube.com/watch?v=x1GulbpV0FM).
### Steps to reproduce

1. Make sure you have completed the _Amulet of Secrets_ quest first.
2. `.go creature id 2909`
3. Check his staying position and accept the _Prospect of Faith_ quest, and observe his behavior.

### Version & Environment

Client Version: 
  - 1.12.1.6005

Commit Hash:  
b4517ac77a4918cda34615a54d6cd423097221fc

OS Client and Server:
  - _Windows XP Professional_ 32bit
### Crashlog

- None

**Comment by NickTyrer** [comment]
Closed in #1308
