### ISSUE TITLE
🐝 [Bug] Prospect of Faith (2) quest

### ISSUE THREAD

**Issue by LEO33SoFo** [vmangos/core#1361]
## 🐝 Bug report - Quest

_Hammertoe's Spirit_ does not spawn and _Historian Karnik_ does not do a dialogue with him after doing the quest _Prospect of Faith_ (2).
This issue is the exact duplicate of https://github.com/azerothcore/azerothcore-wotlk/issues/7748, described more detailed there.
### Expected behavior

_Hammertoe's Spirit_ should spawn and should do a dialogue with _Historian Karnik_ after doing the quest _Prospect of Faith_ (2).
### Steps to reproduce

1. `.quest add 724`
2. `.go creature id 2916`
3. Turn in the quest and check this problem.

### Version & Environment

Client Version: 
  - 1.12.1.6005

Commit Hash:  
b4517ac77a4918cda34615a54d6cd423097221fc

OS Client and Server:
  - _Windows XP Professional_ 32bit

### Crashlog

- None

**Comment by NickTyrer** [comment]
Closed in #1308
