### ISSUE TITLE
🐞 [Bug] Shaman Elemental Focus needs to proc Clearcasting on cast, not on land.

### ISSUE THREAD

**Issue by Velite12** [vmangos/core#1363]
## 🐞 Bug report - Spell

The shaman talent Elemental Focus activates clearcasting when the shaman lands a fire/frost/nature spell on a target currently. According to 2006 vanilla and classic vanilla, Elemental Focus should activate clearcasting when the fire/frost/nature spell is casted, just as the description states. Also, the buff itself should be consumed on cast, of which the spell effect is but the buff persists until the spell lands.

![image](https://user-images.githubusercontent.com/45871932/137520954-32582b84-21a3-435b-9d57-4426bfa30ca2.png)

### Expected behavior

Elemental Focus should activate clearcasting when the fire/frost/nature spell is casted, just as the description states.

Proof:

Classic:

In this video we can see that Clearcasting triggers on cast, not on land, because it does not activate before Elemental Mastery triggers, which triggers on land. We also see that the clearcasting buff is also removed on spell cast, not land.

The flow of events here:

Elemental Mastery activated by caster -> lightning bolt is casted -> clearcasting activates -> lightning bolt hits -> Elemental Mastery is consumed to deliver the crit.

The flow of events on Vmangos:

Elemental Mastery activated by caster -> lightning bolt is casted  -> lightning bolt hits -> Elemental Mastery is consumed to deliver the crit -> clearcasting activates.

https://www.youtube.com/watch?v=NEujh_Dcheg&t=710s

![image](https://user-images.githubusercontent.com/45871932/137520142-daeff565-ace0-44ff-a87e-a29e6df4c8bf.png)

Vanilla 2006:

https://www.youtube.com/watch?v=JE_KzAEBIVc&t=48s

We can see the same behavior at play here, clearcasting triggers after the lightning bolt finishes cast, not on land.

https://streamable.com/zcy2mi

More testing in classic.

### Steps to reproduce

1. For testing you can set the proc chance on Elemental focus spell 16164 to be 100%.
2. Put a talent point into Elemental Focus on a Shaman
3. Cast Lightning Bolt
4. Clearcast will not trigger until the bolt hits the target, which is wrong behavior. When it triggers, it will not be consumed until the next spell lands, not casts.
5. Profit

Client Version: 
1.12.1.5875

**Comment by ratkosrb** [comment]
Fixed.
