### ISSUE TITLE
🐝 [Bug] To Serve Kum'isha quest

### ISSUE THREAD

**Issue by LEO33SoFo** [vmangos/core#1371]
## 🐝 Bug report - Quest

After completing _To Serve Kum'isha_ quest, there is no outro event from _Kum'isha_.

Similar to issue https://github.com/TrinityCore/TrinityCore/issues/22655.
### Expected behavior

There should be an outro event after completing _To Serve Kum'isha_ quest, according to _Wowhead_ [comments](https://classic.wowhead.com/quest=2521/to-serve-kumisha#comments).
### Steps to reproduce

1. `.quest add 2521`
2. `.quest complete 2521`
3. `.go creature id 7363`
4. Turn in the quest and check if there is an outro event.

### Version & Environment

Client Version: 
- 1.12.1.6005

Commit Hash:  
b4517ac77a4918cda34615a54d6cd423097221fc

OS Client and Server:
- _Windows XP Professional_ 32bit

### Crashlog

- None

**Comment by NickTyrer** [comment]
Closed in #1308
