### ISSUE TITLE
🚀 [Feature] 32bit Windows precompiled binaries in GitHub Releases

### ISSUE THREAD

**Issue by LEO33SoFo** [vmangos/core#1374]
## 🚀 Feature

Because of 53db447cb6fb8f01e60fb58c72fd08609a877096, can 32bit _Windows_ precompiled binaries be supported like the 64bit ones? Including support for _Windows XP_, which requires older _ACE_ and _TBB_ libraries.

### Benefits, Purpose

The benefit and the purpose is obvious: no need to manually compile all the time the project whose target is the 32bit _Windows_ OS.

**Comment by ratkosrb** [comment]
I think the option to target XP was removed in VS 2019, which is what Github Actions uses to compile the release. Even if the build was 32 bit, those binaries would not run on XP because they are compiled for newer versions of Windows.

**Comment by ratkosrb** [comment]
```
Note that VS 2017 includes support for Windows XP via v141_xp. For VS 2019, this feature is no longer being updated but you can still install the v141_xp toolset to use with the VS 2019 IDE.
```
https://stackoverflow.com/questions/35664861/how-to-target-windows-xp-in-microsoft-visual-studio-c/35666906

**Comment by coolzoom** [comment]
Yes, the GitHub action virtual environments are pre-defined, can't really change that as far as I can tell.
and it is only able to control by command line, actions require click or such is not possible.
https://github.com/actions/virtual-environments

the 32bit OS only has around 3.75GB of memory and the OS will limit a single process RAM usage below 2GB, which is not as powerful as a raspberry pi if we talking about running a server.
also, our VMaNGOS requires at least 4GB for pre-loaded terrain iirc. although it can be turned off which makes the performance/stability even lower.

**Comment by T1ti** [comment]
Honestly devs shouldn't bother catering to the 0.5%(or even less) that still use windows XP
If you wanna be part of that, compile yourself

**Comment by ratkosrb** [comment]
The core itself will continue to work on XP indefinitely, but we can't provide precompiled binaries for it, since the CI uses new version of Visual Studio. You will have to compile it yourself with 2015 or 2017.

**Comment by LEO33SoFo** [comment]
> Honestly devs shouldn't bother catering to the 0.5%(or even less) that still use windows XP

Well because this is a _WoW_ Vanilla emulator, and _WoW_ itself (including the patches and the client) were released in 2004 - 2006, when _Windows XP_ was the main supported OS and newer ones still not released. So I think _Windows XP_ deserves a little support, within limits of course.

> The core itself will continue to work on XP indefinitely

Glad to hear that.
