### ISSUE TITLE
🐝 [Bug] The Bait for Lar'korwi quest

### ISSUE THREAD

**Issue by LEO33SoFo** [vmangos/core#1376]
## 🐝 Bug report - Quest

- Just using only one of the quest items (The _Preserved Threshadon Meat_ or the _Preserved Pheromone Mixture_) will spawn _Lar'korwi_.
- _Lar'korwi_ spawns near and does not charge into me, a bit similar to #1351.
### Expected behavior

- To summon _Lar'korwi_ both the quest items need to be used and placed, first the _Preserved Threshadon Meat_ and then the _Preserved Pheromone Mixture_. And only then should _Lar'korwi_ be summoned.
- _Lar'korwi_ should spawn a bit farther and should charge towards me.

Source: Wowhead [comments](https://classic.wowhead.com/quest=4292/the-bait-for-larkorwi#comments) and this [video](https://youtu.be/JmBwzMlYZ10?t=86).
### Steps to reproduce

1. `.quest add 4292`
2. `.go xyzo -7193.689453 -2418.811768 -217.428894 4.710205 1`
3. Do the quest and check for the aforementioned issues.

### Version & Environment

Client Version: 
- 1.12.1.6005

Commit Hash:  
40abd16d70d87f0a916a006f47d6cba4884feec8

OS Client and Server:
- _Windows XP Professional_ 32bit

### Crashlog

- None

**Comment by NickTyrer** [comment]
Closed in #1467
