### ISSUE TITLE
whether clang compilation is supported ?

### ISSUE THREAD

**Issue by left3721** [vmangos/core#138]
system:FreeBSD 12.0
Compiler:Clang 7.0.1

cmake -DCMAKE_C_COMPILER=/usr/local/bin/clang70 -DCMAKE_CXX_COMPILER=/usr/local/bin/clang++70 ..
-- The C compiler identification is Clang 7.0.1
-- The CXX compiler identification is Clang 7.0.1
-- Check for working C compiler: /usr/local/bin/clang70
-- Check for working C compiler: /usr/local/bin/clang70 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/bin/clang++70
-- Check for working CXX compiler: /usr/local/bin/clang++70 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detected 64-bit platform.
-- Found Git: /usr/local/bin/git  
-- 
This script builds the MaNGOS server.
  Options that can be used in order to configure the process:
    PREFIX: Path where the server should be installed to
    PCH: Use precompiled headers
    DEBUG: Debug mode
  To set an option simply type -D<OPTION>=<VALUE> after 'cmake <srcs>'.
  For example: cmake .. -DDEBUG=1 -DPREFIX=/opt/mangos

-- Found ACE library: /usr/local/lib/libACE.so
-- Found ACE headers: /usr/local/include
-- Found TBB: /usr/local/include (found version "2019.0") found components:  tbbmalloc 
-- Using mysql-config: /usr/local/bin/mysql_config
-- Found MySQL library: /usr/local/lib/mysql/libmysqlclient.so
-- Found MySQL headers: /usr/local/include/mysql
-- Found OpenSSL library: /usr/lib/libssl.so
-- Found OpenSSL headers: /usr/include/openssl
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
-- 
-- Core revision: ffb2c9c8378b42ba81ea 2019-02-08 16:50:00 +0200 
-- Supported version: CLIENT_BUILD_1_12_1
-- Install server to: /root/server
-- 
-- Use PCH               : No
-- PGO profile           : Disabled
-- Memory allocation     : TBB/Release /usr/local/lib/libtbbmalloc.so;/usr/local/lib/libtbb.so
-- Detected compiler     : Clang
-- Build in debug-mode   : No  (default)
-- Use anticheat    : No  (default)
-- Build scripts    : Yes (default)
-- Debug symbols         : Disabled
-- Build flags (RELEASE) : -O3 -DNDEBUG  -std=c++14 --no-warnings -fexceptions -fnon-call-exceptions -march=native -O3 -pipe 
-- Build flags (DEBUG)   : -g  -std=c++14 --no-warnings -fexceptions -fnon-call-exceptions -march=native -O3 -pipe 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /root/server/build
root@Server:~/server/build # make
Scanning dependencies of target g3dlite
[  0%] Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/AABox.cpp.o
[  0%] Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/Box.cpp.o
[  0%] Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/Crypto.cpp.o
[  1%] Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/format.cpp.o
In file included from /root/erver/dep/src/g3dlite/format.cpp:12:
/root/server/dep/include/g3dlite/G3D/System.h:123:20: error: field has incomplete type 'struct timeval'
    struct timeval m_start;
                   ^
/root/server/dep/include/g3dlite/G3D/System.h:123:12: note: forward declaration of 'G3D::timeval'
    struct timeval m_start;
           ^
1 error generated.
*** Error code 1

Stop.
make[2]: stopped in /root/server/build
*** Error code 1

Stop.
make[1]: stopped in /root/server/build
*** Error code 1

Stop.
make: stopped in /root/server/build

**Comment by ratkosrb** [comment]
Well... if it fails to build, then i guess it's not. I have personally only used gcc and msvc, so i don't know how to help you. But if you do figure out how to build it with clang, you are welcome to submit a fix, provided it doesn't break compilation with the other two.

**Comment by InnaCL** [comment]
try adding "/root/server/dep/include/g3dlite/G3D/System.h"
#include <sys/time.h>
