### ISSUE TITLE
🐛 [Bug] Caravan Mule event

### ISSUE THREAD

**Issue by LEO33SoFo** [vmangos/core#1383]
## 🐛 Bug report

Is the _Caravan Mule_ event implemented, which involve the _Caravan Mule_, _Writ of Safe Passage_ quest, _Guard Didier_, and _Field Marshal Chambers_, which they are not spawned.
I don't see it occurring during the specified times, as per this [Wowpedia](https://wowpedia.fandom.com/wiki/Writ_of_Safe_Passage_(quest)) article.
### Expected behavior

Everything is explained to comments of issue https://github.com/TrinityCore/TrinityCore/issues/14947.
### Version & Environment

Client Version: 
- 1.12.1.6005

Commit Hash:  
40abd16d70d87f0a916a006f47d6cba4884feec8

OS Client and Server:
- _Windows XP Professional_ 32bit

### Crashlog

- None

**Comment by Kittnz** [comment]
Got no sniffed data for this..

**Comment by NickTyrer** [comment]
@Oroxzy has the data for this.

**Comment by NickTyrer** [comment]
Closed here https://github.com/vmangos/core/commit/2ab1c05e70dd513effbe9cbec4bfad0341541691
