### ISSUE TITLE
🐛 [Bug]VMap extractor

### ISSUE THREAD

**Issue by dd667** [vmangos/core#1384]
## 🐛 Bug report
Compiled fresh core + tools. Trying to extract & assemble when coming across this issue.

### Steps to reproduce
1. Compile new core
2. Attempt extracting data
3. When extracting/assembling vmaps error pops

### Version & Environment
  Client Version:
  - 1.12.1.5875

  Commit Hash:
  https://github.com/vmangos/core/tree/2f58b8c

  Operating System:
  - Win 10

### Crashlog
Seems to be too big for the frames: https://pastebin.com/LQBj60xv

**Comment by coolzoom** [comment]
tested and it looks fine to me. 
tested both on my personal computer(win10+vs2019),
and github runner(win server 2019 + vs2019) 
client 1.12.1.5875 enGB client
https://github.com/coolzoom/vmangos-pack/runs/4242103168?check_suite_focus=true
are you using the clean client? maybe download a clean one and try again.

**Comment by dd667** [comment]
Yeah tried it on both old client from hdd I had since game launched and fresh one, same result.
Will try to clone repo again, recompile and extract when I have day off. Thanks for checking, means it might be defective file on my end rather than in vmangos.

**Comment by dd667** [comment]
Haven't played it in a while and forgot about HD graphics patch. It seems to be all fine now.
