### ISSUE TITLE
🐝 [Bug]QUEST <Decoy!>cannot be completed~Bag of Gold cannot be used at the delivery point

### ISSUE THREAD

**Issue by gamelgs** [vmangos/core#1388]
### Expected behavior

QUEST ID 8606  
ITEM ID 21041

Bag of Gold cannot be used at the delivery point

### Steps to reproduce

1          .go 5090.355 -5107.947 928.420 1
2       .quest add 8606

### Version & Environment

Client Version: - 1.12.1.5875

Commit Hash:  2f58b8ccf00c4b24aa01cb603dbaabc41ffcc5d5

OS Client: - Win 10
OS Server: - Win 10

### Crashlog

- None

**Comment by NickTyrer** [comment]
Closed in  #1467
