### ISSUE TITLE
about latest database updates

### ISSUE THREAD

**Issue by chenps10** [vmangos/core#139]
I see that the latest update is the characters database structure update, so how to update the database that already has player data?

**Comment by alexkulya** [comment]
@chenps10
The update adds a new table to the characters database, it does not change the existing ones.
[Try this SQL](https://github.com/vmangos/core/blob/ffb2c9c8378b42ba81ea7f2e80967a93f0f192d7/sql/old_migrations/20190109163701_characters.sql)

**Comment by ratkosrb** [comment]
Just apply the migration.

**Comment by chenps10** [comment]
ok，tks for all
