### ISSUE TITLE
🐜 [Bug] Mounts

### ISSUE THREAD

**Issue by Maurowin** [vmangos/core#1390]
## 🐜 Bug report - Progression

I use patch 1.12 and the 60% mounts requires a skill only available in the first patch.

![Sans titre](https://user-images.githubusercontent.com/31663279/142663411-21f8b17c-2c1f-492b-ace6-54af495944c2.png)

### Expected behavior

Be able to use the 60% mounts with the riding skills from patch 1.12.

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  
3c7eb0a

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by ratkosrb** [comment]
Delete your WDB cache folder.

**Comment by Maurowin** [comment]
You'r right !

There is no possibility on the server side to reset the cache?

**Comment by ratkosrb** [comment]
No. The cache is reset when a new patch is installed on the client. But since you are running the same client version, and not patching it, the cache will remain.
