### ISSUE TITLE
🐞 [Bug] Princess Summons Portal (13912 ID) spell

### ISSUE THREAD

**Issue by LEO33SoFo** [vmangos/core#1391]
## 🐞 Bug report - Spell

No _Ironforge_ portal appears when _Princess Moira Bronzebeard_ casts the portal spell after defeating _Emperor Dagran Thaurissan_.
### Expected behavior

There should be a portal to _Ironforge_ in a specific position after _Princess Moira Bronzebeard_ casts the portal spell, as seen in the database with:
```mysql
SELECT * FROM `spell_target_position` WHERE `id` = 13912;
```
### Steps to reproduce

1. `.go xyzo 1380.58 -819.48 -92.72 4.69 230` (this is the exact position the portal is supposed to appear.)
2. Kill _Emperor Dagran Thaurissan_ while keeping alive _Princess Moira Bronzebeard_.
3. Check if the portal appears after _Princess Moira Bronzebeard_ successfully casts the aforementioned spell.

### Version & Environment

Client Version: 
- 1.12.1.6005

Commit Hash:  
40abd16d70d87f0a916a006f47d6cba4884feec8

OS Client and Server:
- _Windows XP Professional_ 32bit

### Crashlog

- None

**Comment by scottnice** [comment]
Looked into this. This portal effect being used here is old and marked as deprecated. I wonder if that is related.

**Comment by ratkosrb** [comment]
Where is the proof? In my 1.13 sniff of saving the princess, there is no portal opened.
https://streamable.com/1eq98e

The only reference to a portal I could find is this comment from 2007, which is from TBC. We should not be introducing functionality from other expansions.
![Untitled](https://user-images.githubusercontent.com/35845488/148287118-9946b4b1-5114-4bdb-a3ba-1e8497ba7187.jpg)

**Comment by scottnice** [comment]
> Where is the proof? In my 1.13 sniff of saving the princess, there is no portal opened. https://streamable.com/1eq98e
> 
> The only reference to a portal I could find is this comment from 2007, which is from TBC. We should not be introducing functionality from other expansions. ![Untitled](https://user-images.githubusercontent.com/35845488/148287118-9946b4b1-5114-4bdb-a3ba-1e8497ba7187.jpg)

@ratkosrb she already casts the portal spell but nothing appears. If this was added in TBC then we need to remove her spell cast here:
                    m_creature->CastSpell(m_creature, SPELL_OPEN_PORTAL, false);
https://github.com/vmangos/core/blob/development/src/scripts/eastern_kingdoms/burning_steppes/blackrock_depths/boss_emperor_dagran_thaurissan.cpp
