### ISSUE TITLE
🐛 [Bug] Abomination-type NPCs' walking animation problem

### ISSUE THREAD

**Issue by LEO33SoFo** [vmangos/core#1393]
## 🐛 Bug report

All Abomination-type NPCs I have encountered so far do not have animation when they walk.
Is this a core bug?

https://user-images.githubusercontent.com/48962426/142773117-ebffb81c-c9d8-4b36-9134-dcdc3d565b24.mp4

### Steps to reproduce

1. `.go xyzo 2857.617432 -3874.182617 107.829636 0.176506 0` as an example.
2. Check the *Stitched Horror*s.

### Version & Environment

Client Version: 
- 1.12.1.6005

Commit Hash:  
40abd16d70d87f0a916a006f47d6cba4884feec8

OS Client and Server:
- _Windows XP Professional_ 32bit
### Crashlog

- None

**Comment by NickTyrer** [comment]
It had an incorrect aura. It should be fixed in the latest commit.

**Comment by ratkosrb** [comment]
That one made me laugh out loud :smile:
