### ISSUE TITLE
🐛 [Bug] Enchanting Runed Rod

### ISSUE THREAD

**Issue by Maurowin** [vmangos/core#1395]
## 🐛 Bug report

It seems that the upper rod cannot replace the lower ones, at least the gold rod does not replace the silver one etc..., I have not checked for the runic

### Expected behavior

the upper rod replaces, as the description indicates, all the rods below it

### Steps to reproduce

1. Learn Enchant profession
2. try to use gold rod for an enchantment who requier silver rod and below
3.
4. ...
5. Profit

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  
1c7deee

OS Client: windows 10
OS Server: linux ubuntu server 20.04

### Crashlog

- None

**Comment by LEO33SoFo** [comment]
According to this [comment](https://www.reddit.com/r/classicwow/comments/bt3mxx/enchanting_rods_backwards_compatible/eotnyf4/), and the Patch 2.0.1 [changelog](https://wowpedia.fandom.com/wiki/Patch_2.0.1):

> Spells can now require either a totem item or a totem category item to cast a spell. This means that **the Enchanting Rods now count as all of the lower level enchanting rods as well, so you only need a single enchanting rod instead of all six**. This also means that "Finkle's Skinner" now counts as a Skinning Knife. Several weapons that are picks have been flagged as counting as a Mining pick as well.

So this seems to be the intended behavior until _The Burning Crusade_.

**Comment by Maurowin** [comment]
![unknown](https://user-images.githubusercontent.com/31663279/143658690-f5cffc3f-9964-4a4a-ba78-ff41df41736a.png)
@LEO33SoFo In this image from the vMangos server (FR client) it says in yellow, "Can replace all lower enchantment rune rods."

**Comment by GrenderG** [comment]
> ![unknown](https://user-images.githubusercontent.com/31663279/143658690-f5cffc3f-9964-4a4a-ba78-ff41df41736a.png) @LEO33SoFo In this image from the vMangos server (FR client) it says in yellow, "Can replace all lower enchantment rune rods."

That's just wrong, that "yellow text" wasn't added until TBC. https://fr.classic.wowhead.com/item=16207/ vs https://fr.tbc.wowhead.com/item=16207/.

Please don't take other emulators or private servers as a source.

**Comment by GrenderG** [comment]
> ![unknown](https://user-images.githubusercontent.com/31663279/143658690-f5cffc3f-9964-4a4a-ba78-ff41df41736a.png) @LEO33SoFo In this image from the vMangos server (FR client) it says in yellow, "Can replace all lower enchantment rune rods."

That's a bug indeed, some translated texts come from later expansions so issues like this can be present in languages different than English.

**Comment by Maurowin** [comment]
Ah yes, in this case indeed we can have some problems ^^
So, the bug here is the display of bad translation.
![image](https://user-images.githubusercontent.com/31663279/143675872-f3d13041-a0cb-41fb-9a3f-5974b52cfc24.png)
