### ISSUE TITLE
🐝 [Bug] quest id 3503

### ISSUE THREAD

**Issue by Maurowin** [vmangos/core#1396]
## 🐝 Bug report - Quest

you can make the quest loop without having done anything and without having an object.

You don't win anything but it is indicated in the chat that the quest has been completed.
### Expected behavior

to have done or to have the pre-requisite to be able to make the quest

### Steps to reproduce

1. add q 3503
2. talk to the pnj
3.
4. ...
5. Profit

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  
1c7deee

OS Client: windows 10
OS Server: ubuntu 20.04

### Crashlog

- None

**Comment by NickTyrer** [comment]
The prequest was only a requirement in a previous patch
https://classic.wowhead.com/quest=3381/a-meeting-with-the-master#comments

**Comment by ratkosrb** [comment]
@NickTyrer We need to implement the old state too, this is not just a 1.12 emulator. Seems like it changed in patch 1.7.

**Comment by ratkosrb** [comment]
Nevermind, seems like the old state is already implemented too.
