### ISSUE TITLE
🐛 [Bug] crystal in blasted lands

### ISSUE THREAD

**Issue by Maurowin** [vmangos/core#1397]
## 🐛 Bug report

creatures that can become immune to damage do not lose their immunity to crystals 
### Expected behavior

creatures that can become immune to damage must lose their immunity to crystals 
### Steps to reproduce

1. go into blasted lands and engage for exemple the creature id 7670 (guid 2813)
2. wait for him immunity
3. go near the crystal
4. try to kill him
5. Profit

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  1c7deee

OS Client: Win 10
OS Server: Linux ubuntu server 20.04

### Crashlog

- None

**Comment by LEO33SoFo** [comment]
I was in _The Stones That Bind Us_ quest in order for *Stone*s _of Binding_ to be usable by me.

Without that quest, *Servant*s _of Allistarj_ can't be killed, according to some _Wowhead_ [comments](https://classic.wowhead.com/npc=7670/servant-of-allistarj#comments).

**Comment by NickTyrer** [comment]
Working as intended for me.
