### ISSUE TITLE
about vmangos domain 

### ISSUE THREAD

**Issue by DarkmoonRabbit** [vmangos/core#14]
@ratkosrb 
I registered the vmangos.org domain name and currently .com / .net is not registered! Please register first. 
I will use vmangos.org as a promotional vmangos and provide a vmangos pre-compiled download site.
If there are other needs, I can assign vmangos.org to the analysis you need.

**Comment by ratkosrb** [comment]
I don't have any plans for a website. Github is entirely sufficient for the purposes of this project. Any questions can be asked by opening an issue, and helpful information can be posted on the wiki repo.
