### ISSUE TITLE
🐛 [Bug] swiming up

### ISSUE THREAD

**Issue by Maurowin** [vmangos/core#1400]
## 🐛 Bug report

When we press the space bar instead of swimming vertically we make a jump.
### Expected behavior

Swiming up
### Steps to reproduce

1. go under water
2. press barre space
3. see
4. ...
5. Profit

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  1c7deee

OS Client: Win 10
OS Server: Ubuntu server 20.04

### Crashlog

- None

**Comment by ratkosrb** [comment]
This is not a bug, and has nothing to do with the server emulator either. This is how movement in water works in the Vanilla client. It was changed in TBC to float up instead.
