### ISSUE TITLE
🐛 [Bug] Spectral Defender and Spectral Betrayer NPCs near the Skull of Horgus object

### ISSUE THREAD

**Issue by LEO33SoFo** [vmangos/core#1401]
## 🐛 Bug report

*Spectral Betrayer*s are not fighting with *Spectral Defender*s when getting the *Skull of Horgus* for the *Villains of Darrowshire* quest.

Same issue as https://github.com/TrinityCore/TrinityCore/issues/4385#issuecomment-687929323.
### Expected behavior

*Spectral Betrayer*s should be fighting with *Spectral Defender*s when getting the *Skull of Horgus* for the *Villains of Darrowshire* quest.

Video proof [here](https://youtu.be/JH5KAXGdRkQ?t=72).
### Steps to reproduce

1. `.quest add 5181`
2. `.go object id 176208`
3. Check the nearby mobs.

### Version & Environment

Client Version: 
- 1.12.1.6005

Commit Hash:  
40abd16d70d87f0a916a006f47d6cba4884feec8

OS Client and Server:
- _Windows XP Professional_ 32bit

### Crashlog

- None

**Comment by ratkosrb** [comment]
Didn't we just fix this in this commit? https://github.com/vmangos/core/commit/da57123d91afb30c71ca866e26305ff73552ac6e

**Comment by NickTyrer** [comment]
Correct
