### ISSUE TITLE
🐝 [Bug] Loramus quest

### ISSUE THREAD

**Issue by LEO33SoFo** [vmangos/core#1407]
## 🐝 Bug report - Quest

There are some missing words and missing punctuation while talking with _Loramus Thalipedes_.
### Expected behavior

There should be no word spelling and punctuation errors when talking with _Loramus Thalipedes_, as specified [here](https://wowpedia.fandom.com/wiki/Loramus_(quest)).
### Steps to reproduce

1. `.quest add 3141`
2. `.go creature id 7783`
3. Continue the quest by talking to him and check the few word errors.

### Version & Environment

Client Version: 
- 1.12.1.6005

Commit Hash:  
aff74e684ad4a9cc0bc21722a4106b1eb43a56d3

OS Client and Server:
- _Windows XP Professional_ 32bit

### Crashlog

- None

**Comment by NickTyrer** [comment]
I think broadcast_text are bruteforced, so any errors are blizzlike? @ratkosrb

**Comment by ratkosrb** [comment]
Yes. Don't change broadcast texts, they are all correct. Any typos in them are not bugs.
