### ISSUE TITLE
🐛 [Bug] Felhound Tracker NPC

### ISSUE THREAD

**Issue by LEO33SoFo** [vmangos/core#1408]
## 🐛 Bug report

_Felhound Tracker_ does not track the *Azsharite Formation*s when I emote `/roar` to him, when doing the quest _Azsharite_.
The same issue as https://github.com/TrinityCore/TrinityCore/issues/22639.
### Expected behavior

The details are described in https://github.com/TrinityCore/TrinityCore/issues/22639.
### Steps to reproduce

1. `.quest add 3602`
2. `.go xyzo 2750.067871 -5869.417969 101.159897 4.685205 1` as an example.
3. Open the provided _Felhound Tracker Kit_ and summon a _Felhound Tracker_.
4. `/roar` at _Felhound Tracker_ and check his behavior.

### Version & Environment

Client Version: 
- 1.12.1.6005

Commit Hash:  
aff74e684ad4a9cc0bc21722a4106b1eb43a56d3

OS Client and Server:
- _Windows XP Professional_ 32bit

### Crashlog

- None

**Comment by NickTyrer** [comment]
CLosed in https://github.com/vmangos/core/commit/6842c31f3878ef035c1db6d531487deb3fdd8ef9
