### ISSUE TITLE
Where is sql update?

### ISSUE THREAD

**Issue by chendh123** [vmangos/core#141]
Where is sql for rename 'id' to 'entry'?
SQL: SELECT DISTINCT `entry` FROM `spell_template`
[1054] Unknown column 'entry' in 'field list'
Your database structure is not up to date. Please make sure you have executed all the queries in the sql/updates folders.
/mnt/data/mangoszero/vcore/src/shared/Database/DatabaseMysql.cpp:182: Error: Assertion in HandleMySQLError failed: false
./mangosd(_ZN8SpellMgr20LoadExistingSpellIdsEv+0x76) [0xa08d26]
./mangosd(_ZN9ObjectMgr18LoadAllIdentifiersEv+0x758) [0x6384b8]
./mangosd(_ZN5World23SetInitialWorldSettingsEv+0x187) [0x69ab77]
./mangosd(_ZN6Master3RunEv+0x123) [0x609d43]
./mangosd(main+0x2f9) [0x606599]
/lib64/libc.so.6(__libc_start_main+0xf4) [0x38ad21d974]
./mangosd [0x5fda29]

**Comment by ratkosrb** [comment]
If you don't have any custom changes in your db, then just drop the world db and replace with the new 8 February release. Otherwise you can rename the column yourself with something like HeidiSQL.
