### ISSUE TITLE
[Alterac Valley] Massive AI flaws

### ISSUE THREAD

**Issue by Revo86** [vmangos/core#1411]
**Current behavior**: 

Alliance base almost impossible to conquer, matches take forever, because:

- After taking the top NE graveyard, AI goes up the mountains east , south and north again (instead of into Alliance base)
- Alliance spawn in their base and are stuck there looping between the two bunkers. They rarely try to push out.

Therefore Horde runs in 1onX, dying, no bg progress. I'd say this happens 8/10 matches.

**Expected behavior**: 

- Quick 15-20 min matches, run through and conquer base graveyard, then towers.
- Don't get stuck in case the base graveyard is the only one left.

**Steps to reproduce**:

1. Take all graveyards beside enemy base grayeyard
2. Enjoy infinite, impossible to end matches
3. No honor, no r14, no r14 gear, cry in corner.

**Client version**: 

**Commit hash**: 

**Operating system**:

**Comment by Kittnz** [comment]
Suggestions?

**Comment by celguar** [comment]
closest one I can think of is to disable 2 paths for horde bots
vPath_AV_Alliance_Cave_Slop_Crossroad_to_Alliance_Slope_Crossroad
vPath_AV_Alliance_Cave_to_Alliance_Cave_Slop_Crossroad

crude but doubt any horde bot needs to go to ally cave
though if issue is big disabling those 2 paths may make horde bots stuck alltogether and not go into ally base. Need to test

I coulnd't find why it happens though...

**Comment by Kittnz** [comment]
We can always make some paths one way, so they won't go back and forth.

**Comment by celguar** [comment]
From what it looks like it's that bots pick a different path to start from. So a proper path to Ally base is close, but for some reason they pick a different one and move to the start of it. Maybe it's closer I dunno.
1) Horde moves by blue path (**vPath_AV_Alliance_Slope_Crossroad_to_Stormpike_Crossroad**)
2) After capping GY they need to go to Ally base (green path) (**vPath_AV_Stormpike_Crossroad_to_Alliance_Base_Bunker_First_Crossroad**)
3) Instead they go to begining (or some waypoint) of red path (It's not reversable but they go (more like climb a big slope) to its begining (or a waypoint) so they don't go reverse) and make that big hook
**vPath_AV_Alliance_Cave_Slop_Crossroad_to_Alliance_Slope_Crossroad** & **blue** again
![alt_text](https://media.discordapp.net/attachments/841534179250012180/860518693394186302/WoWScrnShot_070221_185104_1.jpg)

**Comment by celguar** [comment]
Actually I think after blue path they also have a small path from Crossroad to flag (**vPath_AV_Stormpike_Crossroad_to_Stormpike_Flag**)
So maybe when they try to go back Flag->Crossroad they calculate that start of path from Ally cave is closer so they move there...No idea, sorry. And no math skills to calculate 😒

**Comment by Revo86** [comment]
Exactly, that's the behavior I tried to explain.

For the almost unconquerable ally base I'd suggest the AI prioritizing the
graveyard there before the bunkers. Also don't conquer all graveyards south
of it because that will force allies to spawn north and dramatically
increasing the game‘s length. That's the first rule you learn if you play
AV a lot and want to avoid endless fighting.

Besides these things playing with AI is lots of fun!

celguar ***@***.***> schrieb am So., 5. Dez. 2021, 00:31:
