### ISSUE TITLE
🐝 [Bug] Alliance NPC gives out Horde quest

### ISSUE THREAD

**Issue by tsvenbla** [vmangos/core#1412]
## 🐝 Bug report - Quest
Argent Quartermaster Lightspark (NPC ID 10857) offers the Horde version of the quest Chromatic Mantle of the Dawn. 

### Expected behavior
Argent Quartermaster Lightspark gives the quest ID 5524 (https://classic.wowhead.com/quest=5524), which is only supposed to be given by the Horde NPC Argent Quartermaster Hasana. 

Instead, Argent Quartermaster Lightspark should hand out the Alliance version, quest ID 5521 (https://classic.wowhead.com/quest=5521).

### Steps to reproduce
1. Ensure patch content is set to 1.3, client version 1.12.1.5875.
2. Create an Alliance character, level to 60.
3. Go to Argent Quartermaster Lightspark in Western Plaguelands, Chillwind Camp.
4. Take and complete the quest Chromatic Mantle of the Dawn.
5. Look up the quest just completed in the table _character_queststatus_.
6. The quest completed has the ID 5524, which is the Horde equivalent of the Alliance one with ID 5521.
7. I.e. an Alliance quest giver is giving a Horde quest. 

### Version & Environment
Client Version:
  - 1.12.1.5875

Commit Hash:  

OS Client: Windows 11 Pro, OS build 22000.248
OS Server: local on same Client

### Crashlog
- None

**Comment by NickTyrer** [comment]
Closed in #1385
