### ISSUE TITLE
🐝 [Bug] Human Orphan has wrong gossip text

### ISSUE THREAD

**Issue by tsvenbla** [vmangos/core#1414]
## 🐝 Bug report - Quest

The Human Orphan ([NPC ID 14305](https://classic.wowhead.com/npc=14305)) that you summon from the Human Orphan Whistle ([item ID 18598](https://classic.wowhead.com/item=18598)) during Children's Week has the wrong gossip text. 

![Gossip text](https://i.imgur.com/wIVvz19.png)

### Steps to reproduce

1. Set game patch to 1.4.
2. Use 1.12.1.5875 client.
3. Start Children's Week event (.event start 10).
4. Pick up quest Children's Week from Orphan Matron Nightingale in Stormwind.
5. Use the whistle and talk to the Human Orphan.

### Version & Environment

Client Version:  1.12.1.5875

Commit Hash:  28c089a283afb5770994a599cc7072f4fac6dd7a

OS Client: Win 11
OS Server: local, same OS as Client

### Crashlog

- None

**Comment by NickTyrer** [comment]
He seems th have the correct gossip menus and text ids in the db, however I only get the placeholder gossip menu "Greetings <name>" when interacting with him in 1.12.1.
