### ISSUE TITLE
🐛 [Bug] Reins of the Winterspring Frostsaber mount

### ISSUE THREAD

**Issue by LEO33SoFo** [vmangos/core#1415]
## 🐛 Bug report

I can mount the _Reins of the Winterspring Frostsaber_ when I am not Exalted with Darnassus faction (as an Alliance non-Night Elf) and don't have the Tiger Riding skill.
### Expected behavior

The _Reins of the Winterspring Frostsaber_ should not be mountable if I don't have the Tiger Riding skill, according to [Wowhead](https://classic.wowhead.com/item=13086/reins-of-the-winterspring-frostsaber#comments:id=2711058:reply=1344140) comments.
### Steps to reproduce

1. Be an Alliance non-Night Elf character.
2. `.mod rep 589 42000`
3. `.additem 13086`
4. Try to mount it.

### Version & Environment

Client Version: 
- 1.12.1.6005

Commit Hash:  
aff74e684ad4a9cc0bc21722a4106b1eb43a56d3

OS Client and Server:
- _Windows XP Professional_ 32bit

### Crashlog

- None

**Comment by ratkosrb** [comment]
Mounts do not have reputation requirement on the item. Tiger Riding is only a thing before 1.12.1, (classic is based on 1.12.0), so if you've set your server to WowPatch = 10 (1.12.1) then of course you can use it without Tiger Riding, since that skill no longer exists there.

**Comment by LEO33SoFo** [comment]
Thanks for the clarification. :smiley:
