### ISSUE TITLE
Not spawning in Kharanos graveyard

### ISSUE THREAD

**Issue by Arvind-SV** [vmangos/core#1417]
**Current behavior**: 
Dying near frostmane hold in Dun morogh is sending me to graveyard near anvilmar instead of kharanos.
**Expected behavior**: 
Dying near frostmane hold in Dun morogh should spawn you at Kharanos graveyard.
**Steps to reproduce**:

1. Create a dwarf/gnome character(or use an existing character).
2. Head to frostmane hold. Its near Gnomeregan.
3. Die to the frostmane trolls.
4. Check where you spawn

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Windows 11

**Comment by FlagFlayer** [comment]
When you Release Spirit the game checks which graveyards it could send you to in the current zone you're in and will then always send you to the nearest graveyard coordinate-wise. When in Frostmane Hold you are closer to the graveyard in Anvilmar than the graveyard in Kharanos, which is why you're sent there. This is the intended behaviour.

EDIT: I was completely wrong

**Comment by heyitsbench** [comment]
I don't know if it's an appropriate source, but [that's not behavior seen in TBC Classic](https://youtu.be/wyaBOODuwqs?t=53).

**Comment by FlagFlayer** [comment]
"Starting area graveyards are still reserved exclusively for characters of similar faction that die within their confines. For example, the spirit of a Horde character dying right outside of [Deathknell](https://wowpedia.fandom.com/wiki/Deathknell) will not use Deathknell graveyard, but will instead go to the next closest Tirisfal Glades graveyard." (Patch 1.6 change notes: https://vanilla-wow-archive.fandom.com/wiki/Patch_1.6.0#World_Environment)

This confirms that there are specific ghost zones for each starting area. This is a bug.

**Comment by FlagFlayer** [comment]
The starting zones have IDs in the AreaTable, this shouldn't be difficult to implement: https://wow.tools/dbc/?dbc=areatable&build=1.6.0.4500
