### ISSUE TITLE
add a bag.

### ISSUE THREAD

**Issue by chendh123** [vmangos/core#142]
set value to nonexistent value field: 120 (count: 121) for object typeid: 2 type mask: 7
/mnt/data/mangoszero/vcore/src/game/Objects/Object.cpp:982: Error: Assertion in SetUInt64Value failed: index + 1 < m_valuesCount || PrintIndexError(index, true)
./mangosd(_ZN4Item10CreateItemEjjPK6Player+0xb4) [0x8b1344]
./mangosd(_ZN6Player12StoreNewItemERKSt6vectorI12ItemPosCountSaIS1_EEjbi+0x15c) [0x93083c]
./mangosd(_ZN11ChatHandler20HandleAddItemCommandEPc+0x25a) [0x75be8a]
./mangosd(_ZN11ChatHandler14ExecuteCommandEPKc+0x2ec) [0x712efc]
./mangosd(_ZN11ChatHandler13ParseCommandsEPKc+0xb5) [0x7182c5]
./mangosd(_ZN12WorldSession36ProcessChatMessageAfterSecurityCheckERSsjj+0x76) [0xadcdd6]
./mangosd(_ZN12WorldSession23HandleMessagechatOpcodeER11WorldPacket+0x2d2) [0xadd372]
./mangosd(_ZN12WorldSession13ExecuteOpcodeERK13OpcodeHandlerP11WorldPacket+0x100) [0x6a5fc0]
./mangosd(_ZN12WorldSession14ProcessPacketsER12PacketFilter+0x37a) [0x6a9c3a]
./mangosd(_ZN12WorldSession6UpdateER12PacketFilter+0x48) [0x6abf28]
./mangosd(_ZN5World14UpdateSessionsEj+0x18e) [0x69864e]
./mangosd(_ZN5World6UpdateEj+0x12f) [0x698aff]
./mangosd(_ZN13WorldRunnable3runEv+0x9f) [0x6191af]
./mangosd(_ZN9ACE_Based6Thread10ThreadTaskEPv+0x27) [0xcfab07]
/mnt/data/mangoszero/vcore_release/lib/libace.so(_ZN21ACE_OS_Thread_Adapter6invokeEv+0x86) [0x2aed05af5336]
/lib64/libpthread.so.0 [0x38ade06367]
/lib64/libc.so.6(clone+0x6d) [0x38ad2d30ad]

CATCH Exception 'ASSERT' for account 5 / IP 192.168.252.1
index + 1 < m_valuesCount || PrintIndexError(index, true)

**Comment by chendh123** [comment]
#if SUPPORTED_CLIENT_BUILD > CLIENT_BUILD_1_8_4
    CONTAINER_FIELD_SLOT_LAST                  = ITEM_END + 0x48,
#else
    CONTAINER_FIELD_SLOT_LAST                  = ITEM_END + 0x29,
#endif
    CONTAINER_END  ? +2?,

**Comment by ratkosrb** [comment]
It should be fixed now.
