### ISSUE TITLE
🐛 [Bug] Heart of Hakkar Event

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#1430]
## 🐛 Bug report
1. After the event runs the following errors are displayed in the console:
```
Delete Gameobject (Entry: 180401 Guid: 3999667) with SpellId 24202 LinkedGO 0 that lost references to owner Creature (Entry: 15069 Guid: 303767) GO list. Crash possible later.
Delete Gameobject (Entry: 180250 Guid: 3999666) with SpellId 24202 LinkedGO 0 that lost references to owner Creature (Entry: 15069 Guid: 303767) GO list. Crash possible later.
Delete Gameobject (Entry: 180249 Guid: 3999665) with SpellId 24202 LinkedGO 0 that lost references to owner Creature (Entry: 15069 Guid: 303767) GO list. Crash possible later.
```

2. The Spirit of Zandalar buff is only given to players in the vicinity of Yojamba Isle when it should also go to players in Booty Bay.

Client Version: 1.12.1

Commit Hash:  5d302c0

**Comment by Kittnz** [comment]
the troll casts it there and yells something..

**Comment by NickTyrer** [comment]
I think he yells text id 10612 and 10537.

**Comment by Daribon** [comment]
Error is probably related to https://github.com/vmangos/core/pull/1149

**Comment by ghost** [comment]
can this be closed @NickTyrer ?
