### ISSUE TITLE
🐛 [Bug] Some Issues with Stranglethorn Fishing Extravaganza

### ISSUE THREAD

**Issue by schell244** [vmangos/core#1434]
## 🐛 Bug report
Issues found with event Stranglethorn Fishing Extravaganza:

game_event 40 = Stranglethorn Fishing Extravaganza: The Crew
game_event 15 = Stranglethorn Fishing Extravaganza: Tournament

Issues with Riggle Bassbait: https://de.classic.wowhead.com/npc=15077/riggle-bassbait

1) Event "Stranglethorn Fishing Extravaganza: The Crew" starts at 13:00
All event related NPC's are spawned in booty bay.
Until the actual tournament event starts at 14:00, Riggle Bassbait shows wrong gossip menu text (broadcast_text: 10600):
```
We already have a winner for our contest, but Jang is willing to purchase any Tastyfish that you have fished up!
There is always next Sunday for you to show your Angling skill!
```

2) Event "Stranglethorn Fishing Extravaganza: Tournament" starts at 14:00:
Now Riggle Bassbait has the correct gossip menu text (broadcast_text: 10475):
```
Welcome to the Booty Bay fishing contest where each week we choose the finest fisherman to be the Master Angler!
Between 2pm and 4pm schools of tastyfish will appear up and down the coast of Stranglethorn.  While fishing if your fishing bobber lands in a tastyfish school then you will catch something from the school rather than the normal stranglethorn fishing fare.
```

3) Player turns in quest Master Angler:
Riggle Bassbait gossip text is not updated (still shows broadcast_text: 10475).

~~Issues with some Schools of Tastyfish https://classic.wowhead.com/object=180248/school-of-tastyfish
Some schools spawns are "cut off" like in screenshot:~~
<img width="252" alt="pool" src="https://user-images.githubusercontent.com/9536270/147878088-028a4435-ac63-45a4-aac7-2bcaf1c399c2.PNG">
-> client related

[update]
possible fix for Riggle Bassbait gossip (I think there's currently no condition to fix this within db gossip menu):
```
bool GossipHello_npc_riggle_bassbait(Player* pPlayer, Creature* pCreature)
{
    if (sGameEventMgr.IsActiveEvent(EVENT_TOURNAMENT) && !sObjectMgr.GetSavedVariable(VAR_TOURN_GOES))
    {
        // When event is active and some player has already turned in QUEST_MASTER_ANGLER -> We already have a winner for our contest...
        pPlayer->SEND_GOSSIP_MENU(GOSSIP_TOURNAMENT_OVER, pCreature->GetObjectGuid());
    }
    else
    {
        // Otherwise: Welcome to the Booty Bay...
        pPlayer->SEND_GOSSIP_MENU(GOSSIP_TOURNAMENT_ACTIVE, pCreature->GetObjectGuid());
    }
    return true;
}
```

### Version & Environment

Client Version: 
1.12.1.5875

Commit Hash:  
71e854e

OS Client & OS Server:
 Win10

**Comment by Oroxzy** [comment]
you will find cut off fish schools in classic too, its client related

**Comment by schell244** [comment]
Thanks for the information. I've crossed that part out.

**Comment by Oroxzy** [comment]
I won the tournament and sniffed it, wanna have it?

**Comment by schell244** [comment]
Nice, I'll pm you in discord later. Thanks!
