### ISSUE TITLE
There is value in the script_texts.content_loc4 table, it will cause the program to crash. Tested.

### ISSUE THREAD

**Issue by wthslw001** [vmangos/core#144]
There is value in the script_texts.content_loc4 table, it will cause the program to crash. Tested.

![image](https://user-images.githubusercontent.com/8679316/52687747-33a7b080-2f8e-11e9-9e2f-1892920f4bef.png)

Use the original version without crashing.
Thank you again for your hard work.

**Comment by DarkmoonRabbit** [comment]
patch?

**Comment by wthslw001** [comment]
> patch?

1.12
