### ISSUE TITLE
🐝 [Bug] Missing Quest End Script Voodoo Feathers (8425)

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#1442]
## 🐝 Bug report - Quest
The questgiver should say some text and give you a buff
see: https://classic.wowhead.com/quest=8425/voodoo-feathers#comments

Commit Hash:  1fd3946

**Comment by scottnice** [comment]
Video example of his text, buff and animation: https://youtu.be/la2GTYLeiak?t=469

10893 in broadcast_text

I believe entry 25101 in spell_template is the battleshout.
