### ISSUE TITLE
🐞 [Bug] Ritual Candle Aura spell (ID: 23226)

### ISSUE THREAD

**Issue by LEO33SoFo** [vmangos/core#1447]
## 🐞 Bug report - Spell

While doing the _Dreadsteed of Xoroth_ quest, the _Ritual Candle Aura_ spell is affecting me when staying within the circled ritual zone.
### Expected behavior

Normally this is not supposed to happen, am I right? This spell should affect enemy mobs only.
### Steps to reproduce

1. Be a Warlock and start the quest _Dreadsteed of Xoroth_ (ID: 7631)
2. Go to the _Prison of Immol'thar_ in _Dire Maul West_, defeat _Immol'thar_ and start the ritual circle event.
3. Check for the aforementioned issue.

### Version & Environment

Client Version: 
- 1.12.1.6005

Commit Hash:  
cb5c6020d66be2ed2b1811e4b067bf284aa37614

OS Client and Server:
- _Windows XP Professional_ 32bit

### Crashlog

- None

**Comment by Daribon** [comment]
You are correct, Ritual Candle Aura should only affect NPCs.
If it affect players, then it is bugged.

Video from classic:
https://www.youtube.com/watch?v=A_IQmMbhPiQ

**Comment by ghost** [comment]
already fixed
