### ISSUE TITLE
💬 [Discussion] Please increase the player death skeleton time to what it was

### ISSUE THREAD

**Issue by RejectedGalaxy** [vmangos/core#1448]
Hello, I'm just here to suggest one change to revert something they did a couple months before Nostalrius shut down. They reduced the time the player death skeletons last to a measly 30 minutes or so. No longer did you see mountains of skeletons covering STV and the Fargodeep mine. You will see a few skeletons here and there on servers, but no where near what you saw during most of Nost. It's just one tiny detail that I care a lot about and I really doubt it would cause much lag, even with 10k+ online on Nost they weren't causing lag (source at bottom for this claim). I'd suggest making them stay permanently as they had to custom add "bone despawn" but honestly some hours would be better than 30 minutes. Thanks for taking time reading this. Here is the forum post with the documented change. https://forum.nostalrius.org/viewtopic.php?f=2&t=18683

Also here is a forum post of a Nost developer stating that skeletons do not cause memory issues https://forum.nostalrius.org/viewtopic.php?f=6&t=17282

I'm suggesting here since most vanilla servers will run on this core. Rather than asking each server dev to change this I hope to get this fixed inside the actual core itself.

**Comment by ratkosrb** [comment]
This is a config option, not something hardcoded in the core itself. Everyone can customize it as they please. We are not going to remove the option to force people to use a given value. Tell whatever server owner to change the value in the config if they so wish.

https://github.com/vmangos/core/blob/development/src/mangosd/mangosd.conf.dist.in#L2504

**Comment by RejectedGalaxy** [comment]
I wasn't exactly suggesting removing it. I was mostly suggesting to increase the default time since its so small.
