### ISSUE TITLE
can't login or create new character, programe crash!

### ISSUE THREAD

**Issue by hyphenz** [vmangos/core#145]
programe infomation:

set value to nonexistent value field: 120 (count: 121) for object typeid: 2 type mask: 7
D:\lightshope\core\src\game\Objects\Object.cpp:982: Error: Assertion in Object::SetUInt64Value failed: index + 1 < m_valuesCount || PrintIndexError(index, true)
Item::WakeUp()+0x34d [0x2b9c0d]
Item::CreateItem()+0xc2 [0x647e2]
Player::StoreNewItemInBestSlots()+0xd8 [0xea218]
Player::Create()+0x4df [0xc363f]
WorldSession::HandleCharCreateOpcode()+0x4ed [0x3d771d]
WorldSession::ExecuteOpcode()+0x1d8 [0x6f618]
WorldSession::ProcessPackets()+0x343 [0x71b03]
WorldSession::Update()+0x4f [0x732ff]
SpellAuraHolder::UpdateHolder()+0x310 [0x42af0]
CreatureAI::SwitchAiAtControl()+0x1fc [0x4194c]
CreatureAI::GetData()+0x4631 [0x307b1]
BarGoLink::step()+0xd21 [0x52e441]
ACE_OS_Thread_Adapter::invoke()+0xa8 [0x6cc38]
crt_at_quick_exit()+0x7d [0x6be1d]
BaseThreadInitThunk()+0xd [0x159cd]
RtlUserThreadStart()+0x21 [0x2a2e1]
CATCH Exception 'ASSERT' for account 2 / IP 127.0.0.1
index + 1 < m_valuesCount || PrintIndexError(index, true)

**Comment by ratkosrb** [comment]
type server info in console and show me what it says, cause i thought i fixed this yesterday

**Comment by hyphenz** [comment]
I update the source , it's fixed! thx~
