### ISSUE TITLE
🦂 [Bug]

### ISSUE THREAD

**Issue by norcaljosh** [vmangos/core#1451]
## 🦂 Bug report - Dungeon
The Scholomance students have too much health. They have 17.7k hp, by comparison Vectus/Marduk have 23/24k hp and they are bosses. This makes clearing the room take around 10 times longer than it should.

### Expected behavior
https://vanillawowdb.com/?npc=10475
This vanilla DB shows they should have only 2.2-2.6k hp.

### Steps to reproduce
None, just look at the NPC's stats

### Version & Environment
  Client Version:
  - 1.12.1.5875

Client Version: 

Commit Hash:  

OS Client: Win 10
OS Server:  Winows I think, it's hosted

### Crashlog
- None

**Comment by ratkosrb** [comment]
Not a bug, in sniff they have 17k health. And vanillawowdb is not an accurate source of information, its using an old mangos database. Do not make reports based on that website.

![Untitled](https://user-images.githubusercontent.com/35845488/150405958-3f39a10a-3f9f-4ed3-ae8f-226a95ceba32.jpg)

**Comment by norcaljosh** [comment]
Thank you, after digging I found there's a quest chain that gives an item which turns the students into skeletons and makes them easier
