### ISSUE TITLE
🦂 [Bug] Awbee NPC

### ISSUE THREAD

**Issue by LEO33SoFo** [vmangos/core#1453]
## 🦂 Bug report - Dungeon

There is no gossip when talking to _Awbee_.
### Expected behavior

There should be a gossip dialogue when talking to _Awbee_, according to [Wowpedia](https://wowpedia.fandom.com/wiki/Awbee) and [Wowhead](https://classic.wowhead.com/npc=10740/awbee#comments:id=3299755) comments.
### Steps to reproduce

1. `.go creature id 10740`
2. Kill the surrounding *Blackhand Thug*s.
3. Talk to _Awbee_ and check for the issue.

### Version & Environment

Client Version: 
- 1.12.1.6005

Commit Hash:  
cb5c6020d66be2ed2b1811e4b067bf284aa37614

OS Client and Server:
- _Windows XP Professional_ 32bit

### Crashlog

- None

**Comment by NickTyrer** [comment]
Closed in #1467
