### ISSUE TITLE
🚀 [Feature] Support for OSX build and better PATH finding for OSX and on other systems

### ISSUE THREAD

**Issue by jaywalker15262** [vmangos/core#1454]
## 🚀 Feature

https://github.com/cmangos/mangos-classic/commit/efc9b1cc8fd65cdcf5ac256ec0e0c925ee4c57f2#diff-81f2d277cc77e427cdfbebd94eba9462a118583bd09ac108e85c2b809694e42c

We should add this commit.

**Comment by ratkosrb** [comment]
I think OSX build already works, cause when it breaks people submit pull requests to fix it.

**Comment by jaywalker15262** [comment]
its just for making it easier to find the mysql libs and headers needed to cmake. Can save ppl some trouble, they are not in the same common places on different systems such as OSX and other UNIX systems.

This actually helped cmake find my libs as they werent in those places and i didnt have to move them

**Comment by ghost** [comment]
Already fixed
