### ISSUE TITLE
🐛 [Bug] loadOffMeshConnections:: input file offmesh.txt not found!

### ISSUE THREAD

**Issue by jaywalker15262** [vmangos/core#1460]
Using the MoveMapGen.exe of the latest Vmangos build(built as x64 in cmake) on WIN10, I get this error while it builds tiles:
`loadOffMeshConnections:: input file offmesh.txt not found!`

Here's an example how it looks in the shell window `[Map 000] Building tile [32,40] (279 / 687)
 loadOffMeshConnections:: input file offmesh.txt not found!
[Map 000] Building tile [32,41] (280 / 687)
 loadOffMeshConnections:: input file offmesh.txt not found!
[Map 000] Building tile [32,42] (281 / 687)
 loadOffMeshConnections:: input file offmesh.txt not found!
[Map 000] Building tile [32,43] (282 / 687)
 loadOffMeshConnections:: input file offmesh.txt not found!
[Map 000] Building tile [32,44] (283 / 687)
 loadOffMeshConnections:: input file offmesh.txt not found!
[Map 000] Building tile [32,45] (284 / 687)
 loadOffMeshConnections:: input file offmesh.txt not found!
[Map 000] Building tile [32,46] (285 / 687)
 loadOffMeshConnections:: input file offmesh.txt not found!
[Map 000] Building tile [32,47] (286 / 687)
 loadOffMeshConnections:: input file offmesh.txt not found!`
 
 This issue was not present in very earlier Vmangos versions.
 
 The maps still get built so I do not know if this actually affects anything.

**Comment by coolzoom** [comment]
did you copy-paste the offmesh.txt from contrib/mmap/offmesh.txt and config.json to the same folder as MoveMapGen.exe?
You can use the data from repack or use the MoveMapGen.sh from CMaNGOS.
or try to use below command to build
./MoveMapGen $PARAMS $OFFMESH

while:

$OFFMESH="--offMeshInput offmesh.txt"
## Additional Parameters to be forwarded to MoveMapGen, see mmaps/readme for instructions
$PARAMS="--silent --configInputPath config.json"

**Comment by jaywalker15262** [comment]
> did you copy-paste the offmesh.txt from contrib/mmap/offmesh.txt and config.json to the same folder as MoveMapGen.exe? You can use the data from repack or use the MoveMapGen.sh from CMaNGOS. or try to use below command to build ./MoveMapGen $PARAMS $OFFMESH
> 
> while:
> 
> $OFFMESH="--offMeshInput offmesh.txt"
> 
> ## Additional Parameters to be forwarded to MoveMapGen, see mmaps/readme for instructions
> $PARAMS="--silent --configInputPath config.json"

I fixed it by copying over offmesh.txt. However I did not require this before. This must be a new thing?

**Comment by coolzoom** [comment]
It is not a new thing, offmesh.txt existed a long time ago along with mmaps, it is just a new notice for one like you who may do not know to use offmesh.txt, it is not a bug.
