### ISSUE TITLE
🐛 [Bug] Drywallow Daggermaw deal insane amounts of damage.

### ISSUE THREAD

**Issue by jaywalker15262** [vmangos/core#1461]
Latest vmangos build

Drywallow Daggermaws deal way higher damage than other npcs at its level range. Harder than many lvl 60 npcs. It also has way less armor it seems than for example Acidic Swamp Oozes. I do not think these values are correct.

**Comment by Daribon** [comment]
Which patch are you running it as, Drywallow daggermaw used to be elites in early to mid vanilla patches.

**Comment by jaywalker15262** [comment]
> Which patch are you running it as, Drywallow daggermaw used to be elites in early to mid vanilla patches.

Latest. 1.12.1
