### ISSUE TITLE
🐞 [Bug] Major super weird bug with Rend Tauren range?

### ISSUE THREAD

**Issue by jaywalker15262** [vmangos/core#1462]
So when Warrior Taurens activate their Auto Attack, their Rend/Overpower and other abilities have their range go from 9y to 6y. What is this about? Old bug that seems to persist in even old vmangos builds. When u are not auting the range goes back to 9y. The tooltips even reflect this as well.

https://imgur.com/a/VH1DXrj

Had this bug found on multiple servers running vmangos and locally as well.

**Comment by ratkosrb** [comment]
The server does not tell the client what range to display on the tooltip of spells. Client reads its own Spell.dbc for that.

**Comment by celguar** [comment]
but how then big Ogres show bigger range for player spells than lesser mobs?

**Comment by celguar** [comment]
on cmangos I saw ogres get enraged and become bigger and it would affect Spell tooltip by increasing 1-2 yards to it

**Comment by celguar** [comment]
Or it was added in later expansions? :O

**Comment by celguar** [comment]
on cmangos classic I did .m scale 10 on a mob I was fighting with and Rend tooltip changed from 6 to 10 yards. Before combat it showed 5y. So vanilla can stll do this I guess

**Comment by ratkosrb** [comment]
Server CANNOT change spell tooltips. You cannot overwrite Spell.dbc data from the server. When said ogres become enraged and get bigger, their scale increases, and when an unit's scale increases, their combat reach is multiplied by their scale. This is a sniffed value, and its used in spell range calculations.

**Comment by celguar** [comment]
Yeah but scale info is still server info so it can't change directly but it changes it by changing combat reach field, correct?

**Comment by ratkosrb** [comment]
The client automatically takes the combat reach of your target into account.

**Comment by celguar** [comment]
In old servers all mobs were same combat reach so we could melee bosses under their asses only, so it still server side issue possibly

**Comment by ratkosrb** [comment]
It is not an issue, this is the correct behavior. It was incorrect that combat reach didn't change with scale previously. Go sniff a mob or player increasing scale in classic and you'll see. Combat reach and Bounding Radius are multiplied by the scale.

**Comment by celguar** [comment]
Ah, so small plainstriders who this guy is talking about have scale less than 1.0f so tooltip changes from 9 to 6?
They look pretty small, so sounds like an explanation :O

**Comment by ratkosrb** [comment]
I'm guessing that when you are not targeting anybody, its using your own combat reach to display the spell range. And tauren players have the biggest combat reach. But when you target the mob, it now uses its combat reach, which is smaller.

**Comment by celguar** [comment]
Okay, thanks a lot for explanation 👍🏼

**Comment by jaywalker15262** [comment]
So what would be a good way to hack this for taurens? I do not know why the client reduces the range from 9 yards to 6 yards when you get in combat. This does not happen for humans for example. I am also pretty sure they solved this client issue on classic.

**Comment by ratkosrb** [comment]
Why would we hack it? We don't want to alter the client, this is the real vanilla client, its behavior is by definition correct. This is an emulation project, not a modding project. Please don't open issues like this in the future.

**Comment by jaywalker15262** [comment]
I was just asking what would be a good way, not saying you should implement it. I mean vmangos does have a custom folder for optional stuff like this. And I did not know this was a strictly client issue before I opened it. No need to be so rude.

**Comment by ratkosrb** [comment]
```
This does not happen for humans for example.
```
That's because humans use the standard combat reach of 1.5 yards, which is also used by most mobs. So nothing changes when you target the mob, the calculation has the same result.
