### ISSUE TITLE
sql update faild

### ISSUE THREAD

**Issue by chenps10** [vmangos/core#147]
Sorry to bother.

my sql recent update is 20190204131040_world

and I drop 20190207163017_world.sql、20190207171305_world.sql is ok.

but drop 20190216195152_world.sql or using merge.sh creat world_db_updates.sql and drop it was faild
and run the mangosd was error with this ：
![qq 20190220101513](https://user-images.githubusercontent.com/39617409/53061694-5ccdc100-34f9-11e9-97c5-abb1a3cb116d.png)

so how i fix it?

**Comment by chenps10** [comment]
i also try to use this database world_full_26_august_2018.7z clear,and use merge to creat update to drop it,but it also error

**Comment by ratkosrb** [comment]
Use 8 February 2019 db.

**Comment by chenps10** [comment]
ok,found it;lol
