### ISSUE TITLE
🐛 [Bug] Ward of Laze drops loot when its not suppost to.

### ISSUE THREAD

**Issue by jaywalker15262** [vmangos/core#1472]
### Expected behavior

Ward of Laze drops loot when it is not suppost to. It is a totem that is summoned by a mob in STV. Here is proof it drops nothing:
https://classic.wowhead.com/npc=2667/ward-of-laze

It is weird for it to drop loot. Also when it drops loot if ur not quick enough u can not loot it. But if ur ight click it in time u are.

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by NickTyrer** [comment]
Closed here #1467
