### ISSUE TITLE
🐛 [Bug] In combat forever bug

### ISSUE THREAD

**Issue by jaywalker15262** [vmangos/core#1475]
## 🐛 Bug report

It seems that not always killing the mob clears you from combat, sometimes it fails. No clue what it could be due to. I have also noticed some mobs that should chase you into the water dont do that, such as wolf in darkshire, or venture .co npc in the barrens where there is a lake under an oil-rig type structure. They dont ever clear combat with you, they just stay outside the water forever and u can basically kill them from there. Pretty abuseable, but I dont know if this is at all related.
https://imgur.com/a/Pk7UYFm

### Expected behavior

I should be cleared of combat.

### Steps to reproduce

1. Go into combat with the spider
2. Kill the spider
3. Wait a bit
4. ...
5. Profit

### Version & Environment

Client Version: 
1.12.1

Commit Hash:  
Latest vmangos version

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by ratkosrb** [comment]
Can't reproduce. I always leave combat instantly after killing the spider.
https://streamable.com/tqvj5o

Give me creature ids and coordinates for the other mobs you mentioned.

**Comment by jaywalker15262** [comment]
I do not think its specific to the spider, else it would be reproduceable everytime. I think its a general problem that can happen to a lot of mobs. Lots of players report being stuck in combat forever and only way to clear it is ALT+F4.

https://imgur.com/a/AqLNqMe
https://imgur.com/a/jTuR4jR

Here as u can see mobs like this just go into evade mode and never actually move as long as they cant path to u. They stay like this pretty much until ur way far away or if u stay in an unpathable area for them long enough. Its weird because some mobs can chase u into the waters and some cant, like the rare on on the oilrig in the barrens can but no the mobs around him. It is also I think blizzlike but not sure, that wether or not a mob decides to go out of combat with u is not decided on path length, that could be infinite for all it matters as long as it can path to u, but rather dependant on distance from its combat area? This was probably why u could abuse so many types of runs in vanilla where you make the mob take really long paths to get to you by jumping between objects, but I am not sure if there  should be any sort of limit to this as u cant make a wolf chase u to the other side of the river by making it run ALL the way around it. So I do not think it looks for paths that far away. It doesnt matter if ur in the water or on objects in the water the mob cant get to u and there seems to be a fixed timer that after X amount of time it just get out of combat but during the time it cant path to u its in evade mode. I do not know how much of this is blizzlike or how much is just safe measures to prevent abuse because we didnt know how it actually worked in vanilla(as a lot of it was guess work). One way to abuse this is due to them being evadeable, u have to get out of the water to make them path again or else they will eventually reset, but u can go into the water, go a bit away from them, exit the water, do a few spells, go back into the water, go back to where the mob used be, attack again. And just do that in an infinite loop between those 2 spots until the mob is dead.

EDIT: It seems most of this behaviour is indeed blizzlike, on SoM they do go straight into evade mode but dont reset, and reset after a short while. I guess its mostly abuseable by mages and warriors because they do not start regenerating health that fast once they get into evade mode, it takes a few seconds. I am not sure but it feels like on SoM/classic servers the mobs start regenerating hp faster, like 1 sec after going into evade mode. On my warrior I could do a big swing with a very slow weapon, go into water, wait for swing timer, and go back in an hit the mob. Wasnt rlly hard to do and was a big help because mob swing more often than me.

**Comment by ratkosrb** [comment]
> I do not think its specific to the spider, else it would be reproduceable everytime.

If i can't reproduce it, I cant fix it. It has to break when I test it.

And are you seriously telling me you did not know that some mobs can't swim, and that mobs eventually evade if you go somewhere they can't follow? This has always been part of the game.

**Comment by jaywalker15262** [comment]
It felt off that I could kill them and at first I thought it was the swimming, but I think its actually that they dont enter evade mode or start regen hp immediately or fast enough which is why I can use water with my warrior to swing, go into water, wait for timer to reset, swing again, go back into water. I wonder if that is how it is suppost to be or is there something how with how slow they go into evade mode?

**Comment by schell244** [comment]
I was able to reproduce a "stuck in combat situation" while riding through map and passing by some mobs which started combat with character. In most cases chasing->evading->combat stop works, but sometimes character remains in combat. Issue seems to be more likely to occur, when speed is higher (.mod speed 5 for example). My guess on this: part of map gets unloaded, where a mob is still in combat with player. Maybe this can be avoided when keeping all maps in RAM (world.conf: Terrain.Preload.Continents = 1) but not checked yet.

**Comment by ghost** [comment]
Spoke with @schell244 , it is not reproduceable anylonger..
