### ISSUE TITLE
core crash

### ISSUE THREAD

**Issue by chenps10** [vmangos/core#149]
in server.log tip is:
2019-02-22 08:40:29 ERROR:WorldSocket::HandleAuthSession: Sent Auth Response (authentification failed).

my server os is centos，it has been running stable before，updated core and sql 2 days ago.
today dump.

when crash,CPU usage is more than 100% ,command “systemctl stop mangosd” no response，
forced reboot os and restart mangosd is running successfully again.

everything is ok until now

patch 1.5
maxlevel：60

**Comment by ratkosrb** [comment]
This log error cannot be related to any crash, it just means somebody tried to login with wrong password.

**Comment by chenps10** [comment]
> This log error cannot be related to any crash, it just means somebody tried to login with wrong password.

Next time I try to get more information.
This is an even discovery. It has been no problem before.
only the server suddenly took up very high, then the entire process of mangosd suddenly died, unable to login anyone
