### ISSUE TITLE
🐛 [Bug] Message: Failed to find target for script with id 852401

### ISSUE THREAD

**Issue by Thorsten42** [vmangos/core#1496]
## 🐛 Bug report
Hi,

I have updated from 62fd507 to f08657d (current development branch).

After starting the server i get the following messages in the server output:

`FindScriptTargets: Failed to find target for script with id 852401 (target_param1: 0), (target_param2: 0), (target_type: 1)
`

### Expected behavior
No messages

### Steps to reproduce
just start the server, but it takes some time - sometimes up to 1-2h hours

### Version & Environment
Client Version: 1.12.1.5875
Commit Hash: f08657d 

OS Client: Win11 
OS Server: Ubuntu 20.04 docker container

**Comment by Oroxzy** [comment]
DELETE FROM `creature_ai_scripts` WHERE `id`=852401;
INSERT INTO `creature_ai_scripts` (`id`, `delay`, `priority`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `target_param1`, `target_param2`, `target_type`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `condition_id`, `comments`) VALUES
(852401, 0, 0, 15, 16567, 7, 0, 0, 0, 0, 1, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Cursed Mage - Cast Spell Tainted Mind');

**Comment by Yuhenan** [comment]
@Thorsten42 

HI Have you solved your problem？How to solve it！QQQ

**Comment by NickTyrer** [comment]
Closed here https://github.com/vmangos/core/pull/1970
