### ISSUE TITLE
🦂 [Bug] Cannot jump into Ring of Law from above

### ISSUE THREAD

**Issue by scottnice** [vmangos/core#1499]
## 🦂 Bug report - Dungeon

When attempting to jump into the Ring of Law from the spectator section above the Arena characters cannot make it over the wall. Sniffs show players in classic making the jump.

![image](https://user-images.githubusercontent.com/3597188/166177144-6642c6bb-f38e-4600-aac7-178e659b513f.png)

### Expected behavior

See the attached sniff file.
### Steps to reproduce

1. .play
2. .settime 1576495325
3. .gotoclient
4. See players jump over wall from above
5. This maybe an issue in the 1.12 client

### Version & Environment

Client Version: 
1.12.1.5875

Commit Hash:  
f08657d2037116b4cf7201ff892c91f79e4ef500

OS Client: Win 11
OS Server: Win 11

### Crashlog

- None

**Comment by ratkosrb** [comment]
Whether you can jump over an obstacle has nothing to do at all with the server.

**Comment by ratkosrb** [comment]
I logged in with the 1.14 client and was able to jump over it on the first try.
https://streamja.com/7Kg6p

So this is a non issue. The old client has different terrain collision handling than the new one. Not related to the server at all.
