### ISSUE TITLE
the program crashes!

### ISSUE THREAD

**Issue by DarkmoonRabbit** [vmangos/core#15]
Pre-compiled successfully with the latest source code!
But there is a problem: in mangosd.exe, enter any command in the console, the program crashes!

**Comment by ratkosrb** [comment]
probably caused by https://github.com/vmangos/core/commit/4310205563054882a5330bd774976969a5bf9293

**Comment by DarkmoonRabbit** [comment]
@ratkosrb 
Player Commands = 0,
still crashing...

PS:
I think some game mechanics can be improved slowly, and the current progress is a bit faster.
I am worried that such an entire system will have an incalculable error. (personal advice, I don't know about development)

**Comment by ratkosrb** [comment]
Fixed here https://github.com/vmangos/core/commit/580f8ca164b8a5ce7ef7eea49d6bed4de399a899
