### ISSUE TITLE
quest 3982:What Is Going On?  in Blackrock Depths has bug(already test it)

### ISSUE THREAD

**Issue by chenps10** [vmangos/core#150]
patch:1.5
instance：Blackrock Depths（1584）
npc：Commander Gor'shak（9020）
quest：What Is Going On?（3982）

kill all enemy,and click npc after compled the quest,npc has no  anyresponse.

all players are the same；
tried to clean up the WDB folder，doesn't work；

**Comment by chenps10** [comment]
issue detail update:
1.exit the copy,
2.reset the copy, 
3.find the npc again, and submit the quest ok now.

but when first compled the quest,click npc has no  any response

@ratkosrb

**Comment by coolzoom** [comment]
i have a hack fix, simply set the npc faction to 35 and he will not enter combat, so you can complete the quest anytime. the issue seems the NPC enter combat and the quest/gossip got de-activated so player couln't interact with him.

**Comment by Test045** [comment]
Is he supposed to enter combat ?

**Comment by coolzoom** [comment]
suppose to, he would fight with the mobs together with players, playes must protect him from being killed.

**Comment by ratkosrb** [comment]
Happens because whoever wrote the script didn't call SelectHostileTarget on UpdateAI. I shall re-do it in the db soon.
