### ISSUE TITLE
🐛 [Bug]LH repack V18 cant perform honor rank calculations

### ISSUE THREAD

**Issue by Yuukiring** [vmangos/core#1501]
LH repack V18 cant perform honor rank calculations
win10 in china
how to fix it
MinHonorKills = 1

**Comment by ratkosrb** [comment]
Honor rank calculations happen on server start, so just restart mangosd.

**Comment by Yuukiring** [comment]
![QQ图片20220504202939](https://user-images.githubusercontent.com/104875639/166682569-5a2560a6-bbbd-443b-a0a3-b866832bf424.png)

**Comment by Yuukiring** [comment]
> Honor rank calculations happen on server start, so just restart mangosd.
Player honor stats cannot be read while calculation

**Comment by ratkosrb** [comment]
What is the WowPatch set to in config? Before patch 1.4 there is no honor system. And try updating to the latest code. Why are you using such an old version?

**Comment by Yuukiring** [comment]
![image](https://user-images.githubusercontent.com/104875639/166689338-337d74b1-064d-4610-9957-30e3cd6896da.png)
There are many players on the server，Convert player data to the latest code will cause a crash

**Comment by NickTyrer** [comment]
@Yuukiring can this be closed?
