### ISSUE TITLE
💬 [Discussion]how to make a item to modify player‘s xp rate？

### ISSUE THREAD

**Issue by Yuukiring** [vmangos/core#1503]
or is there a spell can change player’s xp rate？

**Comment by ratkosrb** [comment]
Make it a dummy spell, then handle the effect in SpellEffects.cpp. You can do anything in c++.
```
pPlayer->SetPersonalXpRate(xp);
```

**Comment by Yuukiring** [comment]
> 

im new to it。。
dont know how to do it ：）
