### ISSUE TITLE
🐞 [Bug] Paladin Talent Vengeance - Not Proccing From Various Spell Crits

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#1505]
## 🐞 Bug report - Spell
Vengeance is not proccing from items that provide a seperate spell damage proc e.g:
 - Fiery Plate Gauntlets
 - Storm Gauntlets
 - Blazefury Medallion
 - Fiery Retributer
 - Crystal Charge from Ungoro Crater
 - Stratholme Holy Water
 - 8 Piece Judgement Tier set Holy Damage
 - Sulfuras, Hand of Ragnaros
 
### Expected behavior
https://youtu.be/na7h2H6AhZU
https://youtu.be/NFrVeDbw2-s

Commit Hash: 10ea1cc

**Comment by NickTyrer** [comment]
Grenades - https://youtu.be/sjJ6OiUbFnw

**Comment by NickTyrer** [comment]
Force Reactive Disk - https://youtu.be/7GcoozFdDz0

**Comment by NickTyrer** [comment]
Fiery Plate Gauntlets - https://youtu.be/UoQimbnuroI
I think basically anything a paladin can get a crit from triggers Vengeance

**Comment by Wall-core** [comment]
found in spell.cpp
a commit broke it, likely in:
void Spell::prepareDataForTriggerSystem()

 // (HACK) trigger Vengeance on weapon crits for Paladins
        // item procs should probably trigger for all classes, e.g. Judgement of Wisdom, but many issues to test for first. Paladin exclusive for now.
        if (m_CastItem && m_casterUnit && m_casterUnit->GetClass() == CLASS_PALADIN && (procEx & PROC_EX_CRITICAL_HIT) && !(m_spellInfo->AttributesEx3 & SPELL_ATTR_EX3_SUPPRESS_CASTER_PROCS))
            m_canTrigger = true;

**Comment by Daribon** [comment]
> // (HACK) trigger Vengeance on weapon crits for Paladins // item procs should probably trigger for all classes, e.g. Judgement of Wisdom, but many issues to test for first. Paladin exclusive for now. if (m_CastItem && m_casterUnit && m_casterUnit->GetClass() == CLASS_PALADIN && (procEx & PROC_EX_CRITICAL_HIT) && !(m_spellInfo->AttributesEx3 & SPELL_ATTR_EX3_SUPPRESS_CASTER_PROCS)) m_canTrigger = true;

That line has been almost unchanged for the past 5 years and the hack comment is from pre vmangos.
https://github.com/vmangos/core/blame/6b52729ed898e62e28d013d4eebf051353243d45/src/game/Spells/Spell.cpp#L1376

**Comment by NickTyrer** [comment]
Cmangos has it working correctly, so I guess their fix could just be ported?

**Comment by NickTyrer** [comment]
I think this mechanic may be paladin exclusive. Shaman talents Elemantal Focus and Elemental Devistation do not proc from grenades or spells cast from a weapon.

**Comment by NickTyrer** [comment]
Similarly Mage talent Arcane Concentration does not proc from grenades or weapon spells.

**Comment by NickTyrer** [comment]
So I think this mechanic should only affect Vengeance (unless anyone can think of anything else to test)

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/36668d0990174fd629c747c4f5ff6f31b029cc8f
