### ISSUE TITLE
🐛 [Bug]Rune of Mazthoril unable to use

### ISSUE THREAD

**Issue by leojoeng** [vmangos/core#1506]
## 🐛 Bug report
When I compiled the latest code and ran it, I found that could not use the Rune of Mazthoril for transmission.
Object Entry: 176164 and 176165

### Expected behavior
Move inside the circle of the rune should be teleported to the upper cave or vise versa.

### Steps to reproduce

1.Move inside the circle of the rune, nothing happened
2.that's what the issue

### Version & Environment

Commit Hash:  

- None

**Comment by ratkosrb** [comment]
Cannot reproduce the issue. I am teleported as intended when i walk over the rune.
