### ISSUE TITLE
World of Warcraft stuttering🔧 [Support]

### ISSUE THREAD

**Issue by ghost** [vmangos/core#1508]
this problem is not related to the server. I was disappointed to find stuttering in Classic wow.
https://youtu.be/wgmNtlj_qMs

**Comment by ratkosrb** [comment]
Try playing with 1.14.0 client instead through [HermesProxy](https://github.com/WowLegacyCore/HermesProxy). It is common for the old client to have performance issues on modern computers.

**Comment by DykeRz** [comment]
Confirmed on #1502 commit
I have 56-60 FPS
1.14 client working fine, always 60 FPS

**Comment by ratkosrb** [comment]
The core commit doesn't matter, as this is a client issue. It was made for 2006 computers.

**Comment by Makkonii** [comment]
Try running it with opengl. Not sure if that will actually help.

**Comment by ratkosrb** [comment]
In my experience it runs much worse in opengl.

**Comment by Daribon** [comment]
From my experience I would not recommend running 1.12.1 in opengl on AMD card.
However your results may be different on a nvidia card.

**Comment by Makkonii** [comment]
> From my experience I would not recommend running 1.12.1 in opengl on AMD card.
> However your results may be different on a nvidia card.

That might be the case. I used to run opengl on vanilla but it was before dxvk and on linux

**Comment by Mitradis** [comment]
as I understand it is possibly related to the versions Windows , I tried changing the drivers, but it didn't work. But what is most interesting, after updating Windows on the old computer, the same picture is observed

**Comment by ghost** [comment]
That's funny. I installed an old version of Windows 10 2004 (and MBR disk) on an old computer (with old drivers) and got the same stuttering. But it wasn't before. I have no more ideas.

**Comment by Wall-core** [comment]
Downgrade from DX12 to DX11 to fix the stuttering issue.

**Comment by Daribon** [comment]
> That's funny. I installed an old version of Windows 10 2004 (and MBR disk) on an old computer (with old drivers) and got the same stuttering. But it wasn't before. I have no more ideas.

What frame rate are you running on vanilla client? I do not recommend running vanilla client above 64 fps because it produces animation artificats, because all animations are done in 64 fps.

**Comment by ghost** [comment]
refrain from formulaic questions about vsync\frame rate\drivers\stars on the sky etc. I already wrote that I'm not a fool. I reread everything related to this, everything that is in Google. The problem is with the game itself, not with me or my computer.

**Comment by ghost** [comment]
Who have same problem pls check game without sound in game.

**Comment by tuxedokev** [comment]
Hi, I have found a solution to having this problem on my own system
I had great FPS on 1.12 clients before but I had to format my PC and reinstalled everything and was experiencing stutters (60-120fps).. I tried many things because I am using a laptop with an AMD iGPU and Nvidia dGPU (rtx 3060 mobile)
 
I opened Nvidia Control Panel > Manage 3D Settings > Program Settings tab > Add.. > Browse.. > Manually find the WoW.exe for the 1.12 client > Select the preferred graphics processor for this program to your Nvidia GPU (mine was set to integrated GPU by default even if I changed the settings in Windows Settings to use the dGPU)

Stutter is now gone and running at a constant 106fps (why it is 106 fps I have no idea, I have a 144hz moniter and the game is running in Windowed mode) so I still have to figure that out

**Comment by ghost** [comment]
You client just started on integrated GPU and you change it. Useless if in bios is disabled integrated GPU. See first post, i have 60fps with 60hz monitor, problem not in fps.

**Comment by ghost** [comment]
Where i can download 1.14?

**Comment by ratkosrb** [comment]
Google wow 1.14.0.40618 and press the first link.

**Comment by schell244** [comment]
Anyone tried to run old client on a Intel Arc GPU (after Intels release of [dx9 performance patch](https://www.tweaktown.com/news/90204/intel-arc-driver-update-brings-massive-43-improvement-to-dx9-games/index.html))?

**Comment by ghost** [comment]
old game engine have problem (like many old games), videoadapter cant help with this. For example same problem have warcraft 3 (with old patches ~1.26).

**Comment by Gamemechanicwow** [comment]
> old game engine have problem (like many old games), videoadapter cant help with this. For example same problem have warcraft 3 (with old patches ~1.26).

Since no one else has mentioned it. Check out https://github.com/hannesmann/vanillafixes - Or upgrade to windows 7 :>

**Comment by Mitradis** [comment]
Finaly!
