### ISSUE TITLE
🐝 [Bug] Investigate the Blue Recluse (1920) and Investigate the Alchemist Shop (1960) Quest Bugs

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#1510]
## 🐝 Bug report - Quest
The quest mechanics for Investigate the Blue Recluse (1920) and Investigate the Alchemist Shop are not working correctly in ways that are difficult to describe so I have 2 videos to show the issue:

- https://www.youtube.com/watch?v=91kfcn79zXU (classic)
- https://youtu.be/nOk1T0A9NUk (vmangos)

Cmangos Fixes:
https://github.com/cmangos/classic-db/commit/cb3029d7c0ccfe78ac8338c716288168c676bf33
https://github.com/cmangos/classic-db/commit/b4fdeeb8799b718d9951a22a896474a1f594d4f6

[investigate_the_blue_recluse_1.14.1.41511_2021-12-22_18-10-21.docx](https://github.com/vmangos/core/files/7764506/investigate_the_blue_recluse_1.14.1.41511_2021-12-22_18-10-21.docx)
7zip file

Commit Hash:  d463419

**Comment by Daribon** [comment]
In vmangos it appears that it summon the NPC right on top of you
In classic the spawns are spread out all over the blue recluse and it feels like they are already spawned (but invisible) when you use the item, considering they tend to chain pull hard on classic.

**Comment by Daribon** [comment]
You can currently just kill one Rift Spawn and then just spam Chest of Containment Coffers to get all three.

Noticed some issue with the object spawns as well:
![nomacs_LEMBtHabcM](https://user-images.githubusercontent.com/6137576/201612197-65d2f695-8e88-4b69-b0e0-f3361a8f46d7.png)
