### ISSUE TITLE
npc creature patch

### ISSUE THREAD

**Issue by w5860363** [vmangos/core#152]
npc id 10583 patch_min =9? Un'Goro Crater

**Comment by w5860363** [comment]
and npc id 16227

**Comment by w5860363** [comment]
https://github.com/vmangos/core/blob/58e83ed56bd863c3ad433931a3a08b5f4fac5e76/sql/old_migrations/20180821004028_world.sql

**Comment by ratkosrb** [comment]
Those flight masters were added in patch 1.11.
> World of Warcraft Client Patch 1.11.0 (2006-06-20)
> - New flight points can be found at Ratchet and Marshall's Refuge, 
Un'Goro Crater.

If you installed the game yourself from the original cd and updated it to 1.12, you should have a file called Patch.txt in your game folder. It contains all the patch notes from launch version to 1.12. Search for "Ratchet" there and you will find that patch notes quote.

You can also watch Joana's leveling videos on youtube, which were recorded before patch 1.11, and you'll see there is no flight master in Ratchet and Un'Goro Crater.

https://youtu.be/v0BPUXwqpeg?t=3220

And if you login with the 1.10 client or earlier, you will see the wyvern and gryphon stands are not there either. Those are not gameobjects spawned by the server, they are part of the map. In Un'Goro that whole area does not exist at all, it's just a cliff there. If you were to spawn the npc, it would be inside the mountain. All the flight paths from and to those locations also do not exist in the TaxiNodes.dbc before patch 1.11.

**Comment by w5860363** [comment]
@ratkosrb thank
