### ISSUE TITLE
🐛 [Bug] Change Chat Text Color (Visible to others)

### ISSUE THREAD

**Issue by tuxedokev** [vmangos/core#1522]
## 🐛 Bug report

I use old tricks and am able to change the color of my text in chat AND it is visible to other players. This usually is already fixed on all older private servers but still works on here.

See screenshot here:
<img src="https://i.imgur.com/D3c4kdh.png">

### Expected behavior

You should not be able to change the color of your text in chat. This can be abused to impersonate a GM.

### Steps to reproduce

1. First enter in any of the /run commands below and press enter.

- Blue
`/run if(not scm) then scm = SendChatMessage; end; function SendChatMessage(msg, type, lang, chan) scm("\124cff00B4FF\124Hitem:19:0:0:0:0:0:0:0\124h" ..msg.."\124h\124r", type, lang, chan);end;`

- Red
`/run if(not scm) then scm = SendChatMessage; end; function SendChatMessage(msg,type,lang,chan) scm("\124cfff00001\124Hitem:19:0:0:0:0:0:0:\124h" ..msg.. "\124h\124r",type,lang,chan);end;`

- Yellow
`/run if(not scm) then scm = SendChatMessage; end; function SendChatMessage(msg,type,lang,chan) scm("\124cffffff00\124Hitem:19:0:0:0:0:0:0:\124h" ..msg.. "\124h\124r",type,lang,chan);end;`

- Orange
`/run if(not scm) then scm = SendChatMessage; end; function SendChatMessage(msg,type,lang,chan) scm("\124cffff9900\124Hitem:19:0:0:0:0:0:0:\124h" ..msg.. "\124h\124r",type,lang,chan);end;`

- Black
`/run if(not scm) then scm = SendChatMessage; end; function SendChatMessage(msg, type, lang, chan) scm("\124cff000000\124Hitem:19:0:0:0:0:0:0:0\124h" ..msg.."\124h\124r", type, lang, chan);end;`

- Purple
`/run if(not scm) then scm = SendChatMessage; end; function SendChatMessage(msg,type,lang,chan) scm("\124cffCC00FF\124Hitem:19:0:0:0:0:0:0:\124h" ..msg.. "\124h\124r",type,lang,chan);end`

- Green
`/run if(not scm) then scm = SendChatMessage; end; function SendChatMessage(msg, type, lang, chan) scm("\124cff00cc33\124Hitem:19:0:0:0:0:0:0:0\124h" ..msg.."\124h\124r", type, lang, chan);end;`

- General Chat Color
`/run if(not scm) then scm = SendChatMessage; end; function SendChatMessage(msg,type,lang,chan) scm("\124cfffBBBB0\124Hitem:19:0:0:0:0:0:0:\124h" ..msg.. "\124h\124r",type,lang,chan);end;`

2. The messages that follow will all appear in that specific color.

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  

OS Client: Win 10
OS Server: 

### Crashlog

- None

**Comment by ratkosrb** [comment]
Have you actually enabled the chat message checks in config?
https://github.com/vmangos/core/blob/development/src/mangosd/mangosd.conf.dist.in#L1323

**Comment by tuxedokev** [comment]
Oh not sure, this is on Wall's test server, will have to check.

**Comment by ratkosrb** [comment]
Cannot reproduce the issue with chat checking turned on. Colored messages do not get displayed.
