### ISSUE TITLE
🔧 [Support]how to add partybot to player’s group

### ISSUE THREAD

**Issue by Yuukiring** [vmangos/core#1523]
### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Steps to reproduce
1.
2.
3.
4. ...
5. Profit

**Comment by Yuukiring** [comment]
use .partybot add tank   can only add partybot to myself party
can I add partybot to other player's party？

**Comment by den13501** [comment]
There is no way to add partybot to other player's group.

**Comment by ratkosrb** [comment]
Add the commands you want to make available to players into the `command` table with `security` = 0.
```
INSERT INTO `command` (`name`, `security`) VALUES ('partybot', 0);
INSERT INTO `command` (`name`, `security`) VALUES ('partybot add', 0);
INSERT INTO `command` (`name`, `security`) VALUES ('partybot clone', 0);
```
