### ISSUE TITLE
💬 [Discussion]can you add a dual-talents system？

### ISSUE THREAD

**Issue by Yuukiring** [vmangos/core#1526]
1.12 requires dual talents

**Comment by ratkosrb** [comment]
No. Dual talents came in patch 3.1.0. This is not a wotlk emulator. Features from other expansions have no place here.

**Comment by Yuukiring** [comment]
thank you

**Comment by den13501** [comment]
Some non-official feature might be implemented by some guys, you can check their fork, just like this [commits](https://github.com/CW3X/core/commit/32e1ac7fcc54ee53d6c1aa099a16b1e3eff35243), but you have to port it to your repository, there may be bug exist or some functions are not compatible with latest official core,  and you need to fix them by yourself.

**Comment by Yuukiring** [comment]
> Some non-official feature might be implemented by some guys, you can check their fork, just like this [commits](https://github.com/CW3X/core/commit/32e1ac7fcc54ee53d6c1aa099a16b1e3eff35243), but you have to port it to your repository, there may be bug exist or some functions are not compatible with latest official core, and you need to fix them by yourself.

thank u very much
