### ISSUE TITLE
🐛 [Bug] Gnomish Battle Chicken Not Despawning

### ISSUE THREAD

**Issue by nellyeo** [vmangos/core#1527]
## 🐛 Bug report
Gnomish Battle Chicken does not depsawn after 1.50 min and stays up until its dead.

### Expected behavior
It should be up for 1.50 min or until its destroyed.

### Steps to reproduce

1. Learn Engineering, adjust skill >= 230
2. Add Gnomish Battle Chicken into inventory (10725) and equip
3. Use it and wait for 1.50 min

Video: [Gnomish Battle Chicken](https://streamable.com/p7w5g6)

### Version & Environment

Client Version:
- 1.12.1.5875

Commit Hash: 
- 992b3803577933c27ce33280fad00720933cf1a4

OS Client: 
- Ubuntu, Windows 10

OS Server:
- Linux (Ubuntu 22.04 LTS (Jammy Jellyfish))

### Crashlog

- None

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/e9b38ff13fbd0c8b6f5bcf17c052de4f84ece4b1
