### ISSUE TITLE
🐞 [Bug] Unable to Buff NPC's Using 1.14 Client

### ISSUE THREAD

**Issue by Firewarrior565** [vmangos/core#1529]
## 🐞 Bug report - Spell
I tested this with just Arcane Intellect but it might be all buffs. I can buff NPC's using the 1.12 client but in 1.14 it just casts it on myself even though I have the friendly NPC selected. In this case in the human starting area trying to cast it on Marshall McBride as a test.

### Expected behavior
Should be able to cast buffs on friendly NPC's. 

### Steps to reproduce

1. Walk up an a friendly NPC.
2. Select the friendly NPC.
3. Cast a buff on them.
4. 1.12 client the buff shows up on them.
5. 1.14 it will just cast it on yourself.

### Version & Environment

OS Client: Windows 10
OS Server:  Windows Server 2022 Standard

### Crashlog

- None

**Comment by ratkosrb** [comment]
This bug report does not belong here. The core is for 1.12 not 1.14. Hermes is a separate project, go report it on it's repo.
