### ISSUE TITLE
Error    [Crash/Auras] Deleting aura 6219 in use (Pet (Petnumber: 3261 Guid: 11))

### ISSUE THREAD

**Issue by wthslw001** [vmangos/core#153]
[Crash/Auras] Deleting aura 6219 in use (Pet (Petnumber: 3261 Guid: 11))
Unit::CleanupsBeforeDelete()+0xee [0x90bfe]
Map::AddObjectToRemoveList()+0x55 [0x121a25]
WorldObject::AddObjectToRemoveList()+0x1f [0x55c8f]
Pet::Unsummon()+0x329 [0x142839]
Map::ScriptCommand_DespawnCreature()+0x2b [0x34e0eb]
Map::ScriptCommandStartDirect()+0xa1 [0x12ad41]
CreatureEventAI::ProcessAction()+0x65 [0x259fa5]
CreatureEventAI::ProcessEvent()+0x5a1 [0x25a5c1]
CreatureEventAI::JustDied()+0x47 [0x259887]
Unit::Kill()+0xabe [0x9afae]
Unit::DealDamage()+0x8df [0x91c4f]
Aura::PeriodicTick()+0x596 [0x28c066]
PersistentAreaAura::Update()+0x1aa [0x28fd0a]
SpellAuraHolder::Update()+0x387 [0x2900b7]
Spell::SendCastResult()+0x8dbc [0x31086c]
Player::_RemoveAllStatBonuses()+0xf593 [0x3049f3]
MaNGOS::at_exit()+0x546 [0x51db26]
Unit::Update()+0xdd [0xa907d]
Player::Update()+0x6b [0xed35b]
Map::UpdatePlayers()+0x159 [0x130369]
Map::Update()+0x245 [0x12d675]
GetSpellRangeStore()+0xd10c [0x1ee69c]
BarGoLink::step()+0xd21 [0x519161]
ACE_OS_Thread_Adapter::invoke()+0xa8 [0x6e1d8]
o__realloc_base()+0x60 [0x1cd70]
BaseThreadInitThunk()+0x14 [0x8364]
RtlUserThreadStart()+0x21 [0x67091]

**Comment by ratkosrb** [comment]
It should be fixed by this -> https://github.com/vmangos/core/commit/864ccc50554b8333a019ae616a9bb1cd22b27c45
