### ISSUE TITLE
🐝 [Bug] Kroshius' Infernal Core (7603)

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#1533]
## 🐝 Bug report - Quest
Script in incorrect:
1. Multiple missing gameobjects
2. Missing spells
3. Wrong factions
4. Custom gameobjects used

### Expected behavior
See:
1. https://github.com/TrinityCore/TrinityCore/commit/fa7cb9fd3539f9d3d0a80951400d169be387279d
4. https://youtu.be/SGuvxeucCj0?t=261

Commit Hash: b00b1f4

**Comment by Daribon** [comment]
I have it sniffed.

**Comment by NickTyrer** [comment]
Closed in #1630
