### ISSUE TITLE
🦂 [Bug]LH v18  Boss's broadcast_text have not been translated

### ISSUE THREAD

**Issue by Yuukiring** [vmangos/core#1534]
LH v18  
windows10

locales_broadcast_text is very comprehensive
But it doesn't work
The shouting of the boss in the game is still in English
how to fix it

**Comment by ratkosrb** [comment]
Most likely the boss in question has a c++ script which does not use broadcast texts, but instead the english text is hardcoded in the core.

**Comment by Yuukiring** [comment]
> Most likely the boss in question has a c++ script which does not use broadcast texts, but instead the english text is hardcoded in the core.

yes，Is there any way to fix it

**Comment by ratkosrb** [comment]
Edit the script's code to use broadcast texts and recompile the core.

**Comment by Yuukiring** [comment]
> Edit the script's code to use broadcast texts and recompile the core.

thank u very much

**Comment by Yuukiring** [comment]
> Edit the script's code to use broadcast texts and recompile the core.

sorry to bother you
can u help me to fix this？
i dont know how  o(╥﹏╥)o

**Comment by NickTyrer** [comment]
Try using a newer version, a few have already been converted. Take a look at these commits to see how its done https://github.com/vmangos/core/search?q=convert+script+texts&type=commits
