### ISSUE TITLE
🦂 [Bug] Spirestone Enforcer not using Puncture (stacking bleed)

### ISSUE THREAD

**Issue by Jaxrs** [vmangos/core#1537]
## 🦂 Bug report - Dungeon
In LBRS, the Spirestone Enforcer mob doesn't use the ability 'Puncture' which is a stacking bleed.

### Expected behavior
[](https://classic.wowhead.com/npc=9199/spirestone-enforcer#abilities;mode:normal)

### Steps to reproduce

1. Enter LBRS
2. Engage a Spirestone Enforcer or Mind Control them, the only ability they have is Strike

### Version & Environment

  Client Version:
  - 1.12.1.5875

**Comment by Twigie** [comment]
Looks like both the Spirestone Enforcer (9199) and Urok Enforcer(10601) are supposed to have the Puncture ability according to WoW Head. 

https://classic.wowhead.com/spell=15976/puncture

This Video shows that both are using the ability in classic: https://www.youtube.com/watch?v=IHKhKr5TajE&t=390s

Also tested on commit 8834103e2a4bc1e09247aa61953abeb46d8f80a2 and confirmed they do not have the ability.
