### ISSUE TITLE
🐛 [Bug] swimming

### ISSUE THREAD

**Issue by hgarner17** [vmangos/core#1538]
## 🐛 Bug report

SWIMMING.  When interacting in the world underwater my Night Elf should not be able to 'flip' when pressing the space bar as if to 'jump'  
Space bar should float me up.. while sit "X" should float me down. It should be the exact same thing as flying in TBC or later expansions.  
I am told that this is a client side issue? So why can't we fix the client itself to correct the wrong actions.  elf flips are cool but not underwater. I should not have to jump jump jump to get to the top again to breathe.  just press and hold space bar to float up and 'jump' when i'm close to the surface to get out and onto the shore/docks.

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by hgarner17** [comment]
I'm reading that the 1.14 client can be used to correct the swimming issues from older clients but still don't see why this is 'closed' with out any correction

**Comment by GrenderG** [comment]
> I'm reading that the 1.14 client can be used to correct the swimming issues from older clients but still don't see why this is 'closed' with out any correction

It's not a bug, so there's nothing to fix. This is how it worked back in the day and it's how the client handles underwater movement. Not related at all to VMaNGOS.
