### ISSUE TITLE
patch 1.6.0

### ISSUE THREAD

**Issue by w5860363** [vmangos/core#154]
Battlemasters
There is a new way to enter the battleground queues. Battlemasters! Located in each of the cities, right-clicking on a battlemaster will allow your character to enter a battleground queue just like you normally would if you touched that battleground's entrance portal. The functionality is exactly the same, so when it's your character's time to enter the chosen battleground, you will be teleported directly in. Local guards can give you directions on how to find the battlemaster that you're looking for.

but battlemasters Is it correct to use a rank in order to use it?

**Comment by ratkosrb** [comment]
I do not understand what the issue is?

**Comment by w5860363** [comment]
@ratkosrb A queuing system requires at least six levels

**Comment by ratkosrb** [comment]
What six levels? If you are telling me that  battlemasters were added in 1.6, I already know that and it was implemented long time ago.
