### ISSUE TITLE
Quest Supplies for the Crossroads has incorrect pre-q🐛 [Bug]

### ISSUE THREAD

**Issue by Simp-N** [vmangos/core#1540]
## 🐛 Bug report
The NPC [Thork](https://classicdb.ch/?npc=3429) has three quests relevant to the pigmen north-east of Crossroads:
[Disrupt the Attacks (871)](https://classicdb.ch/?quest=871)
[Supplies for the Crossroads (5041)](https://classicdb.ch/?quest=5041)
[The Disruption Ends (872)](https://classicdb.ch/?quest=872)

Currently on vmangos, *Supplies for the Crossroads* requires *Disrupt the Attacks* to be completed before you can pick it up, but I believe this is wrong.

### Steps to reproduce
``SELECT * FROM quest_template WHERE entry = 5041``
I am not a dev, but if I understand the database correctly, the column *PrevQuestId* dictates pre-qs.
You can of course also make a lvl ~10 character and head over to Thork and try and grab the quest, which I tried on Wallcraft.

### Expected behavior
*Supplies for the Crossroads* should **not** require *Disrupt the Attacks* to be completed. You should be able to grab both of these quests when you get to the Crossroads.

This is the case in Classic. Picture below, where I am able to have both quests at the same time.
![](https://user-images.githubusercontent.com/75734743/104039336-8a4bb280-51d6-11eb-9ef8-5fe18df4060a.jpg)

This is also the case back in actual vanilla. [Here is a clip from Joana's vanilla guide](https://youtu.be/v0BPUXwqpeg?t=378), where he clearly has both quests available. Please go to 6:18.

If you look at the comments on [Classic Wowhead for Disrupt the Attacks](https://classic.wowhead.com/quest=871/disrupt-the-attacks#comments) you can see several comments mention that you can do both quests at the same time. Examples:
>it's not a prereq for supplies for the crossroads, perhaps you just weren't a high enough level for the supplies quest. He gave me both at once to do.

>I got both quests from the same guy at the same time. When I accepted the first quest, I then clicked on him again and got "Supplies for the Crossroads"

>This leads to "The Disruption ends" ... the Supplies task is not in the chain, since you can get it at the same time as this task depending on your level.

I have reported this earlier on Hyjal bugtracker. https://github.com/the-hyjal-project/bugtracker/issues/197

I believe this bug comes from [Classic Wowhead](https://classic.wowhead.com/quest=5041/supplies-for-the-crossroads) listing *Disrupt the Attacks* as a requirement for *Supplies for the Crossroads*. [Here's a report from Hyjal bugtracker](https://github.com/the-hyjal-project/bugtracker/issues/75) referencing the Classic Wowhead, and [here's](https://github.com/vmangos/core/commit/c1db8e8f625ba5dbba3c03a11eafb4411e1557db) where I think it was "fixed" from correct to wrong.

**Comment by NickTyrer** [comment]
Closed here https://github.com/vmangos/core/pull/1483
