### ISSUE TITLE
🐛 [Bug] NPC 13397 with heavy stats

### ISSUE THREAD

**Issue by Preesoo** [vmangos/core#1543]
Alterac Valley Horde NPC from north mine (Irondeep mines) have heavy stats compared to the alliance NPC

https://classic.wowhead.com/npc=13397/irondeep-peon
https://classic.wowhead.com/npc=13396/irondeep-miner

Horde Irondeep Peon stats are:
5,532 Armor
45,745 Health

alliance Irondeep miner stats are:
2,764
6,712 Health

is so huge unbalanced stats... also the horde one can almost 1shoot ally people
I report this because when horde capture the north mines is almost impossible to get it back as alliance, you maybe need an big team for get it back.

**Comment by ratkosrb** [comment]
That's not true. They have the same stats.

![WoWScrnShot_071422_103601](https://user-images.githubusercontent.com/35845488/178928259-72dd43dd-d23d-42cd-8134-3145c2f5dc2d.jpg)

![WoWScrnShot_071422_103708](https://user-images.githubusercontent.com/35845488/178928285-5de85544-3627-4eb9-9db1-4e8b1980a22b.jpg)

**Comment by Wall-core** [comment]
Issue is with LH DBs, resolved within Everlook core. Ticket can be closed.
