### ISSUE TITLE
🐞 [Bug]Death Wish and Enrage Not Increasing Damage of Bloodthirst and Execute

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#1545]
## 🐞 Bug report - Spell
1. Death Wish should increase the damage of Bloodthirst
https://youtu.be/SAvtedUik1Q (proof from classic PTR)
2. Death Wish should increase the damage of Execute
https://youtu.be/IUOHvH5XHVA (proof from classic PTR)
3. Enrage should increase the damage of Bloodthirst
https://youtu.be/GhQL4rxdcYw (proof from classic PTR)
4. Enrage should increase the damage of Execute

Commit Hash: 0aa048d

**Comment by HS-Disq** [comment]
This is a bigger issue. Bloodthirst and Execute are found to not be affected by any % damage buffs and debuffs. This includes both internal and external buffs and debuffs.

As the above poster said, Enrage and Death Wish are not applied to Bloodthirst and Execute.
If you are in Defensive Stance, which reduces damage by 10%, it is also not being applied,
It becomes a bigger issue when the debuff that Thaddius gives also isn't affecting Bloodthirst and Execute.

Attached you will find two screenshots, both at same amount of AP (1396). One is without Death Wish, one is with Death Wish. Screenshots are made on the Darrowshire project.

![unknown (1)](https://user-images.githubusercontent.com/21331842/179343762-b1d62261-a4b8-42fb-a2be-6d9b56509d60.jpg)
![unknown (2)](https://user-images.githubusercontent.com/21331842/179343765-910714eb-e932-46f2-9f24-23009a866878.jpg)

 We have also reported some time ago that Bloodthirst and Execute sometimes miss against lvl 63 mobs at hit capped. It looks like they are being affected by the 1% spell hit miss penalty even though they are yellow melee hits and shouldn't be affected at all.

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/d4a09912a101833065c14ae99534f8e8a19f7029
