### ISSUE TITLE
🐛 [Bug] Doors doesn't do LOS and can aggro/attack NPCs

### ISSUE THREAD

**Issue by Preesoo** [vmangos/core#1547]
Greetings! today I just notice something about doors
Looks like NPCs can be aggro over the doors instead doing LOS, also they can be attacked with range damage.
this issue can make a lot of asspulls in dungeons (like stratholme, scholomance doors) 

here some SS and a video:

![LOS](https://user-images.githubusercontent.com/109251304/179645619-f91ce1f8-4576-4dd6-8f34-e1099c0039dd.PNG)
![LOS2](https://user-images.githubusercontent.com/109251304/179646138-c58ce94c-3afc-4539-8b4f-aaa6fb426b2a.PNG)
![LOS3](https://user-images.githubusercontent.com/109251304/179646143-b6a46bd8-a258-40a8-ae8c-e293fcfab02c.PNG)

https://user-images.githubusercontent.com/109251304/179646261-d0ba91b3-3e3c-46a6-9bde-de968e6351ce.mp4

.

**Comment by Wall-core** [comment]
Fixed in bdcbeaa036d852fceb97235b85a181c18e323e9f
