### ISSUE TITLE
🔧 [Support]How to replace the v18 map with a new map

### ISSUE THREAD

**Issue by Yuukiring** [vmangos/core#1548]
I'm here again☺

Directly replacing the map file will cause mangos to fail to start

Where does the source code need to be modified to adapt to the new map file

please help me

**Comment by Yuukiring** [comment]
Can I replace all the codes in #1433 to v18 source

**Comment by ratkosrb** [comment]
You can't do that. Just update to newest repack.

**Comment by Yuukiring** [comment]
> You can't do that. Just update to newest repack.

i can’t
I have a lot of player data, which will cause the server to crash after updating

**Comment by Kittnz** [comment]
find out what the crash is?

**Comment by Yuukiring** [comment]
> find out what the crash is?

ok，i will try
thank u very much
