### ISSUE TITLE
patch 1.7.0

### ISSUE THREAD

**Issue by w5860363** [vmangos/core#156]
Patch 1.7.0 (13-Sep-2005): Moved from Orgrimmar to Everlook to promote more intuitive quest flow.
10307 patch=0 faction=876 10307 patch=8 faction=855
But I didn't see any changes in patch 1.10
https://www.wowdb.com/npcs/10307-witch-doctor-mauari

**Comment by ratkosrb** [comment]
His faction was changed from horde-only to neutral.

https://web.archive.org/web/20070815125842/http://wow.allakhazam.com/db/mob.html?wmob=10307
> Posted: May 7th 2006
> Alliance now have access to this quest. It was first not available to the alliance, horde only.

**Comment by w5860363** [comment]
@ratkosrb https://github.com/vmangos/core/blob/ffb2c9c8378b42ba81ea7f2e80967a93f0f192d7/sql/old_migrations/20181016215801_world.sql
creautre 10307 patch_min=5
server patch<5 >8 faction horde-only Is it right?

**Comment by ratkosrb** [comment]
There is no mistake. NPC was moved to Everlook in 1.7, but it was still Horde faction. Alliance could not take the quest. Then it was made Neutral in 1.10 and now Alliance could do the quest. Check the Allakhazam comments i linked.
