### ISSUE TITLE
Warlock partybot not casting demon armour 

### ISSUE THREAD

**Issue by Reav1** [vmangos/core#1560]
**Current behavior**: Warlock party bots do not cast/ buff themselves with demon armour 

**Expected behavior**: should correctly cast/buff themselves with demon armour. It is written in their ai. 

**Steps to reproduce**: clone a warlock character as a party bot. They are added to the party but do not then buff themselves with/ cast demon armour 

1. 
2. 
3. 

**Client version**: 1.12

**Commit hash**: ?

**Operating system**: windows 7

**Comment by ratkosrb** [comment]
I can't reproduce the issue. He buffs himself with Demon Armor.
![WoWScrnShot_081222_125026](https://user-images.githubusercontent.com/35845488/184330227-63f1142f-954a-4cd4-aed1-187d97913d53.jpg)
