### ISSUE TITLE
🐛 [Bug] Wanted poster Steamwheedle Port

### ISSUE THREAD

**Issue by Grimfeather** [vmangos/core#1567]
## 🐛 Bug report

https://i.gyazo.com/f0837a533fde9d2c72404c581664357f.jpg
The wanted poster at the Steamwheedle Port in Tanaris can't be used to pick up quests.

### Expected behavior

It should let you pick up 2 quests: "WANTED: Caliph Scorpidsting" and "WANTED: Andre Firebeard"
https://wowpedia.fandom.com/wiki/Wanted_Poster_(Steamwheedle_Port)
Those 2 quests can right now only be picked up at Gadgetzan.

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  ?

OS Client: Windows 10
OS Server: Windows 7

### Crashlog

- None

**Comment by NickTyrer** [comment]
Closed in #1600
