### ISSUE TITLE
🐛 [Bug] a few unskinnable mobs

### ISSUE THREAD

**Issue by Grimfeather** [vmangos/core#1573]
## 🐛 Bug report

Somnus, Swamp of Sorrows = https://i.gyazo.com/4866412644d29b80ed77917124d1fe7a.jpg
Deathmaw, Burning Steppes = https://i.gyazo.com/3a71ea5e53c711b8db5abdc5ba97f6d9.jpg
Hematos, Burning Steppes = https://i.gyazo.com/c0e0a7fa89d749c63063ec0f702042c1.jpg
Ripscale, Dustwallow Marsh = https://i.gyazo.com/5cfb4e11c0724fad6e7b884c03498b20.jpg
Dart, Dustwallow Marsh = https://i.gyazo.com/49144a9018c0f54f2578c6f8c93a5418.jpg

Playing on Light's Hope 1.12 Repack v21, 1.8 Dragons of Nightmare patch

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  

OS Client: Windows 10
OS Server: Windows 7

### Crashlog

- None

**Comment by NickTyrer** [comment]
Closed in #1600
