### ISSUE TITLE
🐛 [Bug] Run at Mount Speed

### ISSUE THREAD

**Issue by wonderlandx** [vmangos/core#1577]
Run on foot at mounted speed, travel form speed, and more (including not being able to move in normal gameplay situations).

https://www.youtube.com/watch?v=m_YbWcdDUdU

**Comment by ratkosrb** [comment]
I am unable to reproduce this locally. Can you run a sniffer while doing this, and then send me the sniff?

**Comment by wonderlandx** [comment]
what packet sniffer do i use

**Comment by wonderlandx** [comment]
also its the lack of latency and or youre doing the timing wrong.

**Comment by ratkosrb** [comment]
Fixed already.
