### ISSUE TITLE
The mage's blizzard can not be pre-targeted, similar to the need to pull out the range box pre-targeting skills there are many, can not be achieved🐛 [Bug]

### ISSUE THREAD

**Issue by Wh2sKey** [vmangos/core#1585]
### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by ratkosrb** [comment]
This is not a bug. It's normal 1.12 client behavior. Use the 1.14 client if you want to be able to target AoE spells while moving.
