### ISSUE TITLE
The mage turned into a mosaic after turning into a pig🐛 [Bug]

### ISSUE THREAD

**Issue by Wh2sKey** [vmangos/core#1586]
### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by ratkosrb** [comment]
You are most likely using a spell from a newer patch than the one the server is set to. What is WowPatch set to in your config?

**Comment by Daribon** [comment]
This can be closed as this is not related to vmangos.
It was a bug on everlook PTR.
