### ISSUE TITLE
[Bug] instance death animation problem

### ISSUE THREAD

**Issue by w5860363** [vmangos/core#1589]
https://user-images.githubusercontent.com/1938163/187063309-99058b8a-d2d7-4088-8eb5-50c27cc58604.mp4

Steps to reproduce
1.gm on
2.go cr 56702
3.dam 10000000
But it works fine with .die

Client Version:
1.12.1.5875
Commit Hash:
https://github.com/vmangos/core/commit/373fde44b3c8c6f5236656e31dabffbb5f728037

OS Client and Server:

Windows 10 Professional 64bit
Crashlog
None

**Comment by w5860363** [comment]
@ratkosrb Confirmed to be caused by https://github.com/vmangos/core/commit/cb006632a669efb4e556815974f83bb69183d1f0 Can you check this?

**Comment by Grimfeather** [comment]
I've also noticed some odd instant deaths in v21, no death animation at all. Why was this closed? Wrong bug report format?
It doesn't happen all the time. Sometimes the death animation is normal, sometimes instant like no animation at all.
And sometimes it gets back up, after it just went down instantly without an animation, and THEN the death animation plays.

**Comment by w5860363** [comment]
@Grimfeather I have confirmed that submitting will solve the problem https://github.com/vmangos/core/commit/d7e2dee88304745540527d6a9f33dd0b9aeddc9c

**Comment by ratkosrb** [comment]
It's closed because I fixed it.
