### ISSUE TITLE
totol-vm grow up

### ISSUE THREAD

**Issue by chendh123** [vmangos/core#159]
After update,  memory usage increased from 1.4G to 2.4G after a day of running.

Mar  8 09:08:20 AY140522134807845ba4Z kernel: Out of memory: Kill process 12187 (mangosd) score 479 or sacrifice child
Mar  8 09:08:20 AY140522134807845ba4Z kernel: Killed process 12187, UID 503, (mangosd) total-vm:2473908kB, anon-rss:1567948kB, file-rss:444kB

**Comment by wzw1990** [comment]
same problem!

**Comment by ratkosrb** [comment]
It takes 3 GB of ram to load all the mmaps. If preloading of terrain is not enabled, memory usage will increase as players and mobs wander into different zones, forcing the mmaps for that area to be loaded. You can disable mmaps completely if you want to reduce memory usage.

mmap.enabled = 0

**Comment by chendh123** [comment]
I ran for a week before the update, and the memory was stable at about 1.6G.

**Comment by ratkosrb** [comment]
Which update?

**Comment by chendh123** [comment]
Between SHA-1: cb7d83495d6129a60aff4234c1c2951ee7d7089b and SHA-1: a52fe8ffe8f45ea1298d52663cb37ae947b0f261

**Comment by ratkosrb** [comment]
I see nothing here that can cause increased memory usage.

**Comment by chendh123** [comment]
I'll keep testing for a while. 
<img width="506" alt="image" src="https://user-images.githubusercontent.com/15760697/54034582-32b31900-41f2-11e9-9f7d-eb4b9018ac07.png"> tag 20190308 22:33

**Comment by chendh123** [comment]
![image](https://user-images.githubusercontent.com/15760697/54063781-d976d400-4249-11e9-8e5a-afea5adeaf10.png) tag 20190309 09:01

**Comment by chendh123** [comment]
/var/log/message
Mar  7 14:18:12 AY140522134807845ba4Z kernel: Out of memory: Kill process 23554 (mangosd) score 498 or sacrifice child
Mar  7 14:18:12 AY140522134807845ba4Z kernel: Killed process 23554, UID 503, (mangosd) total-vm:2510044kB, anon-rss:1558996kB, file-rss:2740kB


Mar  8 09:08:20 AY140522134807845ba4Z kernel: Out of memory: Kill process 12187 (mangosd) score 479 or sacrifice child
Mar  8 09:08:20 AY140522134807845ba4Z kernel: Killed process 12187, UID 503, (mangosd) total-vm:2473908kB, anon-rss:1567948kB, file-rss:444kB



Mar  9 16:43:29 AY140522134807845ba4Z kernel: Out of memory: Kill process 22458 (mangosd) score 532 or sacrifice child
Mar  9 16:43:29 AY140522134807845ba4Z kernel: Killed process 22458, UID 503, (mangosd) total-vm:2678524kB, anon-rss:1611664kB, file-rss:1020kB


Mar  9 21:20:36 AY140522134807845ba4Z kernel: Out of memory: Kill process 19117 (mangosd) score 424 or sacrifice child
Mar  9 21:20:36 AY140522134807845ba4Z kernel: Killed process 19117, UID 503, (mangosd) total-vm:2348096kB, anon-rss:1349964kB, file-rss:816kB

**Comment by DarkmoonRabbit** [comment]
Expand your memory.

**Comment by chendh123** [comment]
![image](https://user-images.githubusercontent.com/15760697/54486161-24828e00-48bf-11e9-99f9-02c4d7ed1378.png)
I only have 30 players.

It's been running for half a year and it's never taken up so much memory before update.

**Comment by chendh123** [comment]
![image](https://user-images.githubusercontent.com/15760697/54893605-865f7b00-4ef1-11e9-9639-d8d2759da50a.png)
It's been running for 6days.

**Comment by ratkosrb** [comment]
Using 4GB looks normal to me. It takes 3GB only to load all the maps.

**Comment by chendh123** [comment]
![image](https://user-images.githubusercontent.com/15760697/54962792-317b3d80-4fa1-11e9-8cbd-52f2d34618ee.png)

**Comment by chendh123** [comment]
@ratkosrb  Maybe  ahbot cause this problem.
Disable ahbot, and running for half day.
![image](https://user-images.githubusercontent.com/15760697/55055416-d3805000-509d-11e9-9c9f-7c631829526b.png)

**Comment by chendh123** [comment]
Disable ahbot, and running for 6 days.
I think the item may not have been released. @ratkosrb 
![image](https://user-images.githubusercontent.com/15760697/55367719-06ed2f80-5521-11e9-812c-c7c058319244.png)

**Comment by chendh123** [comment]
No rule can be found.
