### ISSUE TITLE
🐛 [Bug] stuck npc's

### ISSUE THREAD

**Issue by Grimfeather** [vmangos/core#1592]
## 🐛 Bug report

Playing on V21, I found a few creatures that are still stuck in or under the ground.
- Alterac Mountains, stuck turtle: https://i.gyazo.com/e1cd4c06ad28516bea15c26228cf234b.jpg
- Ashenvale, stuck wolf: https://i.gyazo.com/a8060cd3d6805a14e5dac3123c0f55d9.jpg
- Feralas, stuck ogre: https://i.gyazo.com/246beac9f3fe8e4ca0796f5b92f2bce7.jpg

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  

OS Client: Windows 10
OS Server: Windows 7

### Crashlog

- None

**Comment by NickTyrer** [comment]
Closed in #1600
