### ISSUE TITLE
🐛 [Bug] MoveMapGen.exe not working; offmesh.txt missing.

### ISSUE THREAD

**Issue by Sapiverenus** [vmangos/core#1596]
- 1.12.1
  - Windows 7 SP1
 There seemed to be a missing model at the end of _I think_ vmap_assembler.exe
I've deleted the directories generated and tried the process over again. I followed the video in Compiling on Windows in the wiki then the Getting Started section. I used the versions of ACE and TBB they use in the video.
For the extractors, I used CMake option to make the Extractors.

Thank you for your assistance.

**Comment by alexkulya** [comment]
[offmesh.txt](https://github.com/vmangos/core/files/9470760/offmesh.txt)

**Comment by Sapiverenus** [comment]
I have begun movemapgen.exe and it is looking good. I put the file in the root of the client directory. At 110/687 still clear. Thanks.
EDIT: I hope the numbers are good lol. I'll assume so.

**Comment by Sapiverenus** [comment]
Is this really suppose to take days lol  I am at map 001 half way through after 5 hours.

**Comment by Daribon** [comment]
Yes it takes a long time to generate mmaps, especially if you have a slow CPU.

**Comment by Sapiverenus** [comment]
i5-2400 killing me. it's running on 1 core too.

**Comment by Vanheden** [comment]
> 

Download the data files from the repack instead.

**Comment by Sapiverenus** [comment]
I have no clue what this repack is or where it is, but I just got past map 70 and I don't know if I want to stop.

**Comment by Vanheden** [comment]
> I have no clue what this repack is or where it is, but I just got past map 70 and I don't know if I want to stop.

PM me on Discord: Roddan#2093

**Comment by Sapiverenus** [comment]
I'm on map 429 I might as well keep it going

**Comment by Sapiverenus** [comment]
"Note that the dbc path must also include the build number of the client from which the files were extracted. If you are unsure what is the exact build, you can see it in the lower left corner of the login screen. The build number of the 1.12.1 client is 5875."

This wiki needs some updating because I am not sure where I am suppose to put this number 5875.

**Comment by ratkosrb** [comment]
In the data directory where the "maps", "vmaps" and "mmaps" folder are, make a folder with the  build number as the name, and then place the dbc folder inside it.

**Comment by Sapiverenus** [comment]
The server directory I moved these to is the C:\MaNGOS folder I made earlier with realmd and mangosd in it right? Thanks for the info

**Comment by Sapiverenus** [comment]
and now I must load databases but they don't connect; there's no admin option on these files for some reason. Are they scheme I load into a database or their own database and I need to figure out command line power user stuff to get it to run as admin?

EDIT: I've gotten past the confusion of this step and have begun progression once more.

**Comment by xBarselonx** [comment]
> [offmesh.txt](https://github.com/vmangos/core/files/9470760/offmesh.txt)

Привет! 
А файл [offmesh.txt](https://github.com/vmangos/core/files/9470760/offmesh.txt) в корень клиента игры закинуть?

**Comment by Misaka10148** [comment]
> Yes it takes a long time to generate mmaps, especially if you have a slow CPU.

I've been running "MoveMapGenerator.exe“  for over 12 hours，only building titles on Map 000 . The CPU is i7 - 12650H.

<img width="543" height="483" alt="Image" src="https://github.com/user-attachments/assets/33f21834-e9e0-4bfd-9374-b067e1ea8466" />

<img width="539" height="412" alt="Image" src="https://github.com/user-attachments/assets/2515c2f8-a878-46e2-80ad-48f242487d96" />

i have solved this problem. when i configure the SourceCode with CMake used “Visual Studio 2026(V145 by default)”，but V142 was not filled in the "option toolset to use(argument to -T)".
