### ISSUE TITLE
🐛Pet HP regen tick rate [not vanilla-like]

### ISSUE THREAD

**Issue by Simp-N** [vmangos/core#1597]
On pservers hunter pets regenerate health every 2 seconds, like player characters. However in actual vanilla and in Classic, pets regenerate health every 5 seconds. 

The two pservers I've played on since Classic, Hyjal and Everlook, which are both based on vmangos afaik, have had hunter pet regen that felt very high. I suspect that when Classic came, pet regen was altered in Vmangos to match that of Classic, but since the tick rate is quicker on Vmangos, the pets simply regenerate too much. I don't know exactly how much pets should regen, but my point is that it should tick every 5 sec instead of every 2. The amount they're currently regen *might be good enough* that you needn't do any re-balancing for the slower tick rate, for simplicity's sake. I've tried gathering some info from Classic and will present comparisons below, but sadly I couldn't find any good info from actual vanilla of exactly how much a pet regens for.

[Classic, lvl 60 Cat, 3089 max HP](https://youtu.be/nUX5TsxfeY4?t=115)
1768 -> 2011
243 hp per tick
**48,8 hp per sec**

[Classic, lvl 60 Cat, 3060 max HP](https://youtu.be/mOzuwMtBQhU?t=280)
2241 -> 2484
243 hp per tick
**48,8 hp per sec**

[Everlook, lvl 60 Cat, 2990 max HP](https://streamable.com/ariug0)
760 -> 1072
312 hp per tick
**156 hp per sec**
So over three times more regen at 60. So even slowing the tick rate to 5 sec (2,5 times slower) it will still be a little higher than Classic, but at least it'll be more reasonable.

[Classic, lvl 20 Boar, 567 max HP](https://streamable.com/9td18f)
428 -> 515
87 hp per tick
**17,4 hp per sec**

[Everlook, lvl 19 Tallstrider, 604 max HP (ignoring 30 sta from T1 set bonus)](https://streamable.com/sr4e0p)
653 -> 721
68 hp per tick
**34 hp per sec**
A little under two times more regen at lvl 19-20.

[Light's Hope, lvl 19 Tallstrider, 602 max HP](https://streamable.com/54rszf)
256 -> 288
32 hp per tick
**16 hp per sec**
I'm including the LH example to show that the amount regenerated obviously been increased since then and that the older regen was more inline with vanilla (or Classic rather) even if the tick rate was every 2 sec.

If the rate is to be slowed to 5 sec, maybe the amount regenerated should be a little higher on lower level pets, and a little lower on higher level pets. Anyway, I hope I make myself comprehensible. What do you think?

Also, Warlock pets should also regenerate HP every 5 sec, but they do not currently regain such absurd amounts as hunter pets.

Lastly, if you want footage from actual vanilla of pet regen every 5 sec:
[45:53](https://youtu.be/v0BPUXwqpeg?t=2753)
[1:29:27](https://youtu.be/Ehxo0J_87iI?t=5367)

**Comment by NickTyrer** [comment]
Closed in https://github.com/vmangos/core/commit/1258a93c349f93d62fd7d0887585a95f4302768e
