### ISSUE TITLE
🐞 [Bug] Divine Shield

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#1599]
**Current behavior**: 

When using divine shield the casting animation is interrupted with physical attacks.

This is the same issue as https://github.com/vmangos/core/issues/451. This was fixed in (https://github.com/vmangos/core/commit/66ebe7f87912dccc032bb293e9b5f3a0990de4ca)

**Expected behavior**: 

The casting animation should not be affected by physical attacs when the shield is active.

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/cdaad1c554293617e73c25dd2210fe83b53468fa
