### ISSUE TITLE
 Mage Frostbite talent spell breaks instantly after its poping.🐞 [Bug]

### ISSUE THREAD

**Issue by Alller** [vmangos/core#1601]
### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by Alller** [comment]
https://user-images.githubusercontent.com/112757757/188267989-9e1af05f-83b1-40e1-bf5d-d9981d150c50.mp4

**Comment by natrist** [comment]
Can you please elaborate on the issue and the steps needed to reproduce it? Thank you.

**Comment by ratkosrb** [comment]
I think this report is from the Everlook private server, and not a clean vmangos. Wall talked to me about it before and I was unable to reproduce it myself.

**Comment by natrist** [comment]
Can we tag it as such and close the issue?
