### ISSUE TITLE
🐛 [Bug] Eyes of the Beast dismissing pet on long range.

### ISSUE THREAD

**Issue by Daribon** [vmangos/core#1616]
## 🐛 Bug report

If you use Eyes of the Beast and run away with the pet outside your viewing range, the pet will despawn when buff cancels.
### Expected behavior

On classic if you run away with pet ouside your viewing range, the pet will teleport back to your side when buff cancels.

I have no proof from vanilla due to how uncommon the usage of the spell is.
The spell was removed in cataclysm and later added again shadowlands.
I believe the classic behavior mirrors that of vanilla.
### Steps to reproduce

1. Create a Night Elf hunter
2. .learn 1002
3. Target nearest boar
4. Use Eyes of the beast
5. Run as far as you can with the pet.
6. Cancel buff.
7. Pet will be dismissed.

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  https://github.com/vmangos/core/commit/373fde44b3c8c6f5236656e31dabffbb5f728037

OS Client: Microsoft Windows 11 Pro N 10.0.22000 Build 22000
OS Server: Microsoft Windows 11 Pro N 10.0.22000 Build 22000

### Crashlog

- None

**Comment by ghost** [comment]
[Feiyan...hunter solo Slave Pens Heroic](https://www.youtube.com/watch?v=YvYiRsCV9FM) (Early TBC)

[The pet despawned when Eyes of the Beast expired](https://youtu.be/YvYiRsCV9FM?t=115) (cancellation couldve possibly resulted in it being teleported to the owner), but what's interesting is that you could [renew EotB without losing control](https://youtu.be/YvYiRsCV9FM?t=87) of the pet (not currently possible on vmangos, you get the error "You already control a charmed creature").

**Comment by Daribon** [comment]
> [Feiyan...hunter solo Slave Pens Heroic](https://www.youtube.com/watch?v=YvYiRsCV9FM) (Early TBC)
> 
> [The pet despawned when Eyes of the Beast expired](https://youtu.be/YvYiRsCV9FM?t=115) (cancellation couldve possibly resulted in it being teleported to the owner), but what's interesting is that you could [renew EotB without losing control](https://youtu.be/YvYiRsCV9FM?t=87) of the pet (not currently possible on vmangos, you get the error "You already control a charmed creature").

Great source of information you found there.
The user that uploaded that TBC video has a bunch of videos from vanilla, showing eyes of the beast.
https://www.youtube.com/user/s923051/videos

I'm gonna have a closer look later.

**Comment by ghost** [comment]
[Feiyan...hunter solo BRD king 1/2 [5:06]](https://youtu.be/o8wQaEixX_I?t=306) – cancelled, despawned

[Feiyan...hunter solo Naxx DK小怪 [0:42]](https://youtu.be/eQsmEK6Wp94?t=42)

[Feiyan...Hunter solo DM north(補充畫面) [2:38]](https://youtu.be/W_BgaXLI7Dc?t=158) – cancelled; not far enough to despawn (iirc the range is about 60 yards)

[Feiyan...hunter solo DMe 女術士 + 水元素王 [6:30]](https://youtu.be/xcKzaHhmx5M?t=390) – no despawn

[Feiyan...hunter solo MC小怪 [3:14]](https://youtu.be/2JCusIVD0KU?t=194) – roughly 30-40 yards, no despawn

[Feiyan...hunter solo DMn no.1 boss [0:33]](https://youtu.be/5E3VOTby-Lg?t=33)

[Feiyan...hunter solo DM north [6:57]](https://youtu.be/Z9ULNE_hWsg?t=417) and [[7:50]](https://youtu.be/Z9ULNE_hWsg?t=470) despawn

despawn range [3:28](https://youtu.be/0Zz_N971uGg?t=208) - [4:37](https://youtu.be/0Zz_N971uGg?t=277)

[Feiyan..hunter solo BRD [0:57]](https://youtu.be/QQ2A0SVGt6Q?t=57)

**Comment by Daribon** [comment]
Video from vanilla https://youtu.be/9Sh4k3rAZSE?t=273 hunter pet despawns when out of range when buff is cancelled.

Guess this can be closed then, considering the vanilla mechanic appears to be that if pet is out of visible range it should despawn.
That is the current vmangos behavior.

I wonder however, if it was possible to chain Eyes of the Beast in vanilla.
I tested Eyes of the Beast on Classic and as long you are in LOS you can continue recasting Eyes of the Beast forever. Yet have I found any proof of it working this way in vanilla.
