### ISSUE TITLE
🐛 [Bug] No Mana/Ley Sprite Spawns

### ISSUE THREAD

**Issue by heyitsbench** [vmangos/core#1619]
### Expected behavior

[Mana Sprites](https://classic.wowhead.com/npc=12382) and [Ley Sprites](https://classic.wowhead.com/npc=12381) should reside in Deadwind Pass.

### Steps to reproduce

1. `.tele deadwindpass`
2. Observe no [Mana Sprites](https://classic.wowhead.com/npc=12382) nor [Ley Sprites](https://classic.wowhead.com/npc=12381).

### Version & Environment

Client Version: All.

Commit Hash:  68d13efa3452a2c6da892e0fa9424d58678d65c5

OS Client: Windows 10 Home x64
OS Server: Windows 10 Home x64

### Crashlog

- None

**Comment by Daribon** [comment]
I believe this is sniffed. If it is not already sniffed I will sniff the spawns and waypoints.

**Comment by heyitsbench** [comment]
> I believe this is sniffed. If it is not already sniffed I will sniff the spawns and waypoints.

I was going to attempt to, but I do not have a character high level enough to survive the area.

**Comment by NickTyrer** [comment]
@heyitsbench You can use the PTR and get an lvl 60 char. You can sniff whatever you like and hopefully make a PR.
