### ISSUE TITLE
Andrew Krighton, Corina Steele & Motega Firemane - Add waypoints, emotes

### ISSUE THREAD

**Issue by alexkulya** [vmangos/core#162]
Andrew Krighton (EntryID: 2046) - waypoints, emotes
Corina Steele (EntryID: 54) - waypoints, emotes
Motega Firemane (EntryID: 10428) - waypoints, emotes

<pre>
UPDATE `creature` SET `position_x` = -9464.08, `position_y` = 87.9186, `position_z` = 58.343, `orientation` = 0.00112867, `spawndist` = 0, `MovementType` = 2 WHERE `id` = 2046;
UPDATE `creature_template` SET `MovementType` = 2 WHERE `entry` = 2046;
DELETE FROM `creature_movement_template` WHERE `entry` = 2046;
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `waittime`, `emote`) VALUES
(2046, 1, -9464.08, 87.9186, 58.343, 0.001129, 60000, 0),
(2046, 2, -9464.31, 89.2169, 58.343, 2.267, 10000, 233),
(2046, 3, -9464.31, 89.2169, 58.343, 2.267, 5000, 0);
UPDATE `creature_template` SET `equipment_id` = 2046 WHERE `entry` = 2046;
DELETE FROM `creature_equip_template` WHERE `entry` = 2046;
INSERT INTO `creature_equip_template` (`entry`, `equipentry1`, `equipentry2`, `equipentry3`) VALUES
(2046, 1903, 0, 0);
</pre>

<pre>
UPDATE `creature` SET `spawndist` = 0, `MovementType` = 2 WHERE `guid` = 80338 AND `id` = 54;
DELETE FROM `creature_movement_template` WHERE `entry` = 54;
INSERT INTO `creature_movement_template` (`entry`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `waittime`, `emote`) VALUES
(54, 1, -9460.3, 101.247, 58.3437, 1.05485, 8000, 233),
(54, 2, -9464.4, 94.0174, 58.3437, 0.0349066, 45000, 0),
(54, 3, -9464.4, 94.0174, 58.3437, 3.13513, 8000, 69),
(54, 4, -9464.4, 94.0174, 58.3437, 0.0349066, 45000, 0);
</pre>

<pre>
UPDATE `creature` SET `spawndist` = 0, `MovementType` = 2 WHERE `guid` = 21693 AND `id` = 10428;
DELETE FROM `creature_movement` WHERE `id` = 21693;
INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `waittime`, `emote`) VALUES
(21693, 1, -4915.57, -1381.18, -52.6008, 5.14872, 60000, 23),
(21693, 2, -4913.27, -1379.59, -52.6119, 0, 0, 0),
(21693, 3, -4911.95, -1376.93, -52.6119, 0, 0, 0),
(21693, 4, -4913.82, -1376.04, -52.6119, 3.044563, 15000, 0),
(21693, 5, -4915.75, -1378.4, -52.6119, 0, 0, 0),
(21693, 6, -4918.77, -1378.01, -52.6119, 0, 0, 0);
</pre>

**Comment by ratkosrb** [comment]
What is the source for the Andrew Krighton and Corina Steele changes? They have the same spawn position in cmangos/trinity.

You can see their position is the same in this wotlk video:
https://youtu.be/mEIOdAYF3Lk?t=283
https://youtu.be/mEIOdAYF3Lk?t=542

And Andrew Krighton has no hammer in the video.
Nor does he have it in the pre-cataclysm screenshots on wowhead.
https://www.wowhead.com/npc=2046/andrew-krighton#screenshots:id=822820

**Comment by alexkulya** [comment]
@ratkosrb My Bad. For vanilla need only script NPC: Motega Firemane. The first two scripts are not needed.
