### ISSUE TITLE
🐛 [Bug] Succubus incorrect stats

### ISSUE THREAD

**Issue by Daribon** [vmangos/core#1621]
## 🐛 Bug report

Current vmangos stats of Succubs with no talents at level 60:
![WoW_qDZf11IIsP](https://user-images.githubusercontent.com/6137576/189506058-2d532144-b7e7-44fa-bc51-6ad0e2365aa3.png)
![WoW_DUT7HwPU4N](https://user-images.githubusercontent.com/6137576/189506060-e7ad7e06-072f-45af-88ec-1342f62bffb9.png)

### Expected behavior

Succubus stats at level 60 with talents from 2006-09-03:
![WoWScrnShot_090306_113009](https://user-images.githubusercontent.com/6137576/189506086-12b7e020-13b9-462f-91ea-2a5d2ff075eb.jpg)
The player has talents Fel Intellect 15% increased mana, Fel stamina 15% HP, Master Demonologist 10% damage and Unholy Power 20% increased damage.

Succubus stats at level 59 with talents from 2006-08-29:
![WoWScrnShot_082906_204414](https://user-images.githubusercontent.com/6137576/189507549-c1ba667a-172a-4dce-af73-0b553619874c.jpg)
Same talents as prior 2006 screenshot.

Succubus stats at level 58 with talents from 2006-08-25:
![WoWScrnShot_082506_162052](https://user-images.githubusercontent.com/6137576/189507206-07117e56-78bf-44b1-ad35-9b8f61208c89.jpg)
Same talents as prior 2006 screenshot.

Succubus stats at level 52 with talents from 2006-08-25:
![WoWScrnShot_072506_192620](https://user-images.githubusercontent.com/6137576/189507378-814fdea1-fc6c-4733-86f5-0de2d9e77aa7.jpg)
Same talents as prior 2006 screenshot.

Stats from a 60 warlock on classic with same talents as the 2006 screenshot:
![WowClassicT_L0dKCAuv7v](https://user-images.githubusercontent.com/6137576/189506248-e8749973-ba6a-42a6-81b4-a45d7fed3fbe.png)
![WowClassicT_OQyeSAnHyn](https://user-images.githubusercontent.com/6137576/189506249-46f2e795-536c-45b1-bf48-964076ea0bca.png)
Taken with Fel Intellect 15% increased mana, Fel stamina 15% HP, Master Demonologist 10% damage and Unholy Power 20% increased damage.
It matches up exactly with the 2006 screenshot even though it was taken from classic.

Stats from a 60 warlock on classic with no talents:
![WowClassicT_C1jaDvrmIB](https://user-images.githubusercontent.com/6137576/189506123-43999b67-cfbd-4ef1-961a-3f7bcd1ebd5b.png)
![WowClassicT_VwFG0HQ8or](https://user-images.githubusercontent.com/6137576/189506132-7ab0e773-1743-45b1-a082-d8b94a3bdea9.png)
### Steps to reproduce

1. Create a warlock
2. .level 59
3. .learn 712
4. .additem 6265
5. Cast summon Succubus

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  https://github.com/vmangos/core/commit/373fde44b3c8c6f5236656e31dabffbb5f728037

OS Client: Microsoft Windows 11 Pro N 10.0.22000 Build 22000
OS Server: Microsoft Windows 11 Pro N 10.0.22000 Build 22000

### Crashlog

- None

**Comment by NickTyrer** [comment]
Don't we have the correct stats now?

**Comment by Daribon** [comment]
no

**Comment by NickTyrer** [comment]
Not this https://github.com/vmangos/core/commit/bae3603dfa9b94d58df500c17623a05ec4056e7d ?

**Comment by Daribon** [comment]
Currently all stats match vanilla except damage.
Stats on vmangos currently have too low damage.
From latest build with no talents:
![WoW_dIR9vzU2mM](https://user-images.githubusercontent.com/6137576/192122111-885389f6-f644-4867-9f1e-28e9a795c6cd.png)

We are also missing sniffed data from level 57.

**Comment by Daribon** [comment]
Fixed in https://github.com/vmangos/core/commit/0d59312bc1dbd6fbefc13e5bf934a4bc12afa1a4
Closing.
