### ISSUE TITLE
🐛 [Bug] Voidwalker incorrect stats

### ISSUE THREAD

**Issue by Daribon** [vmangos/core#1622]
## 🐛 Bug report

Current vmangos stats of Voidwalker with no talents at level 60:
![WoW_fF9ZYE8Y29](https://user-images.githubusercontent.com/6137576/189506624-e632ef6a-318a-42ac-ae51-56a1670625e4.png)
![WoW_L0f1rwFvRA](https://user-images.githubusercontent.com/6137576/189506629-f5fe8658-ba2c-4a64-91e6-b6f5ed5acd92.png)

### Expected behavior

Voidwalker stats at level 60 with talents from 2006-09-03:
![WoWScrnShot_090306_113425](https://user-images.githubusercontent.com/6137576/189506643-2fa9a8af-5cf2-4a5f-a857-e1523ac331bf.jpg)
The player has talents Fel Intellect 15% increased mana, Fel stamina 15% HP, Master Demonologist 10% damage and Unholy Power 20% increased damage.

Voidwalker stats at level 53 with talents from 2006-08-08:
![WoWScrnShot_080806_174641](https://user-images.githubusercontent.com/6137576/189507152-cd1c2b81-7693-4b39-a590-0745cdb64577.jpg)
Same talents as the prior 2006 screenshot.

Voidwalker stats at level 54 with talents from 2006-08-09:
![WoWScrnShot_080906_173346](https://user-images.githubusercontent.com/6137576/189507421-b7af4270-d12b-41fa-bff4-7b795231bb12.jpg)
Same talents as the prior 2006 screenshot.

Voidwalker stats at level 51 with talents from 2006-07-18:
![WoWScrnShot_071806_231601](https://user-images.githubusercontent.com/6137576/189507724-230b0ec7-ede1-4de8-9ef8-b14c26dbdb6d.jpg)
Same talents as the prior 2006 screenshot.

Stats from a 60 warlock on classic with same talents as the 2006 screenshot:
![WowClassicT_O0meCOEtnY](https://user-images.githubusercontent.com/6137576/189506670-7ab8be29-a4b0-4459-b950-76b65e0c2376.png)
![WowClassicT_b9gWTdAlFU](https://user-images.githubusercontent.com/6137576/189506671-cc799dd4-7bc8-4f63-ae8b-8c119e35bdf9.png)
Taken with Fel Intellect 15% increased mana, Fel stamina 15% HP, Master Demonologist 10% damage and Unholy Power 20% increased damage.
It matches up exactly with the 2006 screenshot even though it was taken from classic.

Stats from a 60 warlock on classic with no talents:
![WowClassicT_cXqfTkHtU5](https://user-images.githubusercontent.com/6137576/189506797-f69f1d15-76cf-483e-9258-e6da358c0aca.png)
![WowClassicT_XVyXPurdPl](https://user-images.githubusercontent.com/6137576/189506799-a42e3f9a-4841-4590-ae83-93d8713f0356.png)

### Steps to reproduce

1. Create a warlock
2. .level 59
3. .learn 697
4. .additem 6265
5. Cast summon Voidwalker

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  https://github.com/vmangos/core/commit/373fde44b3c8c6f5236656e31dabffbb5f728037

OS Client: Microsoft Windows 11 Pro N 10.0.22000 Build 22000
OS Server: Microsoft Windows 11 Pro N 10.0.22000 Build 22000

### Crashlog

- None

**Comment by NickTyrer** [comment]
Don't we have the correct stats now?

**Comment by Daribon** [comment]
no

**Comment by Daribon** [comment]
Voidwalker currently has too high damage.
Does not match vanilla or classic.

Currently all stats for voidwalker on vmangos match vanilla except damage.
![WoW_i66R6P1IxB](https://user-images.githubusercontent.com/6137576/192121923-27014c7c-f09b-44f6-b0cf-bc05a1e1a082.png)
No talents.

**Comment by Daribon** [comment]
Fixed in https://github.com/vmangos/core/commit/0d59312bc1dbd6fbefc13e5bf934a4bc12afa1a4
Closing.
