### ISSUE TITLE
🐛 [Bug] Felhunter incorrect stats

### ISSUE THREAD

**Issue by Daribon** [vmangos/core#1623]
## 🐛 Bug report

Current vmangos stats of Felhunter with no talents at level 60:
![WoW_BFtouvCqPW](https://user-images.githubusercontent.com/6137576/189507822-37cb210e-fe5a-4ce6-b63c-8b0bb94867a3.png)
![WoW_5Dla1Nm22V](https://user-images.githubusercontent.com/6137576/189507824-6a2bbac0-b8f2-44b3-847e-333dc3bb65f6.png)
### Expected behavior

Felhunter stats at level 60 with talents from 2006-09-03:
![WoWScrnShot_090306_112142](https://user-images.githubusercontent.com/6137576/189507846-9028060b-63a5-4cf9-b2cd-89323ba43b28.jpg)
The player has talents Fel Intellect 15% increased mana, Fel stamina 15% HP, Master Demonologist 10% damage and Unholy Power 20% increased damage.

Felhunter stats at level 59 with talents from 2006-08-27:
![WoWScrnShot_082706_123405](https://user-images.githubusercontent.com/6137576/189507866-82c5e7fb-e7ab-4bc9-a47f-97b55343cadd.jpg)
Same talents as prior 2006 screenshot.

Felhunter stats at level 54 with talents from 2006-08-09:
![WoWScrnShot_080906_174221](https://user-images.githubusercontent.com/6137576/189507896-1d8b1471-3214-439c-bdf7-57ef4dd96b6f.jpg)
Same talents as prior 2006 screenshot.

Stats from a 60 warlock on classic with same talents as the 2006 screenshot:
![WowClassicT_th4ff6OD1P](https://user-images.githubusercontent.com/6137576/189507926-11b0daa8-ee61-445c-b93f-0294644c3b08.png)
![WowClassicT_v8JuJkDMp7](https://user-images.githubusercontent.com/6137576/189507928-9623ce75-fa96-4a0c-9b06-a5ac8862d0c6.png)

Stats from a level 60 warlock on classic with no talents:
![WowClassicT_nfJMgW48mk](https://user-images.githubusercontent.com/6137576/189507957-d816f23c-c2b8-4107-b2f5-d744f610ae35.png)
![WowClassicT_jq2B0fRyNp](https://user-images.githubusercontent.com/6137576/189507959-16090d33-0eca-4536-bfde-da2299d048e2.png)

### Steps to reproduce

1. Create a warlock
2. .level 59
3. .learn 691
4. .additem 6265
5. Cast Felhunter

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  https://github.com/vmangos/core/commit/373fde44b3c8c6f5236656e31dabffbb5f728037

OS Client: Microsoft Windows 11 Pro N 10.0.22000 Build 22000
OS Server: Microsoft Windows 11 Pro N 10.0.22000 Build 22000

### Crashlog

- None

**Comment by NickTyrer** [comment]
Don't we have the correct stats now?

**Comment by Daribon** [comment]
no

**Comment by Daribon** [comment]
All stats except damage match vanilla now.
The damage is currently too low on vmangos.
Image from felhunter with no talents from latest rev:
![WoW_yFjdHpQqda](https://user-images.githubusercontent.com/6137576/192122217-f936b284-13ff-4bf0-a7a3-37bc8ccc02ef.png)

Missing sniff data from level 57 and level 59.

**Comment by Daribon** [comment]
Fixed in https://github.com/vmangos/core/commit/0d59312bc1dbd6fbefc13e5bf934a4bc12afa1a4
Closing.
