### ISSUE TITLE
🐛 [Bug] Bloodshot [11614] is able to be skinned when they shouldn't be

### ISSUE THREAD

**Issue by heyitsbench** [vmangos/core#1624]
## 🐛 Bug report

[Bloodshot](https://classic.wowhead.com/npc=11614) is skinnable.

### Expected behavior

According at least to SoM PTR, Bloodshot should not be skinnable.

### Steps to reproduce

1. `.learn 8613`
2. `.tele westernplaguelands`
3. Kill Bloodshot.
4. Observe the issue.

### Version & Environment

Client Version: Assumed all.

Commit Hash:  bae3603dfa9b94d58df500c17623a05ec4056e7d

OS Client: Windows 10 x64 Home
OS Server: Windows 10 x64 Home

### Crashlog

- None

**Comment by NickTyrer** [comment]
Closed in #1630
