### ISSUE TITLE
Neutral (yellow) starting mobs are linked/chain aggroing🐛 [Bug]

### ISSUE THREAD

**Issue by lvangh** [vmangos/core#1646]
## 🐛 Bug report
Playing on Everlook PTR

### Expected behavior
Burly Rockjaw Troggs and Rockjaw Troggs for example are link aggroing when one is attacked which is not matching to Classic  

### Steps to reproduce
Attack a yellow/neutral mob with another one nearby, both will aggro. 

### Version & Environment

  - 1.12.1.5875

OS Client: Win  10
OS Server: 

### SS
![image](https://user-images.githubusercontent.com/19690096/194814781-609f8444-c3a4-491f-aa19-28f7e44897e4.png)

**Comment by NickTyrer** [comment]
Can confirm this on latest build.

**Comment by NickTyrer** [comment]
On classic they actually run away if combat is close to them.
