### ISSUE TITLE
🐝 [Bug] Fungal Spore Respawn Timer (Forgotten Pools)

### ISSUE THREAD

**Issue by wolffsi** [vmangos/core#1647]
## 🐝 Bug report - Quest
The Fungal Spore Mushrooms at Forgotten Pools have a super long respawn timer. When i got there there was none, and 15 Minutes Later only one had respawn

### Expected behavior
Dont know the accurate respawn timer but this seems way to long.

**Comment by NickTyrer** [comment]
They have a respawn time of 3 min. These objects are now pooled so they don't always respawn in the same areas.
