### ISSUE TITLE
MURKDEEP!🐝 [Bug] He spawned invisible! 

### ISSUE THREAD

**Issue by legino123** [vmangos/core#1654]
### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by NickTyrer** [comment]
Already closed here https://github.com/vmangos/core/commit/17faec4d65ae22e66b6ff0ea6d57c368d15dca0d
