### ISSUE TITLE
🐝 [Bug] Handful of Oats not respawning in the Westfall.

### ISSUE THREAD

**Issue by arathurin** [vmangos/core#1655]
### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by NickTyrer** [comment]
THey have a respawn time of 5 mins, also they are pooled and wont always respawn in the same spot.
