### ISSUE TITLE
SOUTHSHORE!! Guards are not killing assasins! They are running rampage🐛 [Bug]

### ISSUE THREAD

**Issue by legino123** [vmangos/core#1657]
### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by NickTyrer** [comment]
Resolved here https://github.com/vmangos/core/pull/1630
