### ISSUE TITLE
🐛 [Bug] Krolg [3897] should not drop any loot

### ISSUE THREAD

**Issue by FlagFlayer** [vmangos/core#1658]
### Expected behavior

Krolg should not be dropping any loot (see https://www.wowhead.com/classic/npc=3897/krolg#comments )

### Steps to reproduce

1. .summon 3897
2. kill it
3. it drops loot (it shouldn't drop any loot)
4. ...
5. Profit

### Version & Environment

Client Version: 
 - 1.12.1.5875

Commit Hash:  Whichever one EverlookPTR is using right now

OS Client: Win 10 64x
OS Server: Linux 64x

### Crashlog

- None

**Comment by NickTyrer** [comment]
Closed here https://github.com/vmangos/core/pull/1630
