### ISSUE TITLE
Atiesh turns off Moonkin Aura🐞 [Bug]

### ISSUE THREAD

**Issue by Moonkinlovetea** [vmangos/core#1659]
## 🐞 Bug report - Spell

Hello world!

Power of the Guardian (Ariesh buff) turns off Moonkin Aura . And vice versa. If i take Moonkin Form , Atiesh baff turns off.  
I tested only mage Atiesh ( because only one man have this staff in my server )  and I don't know if the other staffs have a problem.

### Expected behavior

I think buffs should add up because it is logical . 
proof : 

i seen https://www.wowhead.com/classic/spell=28142/power-of-the-guardian#see-also-other  Spell ID 28142
          https://www.wowhead.com/classic/spell=24907/moonkin-aura#triggered-by Spell ID 24907

and not seen mutually exclusive labels
(However, I am a simple player. Maybe I'm not looking there. Do not pinch the wings.. )
p.s. the question is still. does the staff buff take off between them? 

### Steps to reproduce

1. Take Moonkin and take item  22589 . 22630. 22631,22632
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffff8000\124Hitem:22589::::::::60:::::\124h[Atiesh, Greatstaff of the Guardian]\124h\124r"); 
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffff8000\124Hitem:22630::::::::60:::::\124h[Atiesh, Greatstaff of the Guardian]\124h\124r");
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffff8000\124Hitem:22631::::::::60:::::\124h[Atiesh, Greatstaff of the Guardian]\124h\124r");
/script DEFAULT_CHAT_FRAME:AddMessage("\124cffff8000\124Hitem:22632::::::::60:::::\124h[Atiesh, Greatstaff of the Guardian]\124h\124r");
2. Testing 
3. Testing all staff at the same time.
4. ...
5. Profit

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  

OS Client: Win X
OS Server: dont know

### Crashlog

- None

**Comment by Wall-core** [comment]
Can you confirm that they stack on classic? Assuming so, add this to SpellMgr::IsNoStackDueToSpell under spellfamily_generic:

```
// Atiesh aura stacking with Moonkin Aura
if (spellInfo_1->SpellIconID == 46 && spellInfo_2->SpellIconID == 46)
	return false;
```

**Comment by Moonkinlovetea** [comment]
Thx  for help.

I don't have access to official servers. I can search for PTR servers and try on them.

**Comment by Daribon** [comment]
I tried finding a video from classic but absolutely nobody runs a balance druid in their naxx raid. The very few videos I could find that had balance druids and had mages with ateish, did not have the balance druid and the mage in the same group.

**Comment by Moonkinlovetea** [comment]
I bow low to you. You have done a great job /knell

**Comment by Moonkinlovetea** [comment]
![bufs](https://user-images.githubusercontent.com/116117982/198376935-d70390c4-5254-43ca-b6cf-0ec667b48298.jpg)

I found Atiesh of Kronos. And buff have stack.

**Comment by ratkosrb** [comment]
Private servers do not matter at all. The goal of this project is not to emulate Kronos.

**Comment by Moonkinlovetea** [comment]
I am sorry . I dont know your war of Kronos. I dont play now to kronos. But it one server,when i have char and can founde Ariesh. 

I not have want emulate. I not have char of OFF server. 
But more people say when buff can stack.

**Comment by Gamemechanicwow** [comment]
Moonkin Aura stacking with 2x mage ateish
https://classic.warcraftlogs.com/reports/fvL93YgwPNWRChTj#fight=6&type=auras&source=33

Same druid - posted on the druid discord the same day:
![image](https://user-images.githubusercontent.com/2223066/198399370-af6f620b-7299-47e4-bc42-6b080eadafc0.png)

There are several other examples - with screenshots - on the discord: https://discord.gg/classicdruid

**Comment by Moonkinlovetea** [comment]
Greater thx. You save me.
