### ISSUE TITLE
🐛 [Bug] Honor on targets in combat with NPC's is not being calculated properly

### ISSUE THREAD

**Issue by Roflkopterr** [vmangos/core#1660]
🐛 Bug report

Mobs that deal damage to players while in combat is taking away from honor being given to the player/s that kill.

If you kill someone who took damage while in combat with a mob or even if they JUST killed the mob and you wait a few seconds for him to eat back to full. It will calculate the honor as though another player did the damage that was dealt by the mobs/npc's and it will split that honor into the calculation.

So if someone has 100 hp and a mob does 75 dmg to them, combat ends, they eat to full or I kill them right away, in BOTH instances I only get 25% of the actual honor that should be gained.

### Expected behavior
Honor should be calculated from player damage only and NPC/Mob damage should not be a factor or variable in the equation whatsoever.
No version of vanilla ever had this functionality and I am not sure this is supposed to occur even on retail.

https://www.youtube.com/watch?v=xESQ8K7ercE 2:30 full honor for half hp targets.

### Steps to reproduce

1. Kill a target player that has taken damage from a mob. You will not get the proper amount of honor, and the percentage of honor lost will be proportional to the amount of damage taken by the mob.
2.
3.
4. ...
5. Profit

### Version & Environment

<!--
  Client Version:
  - 1.12.1.5875

This has occurred on every Vmango server I have played on to date. Hyjal, Darrowshire, and now the PTR for everook.

**Comment by ratkosrb** [comment]
I believe this to be blizzlike for vanilla. In old ganking videos i found, the person recording seems to consistently get less honor if he kills players at low health who are fighting a mob.

https://www.youtube.com/watch?v=j9rtw35jAE4
https://www.youtube.com/watch?v=IuO_BXGolBQ
https://www.youtube.com/watch?v=TRxpO1qeP1I
