### ISSUE TITLE
🐛 [Bug] Broken/damaged items always sell for full price

### ISSUE THREAD

**Issue by Daribon** [vmangos/core#1664]
## 🐛 Bug report

Damaged or broken items sell for full price at vendor, even if the game tells you that it will sell for less.

When you hover of mouse on any item with 0% durability at vendor on vmangos:
![WoW_YNNCzs1nQR](https://user-images.githubusercontent.com/6137576/197627231-c21447d9-d725-4d0b-b895-44cfda744ceb.png)

Actual price it sold for at vendor on vmangos:
![WoW_SBSlsDMIkq](https://user-images.githubusercontent.com/6137576/197627300-44917896-e842-418a-93f3-68da82983cca.png)

When hovering mouse over item with around 50% durability:
![WoW_hInjG8yVnG](https://user-images.githubusercontent.com/6137576/197627383-e28553dd-90e8-4748-854d-d1c027062ff1.png)

Actual price it sold for at vendor:
![WoW_MjjS2S5u05](https://user-images.githubusercontent.com/6137576/197627412-9515e643-f3d5-48e3-92e8-e43d09a9e748.png)

### Expected behavior

Vendors should take durability into account when you sell item to any NPC.
It should sell for same price as mouse over.

From classic:
![nomacs_FgUGwfSeDU](https://user-images.githubusercontent.com/6137576/197633623-2c2a257f-fc8b-46c7-bfcf-a22bdd6ca2d2.png)
![nomacs_VbnJu3JEMY](https://user-images.githubusercontent.com/6137576/197633653-75155948-a926-4360-af60-89d2282ee06a.png)
After selling on classic:
![WowClassicT_nsQm06KpDP](https://user-images.githubusercontent.com/6137576/197633732-decabea2-15a7-4b6c-a8ba-b772dded05b5.png)

After item repaired:
![WowClassicT_X1uey02dfQ](https://user-images.githubusercontent.com/6137576/197634750-90abac98-e009-40b1-b170-d900f2896c7f.png)

When sold to vendor:
![WowClassicT_YPNMzlAvym](https://user-images.githubusercontent.com/6137576/197634765-0b8b4dc4-06b5-4dad-8612-00655c29ea04.png)

### Steps to reproduce

1. Add any item with durability
2. .die
3. Take Resurrection Sickness
4. .die
5. Take Resurrection Sickness
6. .die 
7. Take Resurrection Sickness
8. Walk to any vendor
9. Sell item for full price no matter durability.

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  https://github.com/vmangos/core/commit/b06ed1f094710cb57d789bf4c51ebb47229ad450

OS Client: Microsoft Windows 11 Pro N 10.0.22000 Build 22000
OS Server: Microsoft Windows 11 Pro N 10.0.22000 Build 22000

### Crashlog

- None

**Comment by NickTyrer** [comment]
Closed in https://github.com/vmangos/core/commit/74b99554a8bc32c3b628b5eda54a703556b34b2a
