### ISSUE TITLE
🐝 [Bug] Druid 'Trial of the Lake' does not shake screen (like earthquake)

### ISSUE THREAD

**Issue by hgarner17** [vmangos/core#1667]
## 🐝 Bug report - Quest

Trial of the Sea lion quest should shake and rumble the screen when you form the pendant. or use the shrine. 
![druid trial of the sealion 01 scene does not shake](https://user-images.githubusercontent.com/35550935/197685867-98368001-cb7e-4f15-a409-95493865413b.png)

### Expected behavior

Unfortunately i don't do video. but in both Classic and in SoM upon completion of 2 pendant halves being joined in the shrine of remulos the ground rumbles (sound effect) and the screen physically shakes. (very cool) then the dryad jumps around dancing /cheer effect.  It's asthetic but still is part of original Vanilla wow.
### Steps to reproduce

1. 
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by NickTyrer** [comment]
I have checked a few videos from classic and I can't see any of this happening. Are you sure you have the correct quest?

**Comment by NickTyrer** [comment]
https://youtu.be/zou_GKVoxCc?t=132. Cant find any evidence for this.

**Comment by FlagFlayer** [comment]
@NickTyrer That is the wrong part of the quest chain. The video is of part 2 where you gather the Pendant of the Sea Lion. The first part involves a bauble retrieved from Lake Elune'ara, and as I recall, there should be a shake when the bauble is used at the Shrine of Remulos.

**Comment by FlagFlayer** [comment]
TBC Example: https://youtu.be/miOpxVA3L-0?t=274

Though I'm certain this was already implemented in Vanilla, it's weird that the effect doesn't show up in https://youtu.be/zou_GKVoxCc?t=40 . Could be that the graphical effect was disabled in settings.

**Comment by NickTyrer** [comment]
Now I know the correct quest I can see that the screen does shake https://youtu.be/m_vMcqsXE0k?t=86. Just needs sniffing to find the spell ID. The dancing and cheering is already implemented. Please Provide accurate details in future.

**Comment by FlagFlayer** [comment]
I believe "Trial of the Lake" in the title is a very accurate detail, but I agree it could've been presented better in the body of the issue.

**Comment by NickTyrer** [comment]
OK, all of this works correctly in vmangos from what I can see, its just the camera shake is less visible in the 1.12 client https://youtu.be/1H7qp5wYOhU

**Comment by FlagFlayer** [comment]
@NickTyrer No, it's not correct. In the video the shake starts DURING the cast. Here there is a small shake after the cast. This is not the same behaviour.

**Comment by FlagFlayer** [comment]
Please reopen this, it is not resolved.

**Comment by NickTyrer** [comment]
Please open a new issue as a bug with the spell.
