### ISSUE TITLE
🐛 [Bug] NPC Alchemy supplies vendor does not have a few health/mana pots in limited supply to sell

### ISSUE THREAD

**Issue by hgarner17** [vmangos/core#1668]
## 🐛 Bug report

Ulthir NPC in Darnassus; alchemy supplies vendor does not sell lesser mana potion. In both Classic and SoM this vendor had a limited supply 1-3 health potions and 1-3 mana potions for sale.  Not sure on the recharge timer. but just like engineering vendors have some bronze tubes. so too alchemy suppliers had a few low level potions for sale.
### Expected behavior

![potions and such 01](https://user-images.githubusercontent.com/35550935/197686882-048f61b1-8828-4042-b534-12673197c110.png)
for comparison.. other mobs have items that maybe shouldn't? 
![5 13](https://user-images.githubusercontent.com/35550935/197687867-583e131d-e4f4-4864-bba0-a8f71835de12.png)
^ this picture shows a lvl 20 area NPC just south along the road from Redridge. He's got potions for sale one level higher than the NPC should be selling in Darnassus
Just have anyone with an active retail subscription run there on any dead server and check.
### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by AnonXS** [comment]
Sorry but https://www.wowhead.com/tbc/npc=4226/ulthir

**Comment by FlagFlayer** [comment]
I believe the wowhead data is wrong on this, I've heard several people say that this vendor does in fact sell potions in Classic, though I have no means to confirm this.

**Comment by NickTyrer** [comment]
I tested on classic a while back. Does not sell pots.
