### ISSUE TITLE
Buff/Debuff Tooltips showing wrong numbers

### ISSUE THREAD

**Issue by Oroxzy** [vmangos/core#167]
**Current behavior**: 
I'm not sure if this is a Client bug or Server (i downloaded other clients and got this problem every time):

If you skilled some improved Skill (Battle Shout or a Totem etc.) and buff yourself or others, the Buff icon says for example +232 Attack Power.. but it should be 290 with 5/5 imp BS.
This only affects the tooltip numbers and not the additional stat it gives the character. The 290 AKP is correctly added to the characters stats. Same i got with all Class buffs and totems even Debuffs on NPCs.

**Steps to reproduce**:
Learn any imp. Skill and buff yourself and move the mouse to the buff...

**Client version**: 
1.12.1

**Comment by ratkosrb** [comment]
To my knowledge, all the texts related to spells are in Spell.dbc which is part of the client. So it is not possible for the server to change any tooltips, as the client does not request them from the server.

**Comment by Daribon** [comment]
This is an issue of the client itself, if I recall correctly Blizzard fixed this in later expansions.

**Comment by Oroxzy** [comment]
ok, I already guessed that -.-
