### ISSUE TITLE
🐛 [Bug] Random Enchantment "of Nature's Wrath" not implemented properly

### ISSUE THREAD

**Issue by FlagFlayer** [vmangos/core#1671]
### Expected behavior

For Example: Adventurer's Tunic should have a 6% chance of being enchanted by Nature's Wrath: https://www.wowhead.com/classic/item=10264/adventurers-tunic

### Steps to reproduce

1. .additem 10264
2. repeat x10000
3. You get every type of Adventurer's Tunic except "of Nature's Wrath"
4. ...
5. Profit

### Version & Environment

Client Version:  1.12.1.5875

OS Client: Win 64
OS Server: Win 64

### Crashlog

- None

**Comment by FlagFlayer** [comment]
This is probably a general Random Enchantments issue, since I've also been able to reproduce it with [15442], [10151], [15435]...

**Comment by NickTyrer** [comment]
Tested and is now working.

**Comment by Gamemechanicwow** [comment]
For reference. The mentioned items uses random_property 493 and 828 - both groups have a total chance above 100%.

The issue was resolved here: https://github.com/vmangos/core/pull/2826
