### ISSUE TITLE
🐛 [Bug] Amplify curse does not interact with Curse of Exhaustion as it should

### ISSUE THREAD

**Issue by Preesoo** [vmangos/core#1677]
Greetings, just notice that when I use Amplify curse with curse of exhaustion I can use it twice times  instead 1 time
![image](https://user-images.githubusercontent.com/109251304/198900834-a6f71f4b-e7c5-4c42-bac4-44ef990525dc.png)

**Comment by NickTyrer** [comment]
Duplicate
