### ISSUE TITLE
🐛 [Bug]Error prompt during compilation

### ISSUE THREAD

**Issue by Tangko** [vmangos/core#1690]
## 🐛 Bug report
When you select "CLIENT_BUILD_1_6_1" when using CMake build, the build is successful. Later, when compiling MANGOS with VS2017, compilation errors will occur! As shown in the figure. However, if I replace "1_6_1" with "1_12_1", the compilation will succeed. Another point is that I successfully compiled "1_6_1" last week, and successfully started the server to enter the game. I suspect that some changes have been made in the latest source code update, resulting in "1_6_1" compilation errors.
![1](https://user-images.githubusercontent.com/65060953/200839738-45183d29-87de-4c91-9cac-63525e9c0ca7.png)

![2](https://user-images.githubusercontent.com/65060953/200839820-c452035f-5764-4841-b438-cc98be10893c.png)

### Expected behavior
VS2017 successfully compiled "CLIENT_BUILD_1_6_1".

### Steps to reproduce
1.Build with CMake.
2.After building, change "CLIENT_BUILD_1_12_1" to "CLIENT_BUILD_1_6_1".
3.Compile "MANGOS" with VS2017.
4."ALL_BUILD" using build.
5. VS2017 prompts compilation failure and error.

### Version & Environment
Client Version:
1.6.1.4544

Commit Hash:

OS Client: - Win 11
OS Server: - Win 11
Client Version: 

### Crashlog
- None

**Comment by Daribon** [comment]
Can confirm, build failed when attempting to build with VS2019 as well.
![devenv_k9i5vz5fVJ](https://user-images.githubusercontent.com/6137576/201258999-4635f8aa-2b91-4d18-a5d4-8dc0f1fbdfcd.png)

**Comment by Tangko** [comment]
> 可以确认，尝试使用VS2019构建时构建失败。 ![devenv_k9i5vz5fVJ](https://user-images.githubusercontent.com/6137576/201258999-4635f8aa-2b91-4d18-a5d4-8dc0f1fbdfcd.png)

Yes, that's the error.

But I used VS2017 and successfully compiled 1 last week_ 6_ 1. You cannot compile now.

**Comment by Tangko** [comment]
> 可以确认，尝试使用VS2019构建时构建失败。 ![devenv_k9i5vz5fVJ](https://user-images.githubusercontent.com/6137576/201258999-4635f8aa-2b91-4d18-a5d4-8dc0f1fbdfcd.png)

Yes, that's the error.
However, I used VS2017 and successfully compiled "1_6_1" last week. Now I can't compile it.

**Comment by Daribon** [comment]
It is because of this commit:
https://github.com/vmangos/core/commit/c221c023674cd0ec01693baf38c67a36d9da2b69

**Comment by Tangko** [comment]
> 

Thank you for helping me find the cause of the problem！
