### ISSUE TITLE
Rich Thorium Node FAILING🐛 [Bug]

### ISSUE THREAD

**Issue by sudolink** [vmangos/core#1691]
### Description
SOME Rich Thorium Nodes (especially at the end of Dire Maul: East, are completely un-minable.  E.g. You complete DM:E, you come to the tunnel near the end and you see 3 veins.
You'll be able to mine two of them just fine, but the third will fail no matter how many times you attempt to mine it.
If there are three there is almost always one that won't work!
See GIF of it failing constantly ->
![thoriumFailsDMEAST](https://user-images.githubusercontent.com/46523097/200913293-5811ab11-e81a-4ef9-acef-e75a48004225.gif)

### Expected behavior
It shouldn't keep failing indefinitely at 300 mining.
One or a few fails are normal, but eventually you should be able to mine it at max mining.

### Steps to reproduce
**#mangosd.conf should have patch set to at least 1 for Dire Maul to be ingame ofc**
## ingame gm commands for quick reproduce
```
.character level 60
.learn all_recipes mining
.additem 2901
.tele diremaul
.gm on
enter DM:E
.modify speed 4
run straight down
talk to big tree boy
go to end boss
.gm off
target boss
.damage 30000 (dont kill outright to trigger tunnel opening)
.gm on
go into tunnel
try to mine the veins
```

## Version & Environment
  Client Version:
  - 1.12.1.5875

This happened to me today on EVERLOOK's PTR. Then I went and fired up an older VMANGOS repack to test it and the issue was the same. Imagine the amount of salty players getting to the end of DM:E and not being able to mine this.

**Comment by AnonXS** [comment]
I think this is some abuse prevention in place against teleport hackers.

**Comment by sudolink** [comment]
Update: definitely part of abuse prevention, because if I hack my way in there, and find a node that keeps failing, then go back out, attack the boss till the imps come out, then try mining it again, it then works.
Script doesn't affect all the veins though, which is probably how it should work to truly prevent abuse.
Closing issue.
