### ISSUE TITLE
hunter pets have full regen out of combat,  https://www.youtube.com/watch?v=mJaQJw1Wf2s&list=PL49Ga_-r7iKkxrbckm9CkUhWzxqrOnw-n&index=55🐛 [Bug]

### ISSUE THREAD

**Issue by grisker** [vmangos/core#1699]
### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by grisker** [comment]
on everlook hunter can pull their pet out of combat and they get full hp regen . you can see on the joana vid that pet had to be healed to keep going, and out of combat it was not healing to full.

**Comment by NickTyrer** [comment]
Closed in https://github.com/vmangos/core/commit/1258a93c349f93d62fd7d0887585a95f4302768e
