### ISSUE TITLE
There's a problem that's been bothering me

### ISSUE THREAD

**Issue by DarkmoonRabbit** [vmangos/core#17]
There's a problem that's been bothering me.
In the era of LH-Server, it exists!

Start mangosd.exe, enter the game! Sometimes the chat window will prompt: the server will restart after 10 minutes!

This operation happens by accident, not every time.
why~~? @ratkosrb

**Comment by mpfans** [comment]
restart automatically every Wednesday.Because Wednesday is the PVP settlement day.

**Comment by ghost** [comment]
https://github.com/vmangos/core/blob/development/src/game/HonorMgr.cpp#L528

If in doubt // it out ;)

**Comment by ratkosrb** [comment]
It's the weekly honor restart. You can just comment out the line Nolin mentioned if you want to prevent it.
