### ISSUE TITLE
‘increase reflection chance’ no effect.

### ISSUE THREAD

**Issue by chendh123** [vmangos/core#170]
talent skill  no effect.
11189:                                 // Frost Warding
28332:

11094:                                 // Improved Fire Ward
13043:

**Comment by Kittnz** [comment]
cmangos implemented it here: https://github.com/cmangos/mangos-tbc/blob/master/src/game/Spells/SpellMgr.cpp#L3208

**Comment by chendh123** [comment]
![image](https://user-images.githubusercontent.com/15760697/56544950-8615d680-65a8-11e9-9fd2-ae19a9233643.png)
A way of vmangos.  function :  Unit::CalculateSpellDamage.
