### ISSUE TITLE
🐛 [Bug] Salt Flats Scavenger [4154] and Salt Flats Vulture [4158] are missing almost all of their spawns

### ISSUE THREAD

**Issue by FlagFlayer** [vmangos/core#1703]
### Expected behavior

See https://github.com/azerothcore/azerothcore-wotlk/issues/4934 and https://github.com/chromiecraft/chromiecraft/issues/2364 for a better overview than I could write here.

### Steps to reproduce

1. Go to Shimmering Flats and see that there are no Vultures in places where they're supposed to be.
2. ...
3. Profit

### Version & Environment

Client Version: 1.12.1.5875

### Crashlog

- None

**Comment by NickTyrer** [comment]
Just to note, all of the creature spawns in this zone are hevily pooled as well.

**Comment by NickTyrer** [comment]
Added Missing Spawns Here https://github.com/vmangos/core/pull/1630

**Comment by FlagFlayer** [comment]
@NickTyrer Note that there are a lot more spawns than just the 3 added by https://github.com/azerothcore/azerothcore-wotlk/pull/5322, which were pulled from cmangos. There's a reason that https://github.com/azerothcore/azerothcore-wotlk/issues/4934 is still an open issue.

**Comment by NickTyrer** [comment]
I added more that 3 spawn positions (3 from sniffs and 3 from cmangos). We may not be missing the spawn positions, we may just be missing pooling data. Either way the area needs a lot more work.

**Comment by NickTyrer** [comment]
I have added all of the spawns now, this can be closed when merged.
