### ISSUE TITLE
🔧 [Support]I want to know Spell.cpp and SpellEffects.cpp help！

### ISSUE THREAD

**Issue by ss958** [vmangos/core#1706]
### Steps to reproduce
1. SpellDefines.h   add  SPELL_EFFECT_RANDOM_PROPERTY_ITEM = 134 and TOTAL_SPELL_EFFECTS = 135
2. SpellEffects.cpp  add   &Spell::EffectRandomPropertyItemPerm  ；   void Spell::EffectRandomPropertyItemPerm(SpellEffectIndex effIdx)
3. spell.h  add  void EffectRandomPropertyItemPerm(SpellEffectIndex effIdx);
4.  spell.cpp  CheckItems()  add case SPELL_EFFECT_RANDOM_PROPERTY_ITEM:
    CheckItems()   case SPELL_EFFECT_RANDOM_PROPERTY_ITEM:   OK。
    void Spell::EffectRandomPropertyItemPerm(SpellEffectIndex effIdx)    NO OK。。 help me。。

**Comment by ghost** [comment]
??
