### ISSUE TITLE
🦂 [Bug] Witch Doctor Zum ' rah does not drop loot

### ISSUE THREAD

**Issue by hgarner17** [vmangos/core#1708]
### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version:  1.2 (progressive Everlook)

Commit Hash:  
![witch Doctor zum'rah does not drop loot 01](https://user-images.githubusercontent.com/35550935/203709417-78073ee3-e5fd-47a0-ab92-f4be0a12075b.png)

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by Godmatik** [comment]
Not a bug - he doesn't have a loot table in that patch
