### ISSUE TITLE
🦂 [Bug] Sgt Bly drops no loot in ZF temple fight

### ISSUE THREAD

**Issue by hgarner17** [vmangos/core#1709]
### Expected behavior

Escorted the caged group down the temple steps (no wipes) we killed all enemies and nobody died. the goblin opened the door to the final boss just as he should have but the NPC did not drop ANY loot. sgt bly should drop some blue items or at the least a green drop. No items were lootable.
### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version:  version 1.2 (everlook progressive server)
![Sgt Bly and crew dropped no loot](https://user-images.githubusercontent.com/35550935/203710024-b7d45237-0206-40f0-aac0-eab96d74eba5.png)

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by Godmatik** [comment]
Not a bug - he only drops the quest item, has no other loot table
