### ISSUE TITLE
🔧 [Support] How to setup to support client 1.12.3 6141

### ISSUE THREAD

**Issue by SoongXiaoTong** [vmangos/core#1712]
hello team,

May I get your help to know how to setup the database to support client 1.12.3 6141 to login? now I will get the error "Unverifiable game version" even iif 6141 is include at "realmbilds".

mysql> select * from realmlist;
+----+--------------+-----------+--------------+-----------------+------+------+------------+----------+----------------------+------------+---------------+---------------+------+-----------------+
| id | name         | address   | localAddress | localSubnetMask | port | icon | realmflags | timezone | allowedSecurityLevel | population | gamebuild_min | gamebuild_max | flag | realmbuilds     |
+----+--------------+-----------+--------------+-----------------+------+------+------------+----------+----------------------+------------+---------------+---------------+------+-----------------+
|  1 | Lightbringer | 127.0.0.1 | 127.0.0.1    | 255.255.255.0   | 8085 |    1 |         64 |        1 |                    0 |          0 |             0 |             0 |    2 | 5875 6005 6141  |
+----+--------------+-----------+--------------+-----------------+------+------+------------+----------+----------------------+------------+---------------+---------------+------+-----------------+
1 row in set

thank you in advance!

**Comment by ratkosrb** [comment]
It should already be working. Try disabling StrictVersionCheck in realmd.conf.

**Comment by SoongXiaoTong** [comment]
yes,, it works! thank you so much ratkosrb.
btw, may I know what is the benefit of enable StrictVersionCheck? Disable it will get alert from Warden.

**Comment by ratkosrb** [comment]
It blocks clients that are not in the approved list.
