### ISSUE TITLE
🐛 [Bug] Monstrous Crawlers [1088] are missing many spawns

### ISSUE THREAD

**Issue by FlagFlayer** [vmangos/core#1715]
## 🐛 Bug report

Another heavily pooled mob that has a tiny, incorrect number of spawns.

### Expected behavior

https://www.wowhead.com/classic/npc=1088/monstrous-crawler

**Comment by Godmatik** [comment]
Confirmed on this, it makes the horde quest https://www.wowhead.com/classic/quest=1430/fresh-meat quite a bit more time consuming

**Comment by FlagFlayer** [comment]
@NickTyrer might be the kind of issue that interests you

**Comment by NickTyrer** [comment]
Closed here https://github.com/vmangos/core/pull/1630
