### ISSUE TITLE
🐛 [Bug] Wild Leather quests recipes are not soulbound, and sell incorrectly

### ISSUE THREAD

**Issue by FlagFlayer** [vmangos/core#1718]
## 🐛 Bug report

When completing one of the Wild Leather quests, the recipe you recieve is not Soulbound. It instead says "Binds when picked up" and it can be traded.
![WoWScrnShot_120222_234623](https://user-images.githubusercontent.com/76889547/205396116-4ff0101f-f837-42eb-86db-bb618b6c84a1.jpg)

### Expected behavior

The recipes should be properly soulbound.

**Comment by FlagFlayer** [comment]
Apprently they also sell for 10s even though they should have no sell price

**Comment by Gamemechanicwow** [comment]
Did you delete your cache? These items are not BOP until 1.8.

**Comment by FlagFlayer** [comment]
Oh this is a patch change huh. My bad on that one.
