### ISSUE TITLE
🐞 [Bug] Cannot have stack amount be higher than procCharges

### ISSUE THREAD

**Issue by jaywalker15262** [vmangos/core#1724]
## 🐞 Bug report - Spell

Any spell with lets say a stack amount of 6 and procCharges of 3 will not work because when you go towards amounts of stacks above what your procCharge is set to, it starts to consume double the amount of stacks per proc. You will always end up with the amount of effective stacks that your procCharge is set to.

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by ratkosrb** [comment]
What spell does that affect?
