### ISSUE TITLE
🐝 [Bug] The Attack! objective finished before RP event.

### ISSUE THREAD

**Issue by Daribon** [vmangos/core#1728]
## 🐝 Bug report - Quest

This quest has several incorrect things:
- Currently the quest objective "Overhear Lescovar and Marzon's Conversation" finished before Lescovar and Marzon has even begun speaking.
- Both Lescovar and Marzon currently have their faction set as enemy once they finished speaking.
- Tyrion's Spybot currently instantly despawns after speaking to Lescovar.
- Both Lescovar and Marzon are yelling when pulled.
- Priestess Tyriona is permanently spawned, only despawned when the quest event starts.

### Expected behavior

- The quest objective "Overhear Lescovar and Marzon's Conversation" should only complete after Lescovar and Marzon has finished speaking.
- Lescovar and Marzo should have neutral faction (but attackable) once RP event finished, they should not be set as enemies.
- Tyrion's Spybot should not instantly despawns after speaking to Lescovar.
- Both Lescovar and Marzon should not be yelling when pulled, it should be done in say.
- Priestess Tyriona (NPC 7779) should not permanently spawned. The NPC should only exist for the quest.

Video from classic:
https://www.youtube.com/watch?v=BK7ynRCp4KM

This quest event has been sniffed by me in SoM or other people in classic.

### Steps to reproduce

1. .go creature Tyrion
2. .quest add 2746
3. .quest complete 2746
4. Turn in the quest
5. Accept the quest The Attack!
6. Watch the quest objective become completed almost instantly.

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  https://github.com/vmangos/core/commit/4d7e82f4c14cb4360f21122ede6d3d1c0b7613cb

OS Client: Microsoft Windows 11 Pro N 10.0.22621.900
OS Server: Microsoft Windows 11 Pro N 10.0.22621.900

### Crashlog

- None

**Comment by ratkosrb** [comment]
That quest was rescripted some time ago so the issue should be fixed now.
