### ISSUE TITLE
Random NPC fixes

### ISSUE THREAD

**Issue by Daribon** [vmangos/core#174]
This just fixes some of the stuff that has annoyed me in the past.
The random creatures in Winterspring and Dun Morogh are just from bad parsing from sniffs which have picked up players pets.

The fix to field of strife is to remove the god awful custom NPC fight in the middle, which never existed in vanilla or any expansion.

```SQL
-- Delete Winterspring Owl in Silithus
DELETE FROM `creature` WHERE `guid` = '2230118';

-- Make Field of Strife Blizzlike
DELETE FROM `creature` WHERE `id` = '20110';
DELETE FROM `creature` WHERE `id` = '20111';

-- Make triggers invisible
-- Trigger Vipore
UPDATE `creature_template` SET `flags_extra`='128' WHERE  `entry`=14031 AND `patch`=0;
-- Trigger Ichman
UPDATE `creature_template` SET `flags_extra`='128' WHERE  `entry`=14029 AND `patch`=0;
-- Trigger Mulverick
UPDATE `creature_template` SET `flags_extra`='128' WHERE  `entry`=14027 AND `patch`=0;
-- Trigger Jeztor
UPDATE `creature_template` SET `flags_extra`='128' WHERE  `entry`=14028 AND `patch`=0;
-- Trigger Slidore
UPDATE `creature_template` SET `flags_extra`='128' WHERE  `entry`=14030 AND `patch`=0;
-- Trigger Guse
UPDATE `creature_template` SET `flags_extra`='128' WHERE  `entry`=14026AND `patch`=0;

-- Delete Cornish Rex Cat from dwarf start
DELETE FROM `creature` WHERE `guid` = '1528';
```

**Comment by Gamemechanicwow** [comment]
The winterspring owl in silithus is blizzlike.

I'll do some digging on the Field of strife, because im not so sure about that. First time i tried AV on a private server and saw the field of strife npcs, my immediate reaction was that i remember them standing closer to eachother. /shrug

**Comment by Hatredshit** [comment]
Daribon there are Elite Trolls that spawn near Snowfall Graveyard and walk to the Field of Strife right before Korrak spawns.

**Comment by Daribon** [comment]
> Daribon there are Elite Trolls that spawn near Snowfall Graveyard and walk to the Field of Strife right before Korrak spawns.

Haven't seen this myself on vmangos, but if its a thing, its probably done by script.

> The winterspring owl in silithus is blizzlike.
> 
> I'll do some digging on the Field of strife, because im not so sure about that. First time i tried AV on a private server and saw the field of strife npcs, my immediate reaction was that i remember them standing closer to eachother. /shrug

Why would a Winterspring Owl be on a road in silithus? You got any proof of it being there from retail?

Here are some pics to clearify that Field of Strife never had a NPC battle:
Patch 1.5
![alteractal27](https://user-images.githubusercontent.com/6137576/56817652-4409c080-6846-11e9-8dd4-4e4c32845068.jpg)
![alteractal28](https://user-images.githubusercontent.com/6137576/56817715-64d21600-6846-11e9-8c13-63db670e277c.jpg)
![alteractal42](https://user-images.githubusercontent.com/6137576/56817775-7fa48a80-6846-11e9-8969-17e86ec9458c.jpg)
Proof of it being 1.5:
![alteractal35](https://user-images.githubusercontent.com/6137576/56818544-1cb3f300-6848-11e9-94b4-09efffea8a0c.jpg)
Patch 1.5:
![571 - ZWV9L](https://user-images.githubusercontent.com/6137576/56818277-97c8d980-6847-11e9-94fe-7f6ea2b914bd.png)
Proof of it being 1.5:
![447 - T5sr8](https://user-images.githubusercontent.com/6137576/56818359-c5ae1e00-6847-11e9-8619-b7c825566f96.png)

Pre Patch 1.10.0:
![03z](https://user-images.githubusercontent.com/6137576/56818191-65b77780-6847-11e9-997c-3c3c380c44c5.jpg)
From blizzards own site:
![aerial_h](https://user-images.githubusercontent.com/6137576/56818415-dd85a200-6847-11e9-8cd7-fadfe7eeebf6.jpg)

Video from patch 1.5.0, showing rogue PvP in the Field of Strife:
https://youtu.be/YDUx5fR6TtM?t=169

Video from 1.5.0, entire video takes place in Field of Strife:
https://www.youtube.com/watch?v=azXig9-fqcQ
Video from 1.5.0:
https://www.youtube.com/watch?v=_WvScFAbwTI
Video dated: 27 06 2005
https://youtu.be/KLfK6v4ATw0?t=154
Part 2 of the video dated: 27 06 2005
https://www.youtube.com/watch?v=-7RBF8cYZRs

In all of those screenshots, in all of those videos, not a single NPC other than ivus, lokholar and korrak can be seen in Field of Strife. It should be very clear by now, that there never was any big NPC battle of alliance/horde units in Field of Strife. Nostalrius team based the custom battle in Field of Strife on one comment iirc from allakhazam which is a joke by itself. 0 research made by them.
