### ISSUE TITLE
🐛 [Bug] Fly and Chat Bug

### ISSUE THREAD

**Issue by Bagiraa** [vmangos/core#1742]
## 🐛 Bug report

When you use fly to go to location A to B, the General And LocalDefense chat didnt change location when you fly throught other locations (and you are still able to speak and see message from the location A chat untill you reach location B).

Chat flying from Stormwind to Booty Bay in VMangos :
![vmangos](https://user-images.githubusercontent.com/39051162/208974158-d1601309-a2f4-429b-95c4-67d3c2e54419.png)

Chat flying from Stormwind to Booty Bay in official Wow Classic era:
![retailera](https://user-images.githubusercontent.com/39051162/208970321-b6723c87-fd5c-47f5-a780-0d870e1b80c4.png)

Another thing is on official i wrote "log" because, instead of vmangos, official wow classic didnt notice you what channel you joined when you log in the game, but vmangos show it.

### Version & Environment

Client Version: 

1.12

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by ratkosrb** [comment]
In vanilla it is the client that switches channels upon going to new zone. The server cannot make the client join a different channel if the join is not initiated by the client. So I don't think we can do anything about this.

**Comment by Bagiraa** [comment]
I guess you are right watched some old wow video (https://www.youtube.com/watch?v=KO1iKRoKDyI) and it looks like to do the same thing. I close it
