### ISSUE TITLE
💬 [Discussion]No dmp file output

### ISSUE THREAD

**Issue by yangyitzzg** [vmangos/core#1755]
mangosd.exe Crash.but No .dmp file output.Where can I open it?

**Comment by jameyboor** [comment]
Make sure your ulimit is set properly, such as:

`ulimit -c unlimited`

**Comment by yangyitzzg** [comment]
I'm sorry to add my system information:windows server 2016
When I use Azerothcore, the dmp file will be generated automatically. I'm still a novice in this field. thank you

**Comment by yangyitzzg** [comment]
Detour seems to have some problems. I tried to make some judgments, but it still went down. At present, no dmp file has been generated and can only be viewed online.

Code [version:](https://github.com/vmangos/core/commit/d0e3936241be22fe9c1b734bf83c1f40c2c79975)
screenshot:
![1](https://user-images.githubusercontent.com/6389276/211036821-0e88e4fe-785f-4540-8e0c-4ed5d943cd98.png)
![2](https://user-images.githubusercontent.com/6389276/211036827-e44ad636-6c62-4220-ac52-fc5349478749.png)
![3](https://user-images.githubusercontent.com/6389276/211036833-7d30a420-3cf4-4411-8d4d-8ed425d484a1.png)
![4](https://user-images.githubusercontent.com/6389276/211036837-33541471-574b-4b89-9d53-cf02b9a7c2a9.png)
![11](https://user-images.githubusercontent.com/6389276/211036842-cdbe677e-2f5e-4a00-bdef-268fd3934de3.png)
![22](https://user-images.githubusercontent.com/6389276/211036848-0876c6ee-2dfc-4d06-a855-f2458ae2a430.png)

**Comment by ratkosrb** [comment]
You are running old version of core, because in your pictures the comments in GetWalkRandomPosition are in French, but they were translated to English afterwards. Try updating and see if the crash still happens.

**Comment by yangyitzzg** [comment]
Thanks, I'll try
