### ISSUE TITLE
🐛 [Bug] Salma Saldean weird drop table

### ISSUE THREAD

**Issue by jaywalker15262** [vmangos/core#1757]
Salma Saldean entry 235: https://www.wowhead.com/classic/npc=235/salma-saldean

Is suppost to have no drop table but instead has a really odd drop table, even dropping some high level smithing plans...

**Comment by jaywalker15262** [comment]
Maybe this drop table was meant for another npc and was accidentally put into the wrong entry?

**Comment by NickTyrer** [comment]
Closed here #1970
