### ISSUE TITLE
🐞 [Bug] AMPLIFY CURSE+ CURSE OF EXHAUSTION

### ISSUE THREAD

**Issue by kurtosmurtos** [vmangos/core#1758]
## 🐞 Bug report - Spell
 The Amplify curse buff/effect, https://classicdb.ch/?spell=18288 is not working properly with the warlock affliction talent spell, curse of exhaustion, https://classicdb.ch/?spell=18223. This seems to be the case on all server using the same core including the Retro wow PTR.

**Current behavior**: Once the warlock activates https://classicdb.ch/?spell=18288 and uses https://classicdb.ch/?spell=18223 which is improved with the the talent ,https://classicdb.ch/?spell=18313, the AMPLIFY CURSE BUFF still remains on the player, which also allows the warlock to cast Amplified curse of exhaustion for 30 seconds, for the duration of the Amplify curse effect. Which means that a warlock can cast a 50% slow for 30 seconds instead of only one 50 % slow with the Amplify buff active. Please also note that the other curses listed in the description of the spell https://classicdb.ch/?spell=18288  AMPLIFY CURSE, work correctly.  This has been happening for over a year on all server using the Vmangos core and now including the Retro wow PTR . This is not the case on the live Retro WoW server or Kronos

Screenshots from the Retro WoW PTR. The duration of the https://classicdb.ch/?spell=18288 spell should make the matter clear.

![Screenshot (187)](https://user-images.githubusercontent.com/112797709/209944987-a4f7dbf4-ec3d-4950-b401-7f59e1745760.png)
![Screenshot (188)](https://user-images.githubusercontent.com/112797709/209945009-431925a8-aad9-4a84-b88b-9fbb3346349d.png)
![Screenshot (189)](https://user-images.githubusercontent.com/112797709/209945056-9b9e2389-78ee-429d-a688-87972ce2e4a0.png)
![Screenshot (190)](https://user-images.githubusercontent.com/112797709/209945066-af6c259d-da08-4252-ae8c-9aae6e962e05.png)
![Screenshot (191)](https://user-images.githubusercontent.com/112797709/209945082-bed9eef0-5396-42d8-8e95-d85f1cac368b.png)
![Screenshot (194)](https://user-images.githubusercontent.com/112797709/209945095-f65f0298-8b4f-4b94-a269-9ffea81c7d1d.png)
![Screenshot (195)](https://user-images.githubusercontent.com/112797709/209945121-a53d2cfe-70c7-4bf6-ae9b-3c33af4dd2d2.png)
![Screenshot (196)](https://user-images.githubusercontent.com/112797709/209945142-3287cac4-1744-4474-9db6-f01becb5d73e.png)
 

### Expected behavior
 When the https://classicdb.ch/?spell=18288, Amplify curse effect is activated, after casting the next (first) curse of exhaustion, https://classicdb.ch/?spell=18223, the buff from the Amplify curse spell should be consumed or in other words it should be gone. Allowing the warlock to cast only ONE 50% slow.  Read the tooltip of the spell, https://classicdb.ch/?spell=18288

Screenshots of how it should work, from the Retro WoW Live server and Kronos.
 Retro:
![Screenshot (279)](https://user-images.githubusercontent.com/112797709/211211741-d3194ef6-3195-4232-be59-bc7cf18b97a4.png)
![Screenshot (280)](https://user-images.githubusercontent.com/112797709/211211770-b4f3e5db-09f1-4161-9cb6-97c070d95ec2.png)
 Kronos:
![Screenshot (281)](https://user-images.githubusercontent.com/112797709/211211792-c7018eab-7f26-40bb-94fa-f2898a08b12f.png)
![Screenshot (282)](https://user-images.githubusercontent.com/112797709/211211800-f413e4a0-a893-4434-864f-b3dc884864c3.png)

### Steps to reproduce

1. Spec into Affliction so that the warlock has Amplify curse,https://classicdb.ch/?spell=18288, Curse of exhaustion, https://classicdb.ch/?spell=18223, and 4/4 Improved curse of exhaustion, https://classicdb.ch/?spell=18313
2. Activate Amplify curse and spam it on multiple or on one target.
3. Notice that the  https://classicdb.ch/?spell=18288, Amplify curse buff/effect is not remove/consumed after casting curse of exhaustion
4. ...
5. Profit

### Version & Environment

Client Version: 1.12

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by Daribon** [comment]
Duplicate: https://github.com/vmangos/core/issues/1307
