### ISSUE TITLE
🐛 [Bug]Crash

### ISSUE THREAD

**Issue by yangyitzzg** [vmangos/core#1759]
## 🐛 Bug report
Code Version:[20230107](https://github.com/vmangos/core/commit/6c2cda47e1ccaadfe1eb3ef6269fcde039a21e0a)

### Expected behavior
The general way is that when some map creatures are attracted to some specific locations, mangosd will be crash.

### Version & Environment
Client Version:1.12.3.6141
Server: Windows Server 2012

### Crashlog:
[Crashs.zip](https://github.com/vmangos/core/files/10370287/Crashs.zip)

**Comment by ratkosrb** [comment]
It is the same crash you posted in https://github.com/vmangos/core/issues/1755

**Comment by yangyitzzg** [comment]
Yes, but I have updated the following files to the latest:

contrib/mmap/src/MapBuilder.cpp
contrib/vmap_extractor/vmapextract/vmapexport.cpp
contrib/vmap_extractor/vmapextract/wmo.cpp
dep/recastnavigation/Detour/Source/DetourNavMeshQuery.cpp
src/game/Anticheat/MovementAnticheat/MovementAnticheat.cpp
src/game/Anticheat/MovementAnticheat/MovementAnticheat.h
src/game/Handlers/MovementHandler.cpp
src/game/Maps/Map.cpp
src/game/Maps/Map.h
src/game/Maps/PathFinder.cpp
src/game/Maps/PathFinder.h
src/game/Maps/ZoneScript.cpp
src/game/Maps/ZoneScript.h
src/game/Movement/MotionMaster.cpp
src/game/Movement/MovementPacketSender.cpp
src/game/Movement/TargetedMovementGenerator.cpp
src/game/Movement/WaypointMovementGenerator.cpp

**Comment by coolzoom** [comment]
you are on your own if the source is different than the official branch.
people are not able to repeat the issue if the sources are different.

**Comment by yangyitzzg** [comment]
> you are on your own if the source is different than the official branch. people are not able to repeat the issue if the sources are different.

The code comes from the official branch and is currently in the learning state. Some minor modifications have been made, such as the code for generating dmp files. Other codes are consistent with the official ones. No changes have been made to the map code.

**Comment by Gamemechanicwow** [comment]
The big issue here is that there is not enough information to reproduce it - or anyone else reporting similar crashes.

If it still happens with a clean vmangos build - I would advise you to extract and rebuild the maps.

**Comment by yangyitzzg** [comment]
> The big issue here is that there is not enough information to reproduce it - or anyone else reporting similar crashes.
> 
> If it still happens with a clean vmangos build - I would advise you to extract and rebuild the maps.

Yes, I'm also very confused. I have extracted and replaced the MMAPS again, and still have the same problem. At present, I am trying to repair and test.
