### ISSUE TITLE
Rogue Poison cast animation?

### ISSUE THREAD

**Issue by Oroxzy** [vmangos/core#176]
**Current behavior**: 
Rogues always doing a "cast animation" if a Poison effect is applied to the Target wich looks really stupid.. in 8-12 year old youtube videos they don't do this..  sometimes you cast only poison and not even the weapons sounds are played wich looks not real -.-

Vid from warcraftmovies 2006-10-06 reuploaded to youtube 2011:
https://www.youtube.com/watch?v=1C7Uvt_0oYs

You can clearly see Rogue is never casting a "Poison effect" just the Weapon is glowing Green...

**Comment by ratkosrb** [comment]
There is a comment in the code claiming the opposite.
https://github.com/vmangos/core/blob/development/src/game/Spells/Spell.cpp#L4459

**Comment by Gamemechanicwow** [comment]
https://github.com/LightsHope/issues/issues/1072

**Comment by Oroxzy** [comment]
so it just looks weird if a rogue with sheathed weapons casts poison and than instant has his weapons back in hands but ok.. if it was real its ok .. ^^

**Comment by ratkosrb** [comment]
I finally discovered the cause of this issue. The spell cast packets for the chance on hit effects are supposed to be sent before the melee swing packet.
https://github.com/vmangos/core/commit/f093d9bde54f9d67b9c2714551960ed2f9c8b009

**Comment by GoonBoiBarry** [comment]
I believe this same issue affected windfury weapon, but it may have been fixed by now and I could be misremembering
