### ISSUE TITLE
🐛 [Bug] The drop rate of items from Big-mouth Clams

### ISSUE THREAD

**Issue by jaywalker15262** [vmangos/core#1760]
The drop rates are horribly off. The drop rates are suppost to be more deifinite and rounded like 1 in 25 not some weird numbers like 1 in 1/76 or some shit. And on top of that Small Lustrous Pearl has a lower drop rate than Golden Pearl.... the lowest ilevel pearl has a lower drop chance than the super rare golden pearl which is suppost to be something like 1 in 200(0.5%) but in the DB its 1.7% which is also a really weird number and I highly doubt this is correct. A quick look on https://www.wowhead.com/classic/item=7973/big-mouth-clam#contains shows the same. And it also shows that some of the pearls and even the meat can drop in quantities higher than 1. I do not know how correct this is though or how frequent that is.

**Comment by schell244** [comment]
I've reworked the drop rate of Big-mouth Clam including the pearls according to wowhead here: https://github.com/vmangos/core/pull/1682
