### ISSUE TITLE
🦂 [Bug]ERROR: [DungeonReset] Instance 0 [map 249]: ScheduleReset 1 for unknown instance.

### ISSUE THREAD

**Issue by hoopzz** [vmangos/core#1769]
<!--
## 🦂 Bug report - Dungeon

![bug](https://user-images.githubusercontent.com/122730483/212542024-c9d9ea50-f23d-4228-bcb6-add2b742bfdb.png)

### Version & Environment
Client Version: 5875
OS Client: windows 11
OS Server: win 2012

### Crashlog
- None

**Comment by yangyitzzg** [comment]
At present, I have also encountered this error. I haven't seen where it was caused

**Comment by hoopzz** [comment]
![QQ截图20230118114742](https://user-images.githubusercontent.com/122730483/213078903-3ec33146-6f75-4416-92ae-d2d246daa15d.png)
![QQ截图20230118114801](https://user-images.githubusercontent.com/122730483/213078930-87fbcae4-35e9-4f40-9255-7ff92b6c56e3.png)

**Comment by ghost** [comment]
duplicate
