### ISSUE TITLE
🐛 [Bug] Holy Spring Water never drops from The Holy Spring

### ISSUE THREAD

**Issue by Daribon** [vmangos/core#1777]
## 🐛 Bug report

Holy Spring Water currently never drops from The Holy Spring.
A loot window shows up, but it is always empty.
![WoW_dPak0xJiXj](https://user-images.githubusercontent.com/6137576/214152894-26821196-5720-45aa-bd4d-5a0350b66c90.png)

### Expected behavior

You should always be able to loot Holy Spring Water from The Holy Spring.
This was both the case in vanilla and classic. An unlimited amount can be looted, but you can only carry one at a time. 

It should not require the quest Sweet Amber (quest 48) or the quest Mok'thardin's Enchantment, part 4.
### Steps to reproduce

1. .go object The Holy Spring
2. Loot it

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  https://github.com/vmangos/core/commit/87ec00fe61966ae33666dbb682372d9e67ad00f5

OS Client: Microsoft Windows 11 Pro N 10.0.22621.900
OS Server: Microsoft Windows 11 Pro N 10.0.22621.900

### Crashlog

- None

**Comment by NickTyrer** [comment]
Closed here https://github.com/vmangos/core/pull/1970
