### ISSUE TITLE
[Crash/Auras] server crash due to pet aura

### ISSUE THREAD

**Issue by coolzoom** [vmangos/core#179]
**Current behavior**: 
server crash continuously due to pet aura,  i recall you've repaired several crashes due to different pet aura issue, i spent a hard time to find what was going wrong but no lucky,  i tried to clean up the pet_aura table and issue seems gone.
i check the history and find no similar crash log like below so sumbit here so you can take a look. but there're two repair history for your quick review, it looks similar to case b.

a: fix crash during load pet aura
https://github.com/vmangos/core/commit/03183cbcbbee1fe4e1633e209cf381e6530cb36c
b: Fix two possible crashes on creature death.
   case: https://github.com/vmangos/core/issues/153
   fix : 
 https://github.com/vmangos/core/commit/864ccc50554b8333a019ae616a9bb1cd22b27c45

current crash dump for you review
2019-05-02 16:56:56 [Crash/Auras] Deleting aura holder 3584 in use (Pet (Petnumber: 43228 Guid: 119))
2019-05-02 16:56:56 ./mangosd(_ZN3Map21AddObjectToRemoveListEP11WorldObject+0xe2) [0x818a92]
./mangosd(_ZN11WorldObject21AddObjectToRemoveListEv+0x24) [0x8c2e94]
./mangosd(_ZN3Pet8UnsummonE11PetSaveModeP4Unit+0x14e) [0x8e325e]
./mangosd(_ZN6Player13SetDeathStateE10DeathState+0xea) [0x9260fa]
./mangosd(_ZN4Unit4KillEPS_PK10SpellEntryb+0x73f) [0x96e58f]
./mangosd(_ZN4Unit10DealDamageEPS_jPK11CleanDamage16DamageEffectType15SpellSchoolMaskPK10SpellEntrybP5Spell+0x6b1) [0x96f781]
./mangosd(_ZN4Unit15DealSpellDamageEP19SpellNonMeleeDamageb+0x10e) [0x9704ce]
./mangosd(_ZN5Spell19DoAllEffectOnTargetEPNS_10TargetInfoE+0xa4c) [0x9b5d2c]
./mangosd(_ZN5Spell16handle_immediateEv+0x29f) [0x9c518f]
./mangosd(_ZN5Spell4castEb+0x5b0) [0x9c5a10]
./mangosd(_ZN5Spell7prepareEP4Auraj+0x686) [0x9c7ac6]
./mangosd(_ZN4Unit9CastSpellEPS_PK10SpellEntrybP4ItemP4Aura10ObjectGuidS3_S3_+0x227) [0x959aa7]
./mangosd(_ZN4Aura12TriggerSpellEv+0x404) [0x9df404]
./mangosd(_ZN4Aura12PeriodicTickEPK10SpellEntry8AuraTypej+0xad) [0x9e02bd]
./mangosd(_ZN15SpellAuraHolder6UpdateEj+0xb9) [0x9dac09]
./mangosd(_ZN4Unit13_UpdateSpellsEj+0x20f) [0x95575f]
./mangosd(_ZN4Unit6UpdateEjj+0x49a) [0x972dba]
./mangosd(_ZN8Creature6UpdateEjj+0xb7) [0x8a3fa7]
./mangosd(_ZN3Map23UpdateCellsAroundObjectEjjPK11WorldObject+0x343) [0x82c153]
./mangosd(_ZN3Map11UpdateCellsEj+0xb8) [0x82d588]
./mangosd(_ZN3Map6UpdateEj+0xfc) [0x825f6c]
./mangosd(_ZN21ContinentAsyncUpdater3runEv+0x1a) [0x83813a]
./mangosd(_ZN9ACE_Based6Thread10ThreadTaskEPv+0x25) [0xd05d15]
/usr/local/lib/libACE.so.6.5.0(_ZN21ACE_OS_Thread_Adapter6invokeEv+0xa6) [0x7f693a0140f6]
/lib64/libpthread.so.0(+0x7dd5) [0x7f6938e04dd5]
/lib64/libc.so.6(clone+0x6d) [0x7f6937e91ead]

**Expected behavior**: 

**Steps to reproduce**:

1. unknown behavior. not sure what can repeat this issue
2. 
3. 

**Client version**: 
1.12.1
**Commit hash**: 
3d8e606b3dbee7953bdedf5c09b0bb5be5679c59
**Operating system**: 
Centos 7

**Comment by ratkosrb** [comment]
Are you able to reproduce the crash reliably? I think I know how to fix it, but it would be nice if you can confirm that it works.

By looking at the crash log, what is happening is a pet that despawns when the owner dies has an aura that periodically triggers another spell that damages nearby allies. When the aura triggers and kills the pet's owner, the pet gets unsummoned and all auras on it are deleted. But when the stack unwinds, it goes back to the update of the original Aura, which has already been deleted. This happens because the triggered spell is executed instantly. The crash can be avoided by postponing the cast until the next update.

**Comment by coolzoom** [comment]
> Are you able to reproduce the crash reliably? I think I know how to fix it, but it would be nice if you can confirm that it works.
> 
> By looking at the crash log, what is happening is a pet that despawns when the owner dies has an aura that periodically triggers another spell that damages nearby allies. When the aura triggers and kills the pet's owner, the pet gets unsummoned and all auras on it are deleted. But when the stack unwinds, it goes back to the update of the original Aura, which has already been deleted. This happens because the triggered spell is executed instantly. The crash can be avoided by postponing the cast until the next update.

Hi Bro, Thanks for the reply, unfortuantly i m not able to repeat this issue reliably, i have the char db and i can see pet 43228 has aura 3584 which is "Volatile Infection", when i try to login use that char, the aura got erased automatically. 

when the issue happen my friend was in western plaguelands killing mobs, he and his pet got the aura by mobs. i tried to do same thing, even add aura to myself(using gm command with gm/god off) tring to kill my char and pet, but noting happened.
so looks like the issue is hard to be repeat but it did happen several times, maybe i havent find out the point to crash, i will keep try.
maybe can apply a temp fix and i can monitor for a long run?

**Comment by coolzoom** [comment]
@ratkosrb Nice and great update
