### ISSUE TITLE
🐛 [Bug] There were extra details in the console `REGEN_FLAG_POWER and low current mana percent (0%)`.

### ISSUE THREAD

**Issue by gajet5** [vmangos/core#1792]
## 🐛 Bug report

After this update, additional lines appeared in the console.
https://github.com/vmangos/core/commit/d32f0d4a6d3dec983dbadb6566c27dd282ab7c05

### Expected behavior

The server is loaded without additional lines in the log file.

### Steps to reproduce

1. Updated the server.
2. Started the server.
5. Profit

### Version & Environment

Client Version: 
1.12.1.5875

Commit Hash:  

OS Client: Win 11
OS Server: Ubuntu

### Crashlog

Loading Creature Data...
Table `creature` have creature (GUID: 4031 Entry: 12378) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 2614 Entry: 1565) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 2611 Entry: 1565) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 2597 Entry: 1565) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 17349 Entry: 2271) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 17340 Entry: 2271) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 16756 Entry: 2240) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 16084 Entry: 2244) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 10695 Entry: 1009) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 16071 Entry: 2244) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 16052 Entry: 2244) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 17763 Entry: 1767) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 9321 Entry: 1174) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 9318 Entry: 1174) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 28749 Entry: 4715) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 28746 Entry: 4715) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 27781 Entry: 4670) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 27300 Entry: 4654) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 27021 Entry: 4634) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 27019 Entry: 4634) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 27015 Entry: 4634) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 27014 Entry: 4634) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 27012 Entry: 4634) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 23556 Entry: 5616) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 23551 Entry: 5616) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 23505 Entry: 5616) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 7733 Entry: 4844) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 7730 Entry: 4844) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 30855 Entry: 4366) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 23260 Entry: 5485) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 23230 Entry: 5481) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 1136 Entry: 672) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 21499 Entry: 4150) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 21492 Entry: 4150) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 7221 Entry: 4844) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 7218 Entry: 4844) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 7217 Entry: 4844) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 20391 Entry: 3267) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 785 Entry: 1653) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 783 Entry: 1565) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 782 Entry: 1653) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 53104 Entry: 10381) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 53103 Entry: 10381) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 52183 Entry: 10382) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 52156 Entry: 10381) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 5920 Entry: 5860) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 5869 Entry: 5860) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 5826 Entry: 5860) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 5496 Entry: 7040) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 12333 Entry: 3113) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 33721 Entry: 5280) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 7347 Entry: 3113) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 6449 Entry: 3113) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 38086 Entry: 5259) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 34584 Entry: 5259) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 3326 Entry: 7049) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 18021 Entry: 1767) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 87288 Entry: 4435) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 87293 Entry: 4436) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 87296 Entry: 4435) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 40129 Entry: 4286) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 10057 Entry: 422) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 10194 Entry: 441) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 11669 Entry: 426) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 89540 Entry: 594) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 48134 Entry: 1783) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 48137 Entry: 1783) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 48369 Entry: 1783) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 91950 Entry: 8523) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 92230 Entry: 8523) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 92281 Entry: 8524) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 92659 Entry: 8528) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 92660 Entry: 8528) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 92667 Entry: 8528) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 92677 Entry: 8528) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 92683 Entry: 8528) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 92776 Entry: 8528) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 40637 Entry: 7112) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 40681 Entry: 7153) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 40813 Entry: 7153) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 48083 Entry: 2008) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 40253 Entry: 9817) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 300422 Entry: 9097) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 300423 Entry: 9045) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 300426 Entry: 9045) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 300433 Entry: 9045) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 300437 Entry: 9097) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 300438 Entry: 9045) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 300452 Entry: 9097) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 300451 Entry: 9097) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 8029 Entry: 4844) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 8031 Entry: 4844) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 8030 Entry: 4844) with REGEN_FLAG_POWER and low current mana percent (0%).
Table `creature` have creature (GUID: 7978 Entry: 4844) with REGEN_FLAG_POWER and low current mana percent (0%).

**Comment by runningman98** [comment]
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=4031 AND `id`=12378; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=2614 AND `id`=1565; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=2611 AND `id`=1565; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=2597 AND `id`=1565; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=17349 AND `id`=2271; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=17340 AND `id`=2271; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=16756 AND `id`=2240; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=16084 AND `id`=2244; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=10695 AND `id`=1009; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=16071 AND `id`=2244; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=16052 AND `id`=2244; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=17763 AND `id`=1767; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=9321 AND `id`=1174; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=9318 AND `id`=1174; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=28749 AND `id`=4715; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=28746 AND `id`=4715; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=27781 AND `id`=4670; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=27300 AND `id`=4654; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=27021 AND `id`=4634; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=27019 AND `id`=4634; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=27015 AND `id`=4634; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=27014 AND `id`=4634; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=27012 AND `id`=4634; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=23556 AND `id`=5616; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=23551 AND `id`=5616; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=23505 AND `id`=5616; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=7733 AND `id`=4844; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=7730 AND `id`=4844; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=30855 AND `id`=4366; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=23260 AND `id`=5485; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=23230 AND `id`=5481; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=1136 AND `id`=672; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=21499 AND `id`=4150; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=21492 AND `id`=4150; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=7221 AND `id`=4844; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=7218 AND `id`=4844; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=7217 AND `id`=4844; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=20391 AND `id`=3267; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=785 AND `id`=1653; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=783 AND `id`=1565; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=782 AND `id`=1653; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=53104 AND `id`=10381; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=53103 AND `id`=10381; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=52183 AND `id`=10382; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=52156 AND `id`=10381; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=5920 AND `id`=5860; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=5869 AND `id`=5860; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=5826 AND `id`=5860; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=5496 AND `id`=7040; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=12333 AND `id`=3113; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=33721 AND `id`=5280; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=7347 AND `id`=3113; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=6449 AND `id`=3113; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=38086 AND `id`=5259; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=34584 AND `id`=5259; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=3326 AND `id`=7049; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=18021 AND `id`=1767; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=87288 AND `id`=4435; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=87293 AND `id`=4436; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=87296 AND `id`=4435; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=40129 AND `id`=4286; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=10057 AND `id`=422; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=10194 AND `id`=441; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=11669 AND `id`=426; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=89540 AND `id`=594; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=48134 AND `id`=1783; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=48137 AND `id`=1783; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=48369 AND `id`=1783; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=91950 AND `id`=8523; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=92230 AND `id`=8523; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=92281 AND `id`=8524; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=92659 AND `id`=8528; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=92660 AND `id`=8528; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=92667 AND `id`=8528; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=92677 AND `id`=8528; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=92683 AND `id`=8528; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=92776 AND `id`=8528; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=40637 AND `id`=7112; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=40681 AND `id`=7153; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=40813 AND `id`=7153; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=48083 AND `id`=2008; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=40253 AND `id`=9817; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=300422 AND `id`=9097; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=300423 AND `id`=9045; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=300426 AND `id`=9045; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=300433 AND `id`=9045; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=300437 AND `id`=9097; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=300438 AND `id`=9045; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=300452 AND `id`=9097; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=300451 AND `id`=9097; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=8029 AND `id`=4844; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=8031 AND `id`=4844; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=8030 AND `id`=4844; 
UPDATE `creature` SET `mana_percent`=100 WHERE `guid`=7978 AND `id`=4844;

**Comment by runningman98** [comment]
Use them to update the World database to fix console log messages.

**Comment by gajet5** [comment]
Thank you very much, I really appreciate your help.

**Comment by gajet5** [comment]
**New**

2023-03-15 07:46:23 >> Loaded 7 pet create spells from table and 332 from DBC
2023-03-15 07:46:23 Loading Creature Data...
2023-03-15 07:46:23 Table `creature` have creature (GUID: 5011 Entry: 205) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 2607 Entry: 1565) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 17006 Entry: 2242) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 9752 Entry: 1034) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 9610 Entry: 1034) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 9325 Entry: 1174) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 27016 Entry: 4634) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 27013 Entry: 4634) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 27008 Entry: 4632) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 27004 Entry: 4632) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 23521 Entry: 5616) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 23519 Entry: 5616) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 30825 Entry: 4360) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 20390 Entry: 3267) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 20384 Entry: 3267) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 20379 Entry: 3267) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 5335 Entry: 7040) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 5334 Entry: 7040) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 5245 Entry: 7040) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 33719 Entry: 5277) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 33641 Entry: 5259) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 39771 Entry: 5259) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 8921 Entry: 426) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 10413 Entry: 441) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 16226 Entry: 548) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 16405 Entry: 430) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 18436 Entry: 436) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 92476 Entry: 8528) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 92522 Entry: 8525) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 39423 Entry: 7105) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 40796 Entry: 7105) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 43153 Entry: 12178) with REGEN_FLAG_POWER and low current mana percent (0%).
2023-03-15 07:46:23 Table `creature` have creature (GUID: 73507 Entry: 4360) with REGEN_FLAG_POWER and low current mana percent (0%).

**Comment by gajet5** [comment]
UPDATE creature SET mana_percent=100 WHERE guid=5011 AND id=205;
UPDATE creature SET mana_percent=100 WHERE guid=2607 AND id=1565;
UPDATE creature SET mana_percent=100 WHERE guid=17006 AND id=2242;
UPDATE creature SET mana_percent=100 WHERE guid=9752 AND id=1034;
UPDATE creature SET mana_percent=100 WHERE guid=9610 AND id=1034;
UPDATE creature SET mana_percent=100 WHERE guid=9325 AND id=1174;
UPDATE creature SET mana_percent=100 WHERE guid=27016 AND id=4634;
UPDATE creature SET mana_percent=100 WHERE guid=27013 AND id=4634;
UPDATE creature SET mana_percent=100 WHERE guid=27008 AND id=4632;
UPDATE creature SET mana_percent=100 WHERE guid=27004 AND id=4632;
UPDATE creature SET mana_percent=100 WHERE guid=23521 AND id=5616;
UPDATE creature SET mana_percent=100 WHERE guid=23519 AND id=5616;
UPDATE creature SET mana_percent=100 WHERE guid=30825 AND id=4360;
UPDATE creature SET mana_percent=100 WHERE guid=20390 AND id=3267;
UPDATE creature SET mana_percent=100 WHERE guid=20384 AND id=3267;
UPDATE creature SET mana_percent=100 WHERE guid=20379 AND id=3267;
UPDATE creature SET mana_percent=100 WHERE guid=5335 AND id=7040;
UPDATE creature SET mana_percent=100 WHERE guid=5334 AND id=7040;
UPDATE creature SET mana_percent=100 WHERE guid=5245 AND id=7040;
UPDATE creature SET mana_percent=100 WHERE guid=33719 AND id=5277;
UPDATE creature SET mana_percent=100 WHERE guid=33641 AND id=5259;
UPDATE creature SET mana_percent=100 WHERE guid=39771 AND id=5259;
UPDATE creature SET mana_percent=100 WHERE guid=8921 AND id=426;
UPDATE creature SET mana_percent=100 WHERE guid=10413 AND id=441;
UPDATE creature SET mana_percent=100 WHERE guid=16226 AND id=548;
UPDATE creature SET mana_percent=100 WHERE guid=16405 AND id=430;
UPDATE creature SET mana_percent=100 WHERE guid=18436 AND id=436;
UPDATE creature SET mana_percent=100 WHERE guid=92476 AND id=8528;
UPDATE creature SET mana_percent=100 WHERE guid=92522 AND id=8525;
UPDATE creature SET mana_percent=100 WHERE guid=39423 AND id=7105;
UPDATE creature SET mana_percent=100 WHERE guid=40796 AND id=7105;
UPDATE creature SET mana_percent=100 WHERE guid=43153 AND id=12178;
UPDATE creature SET mana_percent=100 WHERE guid=73507 AND id=4360;

**Comment by gajet5** [comment]
I think this fixed the problem.: https://github.com/vmangos/core/commit/4309cc34f8d057a26fabee4686abbf94ffe094bd
