### ISSUE TITLE
🐛 [Bug]ERROR

### ISSUE THREAD

**Issue by xBarselonx** [vmangos/core#1798]
## 🐛 Bug report

I saw the error after quitting the game. Applic ation below the file.
[Server.log](https://github.com/vmangos/core/files/10609630/Server.log)

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 1.12.1

Commit Hash:  

OS Client: win10
OS Server: 

### Crashlog

- None

**Comment by ratkosrb** [comment]
There is nothing wrong in this log.
