### ISSUE TITLE
🐞 [Bug] Ice Barrier should benefit from frost spell power but currently does not

### ISSUE THREAD

**Issue by jaywalker15262** [vmangos/core#1799]
According to: https://wowpedia.fandom.com/wiki/Ice_Barrier

It should benefit from frost spell damage, added frost damage gear and saw that the amount absorbed was still the same on all ranks. Nowhere in spell_template or in the core does it show any sort of scaling.

**Comment by ratkosrb** [comment]
```
World of Warcraft Client Patch 2.3.0 (2007-11-13)
-  Ice Barrier now gains additional benefit from spell damage bonuses. 
```
the page you linked is not for vanilla, what you are asking is a tbc change
you should research things before opening issues

**Comment by jaywalker15262** [comment]
You should read things before you close reports. If you had spent at least 2 seconds to scroll down further down the patch notes and just seen: ”Patch changes
[Patch 1.11.0](https://wowpedia.fandom.com/wiki/Patch_1.11.0) (2006-06-19): Ice Barrier received an overhaul. The spell was changed to stack with  [[Power Word: Shield]](https://wowpedia.fandom.com/wiki/Power_Word:_Shield) (which previously overwrote it), had its cooldown reduced from 2 minutes to 30 seconds, `gained the benefit of frost spell damage`, and was prioritized to absorb damage before  [[Mana Shield]](https://wowpedia.fandom.com/wiki/Mana_Shield_(original)), thus saving mana when using both shields.
Test-inline.png [Patch 0.9](https://wowpedia.fandom.com/wiki/Patch_0.9) (2004-08-17): Training costs added to ranks.”

You’re right, it isn't for vanilla, it is for all wow versions. It shows changes all changes that Ice Barrier has gone through in every patch with official patch notes. And both blizzard forums and comments on wowhead from classic shows people saying it scaled with 10% of your frost SP just like frost ward. The tbc  change wasn't adding scaling, it was making the scaling even higher.

https://www.wowhead.com/classic/spell=13033/ice-barrier#comments
https://eu.forums.blizzard.com/en/wow/t/ice-barrier-and-pw-s/111254

**Comment by ratkosrb** [comment]
Neither the wowpedia page you linked, nor the offical patch notes included with the client say anything about spell power scaling for Ice Barrier. Where are you seeing that? And the fact that its mentioned in the 2.3.0 patch notes implies it was not a thing before that.

Edit: Ok i saw what you are quoting, you linked the wrong page. At the bottom of the Ice Barrier page it says that, but this is not the original quote from the patch notes, somebody added in that part in the middle of the sentence.

There is also no such mention in the last version of the page from 2006. We should look for a source from vanilla, every mention of this is made afterwards. It seems to me somebody conflated the 1.11 and 2.3 changes.
https://wowpedia.fandom.com/wiki/Ice_Barrier?oldid=313520

**Comment by FlagFlayer** [comment]
From: https://www.wowhead.com/classic/spell=13033/ice-barrier#comments:id=3152007
> By [Kanariya](https://www.wowhead.com/classic/user=Kanariya) (84,096 – 16·84·716) <Premium User> [on 2019/09/04](https://www.wowhead.com/classic/spell=13033/ice-barrier#comments:id=3152007) (Classic)		
> Spellpower co-efficient is 10% (ex. 250 spellpower = +25 absorb value).
> 
> This is the only Mage absorption spell that scales with spellpower. Fire Ward, Frost Ward, and Mana Barrier do not scale at all.

Also worth mentioning, from: https://www.wowhead.com/classic/spell=11426/ice-barrier#comments:id=2886889
> By belgianmage [on 2006/07/23](https://www.wowhead.com/classic/spell=11426/ice-barrier#comments:id=2886889) (Patch 1.11.2)		
> Subject: "nonono "at 60 it absorbs 835 dmg orsmthing , my mana shield absorbs more , in pvp it totaly sucks, 1 hit and its gone ... only good in 5 man instances, since they only hit 100-200 there

The correct value according to https://www.wowhead.com/classic/spell=13033/ice-barrier would be 826 damage at lv 60. Might be an indication of spellpower increasing this number.

Regardless, this needs testing in Classic, and until it is either confirmed or disproved it should remain an open issue.

**Comment by FlagFlayer** [comment]
It was already rumored to be correct by Patch 2.0, before the Patch 2.3 changes:

From: https://www.wowhead.com/classic/spell=13033/ice-barrier#comments:id=20033
> By [9766](https://www.wowhead.com/classic/user=9766) (5,472 – 2·15·45) [on 2007/01/10](https://www.wowhead.com/classic/spell=13033/ice-barrier#comments:id=20033) (Patch 2.0.3)		
> Ice Barrier uses +spell bonus? Fact or rumor?

Also: https://www.wowhead.com/spell=11426/ice-barrier#comments:id=155198
> By [86954](https://www.wowhead.com/user=86954) (229 – 2) [on 2007/09/19](https://www.wowhead.com/spell=11426/ice-barrier#comments:id=155198) (Patch 2.1.3)		
> It is also worthwhile to note that Ice Barrier will, in fact stack with Mana Shield. When stacked, Ice Barrier will absorb damage first, Mana Shield following. This means a mage can get potentially ~738 Damage Mitigation not counting +Frost equipment, just at level 40 when this spell is obtained.
> 
> In addition, 10% of all bonus frost spell damage will add to the amount Ice Barrier shields for. Therefore a lv40 with say, 100 frost spell damage will actually shield 448 dmg with Ice Barrier instead of 438.

There is plenty of evidence this would've been a 1.11 change. It could've been a 2.0 change as well, but I find it unlikely considering 1.11 is the one that specifically reworked this talent. @ratkosrb please reopen this issue, evidence of this change being completely unrelated to patch 2.3 is insurmountable.

**Comment by jaywalker15262** [comment]
Can we have this issue reopened? From evidence shown it is more likely that Ice Barrier scaled with +10% frost spelld damage post patch 1.10ish, than it not doing so. It makes since frost ward also scales with 10% spell damage. I think FlagFlayer has shown some pretty decent evidence that this is the case.

**Comment by Daribon** [comment]
iirc it had 10% coefficient in classic. Can't confirm that it actually had 10% in classic.
Can't confirm either from vanilla.
