### ISSUE TITLE
Question about Cmake build policy (OLD option)

### ISSUE THREAD

**Issue by attackpure100** [vmangos/core#18]
in Cmakelists file we have (https://github.com/vmangos/core/blob/development/CMakeLists.txt).
lines 23-27.

`# CMake policies (can not be handled elsewhere)
cmake_policy(SET CMP0026 OLD)
if(POLICY CMP0043)
  cmake_policy(SET CMP0043 OLD) # Disable 'Ignore COMPILE_DEFINITIONS_<Config> properties'
endif()` 

why is this using the OLD policy and can it work without ?(haven't tried tbh but wondering what is the purpose of using OLD)?

The reason i ask is because Cmake gives me warnings saying that this selecting this policy is to be deprecated in coming versions of Cmake (or something like that). Can we simply remove those lines? or are they there for a reason that still remains valid (stability etc.), ty

**Comment by ratkosrb** [comment]
Probably left over from _ye olde times_. I tried removing them and it seems to configure and build properly on Windows, with the exception of one line in Main.cpp:
https://github.com/vmangos/core/blob/development/src/mangosd/Main.cpp#L200

If everything is fine without those lines on Linux too, then we can remove them.

**Comment by attackpure100** [comment]
ok then .. my machine cant do virtualization and i dont have a linux machine but regarding the windows stuff i was always building the core with VS2017 and i noticed another item in the Cmakelists.txt file which was line 46:

`#add_definitions(-D_HAS_AUTO_PTR_ETC) # for VS2017 ACE support, won't do any harm to other compilers`
`#set(CMAKE_CXX_STANDARD 17)`
`#set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /std:c++17")`

i would say this might be a different issue altogether but since we are on the topic of removing an old/deprecated policy this might be something to note... i dont know what it actually does

in order to use VS2017 (15.7.5) and win10 SDK (10.0.16299.0) for Desktop C++. I needed to build ACE_wrappers_vs2017.sln as opposed to ACE_wrappers_vc14.sln before i could proceed

**Comment by attackpure100** [comment]
theres the error on the https://github.com/vmangos/core/blob/development/src/mangosd/Main.cpp#L200 That i get:


`12>c:\users\inspiron5559\desktop\vmangos\core\src\mangosd\main.cpp(200): error C2146: syntax error: missing ')' before identifier 'MANGOS_BUILD_OPTIONS'
12>c:\users\inspiron5559\desktop\vmangos\core\src\mangosd\main.cpp(200): error C2146: syntax error: missing ';' before identifier 'MANGOS_BUILD_OPTIONS'
12>c:\users\inspiron5559\desktop\vmangos\core\src\mangosd\main.cpp(200): error C2065: 'MANGOS_BUILD_OPTIONS': undeclared identifier
12>c:\users\inspiron5559\desktop\vmangos\core\src\mangosd\main.cpp(200): error C2143: syntax error: missing ';' before 'string'
12>c:\users\inspiron5559\desktop\vmangos\core\src\mangosd\main.cpp(200): error C2059: syntax error: ')'`

perhaps it can be modified only slightly to fix the issue as opposed to removing the full line? unless of course it is unnecessary in the first place because looks like output to logs or something

**Comment by ratkosrb** [comment]
Nolin already addressed the issue, I'm going to merge it now. And those other lines you mentioned are comments, so they don't do anything.
