### ISSUE TITLE
Item_template Database table [duration] set time, extra_flags = 1 , not available, 

### ISSUE THREAD

**Issue by 127y** [vmangos/core#180]
**Current behavior**: 
Item_template Database table [duration] set time, extra_flags = 1 , not available, 
Correct: extra_flags = 1 Player offline continues to calculate item time
**Expected behavior**: 

It used to be used before.
Extra_flags = 0 Player offline does not count item time
Extra_flags = 1 Player offline calculates item time 

**Steps to reproduce**:

1. 
2. 
3. 

**Client version**: 
1.12.1
**Commit hash**: 
9a08c99536516943cbd2730bc954a0a859886ca2
**Operating system**: 
win 2016

**Comment by ratkosrb** [comment]
It was removed because its not needed. There is a normal flag that does the same thing. Its literally exactly the same functionality.

ITEM_FLAG_REAL_DURATION = 0x00010000

Just do this:
```
UPDATE `item_template` SET `flags` = 0x00010000 WHERE `entry`=77757;
```

**Comment by 127y** [comment]
@ratkosrb thank you very much. The problem with your method has been resolved. Thank you

**Comment by 127y** [comment]
@ratkosrb The faction field in the creature_template table. Values can only be ordered by themselves. Other players can't point. consult

**Comment by ratkosrb** [comment]
I do not understand the question.
