### ISSUE TITLE
It is recommended to restore the item_template database script_name table

### ISSUE THREAD

**Issue by 127y** [vmangos/core#181]
It is suggested to add item_scripts.cpp to make homemade items.

Give an example:

//**************************************************************************************************
//Use of Goods to Achieve Full Alchemy Level
bool Item_item_Alchemy(Player* player, Item* item, const SpellCastTargets& pTargets) {
	if (((Item*)item)->GetEntry() != 77757) {
		return false;
	}
	if (player->GetItemCount(77757, false) == 0) {
		return false;
	}
	    player->learnSpell(11612, false);
		player->SetSkill(171, 300, 300);
		player->DestroyItemCount(77757, 1, true, false);
	return true;
}
//**************************************************************************************************

void AddSC_spell_scripts()
{
    Script *newscript;
//**************************************************************************************************
//Note: You need to fill in the [script_name] field of the corresponding item in your item list with [item_Alchemy]
	newscript = new Script;
	newscript->Name = "item_Alchemy";
	newscript->pItemUse = &Item_item_Alchemy;
	newscript->RegisterSelf();
//**************************************************************************************************
}

**Comment by ratkosrb** [comment]
It is not needed because you can do the same thing with a dummy spell. And it's Blizzlike to do it this way, Blizzard uses spells for all items.

Example how to use dummy spell:
https://github.com/vmangos/core/commit/9f619bd71c32b07671d0403645869e5203a79044

**Comment by 127y** [comment]
@ratkosrb Hello there. Can you provide the skill ID of the same effect you know about 18282? I need 15 such skill ID

**Comment by 127y** [comment]
@ratkosrb 
CMake 3.14.3 Version  The following error occurred. How can I fix CMakeLists.txt ?

```
CMake Warning (dev) at CMakeLists.txt:149 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable ACE_ROOT is set to:

    C:\ACE_wrappers

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.
```


```
 CMake Warning (dev) at CMakeLists.txt:163 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable TBB_ROOT is set to:

    C:\tbb2019_20190320oss

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by ratkosrb** [comment]
Those are not errors. You should be able to continue.
