### ISSUE TITLE
🚀 [Feature] Hardcore Challenge

### ISSUE THREAD

**Issue by gajet5** [vmangos/core#1811]
## 🚀 Feature
The ultimate goal of this challenge is to reach level 60 without ever dying. Once you’re level 60, you can participate in raiding and PvP without a risk of losing your character.

### Visualization
1. After creating a character, the chat command ".hc (enable | on)" is used. Оnly for newly created characters.
2. A debuff (touch of death) is imposed on the character until they receive LVL 60.
3. When such a character dies, there is no resurrection button. The window offers to exit to the lobby (if possible on the server side). If this is a modification of the client, then disconnect the character from the world to send to the lobby.
4. The character becomes neutral for pvp in the open world (if the status of the pvp world).
5. The character can interact only with the same characters.
6. The character has disabled access to the auction, mail, partybots.
7. When the character reaches LVL 60, the debuff disappears. All restrictions are removed. The character becomes ordinary.
8. The character receives the title of "Immortal" as a reward. There may be something else.

### Benefits, Purpose
Attracting new users to the project.
Competition against other emulators.
A trend that is gaining popularity.

### Links
https://classichc.net/

**Comment by ratkosrb** [comment]
This is completely outside the scope of this project. We will not be implementing such custom features.
