### ISSUE TITLE
🐛 [Bug][DungeonReset] Errors in the console when starting the server.

### ISSUE THREAD

**Issue by gajet5** [vmangos/core#1819]
## 🐛 Bug report
Group Ids remapped, next group id is 2
Scheduling normal instance reset...
ERROR: [DungeonReset] Instance 100 [map 189]: ScheduleReset 0 for unknown instance.
ERROR: [DungeonReset] Instance 101 [map 189]: ScheduleReset 0 for unknown instance.
ERROR: [DungeonReset] Instance 102 [map 189]: ScheduleReset 0 for unknown instance.
ERROR: [DungeonReset] Instance 103 [map 189]: ScheduleReset 0 for unknown instance.
ERROR: [DungeonReset] Instance 104 [map 189]: ScheduleReset 0 for unknown instance.
ERROR: [DungeonReset] Instance 105 [map 189]: ScheduleReset 0 for unknown instance.
ERROR: [DungeonReset] Instance 106 [map 229]: ScheduleReset 0 for unknown instance.
ERROR: [DungeonReset] Instance 107 [map 229]: ScheduleReset 0 for unknown instance.
ERROR: [DungeonReset] Instance 108 [map 189]: ScheduleReset 0 for unknown instance.
ERROR: [DungeonReset] Instance 109 [map 36]: ScheduleReset 0 for unknown instance.
ERROR: [DungeonReset] Instance 110 [map 36]: ScheduleReset 0 for unknown instance.
ERROR: [DungeonReset] Instance 0 [map 249]: ScheduleReset 1 for unknown instance.
ERROR: [DungeonReset] Instance 0 [map 309]: ScheduleReset 1 for unknown instance.
ERROR: [DungeonReset] Instance 0 [map 409]: ScheduleReset 1 for unknown instance.
ERROR: [DungeonReset] Instance 0 [map 469]: ScheduleReset 1 for unknown instance.
ERROR: [DungeonReset] Instance 0 [map 509]: ScheduleReset 1 for unknown instance.
ERROR: [DungeonReset] Instance 0 [map 531]: ScheduleReset 1 for unknown instance.
ERROR: [DungeonReset] Instance 0 [map 533]: ScheduleReset 1 for unknown instance.

### Expected behavior
There are no errors in the console.

### Steps to reproduce

1. Run server.
5. Profit

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  

OS Client: Win 11
OS Server: Ubuntu 22.04

### Crashlog

- None

**Comment by ghost** [comment]
duplicate
