### ISSUE TITLE
On Onyxia P2 Fireball

### ISSUE THREAD

**Issue by shwblm** [vmangos/core#182]
On Onyxia P2 Fireball P2 Fireball will give players a DBUFF and leave them in chaos. That's not right.

**Comment by ratkosrb** [comment]
Are you referring to this effect?

```
World of Warcraft Client Patch 1.3.0 (2005-03-22)
   * Onyxia's fireballs will no longer result in a confuse effect 
     (Engulfing Flames). The impact damage of these fireballs has been 
     slightly increased to compensate for the loss of the damage 
     over time.
```

This is intended because all raids are in their pre-nerf state. It was implemented this way on purpose to have the hardest version of the raid.
