### ISSUE TITLE
🐛 [Bug][Partybot] Save bot character progress

### ISSUE THREAD

**Issue by samuel-edmund-morgan** [vmangos/core#1822]
Are there any possibilities to save level and gear on characters spawned by command .partybot load <name_of_character> ?
I mean, I created two accounts and created two characters of 1 level, but when I play with these characters and leveling, giving them gear which dropped by mobs - after relogin these characters still 1 levels and with no gear I gave them.

**Comment by ratkosrb** [comment]
Change PlayerBot.AllowSaving to 1 in mangosd.conf.

https://github.com/vmangos/core/blob/development/src/mangosd/mangosd.conf.dist.in#L2876

**Comment by samuel-edmund-morgan** [comment]
> Change PlayerBot.AllowSaving to 1 in mangosd.conf.
> 
> https://github.com/vmangos/core/blob/development/src/mangosd/mangosd.conf.dist.in#L2876

Yeah, now it's working. By the way, are there any guide\wiki\documentation with full lists of commands for partybot\battlebot? I just found some  lists of commands on Chinese website with approximate list of .partybot and .char .

Do you have some documentation regarding this question?

**Comment by gajet5** [comment]
.partybot
https://github.com/vmangos/core/blob/development/src/game/Chat/Chat.cpp#L94
.char
https://github.com/vmangos/core/blob/development/src/game/Chat/Chat.cpp#L233

**Comment by samuel-edmund-morgan** [comment]
> .partybot https://github.com/vmangos/core/blob/development/src/game/Chat/Chat.cpp#L94 .char https://github.com/vmangos/core/blob/development/src/game/Chat/Chat.cpp#L233

it's not a documentation, you know.
