### ISSUE TITLE
🚀 [Feature] A common pool of bots for the battleground.

### ISSUE THREAD

**Issue by gajet5** [vmangos/core#1825]
## 🚀 Feature
1. The use pool for battlefields option is added to the server configuration.
2. If a player registers on the battlefield, bots are added to him. And the match begins.
3. If another player wants to join the same bg, one of the bots is unloaded, and a player is loaded in its place.
4. Checking for the presence of a player. If there are no players left on bg, the bots are unloaded.
5. Extensibility - only one bg with bots is allowed. If one bg is 10\10 players, then it is permissible to create a second one with bots. etc.

### Benefits, Purpose
Will allow you to make an expandable and exciting visit to BG.

**Comment by gajet5** [comment]
https://github.com/vmangos/core/commit/eedd248821e1d4949d4b9c36de66e1a92c9bdd68#diff-418ac50038d119e9b1af062e281f0b3821a082eed1c3ba4dc4f7d8b162df0763

Will the bot be automatically deleted if another player wants to join?

**Comment by ratkosrb** [comment]
Here is how it works at the moment. Every 10 seconds the bot manager will check all battleground queues. If there are players in queue, but amount is lower than required for bg to start, it will add enough bots on each side for bg to start. Bots are not removed and stay forever.

**Comment by gajet5** [comment]
> Bots are not removed and stay forever.

I need to test this point. There may be a situation in which there will be a large number of bots and they will create several BG and will fight with themselves.

![image](https://github.com/vmangos/core/assets/3825412/9cdf3eea-48c5-422e-ac60-a985abe7c38e)

I have already observed this on my server. But that was before adding this line to the code:

`m_lastBattleBotQueueUpdate = 0;`

in this commit https://github.com/vmangos/core/commit/017c2625e113954119336df6e707cfe4bf66029a

**Comment by gajet5** [comment]
Yes, as I thought, it doesn't work correctly.
https://github.com/vmangos/core/issues/2271

**Comment by gajet5** [comment]
I think this proposal has been fulfilled.
