### ISSUE TITLE
🔧 [Support]How to add custom item script in vmangos?

### ISSUE THREAD

**Issue by catontheway** [vmangos/core#1828]
How to add custom item script in vmangos?
I have written a piece of C++ code for a custom item script that implements certain functionalities. 
However, I noticed that there is no "scriptname" field in the item_template table. 
So, how can I associate the script with the item? Thank you.

**Comment by GrenderG** [comment]
Please don't use Issues to ask about custom stuff, use #off-topic channel on Discord. Regarding your question, this functionality is not required for a Blizzlike emulation so the core doesn't have support for it; you will need to implement that functionality yourself (add field to the database, load script, assign dummy spell to item and run the script on use).

**Comment by catontheway** [comment]
@GrenderG i'm sorry, i'll make sure to pay attention next time.
thank you for your response
however, i believe that whether it's a blizzlike or fun server, this feature should be open to people.
although the itemscript function has been removed now,
it can still be achieved through Spell::EffectDummy, but it just makes things more complicated.
