### ISSUE TITLE
🐛 [Bug] In Zul'Farrak, you can enter 10 people.

### ISSUE THREAD

**Issue by gajet5** [vmangos/core#1829]
## 🐛 Bug report
The limit on the database is the limit of the dungeon of 5 people. However, if you create a raid of 10, then you can go in.

### Expected behavior
You can enter only 5 people.

### Steps to reproduce

1. Create Raid
2. Add bots up to 10 people.
3. Enter the dungeon.
5. Profit

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  No

OS Client: Win11
OS Server: Ubuntu

### Crashlog

- None

**Comment by Gamemechanicwow** [comment]
Zul'Farrak has a 40 man limit until 1.3 where it's lowered to 10.

**Comment by ratkosrb** [comment]
This is not a bug. Most dungeons are 10 man in Vanilla.

**Comment by gajet5** [comment]
https://www.reddit.com/r/classicwow/comments/ct08c7/comment/exi4hus/?context=3&st=jzk35mor&sh=7021b0c4
I'm sorry, I found the information. Perhaps the new realities of the game confused me.
