### ISSUE TITLE
🐛 [Bug] Error loading warden modules.

### ISSUE THREAD

**Issue by gajet5** [vmangos/core#1831]
## 🐛 Bug report
Loading warden modules...
ERROR: Failed to load warden_modules/54B8EC6A00878BBD8A0757ED144053AF.bin - Key file warden_modules/54B8EC6A00878BBD8A0757ED144053AF.key is incorrect size!

### Expected behavior
There is no error.

### Steps to reproduce

1. Put the warden_modules folder next to the executable files.
2. Start the server.
5. Profit

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  No

OS Client: Win 11
OS Server: Ubuntu

### Crashlog

- None

**Comment by ratkosrb** [comment]
Github messes up the file in the repo when committing it somehow. Download this zip and extract it to replace the existing files.

[54B8EC6A00878BBD8A0757ED144053AF.zip](https://github.com/vmangos/core/files/10953365/54B8EC6A00878BBD8A0757ED144053AF.zip)

**Comment by gajet5** [comment]
Replaced, it fixed the error. Did I understand correctly that when compiling, I have to use the -DUSE_ANTICHEAT=1 key to connect the warden module?

**Comment by Vanheden** [comment]
> Replaced, it fixed the error. Did I understand correctly that when compiling, I have to use the -DUSE_ANTICHEAT=1 key to connect the warden module?

Yes.

**Comment by gajet5** [comment]
thx
