### ISSUE TITLE
🐛 [Bug]

### ISSUE THREAD

**Issue by xujibbs** [vmangos/core#1838]
Mangos_string should not be translated simply by google. 
part of Varies like below case cause a crash when command is running.
for example:
When using command .setskill 202 300 300, server will find the string 484 Skill %u (%s) for player %s set to %u and current maximum set to %u (without permanent (talent) bonuses). however, the translation of Chinese is 玩家%s的技能%u(%s) 设置为%u，当前最大值设置为%u(没有永久(天赋)奖励)。the sort order of %s and %u(%s) in translation is not consistant with default string which cause a crash.
when I reverse %s and %u(%s) in Chinese translation, above command runs well.

**Comment by ratkosrb** [comment]
This should already have been fixed by https://github.com/vmangos/core/commit/91a780d77adee5153cbcf6a464adf3c638d4c01c
