### ISSUE TITLE
[Vmap]winterspring vmap issue

### ISSUE THREAD

**Issue by coolzoom** [vmangos/core#184]
**Current behavior**: 
in winterspring, there're few places don't have vmap info, one of the point show as below:

.go 8086.536621 -5673.490723 127.653847 1

when use .gps, it will give you an info say "no vmap available for area info."
in console it will show below info
22:50:06 VMap file '/home/Server/data/vmaps/001.vmtree' is missing or point to wrong version vmap file, redo vmaps with latest vmap_assembler.exe program

i also tried to use v14 map and it looks the same.

this is not ordinary place, but some of the player would swim from darkshore or somewhere to here.

it happened sometime the server would crash right after use .st command, below log may or may not related to the vmap, but i also attach here for your review(again, not sure whether if the vmap was the reson ).
one sample log showing blow:
2019-05-07 20:07:12 Received SIGSEGV
2019-05-07 20:07:12 ./mangosd(_ZN5Spell11EffectStuckE16SpellEffectIndex+0x1a2) [0x9f56b2]
./mangosd(_ZN5Spell13HandleEffectsEP4UnitP4ItemP10GameObject16SpellEffectIndexf+0x234) [0x9ad964]
./mangosd(_ZN5Spell16DoSpellHitOnUnitEP4Unitj+0x9b2) [0x9ae722]
./mangosd(_ZN5Spell19DoAllEffectOnTargetEPNS_10TargetInfoE+0xb80) [0x9b6610]
./mangosd(_ZN5Spell16handle_immediateEv+0x29f) [0x9c593f]
./mangosd(_ZN5Spell4castEb+0x5b0) [0x9c61c0]
./mangosd(_ZN5Spell6updateEj+0x3e6) [0x9c6f26]
./mangosd(_ZN10SpellEvent7ExecuteEmj+0x28) [0x9c7688]
./mangosd(_ZN14EventProcessor6UpdateEj+0xbb) [0xd229db]
./mangosd(_ZN4Unit6UpdateEjj+0x48c) [0x97355c]
./mangosd(_ZN6Player6UpdateEjj+0x46) [0x93c506]
./mangosd(_ZN3Map13UpdatePlayersEv+0x115) [0x815c45]
./mangosd(_ZN3Map6UpdateEj+0xe5) [0x8264d5]
./mangosd(_ZN21ContinentAsyncUpdater3runEv+0x1a) [0x8386ba]
./mangosd(_ZN9ACE_Based6Thread10ThreadTaskEPv+0x25) [0xd067a5]
/usr/local/lib/libACE.so.6.5.0(_ZN21ACE_OS_Thread_Adapter6invokeEv+0xa6) [0x7fbecafc10f6]
/lib64/libpthread.so.0(+0x7dd5) [0x7fbec9db1dd5]
/lib64/libc.so.6(clone+0x6d) [0x7fbec8e3eead]
**Expected behavior**: 

**Steps to reproduce**:

1. .go 8086.536621 -5673.490723 127.653847 1
2. .st
3. 

**Client version**: 
1.12.1
**Commit hash**: 
https://github.com/vmangos/core/commit/7a6464366ce61a5a9fbb41163ff251da8fbc9184
**Operating system**: 
Centos7, using v14 map

**Comment by ratkosrb** [comment]
That location is unreachable without gm commands, so I don't think its a real issue. And the crash log does not seem related. There is no crash when i use .st there.

**Comment by coolzoom** [comment]
all right, i'm going to close this issue, thanks
