### ISSUE TITLE
Received SIGSEGV Segmentation fault

### ISSUE THREAD

**Issue by Friwa28** [vmangos/core#185]
**Current behavior**: 
When compiling with the library TBB, gives an error after ~ 10 hours of server 
"Received SIGSEGV Segmentation fault"
If you compile with malloc, then the server works without errors (worked 3 days)
https://ru.wikipedia.org/wiki/Ошибка_сегментации

/usr/lib/x86_64-linux-gnu/libtbbmalloc.so.2(+0xe873) [0x7f562a8d7873]
/usr/lib/x86_64-linux-gnu/libtbbmalloc.so.2(+0x1107d) [0x7f562a8da07d]
/usr/lib/libACE-6.3.3.so(+0xee211) [0x7f562bd00211]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x65f9) [0x7f562ab0d5f9]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7658) [0x7f562ab0e658]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f5629b37d0f]

Sorry for my english
**Expected behavior**: 
Должно работать с этой библиотекой нормально без сбоев =)
**Steps to reproduce**:

1. Скомпилировать с TBB
2. Сервер должен поработать какое то время, можно даже без нагрузки.
3. 

**Client version**: 
1.12.1 BUILD:5875
**Commit hash**: 
Core Revision: 7a6464366ce61a5a9fbb
**Operating system**: 
Linux Debian 9.8

**Comment by ratkosrb** [comment]
There must be something wrong with the version of TBB you are using. Try a different one or stick with STD malloc.
