### ISSUE TITLE
🐛 [Bug] - NAXX

### ISSUE THREAD

**Issue by xujibbs** [vmangos/core#1857]
**Thaddius cannot be correctly activated.**
19 bots with one player to fight with Feugen and the rest under my lead to fight with Stalagg。 both were killed in the separate platform at the same time by using order .die. However, Thaddius cannot be activated or he is activated but can't target him while he was not attacking anybody.

**Comment by Gamemechanicwow** [comment]
You can't kill them with .die - you need to damage them.
Otherwise, you break the script.

**Comment by xujibbs** [comment]
Thanks, I try to damage them
