### ISSUE TITLE
🐛 [Bug][Quest] New errors in the console when starting the server. Update today.

### ISSUE THREAD

**Issue by gajet5** [vmangos/core#1861]
## 🐛 Bug report
Loading Quests...
Quest 9298 has `SrcItemId` = 22949 but `SrcItemCount` = 0, set to 1 but need fix in DB.
Quest 9297 has `SrcItemId` = 22949 but `SrcItemCount` = 0, set to 1 but need fix in DB.
Quest 9296 has `SrcItemId` = 22949 but `SrcItemCount` = 0, set to 1 but need fix in DB.
Quest 8856 has `SrcItemId` = 20807 but `SrcItemCount` = 0, set to 1 but need fix in DB.
Quest 7704 has `SrcItemId` = 18950 but `SrcItemCount` = 0, set to 1 but need fix in DB.
Quest 810 has `NextQuestInChain` = 811 but quest 811 does not exist, quest chain will not work.
Quest 620 has `SrcItemId` = 3985 but `SrcItemCount` = 0, set to 1 but need fix in DB.
Quest 259 has `NextQuestInChain` = 260 but quest 260 does not exist, quest chain will not work.
Quest 7908 has `SrcItemId` = 18706 but `SrcItemCount` = 0, set to 1 but need fix in DB.

### Expected behavior
There are no errors at the start.

### Steps to reproduce

1. Update server.
2. Start server.
5. Profit

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  

OS Client: Win 11
OS Server: Ubuntu

### Crashlog

- None

**Comment by Daribon** [comment]
Can confirm on latest rev.

**Comment by gajet5** [comment]
Fixed: https://github.com/vmangos/core/commit/a01171d0b2781585a69a403c0d9796e00c29f95b
Quest 9298 has SrcItemId = 22949 but SrcItemCount = 0, set to 1 but need fix in DB.
Quest 9297 has SrcItemId = 22949 but SrcItemCount = 0, set to 1 but need fix in DB.
Quest 9296 has SrcItemId = 22949 but SrcItemCount = 0, set to 1 but need fix in DB.
Quest 8856 has SrcItemId = 20807 but SrcItemCount = 0, set to 1 but need fix in DB.
Quest 7704 has SrcItemId = 18950 but SrcItemCount = 0, set to 1 but need fix in DB.
Quest 620 has SrcItemId = 3985 but SrcItemCount = 0, set to 1 but need fix in DB.
Quest 7908 has SrcItemId = 18706 but SrcItemCount = 0, set to 1 but need fix in DB.

No Fixed
Quest 810 has `NextQuestInChain` = 811 but quest 811 does not exist, quest chain will not work.
Quest 259 has `NextQuestInChain` = 260 but quest 260 does not exist, quest chain will not work.
