### ISSUE TITLE
🐝 [Bug]

### ISSUE THREAD

**Issue by yybss** [vmangos/core#1864]
![微信截图_20230410141857](https://user-images.githubusercontent.com/88591182/230839552-35a626a3-225a-4dee-98b6-88e110700114.png)

## 🐝 Bug report - Quest

亡灵种族无法接取高图斯的命令
### Steps to reproduce

1.我的等级达到了60，这个任务等级是55级且没有前置任务的，但是亡灵种族无法与军官高图斯对话
2.测试部落其他种族都可以对话，唯独亡灵种族无法对话获得任务品

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  

OS Client: windows10 64位 中文版
OS Server: windows2008 64位 中文版

### Crashlog

- None

**Comment by wanglinb741** [comment]
这是你的奥格主城声望没有达到

**Comment by ratkosrb** [comment]
I do not understand Chinese. Bug reports should be in English. And you should specify the commit hash as well.

**Comment by xujibbs** [comment]
This is not bug, I'm sure it's your reputation issue.

**Comment by wanglinb741** [comment]
This is your Ogg Main City reputation not reached

**Comment by wanglinb741** [comment]
This is your Ogg Main City reputation not reached
