### ISSUE TITLE
🐛 [Bug] World Server Crash logs 

### ISSUE THREAD

**Issue by wthslw001** [vmangos/core#1867]
OS Client: 
OS Server: 

### Crashlog

2023-04-21 15:11:16 ./mangosd(_ZNK14dtNavMeshQuery27findRandomPointAroundCircleEmPKffPK13dtQueryFilterPFfvEPmPf+0x382) [0x564785cb06c2]
./mangosd(_ZNK3Map21GetWalkRandomPositionEP16GenericTransportRfS2_S2_fj+0x2a4) [0x56478570d6fc]
./mangosd(_ZNK11WorldObject14GetRandomPointEffffRfS0_S0_+0xef) [0x5647857b3f57]
./mangosd(_ZN23RandomMovementGenerator18_setRandomLocationER8Creature+0xad) [0x5647857652b5]
./mangosd(_ZN23RandomMovementGenerator11UpdateAsyncER8Creaturej+0xbe) [0x56478576569e]
./mangosd(_ZN12MotionMaster17UpdateMotionAsyncEj+0x63) [0x56478575ac13]
./mangosd(_ZN4Unit6UpdateEjj+0x423) [0x56478587f793]
./mangosd(_ZN8Creature6UpdateEjj+0x1d2) [0x5647857909f2]
./mangosd(_ZN3Map23UpdateCellsAroundObjectEjjPK11WorldObject+0x347) [0x564785724da7]
./mangosd(_ZN3Map6UpdateEj+0x319) [0x56478571d399]
./mangosd(_ZN10ThreadPool9worker_sq6doWorkEv+0x56) [0x564785bba796]
./mangosd(_ZN10ThreadPool12worker_mysqlINS_9worker_sqEE6doWorkEv+0x15) [0x564785bbcd15]
./mangosd(_ZN10ThreadPool6worker4loopEv+0x4e) [0x564785bbc3be]
./mangosd(_ZN10ThreadPool6worker12loop_wrapperEv+0x33) [0x564785bbc903]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xd6de4) [0x7f79e73adde4]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7f79e754b609]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f79e709a133]

**Comment by Gamemechanicwow** [comment]
Are you using the newest revision? 

That looks like an old crash - that was fixed months ago.
