### ISSUE TITLE
after "Make SpellEntry related functions into class members." update , the creature  will not cast any spell.

### ISSUE THREAD

**Issue by caicaicai** [vmangos/core#187]
**Current behavior**: 
the creature not cast any spell ( Seems to have lost the AI script) .
**Expected behavior**: 
Monsters have normal behavior, including releasing skills
**Steps to reproduce**:

1. use version  539bae6c9c5f1e64308cfafddf07e12e8230cf6f
2. the creautre（.eg 11350）not normal.

**Client version**: 
1.12.3
**Commit hash**: 
539bae6c9c5f1e64308cfafddf07e12e8230cf6f
**Operating system**: 
windows 7

**Comment by ratkosrb** [comment]
Fixed -> https://github.com/vmangos/core/commit/bfb2d979849eb6d60f7478bd914f1548cbd9beb0
