### ISSUE TITLE
🦂 [Bug]master loot

### ISSUE THREAD

**Issue by zhwblm** [vmangos/core#1871]
When changing the allocation during team formation to captain allocation, regardless of any quality, the captain needs to allocate. No matter how the item quality is set, teammates cannot view the corpse

<!-
-
Visit our Discord to engage directly with the developers of VMaNGOS.

Discord: https://discord.gg/x9a2jt7
-->
### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by ss958** [comment]
The latest core of this problem still exists.
