### ISSUE TITLE
🐛 [Bug]

### ISSUE THREAD

**Issue by gujinjian** [vmangos/core#1873]
[ 28%] Building CXX object src/game/CMakeFiles/game.dir/Anticheat/Anticheat.cpp.o
[ 28%] Building CXX object src/game/CMakeFiles/game.dir/AuctionHouse/AuctionHouseBotMgr.cpp.o
[ 29%] Building CXX object src/game/CMakeFiles/game.dir/AuctionHouse/AuctionHouseMgr.cpp.o
In file included from /home/gjj/core/src/game/Anticheat/Anticheat.h:77:0,
                 from /home/gjj/core/src/game/Anticheat/Anticheat.cpp:17:
/home/gjj/core/src/game/Anticheat/WardenAnticheat/Warden.hpp:132:9: error: ‘ClientOSType’ does not name a type
         ClientOSType m_clientOS;
         ^~~~~~~~~~~~
/home/gjj/core/src/game/Anticheat/WardenAnticheat/Warden.hpp:133:9: error: ‘ClientPlatformType’ does not name a type
         ClientPlatformType m_clientPlatform;
         ^~~~~~~~~~~~~~~~~~
[ 29%] Building CXX object src/game/CMakeFiles/game.dir/Battlegrounds/BattleGround.cpp.o
[ 29%] Building CXX object src/game/CMakeFiles/game.dir/Battlegrounds/BattleGroundAB.cpp.o
src/game/CMakeFiles/game.dir/build.make:1286: recipe for target 'src/game/CMakeFiles/game.dir/Anticheat/Anticheat.cpp.o' failed
make[2]: *** [src/game/CMakeFiles/game.dir/Anticheat/Anticheat.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:285: recipe for target 'src/game/CMakeFiles/game.dir/all' failed
make[1]: *** [src/game/CMakeFiles/game.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
-----------------------------------------------------------
cmake the core  now  the anticheat show the wrong   please help

**Comment by gujinjian** [comment]
wait online

**Comment by ghost** [comment]
Follow the Issue Template!
There is no OS version, neither a commit-hash..
