### ISSUE TITLE
[quest] rescure OOX-17/TN

### ISSUE THREAD

**Issue by coolzoom** [vmangos/core#188]
**Current behavior**: 
quest could not being completed, it will fail after the robot arrive destination.
there're few other robot rescure quest could not finsh as well, i see those changes were made together. im not quite familar with the database script so not sure what i should do
probably related to 
https://github.com/vmangos/core/commit/eb004991f044dd77cb7a5d6f32e14cad1f0f946e

if you need further info please let me know

**Expected behavior**: 

**Steps to reproduce**:

1. 
2. 
3. 

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**:

**Comment by ratkosrb** [comment]
I did the whole quest and it worked without issues.
https://streamable.com/7ekqm

Maybe you took too long to escort it? There is a 30 minute limit on escort quests to prevent them from getting stuck.

**Comment by coolzoom** [comment]
all right, let me do some more tests.
