### ISSUE TITLE
🐛 [Bug] Error applying migration

### ISSUE THREAD

**Issue by ellingtonsantos** [vmangos/core#1881]
## 🐛 Bug report
Error received while importing migrations:
ERROR 1048 (23000) at line 249172: Column 'name_loc1' cannot be null
Migration 20230509115900 sets locales_creature.name_loc1 as NULL, but locales_creature.name_locX cannot be null.

### Expected behavior
No errors.

### Steps to reproduce

1. Generate migrations
2. Import migrations

### Version & Environment

Client Version: 
1.12.1.5875

Commit Hash:  
785463eb0b0e4bc047140a700a42e566ab590de5

OS Client: Linux
OS Server: Linux

### Crashlog

- None

**Comment by gujinjian** [comment]
it is maybe the mysql >5.6  you can see again

**Comment by ellingtonsantos** [comment]
I'm using mariadb:

$ mariadb --version
mariadb  Ver 15.1 Distrib 10.11.3-MariaDB, for Linux (x86_64) using readline 5.1

And table schema prevents NULL values:

```
CREATE TABLE IF NOT EXISTS `locales_creature` (
  `entry` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `name_loc1` varchar(100) NOT NULL DEFAULT '',
  `name_loc2` varchar(100) NOT NULL DEFAULT '',
  `name_loc3` varchar(100) NOT NULL DEFAULT '',
  `name_loc4` varchar(100) NOT NULL DEFAULT '',
  `name_loc5` varchar(100) NOT NULL DEFAULT '',
  `name_loc6` varchar(100) NOT NULL DEFAULT '',
  `name_loc7` varchar(100) NOT NULL DEFAULT '',
  `name_loc8` varchar(100) NOT NULL DEFAULT '',
  `subname_loc1` varchar(100) DEFAULT NULL,
  `subname_loc2` varchar(100) DEFAULT NULL,
  `subname_loc3` varchar(100) DEFAULT NULL,
  `subname_loc4` varchar(100) DEFAULT NULL,
  `subname_loc5` varchar(100) DEFAULT NULL,
  `subname_loc6` varchar(100) DEFAULT NULL,
  `subname_loc7` varchar(100) DEFAULT NULL,
  `subname_loc8` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`entry`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
```

**Comment by Firewarrior565** [comment]
I just had this same issue with a fresh Debian build using MariaDB.

**Comment by coolzoom** [comment]
mysql5.5 and 5.6 are recommended, if having zero date issue, try SET @@sql_mod : = REPLACE(@@sql_mode, 'NO_ZERO_DATE', '');

**Comment by Firewarrior565** [comment]
Doing some tinkering I found this. 

-Drop the mangos DB.
-Create it again.
-Load in the 2021 world DB data.
-Run the SQL query below against the mangos DB.
-Run the world SQL migrations.
-Nice and happy!

ALTER TABLE `locales_item`
    MODIFY COLUMN `name_loc1` VARCHAR(100) NULL DEFAULT '' COLLATE 'utf8_general_ci',
    MODIFY COLUMN `name_loc2` VARCHAR(100) NULL DEFAULT '' COLLATE 'utf8_general_ci',
    MODIFY COLUMN `name_loc3` VARCHAR(100) NULL DEFAULT '' COLLATE 'utf8_general_ci',
    MODIFY COLUMN `name_loc4` VARCHAR(100) NULL DEFAULT '' COLLATE 'utf8_general_ci',
    MODIFY COLUMN `name_loc5` VARCHAR(100) NULL DEFAULT '' COLLATE 'utf8_general_ci',
    MODIFY COLUMN `name_loc6` VARCHAR(100) NULL DEFAULT '' COLLATE 'utf8_general_ci',
    MODIFY COLUMN `name_loc7` VARCHAR(100) NULL DEFAULT '' COLLATE 'utf8_general_ci',
    MODIFY COLUMN `name_loc8` VARCHAR(100) NULL DEFAULT '' COLLATE 'utf8_general_ci';

ALTER TABLE `locales_creature`
    MODIFY COLUMN `name_loc1` VARCHAR(100) NULL DEFAULT '' COLLATE 'utf8_general_ci',
    MODIFY COLUMN `name_loc2` VARCHAR(100) NULL DEFAULT '' COLLATE 'utf8_general_ci',
    MODIFY COLUMN `name_loc3` VARCHAR(100) NULL DEFAULT '' COLLATE 'utf8_general_ci',
    MODIFY COLUMN `name_loc4` VARCHAR(100) NULL DEFAULT '' COLLATE 'utf8_general_ci',
    MODIFY COLUMN `name_loc5` VARCHAR(100) NULL DEFAULT '' COLLATE 'utf8_general_ci',
    MODIFY COLUMN `name_loc6` VARCHAR(100) NULL DEFAULT '' COLLATE 'utf8_general_ci',
    MODIFY COLUMN `name_loc7` VARCHAR(100) NULL DEFAULT '' COLLATE 'utf8_general_ci',
    MODIFY COLUMN `name_loc8` VARCHAR(100) NULL DEFAULT '' COLLATE 'utf8_general_ci';

ALTER TABLE `locales_gameobject`
    MODIFY COLUMN `name_loc1` VARCHAR(100) NULL DEFAULT '' COLLATE 'utf8_general_ci',
    MODIFY COLUMN `name_loc2` VARCHAR(100) NULL DEFAULT '' COLLATE 'utf8_general_ci',
    MODIFY COLUMN `name_loc3` VARCHAR(100) NULL DEFAULT '' COLLATE 'utf8_general_ci',
    MODIFY COLUMN `name_loc4` VARCHAR(100) NULL DEFAULT '' COLLATE 'utf8_general_ci',
    MODIFY COLUMN `name_loc5` VARCHAR(100) NULL DEFAULT '' COLLATE 'utf8_general_ci',
    MODIFY COLUMN `name_loc6` VARCHAR(100) NULL DEFAULT '' COLLATE 'utf8_general_ci',
    MODIFY COLUMN `name_loc7` VARCHAR(100) NULL DEFAULT '' COLLATE 'utf8_general_ci',
    MODIFY COLUMN `name_loc8` VARCHAR(100) NULL DEFAULT '' COLLATE 'utf8_general_ci';
