### ISSUE TITLE
Baron Riverdare heals even if Skeletons are killed quickly

### ISSUE THREAD

**Issue by heyiamsven** [vmangos/core#189]
**Current behavior**: 
Baron Riverdare still uses his self heal spell (Death Pact) even when the skeletons are killed in expected time. This situation occurs always and on every skeleton wave. The boss becomes not killeable by players this way.

**Expected behavior**: 
If skeletons are killed in expected time Baron Riverdare shouldn't use Death Pact anymore to heal himself.

Here is the solution in C# for Trinity:
https://github.com/Nitair/TrinityCore/blob/stratholme_rivendare/src/server/scripts/EasternKingdoms/Stratholme/boss_baron_rivendare.cpp

**Steps to reproduce**:

1. Attack Baron Riverdare
2. Kill Skeletons in Time
3. Baron Riverdare still uses Death Pact

**Client version**: 
1.12.1

**Commit hash**: 

**Operating system**: 
Windows 10

**Comment by ratkosrb** [comment]
I was able to reproduce the issue once when i teleported to him directly instead of clearing the mini bosses first. But it doesn't bug out when I do it the normal way. Also that trinity script is almost identical to the one used here.

**Comment by heyiamsven** [comment]
People on my server reported the bug. I tried to clear the Instance most naturally without porting directly to him 3 times and each time I was able to reproduce. The trinity script let's the skeletons cast the death pact instead of Baron itself like it is in vmangos the case.  I think this is the cause of the issue.

I replaced Death Pact for test purposes with Mortal Strike and it seems if the bug occurs, that he wants always to use Death Pact when he spawns new skeletons (if earlier skeleton wave is cleared)

**Comment by ratkosrb** [comment]
Try if he still heals while skeletons are dead after this commit -> https://github.com/vmangos/core/commit/c11e45bf4fa58e14fdea90623b12983971202cc3

**Comment by heyiamsven** [comment]
Script works now correctly. Unfortunately he is spawned at wrong location (right corner) and he has movement type set to move. I changed it by command to the right position and movement type.

**Comment by ratkosrb** [comment]
This must be due to something you did, because i didn't touch his spawn data at all. Just replaced the hardcoded script with EventAI.
