### ISSUE TITLE
🦂 [Bug]There is a problem with the assignment of captains,

### ISSUE THREAD

**Issue by zhwblm** [vmangos/core#1897]
There is a problem with the allocation of the captain in the VMANGOS squadron, if the captain distributes the loot instead, then regardless of the quality of the item, only the captain can see it, and the other team members cannot see the pickup, and the normal captain allocation should be equal to or higher than the selected quality of the item is the captain allocation At the same time, all team members should be able to view the corpse But in the latest Vmangos it is wrong

**Comment by gujinjian** [comment]
I have also get the same wrong  thank you also neet too rebuild

**Comment by zhwblm** [comment]
No solution has been found yet Do you have a solution?

> 我也弄错了，谢谢你也重建

**Comment by ss958** [comment]
I'm encountering this issue as well, and I hope a skilled expert can resolve it. Thank you!

**Comment by ratkosrb** [comment]
This should be fixed already. Are you using the latest version of the core?

**Comment by ss958** [comment]
I am using the latest core version, with a client of 1.12.1. When the team leader is distributing items, it's set to require distribution only for items of green quality and above. However, white-quality items are also requiring the team leader to distribute them.
