### ISSUE TITLE
🐛 [Bug]Compile the latest version of code server crash logs on Ubuntu 20.11

### ISSUE THREAD

**Issue by wthslw001** [vmangos/core#1902]
## 🐛 Bug report
![崩溃日志](https://github.com/vmangos/core/assets/8679316/3de81224-021e-4e04-bdaf-6df6825294fc)

### Version & Environment

  Client Version:
  - 1.12.1.5875
 - 1.12.3.6141

OS Client: Win 10+
OS Server:  Ubuntu 20.11

### Crashlog

2023-05-23 07:35:14 Received SIGSEGV
2023-05-23 07:35:14 ./mangosd(_ZNK14dtNavMeshQuery27findRandomPointAroundCircleEmPKffPK13dtQueryFilterPFfvEPmPf+0x382) [0x55b822165632]
./mangosd(_ZNK3Map21GetWalkRandomPositionEP16GenericTransportRfS2_S2_fj+0x2a4) [0x55b821bc489c]
./mangosd(_ZNK11WorldObject14GetRandomPointEffffRfS0_S0_+0xef) [0x55b821c6b747]
./mangosd(_ZN23RandomMovementGenerator18_setRandomLocationER8Creature+0xad) [0x55b821c1cab5]
./mangosd(_ZN23RandomMovementGenerator11UpdateAsyncER8Creaturej+0xbe) [0x55b821c1ce9e]
./mangosd(_ZN12MotionMaster17UpdateMotionAsyncEj+0x63) [0x55b821c12413]
./mangosd(_ZN4Unit6UpdateEjj+0x423) [0x55b821d36b53]
./mangosd(_ZN8Creature6UpdateEjj+0x1d2) [0x55b821c481e2]
./mangosd(_ZN3Map23UpdateCellsAroundObjectEjjPK11WorldObject+0x347) [0x55b821bdc2e7]
./mangosd(_ZN3Map6UpdateEj+0x309) [0x55b821bd4d09]
./mangosd(_ZN10ThreadPool9worker_sq6doWorkEv+0x56) [0x55b82206f736]
./mangosd(_ZN10ThreadPool12worker_mysqlINS_9worker_sqEE6doWorkEv+0x15) [0x55b822071cb5]
./mangosd(_ZN10ThreadPool6worker4loopEv+0x4e) [0x55b82207135e]
./mangosd(_ZN10ThreadPool6worker12loop_wrapperEv+0x33) [0x55b8220718a3]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xd6de4) [0x7f4dccf23de4]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7f4dcd0c1609]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f4dccc10133]

**Comment by ratkosrb** [comment]
In mangosd.conf change Continents.MotionUpdate.Threads to 1 and test if it fixes the problem.

**Comment by wthslw001** [comment]
> In mangosd.conf change Continents.MotionUpdate.Threads to 1 and test if it fixes the problem.

In mangosd.conf change Continents.MotionUpdate.Threads to 1  
The problem still exists.

**Comment by wthslw001** [comment]
2023-05-25 09:40:51 ./mangosd(_ZNK14dtNavMeshQuery27findRandomPointAroundCircleEmPKffPK13dtQueryFilterPFfvEPmPf+0x382) [0x562c604d7e72]
./mangosd(_ZNK3Map21GetWalkRandomPositionEP16GenericTransportRfS2_S2_fj+0x2a4) [0x562c5ff360fc]
./mangosd(_ZNK11WorldObject14GetRandomPointEffffRfS0_S0_+0xef) [0x562c5ffdd007]
./mangosd(_ZN23RandomMovementGenerator18_setRandomLocationER8Creature+0xad) [0x562c5ff8e315]
./mangosd(_ZN23RandomMovementGenerator11UpdateAsyncER8Creaturej+0xbe) [0x562c5ff8e6fe]
./mangosd(_ZN12MotionMaster17UpdateMotionAsyncEj+0x63) [0x562c5ff83c73]
./mangosd(_ZN4Unit6UpdateEjj+0x423) [0x562c600a8873]
./mangosd(_ZN8Creature6UpdateEjj+0x1d2) [0x562c5ffb9a42]
./mangosd(_ZN3Map23UpdateCellsAroundObjectEjjPK11WorldObject+0x347) [0x562c5ff4db47]
./mangosd(_ZN3Map6UpdateEj+0x309) [0x562c5ff46569]
./mangosd(_ZN10ThreadPool9worker_sq6doWorkEv+0x56) [0x562c603e1f76]
./mangosd(_ZN10ThreadPool12worker_mysqlINS_9worker_sqEE6doWorkEv+0x15) [0x562c603e44f5]
./mangosd(_ZN10ThreadPool6worker4loopEv+0x4e) [0x562c603e3b9e]
./mangosd(_ZN10ThreadPool6worker12loop_wrapperEv+0x33) [0x562c603e40e3]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xd6de4) [0x7f63b4678de4]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7f63b4816609]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f63b4365133]

**Comment by ratkosrb** [comment]
Issue should be finally fixed after this commit: https://github.com/vmangos/core/commit/d4c0f86437ea2c8d5ebdb30e1d37268a72f47bd3

Please test it!
