### ISSUE TITLE
🐛 [Bug] Teleport breaks area triggers

### ISSUE THREAD

**Issue by Wall-core** [vmangos/core#1907]
## 🐛 Bug report

This is something that I've noticed happen for a long time when using GM teleport commands; if you teleport to a far away location, it will occasionally break the ability to zone into dungeons until you relog. This was very pronounced today during Warsong Gulch; as players were teleported to azshara crater before queueing into WSG, it would effectively break the ability to capture flags until the player relogs. I don't know exactly how to replicate but the most reliable way is to teleport to uninitialized maps and then attempt to zone into a dungeon, 25% of the time it will break the area triggers until you relog. might be related to TeleportFar
### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by ratkosrb** [comment]
This behavior is entirely client side. It happens if you teleport to a map without any areatriggers. Do you have custom maps?

**Comment by Wall-core** [comment]
Yeah we had been exploring Azshara Crater map which doesn't contain triggers. Much appreciated on the quick reply.
