### ISSUE TITLE
🚀 [Feature] Maraudon, when player jump on the tree, the mobs directly climb up to tree as well

### ISSUE THREAD

**Issue by rogical** [vmangos/core#1908]
## 🚀 Feature
Maraudon, when player jump on the tree, the mobs directly climb up to tree as well. thus player will not play as below 
https://www.youtube.com/watch?v=D5QRcU6dPRo

which is very widely played 

### Visualization
https://www.youtube.com/watch?v=D5QRcU6dPRo

### Benefits, Purpose
Blizzard like, allow vmangos to be more Blizzard like
funny to players
they can use their skills to have fun and get golds

**Comment by rogical** [comment]
![((W6XI{Z(B9O3K$4K$EFH_0](https://github.com/vmangos/core/assets/1172002/d5976456-a7c1-4fc0-a266-65106ea17dbf)

**Comment by ratkosrb** [comment]
Blizzard uses a different path finding library, which we don't have access to. You should not expect the pathing to be the same.

**Comment by rogical** [comment]
13min
player can jump on tree
jump on jump off
in Blizzard way, if you jump on or jump off, mobs will trun around. while in vmangos, mbos directly climb up on tree
