### ISSUE TITLE
Player buffs should apply threat

### ISSUE THREAD

**Issue by heyiamsven** [vmangos/core#191]
**Current behavior**: 
Battle Shout and other Player buffs generate no threat.

**Expected behavior**: 
Battle Shout and other Player buffs should generate threat. Warriors used for example Battle Shout to generate threat for larger mob groups. If a buff get's reapplied it should also generate additional threat. Threat generated by Buffs depends on how many players get buffed by it, what the threat multiplier of the tank is and how many mobs are tanked.

https://forum.elysium-project.org/topic/25797-reporting-bug-as-bug-tracker-is-giving-500-internal-server-error/
https://forum.elysium-project.org/topic/23110-aoe-threat-generation/

**Comment by ratkosrb** [comment]
Test before making reports.
https://streamable.com/j9alu

**Comment by heyiamsven** [comment]
It just pulls the aggro in your video, but if you check via KTM Addon it generates no threat and the threat should multiply by the amount of players that receive the buff. Battle Shout threat behaviour was in KTM noticeable back then. Normally it should be possible to hold aggro by the warrior by spamming it vs AoE spells. 

For example if a player has lets say 1000 Threat in KTM the Warrior should be able to pull the aggro with 3-4 Battle Shout (in a 5 man group), because it should generate 5x55 threat for 5 players each time).

**Comment by Gamemechanicwow** [comment]
KTM dont know the serverside threat values. It estimates/guesses threat based on predefined values in the addon and combatlog listeners. Don't expect it to be 100% accurate.

**Comment by ratkosrb** [comment]
You realize that threat is server side, right? That addon is guessing how much threat you should have based on the abilities you are using, but it does not know your actual threat. And in this case the addon is bugged and doesn't think Battle Shout generates threat, even though it does. Your third party addon being shit is not the server's fault.

Here is another video where you can see me take threat by spamming only Battle Shout, even though the Warlock is attacking the mob.

https://streamable.com/pxwcv

**Comment by heyiamsven** [comment]
I already thought about that. Is there any way to get the real threat numbers generated by the server?
I'll try to get some footage of a 5-man dungeon test as people report that they we're normally able to hold aggro with spamming BS against AoE spells. Anyways if this is not true I'm really sorry for opening this issue then!

**Comment by ratkosrb** [comment]
To my knowledge, there is no command to list threat. You would have to edit the source and make it print it yourself.
