### ISSUE TITLE
🐝 [Bug] The Captain's Chest

### ISSUE THREAD

**Issue by Wall-core** [vmangos/core#1910]
## 🐝 Bug report - Quest

Captain Hecklbury Smotts offers quest 641 and quest 8551, both of which are "The Captain's Chest". I believe 641 was replaced by 8551 in a later patch, and his involved relations don't reflect this as he offers both in patch 10. Haven't confirmed on default vmangos but this is untouched and likely needs an update to remove 641 in patch 7.
### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by Wall-core** [comment]
Sorry, quest 614 - not 641

**Comment by NickTyrer** [comment]
Closed here https://github.com/vmangos/core/pull/1970
