### ISSUE TITLE
💬[讨论

### ISSUE THREAD

**Issue by yybss** [vmangos/core#1913]
## 💬 讨论<!--详细描述你想讨论的内容。如果需要，请附上屏幕截图和图纸。--
How to use the source code to trigger the dialogue? I studied that the npc table has Scriptname, but there is no Scriptname in the item list. Where is the item list Scriptname triggered?

**Comment by yybss** [comment]
How to use the source code to trigger the dialogue? I studied that the npc table has Scriptname, but there is no Scriptname in the item list. Where is the item list Scriptname triggered?

**Comment by cdkr** [comment]
What kind of dialogue? Could you paste a screenshot.
