### ISSUE TITLE
🐝 [Bug] Cancelling the quest "Need for a Cure" (id:812) deletes the item "Venomtail Antidote" (id:4904) from inventory.

### ISSUE THREAD

**Issue by alibayindir** [vmangos/core#1914]
## 🐝 Bug report - Quest
Cancelling the quest "Need for a Cure" (id:812) deletes the item "Venomtail Antidote" (id:4904) from inventory.
### Expected behavior
"Venomtail Antidote" which is reward from "Finding the Antidote" (id:813) quest should be stay in inventory even if the "Need for a Cure" quest is failed or cancelled.

### Steps to reproduce
1. Accept quest "Need for a Cure".
2. Accept quest "Finding the Antidote".
3. Complete quest "Finding the Antidote".
4. Cancel quest "Need for a Cure".
5. Profit

### Version & Environment
  Client Version:
  - 1.12.1.5875

OS Client: Win 10
OS Server: Win 10

**Comment by Gamemechanicwow** [comment]
I don't think this is a bug.

![image](https://github.com/vmangos/core/assets/2223066/6d3945d8-43c4-4c8a-bf20-c48d7447b167)

**Comment by alibayindir** [comment]
I am sorry.
Some old game guides suggest cancel and reaccept Need for Cure quest if timer run out.  I think some old patches work like that.
Today I have tested it in official classic servers and it works  same as implemented in vmangos.
