### ISSUE TITLE
🐛 [Bug] Process terminated abnormally

### ISSUE THREAD

**Issue by yaolovelive** [vmangos/core#1915]
## 🐛 Bug report

When there are many people online, the process may exit abnormally。
Like this(From **dmesg**):
  - [Mon May 22 15:09:17 2023] mangosd[2869981]: segfault at ffffffffffffff80 ip 00007fd8bdc3722d sp 00007fd8a8104f40 error 7 in libstdc++.so.6.0.30[7fd8bdc23000+111000]
  - [Mon May 22 15:47:35 2023] traps: mangosd[3438615] trap divide error ip:562e826ec2ea sp:7fbe84705618 error:0 in mangosd[562e81e68000+88e000]
  - [Wed May 31 20:53:52 2023] mangosd[2477426]: segfault at ffffffffffffff80 ip 00007fec3dfe922d sp 00007febfa7bd3c0 error 7 in libstdc++.so.6.0.30[7fec3dfd5000+111000]
  - [Wed May 31 20:59:36 2023] mangosd[2481128]: segfault at ffffffffffffff80 ip 00007fc33219b22d sp 00007fc2eeabe3c0 error 7 in libstdc++.so.6.0.30[7fc332187000+111000]
  - [Wed May 31 21:03:34 2023] mangosd[2482379]: segfault at ffffffffffffff80 ip 00007f825bb5c22d sp 00007f8218dc33c0 error 7 in libstdc++.so.6.0.30[7f825bb48000+111000]
  - [Fri Jun  2 00:33:12 2023] traps: mangosd[2483388] trap divide error ip:55c1f8593d2a sp:7f3a9bf48618 error:0 in mangosd[55c1f7d0e000+890000]
  - [Fri Jun  2 16:34:38 2023] traps: mangosd[2983371] trap divide error ip:55b7d2b63d2a sp:7f7d13a8c618 error:0 in mangosd[55b7d22de000+890000]

### Steps to reproduce

1. Irregular

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  
  f74cc2c762c140d097a6bc37f47a45571b25cb10(Maybe..)

OS Client: Win 10
OS Server: ubuntu 22.04

### Crashlog

- None

### The End
Thanks to the author for his hard work

**Comment by ratkosrb** [comment]
You need to compile with debug symbols for the call stack to be useful. The log you posted gives me no useful information.
