### ISSUE TITLE
🦂 [Bug] wrong money awarded Gnomeregan , The Sparklematic 5200!

### ISSUE THREAD

**Issue by rogical** [vmangos/core#1918]
## 🦂 Bug report - Dungeon
player reported he was awarded 429496Gold in quest The Sparklematic 5200!

### Expected behavior
less award

### Steps to reproduce
n/a

### Version & Environment
  Client Version:
  - 1.14.2

OS Client: Win 10
OS Server: ubuntu 22.04

### Crashlog
n/a

**Comment by rogical** [comment]
![QQ截图20230602231604](https://github.com/vmangos/core/assets/1172002/38bb6ec4-cca6-4f50-8341-63b6ced5027a)

**Comment by ratkosrb** [comment]
This is a visual bug in HermesProxy, not a bug in the server.
