### ISSUE TITLE
Fearing / Confusing a player on a transport sends the player flying

### ISSUE THREAD

**Issue by Test045** [vmangos/core#193]
**Current behavior**: 
Fearing / Confusing a player on a boat or zeppelin sends it flying
**Expected behavior**: 
The player should stay on the transport
**Steps to reproduce**:

1. Go into a zeppelin or a boat with a warlock and another character
2. Have the warlock fear the other character
3. Assert that the other character is sent flying

**Client version**: 
1.12
**Commit hash**: 

**Operating system**: 
Windows 10

Here's my analysis  : 
~~Charge works perfectly on transport. For some reason, the feared/confused unit loses/never gets the MOVEFLAG_SPLINE_ENABLED unit movement flag for no reason on transports. This is 100% the cause, because having that flag determines how the movement update packet is built (see Object.cpp line 461). Hack-fixing it fixes the issue, but I still haven't found the root cause so far. Of course, on land, the unit keeps that flag like it should.~~

~~The fear movement generator builds the spline data through MoveSplineInit::Launch() and sets the flag properly everytime as far as I can tell, very weird issue.
Old Nostalrius videos have shown it working properly, but I don't see any related commit to this that could have broken this.~~

Nevermind, the flag doesn't seem to change shit.
The movement info is overwritten by the client when handling opcodes CMSG_MOVE_NOT_ACTIVE_MOVER and CMSG_FORCE_RUN_SPEED_CHANGE_ACK , but hack-fixing it to keep the MOVEFLAG_SPLINE_ENABLED doesn't do shit. At this point I have no damn clue of what's the issue is

**Comment by Kittnz** [comment]
It might have been fixed but we didn't get the latest core rev from nost. It never worked correctly to begin with.

**Comment by Daribon** [comment]
Wasn't working on early nostalrius, at least from what I recall.

**Comment by Test045** [comment]
just found the root issue after editing my post : the issue comes from how we handle CMSG_FORCE_RUN_SPEED_CHANGE_ACK. See the mapped function pointer tied to this packet : WorldSession::HandleForceSpeedChangeAckOpcodes in MovementHandler.cpp
So far removing all the code there causes fear to work perfectly on transport.
Will have to investigate what dumb shit we were replying to the client.
