### ISSUE TITLE
 You can not get ambush after the last update takes you out of the stealh without applying anything

### ISSUE THREAD

**Issue by kasykiller** [vmangos/core#194]
**Current behavior**: 

the ambush, can not be applied to npcs removes the invisible without ambush

**Expected behavior**: 

the ambush would have to give to the objective, and then to leave the stheal, also it can fail but it does not leave like fault.

**Steps to reproduce**:

1. I put on stealth
2. I use distract, then I get closer I put ambush
3. the ambush does not apply or leave failure or take away the stealh without applying the ambush

**Client version**: 
1.12.1
**Commit hash**: 
   b339a414b6f8a51e86199efab226e4171c57ae10
**Operating system**: 
   windows 10

**Comment by heyiamsven** [comment]
Can confirm this behaviour. As GM it works fine, because you don't pull aggro, but without GM the mob aggro's you without the spell getting performed.

**Comment by ratkosrb** [comment]
It should work now -> https://github.com/vmangos/core/commit/14e2ad5749dfa9a8bef14af4c6877aa5be3227c8

**Comment by mako-taco** [comment]
there's a similar issue with rogues. should this fix also apply to them?

**Comment by ratkosrb** [comment]
Make sure you are using the latest revision. Ambush should no longer take you out of stealth without actually casting the ability.
