### ISSUE TITLE
[Quest] Quest 4021 Counterattacks

### ISSUE THREAD

**Issue by coolzoom** [vmangos/core#196]
**Current behavior**: 
Accept the quest and kill the Kolkar for a while, their Leader Warlord Krom'zar should appear, but Warlord Krom'zar won't appear so the quest couldt be finished.

Quest id : 4021 Counterattacks
Creature: 9456  Warlord Krom'zar(EventAI + script npc_warlord_kromzar)

**Expected behavior**: 
Warlord Warlord Krom'zar should appear
**Steps to reproduce**:

1. 
2. 
3. 

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**:

**Comment by ratkosrb** [comment]
Cannot reproduce. I just did the quest without any issue.
![WoWScrnShot_052419_161736](https://user-images.githubusercontent.com/35845488/58330476-99ce8a00-7e3f-11e9-84e5-22a9f9ab0e5f.jpg)

He spawned once I killed a bunch of Kolkar.

**Comment by coolzoom** [comment]
ok let me do some more test, probably related to my database

**Comment by coolzoom** [comment]
comments: found the issue, my MaxCreatureSummonLimit was 20, so it stopped summon when reach 20
