### ISSUE TITLE
🐛 [Bug] Chat problem

### ISSUE THREAD

**Issue by ghost** [vmangos/core#1964]
whisper another player ID-realmname ,cant find the player

**Comment by ghost** [comment]
![Uploading 5V(5~AN@8}KF2EL7{}(~I5Y.png…]()

**Comment by ratkosrb** [comment]
We don't support cross realm, you should not include the realm name when whispering.

**Comment by ghost** [comment]
> We don't support cross realm, you should not include the realm name when whispering.

got it
