### ISSUE TITLE
The quest does not work and problems in the water

### ISSUE THREAD

**Issue by Friwa28** [vmangos/core#201]
1) Quest does not work https://ru.wowhead.com/quest=3861/куд-кудаааа
can take Quest, can not be completed

2) in the water, press the jump button, and he will jump. 
I think so should not be ;D

**Client version**: 
1.12
**Commit hash**: 
full
**Operating system**: 
debian 9

**Comment by alexkulya** [comment]
1. I can't write anything yet.

2. It must be. These are the features of a classic client.
[Video link](https://www.youtube.com/watch?v=FaV6oAteJGI&feature=youtu.be&t=6894#t=40m51s)

**Comment by ratkosrb** [comment]
Invalid report. Both are working as intended.
