### ISSUE TITLE
🐛 [Bug] NPC Rory 11285 missing gossip text

### ISSUE THREAD

**Issue by Daribon** [vmangos/core#2041]
## 🐛 Bug report

The NPC Rory in Caer Darrow is currently missing his gossip text.
![nomacs_iipfMOj0qm](https://github.com/vmangos/core/assets/6137576/116a5f8e-98ae-4f0a-90d1-72a24a759343)

### Expected behavior

Should have the following gossip text:
- They don't realize that they're dead, $r. They are cursed to relive the last memory they had before the town was eaten alive from the inside out. Most of them, anyway. Some were less fortunate.$B$BYou thought the Scourge did this? The Scourge did not yet exist and if they had, we would have at least put up a damned fight.$B$BNo, this was the result of a plague that came out of Scholomance and ravaged the town. It was horrifying and devastating. None survived.$B$BNow leave me to my sorrows.

I have the text sniffed. It's not in mass parse since I've forgotten about the sniff for 2+ years now.

### Steps to reproduce

1. .go creature 300353
2. .add 13544
3. Talk to Rory.
4. Profit

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  https://github.com/vmangos/core/commit/a8c8860403acda2c7c5044144fa6b9495712d73e

OS Client: Windows 10 Pro N 10.0.22621.1413
OS Server: Windows 10 Pro N 10.0.22621.1413

### Crashlog

- None

**Comment by NickTyrer** [comment]
He has the gossip for me

**Comment by Daribon** [comment]
> He has the gossip for me

Cleaned cache and now works, how weird. I haven't spoken to the NPC previously.

**Comment by NickTyrer** [comment]
Yeh, I respawned all of  Caer Darrow from the sniffs. Thought I had added that gossip.
