### ISSUE TITLE
Poison cleansing totem cleansing Itch in AQ20

### ISSUE THREAD

**Issue by n3veruary** [vmangos/core#205]
**Current behavior**: 
Poison cleansing totem automatically cleanses Itch, and does not allow Itch to apply its poison debuff which is cleansable by the totem.

**Expected behavior**: 
https://vanilla-twinhead.twinstar.cz/?spell=8166 -- Totem is expected to cleanse one **poison** effect per five second interval, with possible failures as indicated by tooltip.
https://vanilla-twinhead.twinstar.cz/?spell=25185 -- Itch turns into Hive'Zara Catalyst which is dispellable by Poison Cleansing Totem under normal conditions.

**Steps to reproduce**:
https://www.youtube.com/watch?v=QxymiLfxG_c

1. Go to any mob that applies Itch
2. Put down a poison cleansing totem, start combat
3. Itch effect is cleansed on proc, poison debuff never applies

**Client version**: 
1.12.1 build 5875
**Commit hash**: 
Brotalnia's repack v14 -- unable to retrieve commit hash but have not made updates to core.
**Operating system**: 
Windows

**Comment by snuffysasa** [comment]
I am confused between what the difference is between the expected behavior and the current behavior.

Could you explain them both again carefully?

Are you saying that the itch debuff is not supposed to be dispelled by the totem? however the poison that it turns into is something that the totem should dispell?

**Comment by n3veruary** [comment]
@snuffysasa your understanding is exactly correct. Itch itself is not a poison, but Hive'Zara catalyst is.

**Comment by snuffysasa** [comment]
I'll right! I'll give fixing this a shot tonight!

Side thought, I'm amazed that you discovered a glitch as deep as this.  I am wondering were you purposely going through areas and spells searching for glitches, or were you just playing the game for fun and encountered this issue.

**Comment by snuffysasa** [comment]
I explored the issue a little bit and have made a temp fix here:
https://github.com/snuffysasa/core/tree/poisonCleansingTotemTempFix

However, when I have time possibly this weekend I'll explore the root cause of this issue and see if there is a better fix.

**Comment by ratkosrb** [comment]
The spell data was modified for some reason and the Itch debuff was made dispelable.
