### ISSUE TITLE
"In Dreams" Quest bugged

### ISSUE THREAD

**Issue by heyiamsven** [vmangos/core#208]
**Current behavior**: 
Taelan Fordring fights in the end against Grand Inquisitor Isillen.
Unfortunately he isn't able to kill Isillen, Isillen gets stuck on 10% HP and the fight never ends

**Expected behavior**: 
Taelan Fordring fights in the end against Grand Inquisitor Isillen and kills him.

**Steps to reproduce**:

1. Do the pre Quest Chain
2. If you do "In dreams", don't remove the disguise and let Fordring do all the combat.

**Client version**: 
1.12.1

**Screenshot of behavior**:
https://abload.de/img/1hejvn.png

**Comment by ratkosrb** [comment]
Did this happen just once, or were you able to reproduce it again.

**Comment by heyiamsven** [comment]
> Did this happen just once, or were you able to reproduce it again.

It was every time I tested.
I will refresh my world db today, I will report back later if the issue is gone.

**Comment by heyiamsven** [comment]
Update:
After sanatizing the DB it works. I will close the issue
