### ISSUE TITLE
🐝 [Bug] Quest Dawn's Gambit incorrect quest text.

### ISSUE THREAD

**Issue by Daribon** [vmangos/core#2084]
## 🐛 Bug report

Both the OfferReward and RequestItems text for the quest Dawn's Gambit is currently incorrectly taken from the quest The Archivist:
![heidisql_9LeczBI7lQ](https://github.com/vmangos/core/assets/6137576/28782ba6-26a2-4234-a007-01d9d22bfe65)

The quest Dawn's Gambit currently has incorrect OfferReward text:
![WoW_ktYbK1bSk6](https://github.com/vmangos/core/assets/6137576/935ffde1-94ad-415a-99b8-27218525f075)

It also has incorrect RequestItems text:
Remember, $N - we must be tolerant yet rigid in our beliefs!

### Expected behavior

It should have the following text:
![image](https://github.com/vmangos/core/assets/6137576/256d6df7-d3bb-4338-83b6-54816ccad2f5)
Image is taken from this video from classic: https://youtu.be/xwwlLRuUqag?t=579
It matches what can be seen on wowhead: https://www.wowhead.com/classic/quest=4771/dawns-gambit

The quest OfferReward and RequestItems text is not sniffed.

### Steps to reproduce

1. .quest add 4771
2. .go creature Betina
3. Profit

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash: https://github.com/vmangos/core/commit/026ac142e41e22cd693c2e33684e5863493e69f1

OS Client: Windows 11 Pro N 10.0.22621.1413
OS Server: Windows 11 Pro N 10.0.22621.1413

### Crashlog

- None

**Comment by NickTyrer** [comment]
Closed here https://github.com/vmangos/core/pull/1970
