### ISSUE TITLE
🐛 [Bug] entry 13944 in gameobject_loot_template looks not correct, should be 176582

### ISSUE THREAD

**Issue by rogical** [vmangos/core#2096]
## 🐛 Bug report

entry 13944 in gameobject_loot_template looks not correct, should be 176582
![image](https://github.com/vmangos/core/assets/1172002/89117b72-f481-4738-8d79-3b436145038d)

https://www.wowhead.com/?object=176582

**Comment by NickTyrer** [comment]
`gameobject_loot_template` 13944  is assigned to `gameobject_template` 176582.
