### ISSUE TITLE
🐝 [Bug] Missing gameobject pool for Crossroads Supply Crates

### ISSUE THREAD

**Issue by Marcelo20XX** [vmangos/core#2099]
## 🐝 Bug report - Quest
Gameobject 175708, Crossroad Supply Crates fail to spawn in the world due to an incorrect pool

### Expected behavior
Gameobject should appear in one of eight places

### Steps to reproduce

- .quest add 5041
- .tel crossroads
- run to Razormane Camps
- .go object 175708
- object not found in the world

### Version & Environment

  Client Version:
  - 1.12.1.5875

Commit Hash:  
8353ba5fe1c52d3ecda5aab26db0b9cabb130328

  Operating System:
  - Win XX

**Comment by NickTyrer** [comment]
I added the pools in a later commit https://github.com/vmangos/core/commit/911166efd2bebba3a73dab0e50343ad309abefae#diff-0cfc48d9446538e90eec4994f1f73d42be8566a33b79afecfec18ed8d1954c94R139 .

**Comment by NickTyrer** [comment]
Closed in #2100
