### ISSUE TITLE
🐛 [Bug]

### ISSUE THREAD

**Issue by cpevors** [vmangos/core#2102]
## 🐛 Bug report
When migrating the latest batch of commits, I received a slew of errors. Those errors can be seen in the error log attached. I am utterly unable to start my server. I have tried dropping and rebuilding all of my databases, and I have tried using the db dump sql files off the core's github page, to no avail. My server instantly crashes when I launch either/both realmd and mangosd.

[errors.txt](https://github.com/vmangos/core/files/12089878/errors.txt)

### Expected behavior
I shouldn't receive errors when loading the commits, and my server shouldn't instantly crash.

### Steps to reproduce

1. Pull down the latest commits from http://github.com/vmangos/core
2. Run the merge.bat file to generate new characters_db_updates, logon_db_updates, logs_db_updates, and world_db_updates SQL files.
3. Load the world_db_updates SQL file into the mangos database.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: Windows 11 64-bit
OS Server: 

### Crashlog

- None

**Comment by Marcelo20XX** [comment]
Didn't have this issue myself and I rebuilt the database from scratch today, maybe something on your side? First import the world_full_14_june_2021.sql then merge the migrations on the sql folder and import them...

**Comment by cpevors** [comment]
I’ve very certainly done that. Issues persist. I’ll hopefully figure something out.

**Comment by TuriansNotBad** [comment]
I've had this problem when trying to merge all of the migrations at once. It worked for me to only merge a part of the migrations at a time.

**Comment by Marcelo20XX** [comment]
Did you manually dropped your world database before running the queries?

**Comment by cpevors** [comment]
I dropped my databases. I created new databases. I loaded the SQL files against their respective databases. For the mangos database, I started with brotalnia’s world database from July 2021 before I ran the world SQL file that was spit out from merge.bat. 

I have created and maintained a VMaNGOS server for a decent while now, so the ability to create and maintain one hasn’t been an issue until HeidiSQL started spitting out the errors indicated in the attached file. Considering a fair few of the errors indicate, for instance, syntax errors, over which I have no agency, I’m not sure that this is entirely user error.

**Comment by cpevors** [comment]
> I've had this problem when trying to merge all of the migrations at once. It worked for me to only merge a part of the migrations at a time.

I’ll give this a try. Thank you.

**Comment by cpevors** [comment]
> I've had this problem when trying to merge all of the migrations at once. It worked for me to only merge a part of the migrations at a time.

This actually seemed to work for me. A bit odd that this is the first and only time I’ve needed to take this approach, but good to know.
