### ISSUE TITLE
🐛 [Bug] Lost drop list at the NPC: 4494

### ISSUE THREAD

**Issue by gajet5** [vmangos/core#2103]
## 🐛 Bug report
I didn't find a drop list at the NPC.

### Expected behavior
The NPC drop list is in the database.

### Steps to reproduce
1. Go to DB
2. Open: item_loot_template
3. SELECT * FROM `wow_mangos`.`item_loot_template` WHERE entry=4494;
4. Profit

### Version & Environment
Client Version: 1.12.1.5875

Commit Hash:  No

OS Client: Win 11
OS Server: Ubuntu 20.04

### Crashlog
- None

![image](https://github.com/vmangos/core/assets/3825412/4210b101-0726-49aa-9305-7e262b0caff9)

**Comment by cpevors** [comment]
I think you have it a bit backwards. 

You can find this NPC’s various drops/loot table in creature_loot_template. 

If the creature_loot_template denotes a negative value in mincountorRef, you can then consult the item_loot_template.

**Comment by rogical** [comment]
https://github.com/cmangos/issues/wiki/loot_template  complete description of loot logic

**Comment by gajet5** [comment]
Thank you very much, my mistake.
