### ISSUE TITLE
🐛 [Bug] NPC teleporting up in air after reaching new waypoint.

### ISSUE THREAD

**Issue by Daribon** [vmangos/core#2116]
## 🐛 Bug report

Currently NPCs have a high possibility to teleport around 3 yards up in the air when a new waypoint is reached.
It affects many NPC that uses waypoints and happens on both .wmo objects and normal terrain.

It looks like it happens more often when terrain is somewhat steep.

### Expected behavior

NPCs should not teleport 3 yards up in the air when a new waypoint is reached.

### Steps to reproduce

1.  .go creature 42895 or  .go creature 4247 or just .tele stormwind and find any NPC with waypoints.
2. Follow it.
3. See NPC teleport into the air.
4. Profit

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  https://github.com/vmangos/core/commit/2ed34467bcde8a0702981d9d212e49000bda7cdc

OS Client: Windows 11 Pro N 10.0.22621.1413
OS Server: Windows 11 Pro N 10.0.22621.1413

### Crashlog

- None

**Comment by Daribon** [comment]
Does not happen on 1.14.1 when running hermesproxy.

**Comment by Gamemechanicwow** [comment]
I can't reproduce it. Followed 42895 and 4247 for 3 loops.

Latest revision. Patch 10.

**Comment by Daribon** [comment]
Client bug with 1.12.1 client when running high FPS. 
The higher the FPS the more more likely for the glitch to happen. To fix this, make sure to run vsync or limit the framerate to max 144 fps.
