### ISSUE TITLE
Strange speed behavior

### ISSUE THREAD

**Issue by caicaicai** [vmangos/core#212]
**Current behavior**: 
When I ride the mount into a instance, my speed will  not be  normal（Expected the speed is 1x 
 with out mount）, but 2 times faster now with out any mount. with this Strange state，Use a mount I will be kickout ~~with exception ：
 MovmentHandler.cpp  line442
 sLog.outError("WorldSession::HandleForceSpeedChangeAck: Unknown move type opcode: %u", opcode);~~

**Expected behavior**: 
Normal access in to the instance, normal speed
**Steps to reproduce**:

1. use commit hash b6f4a2574bdd9b98d45d442409fdbdbdbbad7897 build.
2. Use a mount ,Try to enter the instance（ragefire-chasm）.
3. You will get a strange speed.

**Client version**: 
1.12
**Commit hash**: 
b6f4a2574bdd9b98d45d442409fdbdbdbbad7897
**Operating system**: 
win7

**Comment by ratkosrb** [comment]
Can you tell me the opcode number it mentions in the console? You should see a number where the %u is at the end of the message.

**Comment by caicaicai** [comment]
<img width="652" alt="WechatIMG1" src="https://user-images.githubusercontent.com/3754009/59585548-54863b00-9113-11e9-9f60-5bb947ce9af2.png">
Maybe I got the wrong code location。

**Comment by caicaicai** [comment]
I just upload my test video to youtu.
https://youtu.be/QTPfU9NMGXA

I found that this problem maybe does not occur with GM mode.

**Comment by caicaicai** [comment]
It's easy to reproduce this bug, non-GM mode, riding into the instance.

**Comment by Kittnz** [comment]
Maybe we should not kick the player but try to set new speed again https://github.com/vmangos/core/blob/development/src/game/Handlers/MovementHandler.cpp#L481

**Comment by ratkosrb** [comment]
The data sent in the ACK should be about the change we are expecting, and have the correct counter. Not sure what you mean exactly by "set a new speed", the speed is set after we verify the ACK, which is what is done in that if statement.

**Comment by ratkosrb** [comment]
I found why it happens. Player gets teleported too soon after being dismounted, and has no time to respond to the speed change. Going to fix it soon.

**Comment by caicaicai** [comment]
Agree with your guess, if (the dismount and the teleporte) this two action  is Very close,then the speed will be unable to correct.
