### ISSUE TITLE
Frequent disconnects during onyxia

### ISSUE THREAD

**Issue by mako-taco** [vmangos/core#214]
**Current behavior**: 
about 10 of the 25 players doing onyxia would be D/Ced whenever they were hit with a tail whip, or had their stats reset via `.reset stats`. Perhaps caused by #197?

**Expected behavior**: 
no disconnects

**Steps to reproduce**:

1. Start a raid with a bunch of players on the 1.12 client (5875 or whatever) 
2. Engage onyxia
3. Have them eat tail whips

**Client version**: 
1.12

**Commit hash**: 
5166b62b5cc86db1b8f72ef398b30e03b6382dd0

**Operating system**: 
Windows 10

**Comment by mako-taco** [comment]
Our tank also experienced DCs upon being knocked back by the wing buffet.

**Comment by ratkosrb** [comment]
Is it only specific people who get disconnected when hit by Tail Swipe, or does it happen to everyone hit by it?

**Comment by mako-taco** [comment]
specific people, but consistently

**Comment by ratkosrb** [comment]
What error does it print in the console when they get disconnected? Also is it possible that they have a modified Wow.exe? You can compare files on windows using the "fc /b Wow1.exe Wow2.exe" command, to see if their exe is different than yours.

**Comment by mako-taco** [comment]
the server is running on a guildmates machine that I don't have SSH access too. I'll post logs tomorrow.

**Comment by heyiamsven** [comment]
I reported similar behavior on discord. With newest pull's the server did DC Clients while they moving with their char on my server, specially if movement speed gets changed. I had to rollback to my old core rev. in order to fix it.

Server console didn't output much info, so I can't reproduce now and get any log of it as it's already overwritten.

**Comment by mako-taco** [comment]
This appears once (only):
```
2019-06-17 05:18:42 ERROR:WorldSocket::handle_input_header: client xxx.xxx.xxx.xxx sent malformed packet size = 5635 , cmd = 25755649
```

And this has dozens of occurrences, always for these three NPCs though:
```
2019-06-17 00:06:23 ERROR:MoveSplineInitArgs::Validate: expression 'velocity > 0.f' failed for Creature (Entry: 20008 Guid: 2000026)
2019-06-17 00:06:23 ERROR:MoveSplineInitArgs::Validate: expression 'velocity > 0.f' failed for Creature (Entry: 90029 Guid: 2000030)
2019-06-17 00:06:23 ERROR:MoveSplineInitArgs::Validate: expression 'velocity > 0.f' failed for Creature (Entry: 90028 Guid: 2000029)
```

Those npcs are GM island helpers:
```
+-------+-------------+
| entry | name        |
+-------+-------------+
| 20008 | Teleportman |
| 90028 | Enchants 2  |
| 90029 | Professions |
+-------+-------------+
```

**Comment by mako-taco** [comment]
I confirmed after reverting #197 that everything worked as expected.

**Comment by ratkosrb** [comment]
That much is obvious, since its an intentional disconnect by the server for incorrect ACK data being returned. The question is why are those clients sending incorrect data.

**Comment by ratkosrb** [comment]
It should be fixed if you running without anticheat after https://github.com/vmangos/core/commit/7f7160b2b746673934d9bc033aafee620bd6be44

**Comment by mako-taco** [comment]
Thanks, I'll confirm soon.

**Comment by mako-taco** [comment]
looks good!
