### ISSUE TITLE
🐛 [Bug] High Perch Soarer slow movement speed

### ISSUE THREAD

**Issue by Marcelo20XX** [vmangos/core#2152]
## 🐛 Bug report
High Perch Soarer guid 21707 and 21708 fly at a slower speed than they should  

### Expected behavior
They both fly at nearly the triple speed than its current speed on official servers

### Steps to reproduce
1. .go creature 21707
2. watch them fly on its waypoint paths
3. ...

### Version
  Client Version:
  - 1.12.1.5875

**Comment by NickTyrer** [comment]
Those creatures don't exist there in classic. There is just one that has waypoints through the area.

**Comment by NickTyrer** [comment]
Closed in https://github.com/vmangos/core/pull/1970
