### ISSUE TITLE
🐛 [Bug] Block while shield sheathed.

### ISSUE THREAD

**Issue by Daribon** [vmangos/core#2157]
## 🐛 Bug report

You can currently block with shield sheathed.

### Expected behavior

On classic you have to have shield unsheathed, if you want to block a hit.
Any hit while your shield is not in your hand, will not be possible to block on classic.

The only thing I have from vanilla is from the spell attribute of the block spell in 1.12.1:
SPELL_ATTR_DO_NOT_SHEATH
![QSW_0ECwvCnivV](https://github.com/vmangos/core/assets/6137576/382ff532-8417-4be2-9ec9-4f39b7039912)
It only exists in SpellDefines.h but nowhere else.

### Steps to reproduce

1. Have your shield sheathed.
2. Go near any enemy mob.
3. Hits will be blocked while shield is sheathed.
4. Profit

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  https://github.com/vmangos/core/commit/4e9b446e9d715cb5c48b59116f42b6bbf70e9ed0

OS Client: Windows 11 Pro N 10.0.22621.1413
OS Server: Windows 11 Pro N 10.0.22621.1413

### Crashlog

- None

**Comment by Wall-core** [comment]
this should actually replace the code that prevents blocking AND parrying while casting, mounted, etc. 
The spell being cast should determine whether or not the player is able to block or parry while casting via the automatic sheathing of the weapon/shield. Some spells with cast time do not prevent blocking as they do not sheathe weapon or shield.

**Comment by rene-duchamp** [comment]
https://warcraft.wiki.gg/wiki/Patch_2.1.0_(undocumented_changes)
You can now block attacks while your shield is in the sheathed position. Previously, Warriors, Shamans and Paladins were vulnerable while using instant-cast abilities that caused their shield to momentarily appear on their back.

**Comment by ratkosrb** [comment]
https://github.com/user-attachments/assets/dec09aaf-66d3-48e5-bf41-64e4504989fe

I can't reproduce it on classic. I don't have my shield or melee weapon drawn yet I can block and parry attacks.

**Comment by ratkosrb** [comment]
We'll assume the TBC patch notes to be true, and if someone finds video proof from vanilla of blocking without having shield drawn we'll revert it.

**Comment by ratkosrb** [comment]
Okay I performed a better test and I understood how it works. It's specifically in unarmed sheath state that you can't block. In ranged state you can still block. Also it does not affect parry.

https://github.com/user-attachments/assets/9a93b54c-1110-48b9-aced-1a131db01229

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/707c9c9ccb1d786159e0e55f157316323fdef158
