### ISSUE TITLE
🐞 [Bug] Touch of Weakness incorrect threat.

### ISSUE THREAD

**Issue by Daribon** [vmangos/core#2163]
## 🐞 Bug report - Spell

Touch of Weakness currently does no threat on when used. The threat caused by its proc damage is incorrect.

### Expected behavior

Touch of Weakness should cause threat when you use the ability.
Touch of Weakness should do bonus threat on proc.

Here is the correct threat for casting the spell:
r6: 60
r5: 50
r4: 40
r3: 30
r2: 20
r1: 10

Here is a fix for the cast threat:
```-- Touch of Weakness R1
INSERT INTO `spell_threat` (`entry`, `Threat`, `multiplier`, `ap_bonus`) VALUES (2652, 10, 0, 0);
-- Touch of Weakness R2
INSERT INTO `spell_threat` (`entry`, `Threat`, `multiplier`, `ap_bonus`) VALUES (19261, 20, 0, 0);
-- Touch of Weakness R3
INSERT INTO `spell_threat` (`entry`, `Threat`, `multiplier`, `ap_bonus`) VALUES (19262, 30, 0, 0);
-- Touch of Weakness R4
INSERT INTO `spell_threat` (`entry`, `Threat`, `multiplier`, `ap_bonus`) VALUES (19264, 40, 0, 0);
-- Touch of Weakness R5
INSERT INTO `spell_threat` (`entry`, `Threat`, `multiplier`, `ap_bonus`) VALUES (19265, 50, 0, 0);
-- Touch of Weakness R6
INSERT INTO `spell_threat` (`entry`, `Threat`, `multiplier`, `ap_bonus`) VALUES (19266, 60, 0, 0);
```

The problem is that the proc threat is incorrect and I can't find a way to fix it through the spell_threat table.

Every Touch of Weakness uses the same spell with spellid: 28598.
However, every rank should cause different threat when procced.
The threat proc should be threat damage + 2x the bonus threat of the cast.

For example a rank 6 proc if it dealt 111 damage would cause 111 threat + 120 bonus threat, resulting in 231 threat.
![WowClassicT_X1yErVbUk8](https://github.com/vmangos/core/assets/6137576/984e8a28-e2b3-4a47-9972-e3092703188b)
![WowClassicT_KtkjfzH4Vf](https://github.com/vmangos/core/assets/6137576/2d5cff8b-bba5-4ea7-9901-df60faed9b7e)

Same thing goes with for example r1 dealing 56 damage. It would cause 56 damage threat + 20 bonus threat, resulting in 76 threat.
![WowClassicT_R9bqJgAse3](https://github.com/vmangos/core/assets/6137576/84dfaf89-d24f-45aa-ad7c-d9d341720822)
![WowClassicT_vjVBIELeck](https://github.com/vmangos/core/assets/6137576/1ddc8857-374c-4949-a35c-752af28de3eb)

### Steps to reproduce

1. Create a priest
2. .learn 19266
3. Walk near enemy mob
4. Cast Touch of Weakness
5. .list threat

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  https://github.com/vmangos/core/commit/b6eef3471c09a487941e6dc664accab8422ca844

OS Client: Windows 11 Pro N 10.0.22621.1413
OS Server: Windows 11 Pro N 10.0.22621.1413

### Crashlog

- None

**Comment by ratkosrb** [comment]
Can't you assign the threat on proc to the spells triggered by the dummy spell that all the ranks use?

https://github.com/vmangos/core/blob/development/src/game/Spells/SpellEffects.cpp#L1822

Rank 1 - 2943
Rank 2 - 19249
Rank 3 - 19251
Rank 4 - 19252
Rank 5 - 19253
Rank 6 - 19254

**Comment by Daribon** [comment]
> Can't you assign the threat on proc to the spells triggered by the dummy spell that all the ranks use?
> 
> https://github.com/vmangos/core/blob/development/src/game/Spells/SpellEffects.cpp#L1822
> 
> Rank 1 - 2943 Rank 2 - 19249 Rank 3 - 19251 Rank 4 - 19252 Rank 5 - 19253 Rank 6 - 19254

Yes, that worked. Thanks. 

I will PR it soonish.
