### ISSUE TITLE
🐛 [Bug] There is no slime debuff standing in the green liquid of Naxxramas

### ISSUE THREAD

**Issue by leechunlung** [vmangos/core#2175]
Naxxramas slime debuff cannot take effect.

### Version & Environment

<!--
  Client Version:
  - 1.12.1.5875

<!--
  Operating System:
  - Win XX

**Comment by coolzoom** [comment]
check this: https://github.com/vmangos/core/commit/fb91e33eb92d1aa34c86caff83a0fc73c6141ac0
and here: https://github.com/vmangos/core/blob/4264cded0dc90b1fed5370ffcf30c88451072cf7/src/game/Objects/Player.cpp#L1442

big changes always have cons and pros
