### ISSUE TITLE
🦂 [Bug] Sapphiron no  BOSS animation  and Kel'Thuzad do not summon creatures of Naxxramas

### ISSUE THREAD

**Issue by wthslw001** [vmangos/core#2184]
## 🦂 Bug report - Dungeon

Sapphiron no  BOSS animation
Kel'Thuzad  in P1  do not summon creatures

### Version & Environment

Client Version: 1.12.1.5875

**Comment by Vanndar** [comment]
I can confirm Sapphiron no animation but KT P1 was already fixed
