### ISSUE TITLE
🐝 [Bug] Lothos Riftwaker can not send player into MC

### ISSUE THREAD

**Issue by rogical** [vmangos/core#2185]
### Steps to reproduce

1. set patch 1.4 or 1.5 
2. .tele moltencore
3. complete quest Attunement to the Core
4. open dialog from Lothos Riftwaker
5. click dialog, nothing happend  (single player or in group both same)
6. however, player still can jump the window into MC

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  

OS Client: win 10
OS Server: unbuntu 

### Crashlog

- None

**Comment by cpevors** [comment]
I actually cannot reproduce on the Human and Undead Level 60 characters I just created.

**Comment by ratkosrb** [comment]
Lothos Riftwaker's gossip option was added in Patch 1.11.

**Comment by ratkosrb** [comment]
If you don't believe me, look at how high the broadcast text Id for the gossip option is, and what other texts have an Id near it.
![Untitled](https://github.com/vmangos/core/assets/35845488/6f432c53-9df6-4428-a585-d72b628f9225)

These are all outdoor pvp texts, for the towers in eastern plaguelands, and the silithus one, both added in patch 1.12.0.
