### ISSUE TITLE
🐛 [Bug] Skeletal Horror missing Terrify ability

### ISSUE THREAD

**Issue by LeFroid** [vmangos/core#2195]
## 🐛 Bug report

The creature [Skeletal Horror](https://www.wowhead.com/classic/npc=202/skeletal-horror) should cast [Terrify](https://www.wowhead.com/classic/spell=7399/terrify) during combat. It has no abilities currently.

### Expected behavior

Looking at Trinity, the NPC should cast Terrify initially between 5-8 seconds, then every 9-13 seconds

### Steps to reproduce

1. .go creature 5162 
2. Engage in combat

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  f840413d743d41c4a12578ca54a44c444160fb03

OS Client: Linux
OS Server:  Linux

### Crashlog

- None

**Comment by NickTyrer** [comment]
Closed here #1970
