### ISSUE TITLE
🐛 [Bug]Corpse still can move or attack player

### ISSUE THREAD

**Issue by rogical** [vmangos/core#2198]
## 🐛 Bug report

A lot players reported, Corpse still attack players.

### Version & Environment

Client Version: 
1.12.1

OS Server: Ubuntu

### Crashlog

- None

**Comment by rogical** [comment]
https://github.com/vmangos/core/assets/1172002/fb74dbfc-01f0-4484-a492-5d12de4d2479

**Comment by rogical** [comment]
https://youtu.be/ujqb5GuLqm8

**Comment by rogical** [comment]
![QQ图片20230919194137](https://github.com/vmangos/core/assets/1172002/1cce0c3b-0da5-43a5-96d0-c574c709f074)

**Comment by rogical** [comment]
a player just kiilled this mob, but it still attacks player.

after player leave combat, the corpse immediately revived, but can not be attacked.

**Comment by rogical** [comment]
![QQ截图20230919194748](https://github.com/vmangos/core/assets/1172002/6588b289-e0d3-4486-94f5-aff648471060)

**Comment by rogical** [comment]
Wall:
it's a bug
the mobs isn't dead, it's due to a weird packet issue and almost certainly has nothing to do with the core
the npc is visually not displaying correctly on the client; it's an extremely rare issue and impossible to duplicate but I've seen it happen before
afaik when the server is sending the DeathState packet, it's lost in transaction and the client doesn't change the corpse state of the creature despite it being alive
If they were to reboot their client, it would solve it

**Comment by ratkosrb** [comment]
In the "npc info" screenshot it says current health is 0. But if creature is alive why doesn't it regen the health back to full. I tested setting an alive creature's health to 0 directly, and it just regens it back to full.

**Comment by Gamemechanicwow** [comment]
Current spawntime is shown as 3m 37s - so I guess that means the server knows this creature is dead.

I have no idea how to recreate this. I have never seen it myself.

**Comment by Wall-core** [comment]
Use wireshark and intercept/block the packet that is sending the change to DeathState, I can almost guarantee it'll cause this.

**Comment by Gamemechanicwow** [comment]
I guess it would look the same for the player. 

But the .npc info command wouldn't show an NPC with 0 hp and an active respawn timer if the creature is alive.

**Comment by rogical** [comment]
npc info command i may need to double confirm, as at that time there's a lot corpse.

**Comment by rogical** [comment]
player confirmed restart client doesn't fix issue. and other player can see same issue on the same creature.

the corpse can only be killed by aoe spells

**Comment by rogical** [comment]
latest observation:

can not kill the corpse with .die command

https://youtu.be/yQIhpv8Fpus

.npc info
![image](https://github.com/vmangos/core/assets/1172002/2bfc37f3-c223-4ea1-a70f-5b92739db5f8)

**Comment by rogical** [comment]
https://youtu.be/XDqE2BnqoyE

**Comment by rogical** [comment]
my dev server works good, prod server has this issue for this creature 10052

**Comment by rogical** [comment]
after server rebooted, the creature turns out good. it looks randomly.

**Comment by rogical** [comment]
![QQ截图20231105130713](https://github.com/vmangos/core/assets/1172002/363d1075-a6d2-4883-a58f-8f131a51c1ad)
after server running several days, issue come again

**Comment by rogical** [comment]
this creature it is very high chance to regenerate issue. after server reboot, and run a few days, issue repeated for this creature.

**Comment by Gamemechanicwow** [comment]
just to make absolutely sure... This is a clean vmangos installation without any modifications? Or are you using a different fork - like eluna?

**Comment by ratkosrb** [comment]
He is using a fork.

**Comment by Gamemechanicwow** [comment]
That was my understanding. Just wanted to be sure - and get the info on the tracker - so ppl don't spend time looking for a bug that belongs on a different fork.

**Comment by Wall-core** [comment]
This can happen on clean mangos but you have to break the respawn time on creatures in DB and have it recache. It happens rarely when I'm editing the DB respawn time for creatures on live servers, eventually they break and can be seen moving about dead. I think it's client error, maybe data is being packed that client is handling badly. I last witnessed this a month ago after editing rare spawns; reloading the mangos.conf with rare spawn corpse timers changed caused it. A player messaged me about the rare outside BRD sliding around dead, I went and confirmed myself after zoning while it was alive that this bug occurred.
