### ISSUE TITLE
🐝 [Bug]

### ISSUE THREAD

**Issue by SalBuddy10** [vmangos/core#2199]
## 🐝 Bug report - Quest

Looks to be a typo here. Not sure what correct wording is.

![image](https://github.com/vmangos/core/assets/145512415/c86c9100-65aa-4ab0-a947-82eaaa5321f9)

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by Wall-core** [comment]
The text might have a typo as blizzlike, have to confirm if this is sniffed

**Comment by ratkosrb** [comment]
All broadcast texts are sniffed. Typos there are blizzlike and must not be changed.
