### ISSUE TITLE
Warlord Goretooth gossip menu

### ISSUE THREAD

**Issue by alexkulya** [vmangos/core#221]
Warlord Goretooth (ID: 9077) - added gossip menu

<pre>
-- ID: 9077 - gossip menu
UPDATE `creature_template` SET `gossip_menu_id` = 2884 WHERE `entry` = 9077;
DELETE FROM `npc_gossip` WHERE `npc_guid` = 6878 AND `textid` = 3560;

DELETE FROM `gossip_menu` WHERE `entry` = 2884 AND `text_id` = 3560;
DELETE FROM `gossip_menu` WHERE `entry` = 2885 AND `text_id` = 3561;
DELETE FROM `gossip_menu` WHERE `entry` = 2886 AND `text_id` = 3562;
DELETE FROM `gossip_menu` WHERE `entry` = 2887 AND `text_id` = 3563;
DELETE FROM `gossip_menu` WHERE `entry` = 2888 AND `text_id` = 3564;
DELETE FROM `gossip_menu` WHERE `entry` = 2889 AND `text_id` = 3565;
INSERT INTO `gossip_menu` (`entry`, `text_id`) VALUES
(2884, 3560),
(2885, 3561),
(2886, 3562),
(2887, 3563),
(2888, 3564),
(2889, 3565);

DELETE FROM `gossip_menu_option` WHERE `menu_id` IN (2884, 2885, 2886, 2887, 2888, 2889) AND `id` = 0;
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `OptionBroadcastTextID`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_script_id`, `condition_id`) VALUES
(2884, 0, 0, "What roles?", 5971, 1, 1, 2885, 0, 61002),
(2885, 0, 0, "Dreams?", 5973, 1, 1, 2886, 0, 0),
(2886, 0, 0, "I pray for such things.", 5975, 1, 1, 2887, 0, 0),
(2887, 0, 0, "I do not deserve such praise, Warlord Goretooth.", 5977, 1, 1, 2888, 0, 0),
(2888, 0, 0, "Sir! Until my body ceases to function!", 5979, 1, 1, 2889, 0, 0),
(2889, 0, 0, "Yes, sir. Thank you, sir!", 5981, 1, 1, -1, 2889, 0);

DELETE FROM `gossip_scripts` WHERE `id` = 2889;
INSERT INTO `gossip_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `target_param1`, `target_param2`, `target_type`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `condition_id`, `comments`) VALUES
(2889, 0, 15, 16548, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "Cast Goretooth's Orders");

DELETE FROM `conditions` WHERE `condition_entry` IN (61000, 61001, 61002);
INSERT INTO `conditions` (`condition_entry`, `type`, `value1`, `value2`, `value3`, `value4`, `flags`) VALUES
(61000, 9, 4903, 0, 0, 0, 1),
(61001, 2, 12563, 1, 0, 0, 1),
(61002, -1, 61000, 61001, 0, 0, 0);
</pre>

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/002cb8b2c434fc8503de4054d56f0d8b38810720
