### ISSUE TITLE
🦂 [Bug] Kel'Thuzad Animation

### ISSUE THREAD

**Issue by FireGolza1** [vmangos/core#2212]
## 🦂 Bug report - Dungeon

1. Kel'thuzad does not do the summon/frost animation as he does in wow classic once phase 1 starts. He is still in his idle animation as the phase progresses.

Demonstration of animation issue:
(0:24)
https://youtu.be/2IBdHZRUPNI

![image](https://github.com/vmangos/core/assets/146747725/ff73131e-bb6a-4f52-9f59-a43a7a1836fb)

### Expected behavior

(11:30:)
https://www.youtube.com/watch?v=uaF7Sw-THMs

(1:07, although you can barely see it:)
https://www.youtube.com/watch?v=6CNN_Cn2L2A

### Steps to reproduce

1. .gm on
3. .tele naxx
4. .go creature kel'thuzad
5. .gm off
6. stand on blue circle
7. ....
8. Profit

### Version & Environment

 Client Version:
  - 1.12.1.5875
  
   Operating System:
  - Win 11
<!-- 

<!--

**Comment by ratkosrb** [comment]
![WoWScrnShot_100223_211913](https://github.com/vmangos/core/assets/35845488/f298c1d8-db1a-4b5e-9dc4-2249ebc8118e)

I can't reproduce the issue. He does the channeling animation.

**Comment by FireGolza1** [comment]
Oh…. Perhaps this only breaks on the 1.14 client when used with Hermes (Apologies I didn’t know there would be a difference. I used the 1.14 client and assumed there would be no difference between it and 1.12) Is there any way to address this?

**Comment by FireGolza1** [comment]
Did you use the 1.12 client?

**Comment by ratkosrb** [comment]
Yes I used 1.12. VMaNGOS is a 1.12 emulator, and does not support 1.14. Report bug on Hermes repo if you are certain it only happens with 1.14.

**Comment by FireGolza1** [comment]
Ok thanks. Apologies for the confusion.
