### ISSUE TITLE
🐞 [Bug] The spells Starshards and Tranquility don't continue channeling animation effects after a few seconds

### ISSUE THREAD

**Issue by GoonBoiBarry** [vmangos/core#2214]
🐞 Bug report - Spell
When you cast either spell, the spell effect around your hands and the channeling sound effect both stop, despite the channel being unfinished. In addition, the tranquility rain effect stops too.

Expected behavior
The visual and sound effects should continue until the channel has finished, or been interrupted.

Steps to reproduce
1. .cheat powercost off
2. .cast 740 (tranquility rank 1) 
3. Witness the tranquility visuals and sound effects end before the channel has ended
4. Find a mob and .cast 10797 (starshards rank 1)
5. Witness the hand channel visuals and sound effects end before the channel has ended
6. Profit

Version & Environment

  Client Version:
  - 1.12.1.5875

OS Client: Windows 10
OS Server: Windows 10

**Comment by peacebringer** [comment]
Can confirm this bug report.

Here are 2 videos from both original vanilla and current classic era, that visual raining effects of druid tranquility spell should last as long as channeling time of that spell:

Original vanilla wow video from December 2006, tranquility spell starts from 3:58

https://www.youtube.com/watch?v=08M1EuTR7eY

Video from classic era realm

https://streamable.com/aj9sni
