### ISSUE TITLE
🐞 [Bug] Various channel spells also have channel animation issues and audio popping on recently fixed channels

### ISSUE THREAD

**Issue by GoonBoiBarry** [vmangos/core#2216]
🐞 Bug report - Spell
The following channel spells have no channel spell effect animations, or casting audio (sorry I neglected to check these in the previous post).
.Rain of Fire (id 5740)
.Blizzard (id 10)
.Hurricane (id 16914)
.Hellfire (id 1949)
.Mind Flay (id 15407)
.Volley (id 1510 appears to have no animation at all beyond the initial cast, supposed to keep shooting)

Unfortunately, it looks like the recent fixes to tranquility and starshards caused audio popping issues partway through the channel, possibly due to the method of looping. It seems like the channel sound is on a short loop after a certain point and when audio is cut together this way without sound waves lining up together, it creates this issue. I think that's what's happening, but I could be wrong. If I'm right, I assume there is an intended loop duration where the sound waves line up and the popping doesn't occur.

Expected behavior
The spells should have channel spell effect animations and sounds during their channels according to the 1.14 client.

Video showing volley animation at time 1:14
https://www.youtube.com/watch?v=hNropCkLb3c

Video showing blizzard channel animation and sound at time 0:25
https://www.youtube.com/watch?v=X8t-4J4R9Z4

The channel sounds should not have audio popping according to the 1.14 client.

Video to compare audio of Starshards, to the popping in current vmangos at time 16:24
https://www.youtube.com/watch?v=oHHglr15Nzw&t=984s

Steps to reproduce

1. .cheat powercost on
2. .cast spellid of any of the listed spells
3. Witness lack of spell channeling effect visual or sound effect
4. Mute game music and game ambience
5. .cast 740, or .cast 10797 on a mob
6. Listen to full channel for popping audio loop
7. Profit

Version & Environment

  Client Version:
  - 1.12.1.5875

Operating System:

OS Client: Win 10
OS Server: Win 10

**Comment by ratkosrb** [comment]
Do not link 1.14 videos as proof. The previously reported spells had perfectly working animations in 1.14 client on vmangos through HermesProxy, which means this is specific to 1.12 client, and not related to server. Link original vanilla videos of those spells and compare animation with what you see in video.

Regarding Blizzard here you can see his hands stop glowing after a few seconds:
https://www.youtube.com/watch?v=unusjpGt8bY
https://www.youtube.com/watch?v=amnkJn7Mop8
https://www.youtube.com/watch?v=eRFpF8bwrHw

Regarding audio issues, those are inevitable, as the duration of the visual does not match the duration of the sound. If you increase time before visual is resent to match the sound duration, you will have the visual constantly blinking on and off.

**Comment by ratkosrb** [comment]
```
Video showing volley animation at time 1:14
https://www.youtube.com/watch?v=hNropCkLb3c
```

This video is from 2009, that's Wrath of the Lich King, version 3.X. You cannot compare it with vanilla client. The bug with Tranquility did not happen with TBC client either, I tested it, meaning this is a difference in clients.

```
Video showing blizzard channel animation and sound at time 0:25
https://www.youtube.com/watch?v=X8t-4J4R9Z4
```
This is a video from 2022, again using a way newer client, which never had this issue to begin with.

```
Video to compare audio of Starshards, to the popping in current vmangos at time 16:24
https://www.youtube.com/watch?v=oHHglr15Nzw&t=984s
```
Again a video of new client from 2021.

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/assets/35845488/48365fea-9407-4897-84d4-f25750c5bc01

Here is a video of casting Blizzard on VMANGOS with the 1.14 client. You can see glowing hands visual remains during the whole cast, and does not disappear as with 1.12, demonstrating that this is a difference in how the clients work, and so footage from 1.14 does not prove anything, as it already works the same way with 1.14 client on vmangos.

**Comment by GoonBoiBarry** [comment]
Okay my bad, I didn't think about visual client distinctions. I can see based on the videos you showed me that channel spells seemed to work this way in vanilla clients. Clearly my last report was based on bad evidence. I will keep this in mind in future reports and test through hermesproxy if necessary. Sorry I misunderstood.
