### ISSUE TITLE
🐛 [Bug] Build Warning: warning: the use of `tmpnam' is dangerous, better use `mkstemp'

### ISSUE THREAD

**Issue by rogical** [vmangos/core#2222]
## 🐛 Bug report

[ 23%] Linking CXX static library libgame.a
[ 61%] Built target game
[ 99%] Built target scripts
[ 99%] Linking CXX executable mangosd
/usr/bin/ld: ../../dep/lualib/liblualib.a(loslib.c.o): in function `os_tmpname':
/home/rogical/vmangos/core/dep/lualib/loslib.c:108: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
### Version & Environment

Client Version: 

OS Server: Ubuntu

### Crashlog

- None

**Comment by ratkosrb** [comment]
```
core/dep/lualib/loslib.c
```
There is no such file. You are not using vmangos! Do not post issues with other projects here.
