### ISSUE TITLE
🐛 [Bug]honor rank

### ISSUE THREAD

**Issue by Soulyes** [vmangos/core#2223]
## 🐛 Bug report

Server needs to be restarted to perform honor rank calculations.
But I cann't restart ,Shutdown The MaGons,Cann't Do this.

Command: Server Restart  only Use Canncel.

OS Client: Win10
OS Server: Windows 2012R2

**Comment by Wall-core** [comment]
you can restart the server with the following command:
.server restart 60
This would restart the server in 60 seconds. Try that.

**Comment by Soulyes** [comment]
Thanks



--------------------------------------------------------
By 老钟
 
发件人： Wall
发送时间： 2023-10-14 14:27
收件人： vmangos/core
抄送： Soulyes; Author
主题： Re: [vmangos/core]  [Bug]honor rank (Issue #2223)
you can restart the server with the following command:
.server restart 60
This would restart the server in 60 seconds. Try that.
