### ISSUE TITLE
🐛 [Bug] Book of military rank looks broken

### ISSUE THREAD

**Issue by rogical** [vmangos/core#2224]
## 🐛 Bug report

see attachment
![QQ截图20231014093721](https://github.com/vmangos/core/assets/1172002/f5446269-a223-4462-9306-852cfaa2b1be)

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by Wall-core** [comment]
The chinese localization is different in the templates to other versions. They use HTML in the page. Can you try to fix the locales_page_text entry 2654 text_loc4 (chinese) column? @rogical

**Comment by rogical** [comment]
let me try, thanks!
