### ISSUE TITLE
🐛 [Bug]About recompilation，Something bug

### ISSUE THREAD

**Issue by Soulyes** [vmangos/core#2225]
## 🐛 Bug report

1. Cmake to Build C++ Source
2. ACE ver ACE-7.1.1
3. oneApi-TBB ver  (download from https://github.com/oneapi-src/oneTBB/releases  [oneapi-tbb-2021.10.0-win.zip])

I used C++ recompilation mangos.exe and realmd.exe
mangos file size more than 22M ,on this Program running，CPU Load 70%+，but use [core-bf8d6ad.zip] on Program running CPU Load 10%
and I recompilation still need ACEd.dll and TBB12.dll

OS Client: 
OS Server: Windows 10 & Visual Stdio 2017 15.9.58

**Comment by coolzoom** [comment]
sure it took more resources under debug mode, you need to select release mode from VisualStudio, and this is not a bug, it is how you operate.

**Comment by Soulyes** [comment]
thanks very mush,I have compiled it successfully.
