### ISSUE TITLE
🐝 [Bug]rogueT0.5 (challenge) mission could not be completed

### ISSUE THREAD

**Issue by zxnhrdz** [vmangos/core#2229]
## 🐝 Bug report - Quest
Theldren Kill Credit
This quest condition cannot be completed

### Expected behavior
You should be able to see it from inside the quest after defeating Seldrin's squad
Theldren Kill Credit: 1/1

### Steps to reproduce

After picking up the quest solo, enter the Blackrock Abyss Arena solo or in a small group, and plant the Challenge Flag in the center of
the field after you' ve been sentenced by the adjudicator, Greystone. After klling two waves of minions midway through the game,
Seldrin's squad makes their appearance. Kill Seldrin's squad, then deliver the first part of the Vatarak Trinket to Antaeus Halmon in the
Eastern Plague Lands. At this point, the quest is complete.

  Client Version:
  - 1.12.1.5875
  
  Commit Hash:
  https://github.com/vmangos/core
  https://github.com/vmanggs/core/commit/bf8d6ad13e64fc2f4ab6454e8b3890216d6f949e

  Operating System:
  Ubuntu 20.04.3 LIS (GNU/Linux 5.4.0-164-generic x86 _64)

**Comment by gujinjian** [comment]
战士T0.5  9015任务修复击杀NPC代码16166更正为1059

**Comment by zxnhrdz** [comment]
1059？Ana'thek the Cruel？No way!
