### ISSUE TITLE
Issues with Pyrewood Ambush quest

### ISSUE THREAD

**Issue by GrenderG** [vmangos/core#223]
**Current behavior**: 
- Humans summoned by this quest are humans even if done at night.
- Quest is not correctly marked as failed in the quest log if Deathstalker Faerleia dies.
- When a player fails the quest and Deathstalker Faerleia respawns, she doesn't have the quest giver flag. This doesn't always happen, but definitely does some times.

**Expected behavior**: 
- Humans summoned by this quest should be worgens if done at night.
- Quest should be correctly marked as failed in the quest log when the quest giver dies.
- The quest giver must always have the quest giver flag set again.

**Comment by ulfgebhardt** [comment]
@GrenderG can you provide more details, like the link to the quest in wowhead. This is not clear to me.

**Comment by GrenderG** [comment]
Wowhead: https://classic.wowhead.com/quest=452/pyrewood-ambush
YouTube video where you can see NPCs being worgens: https://www.youtube.com/watch?v=4Mj5tH2goIc
