### ISSUE TITLE
🐛 [Bug] High GUID in character db/ item_instance etc due Partybots and battlebots

### ISSUE THREAD

**Issue by Vanndar** [vmangos/core#2230]
## 🐛 Bug report

Character GUIIDs, item_instance guids are getting crazy big after spawning battle and partybots, they shouldn't increase guids (guids increase only, maybe add a seperate table for it so we can clean it?) in the database, would be nice if this could be fixed.
### Expected behavior

Only real players should count and increase the guids
### Steps to reproduce

1. Create a new character, check the GUID, then spawn bots , create a new character and the guid will be increased. after some time this is getting big. No big deal since I play alone but might be good if public one day.

### Version & Environment

Client Version: 1.12.1

Commit Hash:  Latest

OS Client: Win
OS Server:  Win

### Crashlog

- None

**Comment by GrenderG** [comment]
I guess as a solution the system could reuse unused guids instead of always doing a +1.

**Comment by Wall-core** [comment]
Best solution that I recently started using myself was splitting player guid into low/high, putting bot guids in the million range while keeping playerguids low value. This may help resolve this issue, though isn't strictly necessary as default vmangos playerbots don't generate new guids themselves.

**Comment by GrenderG** [comment]
> default vmangos playerbots don't generate new guids themselves.

Hmm they do as far as I know. To quickly test it spawn many bots, then create a new character and check its guid.

**Comment by ratkosrb** [comment]
Player bots are as the name implies Player objects, just controlled by an AI, so it's unavoidable that guid counter must be incremented, as player guids need to be unique.

**Comment by Vanndar** [comment]
ok thanks for the info then I'll just change the GUID type ti bigint and length 250, just in case, same for item_instance and all other guids from the character database @ratkosrb @GrenderG
