### ISSUE TITLE
🔧 [Support]How to change the number of entry dungeons per hour

### ISSUE THREAD

**Issue by Soulyes** [vmangos/core#2235]
How to change the number of entry dungeons per hour.
Mangos.conf ,This configuration item is not included.

Client Version: 
1.12.1.5875

OS Client: Win10
OS Server: Win2012R

**Comment by ratkosrb** [comment]
I added a new option for this: Instance.PerHourLimit

**Comment by Soulyes** [comment]
thank you very much.
