### ISSUE TITLE
🐛 [Bug] Line of sight is checked for interacting with objects

### ISSUE THREAD

**Issue by red-candle** [vmangos/core#2240]
## 🐛 Bug report
Whenever I attempt to interact with a chest/chair/quest object (bookcase) that is out of line of sight (behind a wall), the client tries to do it, but the server throws a "line of sight" error. Actually, the error is only thrown in SOME(???) cases, such as a chest, but the check is still performed and fails the attempt.
Up to halfway through The Burning Crusade, this was possible to do on retail and even with the patch that "fixed" this, it was done by preventing the cursor in the client from reacting to objects that were behind walls (not by performing a server-side check).
I know that this may seem like a bug to most, but if you are trying to recreate something the way it was, then please skip these hacks. 

Interestingly enough, this worked properly (on all private servers) for many years.

One thing that's definitely broken now is that the Secret Safe in BRD (object 161495) is unusable because it's always "out of line of sight".

### Expected behavior
Move up to the Booty Bay inn wall so that you are in range of a chair inside. Click the chair through the wall and teleport onto it. The same should go for chests that are placed indoors, but close to walls so that they can be looted from outside.
1. https://www.wowhead.com/classic/quest=64/the-forgotten-heirloom#comments:id=2787197
2. https://www.wowhead.com/classic/quest=540/preserving-knowledge#comments:id=731

### Steps to reproduce
1. Hug the Booty Bay inn wall from the east (outside)
2. Move around until the cursor finds a chair that is in range
3. Click the chair
4. Nothing happens
5. No profit :(

1. (1, but this editor mashes up both lists) Defeat Warder Stilgiss in BRD (npc 9041)
2. (2, but this editor mashes up both lists) The hidden compartment opens up
3. (3, but this editor mashes up both lists) Can't loot the Secret Safe (object 161495) because it's "not in line of sight"

### Version & Environment
Client Version: 1.12.1.5875 (en-gb)

Commit Hash: ??? (I'm playing - no access to server)

OS Client: Windows 10
OS Server: ??? (I'm playing - no access to server)

### Crashlog

- None

**Comment by ratkosrb** [comment]
Both of your examples already work in vmangos.


https://github.com/vmangos/core/assets/35845488/534fccf6-6c7a-44d3-a51d-882ca62ce764


https://github.com/vmangos/core/assets/35845488/c9f152e4-e518-4d49-a513-2b14a28fc7b5

**Comment by red-candle** [comment]
I'm very sorry. I'll stop posting issues from custom servers. :(

**Comment by codestothestars** [comment]
> I'm very sorry. I'll stop posting issues from custom servers. :(

If you want to verify an issue before reporting, download and spin up the repack and check it there. For most people it's a matter of minutes to set up.

**Comment by Udolfoo** [comment]
Hey, 

https://www.youtube.com/watch?v=9hKSHebsd64

You are right, both of them work youve tested but in BRD it dont work.
Which is confusing "Heart of the Mountain" work

But the object 161495 dont work.

Regards

**Comment by red-candle** [comment]
Interesting. Line of sight should never be checked for objects.
