### ISSUE TITLE
🐛 [Bug] Confessor's Raiment (3/5) + Holy Reach = Out of range

### ISSUE THREAD

**Issue by red-candle** [vmangos/core#2241]
## 🐛 Bug report
I believe that this isn't really a spell bug but rather a general mechanics issue.

The Confessor's Raiment (3/5) set bonus adds 5y to Smite and Holy Fire ranges. Holy Reach boosts those ranges by 20%. The UI calculates 42y and the spells become available at that distance, but the server replies "Out of range" beyond approx. 41y.

In fact, when the UI states that I am barely in range **without the set bonus**, the server still says "Out of range" - rounding error?
So the Holy Reach (2/2) talent is also broken.
I used to experience this once or twice a week when doing a lot of PvP and always assumed that it was lag-related, but now that I have done proper testing, it's always the same: max range Mind Blast casts always work, talented Smite/Holy Fire never work.

Anyway, if these properties are to be compared to primary attributes (stamina) and how those stack, if you have an effect that boosts an attribute by a percentage (Blessing of Kings), it is applied on the sum of all integer boosts to that attribute, for example:
100 base stamina, +10 on gloves, +10% kings = (100 + 10) * 1.1 = 121
If this same order is applied to the range of spells, 30y base, +5y set bonus, +20% talent = (30 + 5) * 1.2 = 42

**Quest/Item/Spell Link**
https://www.wowhead.com/classic/spell=27790/holy-reach
https://www.wowhead.com/classic/spell=24482/improved-smite-and-holy-fire

### Steps to reproduce
1. Pixel sneak into range of Mind Blast (30y) of a stationary enemy. Wiggle back and forth to find that max distance where the default UI shows white text on the action bar (in range). Jump to confirm the position on the server.
2. Start casting Mind Blast multiple times successfully.
3. With Holy Reach (2/2), retry steps 1+2 with Smite or Holy Fire and fail with "Out of range".
4. Get a tiny bit closer (less than 1y) and now they work.
5. With Confessor's Raiment (3/5) and Holy Reach (2/2), retry steps 1+2 and see them fail.
6. Get closer (estimated 1y) and now they work.

### Expected behavior
https://www.wowhead.com/classic/item-set=480/confessors-raiment#comments:id=2852273
https://classicdb.ch/?itemset=480#comments:id=118927
(Also, the default UI shows 42y on the spells.)

36y range for the affected spells with Holy Reach (2/2), not slightly less.
42y range for the affected spells with Confessor's Raiment (3/5) and Holy Reach (2/2), not 41y.

I suspect that the server first applies 20% then adds 5y for a total of 41y.
30y x 1.2 + 5y = 41y

According to Blizzard's UI, first the 5y should be added, then boosted by 20% to a total of 42y.
(30y + 5y) x 1.2 = 42y

### Version & Environment
Client Version: 1.12.1.5875 (en-gb)

Commit Hash: ??? (player - no server access)

OS Client: Windows 10
OS Server: ??? (player - no server access)

### Crashlog
- None

**Comment by ratkosrb** [comment]
I cannot reproduce the issue. You seem to be reporting issues from a private server using a different core.


https://github.com/vmangos/core/assets/35845488/73ef33d0-773a-4f26-8939-4aa40ed62235

**Comment by red-candle** [comment]
I'm very sorry. I'll stop posting issues from custom servers. :(
