### ISSUE TITLE
🐝 [Bug]“The Stones That Bind Us”  cannot be completed

### ISSUE THREAD

**Issue by yjfyy** [vmangos/core#2247]
Steps to reproduce
1. .quest add 2681
2. .go .go -11855 -2957 11 0
3. Beat monsters
4. Using stones

Unable to complete

  Client Version:
  - 1.12.1.5875

Commit Hash:   https://github.com/vmangos/core/commit/bf8d6ad13e64fc2f4ab6454e8b3890216d6f949e

OS Client:  Windows
OS Server: Windows

**Comment by schell244** [comment]
Same problem reported here: https://github.com/vmangos/core/issues/2226
