### ISSUE TITLE
🐛 [Bug] Battlebots wallclimbing to the graveyard in WSG

### ISSUE THREAD

**Issue by Vanndar** [vmangos/core#2252]
Bug: Battlebots are wallclimbing into the graveyard at WSG (pathing issue?)
### Expected behavior

They shouldn't since players also can't.
### Steps to reproduce

1. Spawn WSG bots, enter WSG and monitor for few mins

### Version & Environment

Commit Hash:  Latest

OS Client:  Win 
OS Server:  Win

**Comment by leechunlung** [comment]
Indeed, there is a problem with the path

**Comment by NickTyrer** [comment]
Duplicate #1181
