### ISSUE TITLE
🦂 [Bug]Lord Valthalak can‘他’

### ISSUE THREAD

**Issue by gujinjian** [vmangos/core#2255]
Lord Valthalak  can't  call  T0.5  of ROUGE   use  fire basket 
 
### Version & Environment

Client Version:
  - 1.12.1.5875
Client Version: 
ubuntu18.04
  Operating System:
  - Linux Flavor
time：2023-10-28

**Comment by cdkr** [comment]
You are providing incorrect information, that's Brazier of Beckoning not "fire basket". I suggest close this issue asap.
