### ISSUE TITLE
🐛 [Bug] Partybots use spells of the largest spell id known, not the highest rank.

### ISSUE THREAD

**Issue by GoonBoiBarry** [vmangos/core#2256]
## 🐛 Bug report
The paladin spells "Seal of Righteousness" and "Consecration" both have their rank 1 versions as higher spell ids than the other ranks. As a result, paladin partybots use these rank 1 spells instead, even when they know higher ranks.

### Expected behavior

Partybots should use their highest rank spells.
### Steps to reproduce

1. Create a paladin partybot that knows multiple ranks of seal of righteousness that it can use.
2. Make it fight something so that it cast seal of righteousness.
3. Watch their mana go down by only 20 (cost of rank 1) and do rank 1 seal damage.
4. Repeat for consecration if you want similar confirmation (harder to set up because of multiple enemies requirement for ai to use).
5. Profit!

### Version & Environment

  Client Version:
  - 1.12.1.5875

OS Client: Win 10
OS Server:  Win 10

### Crashlog

- None

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/f232701b71cf7fc1e27385b8cae8e48f195015b3
