### ISSUE TITLE
🐝 [Bug] Mage - Investigate the Alchemist Shop / the Blue Recluse

### ISSUE THREAD

**Issue by schell244** [vmangos/core#2262]
## 🐝 Bug report - Quest
Currently, the quest can't be completed. When using [Containment Coffer](https://www.wowhead.com/classic/item=7247/chest-of-containment-coffers) on a weaked [Rift Spawn](https://www.wowhead.com/classic/npc=6492/rift-spawn), nothing happens and there is no quest credit. After a while, weakend Rift Spawn just despawn.
Also when using [Cantation of Manifestation](https://www.wowhead.com/classic/item=7308/cantation-of-manifestation) in the basement of the inn (alliance quest), player is attacked by an invisible Rift Spawn, after a few seconds it becomes visible.

Horde quest: https://www.wowhead.com/classic/quest=1920/investigate-the-blue-recluse
Alliance quest: https://www.wowhead.com/classic/quest=1960/investigate-the-alchemist-shop

Spell which is supposed to be casted by Rift Spawns: https://www.wowhead.com/classic/spell=9010/create-filled-containment-coffer

Last related change to the quest:
https://github.com/vmangos/core/commit/f43730b97c485849393a33a6371f1ec5d4d8fa06

### Expected behavior
https://youtu.be/0k9D8Mp2XbM?t=99

### Steps to reproduce
1. add quest 1920 or 1960 and collect items
2. move to Rift Spawn positions, use Cantation of Manifestation
3. weaken then until they show stunned annimation
4. use Chest of Containment Coffers
5. -> nothing happens

### Version & Environment
  Client Version:
  - 1.12.1.5875

Commit Hash:  
017c262

**Comment by Udolfoo** [comment]
Hey Schell,

ive tested it and on my site and i cant reproduce it, its like in the Video youve showed, please remeber to delete your WDB

Regards

**Comment by schell244** [comment]
Hi Elmo, are you using latest commit? I remeber this quest was working some time ago. Just recompiled & did fresh db setup to make sure, still getting the issue.
<img width="200" alt="Unbenannt" src="https://github.com/vmangos/core/assets/9536270/c9e140d5-b903-4b90-ab5b-ef104234300f">

**Comment by Udolfoo** [comment]
I use a Commit where the last change where the same as here. So No i dont use the last commit.

**Comment by Wall-core** [comment]
The script needs to be redone from sniffs, it's using ancient hackfixes. The mobs should be perma invis with a 1k basepoint invis spell, and the scrolls should reduce their invis by 1k; it needs to be scripted to check the correct targets because without, it will break whatever it hits that doesn't have 1k invis.
