### ISSUE TITLE
🔧 [Support]boss loot

### ISSUE THREAD

**Issue by Soulyes** [vmangos/core#2263]
Client Version: 1.142

OS Client: windows 10
OS Server: windows 2012R

Can you increase the mass BOSS Loot that can be traded to other members within 2 hours?
like class_era.

**Comment by ratkosrb** [comment]
No, that is not a thing in vanilla. We are not implementing features from the new classic, that contradicts the goal of the project, it would make it not accurate to vanilla to have such custom things.
