### ISSUE TITLE
🐛 [Bug] Frost Mage playerbots only cast frostbolt when the target is not affected by the slow debuff

### ISSUE THREAD

**Issue by GoonBoiBarry** [vmangos/core#2267]
## 🐛 Bug report
Mage playerbots will only cast frostbolt when when the target is not affected by the slow debuff. This is due to the condition that prevents bots from reapplying dots/regular debuffs, but in this case it causes the bot to do lower dps if frost spec.

### Expected behavior
Mage playerbot should cast frostbolt continuously for efficient single target dps.

### Steps to reproduce

1. Load a mage bot.
2. Have it fight an at level mob.
3. Watch it cast frostbolt until the mob is hit and then resort to fireballs.
4. ...
5. Profit

  Client Version:
  - 1.12.1.5875

Commit Hash:  

OS Client: Win 10
OS Server: Win 10

### Crashlog

- None

**Comment by ratkosrb** [comment]
If we remove the condition, then bot will never cast any spell below Frostbolt in the script. It tries to cast things in the order that is defined in the script.

https://github.com/vmangos/core/blob/development/src/game/PlayerBots/PartyBotAI.cpp#L1764

The following spells will never be used if casting Frostbolt while debuff is already applied is allowed:
- Fire Blast
- Fireball
- Evocation

**Comment by ratkosrb** [comment]
The bots do not have any concept of specs btw, in Vanilla you do not have to choose a spec like was made mandatory in Catacylsm, so saying "Frost" spec is a very arbitrary term. How many points in the tree does it constitute as being that spec? Not to mention there is a different play style to different specs, with different priorities. The bot AI is supposed to be generic, it tries to use all class abilities. It is not meant to be the optimal implementation of 1 specific spec.

**Comment by GoonBoiBarry** [comment]
I always assumed you randomly gave them a preset spec and unlearned frostbolt if they had fire spec, but nvm. You could also place evocation higher in priority and it would work just fine, since it uses power < 30 as a condition. I think that for pve there are obviously fairly somewhat fixed specs that use one set of spells or the other. Generalizing them pretty much just makes them worse than they could be for pve, but that's your choice. Fyi this bug also affects fireball stacking ignites, as they will not refresh the debuff before it expires.
