### ISSUE TITLE
Auto-attack leeway

### ISSUE THREAD

**Issue by Klimpb** [vmangos/core#227]
**Current behavior**: 
Currently Auto-attacks follow the same leeway conditions as melee abilities.

**Expected behavior**: 
Auto-attacks should get leeway when jumping or moving, regardless if either player is slowed, doesn't follow same conditions as melee abilities.

Only movement that won't trigger leeway is RP-walking(is there a movement flag specifically for this?) and backpeddle.

**Steps to reproduce**:
Mimic this: https://streamable.com/d4dw9

**Source**:
https://us.forums.blizzard.com/en/wow/t/wow-classic-not-a-bug-list/175887/23
https://www.twitch.tv/tribe_tv1/clip/ConsiderateFitLionRitzMitz - Backpeddle & slowed autos
https://streamable.com/85hf4 - RP walk
https://streamable.com/d4dw9 - slowed autos

**Comment by Bzmode** [comment]
creatures should also have this attack leeway.
