### ISSUE TITLE
🔧 [Support]About Quest loot

### ISSUE THREAD

**Issue by Soulyes** [vmangos/core#2270]
Excuse me, How bonding a quest item loot , when get quest ,the creature can loot?
thanks

**Comment by Alleyaka** [comment]
This is a little confusing. 

Are you asking about how to loot a quest item or are you asking if the item is soulbound, tradable, Bind on Equip, etc? Could you be a little more specific with what you want to know?

**Comment by Soulyes** [comment]
Step 1. I created a new task that needed to kill a monster and get something;(mangos.quest_template)
Step 2. The item can only fall off after receiving the task;(mangos.creature_loot_template   changeorquest -100)
Step 3. The chanceorquest field in the database is invalid after filling in;
