### ISSUE TITLE
🐛 [Bug]About Script Error

### ISSUE THREAD

**Issue by Soulyes** [vmangos/core#2279]
Client Version:  1.142
OS Client: win10
OS Server: Server2012R

1. ERROR: SCRIPT_COMMAND_ATTACK_START (script id 1335804) for an invalid attack target, skipping.
2. ERROR: Creature entry 13598/13597 call SetInCombatWithZone for map (id: 30) that isn't an instance.
3. ERROR: FindScriptTargets: Failed to find target for script with id 852401 (target_param1: 0), (target_param2: 0), (target_type: 1).

These three are often found in the error log.
![image](https://github.com/vmangos/core/assets/147594856/b962febd-d4d4-40a1-8f49-160b211a462e)

**Comment by cbunting99** [comment]
I was just browsing around, but I know HermesProxy doesn't fully support client 1.14.2. There are a lot of things that don't work right in any classic server when using that client. I think you need to use either 1.14.0 or 1.12.1 clients.

**Comment by ratkosrb** [comment]
These errors in the console have nothing to do with what client players are using.

**Comment by cbunting99** [comment]
I was talking about the opcode message in white. Didn't even really notice the red creature/script error.
