### ISSUE TITLE
Quest 2118

### ISSUE THREAD

**Issue by darkmord1991** [vmangos/core#228]
https://de.wowhead.com/quest=2118/verseuchtes-land
**Current behavior**: 
trap does not spawn for hunting/catching the bear
**Expected behavior**: 
trap has to spawn
**Steps to reproduce**:

1. start quest
2. 
3. 

**Client version**: 
1.12.1
**Commit hash**: 
12.06.2019 00:27:30
**Operating system**: 
Win Server 2016

**Comment by ratkosrb** [comment]
I cannot reproduce the issue. The trap works fine.
https://streamable.com/f3zle
