### ISSUE TITLE
🐝 [Bug]Emberstrife cannot be controlled, below 10% of health

### ISSUE THREAD

**Issue by leechunlung** [vmangos/core#2282]
### Steps to reproduce

1.Combat Emberstrife to less than 10% health

2.Click on Orb of Draconic Energy in the backpack

3.No effect, and he is in a weakened state

4. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: win 11
OS Server: win 11

### Crashlog

- None

**Comment by leechunlung** [comment]
Used packaging after November 5th 2023

**Comment by ratkosrb** [comment]
Fixed it.
