### ISSUE TITLE
🔧 [Support]several players in the guild are not appearing in the guild list

### ISSUE THREAD

**Issue by zbhcn** [vmangos/core#2287]
I encountered a strange problem where several players in the guild are not appearing in the guild list. Even if they leave and rejoin the guild, they still don’t show up. They have also tried logging off and back on, but it doesn’t work. There are indeed relevant records in the guild_member table in the database. It’s really strange. What could be the reason for this?

**Comment by ratkosrb** [comment]
How many people are in the guild? If there are too many, it won't be possible to send the full list to the client.

**Comment by zbhcn** [comment]
there are more than 800 members in my guild , i delete some members yesterday , it's ok now , thank you , by the way ,it's a bug,isn't it?

**Comment by ratkosrb** [comment]
It is impossible to send that many members to the client. There is no space in the packet. They are limited to 65535 kb. It was like this in original vanilla too, this is a limit of the client.
