### ISSUE TITLE
🐛 [Bug]Battlebots in the Alterac Valley all at level 51 when 60lv player starting auto join

### ISSUE THREAD

**Issue by leechunlung** [vmangos/core#2289]
### Steps to reproduce

1.Set "mangosd.conf" BattleBot.AutoJoin = 1
2.60level player Join Alterac Valley 
3.found that Battlebots are all level 51 
4.A general who cannot defeat level 60 will not end the battlefield
5. Profit

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  

OS Client: Win 11
OS Server: Win 11

### Crashlog

- None

**Comment by zbhcn** [comment]
hi,guys,you say what i want to say. battleground became so easy

**Comment by leechunlung** [comment]
It should be the same level as the player to make sense, or a random level of 51-60, if all levels are 51, it is not reasonable

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/d026dc727d1099ffd8e6b9435e96b06db4d195d9
