### ISSUE TITLE
Un'goro Dirt Pile should give 1-4 Un'goro Soil

### ISSUE THREAD

**Issue by GrenderG** [vmangos/core#229]
**Current behavior**: 
Only giving 1 Un'goro Soil.

**Expected behavior**: 
Should give 1-4 Un'goro Soil (https://classic.wowhead.com/item=11018/ungoro-soil#comments:id=2689942:reply=1168429).

Fix:

```sql
update gameobject_loot_template set maxcount = 4 where item = 11018;
```

**Comment by AnonXS** [comment]
https://web.archive.org/web/20111104031323/http://www.wowhead.com:80/object=157936
