### ISSUE TITLE
🚀 [Feature] Partybots can infinitely replicate tradable items！

### ISSUE THREAD

**Issue by leechunlung** [vmangos/core#2290]
## 🚀 Feature

1、Any player character, summon a partybot
2、I separate the stacking numbers of items，for example Arcanite Bar.   whatever items that can be traded and stacked
3、And then trade it to the partybot，partybots will accept
4、player character offline ， log out of the game
5、then player online，log in
6、We found that the items in the backpack did not decrease, and there were also stacked items added
7、Affects the balance of certain gameplay

**Comment by ratkosrb** [comment]
Are you using "partybot load" command to summon real characters as bots?

**Comment by leechunlung** [comment]
no，just .parybot add ，Random partybots

**Comment by leechunlung** [comment]
> Are you using "partybot load" command to summon real characters as bots?

no，just .parybot add ，Random partybots

**Comment by ratkosrb** [comment]
But these bots are not saved in the db, how can they dupe anything? I don't understand. Can you make a video of the problem?

**Comment by leechunlung** [comment]
> But these bots are not saved in the db, how can they dupe anything? I don't understand. Can you make a video of the problem?

I recorded a video

https://youtu.be/vDglQsJMEtI

**Comment by leechunlung** [comment]
I used to have two black lotus flowers, but now I have infinite

**Comment by leechunlung** [comment]
I used to have two black lotus , but now I have infinite

**Comment by leechunlung** [comment]
> But these bots are not saved in the db, how can they dupe anything? I don't understand. Can you make a video of the problem?

If partybot trading is prohibited?trading seems useless ...
