### ISSUE TITLE
🦂 [Bug]Shadowfang Keep cannot be opened prison door

### ISSUE THREAD

**Issue by leechunlung** [vmangos/core#2299]
### Steps to reproduce

1.Enter the Shadowfang Keep
2.Defeat the Rethilgore
3.Rescue Sorcerer Ashcrombe or Deathstalker Adamant
4.The door of the cell cannot be opened, and the pull rod on the wall is ineffective
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/8728a4820f11f4d8921fdb5672ae0a3b671f425f
