### ISSUE TITLE
Warlord Goretooth's quest offering behavior issues

### ISSUE THREAD

**Issue by GrenderG** [vmangos/core#230]
**Current behavior**: 
Warlord Goretooth is offering both the quest (Warlord's Command) and the dialogue option and also offering them even if you are Neutral with Orgrimmar.

**Expected behavior**: 
He should only offer the dialogue option (Proof https://classic.wowhead.com/quest=4903/warlords-command#comments:id=403). Also, he should only offer it if you are Friendly or more with Orgrimmar. (Proof: https://classic.wowhead.com/quest=4903/warlords-command#comments:id=2964459 and https://classic.wowhead.com/quest=4903/warlords-command#comments:id=2964454)

**Comment by NickTyrer** [comment]
Can be closed. Fixed in #687
