### ISSUE TITLE
🐛 [Bug][AutoJoin] BattleBots start bg without people.

### ISSUE THREAD

**Issue by gajet5** [vmangos/core#2302]
## 🐛 Bug report
![image](https://github.com/vmangos/core/assets/3825412/4ec2bc89-94b9-450c-9c65-eef850873a6d)

Somehow, an additional pool of battlebots appeared. When registering a new participant, an additional BG starts without people.

### Expected behavior
Battlebots do not start BG without people.
We need a check. If there are no people on BG, delete battlebots or disallow going to BG with playerbots.

### Steps to reproduce
1. Add partybot.
2. Register as a group on BG.
3. Go to BG.

### Version & Environment
Client Version: 1.12.1.5875

Commit Hash:  No

OS Client: Windows
OS Server: Ubuntu

### Crashlog

- None

**Comment by gajet5** [comment]
We found the reason. 
The problem is that with partybots you can go to BG, then an excess of battlebots get into the queue.

**Comment by leechunlung** [comment]
> We found the reason. The problem is that with partybots you can go to BG, then an excess of battlebots get into the queue.

I think you should turn off battlefield balance in the mangosd.conf

**Comment by gajet5** [comment]
The problem with BG is still present, bots are starting to be added. You need to check for the presence of real players or something else.

![image](https://github.com/vmangos/core/assets/3825412/229665a1-a83b-4c2c-a76c-c8a15de48711)

after .battlebot removeall
![image](https://github.com/vmangos/core/assets/3825412/5409bd8e-c93c-49d2-8bf6-a1a94d1e02a4)

**Comment by gajet5** [comment]
After executing the command `.battlebot removeall`, this is a bug. In fact, all bots are deleted, but they continue to be displayed in the statistics.

**Comment by gajet5** [comment]
![Screenshot_3](https://github.com/vmangos/core/assets/3825412/697af367-12b1-4095-b752-783ffe8e2649)

We have no idea how it works :(

**Comment by gajet5** [comment]
> I think you should turn off battlefield balance in the mangosd.conf

As a workaround, it worked. I changed this setting during server maintenance today.

**Comment by gajet5** [comment]
![image](https://github.com/vmangos/core/assets/3825412/718079ee-ac2c-4791-9484-a8dba4284a02)
