### ISSUE TITLE
🐝 [Bug]quest ID 2480 quest name Hinott's Assistanc , Hinott(npc) is Stucked

### ISSUE THREAD

**Issue by zbhcn** [vmangos/core#2303]
quest ID: 2480
quest name: Hinott's Assistanc 

Hinott(npc) is Stucked when player accepted the quest id 2480 , Hinott(npc) can't  give players poison skills after waiting for a while . the player's class  is rogue , race is Horde

**Comment by ratkosrb** [comment]
Can't reproduce the issue. I did the quest and it completed without issue after waiting for him to walk around.

**Comment by zbhcn** [comment]
sorry ,it's my fault ，delete this please
