### ISSUE TITLE
🦂 [Bug] Son of Flame can no longer be rooted by frost nova, or slowed by frostbolt

### ISSUE THREAD

**Issue by GoonBoiBarry** [vmangos/core#2305]
## 🦂 Bug report - Dungeon
The recent changes to mob immunity has made Sons of Flame immune to frost nova root and frostbolt slow. I assume this is based on sniff data, so I don't know how this happened as there appears to plenty of proof these mobs are affected by both of these, but maybe I'm missing something.

### Expected behavior
https://www.youtube.com/watch?v=WPPmqII0xYU At 6:17 you can see these mobs are rooted by frost nova.

https://www.youtube.com/watch?v=bxjFjYX1N9w&t=267s At 4:37 you can see them affected by frostbolt slow.

### Steps to reproduce

1. Create a mage and learn mage abilities
2. .cheat god on
3. .npc summon 12143
4. cast frostbolt and frost nova and witness no slow or root
5. Profit

### Version & Environment

  - 1.12.1.5875

Commit Hash:  

OS Client: Win 10
OS Server: Win 10

### Crashlog

- None

**Comment by ratkosrb** [comment]
Hmm maybe it was Banished and then somebody casted Frost Nova and that's why it was seen being immune in sniff?

**Comment by GoonBoiBarry** [comment]
Yeah that would make sense, but unfortunately that would raise questions on the accuracy of other sniffs on at least demons and elementals. How do damage schools not get grouped into that too though?

**Comment by ratkosrb** [comment]
I have an idea. I'll add a new table in sniff db with mechanics and schools mobs are not immune to. When they are hit by a spell, we add the school and mechanic of the spell that hit it to the table.

**Comment by GoonBoiBarry** [comment]
The only issue I could see with that is that some abilities still apply damage even when the mob is immune to the mechanic, like riposte for example. So I don't know if that can be taken into consideration with that setup

**Comment by ratkosrb** [comment]
@GoonBoiBarry The mechanic is per effect in the case of Riposte, I'll only export it into the `creature_spell_not_immune_mechanic` table when it's a mechanic set on the spell itself, not on a specific effect.

You can see what I came up with here.
https://github.com/ratkosrb/WowPacketParser/commit/7b0f91b915e86042f592d23a6beaec4625dcc17d

But now all the sniffs have to be reparsed to export this data. It will take a long time.

**Comment by GoonBoiBarry** [comment]
Ah okay cool, I should of figured that because the recent immunity changes were distinguished that way.

Hopefully it fixes it, glad you can at least reuse the same data.

Thanks for all your hard work btw. You are pretty much the main contributor for this project now and my life is made much happier having access to my own close to parity classic wow server and your ai bots :). You are an unsung hero.

**Comment by mserajnik** [comment]
> Thanks for all your hard work btw. You are pretty much the main contributor for this project now and my life is made much happier having access to my own close to parity classic wow server and your ai bots :). You are an unsung hero.

I'll second that, the quality of this project is insane.

@GoonBoiBarry

If you had already applied the migration `20231121204641` from https://github.com/vmangos/core/commit/2f9dc70a3e369c0496e4d400bdf2144e4977ff60 to the database you actually use (which I assume you had, unless you created this issue based on a test with a separate database) take a look at [my comment here](https://github.com/vmangos/core/commit/75474d2d33bccfabc2a2f05986132529f3b79cbb#commitcomment-133297131).

You might have already realized that yourself, but I figured I would mention it here as well for visibility.

**Comment by GoonBoiBarry** [comment]
I usually just drop the old mangos table and run the mangos.sql from the db dump, so I don't think that'll affect me. But thanks anyway for going outta your way to give a heads up :)
