### ISSUE TITLE
🐛 [Bug] [Biznicks 247x128 Accurascope] doesn't work for melee

### ISSUE THREAD

**Issue by sh3ppard** [vmangos/core#2306]
**Describe the bug**
[Biznicks 247x128 Accurascope](https://www.wowhead.com/classic/item=18283/biznicks-247x128-accurascope) **doesn't work for melee**.

It should work before `1.10` patch:
> This item used to effect melee swings and was one of the most saught after enchantsments by rogues and warriors alike. It was nerfed to only ranged attacks and made to be a balanced part of the game.
> 
> It was also taken out of the loot table for a long while until they fix it for ranged only. So, many engineers that had the pattern before they removed it from the loot table got to price gouge all they wanted as many servers only had a handful of people with it.
> 
> Source: https://www.wowhead.com/classic/item=18283/biznicks-247x128-accurascope#comments:id=4612

**Quest/Item/Spell Link**
[Biznicks 247x128 Accurascope](https://www.wowhead.com/classic/item=18283/biznicks-247x128-accurascope) 

**To Reproduce**
1. Go to Heroic Training Dummy at Orgrimmar
2. Equip enough hit (also bow/gun with this scope) for getting soft hit cap `9%`
3. Equip only maind-hand or 2H weapon
4. Start hit the dummy

**Expected behavior**
It must adds `3%` hit for melees too on early patches.
> - Patch 1.10.0 (2006-03-28): Now only affects ranged attacks.
> - Patch 1.4.0 (2005-04-19): Added.
> 
> Source: https://wowpedia.fandom.com/wiki/Biznicks_247x128_Accurascope

I have not tested it on the stock vMangos. I copied this issue from Everlook github (they don't wanna fix it). I leave it here.
[Original post](https://github.com/TeamEverlook/Everlook-BugTracker/issues/116#issue-1570947542).

**Comment by ratkosrb** [comment]
Enchants are spells. Spell progression is tied to client progression. You must compile core for client prior to 1.10 if you want the enchant to work like it did before 1.10.

**Comment by TuriansNotBad** [comment]
Note that it's not implemented on old clients either. Currently we have a hardcoded special case for Biznik's with no client version guards in Aura::HandleModHitChance that stops Biznik's from granting melee hit.

Blizzard updated its spell (22780) in 1.10 by setting EquippedItemSubClassMask to 0x0004000C (BOW, GUN, CROSSBOW), previously = 0, but it's never looked at by the server. Related issue to this are also Rogue/Paladin Precision talents that increase melee hit chance and have the mask set to all melee weapons available to those classes but we have them increasing both ranged and melee hit instead cos that information is not used.

The 2 precision talents and Biznik's are the only spells using this and they all are either all possible melee or all possible ranged weapons so a full per weapon implementation similar to crititcal chance doesn't seem worth it (or well I at least assume you cannot enchant thrown weapons).

**Comment by ratkosrb** [comment]
@TuriansNotBad Please check if my solution fixes the issue.

**Comment by TuriansNotBad** [comment]
it does, replied on commit
