### ISSUE TITLE
🐞 [Bug] Demoralizing Roar

### ISSUE THREAD

**Issue by ghost** [vmangos/core#2307]
## 🐞 Bug report - Spell
Demoralizing Roar displays a different number of melee attack power reductions on the enemy than that indicated by the tooltip.

Here are some screenshots I took as a proof:

![WoWScrnShot_112223_114741](https://github.com/vmangos/core/assets/113198524/5b3001fb-008f-4215-abae-ca9715205c2d)
![WoWScrnShot_112223_114751](https://github.com/vmangos/core/assets/113198524/d485753e-7035-4d3b-ae28-0f4cdc47df4c)
![WoWScrnShot_112223_114801](https://github.com/vmangos/core/assets/113198524/cc99179d-52fa-43b4-b083-f21616eff54a)

As you can see, this should be a 45 reduction in melee attack power, but it's 37 instead.
I put 3 points on the talent that improves Demoralizing Roar's debuff, maybe it's not working? The tooltip updates correctly with each point put into the talent, if that helps.

### Version & Environment
Client Version: 1.12.1.5875

**Comment by ratkosrb** [comment]
This is not a bug. Tooltips are client side. It cannot be changed from the server. That's just the way it works in 1.12.
