### ISSUE TITLE
error with  world_db_updates.sql

### ISSUE THREAD

**Issue by coderAt30** [vmangos/core#2309]
git clone the latest version
msyql 5.6
when i run world_db_updates.sql with navicat

error happens

[SQL] Query world_db_updates start
[ERR] 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '??
delimiter ; 
CALL add_migration();
DROP PROCEDURE IF EXISTS add_migration;
 
' at line 2450

**Comment by TuriansNotBad** [comment]
possibly same issue, if it just crashes somewhere around middle
https://github.com/vmangos/core/issues/2102

don't know a proper fix, I have to split migrations into 4 parts and merge them separately.

**Comment by coderAt30** [comment]
> possibly same issue, if it just crashes somewhere around middle #2102
> 
> don't know a proper fix, I have to split migrations into 4 parts and merge them separately.

thank you for giving me a idea.
i tried different tools . datagrip and navicat   they shows diffrent errors  with diffrent file
there is a rule:  datagrip can run  batch little files.navicat can run big file singlely.
so i used the two tools  to  run  in order .   5 big files and  5 directory with a lot of little file.
