### ISSUE TITLE
🔧 [Support] Which client version should I use if I want to play with earlier patch

### ISSUE THREAD

**Issue by ch3rub1m** [vmangos/core#2313]
Can I play with client version 1.12 and server patch 1.2 ?
It's confusing that it wasn't mentioned in README.

**Comment by Wall-core** [comment]
Yes, you can use the 1.12 client/build and use server patch 0-10. Set it within mangos.conf; this controls aspects such as available dungeons and raids, progressive itemization, and many stat/quest/mob changes.

**Comment by ch3rub1m** [comment]
@Wall-core thanks.
