### ISSUE TITLE
Harpy Hide Quiver should require Revered reputation to get it

### ISSUE THREAD

**Issue by GrenderG** [vmangos/core#232]
**Current behavior**: 
You can buy the "Harpy Hide Quiver" with no reputation.

**Expected behavior**: 
"Harpy Hide Quiver" should require Revered reputation to get it (https://classic.wowhead.com/item=19319/harpy-hide-quiver#comments:id=2634652), the same way as the "Gnoll Skin Bandolier" is requiring it now.

**Steps to reproduce**:

1. Visit any Frostwolf / Stormpike vendor and try to buy the Quiver with no reputation.

Fix:

```sql
update item_template set required_reputation_rank = 6 where entry = 19319;
```

**Comment by ratkosrb** [comment]
Hmm, in the ItemSparse.db2 from Classic Blizzcon Demo client both required reputation faction and rank fields are 0 for this item.

**Comment by GrenderG** [comment]
> Hmm, in the ItemSparse.db2 from Classic Blizzcon Demo client both required reputation faction and rank fields are 0 for this item.

That's weird. As you can see in the old comments people said that it required Revered reputation. And it would be weird that the Bandolier required Revered but not the Quiver, specially taking into account that the Quiver is very good for that level.
