### ISSUE TITLE
🦂 [Bug]In the Stockade right area,the creatures encountered evasion and terrain issues

### ISSUE THREAD

**Issue by leechunlung** [vmangos/core#2321]
### Steps to reproduce

1.choose a remote roles
2.In the Stockade right area,the creatures encountered evasion and terrain issues
3.Almost all creatures remain in place after entering battle
4.Only melee attacks can take effect, and ranged spells are all evasion
5.It seems that there is an issue with the map. I'm not sure if other dungeons have similar issues

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  

OS Client: win10
OS Server: win10

### Crashlog

- None

**Comment by mserajnik** [comment]
I can't replicate this, all the mobs seem to behave fine for me (using recently extracted maps that are up-to-date with any code changes related to the extractors).
