### ISSUE TITLE
🦂 [Bug]Flamewaker Healer Polymorph immunity

### ISSUE THREAD

**Issue by leechunlung** [vmangos/core#2324]
### Steps to reproduce

1.The Molten Core
2.  Flamewaker Healer Polymorph immunity
3.
4. ...
5. Profit

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  

OS Client: Win XX
OS Server: Win XX

### Crashlog

- None

**Comment by zbhcn** [comment]
yes, me too

**Comment by zbhcn** [comment]
Executing the following SQL statement in your database can solve this bug

UPDATE `mangos`.`creature_template` SET `name` = 'Flamewaker Healer', `subname` = NULL, `level_min` = 60, `level_max` = 60, `faction` = 54, `npc_flags` = 0, `gossip_menu_id` = 0, `display_id1` = 13029, `display_id2` = 0, `display_id3` = 0, `display_id4` = 0, `display_scale1` = 0, `display_scale2` = 0, `display_scale3` = 0, `display_scale4` = 0, `display_probability1` = 0, `display_probability2` = 0, `display_probability3` = 0, `display_probability4` = 0, `display_total_probability` = 0, `mount_display_id` = 0, `speed_walk` = 1, `speed_run` = 1.71429, `detection_range` = 20, `call_for_help_range` = 5, `leash_range` = 0, `rank` = 1, `xp_multiplier` = 1, `health_multiplier` = 40, `mana_multiplier` = 12, `armor_multiplier` = 1.1, `damage_multiplier` = 12, `damage_variance` = 0.14, `damage_school` = 0, `base_attack_time` = 2000, `ranged_attack_time` = 2000, `holy_res` = 0, `fire_res` = 15, `nature_res` = 15, `frost_res` = 15, `shadow_res` = 15, `arcane_res` = 15, `unit_class` = 2, `unit_flags` = 0, `pet_family` = 0, `trainer_type` = 0, `trainer_spell` = 0, `trainer_class` = 0, `trainer_race` = 0, `type` = 7, `type_flags` = 8, `loot_id` = 11663, `pickpocket_loot_id` = 0, `skinning_loot_id` = 0, `gold_min` = 1007, `gold_max` = 5037, `spell_id1` = 21077, `spell_id2` = 23952, `spell_id3` = 10960, `spell_id4` = 0, `spell_list_id` = 116630, `pet_spell_list_id` = 0, `spawn_spell_id` = 0, `auras` = NULL, `ai_name` = '', `movement_type` = 0, `inhabit_type` = 3, `civilian` = 0, `racial_leader` = 0, `regeneration` = 3, `equipment_id` = 0, `trainer_id` = 0, `vendor_id` = 0, `mechanic_immune_mask` = 612515807, `school_immune_mask` = 0, `immunity_flags` = 0, `flags_extra` = 2097152, `script_name` = '' WHERE `entry` = 11663 AND `patch` = 0;
UPDATE `mangos`.`creature_template` SET `name` = 'Flamewaker Elite', `subname` = NULL, `level_min` = 62, `level_max` = 62, `faction` = 54, `npc_flags` = 0, `gossip_menu_id` = 0, `display_id1` = 12002, `display_id2` = 0, `display_id3` = 0, `display_id4` = 0, `display_scale1` = 0, `display_scale2` = 0, `display_scale3` = 0, `display_scale4` = 0, `display_probability1` = 0, `display_probability2` = 0, `display_probability3` = 0, `display_probability4` = 0, `display_total_probability` = 0, `mount_display_id` = 0, `speed_walk` = 1, `speed_run` = 1.71429, `detection_range` = 20, `call_for_help_range` = 5, `leash_range` = 0, `rank` = 1, `xp_multiplier` = 1, `health_multiplier` = 40, `mana_multiplier` = 12, `armor_multiplier` = 1.25, `damage_multiplier` = 16.85, `damage_variance` = 0.14, `damage_school` = 0, `base_attack_time` = 2400, `ranged_attack_time` = 2000, `holy_res` = 0, `fire_res` = 93, `nature_res` = -93, `frost_res` = -93, `shadow_res` = -93, `arcane_res` = -93, `unit_class` = 2, `unit_flags` = 0, `pet_family` = 0, `trainer_type` = 0, `trainer_spell` = 0, `trainer_class` = 0, `trainer_race` = 0, `type` = 7, `type_flags` = 8, `loot_id` = 11664, `pickpocket_loot_id` = 0, `skinning_loot_id` = 0, `gold_min` = 300, `gold_max` = 1500, `spell_id1` = 20623, `spell_id2` = 0, `spell_id3` = 0, `spell_id4` = 0, `spell_list_id` = 116640, `pet_spell_list_id` = 0, `spawn_spell_id` = 0, `auras` = NULL, `ai_name` = 'EventAI', `movement_type` = 0, `inhabit_type` = 3, `civilian` = 0, `racial_leader` = 0, `regeneration` = 3, `equipment_id` = 11664, `trainer_id` = 0, `vendor_id` = 0, `mechanic_immune_mask` = 646657887, `school_immune_mask` = 0, `immunity_flags` = 0, `flags_extra` = 2097152, `script_name` = '' WHERE `entry` = 11664 AND `patch` = 0;

**Comment by leechunlung** [comment]
> Executing the following SQL statement in your database can solve this bug
> 
> UPDATE `mangos`.`creature_template` SET `name` = 'Flamewaker Healer', `subname` = NULL, `level_min` = 60, `level_max` = 60, `faction` = 54, `npc_flags` = 0, `gossip_menu_id` = 0, `display_id1` = 13029, `display_id2` = 0, `display_id3` = 0, `display_id4` = 0, `display_scale1` = 0, `display_scale2` = 0, `display_scale3` = 0, `display_scale4` = 0, `display_probability1` = 0, `display_probability2` = 0, `display_probability3` = 0, `display_probability4` = 0, `display_total_probability` = 0, `mount_display_id` = 0, `speed_walk` = 1, `speed_run` = 1.71429, `detection_range` = 20, `call_for_help_range` = 5, `leash_range` = 0, `rank` = 1, `xp_multiplier` = 1, `health_multiplier` = 40, `mana_multiplier` = 12, `armor_multiplier` = 1.1, `damage_multiplier` = 12, `damage_variance` = 0.14, `damage_school` = 0, `base_attack_time` = 2000, `ranged_attack_time` = 2000, `holy_res` = 0, `fire_res` = 15, `nature_res` = 15, `frost_res` = 15, `shadow_res` = 15, `arcane_res` = 15, `unit_class` = 2, `unit_flags` = 0, `pet_family` = 0, `trainer_type` = 0, `trainer_spell` = 0, `trainer_class` = 0, `trainer_race` = 0, `type` = 7, `type_flags` = 8, `loot_id` = 11663, `pickpocket_loot_id` = 0, `skinning_loot_id` = 0, `gold_min` = 1007, `gold_max` = 5037, `spell_id1` = 21077, `spell_id2` = 23952, `spell_id3` = 10960, `spell_id4` = 0, `spell_list_id` = 116630, `pet_spell_list_id` = 0, `spawn_spell_id` = 0, `auras` = NULL, `ai_name` = '', `movement_type` = 0, `inhabit_type` = 3, `civilian` = 0, `racial_leader` = 0, `regeneration` = 3, `equipment_id` = 0, `trainer_id` = 0, `vendor_id` = 0, `mechanic_immune_mask` = 612515807, `school_immune_mask` = 0, `immunity_flags` = 0, `flags_extra` = 2097152, `script_name` = '' WHERE `entry` = 11663 AND `patch` = 0; UPDATE `mangos`.`creature_template` SET `name` = 'Flamewaker Elite', `subname` = NULL, `level_min` = 62, `level_max` = 62, `faction` = 54, `npc_flags` = 0, `gossip_menu_id` = 0, `display_id1` = 12002, `display_id2` = 0, `display_id3` = 0, `display_id4` = 0, `display_scale1` = 0, `display_scale2` = 0, `display_scale3` = 0, `display_scale4` = 0, `display_probability1` = 0, `display_probability2` = 0, `display_probability3` = 0, `display_probability4` = 0, `display_total_probability` = 0, `mount_display_id` = 0, `speed_walk` = 1, `speed_run` = 1.71429, `detection_range` = 20, `call_for_help_range` = 5, `leash_range` = 0, `rank` = 1, `xp_multiplier` = 1, `health_multiplier` = 40, `mana_multiplier` = 12, `armor_multiplier` = 1.25, `damage_multiplier` = 16.85, `damage_variance` = 0.14, `damage_school` = 0, `base_attack_time` = 2400, `ranged_attack_time` = 2000, `holy_res` = 0, `fire_res` = 93, `nature_res` = -93, `frost_res` = -93, `shadow_res` = -93, `arcane_res` = -93, `unit_class` = 2, `unit_flags` = 0, `pet_family` = 0, `trainer_type` = 0, `trainer_spell` = 0, `trainer_class` = 0, `trainer_race` = 0, `type` = 7, `type_flags` = 8, `loot_id` = 11664, `pickpocket_loot_id` = 0, `skinning_loot_id` = 0, `gold_min` = 300, `gold_max` = 1500, `spell_id1` = 20623, `spell_id2` = 0, `spell_id3` = 0, `spell_id4` = 0, `spell_list_id` = 116640, `pet_spell_list_id` = 0, `spawn_spell_id` = 0, `auras` = NULL, `ai_name` = 'EventAI', `movement_type` = 0, `inhabit_type` = 3, `civilian` = 0, `racial_leader` = 0, `regeneration` = 3, `equipment_id` = 11664, `trainer_id` = 0, `vendor_id` = 0, `mechanic_immune_mask` = 646657887, `school_immune_mask` = 0, `immunity_flags` = 0, `flags_extra` = 2097152, `script_name` = '' WHERE `entry` = 11664 AND `patch` = 0;

Thank you, I think this is also a SQL error,the key is `immunity_flags` = 0

Every update will have a large number of SQL errors, and I don't know where to find a more complete DB Dump

**Comment by ratkosrb** [comment]
I have completed reparsing all sniffs and combining them into a single db and will make a mass update to remove wrong immunities soon. Just need to write a tool for it.

**Comment by zbhcn** [comment]
looking forward Very much

**Comment by balakethelock** [comment]
> I have completed reparsing all sniffs and combining them into a single db and will make a mass update to remove wrong immunities soon. Just need to write a tool for it.

Is the new mass parse available for download?

**Comment by GoonBoiBarry** [comment]
You can check commits to see when it's been done. You don't have to ask him when he just said he's still working on it.

**Comment by balakethelock** [comment]
> You can check commits to see when it's been done. You don't have to ask him when he just said he's still working on it.

Was referring to the parse not the update =)

**Comment by GoonBoiBarry** [comment]
Oh right, sorry. Bad comprehension on my part.

**Comment by oowow-core** [comment]
https://github.com/vmangos/core/issues/2346
MC Majordomo Executus, NPC_FLAMEWAKER_HEALER/NPC_FLAMEWAKER_ELITE are not able to Polymorph: Sheep now, while previously can.

eaiser for people to search via boss name.
