### ISSUE TITLE
🐝 [Bug] Frostmaw quest works in general but it needs some polishing.

### ISSUE THREAD

**Issue by peacebringer** [vmangos/core#2327]
Hello.

Frostmaw mob spawns when you use Fresh Carcass, but he spawns in the wrong spot.
On Vmangos Frostmaw spawns at Flame (brazier) which is wrong.

Frostmaw should spawn outside of the cave and slowly walk inside the cave
towards Flame spot (where you used Fresh Carcass).
As proof I have comments from https://classicdb.ch/?quest=1136#comments

Plus I have videos that Frostmaw should spawn outside of the cave and slowly walk
into cave towards Flame spot (where you used Fresh Carcass):

At 0:58 - https://www.youtube.com/watch?v=aXCL4uNwVrU

At 1:17 - https://www.youtube.com/watch?v=lD-kOko9BDU

At 25:22 - https://www.youtube.com/watch?v=ZRmjMIVPgM4

**Comment by peacebringer** [comment]
I've heared this is already fixed.

If that's the case, I guess this topic can be closed.

**Comment by NickTyrer** [comment]
Fixed here https://github.com/vmangos/core/pull/1970/files#diff-3c4b0806c3fb4404eb821ef33b33fea1972ffb8cd7305d795bcea6e69c7e8975R169
