### ISSUE TITLE
🐝 [Bug] Saving Sharpbeak RP Quest event after you release Sharpbeak doesn't happen

### ISSUE THREAD

**Issue by peacebringer** [vmangos/core#2329]
Hello there.

After you finish quest Saving Sharpbeak, after you release Sharpbeak, RP Quest even should start
but that doesn't happen on Vmanogs. 

After you release Sharpbeak, his parents, Sharbeak's Father and
Sharpbeak's Mother should appear too in this event.

From comments we can see that this intersting and emotional RP event indeed existed.
https://classicdb.ch/?quest=2994#comments

And here are videos how it should look like. 
At 1:17 we can see in the chat that "Sharpbeak chirps a goodbye to -player's name-."
https://www.youtube.com/watch?v=5yGyB1nfWyQ

At 1:16 we can see again in the chat that "Sharpbeak chirps a goodbye to -player's name-."
https://www.youtube.com/watch?v=LQCRFY3IJKY

And third video:
https://www.youtube.com/watch?v=QnytlvxuQmA

**Comment by Daribon** [comment]
I think I have this quest sniffed back on som.

**Comment by ratkosrb** [comment]
It's already scripted, just the opening spell was missing targets so it failed to open the cage.


https://github.com/vmangos/core/assets/35845488/1d3ba837-a8af-464d-a7db-c62a8e8ffd6b
