### ISSUE TITLE
🦂 [Bug] Satura + guards are incorrectly invuln to stuns

### ISSUE THREAD

**Issue by Zebouski** [vmangos/core#2335]
## 🦂 Bug report - Dungeon

Looks like a big update pass was made on which mobs are CCable. But the sartura fight has regressed in blizzlikeness

### Expected behavior

They should only be stun immune during the whirlwind mechanic and not otherwise.

https://wowpedia.fandom.com/wiki/Battleguard_Sartura?oldid=338277
> Whirlwind - immune to stun while Whirl-winding, but otherwise vulnerable.

### Steps to reproduce

1. pull sartura
2. wait till they start autoing and stop whirlwind
3. hit hammer of justice or another stun
4. see immune
![image](https://github.com/vmangos/core/assets/11151284/d8193d2a-5e8c-4ae6-89aa-86ad80abdfac)

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  e290c68cc2984ae6209df2d259eee06a5be7bdd4

OS Client: Arch Linux
OS Server: Arch Linux

### Crashlog

- None

**Comment by ratkosrb** [comment]
I will soon™ make another mass update this time to remove incorrect immunities. But i need to reparse all the sniffs to export this info first.
