### ISSUE TITLE
🐛 [Bug] Anticheat banned a lot players in latest commit

### ISSUE THREAD

**Issue by oowow-core** [vmangos/core#2338]
## 🐛 Bug report

a lot players banned, after merge latest commit, they doesn't do teleport. 

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 1.12 / 1.14 both

Commit Hash:  

OS Client: 
OS Server: ubuntu 22.04

### Crashlog

- None

**Comment by oowow-core** [comment]
[pkt.zip](https://github.com/vmangos/core/files/13587488/pkt.zip)

**Comment by zbhcn** [comment]
Yes, this is a serious problem that I have also encountered, and when someone falls from a height and is not dead, they will be considered cheating and their account will be suspended

**Comment by ratkosrb** [comment]
Thank you for providing the movement logs. The issue should be fixed now.
