### ISSUE TITLE
🐝 [Bug][BRD] The Challenge - Does not count

### ISSUE THREAD

**Issue by gajet5** [vmangos/core#2341]
## 🐝 Bug report - Quest
Quest: https://www.wowhead.com/classic/quest=9015/the-challenge
Video: https://www.youtube.com/watch?v=LWwImIYV2pU

### Expected behavior
The quest is being completed.

### Steps to reproduce
1. Go to the Arena in Blackrock Depths
2. Set the Banner of Provocation
3. Win

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  No

OS Client: Win
OS Server: Ubuntu

### Crashlog
- None

**Comment by coolzoom** [comment]
same as https://github.com/vmangos/core/issues/2229
