### ISSUE TITLE
🐛 [Bug]Wands have no resist check

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2344]
## 🐛 Bug report
Wands cannot be resisted by enemies. I had 0 wand skill and never had a resist the entire time leveling it up to level 18 on my mage against level 15+ mobs.

### Expected behavior
Wands should be resisted very often if your skill is low compared to the targets level. On retail if I had 0 wand skill and attacked level15 mobs I would be resisted over and over until nearly capped skill for level15 mage against level 15 mobs.

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version:    - 1.12.1.5875

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/assets/35845488/1db63fe9-7219-449d-a7ce-3b8d80af329e


Cannot reproduce. My wand gets resisted when attacking high level creatures.

**Comment by ShiyoKozuki** [comment]
![image](https://github.com/vmangos/core/assets/58101246/dd378b3c-4770-4ff0-b3e9-8813ae1788a6)
I have 0 wand skill and I'm not getting a single resist vs a level 11 enemy
This isn't correct.

**Comment by ShiyoKozuki** [comment]
> vid.2023-12-18-1228-41.mp4 
> [×<MEDIA>@https://private-user-images.githubusercontent.com](https://private-user-images.githubusercontent.com/35845488/291249013-1db63fe9-7219-449d-a7ce-3b8d80af329e.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDQ4NTksIm5iZiI6MTcwMzAwNDU1OSwicGF0aCI6Ii8zNTg0NTQ4OC8yOTEyNDkwMTMtMWRiNjNmZTktNzIxOS00NDlkLWE3Y2UtM2I4ZDgwYWYzMjllLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDE2NDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNjAzMGJhM2IyZmYyZDQ0M2JiYzMwYzlkMDg4MzUyMGU3NGFlMGY4OTI5MGI2ZWQzOWUwN2M3MTUzYzQxN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0ZMNPiK_etPftK0wG8L6c-X1HZCjJK94TcPB6Ytklw0)
> Cannot reproduce. My wand gets resisted when attacking high level creatures.

![image](https://github.com/vmangos/core/assets/58101246/42754c5e-d251-4ee8-88ce-aaa4e80ece07)
I have 0 wand skill and I'm not getting a single resist vs a level 11 enemy
This isn't correct.
You tested level 0 vs a level 48+ enemy. However, at lower level gaps, there seems to be zero hit rate check or it's not strict enough at lower skill difference gaps.
