### ISSUE TITLE
🐝 [Bug]Raene's Cleansing bugged

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2348]
## 🐝 Bug report - Quest
Cannot loot https://www.wowhead.com/classic/item=5388/ran-bloodtooths-skulls while on the quest
https://www.wowhead.com/classic/quest=1045/raenes-cleansing (You need it for the quest after, you're expected to have it).
The head shows up as lootable on Ran after killing but it will not let you loot it while on this quest.

### Expected behavior
The boss drops  (https://www.wowhead.com/classic/npc=3696/ran-bloodtooth) the skull and you need it for the quest after for https://www.wowhead.com/classic/quest=1046/raenes-cleansing
You're supposed to be able to loot it earlier when you kill him for the previous quest to kill him, but it won't let you

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version:  1.12.1.5875

Commit Hash:  

OS Client: Win 10
OS Server:  Win 10

### Crashlog

- None

**Comment by ShiyoKozuki** [comment]
Pretty sure item = 5388 just needs to be set to 100 instead of -100 in creature_loot_template to fix this but I don't know how to commit a migration

**Comment by NickTyrer** [comment]
Closed here #1970
