### ISSUE TITLE
🐝 [Bug]List of quests bugged when more than 1 person loots

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2349]
## 🐝 Bug report - Quest
It seems a lot of these have been audited and fixed over the years of pserver development, but here's a list of ones still unfixed:

https://www.wowhead.com/classic/quest=335/a-noble-brew
Party member looted one of the items below
I then cannot loot one of the items below. I can open it, but nothing is inside it to pick up, or it depops for 5m+ plus.
Most of them do not depop but when you try to loot them they are "empty", simply relogging allows you to loot them, which seems buggy.
Relogging does not fix the ones that despawn for 5 minutes, however, on Classic Era these chests/containers/etc respawn within seconds and not 5 minutes.

https://www.wowhead.com/classic/item=1349/abercrombies-crate for 
https://www.wowhead.com/classic/quest=134/ogre-thieves

https://www.wowhead.com/classic/object=142076/claras-fresh-apples for https://www.wowhead.com/classic/quest=2746/items-of-some-consequence

https://www.wowhead.com/classic/item=4433/waterlogged-envelope for
https://www.wowhead.com/classic/quest=637/sully-balloos-letter

https://www.wowhead.com/classic/item=5852/fuel-regulator-blueprints from the chest for
https://www.wowhead.com/classic/quest=1182/goblin-sponsorship

All keys bugged
https://www.wowhead.com/classic/quest=651/stones-of-binding 

https://www.wowhead.com/classic/item=3659/worn-leather-book for
https://www.wowhead.com/classic/quest=540/preserving-knowledge

### Expected behavior
Should be able to loot it after someone else does immediately or within ~20 seconds.

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by Wall-core** [comment]
Can you include video proof of this from vanilla/classic/era?

**Comment by ShiyoKozuki** [comment]
It's very clearly bugged because RELOGGING allows you to get loot from the objects immediately. For the ones that despawn for 5 minutes, relogging doesn't fix.
I don't have a video for the ones that despawn on Classic Era.

**Comment by ShiyoKozuki** [comment]
Ogre Thieves does not despawn on classic
https://youtu.be/04pPwoHKfIA?t=380

Tear of Tiloa for a Noble Brew despawns then immediately respawns (on here, it doesn't despawn, and cannot be looted after someone else just looted it, relogging lets you loot it)
https://youtu.be/-oiwhnTRjqI?t=147

**Comment by ShiyoKozuki** [comment]
So far every other quest container seems to be fixed besides ones on this list that I've encountered. So someone went through and fixed most of them. Unsure how to fix the rest.

**Comment by NickTyrer** [comment]
Closed here #1970
