### ISSUE TITLE
Torwa Pathfinder wrong gossip menu

### ISSUE THREAD

**Issue by GrenderG** [vmangos/core#235]
**Current behavior**: 
When you select `Who is this Lar'korwi you spoke of?` dialog option from **Torwa Pathfinder**, the gossip menu of **Jes'rimon** appears.

**Expected behavior**: 
When `Who is this Lar'korwi you spoke of?` option is selected from **Torwa Pathfinder**, this text should appear and that's all:

```
The ravasaur here in Un'goro seems to be related to the raptors of the barrens-- highly intelligent, volatile, and with a sense or code of conduct. The Greatest of there that I have encountered is Lar'korwi. He is one of the most dangerous beasts I've ever seen. In taurahe, Lar'korwi means "Sharp Claw," but that does not do him justice. 

Do not underestimate Lar'korwi if you ever plan on hunting him, but I will help you in any way I can if you do. 
```

https://wow.gamepedia.com/Jes%27rimon
https://wowwiki.fandom.com/wiki/Torwa_Pathfinder

**Comment by alexkulya** [comment]
Fix:
<pre>
UPDATE `gossip_menu_option` SET `action_menu_id` = 2191 WHERE `menu_id` = 2188 AND `id` = 0 AND `action_menu_id` = 2189;

-- Free entry
INSERT INTO `gossip_menu` (`entry`, `text_id`, `condition_id`) VALUES
(2191, 2835, 0);
</pre>
