### ISSUE TITLE
🦂 [Bug]Gnomergan polish / minor bugs

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2351]
## 🦂 Bug report - Dungeon
alarm-a-bomb 2600 bugged cant be attacked and won't aggro
dark iron agent bombs say "Pet will be armed" not "dark iron land mine will be armed"

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by ratkosrb** [comment]
The Alarm-a-bomb 2600 is not supposed to be attackable. He is part of Kernobee's escort quest.
