### ISSUE TITLE
🐛 [Bug] Kill Princess Moira Bronzebeard , item cannot be allocated 

### ISSUE THREAD

**Issue by yjfyy** [vmangos/core#2353]
🐛 Bug report
Kill Princess Moira Bronzebeard , item cannot be allocated，Team members randomly obtain

### Steps to reproduce
1.  team up
2.  .go 1369 -797 -91 230
3.  .namego xxxx
4.  Kill Princess Moira Bronzebeard
5.  pickup

Client Version:
  - 1.12.1.5875

Commit Hash:  https://github.com/vmangos/core/tree/363ef19db69e8c4e92250e9ebc4896a98e1e49cd

OS Client: Win 10
OS Server: Win 10

Crashlog
- None

**Comment by Gamemechanicwow** [comment]
Only those who've completed the quest to save Princess Moira Bronzebeard will be eligible for loot.

**Comment by yjfyy** [comment]
I see

**Comment by yjfyy** [comment]
I see
