### ISSUE TITLE
🐛 [Bug]Ret aura breaks poly on ranged mobs with bows/throwing weapons/etc

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2355]
## 🐛 Bug report
If a projectile is mid flight and you poly, it will proc ret aura and break sheep.

### Expected behavior
Shouldn't do this

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version:  1.12

Commit Hash:   newest

OS Client:  win 10
OS Server:  win10

### Crashlog

- None

**Comment by Wall-core** [comment]
Please include video footage of correct behavior from vanilla/classic/era in order to confirm this behavior.

**Comment by NickTyrer** [comment]
Reopen if proof is supplied
