### ISSUE TITLE
🐛 [Bug]Syndicate Conjurer's in Stormgarde (Arathi Highlands) wrong spell? 

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2360]
## 🐛 Bug report
![image](https://github.com/vmangos/core/assets/58101246/cb4267b9-ae8e-46e8-8a99-00a218b7eeda)
Syndicate Conjurer's  cast "Bright Campfire" which is a campfire.

### Expected behavior
Shouldn't cast this, seems to be a player only spell(normal campfire for cooking)

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version:  1.12.1

Commit Hash:   current

OS Client:  win10
OS Server:  win10

### Crashlog

- None

**Comment by Daribon** [comment]
It should cast it, however only outside combat. The actual issue is that there are permanently spawned campfires atm, which should not exist.
