### ISSUE TITLE
🐝 [Bug]The Exorcism (Mage quest)

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2365]
## 🐝 Bug report - Quest
Bug 1) If someone else turns in any quests to Tabetha after you start this quest, she stands in place and does nothing until the quest fails. Once the quest fails, she summons the demon. Abandoning then reaccepting the quest causes bug 2 to happen, which makes her summon the Demon of the orb twice in a row.
Bug 2) If you start the quest while a Demon of the orb is currently up she will channel to summon it forever until the demon is killed, then immediately resummon it.

### Expected behavior
Someone else turning in another quest mid-RP to the summoning ritual part shouldn't bug her out

### Steps to reproduce

1. accept "The Exorcism"
2. Have another player turn in a quest

### Version & Environment

Client Version:  1.12.1

Commit Hash:  newest

OS Client:  win10
OS Server:  win 10

### Crashlog

- None

**Comment by ratkosrb** [comment]
Cannot reproduce the issue. She cannot be interacted with by other players while summoning the demon.


https://github.com/vmangos/core/assets/35845488/f7cd168d-4ed4-478c-acf7-c72afa79126d

**Comment by ShiyoKozuki** [comment]
> Cannot reproduce the issue. She cannot be interacted with by other players while summoning the demon.
> 
>  Untitled.mp4

The other person needs to turn in a quest to her(was a paladin turning in a dungeon quest) before she even starts to walk away to bug her out.
She just stood in the house until the timer ran out and then went and summoned after my quest failed.
It might be an extremely niche case scenario where a quest has to be turned in the spit second someone starts the mage quest.

**Comment by ratkosrb** [comment]
She starts walking instantly when you accept the quest so i dont get how its possible.
