### ISSUE TITLE
🐝 [Bug]Sign of the Earth patrol pathing wrong

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2366]
## 🐝 Bug report - Quest
The "guards" are supposed to patrol directly behind the boss for the quest. They do not. 

### Expected behavior
The "guards" are supposed to patrol directly behind the boss for the quest.
https://youtu.be/ZqN3zVrBvFE?t=45

### Version & Environment

Client Version:  1.12.1

Commit Hash:   current

OS Client:  win10
OS Server:  win10

### Crashlog

- None

**Comment by ratkosrb** [comment]
You have linked a private server video. Notice that it was uploaded on Jun 20, 2019 while classic released on August 26, 2019. Also take a look at the minimap, there is no clock there, so its a video recorded on 1.12 client. Given that the video is in 1080p resolution, there is no way this person recorded the video on official servers in 2006 and waited until 2019 to upload it. That whole channel is private server videos.

**Comment by ShiyoKozuki** [comment]
> You have linked a private server video. Notice that it was uploaded on Jun 20, 2019 while classic released on August 26, 2019. Also take a look at the minimap, there is no clock there, so its a video recorded on 1.12 client. Given that the video is in 1080p resolution, there is no way this person recorded the video on official servers in 2006 and waited until 2019 to upload it. That whole channel is private server videos.

https://www.youtube.com/shorts/_pmAiSIVaXE
There's a ton of videos showing the correct patrol "Guards" pathing

**Comment by ratkosrb** [comment]
That video is cropped and the minimap is not visible.

**Comment by ShiyoKozuki** [comment]
> That video is cropped and the minimap is not visible.

https://youtu.be/IVifXIgvDew?t=59
https://youtu.be/3Np9PQwXT10?t=1600

https://youtu.be/V-a6_2c0dBw?t=43

**Comment by ratkosrb** [comment]
> https://youtu.be/IVifXIgvDew?t=59

This is a video from a 3.3.5 wotlk private server. Notice the calendar icon on the minimap. Notice the dungeon finder icon at the bottom. Notice the incomplete localization on his other videos. Some quest texts are in english because the server is missing localization, while others are in spanish. For example https://www.youtube.com/watch?v=TvqAL_QqutM at 0:02 and 0:30, also notice that the quest giver is even missing gossip text, showing the placeholder "Greetings, name" which is not a thing on official servers!

**Comment by ShiyoKozuki** [comment]
> https://youtu.be/3Np9PQwXT10?t=1600
> 
> https://youtu.be/V-a6_2c0dBw?t=43

https://youtu.be/3Np9PQwXT10?t=1600

https://youtu.be/V-a6_2c0dBw?t=43

These should 100% be Classic, one is during TBC classic, though.

**Comment by ShiyoKozuki** [comment]
> > https://youtu.be/IVifXIgvDew?t=59
> 
> This is a video from a 3.3.5 wotlk private server. Notice the calendar icon on the minimap. Notice the dungeon finder icon at the bottom. Notice the incomplete localization on his other videos. Some quest texts are in english because the server is missing localization, while others are in spanish. For example https://www.youtube.com/watch?v=TvqAL_QqutM at 0:02 and 0:30, also notice that the quest giver is even missing gossip text, showing the placeholder "Greetings, name" which is not a thing on official servers!

These should 100% be classic, one is during TBC classic, though

https://youtu.be/3Np9PQwXT10?t=1600

https://youtu.be/V-a6_2c0dBw?t=43

**Comment by Simp-N** [comment]
What exactly is the issue? In each video the group appears to be different, and in only two of them the guards appear to walk behind the Big Boss Ogre.

Here's another example, from Joana. Go to 28:05
https://youtu.be/Q1deRV5ZJBs?si=89XnLYYyYcuL9glq&t=1685

Big Boss Ogre is walking behind his guards. Given how each example appears to be different, I guess there's some variance in the group layout.
