### ISSUE TITLE
🐝 [Bug] Uldaman Reagent Run

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2367]
## 🐝 Bug report - Quest
Currently gives only 1

### Expected behavior
https://youtu.be/Sj8pRgfh66U?t=1430
https://www.wowhead.com/classic/quest=2202/uldaman-reagent-run#comments
should be mushrooms 1-6 per loot
### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by GoonBoiBarry** [comment]
Do you have any footage of this from classic? Wowhead is not used as a source here.

**Comment by ShiyoKozuki** [comment]
https://youtu.be/Sj8pRgfh66U?t=1430
Looted 3 at this time
