### ISSUE TITLE
🐛 [Bug]Gryphons in Hinterlands should be "Flying" animation

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2369]
## 🐛 Bug report
Gryphons in Hinterlands are not "Flying" animation

### Expected behavior
https://youtu.be/xbPS0qDHmCo?t=487
Should be flying Animation

### Version & Environment

Client Version:  1.12.1

Commit Hash:  current

OS Client:  win10
OS Server:  win10

**Comment by GoonBoiBarry** [comment]
The gryphons are flying on my server. Please provide evidence of the issue you are describing. 

![WoWScrnShot_122123_153247](https://github.com/vmangos/core/assets/146424299/af4cac2c-9a44-4c3c-a2b2-71aa0b400d8b)

**Comment by ShiyoKozuki** [comment]
![image](https://github.com/vmangos/core/assets/58101246/c4be71f2-dcf4-4a23-abcc-98fafc5b948d)

Perhaps it's due to the HD mod, then.
Did not think modding the graphics would cause that, my mistake then.
