### ISSUE TITLE
Gnome Mages Should Have Less Mana (90 less)

### ISSUE THREAD

**Issue by Jokerdddd** [vmangos/core#237]
**Current behavior**: 
Gnome: Level 1, Level 2, Level 3, Level 4, Level 5, etc
 Mana =  225 ,     325,      351 ,     393,      421

Level 6+ (from this point onward difference is always +90 mana, with repack being the one with more max mana)

Source: https://www.youtube.com/watch?v=6aBcfd6BO4Q&t=1764s

**Expected behavior**: 
Gnome: Level 1, Level 2, Level 3, Level 4, Level 5,
 Mana =  225 ,     250,      276 ,     303,      331

Source: https://www.youtube.com/watch?v=ul1X2oeRXDk&t=1018s

**Comment by ratkosrb** [comment]
Need to know if the intellect was the same.

**Comment by NickTyrer** [comment]
@ratkosrb I have compared classic to vmangos and it looks like levels 2 and 4 provide the wrong stats
![Untitled](https://user-images.githubusercontent.com/22723839/76882624-d4902b80-6872-11ea-94e7-2daa7d5d4129.png)

**Comment by NickTyrer** [comment]
Looks like human, undead and troll mages stats are also slightly out.

**Comment by ulfgebhardt** [comment]
@NickTyrer Would you be willing to PR this? <3

**Comment by NickTyrer** [comment]
@ulfgebhardt This issue should be combined with #902 as it is not a case of just adjusting the stats unfortunately.

**Comment by ulfgebhardt** [comment]
So there is a subsystem not properly implemented to reflect the vanilla stats, do I get that right? @NickTyrer

**Comment by NickTyrer** [comment]
@ulfgebhardt I believe so, but cannot confirm 100%

**Comment by ratkosrb** [comment]
Pretty sure its just wrong data.

**Comment by NickTyrer** [comment]
Closed in https://github.com/vmangos/core/commit/0c11862258388ffcc4a82979e590a1d1e49db0a8
