### ISSUE TITLE
🐝 [Bug]Freed from the Hive

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2371]
## 🐝 Bug report - Quest
While in a party, upon accepting this quest, it will ask nearby party members if they would like to accept it. However, after they accept it, it will not complete the quest for them. They have to drop it then re-accept it and have the NPC talk again in order to get completion credit.

### Expected behavior
Credit should be shared to everyone upon completion.

### Version & Environment

Client Version:  1.12.1

Commit Hash:  Newest

OS Client:  win10
OS Server:  win10

### Crashlog

- None

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/9daa4e4f01ab38a08f3c2840a30a897c018648ca
