### ISSUE TITLE
🦂 [Bug]Zul'farrak executioner's key did not drop

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2372]
## 🦂 Bug report - Dungeon
https://www.wowhead.com/classic/npc=7274/sandfury-executioner did not drop 
https://www.wowhead.com/classic/item=8444/executioners-key#dropped-by
This means you can't do the divino-magic-rod quest or the final boss of the dungeon
Group loot, with bots and a 2nd player

### Expected behavior
Key should be 100% drop chance

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version:  1.12.1

Commit Hash:  newest

OS Client:  win10
OS Server:  win10

### Crashlog

- None

**Comment by GoonBoiBarry** [comment]
If you had group loot on with bots, then it could've dropped for one of the bots and they do not loot. To avoid this, make loot free for all. Please stop reporting issues before doing some due diligence and thinking about why your issue is happening. Stop just jumping to conclusions and wasting peoples time.

**Comment by ShiyoKozuki** [comment]
if bots are getting loot, then the bug is a bigger issue than just this.
Bots should be coded to not be considered for loot, then.
Considering there's been multiple commits pushed just to fix bugs I've reported, I don't think I'm wasting anyone's time.
If you're offended by people reporting bugs on a bug report section of the project, consider not reading the bug report section.

**Comment by ratkosrb** [comment]
Bots being eligible for loot is not a bug. Bots are player characters, just controlled by an AI. There shall be no special accommodation for bots in other parts of the core, we should not contaminate the code base with bot specific exceptions. Do not request anything related to bots that would require treating them differently than human controlled players. All bot specifc code should be contained in the PlayerBots folder.
