### ISSUE TITLE
🐛 [Bug]Reflected damage should be "Yellow" in SCT

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2373]
## 🐛 Bug report
![image](https://github.com/vmangos/core/assets/58101246/478488af-b51d-44d8-9591-08d73f1f692a)
Reflected damage is currently "White" in the SCT (Scrolling combat text)
Ret aura, imp fire shield, blessing of sanctuary, holy shield, thorns, etc. 

### Expected behavior
https://youtu.be/STZjFsmmcWY?t=362
Should be "Yellow"

### Version & Environment

Client Version:  1.12.1

Commit Hash:  current

OS Client:  win10
OS Server: win10

### Crashlog

- None

**Comment by ratkosrb** [comment]
This is not a bug, but a difference between vanilla and classic clients.
