### ISSUE TITLE
🐝 [Bug]Calm Before the Storm

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2377]
## 🐝 Bug report - Quest
![image](https://github.com/vmangos/core/assets/58101246/170c679f-06ca-4f05-97e3-0fa5ecfffb56)

It allows me to accept both the horde and alliance version of this quest

### Expected behavior
Horde shouldn't get alliance quests, alliance shouldn't get horde quests.

### Version & Environment

Client Version:  1.12.1

Commit Hash:  current

OS Client:  win10
OS Server:  win10

### Crashlog

- None

**Comment by NickTyrer** [comment]
Closed here #1970
