### ISSUE TITLE
🐛 [Bug]Missing rare in WPL Sorrow Hill

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2378]
## 🐛 Bug report
Lord Maldazzar isn't in sorrow hill

### Expected behavior
Should be up in Sorrow Hill, killed him multiple times when AOE grinding in Sorrow HIll on classic era.
https://www.youtube.com/watch?v=flejEU2n5EQ
https://www.wowhead.com/classic/npc=1848/lord-maldazzar#comments

### Version & Environment

Client Version:  1.12.1

Commit Hash:  newest

OS Client:  win10
OS Server:  win10

### Crashlog

- None

**Comment by mserajnik** [comment]
Lord Maldazzar (ID [`1848`](https://www.wowhead.com/classic/npc=1848/lord-maldazzar)) does exist:

```sql
SELECT `guid`, `position_x`, `position_y`, `movement_type`, `wander_distance` FROM `creature` WHERE `id` = 1848;
-- +-------+------------+------------+---------------+-----------------+
-- | guid  | position_x | position_y | movement_type | wander_distance |
-- +-------+------------+------------+---------------+-----------------+
-- | 52725 |    1061.03 |   -1912.26 |             1 |               5 |
-- +-------+------------+------------+---------------+-----------------+
```

You can confirm ingame by using `.go creature 52725` to teleport directly to him:

![image](https://github.com/vmangos/core/assets/80664890/7813cc67-0b12-435f-b5d3-16680475e5b7)


He currently has random movement ([`movement_type` is `1`](https://github.com/vmangos/core/blob/7e3743d543b327a76217eb09a0cd56c9fbad77b5/src/game/Movement/MotionMaster.h#L39)) instead of fixed waypoint pathing ([`movement_type` is `2`](https://github.com/vmangos/core/blob/7e3743d543b327a76217eb09a0cd56c9fbad77b5/src/game/Movement/MotionMaster.h#L40)) , which might be wrong. However, looking at various videos (e.g., [here](https://youtu.be/iE5le8ec72A?si=yZTnGF8KIKMART4J&t=52) and [here](https://www.youtube.com/watch?v=lKJujKHZ0y0)) it looks like he's probably just supposed to move around randomly in that room.

**Comment by ShiyoKozuki** [comment]
I typed .go creature lord Maldazzar and it wouldn't go to him, was unsure of how to go to him properly.
Name not in the sql so wasn't sure of his guid, so I Tried to use the .go creature command and couldn't find
Is there anyway to go to a creature by name with multiple words in their name?

**Comment by GoonBoiBarry** [comment]
> SELECT `guid`, `position_x`, `position_y`, `movement_type`, `wander_distance` FROM `creature` WHERE `id` = 1848;
> -- +-------+------------+------------+---------------+-----------------+
> -- | guid  | position_x | position_y | movement_type | wander_distance |
> -- +-------+------------+------------+---------------+-----------------+
> -- | 52725 |    1061.03 |   -1912.26 |             1 |               5 |
> -- +-------+------------+------------+---------------+-----------------+

The guid is in mserajnik's comment

**Comment by mserajnik** [comment]
@ShiyoKozuki

You can actually also do `.go creature id <id>` where `<id>` would be `1848` in this case. That's the ID that's also used on Wowhead. E.g., in this example, you can see the `npc=1848` in the URL: https://www.wowhead.com/classic/npc=1848/lord-maldazzar

That's probably the easiest way to teleport to a specific creature.

Other than that, it seems like VMaNGOS does a [`LIKE %%<name>%%` lookup](https://github.com/vmangos/core/blob/7e3743d543b327a76217eb09a0cd56c9fbad77b5/src/game/Commands/TeleportCommands.cpp#L461) when providing a string so just using `.go creature Maldazzar` would probably work, for example. It should teleport to the first creature found (if that query would have multiple results); I am not at home to confirm this right now though.

**Comment by ShiyoKozuki** [comment]
> @ShiyoKozuki
> 
> You can actually also do `.go creature id <id>` where `<id>` would be `1848` in this case. That's the ID that's also used on Wowhead. E.g., in this example, you can see the `npc=1848` in the URL: https://www.wowhead.com/classic/npc=1848/lord-maldazzar
> 
> That's probably the easiest way to teleport to a specific creature.
> 
> Other than that, it seems like VMaNGOS does a [`LIKE %%<name>%%` lookup](https://github.com/vmangos/core/blob/7e3743d543b327a76217eb09a0cd56c9fbad77b5/src/game/Commands/TeleportCommands.cpp#L461) when providing a string so just using `.go creature Maldazzar` would probably work, for example. It should teleport to the first creature found (if that query would have multiple results); I am not at home to confirm this right now though.

Thank you!
