### ISSUE TITLE
🐛 [Bug]Gorishi Egg perma up and evading

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2380]
## 🐛 Bug report
![image](https://github.com/vmangos/core/assets/58101246/46ef1cdb-3f69-41de-8a03-a3a882059c09)

This egg is stuck alive evading and shouldn't even be here
https://www.wowhead.com/classic/npc=9496/gorishi-egg

### Expected behavior
Shouldn't be here as it's spawned by some mob I think? But it should hatch a grub eventually and not be spam evading. Server reboot did not delete it and it's been stuck here for days.

### Steps to reproduce

1. .go creature id 9496

### Version & Environment

Client Version:  1.12.1

Commit Hash:  newest

OS Client:  win10
OS Server:  win10

### Crashlog

- None

**Comment by Daribon** [comment]
duplicate https://github.com/vmangos/core/issues/1779
