### ISSUE TITLE
🐝 [Bug] Anthion's Parting Words, available for both factions.

### ISSUE THREAD

**Issue by gajet5** [vmangos/core#2382]
## 🐝 Bug report - Quest
![image](https://github.com/vmangos/core/assets/3825412/242de2dd-6493-466d-ba10-131484460e42)
https://www.wowhead.com/classic/quest=8959

### Expected behavior
Available for one faction.

### Steps to reproduce
1. Try to get a quest: Anthion's Parting Words

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  No

OS Client: Windows
OS Server: Ubuntu

### Crashlog

- None

**Comment by NickTyrer** [comment]
Closed here #1970
