### ISSUE TITLE
🐛 [Bug]Spamming jump while inside lava makes you immune to lava damage ticks

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2389]
## 🐛 Bug report
If you spam jump while at the top of lava, you're immune to lava damage ticks

### Expected behavior
Should still take damage from lava if spamming jump in it

### Steps to reproduce

1.go into lava
2. Mash spacebar and hold W

### Version & Environment

Client Version:  1.12.1

Commit Hash:  newest

OS Client:  win10
OS Server:  win10

### Crashlog

- None

**Comment by GoonBoiBarry** [comment]
This is not a bug. Lava damage in vanilla occurs on 2 second server ticks, at the same time that your health and mana regen.

https://www.youtube.com/watch?v=0VUJa_An09E

**Comment by ShiyoKozuki** [comment]
It's effortless to do and doesn't even require an addon to do here.

**Comment by GoonBoiBarry** [comment]
In my experience it's effortless on classic too. If you are just spamming jumps though as soon you enter the lava, there is a chance you will sync with the damage ticks while being in the lava, so it can help to know when the ticks happen to adjust your rhythm.

The only requirement is that you are not in lava when the tick occurs, that function's the same on vmangos and classic as far as I know.
