### ISSUE TITLE
Murloc pets should dance.

### ISSUE THREAD

**Issue by GrenderG** [vmangos/core#239]
**Current behavior**: 
They are not dancing.

**Expected behavior**: 
The four murloc pets summoned by these items (https://classic.wowhead.com/search?q=murloc+egg) should be dancing when they are summoned. I have done some research and seems like they should have this aura: https://classic.wowhead.com/spell=24983/baby-murloc-passive that will trigger https://classic.wowhead.com/spell=24984/baby-murloc every 15 minutes, that last spell is a 15 seconds channel that will play baby murloc sounds, but the dance behavior needs to be scripted server-side. I think the emote shouldn't be "one shot", it should play even if moving, but they must stop dancing after 15 seconds, when the channeled spell ends.

P.S.: This is db-related, but these creatures are missing in the database: https://classic.wowhead.com/search?q=baby+murloc

**Comment by Oroxzy** [comment]
classic CE pets also do no random emotes but they should?
diablo https://classicdb.ch/?spell=18873
panda https://classicdb.ch/?spell=19230
zergling https://classicdb.ch/?spell=19226

adding it to creature_template_addon should work?

**Comment by GrenderG** [comment]
I'm having 0 luck making `creature_template_addon` work for companions, everything I put there is being ignored if it's for a pet.

**Comment by Oroxzy** [comment]
yes i just tested its not working but selecting the pet and .aura works

**Comment by schell244** [comment]
Currenlty VMangos treats `Apply Aura: Periodically trigger spell` with hacks. This spells also seems to have this attribute due to https://classic.wowhead.com/spell=24983/baby-murloc-passive 

Maybe this will be fixed, when the flag gets implemented https://github.com/vmangos/core/pull/906 
`SPELL_ATTR_PERIODICALLY_TRIGGER = 0x00000800 // 11 TODO: confirm & implement - periodically trigger spell`

**Comment by magicstone4** [comment]
Any update on this? I loooooooooooooooove that dance.

**Comment by LEO33SoFo** [comment]
Bump.

**Comment by NickTyrer** [comment]
Looks like this is working in trinity https://github.com/TrinityCore/TrinityCore/issues/24973 maybe it can be ported?

**Comment by GrenderG** [comment]
At long last. Now VMaNGOS is fully playable!
