### ISSUE TITLE
🦂 [Bug]Blackrock Depths vault doors don't properly load

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2390]
## 🦂 Bug report - Dungeon
![image](https://github.com/vmangos/core/assets/58101246/ca19030b-486f-4102-976e-4b0f05e7188e)
![image](https://github.com/vmangos/core/assets/58101246/18693b8b-667a-46e0-97d6-0b783795a92b)
![image](https://github.com/vmangos/core/assets/58101246/8feb3cc2-d9d2-48de-ab59-14a3184beff5)

Can't open vault, two of the vault "doors" won't load. Trying to open the chest inside just says "failed attempt".
Object GUIDs in screenshot

### Expected behavior
All doors should load and be clickable

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version:  1.12.1

Commit Hash:  newest

OS Client:  win10
OS Server:  win 10

### Crashlog

- None

**Comment by NickTyrer** [comment]
Unable to reproduce this, are you playing on a fully updated unmodified core?

**Comment by ShiyoKozuki** [comment]
> Unable to reproduce this, are you playing on a fully updated unmodified core?

Yes, the only update I'm missing is the super recent one to onyxia.

**Comment by GoonBoiBarry** [comment]
I also can't reproduce. I remember you mentioned you had a model edit on your client. Maybe a reach, but might be culprit.

**Comment by NickTyrer** [comment]
@ShiyoKozuki Can you retest with a clean client?

**Comment by ShiyoKozuki** [comment]
Tried it without the patch and it seems to properly texture them. I will report this bug to the patch maker. Seems fine here.
Sorry about that.
