### ISSUE TITLE
🐛 [Bug] Venomhide Ravasaur's skin is missing the abiltiy to coat your weapon with Venomhide poison

### ISSUE THREAD

**Issue by twowTurtReynolds** [vmangos/core#2392]
### Expected behavior

By melee attacking this mob, you should eventually get a poison applied to your weapon in the imbue slot.
https://www.wowhead.com/classic/npc=6508/venomhide-ravasaur#comments
### Steps to reproduce

1. Go to a venomhide ravasaur, `.go creature id 6508`
2. Attack it a bunch. Use `.aura 18065` a bunch on yourself for haste to make it obvious
3. Check weapon, see it never gets the poison applied.
4. ...
5. Profit
![image](https://github.com/vmangos/core/assets/151180101/5eabaea7-8791-4dca-9006-7bee70b9c99b)

### Version & Environment

Client Version: 
1.12.1.5875

Commit Hash:  
6f5865accea9c7ef46b0

OS Client: Win on wine
OS Server: Linux

### Crashlog

- None

**Comment by AnonXS** [comment]
Seems the aura passive is not applied to the npc on spawn, seems to be a core issue. (hope this 
Manually doing .aura 14108 to the mob makes it work.

it has 14108 in creature_template in vmangos, still not being applied.
