### ISSUE TITLE
🐝 [Bug] Quest: Root Samples (866)

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#2395]
## 🐝 Bug report - Quest
Item Root Sample (5056) cannot be gathered from herbs in the Barrens.

Previous to the mass herb updates all of the herbs in the Barrens where using the wrong object id's for example Peacbloom's use object 1618 everywhere apart for the Barrens where they use object id 3724. All of the loot tables must now be swapped for:

- [ ] Briarthorn 1621 <-> 3729

- [ ] Bruisweed 1622 <-> 3730

- [ ] Earthroot 1619 <-> 3726

- [ ] Mageroyal 1620 <-> 3727

- [ ] Peacebloom 1618 <-> 3724

Commit Hash: 312da6a

**Comment by NickTyrer** [comment]
Closed Here #1970

**Comment by Wall-core** [comment]
Did this issue include Swiftthistle in barrens? @NickTyrer

**Comment by NickTyrer** [comment]
@Wall-core Wasn't aware of any issue with Swiftthistle, but it could be related. Open a new Issue on the bug tracker and I will take a look at some point.
