### ISSUE TITLE
🐛 [Bug]Scourge invasion bosses spawning without invasion active

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2397]
## 🐛 Bug report
![image](https://github.com/vmangos/core/assets/58101246/0457dc93-ef2e-4e5c-b831-e35c019e6f6a)
![image](https://github.com/vmangos/core/assets/58101246/87c01f44-77f4-4797-ac12-c6664495a5fd)
These two bosses were up. Lord Blackwood didn't spawn the first time I ran Scholomance, but did on the 2nd.

### Expected behavior
Shouldn't be up without the invasion

### Version & Environment

Client Version:  1.12.1

Commit Hash:  newest

OS Client:  win10
OS Server:  win10
 
### Crashlog

- None

**Comment by GoonBoiBarry** [comment]
Can you type .server motd to show what patch your server is currently on?

**Comment by ShiyoKozuki** [comment]
1.12 drums of war

**Comment by GoonBoiBarry** [comment]
3 of the scourge events seem to start on the 1st of Jan and end some time later in the month. I set my server time back before January and after and the events were no longer active.

The event ids and names of these are:
81 - Scourge Invasion - Boss in instance activation
129 - Scourge Invasion - Phase 2 - Invasion Stormwind
130 - Scourge Invasion - Phase 2 - Invasion Undercity

**Comment by ShiyoKozuki** [comment]
> 3 of the scourge events seem to start on the 1st of Jan and end some time later in the month. I set my server time back before January and after and the events were no longer active.
> 
> The event ids and names of these are: 81 - Scourge Invasion - Boss in instance activation 129 - Scourge Invasion - Phase 2 - Invasion Stormwind 130 - Scourge Invasion - Phase 2 - Invasion Undercity

I dont really understand how the events work, but is it a bug or not?

**Comment by GoonBoiBarry** [comment]
I never did the scourge event, but I thought it ended before patch 1.12. If that's true then this should be a bug yes. That's why I left the ids up for developers if they wanna investigate.

**Comment by ShiyoKozuki** [comment]
> I never did the scourge event, but I thought it ended before patch 1.12. If that's true then this should be a bug yes. That's why I left the ids up for developers if they wanna investigate.

The SQL database for events has scourge invasion disabled column all set to "1" for me meaning disabled (their defaults).

**Comment by GoonBoiBarry** [comment]
Yeah, it probably means these sub events should be too, but idk enough about the event to be sure.

**Comment by NickTyrer** [comment]
Event is being overhauled here https://github.com/vmangos/core/pull/1717
