### ISSUE TITLE
🐛 [Bug]There are no fountain water in the Stormwind Trade Zone

### ISSUE THREAD

**Issue by sdpHTF9173** [vmangos/core#2405]
## 🐛 Bug report

There are no fountain water in the Stormwind Trade Zone
![360截图20240103231134464](https://github.com/vmangos/core/assets/87078856/4be6b4d7-0467-44ac-a008-80bcab56f9ee)
Hope to repair and make Storm City more beautiful
### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by Gamemechanicwow** [comment]
Why would it have water? Afaik it was added in cata - and its a client change, unrelated to the server.
