### ISSUE TITLE
Bristleback Shaman deals too much damage with lightning bolt.

### ISSUE THREAD

**Issue by Bzmode** [vmangos/core#241]
**Current behavior**: Lightning bolts hitting anywhere from 12-30

**Expected behavior**: Lightning bolts hit for ~3-6

https://www.twitch.tv/videos/450974401?t=17m42s

**Client version**: 1.12.1

**Comment by ratkosrb** [comment]
Creature uses the same spell id in both cmangos and trinity.

**Comment by AnonXS** [comment]
Maybe hidden malus for s.9532 in low level range related to SPELL_ATTR_LEVEL_DAMAGE_CALCULATION?

**Comment by balakethelock** [comment]
https://www.youtube.com/watch?v=ARBE38OEKJ0&t=3159s footage of the level 3 mob in classic doing lightning bolts for 2-3, and level 4 mob doing lightning bolts for 3-4

Needs a lot more data from classic from all levels to find the true level scaling formula.
