### ISSUE TITLE
🐛 [Bug] Enslaved Demon Summon invalid target

### ISSUE THREAD

**Issue by Darg727** [vmangos/core#2415]
## 🐛 Bug report

When you enslave a demon that has a summon spell and you use the summon spell, the summoned creature is an invalid target for all attacks and spells. This is regardless of the state of the demon. When the demon is killed or dismissed, the summoned creature turns hostile to you and becomes unkillable.

![Screenshot (19)](https://github.com/vmangos/core/assets/78714523/8f3cfd4b-c3b4-40cc-83ea-f7d353b05746)
![Screenshot (20)](https://github.com/vmangos/core/assets/78714523/fd383fa1-b103-4979-83ec-575d9aaba9ad)
![Screenshot (21)](https://github.com/vmangos/core/assets/78714523/7219a67d-2979-4a91-a24f-ed37ae4bea78)

### Expected behavior
Not quite sure, but I don't think it's supposed to create unkillable henchman.

### Steps to reproduce

1.  .go c bleakheart hellcaller
2. Use enslave demon on the above creature
3. Use the enslaved demon's summon demon spells
4. Try to target with any attack or spell.
5. Profit

### Version & Environment

Client Version: 1.12.1.5875

OS Client: Win 10
OS Server: Win 10

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/assets/35845488/c8b37e23-c9d2-4793-8ff2-7ad09b86edc9

Here is what happens on the classic ptr, since you didn't provide any videos how it should work.

**Comment by Wall-core** [comment]
What he means is that on vmangos, if you enslave that hellcaller and then use its ability to summon an imp, and then dismiss the hellcaller, the imp will aggro you but have neutral flag and you cannot attack it back, it will just chase you forever until you die.

**Comment by ratkosrb** [comment]
As you can see in the video, you should not be able to use the pet summoning spells when you enslave the mob. They do not appear on the bar.
