### ISSUE TITLE
🐝 [Bug]Ogre Thieves

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2419]
## 🐝 Bug report - Quest
Same bug as https://github.com/vmangos/core/issues/2417
After looting, it doesn't despawn, and additional players can try to loot it but will have no loot in the loot window until it's loot "respawns" after 30s.

### Expected behavior
Same as https://github.com/vmangos/core/issues/2417
Should either despawn until it has loot inside it or be lootable immediately.

### Crashlog

- None

**Comment by ratkosrb** [comment]
I disagree with this. Chest type gameobjects have a data field for consumable and for loot restock time. This data is from sniffs. We are not going to change the sniff data to make the loot restock instantly.

**Comment by ShiyoKozuki** [comment]
> I disagree with this. Chest type gameobjects have a data field for consumable and for loot restock time. This data is from sniffs. We are not going to change the sniff data to make the loot restock instantly.

They restock in 30 seconds, like every other quest on vmangos that is 1 time loot for a single item.
The issue is their object does not despawn, and they are still clickable without loot.  This is not how anything else on Vmangos behaves
Other objects respawn loot in 30 seconds, but also despawn during that time, or simply do not despawn and always have loot.

These were recently changed from 5 minute respawn to 30 seconds as a bugfix, and that person(tyler or something) for other quests like this, but those already had the object despawn.
These simply did not have the object despawn, and he accidentally missed them. They are bugged.

You aren't changing anything from Classic sniffs, they are bugged in comparison to the other code on vmangos.

**Comment by ratkosrb** [comment]
Why would they be marked as non consumable and have restock time set in the gameobject template if they are meant to despawn? Respawn time is completely different thing, that is set per spawn in the gameobject table, not in the template table. Whether gobject is consumable and the loot restock time is in the gameobject template table which is sniffed.

**Comment by ShiyoKozuki** [comment]
> Why would they be marked as non consumable and have restock time set in the gameobject template if they are meant to despawn? Respawn time is completely different thing, that is set per spawn in the gameobject table, not in the template table. Whether gobject is consumable and the loot restock time is in the gameobject template table which is sniffed.

On retail they don't despawn, but insta restock.
On vmangos they don't despawn, but also don't restock.
That is why I gave two options - either despawn for 30 seconds, or are immediately stocked with loot. 
if you want accurate, it's immediate restock and no despawn.
These are the only two remaining quests I've experienced so far that have this strange "invisible loot" issue. 
I lvled on classic duo, and never ran into this issue.

**Comment by ratkosrb** [comment]
If its supposed to be immediate why isn't the restock time in the gameobject template 0 or 1, but 30 seconds instead?

**Comment by ShiyoKozuki** [comment]
> If its supposed to be immediate why isn't the restock time in the gameobject template 0 or 1, but 30 seconds instead?

I don't know, I'm not a reverse engineer, only a player.

The 30 second respawn is tolerable(5 minutes was awful..), but it seems buggy and nothing else works like it. if it's meant to be, then it's meant to be.

I leveled on Turtle WoW and these quests were like this.
I leveled on classic era duo immediately afterwards, and never ran into this issue. The quests did not have this issue. 
We specifically noted these quests behaving completely different on classic era, because waiting around 5m on multiple quests was really unfun.

This has been bugged on emulators for _years_.

**Comment by ratkosrb** [comment]
Do not mention private servers as examples, we are not emulating a private server. Nor should you argue your point by mentioning how fun or unfun something is, that is completely irrelevant, player satisfaction does not matter to the goals of the project.

Regarding your claim that it is restocked instantly on classic (for which you provided no proof), it is possible that this is a quality of life change they made for classic to reduce bottlenecks just like layering. The restock time is clearly not instant in the original data. If it is restocking instantly like you claim then they must be overriding the db values from the core. I require a video from original vanilla that clearly demonstrates the gameobject in question works the way you claim. Either it should disappear and despawn after being looted in the video, or it gets successfully looted twice (loot it, destroy quest item, loot it again).

**Comment by ShiyoKozuki** [comment]
I mentioned Turtle WOW because it was 5m respawn there, which is based off a much older version of mangos(I think?) to use as an example that it's been bugged for years on emulators. It worked the same way there as it does here, years later. It's only until recently (my recent bug report) that it was fixed on emulators to be 30 seconds. Nowhere did I state that turtle wow is accurate and you should be replicating a private server, I actually stated the opposite.

I don't have access to a classic account without paying Blizzard $15,  and I don't see how an object despawning is QOL?
It still seems weird for something to exist as an object but have no loot, when the majority of  objects _on this project_, do not behave like that, which is why I reported it as a bug, since it seems wrong and out of place.

I didn't report this because I wanted QOL, or change, or edited. I reported this because, as I stated, other objects in this project do not behave the same. You have to wait 30 seconds regardless of if this is changed or not. There is no gameplay benefit from my proposed changes, only consistency.

**Comment by ShiyoKozuki** [comment]
It's 30s respawn on loot RIGHT NOW on vmangos
if you make the object despawn for 30s, its still 30s to loot, but the object isn't clickable with blank "no loot".
That can't possibly be classic QOL because you still have to wait 30s...
There is zero beneficial gameplay impact to anything being suggested. 
My proposed change makes it seem less buggy, because right now, it seems buggy as it doesn't behave like other objects in the game.

**Comment by ratkosrb** [comment]
Nothing will be done without proof from vanilla. The data says 30 seconds.
