### ISSUE TITLE
🐛 [Bug][Error][Console] Loading Aggro Spells Definitions.

### ISSUE THREAD

**Issue by gajet5** [vmangos/core#2422]
## 🐛 Bug report
Spell 6196 listed in `spell_threat` has effects with different targets, threat may be assigned incorrectly
Spell 126 listed in `spell_threat` has effects with different targets, threat may be assigned incorrectly
Spell 16689 listed in `spell_threat` has effects with different targets, threat may be assigned incorrectly
Spell 16810 listed in `spell_threat` has effects with different targets, threat may be assigned incorrectly
Spell 16811 listed in `spell_threat` has effects with different targets, threat may be assigned incorrectly
Spell 16812 listed in `spell_threat` has effects with different targets, threat may be assigned incorrectly
Spell 16813 listed in `spell_threat` has effects with different targets, threat may be assigned incorrectly
Spell 17329 listed in `spell_threat` has effects with different targets, threat may be assigned incorrectly
Spell 633 must be listed in `spell_threat` as first rank for listed custom ranks of spell but not found!
Spell 8092 must be listed in `spell_threat` as first rank for listed custom ranks of spell but not found!

### Expected behavior
There is no error when starting the server.

### Steps to reproduce
1. Start the server.
2. Profit

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  No

OS Client: Windows
OS Server: Ubuntu

### Crashlog

- None

**Comment by ratkosrb** [comment]
Why do you open issues for startup errors? We can see them in the log ourselves, we are not blind.

**Comment by gajet5** [comment]
Because I can't know if you see them. Therefore, I am creating an error report, thereby creating a connection between your eyes and my understanding.
