### ISSUE TITLE
🐛 [Bug][Error][Console] Loading SpellsScriptTarget.

### ISSUE THREAD

**Issue by gajet5** [vmangos/core#2423]
## 🐛 Bug report

Table `spell_script_target`: spellId 4170 listed for TargetEntry 2595 does not have any implicit target TARGET_UNIT_SCRIPT_NEAR_CASTER(38) or TARGET_LOCATION_SCRIPT_NEAR_CASTER (46) or TARGET_GAMEOBJECT_SCRIPT_NEAR_CASTER (40).
Table `spell_script_target`: spellId 4170 listed for TargetEntry 2596 does not have any implicit target TARGET_UNIT_SCRIPT_NEAR_CASTER(38) or TARGET_LOCATION_SCRIPT_NEAR_CASTER (46) or TARGET_GAMEOBJECT_SCRIPT_NEAR_CASTER (40).
Table `spell_script_target`: spellId 4170 listed for TargetEntry 11054 does not have any implicit target TARGET_UNIT_SCRIPT_NEAR_CASTER(38) or TARGET_LOCATION_SCRIPT_NEAR_CASTER (46) or TARGET_GAMEOBJECT_SCRIPT_NEAR_CASTER (40).

### Expected behavior
There is no error when starting the server.

### Steps to reproduce

1. Run Server
2. Profit

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  No

OS Client: Windows
OS Server: Ubuntu

### Crashlog

- None

**Comment by ratkosrb** [comment]
Why do you open issues for startup errors? We can see them in the log ourselves, we are not blind.

**Comment by gajet5** [comment]
Because I can't know if you see them. Therefore, I am creating an error report, thereby creating a connection between your eyes and my understanding.
