### ISSUE TITLE
🚀 [Feature][Partybot] When cloning a bot, there is no enchantment.

### ISSUE THREAD

**Issue by gajet5** [vmangos/core#2425]
## 🚀 Feature
When cloning a bot, there is an enchantment on the clothes.

### Visualization
1. Create an enchanted item on yourself.
2. Copy the bot from yourself.
3. Inspect the bot's items.
4. Profit.

### Benefits, Purpose
Improve bots.

**Comment by ShiyoKozuki** [comment]
This doesn't happen 100% of the time and seems to either be a display bug or random(When you do .partybot load <name>).

**Comment by gajet5** [comment]
I'm talking about the .partybot clone and .partybot add [some]. Not .partybot load

for example, here are 39 copies of my character and all of them without enchanted weapons.

![image](https://github.com/vmangos/core/assets/3825412/307085c0-3edc-4da3-b563-bb82d1be656d)

**Comment by celguar** [comment]
4. Inspect the bot's items.
You are using 1.14, enchants don't even show in inspect, did you try 1.12?

**Comment by ShiyoKozuki** [comment]
All my bots have enchants, load or add. The only time they don't I assume is an inspect bug since sometimes even players won't show proper stats/enchants(like bracers of the boar just say bracers with no boar stats).

**Comment by gajet5** [comment]
OK, I tried it on 1.12 client
Let me show you what it looks like: https://youtube.com/live/A6CZxtaoJ0w?feature=share
