### ISSUE TITLE
Dungeon Elites EXP

### ISSUE THREAD

**Issue by JeromeBadt** [vmangos/core#243]
**Current behavior**: 
Dungeon Elites give 200% EXP

**Expected behavior**: 
Dungeon Elites should give 250% EXP

See:
https://web.archive.org/web/20061117091623/http://www.wowwiki.com/Formulas%3AMob_XP#Elite_Mobs
https://www.twitch.tv/videos/425939728
- lvl 22 elite kill @ 02:46:49: 77 EXP
- lvl 22 dungeon elite kill @ 02:53:20: 96 EXP

**Comment by Bzmode** [comment]
Also note that all major bosses give 500% EXP 
https://youtu.be/j01MfraN6b0?t=892
https://youtu.be/j01MfraN6b0?t=325

**Comment by AnonXS** [comment]
Dungeon Elite 2.5 Exp Multiplier: <https://github.com/cmangos/mangos-tbc/commit/2cce6bb0db1fe89ba4db0e60b405390ef42d92ec#diff-7792c66ece59f8c239b248686a70c4cbR142>

its' more like x2 the current value depending on group level composition. (tested on Cmangos)

dungeon boss xp from video evidence:

| NPC  | Level | PlayerLevel | XP | GroupLevelSum | CMaNGOS |
| --- | --- | --- | --- | --- | --- |
| Rhahk'Zor | level 19 | player level 18 | 184xp | ? | ~ 94|
| Sneed | level 20 | player level 19 | 198xp | ? | ~ 96|
| Sneed's Shreeder | level 20 | player level 19 | 198xp | ? | ~ 96|

Current Cmangos output:
![Unbenannt](https://user-images.githubusercontent.com/19734826/61492193-21a0c280-a9b1-11e9-8d11-520dd7f76978.PNG)
![Unbenannt](https://user-images.githubusercontent.com/19734826/61491616-e5209700-a9af-11e9-8427-512cbb970a9c.PNG)

**Comment by Bzmode** [comment]
If you take 100% x2.5 it's 250% which is all elites in dungeons. If you take 100% x5 it's 500%. 
A brute force way to fix it is to set every dungeon elite in the database to a 1.25x multiplier and every boss to 2.5x. This will change the default elite xp of 200% and turn it into 250% and every boss from 200% to 500%.
