### ISSUE TITLE
🐞 [Bug]Terrain / Objects "eating" spell casts

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2431]
## 🐞 Bug report - Spell

https://github.com/vmangos/core/assets/58101246/f3b523fe-143d-4349-8cca-33dcd6c5f8e3
Some terrain or objects will "eat" your spell cast. This means you can cast the spell, it will use mana/go on cooldown, but does not deal damage.

### Expected behavior
Should either bypass the terrain/object or not allow you to expend resources/cooldowns on a spell that will fail to land. No version of retail WoW has had this bug.

### Version & Environment

Client Version:  1.12.1

Commit Hash:  newest

OS Client:  win10
OS Server:  win10

### Crashlog

- None

**Comment by Wall-core** [comment]
That is client side and simply due to how the spell checks creature type. It's not going on cooldown or using mana in your clip.

**Comment by ShiyoKozuki** [comment]
> That is client side and simply due to how the spell checks creature type. It's not going on cooldown or using mana in your clip.



https://github.com/vmangos/core/assets/58101246/37b4ba82-7378-4982-b075-552c8d9aa07b

New clip with cooldown / resource cost shown. The original clip has no power cost and no cooldown godmode on so I can spam it to show it the bug in action
It is not a client issue - this **does not** happen in any version of Retail WoW.

**Comment by Wall-core** [comment]
And it doesn't happen for me in vmangos either. Your video is not clear in this regard, as having GM cheats on is not a good way to test. What commit are you on? If you've pulled the recent Sapphiron LoS fix, it may be related.

**Comment by ratkosrb** [comment]
Give teleport coordinates for this exact spot.

**Comment by ShiyoKozuki** [comment]
> Give teleport coordinates for this exact spot.

![image](https://github.com/vmangos/core/assets/58101246/550ea8a8-f537-48fb-9d71-c54f670938a1)

**Comment by ShiyoKozuki** [comment]
https://github.com/vmangos/core/assets/58101246/ec88aba6-8ecd-45c6-82f1-cfb83b99d771

video with gps. unlimited power/cd is on, if i turn it off i can only use it once every 15 seconds..it goes on cooldown and uses mana(see last video)
This has been happening since day2 of using vmangos, before the sapphiron LOS commit.

**Comment by Wall-core** [comment]
in two videos, you have untargetable gm cheat on which makes it so that you dont get targeted or put in combat. in the other clip, you arent casting the spell; its fizzling entirely. Can you show a clip with it happening and no cheats?

**Comment by ShiyoKozuki** [comment]
> > That is client side and simply due to how the spell checks creature type. It's not going on cooldown or using mana in your clip.
> 
>  2024-01-12.13-09-38.mp4 
> New clip with cooldown / resource cost shown. The original clip has no power cost and no cooldown godmode on so I can spam it to show it the bug in action It is not a client issue - this **does not** happen in any version of Retail WoW.

that was posted already

**Comment by ShiyoKozuki** [comment]
> in two videos, you have untargetable gm cheat on which makes it so that you dont get targeted or put in combat. in the other clip, you arent casting the spell; its fizzling entirely. Can you show a clip with it happening and no cheats?

yes, i did this already
https://github.com/vmangos/core/issues/2431#issuecomment-1889744468

**Comment by Wall-core** [comment]
target yourself and do the following, one at a time:
.gm off
.gm vis on
.cheat god off
.cheat immunenpc off
.cheat untargetable off
.cheat power off
.cheat cooldown off

**Comment by ShiyoKozuki** [comment]
> target yourself and do the following, one at a time: .gm off .gm vis on .cheat god off .cheat immunenpc off .cheat untargetable off .cheat power off .cheat cooldown off

This was already done in the linked video

https://github.com/vmangos/core/assets/58101246/6bb562c6-0370-41c6-93c1-d7b59208cc40
