### ISSUE TITLE
🐛 [Bug]You can out of range setting Hearth at an Innkeeper

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2432]
## 🐛 Bug report

https://github.com/vmangos/core/assets/58101246/81e46bdb-f1c3-494a-a967-efa8e442feb7
You can be close enough to gossip but too far away from the NPC to land the spell on you, so your hearth won't get set.

### Expected behavior
Shouldn't be able to gossip and not be in the hearth setting spell range at the same time.

### Version & Environment

Client Version:  1.12.1

Commit Hash:  newest

OS Client:  win10
OS Server:  win10

### Crashlog

- None

**Comment by NickTyrer** [comment]
Tested on [943b228](https://github.com/vmangos/core/commit/943b2287892f406799aa88cc9444174577c53638) and this is no longer happening.

**Comment by ShiyoKozuki** [comment]
> Tested on [943b228](https://github.com/vmangos/core/commit/943b2287892f406799aa88cc9444174577c53638) and this is no longer happening.

What fixed it?
