### ISSUE TITLE
Arathi Basin issues

### ISSUE THREAD

**Issue by GrenderG** [vmangos/core#244]
Occasionally a base can have both Alliance and Horde auras, making it impossible to re-take by the attacking team.
![image](https://user-images.githubusercontent.com/8654362/61537956-a97ddf80-aa38-11e9-9019-e44d396927e1.png)
Also, Spirit Guides from both factions are visible at the same time.
![image](https://user-images.githubusercontent.com/8654362/61537981-b7cbfb80-aa38-11e9-9a47-dbe1d115ad6e.png)

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/f940f5887e674ba5486cbd2fa10cd9a7313de372

**Comment by NickTyrer** [comment]
In classic the flag having Alliance and Horde auras happens as well.

**Comment by ulfgebhardt** [comment]
@ratkosrb is this fixed?
