### ISSUE TITLE
💬 [Discussion]Is this intended auto-attack LOS behavior?

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2440]
## 💬 Discussion
I can hit the enemy through the floor at the bottom of the boat.

https://github.com/vmangos/core/assets/58101246/c30286b6-1d5f-4834-ac98-299774d29a80

**Comment by Wall-core** [comment]
Yes in vanilla you can melee through walls.

**Comment by ratkosrb** [comment]
It is intended that LoS does not interrupt melee attacks yes. I have personally tested that.
