### ISSUE TITLE
🐛 [Bug]Bugged mob spawn position

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2444]
## 🐛 Bug report

https://github.com/vmangos/core/assets/58101246/3e0716d8-0550-497f-a304-2bf74bb6bd37

 This mob spawn is always bugged and won't path to you but can be hit. He's stuck and can't move or be looted.
He's bugged every single time I've been to hinterlands and done this quest by him.

**Comment by ratkosrb** [comment]
mmaps are bugged in this spot

**Comment by ratkosrb** [comment]
Oh actually his Z coordinate was in the sky for some reason.
