### ISSUE TITLE
Server crash causing collective disconnection 🐛 [Bug]

### ISSUE THREAD

**Issue by zw-su** [vmangos/core#2445]
## 🐛 Bug report

server log:
mangosd[4149030]: /wow/run/bin/mangosd(_ZNK14dtNavMeshQuery8findPathEmmPKfS1_PK13dtQueryFilterPmP>
Jan 21 21:53:35 C20240111072757 mangosd[4149030]: /wow/run/bin/mangosd(_ZN8PathInfo13BuildPolyPathERKN3G3D7Vector3ES3_+0x49f) [0x>
Jan 21 21:53:35 C20240111072757 mangosd[4149030]: /wow/run/bin/mangosd(_ZN8PathInfo9calculateEfffbb+0x250) [0x5577aff7dca0]
Jan 21 21:53:35 C20240111072757 mangosd[4149030]: /wow/run/bin/mangosd(_ZN8Movement14MoveSplineInit6MoveToERKN3G3D7Vector3Ej+0x89>
Jan 21 21:53:35 C20240111072757 mangosd[4149030]: /wow/run/bin/mangosd(_ZN23RandomMovementGenerator18_setRandomLocationER8Creatur>
Jan 21 21:53:35 C20240111072757 mangosd[4149030]: /wow/run/bin/mangosd(_ZN23RandomMovementGenerator11UpdateAsyncER8Creaturej+0x9b>
Jan 21 21:53:35 C20240111072757 mangosd[4149030]: /wow/run/bin/mangosd(_ZN4Unit6UpdateEjj+0x3db) [0x5577b00c9c7b]
Jan 21 21:53:35 C20240111072757 mangosd[4149030]: /wow/run/bin/mangosd(_ZN8Creature6UpdateEjj+0xda) [0x5577affd3b0a]
Jan 21 21:53:35 C20240111072757 mangosd[4149030]: /wow/run/bin/mangosd(_ZN3Map23UpdateCellsAroundObjectEjjPK11WorldObject+0x4c5) >
Jan 21 21:53:35 C20240111072757 mangosd[4149030]: /wow/run/bin/mangosd(_ZN3Map6UpdateEj+0x2b1) [0x5577aff59f81]
Jan 21 21:53:35 C20240111072757 mangosd[4149030]: /wow/run/bin/mangosd(_ZN10ThreadPool9worker_sq6doWorkEv+0x54) [0x5577b04c1c54]
Jan 21 21:53:35 C20240111072757 mangosd[4149030]: /wow/run/bin/mangosd(_ZN10ThreadPool12worker_mysqlINS_9worker_sqEE6doWorkEv+0x1>
Jan 21 21:53:35 C20240111072757 mangosd[4149030]: /wow/run/bin/mangosd(_ZN10ThreadPool6worker4loopEv+0xcb) [0x5577b04c3dbb]
Jan 21 21:53:35 C20240111072757 mangosd[4149030]: /lib/x86_64-linux-gnu/libstdc++.so.6(+0xdc253) [0x7f30847dd253]
Jan 21 21:53:35 C20240111072757 mangosd[4149030]: /lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7f3084465ac3]
Jan 21 21:53:35 C20240111072757 mangosd[4149030]: /lib/x86_64-linux-gnu/libc.so.6(+0x126850) [0x7f30844f7850]
Jan 21 21:53:35 C20240111072757 mangosd[4149030]: 
Jan 21 21:53:35 C20240111072757 kernel: mangosd[4149073]: segfault at ffffffffffffff80 ip 00007f30847af1ad sp 00007f306d8b0f40 er>
Jan 21 21:53:35 C20240111072757 kernel: Code: ff 48 89 d8 5b c3 0f 1f 80 00 00 00 00 f3 0f 1e fa 55 53 48 83 ec 08 e8 41 ff ff ff>
Jan 21 21:53:54 C20240111072757 systemd[1]: vmmangosd.service: Main process exited, code=killed, status=11/SEGV
Jan 21 21:53:54 C20240111072757 systemd[1]: vmmangosd.service: Failed with result 'signal'.

gdb --bt full：
#9  0x000056232864f4f9 in Unit::Kill (this=<optimized out>, pVictim=<optimized out>, spellProto=0x0, durabilityLoss=<optimized out>) at /wow/vmangos/vm23/src/game/Objects/Unit.cpp:1137
        pPlayerTap = <optimized out>
        pCreatureVictim = <optimized out>
        pPlayerVictim = <optimized out>
        pGroupTap = <optimized out>
        allowLoot = <optimized out>
        damageFromSpiritOfRedemtionTalent = false
        spiritOfRedemtionTalentImmune = <optimized out>
#10 0x00005623286510f7 in Unit::DealDamage (this=0x7fe9e89732c0, pVictim=0x7fe9afcb2b80, damage=<optimized out>, cleanDamage=0x7fe9dfffd740, damagetype=DIRECT_DAMAGE, damageSchoolMask=SPELL_SCHOOL_MASK_NORMAL, spellProto=0x0, durabilityLoss=true, spell=0x0, reflected=false) at /wow/vmangos/vm23/src/game/Objects/Unit.cpp:811
        health = 46
        duel_hasEnded = <optimized out>
        __FUNCTION__ = "DealDamage"
#11 0x00005623286529a8 in Unit::DealMeleeDamage (this=0x7fe9e89732c0, damageInfo=0x7fe9dfffd890, durabilityLoss=<optimized out>) at /wow/vmangos/vm23/src/game/Objects/Unit.cpp:1697
        pVictim = 0x7fe9afcb2b80
        cleanDamage = {damage = 2, attackType = BASE_ATTACK, hitOutCome = MELEE_HIT_NORMAL, absorb = 0, resist = 0}
#12 0x0000562328653466 in Unit::AttackerStateUpdate (this=0x7fe9e89732c0, pVictim=0x7fe9afcb2b80, attType=BASE_ATTACK, extra=<optimized out>) at /wow/vmangos/vm23/src/game/Objects/Unit.cpp:2189
        hitInfo = <optimized out>
        damageInfo = {attacker = 0x7fe9e89732c0, target = 0x7fe9afcb2b80, totalDamage = 87, totalAbsorb = 0, totalResist = 0, subDamage = {{damageSchoolMask = SPELL_SCHOOL_MASK_NORMAL, damage = 87, absorb = 0, resist = 0}, {damageSchoolMask = SPELL_SCHOOL_MASK_NORMAL, damage = 0, absorb = 0, resist = 0}, {damageSchoolMask = SPELL_SCHOOL_MASK_NORMAL, damage = 0, absorb = 0, resist = 0}, {damageSchoolMask = SPELL_SCHOOL_MASK_NORMAL, damage = 0, absorb = 0, resist = 0}, {damageSchoolMask = SPELL_SCHOOL_MASK_NORMAL, damage = 0, absorb = 0, resist = 0}}, blocked_amount = 0, HitInfo = 2, TargetState = 1, attackType = BASE_ATTACK, procAttacker = 4194308, procVictim = 1048584, procEx = 1, cleanDamage = 2, hitOutCome = MELEE_HIT_NORMAL}
#13 0x0000562328654181 in Unit::UpdateMeleeAttackingState (this=this@entry=0x7fe9e89732c0) at /wow/vmangos/vm23/src/game/Objects/Unit.cpp:404
        pVictim = 0x7fe9afcb2b80
        swingError = ATTACK_RESULT_OK
        pPlayer = <optimized out>
#14 0x000056232860559e in Player::Update (this=0x7fe9e89732c0, update_diff=100, p_time=100) at /wow/vmangos/vm23/src/game/Objects/Player.cpp:1603
        now = 1705899979
#15 0x00005623284d85ac in WorldObject::UpdateHelper::UpdateRealTime (time_diff=<optimized out>, now=45053818, this=<synthetic pointer>) at /wow/vmangos/vm23/src/game/Objects/Object.h:674
No locals.
#16 Map::UpdatePlayers (this=this@entry=0x7fea1db92140) at /wow/vmangos/vm23/src/game/Maps/Map.cpp:925
        plr = 0x7fe9e89732c0
        helper = <optimized out>
        now = 45053818
        diff = 100
        updateInactivePlayers = <optimized out>
#17 0x00005623284e3e59 in Map::Update (this=0x7fea1db92140, t_diff=<optimized out>) at /wow/vmangos/vm23/src/game/Maps/Map.cpp:968
        updateMapTime = 45053818
        sessionsUpdateTime = 0
        start = <optimized out>
        playersUpdateTime = <optimized out>
        activeCellsUpdateTime = <optimized out>
        objectsUpdateTime = <optimized out>
        visibilityUpdateTime = <optimized out>
        playersUpdateTime2 = <optimized out>
        additionnalWaitTime = <optimized out>
        additionnalUpdateCounts = <optimized out>
        __FUNCTION__ = "Update"
        packetBroadcastSlow = <optimized out>
#18 0x0000562328a4bc54 in std::function<void ()>::operator()() const (this=<optimized out>) at /usr/include/c++/12/bits/std_function.h:591
No locals.
#19 ThreadPool::worker_sq::doWork (this=0x7fe9ebe1ff20) at /wow/vmangos/vm23/src/shared/ThreadPool.cpp:251
        i = <optimized out>
#20 0x0000562328a4ddbb in ThreadPool::worker::loop (this=0x7fe9ebe1ff20) at /wow/vmangos/vm23/src/shared/ThreadPool.cpp:195
        remaning = <optimized out>
#21 0x00007fea3bc6d253 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#22 0x00007fea3b8f5ac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140642578675952, 529216591713207931, 140642462201408, 0, 140643998324688, 140642578676304, -537168259253860741, -536965533890967941}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#23 0x00007fea3b987850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

### Steps to reproduce

1. I don't know what caused it, so I can't reproduce it
2.
3.
4. ...
5. Profit

### Version & Environment

  Client Version:
  - 1.12.1.5875
  - 1.11.2.5464
  - 1.10.2.5302
  - 1.9.4.5086
  - 1.8.4.4878
  - 1.7.1.4695
  - 1.6.1.4544
  - 1.5.1.4449
  - 1.4.2.4375
  - 1.3.1.4297
  - 1.2.4.4222
-->
Client Version: 
1.12.1.5875

Commit Hash:  

OS Client: 
OS Server: 
ubuntu 22.04
### Crashlog

- None

**Comment by zw-su** [comment]
=The content after the number cannot be displayed, it is all <optimized out>

**Comment by zw-su** [comment]
=The content after the number cannot be displayed, it is all “<optimized out>“

**Comment by zw-su** [comment]
=The content after the number cannot be displayed, it is all “optimized out”

**Comment by Wall-core** [comment]
What version of mmaps are you using? Try updating to the latest version and rebuilding, it should fix this issue.

**Comment by zw-su** [comment]
Thank you very much for your answer. I will give it a try first

**Comment by ratkosrb** [comment]
Update to latest version and set this in config:

mmap.randomMovement = 0
