### ISSUE TITLE
🐛 [Bug] Server Crushed

### ISSUE THREAD

**Issue by william19831103** [vmangos/core#2447]
![Crush_20240123115822](https://github.com/vmangos/core/assets/15699126/25eda3a0-46ef-4772-97bb-f6cdc9f5d23e)

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by ratkosrb** [comment]
Try to set Continents.MotionUpdate.Threads to 1 in mangosd.conf and try again.

**Comment by cbcs** [comment]
This is a long-standing bug

**Comment by ratkosrb** [comment]
Update to latest version and set this in config:

mmap.randomMovement = 0
