### ISSUE TITLE
🐛 [Bug] Spells can be casted for a brief window while strafing (if using the turn key while holding right mouse, not if keybound to strafe)

### ISSUE THREAD

**Issue by GoonBoiBarry** [vmangos/core#2448]
## 🐛 Bug report
Okay so this is a weird one. If you start casting a spell while standing still and then attempt to strafe by holding the right mouse and using the turn keybinds, your spells will continue to cast for about half a second. It's important to note that you have to use the turn keys with the mouse, the regular strafe key interrupts.

### Expected behavior
Spell should be interrupted.

### Steps to reproduce

1. Create a priest or class with self healing cast.
2. Make sure you have turn keys bound to something.
3. Cast the heal on yourself, then while holding the right mouse button press a turn key while the cast is happening
4. ...
5. Profit

### Version & Environment

  - 1.12.1.5875

Commit Hash:  

OS Client: Win 10
OS Server:  Win 10

### Crashlog

- None

**Comment by Wall-core** [comment]
client handles interrupts. some spells don't have proper interrupt flags set in client, so the delay between you moving and it canceling is due to the delay of the server processing and responding to the movement with an interrupt

**Comment by GoonBoiBarry** [comment]
This is not what I'm describing. It is 100% reproducible and every other kind of movement instantly interrupts 100% of the time. It is only the specific inputs I describe that don't.

**Comment by Wall-core** [comment]
yes, likely the client sees this combination of inputs as "not moving" but turning, and thus doesnt force cancel the cast

**Comment by GoonBoiBarry** [comment]
That's probably true, just figured I'd report in case it's serverside. Cool tech too, the cast can actually go off well after movement. Might be useful with cast like slam

**Comment by NotRealySly** [comment]
I don't think the issue comes from the client side; I have the same problem with the 1.14 client using HermesProxy. Moreover, this problem didn't exist with the 1.12 client. 
This issue is very bothersome as it gives a considerable advantage to casters. Even when you cast a spell and try to turn away from the target, this 'latency' is still present, and the spell goes off anyway. So, it's not just a problem with character movement or strafing.

**Comment by cpevors** [comment]
The problem certainly exists with the 1.12 client; it's both what the OP indicated he/she uses, and I just replicated the issue with my 1.12 client.

**Comment by ratkosrb** [comment]
When you begin to strafe with the strafe keys, the client cancels the spell cast on its own, it sends CMSG_CANCEL_CAST. When you do it by holding the mouse and turning, it does not cancel the spell on its own, it's the server which cancels it when it receives the movement packet.
