### ISSUE TITLE
🐛 [Bug] Can cast spells on npcs that are not in line of sight to receive effect

### ISSUE THREAD

**Issue by GoonBoiBarry** [vmangos/core#2449]
## 🐛 Bug report
There appears to be two separate line of sight checks that are dysynced. If there is a line of sight object between just the player's waist and the npc, the player will still be able to cast and use mana for the spell, but the cast will have no effect. It appears the check of whether you can cast comes from the player's head, whereas the check for the effect going off comes from around the waist.

### Expected behavior
Either the waist line of sight is wrong, or the head line of sight.

### Steps to reproduce

1. Create an undead priest.
2. .go xyz 1839 1611 96
3. Without moving from that spot, cast lesser heal at Deathguard Saltain, who is across from the stairs and watch as no heal visual or effect occurs.
4. Step out from the steps into proper los of Saltain and cast it again to show that the spell visual/effect works and los is the issue.
5. Profit

### Version & Environment

  - 1.12.1.5875

Client Version: 

Commit Hash:  

OS Client: Win 10
OS Server: Win 10

### Crashlog

- None

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/assets/35845488/29ac1ff6-f72e-4caa-ade0-a29f6732b0dc

I can't reproduce it.
