### ISSUE TITLE
🐝 [Bug]Winterfall Runners crate drop

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2451]
## 🐝 Bug report - Quest
https://www.wowhead.com/classic/item=12829/winterfall-crate
Can only be looted by 1 person in the party

### Expected behavior
Should be able to be looted by everyone in the party

### Steps to reproduce

1. .go creature id 10916
2. kill
3. loot
4. ...
5. Profit

**Comment by ratkosrb** [comment]
Whether an item can be looted by everyone is part of the flags on the item template. Those should all be correct already. Please provide video proof of the claim.

**Comment by ShiyoKozuki** [comment]
My mistake
