### ISSUE TITLE
🐛 [Bug]Creatures should not enrage mid spell and interrupt the spell cast

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2452]
## 🐛 Bug report

https://github.com/vmangos/core/assets/58101246/96253969-2fec-4f94-85ab-12bb037f031d

Creatures  with enrage or enrage-like spells(trolls, Jaedenar Warlock unholy frenzy, etc) should not be cast while they are already casting a spell and thus interrupting the spell to enrage.

### Expected behavior
https://youtu.be/HTrPPTexwn4?t=17
Should not interrupt their spell to cast enrage.

### Steps to reproduce

1. .go creature id 7120
2. .go creature id 595
3.
4. ...
5. Profit

### Version & Environment

Client Version:  1.12.1

Commit Hash:  newest

OS Client:  win10
OS Server:  win10

### Crashlog

- None

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/8a1df629e4b068e7fff6f9ef6f965751b201586c
