### ISSUE TITLE
🐛 [Bug] Crash in BattleGroundQueue

### ISSUE THREAD

**Issue by william19831103** [vmangos/core#2457]
### Expected behavior

some player joined battleground queue and loged out, then server may crush.
![Crush 1 20240126204125](https://github.com/vmangos/core/assets/15699126/24f351e0-f525-403b-be56-4d29eb1e6d77)
![Crush 2 20240126204140](https://github.com/vmangos/core/assets/15699126/ad580dfc-886b-499f-8a1b-660544af705e)

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by Gamemechanicwow** [comment]
Linenumbers doesn't match up with clean vmangos code.. looks like vmangos-eluna.
