### ISSUE TITLE
Position of Cenarion Emissary Blackhoof

### ISSUE THREAD

**Issue by GrenderG** [vmangos/core#246]
**Current behavior**: 
Cenarion Emissary Blackhoof is not placed in the right spot.

**Expected behavior**: 
Cenarion Emissary Blackhoof should be in the Valley of Strength. (https://wowwiki.fandom.com/wiki/Cenarion_Emissary_Blackhoof?oldid=149521)

Fixes:
```sql
-- Cenarion Emissary Blackhoof correct location
update creature set position_x = 1658.71, position_y = -4348.8, position_z = 29.2574, orientation = 4.39823 where guid = 6504;
```

**Comment by ratkosrb** [comment]
How do you know he is supposed to be spawned there? This npc is not in classic yet.

**Comment by GrenderG** [comment]
Check the link I posted, it's from 2006. Also, I have more evidence from my own Vanilla screenshots:

![imagen](https://user-images.githubusercontent.com/8654362/76794445-53c82580-67c7-11ea-885e-4e713613b9ec.png)

The exact coords are taken from a TBC DB where the position was correct.

**Comment by NickTyrer** [comment]
Confirmed in classic
![Untitled](https://user-images.githubusercontent.com/22723839/80860829-40cbc080-8c62-11ea-94c5-5f3b534ae1d4.png)

**Comment by NickTyrer** [comment]
@ratkosrb this is now fixed
