### ISSUE TITLE
🐝 [Bug] Quest 1173 (Challenge Overlord Mok'morokk) not completable

### ISSUE THREAD

**Issue by Wall-core** [vmangos/core#2465]
The quest automatically fails upon reducing Overlord Mok'morokk to the required amount of health.

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/assets/35845488/fe178902-44d6-4e54-b251-66e5fe4c7d0c

I can't reproduce the issue. It says completed not failed.

**Comment by ratkosrb** [comment]
Maybe the script rows got re-ordered for you and were executing in wrong order. Try if this solves it for you.
https://github.com/vmangos/core/commit/dba1d17b2a1fdd5757ac49d92b363001a6d517d7

**Comment by cpevors** [comment]
> Maybe the script rows got re-ordered for you and were executing in wrong order. Try if this solves it for you. [dba1d17](https://github.com/vmangos/core/commit/dba1d17b2a1fdd5757ac49d92b363001a6d517d7)

This solved my issue. Not sure if @Wall-core is still having issues this many months later?
