### ISSUE TITLE
🐝 [Bug] Supplies for the Crossroads quest can be accepted before completing Disrupting the Attacks

### ISSUE THREAD

**Issue by GoonBoiBarry** [vmangos/core#2466]
## 🐝 Bug report - Quest
The quest Supplies for the Crossroads can be accepted before completing it's prerequisite Disrupting the Attacks

### Expected behavior
Should only be acceptable after completing Disrupting the Attacks https://www.wowhead.com/classic/quest=5041/supplies-for-the-crossroads

### Steps to reproduce

1. Create fresh horde character, set to level 10
2. .tele crossroads
3. Talk to Thork to see that both quest are available from the get go
4. ...
5. Profit

### Version & Environment

Client Version: - 1.12.1.5875

Commit Hash:  

OS Client: Win 10
OS Server: Win 10

### Crashlog

- None

**Comment by NickTyrer** [comment]
This is the correct behaviour https://github.com/vmangos/core/issues/1540
