### ISSUE TITLE
🐝 [Bug]Bijou's Belongings quest ID 5001

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2468]
## 🐝 Bug report - Quest
Has a bugged spawn position
![image](https://github.com/vmangos/core/assets/58101246/c758a5ae-db60-4700-9f35-6ddb868cffc2)

### Expected behavior
All spawns should be in the game  world

### Steps to reproduce

1. .go -28 -433 -18 
2.
3.
4. ...
5. Profit

**Comment by ratkosrb** [comment]
What's bugged about it? I don't get what this issue is about.

![Untitled](https://github.com/vmangos/core/assets/35845488/5884996f-7e0e-4f73-8624-2bbeb3c384ec)

**Comment by ShiyoKozuki** [comment]
How were you able to go there? Anytime I tried it would put me into the sky
The chest also wasn't anywhere
I did .go -28 -433 -18

**Comment by ratkosrb** [comment]
You can teleport to a specific spawn by guid.

.go o 54964

Make sure you don't have any mods that could have altered the map.
