### ISSUE TITLE
🐛 [Bug] Crash in InstancePlayerBind* Player::GetBoundInstance(uint32 mapid)

### ISSUE THREAD

**Issue by william19831103** [vmangos/core#2471]
## 🐛 Bug report

![Crush boundinstance 1 20240129211735](https://github.com/vmangos/core/assets/15699126/2a8992b7-e67f-4347-92b9-bb2ea7bf4e8f)
![Crush bound 2 20240129211806](https://github.com/vmangos/core/assets/15699126/0db4764f-168c-473c-969a-4ce2b04e8b2c)

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by ratkosrb** [comment]
I'm hoping this will fix it https://github.com/vmangos/core/commit/863d7e8974b614bd4371825c6299d97928d1a9e9
