### ISSUE TITLE
🐛 [Bug]Battlebots no longer autofill bg queues after typing .battlebot removeall

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2473]
## 🐛 Bug report
Battlebots autofill BGs until I type .battlebot removeall
Not talking about the current bg, but if I queue a new one they won't autofill the next

### Expected behavior
Should keep autofilling bgs regardless of if I remove battlebots or not

**Comment by ratkosrb** [comment]
That's not a bug. Auto join is intentionally disabled to make sure there are no bots once you type removeall.
