### ISSUE TITLE
🐛 [Bug]Char premade spec saving command

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2476]
## 🐛 Bug report
If targetting nothing, you can save spec and it will create a blank template with no spells

### Expected behavior
Should throw an error that nothing is targetted and not create a blank template

### Steps to reproduce

1. target nothing
2. type .char premade savespec <anything here>
3.
4. ...
5. Profit

**Comment by ratkosrb** [comment]
The command does not require a target, it always saves your own character's spec, but you must logout after setting your talents before saving them.

**Comment by ShiyoKozuki** [comment]
I did log out, and it saved blank templates into the db

**Comment by ratkosrb** [comment]
I don't believe you. You must have put in the talents and used command without reloging first. The command reads your spells from the db, so if you've learned anything during this session, it wont be in the db, and thus wont get saved.  I created all the spec templates with the command, so it definitely works.

**Comment by ShiyoKozuki** [comment]
It's happened to me over 3 times and I've only added 20 specs. Every single time it has the character has full talents and spells learned.
There's no rhyme or reason for what causes it, but it's bugged.
