### ISSUE TITLE
🔧 The issue of equipment drop in Molten core

### ISSUE THREAD

**Issue by zw-su** [vmangos/core#2477]
## 🔧 Support Request

1. I set up horde and alliances to form teams in mangos.conf
2.  when the leader is a horde, the knight's equipment will not drop
3.  When the team leader is in an alliance, shaman equipment will not drop
4.  How can I make all the equipment drop?
### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  

OS Client: 
OS Server:  ubuntu 22.04

### Steps to reproduce
1.
5.
6.
7. ...
8. Profit

**Comment by Wall-core** [comment]
This is correct behavior. If you wished to modify it, you'd have to change the condition entry in creature_loot_template, but that would be custom. this is not a bug.

**Comment by zw-su** [comment]
thanks,  this is not a bug.  condition_id  in creature_loot_template is 0, But I don't know what the change will take effect

**Comment by ShiyoKozuki** [comment]
Shaman gear could drop in MC for alliance, and paladin for horde in early Vanilla.
Not sure when / if it was ever fixed.

**Comment by zw-su** [comment]
Thank you for your answers, I found it  in table reference_loot_template
