### ISSUE TITLE
🐛 [Bug]Rogue / Feral bots rarely use openers

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2480]
## 🐛 Bug report
They will very rarely use openers. It's coded, but they usually auto-attack from stealth and unstealth themselves before they can use an opener.

### Expected behavior
Shouldn't auto-attack from stealth and unstealth themselves.

**Comment by ratkosrb** [comment]
It would over complicate the code to not always auto attack. Every update cycle it would have to check are you a stealth class, then do you have a stealth ability, then is that aura active, then do you have any stealth opener spells. It would turn generic code into a mess of exceptions. I don't want to change it. Bots are not supposed to be 200 IQ. I want their behavior to be simplistic.

**Comment by ShiyoKozuki** [comment]
How is using openers 200 IQ? That's standard rogue and feral druid gameplay. A rogue not using openers is essentially a useless dead weight character in any form of PvP.

**Comment by ratkosrb** [comment]
They use an opener - auto attack!

**Comment by ShiyoKozuki** [comment]
Please show me where it would need to be checked in the code to not auto-attack from stealth

**Comment by ratkosrb** [comment]
Multiple places in BattleBotAI.cpp, and I think acquiring enemy targets is pretty much tied to enabling auto attack.

**Comment by Wall-core** [comment]
@ShiyoKozuki just add a function that checks on acquired target if the rogue/druid bot is in stealth, if so have it cast cheap shot or whatever at increased distance of 7 yards. Also I'm fairly certain this is related to that leeway issue where auto attacks and abilities use different leeway calculations, with autos calculated at marginally larger ranges which would cause bots that have no frame-delay to auto instead of using abilities. See: 
![image](https://github.com/vmangos/core/assets/90075138/982d18f4-8f3d-4d29-ab57-0bf5715fb326)

**Comment by ShiyoKozuki** [comment]
> @ShiyoKozuki just add a function that checks on acquired target if the rogue/druid bot is in stealth, if so have it cast cheap shot or whatever at increased distance of 7 yards. Also I'm fairly certain this is related to that leeway issue where auto attacks and abilities use different leeway calculations, with autos calculated at marginally larger ranges which would cause bots that have no frame-delay to auto instead of using abilities. See: ![image](https://private-user-images.githubusercontent.com/90075138/301973251-982d18f4-8f3d-4d29-ab57-0bf5715fb326.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MDkyMzIsIm5iZiI6MTcwNjkwODkzMiwicGF0aCI6Ii85MDA3NTEzOC8zMDE5NzMyNTEtOTgyZDE4ZjQtOGYzZC00ZDI5LWFiNTctMGJmNTcxNWZiMzI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDIxMjIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MGVkY2E5ODI5YTdiZTMxZTAzN2M1YTdmNzMwOWUyMWI5ZWNjZWM2ZjRjOTJhMDE1NmQxZWFiNzg0M2I1ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wWVXgvNlqkRyCQx9hZaDJuVOBKDo1FYEHhfxouaL8q0)

Taurens auto me from out of CoC range on mage, it's kinda hilarious
