### ISSUE TITLE
🐛 [Bug]SpellCaster::IsNonMeleeSpellCasted function does not ignore physical ranged spells (shoot crossbow etc)

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2481]
## 🐛 Bug report
As the title says, SpellCaster::IsNonMeleeSpellCasted function does not ignore physical ranged spells (shoot crossbow etc)
![PGWqgRi](https://github.com/vmangos/core/assets/58101246/76484298-4b94-4a68-b6b1-a0586c72920d)

### Expected behavior
Should probably ignore physical ranged spells because physical ranged spells can't be interrupted and it's used for that in the code in a lot of places.

### Steps to reproduce

1. be a class with a ranged wep
2. fight a mage bot
3. shoot them
4. ...
5. Profit

### Version & Environment

Client Version:  1.12.1

Commit Hash:  newest

OS Client:  win10
OS Server:  win10

### Crashlog

- None

**Comment by ratkosrb** [comment]
This is not a bug, the function name is very clear... It does not say IsNonMeleeNonRangedAutoRepeatSpellCasted, it says IsNoneMeleeSpellCasted, and that's what it returns.

**Comment by ShiyoKozuki** [comment]
So shouldn't there be one to ignore ranged spells too, then?
Doesn't seem very completed.

**Comment by ratkosrb** [comment]
```
 bool IsNonMeleeSpellCasted(bool withDelayed = false, bool skipChanneled = false, bool skipAutorepeat = false)
 ```
 maybe read the parameters

**Comment by ShiyoKozuki** [comment]
What parameter says "Don't skip ranged attacks"?
Shoot crossbow isn't auto-shoot, and isn't auto-repeat.

**Comment by ratkosrb** [comment]
The non auto shot version of shoot is a normal spell cast, its not of a different type. It should not be handled any differently.

**Comment by ratkosrb** [comment]
If you are trying to argue that Shoot Crossbow should be prevented by Silence, that's not true. What spells are silencable is controlled by the prevention type column.

**Comment by ShiyoKozuki** [comment]
> If you are trying to argue that Shoot Crossbow should be prevented by Silence, that's not true. What spells are silencable is controlled by the prevention type column.

I didn't say this, that's why this bug report was opened. You can't interrupt ranged physical spells.
The function is used in numerous spots of the projects code assuming that it's only interrupting spells that can be interrupted, which ranged physical spells are not.

**Comment by ShiyoKozuki** [comment]
So is it also intended that capping nodes in AB also triggers IsNonMeleeSpellCasted ?
Because it does, since the channel is considered a "spell".

**Comment by Wall-core** [comment]
Yes, actions such as opening a chest or capturing a flag use a spell that your character learns on creation (Open Chest). This is correct behavior. What is the issue here?
