### ISSUE TITLE
🐛 [Bug] Incorrect house_id in auction table crashes the application at start

### ISSUE THREAD

**Issue by kjarex** [vmangos/core#2482]
## 🐛 Bug report
If the `auction` table contains records with invalid `house_id`s the application crashes 

```
Loading Auctions...

>> Loaded 50 auction items
zsh: segmentation fault  ./mangosd
```

### Expected behavior
The application should handle such situations (by ignoring or maybe deleting those records - ideally with some output, notifying about the issue). It could also stop if it thinks it's necessary, but should then do so gracefully and not by segfault

### Steps to reproduce
1. create a record with an invalid house_id in your auction table
2. start mangosd
3. watch it segfaulting
4. cry

### Version & Environment

Client Version: no client needed/ involved

Commit Hash:  🤔

OS Client: Palm Vx
OS Server: Debian Buster

### Crashlog

- None

**Comment by Wall-core** [comment]
Why are you adding non-existent auction house IDs? This is a problem you created, not an issue with the emulator. It should never parse an illegitimate ID.

**Comment by kjarex** [comment]
I fully agree that the trigger is user created, but I disagree that this is not an issue of the emulator. Error handling of invalid input is a matter of any software (and vmangos does it in several other cases).

>  It should never parse an illegitimate ID.

I don't even necessarily want it to parse it - it would be enough if at least:

>  stop if it thinks it's necessary, but should then do so gracefully and not by segfault

and ideally it would do so by also mentioning the reason (like "invalid house_id in record x in auction table") in the output and log.

**Comment by Wall-core** [comment]
If an error can happen in the normal handling of a function or call, then we aim to catch. But this is not the case here; a user would have to purposefully modify something that they shouldn't be changing. We couldn't possibly have catches for everything that is caused by someone breaking their own database or core; modifying it falls under the users responsibility, not ours.

**Comment by kjarex** [comment]
Then we just agree to disagree, as in my opinion the user should **never** be able to cause a segfault, no matter how bad or wrong their input is (not saying the application always has to run - just never ever segfaulting).
