### ISSUE TITLE
🔧 [Support]quest Saving Sharpbeak Unable to complete

### ISSUE THREAD

**Issue by zw-su** [vmangos/core#2485]
### Version & Environment

Client Version: 1.12.1

Commit Hash:  

OS Client: 
OS Server: 

### Steps to reproduce
1. When I opened the cage using Hexx's Key, it prompted an invalid target
2.  I followed the modifications to #269,But it didn't work
3.
4. ...
5. Profit

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/assets/35845488/583d808f-329b-4114-9106-3b641c89fe2e

I cannot reproduce the issue. Your server must be outdated.
