### ISSUE TITLE
🐛 [Bug]Battlebots now randomize gear sets far below their level

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2490]
## 🐛 Bug report
Battlebots now randomize gear far below their level if not level 60.

### Expected behavior
Prob related to this:
https://github.com/vmangos/core/commit/c499539e091cd4a2244c855319c29ae8c77db5e6

**Comment by ratkosrb** [comment]
Would you like the old behavior restored?

**Comment by ShiyoKozuki** [comment]
> Would you like the old behavior restored?

No, the old is much worse for level 60.
It could be clamped to not equip gear too far below your level like how there's a config setting for partybots gear randomizing level.
