### ISSUE TITLE
🐛 [Bug]Saving Char premade spec

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2491]
## 🐛 Bug report
![image](https://github.com/vmangos/core/assets/58101246/f31d4b20-4520-4fad-963a-5f30d69f7f86)
![image](https://github.com/vmangos/core/assets/58101246/72fabb83-1984-4aed-95bc-536376dafbe5)

I saved all of these the exact same way, with spells learned, with full talents.

EDIT: Found out how to reproduce
If it is a brand new character that has not used .save or been online for 15 minutes, it does not properly save spells

### Expected behavior
Currently, this command is unintuitive to the common user.
It should work even if the character is brand new thus it should force a character save before running the command itself.

### Steps to reproduce

1. create a new character, learn spells, learn talents
2. before 15 mintues have passesd, type .char premade savespec <name here>
3. look at player_premade_spell for your new template, no entries will exist
4. ...
5. Profit

### Version & Environment

Client Version:  1.12.1

Commit Hash:  newest

OS Client:  win10
OS Server:  win10

### Crashlog

- None

**Comment by ratkosrb** [comment]
```
EDIT: Found out how to reproduce
If it is a brand new character that has not used .save or been online for 15 minutes, it does not properly save spells
```

I TOLD YOU THAT YOU HAVE TO RELOG AFTER PUTING TALENTS AND LEARNING SPELLS BEFORE USING SAVESPEC COMMAND

Do not open a third issue about this. You will be blocked from the organization if you do.
