### ISSUE TITLE
🐛 [Bug] Error in the ID of High Priest Thekal

### ISSUE THREAD

**Issue by gajet5** [vmangos/core#2496]
## 🐛 Bug report
npc info
![image](https://github.com/vmangos/core/assets/3825412/58e9020a-2265-4c32-9408-57233d5385cc)

in db
![image](https://github.com/vmangos/core/assets/3825412/28cae56e-e219-40a4-b643-06ad6353055b)

in locales and wowhead
![image](https://github.com/vmangos/core/assets/3825412/40547b1c-45dd-4a38-a730-f7b74041a6c7)

### Expected behavior
the ID is correct

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  No

OS Client: Win
OS Server: Ubuntu

### Crashlog

- None

**Comment by mserajnik** [comment]
Fixed via https://github.com/vmangos/core/commit/d76a21b150686311acffde658b7230d16f33b0a1, no?

https://github.com/vmangos/core/blob/d76a21b150686311acffde658b7230d16f33b0a1/sql/migrations/20240408140703_world.sql#L17-L19
