### ISSUE TITLE
Graveyards near starting areas

### ISSUE THREAD

**Issue by Bzmode** [vmangos/core#250]
**Current behavior**:  When you die outside a starting area you are sometimes ported to a starting area gy.

**Expected behavior**: No matter how far you are if you die outside the starting area you shouldn't be put in the starting area gy.

**Steps to reproduce**:

1. Die outside any of the starting areas
2. https://www.twitch.tv/videos/443961960?t=23m58s

**Comment by ratkosrb** [comment]
Related cmangos issue https://github.com/cmangos/mangos-classic/pull/369

**Comment by Jinnai** [comment]
Related to this I have noticed that dying in Dun Morogh at the South Gate tunnel to Loch Modan just before the zone changes to Loch Modan (so still in Dun Morogh) you get ported to Ironforge GY. In the Classic Stress Test this ports you to Kharanos.
