### ISSUE TITLE
🐞 [Bug] after commit,Partial spell release invalid

### ISSUE THREAD

**Issue by zw-su** [vmangos/core#2500]
### Steps to reproduce

1. I manually updated the local code from commit d076cd4
2.  #2282 were no issues with the test and it has been fixed
3.   but mage‘s Ice Barrier and Ice Block，shaman‘s  Lightning Shield，hunter‘s Aspect of the Cheetah are all release failures
4.  I don't know if it's because I haven't made any changes to it
5. ...
6. Profit

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  dcf59b62670b1e1d892fc2ceefa85b05a69a099f

OS Client: window 11
OS Server: ubuntu 22.04

### Crashlog

- None

**Comment by ratkosrb** [comment]
What are you reporting? I do not understand, what doesn't work?

**Comment by zw-su** [comment]
mage‘s Ice Barrier and Ice Block，Can be released, but it won't take effect

**Comment by zw-su** [comment]
Uploading 4c295e6e9472ed5241410f72591a39ef.mp4…

**Comment by zw-su** [comment]
![20240209142904](https://github.com/vmangos/core/assets/42259621/bbfff946-5376-48c0-8cf3-c5682c666b82)

**Comment by zw-su** [comment]
After releasing the spell, there are actions but no effects

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/assets/35845488/d24a554d-f4f5-44d2-ac72-ebd416a177f8

Cannot reproduce the issue, Ice Barrier works fine.

**Comment by zw-su** [comment]
I resolved this issue based on other commit
