### ISSUE TITLE
💬 [Discussion]Modifying experience obtained by one person

### ISSUE THREAD

**Issue by zw-su** [vmangos/core#2502]
## 💬 Discussion

1. A low-level character and other full level characters enter the dungeon

2. One of the fully rated characters, attract monsters to come over (hunter), then feign death and exit the dungeon

3. Other fully rated characters exit the team and kill the monster

4. At this point, low-level characters will gain all experience

5. I hope this low-level character only gains a small amount or no experience, what should I do?

**Comment by ratkosrb** [comment]
This is not a bug. This is exactly what Athene did in 2008 to try and get world first level 80 when WotLK was released, before he got banned. Mob tagging for power leveling was not prevented until MoP came out.

**Comment by zw-su** [comment]
Thanks for your answer. I will close this question for now
