### ISSUE TITLE
🐝 [Bug]Rogue level 10 quests

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2508]
## 🐝 Bug report - Quest
![image](https://github.com/vmangos/core/assets/58101246/7edc72e1-6ff8-41fc-a857-a9b18253a639)

Can pick up all the level 10 quests on rogue even if you completed one of them

### Expected behavior
Shouldn't be able to pick up and do every level 10 rogue quest if you completed one - they're a shared thing.
![image](https://github.com/vmangos/core/assets/58101246/cbfacd1a-cc27-4298-80b1-bb64f344def7)

https://www.wowhead.com/classic/quest=2218/road-to-salvation

### Version & Environment

Client Version:  1.12.1

**Comment by NickTyrer** [comment]
This is the correct behaviour for these quest chains (tested on classic).
