### ISSUE TITLE
Lack of Negative Range

### ISSUE THREAD

**Issue by Klimpb** [vmangos/core#251]
**Current behavior**: There currently is no negative range for melee and ranged spells/abilities

**Expected behavior**: 
There should be roughly 2 yards of negative range for all ranged and melee abilities/spells

I'll let clips from classic beta do the talking as its easier than explaining: 
https://clips.twitch.tv/BlushingAbnegateMetalANELE before he turned around, he was able to gouge in that position. After he turned around, he's able to backstab. In addition to this, you're also able to cast spells behind the target 
https://clips.twitch.tv/AnimatedLachrymoseMangoPipeHype

**Comment by Klimpb** [comment]
Basically, if you're within 2(could be 1.5) yards of an enemy, there should be no "orientation checks" for your spells and auto-attacks.

EDIT: the range is most likely the same value as player's(source) CombatReach.

**Comment by SuddenDeath** [comment]
Could be 1.5 yards, hard to determine.
