### ISSUE TITLE
🐞 [Bug]Instant Poison procs off Sap casts

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2514]
## 🐞 Bug report - Spell
https://github.com/vmangos/core/assets/58101246/be3b8ab7-b8e0-4ab7-87a4-6b90968dd0bf

Instant Poison(and maybe all poisons? Unsure) procs off Sap casts.
### Expected behavior
Should not proc off sap casts - it defeats the purpose of sap and instantly breaks it.

### Version & Environment

Client Version:  1.12.1

**Comment by ratkosrb** [comment]
You are wrong. It is blizzlike for Sap or any other ability that requires a melee weapon to apply poisons.

Here is proof from original vanilla.
https://www.youtube.com/watch?v=klMsyF_Kz5o

Here is post from Blizzard's forums of players complaining about the same thing.
https://us.forums.blizzard.com/en/wow/t/sap-applies-poisons/309762
