### ISSUE TITLE
🐛 [Bug] “Love is in the Air“ Task Error

### ISSUE THREAD

**Issue by yjfyy** [vmangos/core#2515]
Orgrimmar Undercity  Stormwind  Ironforge is normal
![1](https://github.com/vmangos/core/assets/3762051/44adc114-80b5-4f35-9604-4a5fe8c428c5)
 
Thunder Bluff  Darnassus No menu
![2](https://github.com/vmangos/core/assets/3762051/d5e2c1a3-4167-442d-8862-73287bfe4021)

Client Version: 1.12.1.5875

Commit Hash: https://github.com/vmangos/core/tree/abf0be6fd32dfa141e4d78199cf182db00e9ed5e

OS Client: Win
OS Server: Win

**Comment by ratkosrb** [comment]
It tells you to apply Cologne.

**Comment by yjfyy** [comment]
Neither does cologne

**Comment by yjfyy** [comment]
> It tells you to apply Cologne.

Neither does cologne

**Comment by ratkosrb** [comment]
![WoWScrnShot_021724_050619](https://github.com/vmangos/core/assets/35845488/88baed68-a7a3-40ba-a6c8-2b46a1be5dc7)

I can't reproduce the issue.

**Comment by yjfyy** [comment]
Sorry, my mistake

**Comment by yjfyy** [comment]
There is still a problem.In Thunder Bluff start event, Logout,**_Wait a few minutes_**, Login again, The guards have no love icons

https://github.com/vmangos/core/assets/3762051/d803af0a-1bdd-48b0-b6dd-678914f9d605

**Comment by ratkosrb** [comment]
Are you sure the event wasn't turned off because the time for it has expired?

**Comment by yjfyy** [comment]
I have manually enabled it,And Orgrimmar is normal

https://github.com/vmangos/core/assets/3762051/733b6f7f-5f23-48c6-bcd6-b19604984275

**Comment by yjfyy** [comment]
> Are you sure the event wasn't turned off because the time for it has expired?

must log out and wait for a few minutes

**Comment by ratkosrb** [comment]
Is GridUnload enabled in config?

**Comment by yjfyy** [comment]
> Is GridUnload enabled in config?

It's not this issue, I will conduct a detailed inspection and provide feedback later
