### ISSUE TITLE
🐛 [Bug] crash in         RemoveAurasWithInterruptFlags(AURA_INTERRUPT_LEAVE_WORLD_CANCELS | AURA_INTERRUPT_MOVING_CANCELS | AURA_INTERRUPT_TURNING_CANCELS);

### ISSUE THREAD

**Issue by william19831103** [vmangos/core#2517]
### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None
![remove aura 20240218195632](https://github.com/vmangos/core/assets/15699126/e984a684-0242-4937-8556-2e45f932c77e)
![crash aura20240218200022](https://github.com/vmangos/core/assets/15699126/c8b66d2a-ff0c-42ca-a241-e95f8773090c)

**Comment by william19831103** [comment]
![Uploading crash aura 120240218195821.jpg…]()

**Comment by Gamemechanicwow** [comment]
I guess you are using vmangos-eluna?
