### ISSUE TITLE
The continuous spell is attacked and the reading action disappears!

### ISSUE THREAD

**Issue by xiejin101** [vmangos/core#2518]
The continuous spell is attacked and the reading action disappears!
Like a blizzard sucking souls!

**Comment by Wall-core** [comment]
Need more info

需要更多信息

**Comment by xiejin101** [comment]
Blizzard is continuously attacked by creatures, and the spell casting bar ends immediately and the action also ends, but the spell effect is still ongoing

**Comment by xiejin101** [comment]
Normally, during a continuous blizzard, being attacked by a creature should reduce the duration of casting spells instead of immediately disappearing them

**Comment by xiejin101** [comment]
Normally, during a continuous blizzard, being attacked by a creature should reduce the duration of casting spells instead of immediately disappearing them

**Comment by cpevors** [comment]
Is this open or closed at this point? Worth investigating?

**Comment by rogical** [comment]
encounter same issue, a lot players reported

**Comment by oowow-core** [comment]
already fixed by brotalnia

**Comment by SandWind** [comment]
> already fixed by brotalnia

where is this fix commit?
