### ISSUE TITLE
🐛 [Bug]When mangosd.exe reads the group and group_member tables, it crashes and must be cleared before it can start

### ISSUE THREAD

**Issue by leechunlung** [vmangos/core#2529]
### Steps to reproduce

1.When mangosd.exe reads the group and group_member tables, it crashes and must be cleared before it can start
2.mangosd.conf  set "AllowTwoSide.Interaction.Group = 1" 
3. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by ratkosrb** [comment]
I can't reproduce the issue.
