### ISSUE TITLE
🐝 [Bug]Egg Collection Unable to complete

### ISSUE THREAD

**Issue by zw-su** [vmangos/core#2530]
### Steps to reproduce

1.  Eggscilloscope Can freeze Rookery Egg
2.  Collectronic Module Unable to collect Rookery Egg，Prompt that you have no target
3.  update spell_script_target set conditionid=0 where entry=15958; After modification, it still doesn't work
4. ...
5. Profit

### Version & Environment

Client Version: 1.12.1

Commit Hash:  

OS Client: win 10
OS Server: linux

### Crashlog

- None

**Comment by zw-su** [comment]
Is this question too simple for me to ask？

**Comment by zw-su** [comment]
I found the answer in a commit

**Comment by ratkosrb** [comment]
Why aren't you using the latest core and db? :(
