### ISSUE TITLE
🐛 [Bug]Wrong low-level character acquisition experience method

### ISSUE THREAD

**Issue by leechunlung** [vmangos/core#2531]
### Steps to reproduce

1.If you have a level 60 character and a level 1 character
2.two char in a group
3.Use level 1 characters to deal at least a little damage to creature
4. Level 60 character leave the group,and then kill the creature
5.Level 1 characters can receive full exp
6.This is unreasonable. In the official game, it is necessary to deal 40% or 50% damage in order to gain experience, otherwise it is very easy to level up with low-level characters.

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by Gamemechanicwow** [comment]
> 6.This is unreasonable. In the official game, it is necessary to deal 40% or 50% damage in order to gain experience, otherwise it is very easy to level up with low-level characters.

Mob tagging was a thing in vanilla - and classic for that matter.
Since you mention the players being in a group. I am guessing you are referring to mobtagging in dungeons. This was also a thing in vanilla and classic - but eventually nerfed in wotlk classic.

**Comment by GoonBoiBarry** [comment]
He's not claiming mob tagging shouldn't exist, he's saying the conditions surrounding it are different in classic when using the method he describes. The group aspect he's describing is just a step in the method to produce what he believes to be an inconsistency between classic and vmangos.

I'm not saying he's right, he didn't provide any evidence at all, but you misunderstood what he was saying.

**Comment by ratkosrb** [comment]
We are aware its different in classic, vmangos is accurate to vanilla. This was only changed in mists of pandaria and blizzard kept the new behavior for classic cause they didn't like mob tagging. Do not make issues to adopt non vanilla behavior.
