### ISSUE TITLE
NAT - Port forwarding - Share your server over the internet🔧 [Support]

### ISSUE THREAD

**Issue by noire-x** [vmangos/core#2537]
Hi there peeps,
and thanks for the project!
I would like to host a server on debian 12 for my guild so to get some practices going on. 
Which ports need to be forwarded to the server? Do you have a wiki about getting started about this? Also about configuring the clients to reach my server from the internet?
Many thanks!

**Comment by GrenderG** [comment]
https://github.com/vmangos/wiki/wiki/Compiling-on-Linux
https://github.com/vmangos/wiki/wiki/Getting-it-working

Bonus video: https://www.youtube.com/watch?v=ymtjkglLYk0

**Comment by noire-x** [comment]
Hi thanks for your reply.
I have found it out also surfing on some of your forums so just posting my quick "solution" here

NAT/Forward Ports in your modem/router to the internal IP address of your server (in this case 192.168.1.33):
- TCP 3724
- TCP 8085

If you then have issues with Realm selection/loop make sure you have edited the IP address with your Public IP address which is the one your ISP assigns you to navigate in internet/outside your internal network. You can get your Public IP googling "myip". 
Then edit your DB using for instance phpmyadmin and add your public IP into the "address" column (in this case the Public IP address added is 170.21.133.118)

![image](https://github.com/vmangos/core/assets/112881201/74e98aba-d569-45e5-9760-eff59cd78f1c)

Then edit your file realmlist.wtf, delete anything in there and just add this row:

set realmlist 170.21.133.118
(You must change the Public IP above with your own)

Hope it will help!

**Comment by mserajnik** [comment]
@noire-x FYI, the `realmlist.address` column can also contain a domain instead of an IP (which might be useful when the server is run on a machine that has a dynamic WAN IP and uses DDNS).
