### ISSUE TITLE
🐛 [Bug] Server auto shut down 15mins

### ISSUE THREAD

**Issue by rockydonet** [vmangos/core#2547]
![2024-03-11 001425](https://github.com/vmangos/core/assets/67671559/dc897179-6fcc-4497-ba61-4bbce50467ce)

Hello guys,

I just updated to lastest Vmangos Core and load latest sql updates.  But I notice that the server will auto shut down every 15mins, which is very annoying.

In console I can see below message:
"HonorMaintenancer: Server needs to be restarted to perform honor rank calculations."

I figure out by typying below command to cancel restart:
server idlerestart cancel

But can I permanently fix this? Thanks

**Comment by mserajnik** [comment]
You should be able to disable the automatic restart by setting [`AutoHonorRestart`](https://github.com/vmangos/core/blob/f3ad95970a79a2be2cac7daa54d3779fb83e138a/src/mangosd/mangosd.conf.dist.in#L1094) to `0`.

However, it should not attempt to restart every 15 minutes, the restart should only happen once a week (on Wednesday by default, configurable via [`MaintenanceDay`](https://github.com/vmangos/core/blob/f3ad95970a79a2be2cac7daa54d3779fb83e138a/src/mangosd/mangosd.conf.dist.in#L1091)). If you let the restart happen does it immediately schedule a restart again?

**Comment by ratkosrb** [comment]
It restarts multiple times because you have missed multiple weeks of honor calculations.
