### ISSUE TITLE
Risen Aberration(ID:10485) in Scholomance supposed to despawn when Rattlegore dies.

### ISSUE THREAD

**Issue by Bzmode** [vmangos/core#255]
**Current behavior**: Doesn't despawn

**Expected behavior**: Risen Aberrations(ID:10485) in Scholomance supposed to despawn when Rattlegore dies.

**Steps to reproduce**:

1. Kill Rattlegore
2. go look at the room filled with Risen Aberrations

**Comment by GrenderG** [comment]
Proof?

**Comment by Daribon** [comment]
Not true, tested on classic.
They never despawn unless killed.
