### ISSUE TITLE
[Angry Programmer Tweedle Dee] NPC (entry 128) is missing

### ISSUE THREAD

**Issue by GrenderG** [vmangos/core#256]
https://classic.wowhead.com/npc=128/angry-programmer-tweedle-dee
https://www.youtube.com/watch?v=cNlUAoEygwk (Minute 21:30)

Display id: 1415

EDIT: Also, the spell to summon him https://classic.wowhead.com/spell=897/ is being wrongly used to summon King Gordok.

**Comment by Kittnz** [comment]
Added in patch 1.13.2.30406, i don't know where this should be spawned

**Comment by GrenderG** [comment]
> Added in patch 1.13.2.30406, i don't know where this should be spawned

According to Wowhead it was added in patch `1.12.1.13164`, but it might have been added even earlier, since it uses a low Entry (128). No need to spawn the NPC either, it's just to make the database as complete as possible. :P

**Comment by Gamemechanicwow** [comment]
Try browsing a few more testing npcs and consider if blizzard have started to use previously unused id’s for testing purposes.

**Comment by GrenderG** [comment]
> Try browsing a few more testing npcs and consider if blizzard have started to use previously unused id’s for testing purposes.

I can find people talking about this NPC in WoTLK times, so it's not a new addition for Classic. Also, the spell to summon it is in game files since Vanilla: https://classic.wowhead.com/spell=897/ and it's being wrongly used at this moment to summon King Gordok.

**Comment by Daribon** [comment]
It shouldn't be spawned anywhere, but it is a NPC that existed in vanilla. It's just one of those blizzard development NPCs.
