### ISSUE TITLE
🚀 [Feature]How to modify the maximum number of people entering the Molten core dungeon

### ISSUE THREAD

**Issue by zw-su** [vmangos/core#2562]
## 🚀 Feature

1. I couldn't find where to modify this maximum number of people
2. If it's convenient to answer, thank you very much

**Comment by ratkosrb** [comment]
The `map_template` table.

**Comment by mserajnik** [comment]
```sql
SET @PLAYER_LIMIT = 40;
UPDATE `map_template` SET `player_limit` = @PLAYER_LIMIT WHERE `entry` = 409; -- Molten Core
```

Set `@PLAYER_LIMIT` to your desired maximum number of players.

**Comment by zw-su** [comment]
Thanks!
