### ISSUE TITLE
🔧 [Support] May I ask how to set up a SOAP authentication account and password

### ISSUE THREAD

**Issue by Shirley-Jones** [vmangos/core#2568]
## 🔧 Support Request
May I ask how to set up a SOAP authentication account and password!

### Version & Environment
  Client Version:
  - 1.12.1.5875
  
  Operating System:
OS Client: windows 10
OS Server: ubuntu 22.04

**Comment by mserajnik** [comment]
From what I can see, SOAP just uses regular user accounts for authentication:
https://github.com/vmangos/core/blob/f53de3d5b43d1654f02e7ee2c8e3f6b5e1f5c907/src/mangosd/MaNGOSsoap.cpp#L103-L120

To use SOAP, it has to be enabled in the config:
https://github.com/vmangos/core/blob/f53de3d5b43d1654f02e7ee2c8e3f6b5e1f5c907/src/mangosd/mangosd.conf.dist.in#L2805-L2807

And there's a small example SOAP client PHP script [here](https://github.com/vmangos/core/blob/f53de3d5b43d1654f02e7ee2c8e3f6b5e1f5c907/contrib/soap/example.php).

**Comment by Shirley-Jones** [comment]
What I want to know is how to set login and password. The username and password in the example file are: administrator. Thank you.
![2](https://github.com/vmangos/core/assets/53739479/0a2103ac-1a70-43db-a009-680e5b378010)


Connection soap error
![1](https://github.com/vmangos/core/assets/53739479/46f0fcd4-ab5a-40da-a55c-cdb6d00e0fa9)

Command failed! Reason:
HTTP Error: 401 Unauthorized

**Comment by mserajnik** [comment]
As I wrote before:

> From what I can see, SOAP just uses regular user accounts for authentication

So you have to create a regular user account, e.g.:

```sh
account create <account name> <account password>
account set gmlevel <account name> 6 # SEC_ADMINISTRATOR, see https://github.com/vmangos/core/blob/bd9cca7b9d16d3e88c15ed378a893faebaf353f1/src/shared/Common.h#L183-L190
```

And then authenticate using this user's credentials.

**Comment by ratkosrb** [comment]
I think you need to make the account gm level 6.

**Comment by Shirley-Jones** [comment]
Thank you everyone, the problem has been resolved.
