### ISSUE TITLE
Quest [Saving Sharpbeak] (9472) is not scripted.

### ISSUE THREAD

**Issue by GrenderG** [vmangos/core#257]
**Current behavior**: 
Sharpbeak creature is too large, so large that it gets out of the cage. Also, the quest is not scripted.

**Expected behavior**: 
Sharpbeak needs to be smaller, like a "baby" gryphon who fits inside the cage. He should get out of the cage as soon as you open it. His parents should come and they three should start flying and going away together.

Proof about how this quest should work: https://www.youtube.com/watch?v=LQCRFY3IJKY

**Comment by Kittnz** [comment]
https://www.youtube.com/watch?v=LQCRFY3IJKY

**Comment by GrenderG** [comment]
> https://www.youtube.com/watch?v=LQCRFY3IJKY

That's the exact video I posted, haha.
