### ISSUE TITLE
🐛 [Bug][Critical] Some NPCs are immortal.

### ISSUE THREAD

**Issue by gajet5** [vmangos/core#2571]
## 🐛 Bug report
After Wednesday's update, some NPCs don't die.
Their standard of living reaches 1% and nothing happens.

We saw this behavior back in scholomance, monsters that get up after being killed. As soon as they get up, they become immortal.

https://www.youtube.com/watch?v=ed0ffubCL64

Error in console: 
mob_batriderAI: Jeklik not found.

### Expected behavior
NPCs are dying.

### Steps to reproduce

1. Go to ZG
2. Go to Jeklik 
3. Try to kill (.die)
4. Profit

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  don't know

OS Client: Win
OS Server:  Ubuntu

### Crashlog

- None

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/191e3af38f053d8b69a0f2535127ce8365160b71

Report more creatures that have this problem.

**Comment by ratkosrb** [comment]
And Jeklik is not supposed to be insta killable, she must first enter Phase 2, and then she can die. So you must 2 hit her not 1 hit.

**Comment by gajet5** [comment]
> [191e3af](https://github.com/vmangos/core/commit/191e3af38f053d8b69a0f2535127ce8365160b71)
> 
> Report more creatures that have this problem.

I checked, now he's dying.


The same problem:
https://youtu.be/JZGeEE1zJCs
https://youtu.be/Dee8VZn0F-U
https://youtu.be/7Y2l3fsow5c

I noticed that the problem occurs in NPCs with the ability to resurrect.

**Comment by ratkosrb** [comment]
I have remade the Thekal script to fix him.
https://github.com/vmangos/core/commit/d76a21b150686311acffde658b7230d16f33b0a1

**Comment by gajet5** [comment]
I checked it works well. (Thekal)

**Comment by gajet5** [comment]
https://github.com/vmangos/core/commit/af3fb8803485ab1e249fb34a4588d2ad12439835

I see the fixes, I'll test them soon.

**Comment by ratkosrb** [comment]
Let me know if there are more unkillable mobs, or close the issue otherwise.

**Comment by gajet5** [comment]
> Let me know if there are more unkillable mobs, or close the issue otherwise.

https://www.youtube.com/watch?v=Dee8VZn0F-U
this one.

**Comment by ratkosrb** [comment]
But this is the same one i fixed in my commit.
https://github.com/vmangos/core/commit/f3a905e51bc31489241d46fb818b96e3a72092c5

**Comment by gajet5** [comment]
Sorry, I didn't see it.

**Comment by gajet5** [comment]
https://github.com/vmangos/core/commit/af3fb8803485ab1e249fb34a4588d2ad12439835
https://github.com/vmangos/core/commit/f3a905e51bc31489241d46fb818b96e3a72092c5
I checked, these two fixes do not fix the problem. NPC are still immortal.

**Comment by ratkosrb** [comment]
You must hit them with damage, not with .die command...

**Comment by gajet5** [comment]
I'm sorry again, I didn't take this into account in the tests.
I just double-checked, everything is working as it should.

I will close this issue as I don't have any new information yet. If it appears, we will solve it within the framework of another issue.
Thx
