### ISSUE TITLE
🐛 [Bug]After knocking The Scarab Gong,there were no war events

### ISSUE THREAD

**Issue by leechunlung** [vmangos/core#2574]
### Steps to reproduce

1.The AQ door is not open
2.There were no 10 hour AQ war events either
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by Wall-core** [comment]
It's manually controlled by game_events, check that table and use the .event commands to set them.

**Comment by leechunlung** [comment]
It seems like the AQ door can be opened directly, but how did a AQ war event occur?

**Comment by leechunlung** [comment]
> It's manually controlled by game_events, check that table and use the .event commands to set them.

After starting the event, there is no follow-up after event code 65. Each event ends quickly and the AQ door cannot be opened correctly

**Comment by ratkosrb** [comment]
The problem was that the script was looking for a Ghost Gate gameobject spawned there which doesn't exist.

Run this if you already banged the gong and it didn't work:
```
DELETE FROM `variables` WHERE `index`=30053;
```

Then in game type this:
```
.war setstage 7
```

Then when you turn in the quest at the gong it should start the next phase.
