### ISSUE TITLE
🐛 [Bug]cann't find any Un'Goro Dirt Pile and Silithyst Geyser

### ISSUE THREAD

**Issue by Soulyes** [vmangos/core#2576]
## 🐛 Bug report

Silithyst Geyser  Entry:181598
Silithyst Mound Entry:181597
Un'Goro Dirt Pile Entry:157936
The above items exist in the database gameobject, but they cannot be found and displayed in the game.

gameobject
![image](https://github.com/vmangos/core/assets/147594856/312894cd-6085-4636-acf4-1010829ba180)
![image](https://github.com/vmangos/core/assets/147594856/16e142d4-3297-4ec7-bdeb-b84ae1eb03da)
gameobject_template
![image](https://github.com/vmangos/core/assets/147594856/f4574364-8104-440b-9e9d-5ac05875a950)

Client Version: 
 1.14 ,1.12

**Comment by mserajnik** [comment]
[Un'Goro Dirt Pile (`157936`)](https://www.wowhead.com/classic/object=157936/ungoro-dirt-pile) does spawn, here are some examples:

GUID `17968`:
<img width="1470" alt="gobject_17968" src="https://github.com/vmangos/core/assets/80664890/f8bac4d2-81f7-414f-a691-6b3502ac9cb3">

GUID `17967`:
<img width="1470" alt="gobject_17967" src="https://github.com/vmangos/core/assets/80664890/90fcaede-5404-4e13-a127-9b8b71e9a37c">

GUID `17964`:
<img width="1470" alt="gobject_17964" src="https://github.com/vmangos/core/assets/80664890/76ad6426-4386-4b3c-a94b-a1dc9ae46441">

**Comment by mserajnik** [comment]
Regarding the other two, see #2259.

**Comment by Soulyes** [comment]
successfully solve
update gameobject set id = 181597 where id  = 181598;
update gameobject set guid = guid + 4000000 where id = 181597;
update gameobject set guid = guid + 4000000 where id = 157936;

restart server
but,I don't know why?

**Comment by Soulyes** [comment]
> Regarding the other two, see #2259.

thanks
