### ISSUE TITLE
💬 [Discussion] About Scarab Lord title,does it exist in vanilla?can it be achieved here?

### ISSUE THREAD

**Issue by leechunlung** [vmangos/core#2577]
## 💬 Discussion

When the player rings the gong, or at the end of the AQ war, they dont obtain a title

**Comment by ratkosrb** [comment]
There are no titles in vanilla!!!

**Comment by ratkosrb** [comment]
![Untitled](https://github.com/vmangos/core/assets/35845488/ec8f0dde-5e05-4ac7-a7a5-35a47ce9da36)
