### ISSUE TITLE
🦂 [Bug][BWL][Razorgore] The player can click on the eggs.

### ISSUE THREAD

**Issue by gajet5** [vmangos/core#2582]
## 🦂 Bug report - Dungeon
https://youtu.be/8bylhb4qAQ0

### Expected behavior
Only the boss can crush eggs.

### Steps to reproduce
1. Go to BWL
2. Pull Razorgore and controle him.
3. Try to break the eggs with another character.
4. Profit

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  No

OS Client: Windows
OS Server: Ubuntu

### Crashlog

- None

**Comment by Daribon** [comment]
Can't reproduce it. 

Make sure you have are not in gm mode. Use .gm off

**Comment by Daribon** [comment]
The reason for the issue is because I set the faction to be 14 and flag 4. Previously it incorrectly had no faction and clicking was only prevented by using flag 4, which I removed. 

I will just set it back to use flag 4 for now.
