### ISSUE TITLE
🦂 [Bug][LBRS] After defeating the spider boss, spider's web continues to overlap the players.

### ISSUE THREAD

**Issue by gajet5** [vmangos/core#2587]
## 🦂 Bug report - Dungeon
https://youtu.be/cHNFfme4wGs

from the player
https://github.com/vmangos/core/assets/3825412/cd69ee0f-0431-43d6-86af-c0d68b5e0a16

### Expected behavior
The debuff stops overlapping after the victory.

### Steps to reproduce

1. Go to LBRS
2. Kill the spider
3. Profit

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  No

OS Client: Windows
OS Server: Ubuntu

### Crashlog

- None

**Comment by ratkosrb** [comment]
It says it in on the debuff tooltip that you have a chance to be immobilized until debuff is dispelled.

![Untitled](https://github.com/vmangos/core/assets/35845488/91346840-6c21-4a9e-b6d7-9f9afa4d2e88)

**Comment by gajet5** [comment]
That's not the problem.

![image](https://github.com/vmangos/core/assets/3825412/0cb42d86-e3eb-47cc-b810-b4236960d72b)
The problem is with the web, which overlaps over and over and over again.

**Comment by ratkosrb** [comment]
He has the debuff!!! Look the other icon next to the net, the green icon. Read what the description of the debuff is, that it causes nearby allies to be immobilized. You must cast dispel on the player with the green debuff to stop the webbing.

**Comment by gajet5** [comment]
Oh my God, I get it now.
I will take into account the fact next time that you need to deal more deeply with a problem that may not be a problem.
So there was a bug before that with the fact that it didn't work?
