### ISSUE TITLE
[IMPORTANT] DoTs keep you in combat even after Feign Death (or just combat stopped).

### ISSUE THREAD

**Issue by GrenderG** [vmangos/core#259]
**Current behavior**: 
If a creature uses a DoT on you and you use Feign Death, every time the DoT ticks it will put you in combat with the creature again.

**Expected behavior**: 
You shouldn't engage combat even if the DoT ticks again if you used Feign Death or the combat stopped for whatever reason.

Recording of the issue: https://streamable.com/4u1px

**Comment by Bzmode** [comment]
Dots also seems to be stopping mount cast.

**Comment by ratkosrb** [comment]
I cannot reproduce the issue. Once I have left combat, I do not get put back in combat when the remaining dots damage me. I am also able to use my mount while the dot is damaging me. Tried using Feign Death too.

**Comment by ratkosrb** [comment]
Oh nevermind, it does happen with the DoT in the video. Maybe it's because it also has a direct damage component.
