### ISSUE TITLE
🦂 [Bug]In the P2 C‘thun true body will inherit the health of the previous battle

### ISSUE THREAD

**Issue by leechunlung** [vmangos/core#2594]
### Steps to reproduce

1.In the P2 C‘thun true body will inherit the health of the previous battle
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by ratkosrb** [comment]
I do not understand what you are trying to say. Can you explain in more detail?

**Comment by leechunlung** [comment]
In the phase 2 of the battle with C'tun, his real body（Not his eyes ）will not reset his health

**Comment by leechunlung** [comment]
In the battle after raid failure

**Comment by leechunlung** [comment]
> I do not understand what you are trying to say. Can you explain in more detail?

When creatures are out of combat, they're supposed to reset their health, but the real body of C‘thun doesn't, this led to the use of sea of humanity tactics to defeat him
