### ISSUE TITLE
Error message: unable to save equipment. Please help me.

### ISSUE THREAD

**Issue by ss958** [vmangos/core#26]
![tim 20181006131248](https://user-images.githubusercontent.com/29692005/46567752-3274d000-c96b-11e8-98be-60b9345a297b.png)
ERROR:SQL: cannot execute 'INSERT INTO character_inventory (guid,bag,slot,item,item_template) VALUES (?, ?, ?, ?, ?)'
ERROR:SQL ERROR: When @@GLOBAL.ENFORCE_GTID_CONSISTENCY = 1, updates to non-transactional tables can only be done in either autocommitted statements or single-statement transactions, and never in the same statement as updates to transactional tables.

**Comment by ratkosrb** [comment]
What version of mysql server are you using?
When exactly does this happen, what do you do in game to trigger the error?
Was this happening before the mysql version update commit a week ago?

**Comment by ss958** [comment]
Thank you. I found a problem. It is the reason that the enforce_gtid_consistency function of MYSQL database is not closed. If you can, please find a way not to turn off this function. Because I use the cloud server, can not turn off this function!

**Comment by ratkosrb** [comment]
Have you tried making those tables InnoDB instead of MyISAM? Also you didn't answer my questions :/

**Comment by ss958** [comment]
There should always be such a problem. My conversion to InnoDB still prompts this question!

**Comment by ratkosrb** [comment]
I am closing this as you didn't provide enough information. I am guessing you were using an unsupported version of mysql with a possibly wrong configuration. The recommended version is 5.5 and I have never seen this error with it.
