### ISSUE TITLE
Many spawns should have a chance of spawning different creatures.

### ISSUE THREAD

**Issue by Bzmode** [vmangos/core#260]
**Current behavior**: Most spawns are fixed. Pooling is a band aid fix but is a very bad implementation for mass use.

**Expected behavior**: Many spawns should have a chance of spawning different creatures.

**Steps to reproduce**:

1. Watch creature spawns from the beta, especially in instances.

**Comment by Kittnz** [comment]
because on retail, they use spawn points and have entrys attached to it

**Comment by AnonXS** [comment]
could you report any significant examples so we could get a dataset on this matter?
preferably dungeon spawns as they are more important.

**Comment by ratkosrb** [comment]
The core support for this has been implemented here.
https://github.com/vmangos/core/pull/293

**Comment by NickTyrer** [comment]
Closed here #1468
