### ISSUE TITLE
🔧 [Support] DATA files

### ISSUE THREAD

**Issue by shikulja** [vmangos/core#2619]
1. vmangos uses vmaps/mmaps v6 data
when cmangos requires v8, is it possible to update data support so as not to store two sets of data. And maybe get better navigation

2. The server uses DBC files, although the Russian client works fine. But nevertheless, there are no DBCs for the Russian client (in the repack).
It may also be possible to add ruRU DBC support for the server, this will probably be useful.
The Russian client can be checked here:
https://wowruru.github.io/win_instruction.html

**Comment by ratkosrb** [comment]
The russian client is fake, its made by fans, there is no official russian client. There is no index for russian text in dbc files. They have replaced the english texts. The server thinks the russian dbcs are english dbcs, because they use the english locale index in dbcs.

**Comment by shikulja** [comment]
@ratkosrb In other localizations everything is the same. Used "string" column for names

![image](https://github.com/vmangos/core/assets/3386359/03b62f07-bbd9-4ef8-80ec-c84ff4179cd1)
![image](https://github.com/vmangos/core/assets/3386359/6d8bb927-1d87-4b7b-b3b4-6960c81b66f4)
