### ISSUE TITLE
🦂 [Bug]cann't summon Urok Doomhowl

### ISSUE THREAD

**Issue by Soulyes** [vmangos/core#2621]
cann't summon Urok Doomhowl
use item ：Omokk's Head ， 12534
notice：You have no target

![image](https://github.com/vmangos/core/assets/147594856/fe5d18d4-fbc0-45d2-967f-81455ac88274)

**Comment by GoonBoiBarry** [comment]
That's the wrong id?

**Comment by GoonBoiBarry** [comment]
Just tested and it worked fine for me using the correct items 12534 and 12533.

**Comment by Soulyes** [comment]
Has been resolved, thanks
