### ISSUE TITLE
🚀 [Feature] Add a speedhack check to the passive anti-cheat.

### ISSUE THREAD

**Issue by gajet5** [vmangos/core#2624]
## 🚀 Feature
Add a check of the last five coordinates of the player to the passive anti-cheat.
With a large change in the parameters x, y, z, output a message to the console about a possible speed hack.

### Benefits, Purpose
Checking for speedhack when anti-cheat is disabled.
This useful feature will be in demand for servers with 1.14.+ client support that cannot use anti-cheat.

**Comment by Gamemechanicwow** [comment]
You may want to take a look at movementanticheat. Because it sounds like you are requesting a feature that has been in the core for almost 5 years.

**Comment by gajet5** [comment]
This is really very similar to what you want to see on the server. I need to check it out.

**Comment by Wall-core** [comment]
The MovementAnticheat system described above does need some expanding, namely it should be incorporated into the fall damage check system. Currently, fall damage is calculated based on flags which can be modified by the client, leading to the infamous "Instant death short fall" bug. These checks should be incorporated into the fall damage system as a means of checking the veracity of the current data, and if there is a discrepancy it should handle it based on server-exclusive data used by MovementAnticheat

**Comment by gajet5** [comment]
> The MovementAnticheat system described above does need some expanding, namely it should be incorporated into the fall damage check system. Currently, fall damage is calculated based on flags which can be modified by the client, leading to the infamous "Instant death short fall" bug. These checks should be incorporated into the fall damage system as a means of checking the veracity of the current data, and if there is a discrepancy it should handle it based on server-exclusive data used by MovementAnticheat

It sounds like a bug description, maybe you create a new one?
