### ISSUE TITLE
🔧 [Support] When fighting Jin'do the Hexxer, the partybot's hover over the pool and do nothing.

### ISSUE THREAD

**Issue by gajet5** [vmangos/core#2626]
## 🔧 Support Request
Hi, I noticed the strange behavior of partybot in the battle with Jin'do the Hexxer. When he uses the banishment skill, the bot moves to the area above the pool and freezes.

What do you think is the reason for this?

I tried to program the behavior at the point, but the bot ignores the instructions and continues to hang over the pool.
```c++
// go to leader after tp
if (me->GetDistance2dToCenter(-11582, -1251) < 30)
{        
    me->GetMotionMaster()->MoveChase(GetPartyLeader());
    return;
}
```

Video: https://youtu.be/mt8dBeIH1m4

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  No

OS Client: Windows
OS Server: Ubuntu

### Steps to reproduce
1. Start the boss fight.

**Comment by Wall-core** [comment]
It's because they're teleported and are basically rooted while under the effects of AI, and can't move/fall while floating.
add a check for player->IsBot() in the jindo script and if true, set the teleport Z level to ground Z level.

**Comment by gajet5** [comment]
Thanks for the advice. Indeed, the problem is the eternal fall of the bot. I rewrote the behavior, it got better :).
