### ISSUE TITLE
🐛 [Bug] The quest to open the upper level of Blackrock Tower and Urok cannot be completed.

### ISSUE THREAD

**Issue by yybss** [vmangos/core#2634]
1.The Emberstrife mission cannot be completed during the dragon control phase, prompting an invalid target
2.Using Ormoc's head in the Urok tribute pile prompts an invalid target

**Comment by ratkosrb** [comment]
Is your core up to date? Can you tell me the revision?

**Comment by yybss** [comment]
https://github.com/bing2008/VMangos-eluna
I used this link, but I see that the codes related to the skills required for these two tasks are the same.

**Comment by yybss** [comment]
The client version is 1.12.1

**Comment by yybss** [comment]
I'm really sorry, I was wrong. I retested the latest core and found it to be normal! It’s that core that lacks npcAI

**Comment by ratkosrb** [comment]
Please do not report anything related to vmangos-eluna, this is completely unsupported, it is not made by us. The user @bing2008 should be responsible for solving your problem because he made it.
