### ISSUE TITLE
🐞 [Bug] Slam does not make the casting animation in certain races

### ISSUE THREAD

**Issue by Arroyopy** [vmangos/core#2636]
### Expected behavior

Slam does not make the casting animation in certain races:
Night Elf
Gnome
Undead
Tauren
Troll

### Steps to reproduce

1. .learn all_my
2. get rage
3. /cast slam

### Version & Environment

Client Version: 
  - 1.12.1.5875

Commit Hash:  b54215a4983a4058f3864312c6520dfbb766928e

https://github.com/vmangos/core/assets/35780566/17e74729-df07-40e9-b800-e7470a76e9a8

OS Client: Windwos 11
OS Server: Ubuntu 22.04.4 LTS (GNU/Linux 6.5.0-1023-oracle aarch64)

### Crashlog

- None

**Comment by GoonBoiBarry** [comment]
I'm pretty sure most of them don't have ability casting animations if you check in wowhead's dressing room.

You can see here an undead casting slam with no ability casting animation.
https://www.youtube.com/watch?v=Ibh4SO5W4OU

**Comment by ratkosrb** [comment]
Do you have proof from original vanilla there was a casting animation?

**Comment by Arroyopy** [comment]
i dont have proof from vanilla.
