### ISSUE TITLE
🦂 [Bug] Warchief Rend Blackhand can be summoned endlessly.

### ISSUE THREAD

**Issue by rogical** [vmangos/core#2638]
## 🦂 Bug report - Dungeon

Blackrock Spire

Warchief Rend Blackhand can be summoned endlessly.

https://www.youtube.com/watch?v=fUaS_bFuGbY

### Steps to reproduce

1. hit Gyth, untile Warchief Rend Blackhand show
2. kill Warchief Rend Blackhand
3. let Gyth return, then hit again, then Rend  will show again

### Version & Environment

Client Version: 1.12

Commit Hash:  

OS Client: 
OS Server: Ubuntu

### Crashlog

- None

**Comment by ratkosrb** [comment]
I think you linked the wrong video.

**Comment by shudza** [comment]
you could do this on classic servers, so this could actually be blizzlike 😅 https://youtu.be/SWyTBscXytA

**Comment by ratkosrb** [comment]
Seems like it's not a bug.

**Comment by rogical** [comment]
updated video https://www.youtube.com/watch?v=fUaS_bFuGbY

somehow attached wrong url
