### ISSUE TITLE
🔧 [Support]About Ddos or CC network attacks

### ISSUE THREAD

**Issue by Soulyes** [vmangos/core#2641]
![3d50f6f87bc0cd056bdbbd1ac14160c](https://github.com/vmangos/core/assets/147594856/8ae6fdd3-2bd5-4e92-9a54-1956442070b9)

Is it possible to increase the functionality of blocking the packets sent by the receiving IP

**Comment by gajet5** [comment]
if your server os is nix, use fail2ban.

**Comment by Soulyes** [comment]
mangosSocketlmpl.h Write part of the code, you can automatically block the attack IP, please close, thank you.
