### ISSUE TITLE
💬 [Discussion]How to start Scourge Invasion event？

### ISSUE THREAD

**Issue by leechunlung** [vmangos/core#2645]
When I started version 1.11, no events occurred

**Comment by Wall-core** [comment]
Scourge Invasion and AQ war event are started manually. Check your game_event table, or use `!lookup event XXX` or `.event list` to view them ingame. Use `.event start XXX` to enable them.

**Comment by leechunlung** [comment]
> Scourge Invasion and AQ war event are started manually. Check your game_event table, or use `!lookup event XXX` or `.event list` to view them ingame. Use `.event start XXX` to enable them.

I can use `.war setstage num` to start a complete AQ war event. Scourge Invasion have such command?

**Comment by Wall-core** [comment]
yes, search your game_events table in your world database for "scourge", or `!lookup event Scourge` ingame.
![image](https://github.com/vmangos/core/assets/90075138/bca2cd7f-c40f-4d95-90b8-54b1a359b79f)

**Comment by leechunlung** [comment]
> yes, search your game_events table in your world database for "scourge", or `!lookup event Scourge` ingame. ![image](https://private-user-images.githubusercontent.com/90075138/337723617-bca2cd7f-c40f-4d95-90b8-54b1a359b79f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3ODEwNDEsIm5iZiI6MTcxNzc4MDc0MSwicGF0aCI6Ii85MDA3NTEzOC8zMzc3MjM2MTctYmNhMmNkN2YtYzQwZi00ZDk1LTkwYjgtNTRiMWEzNTliNzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDE3MTkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2MjRmYTkzNjRhNmE1MjAwOGZhNjFiMGU3MmQ0MGE1OTE5ZmQ0ZGNlOWYzNDU3OGE0ZTMyOTFiMTJkM2VmMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NZuPnXS4gDNgu25_5n5X7qf7gvoXsJLD0LuBbNfTWfs)

thanks ,.event start 17,I successfully start the event
