### ISSUE TITLE
🐛 [Bug][Priority: 5][Hermes Proxy] The new check in the anti-cheat is not working correctly.

### ISSUE THREAD

**Issue by gajet5** [vmangos/core#2653]
## 🐛 Bug report

https://youtu.be/fMwhjqtZx9c
https://youtu.be/EiqS9NPo3_A

```
2024-06-12 07:28:56 [Anticheat] (MovementAnticheat) (acc 1, ip , guid 13, name Tris, map 249, pos 27.3356 -61.3708 -4.82234) [MovementAnticheat] Player Tris:13 , Cheat BadMoveStart(Total:1), Penalty: Kicked.
2024-06-12 07:31:23 [Anticheat] (MovementAnticheat) (acc 1, ip , guid 13, name Tris, map 249, pos -4.04485 -236.907 -87.3825) [MovementAnticheat] Player Tris:13 , Cheat BadMoveStart(Total:1), Penalty: Kicked.

```

### Expected behavior
The anti-cheat does not work with false positives.

### Steps to reproduce

1. Watch the video.

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  https://github.com/vmangos/core/commit/17ed98cdae038cd139fb1d35b5d52fc4ee8ea93c

OS Client: Windows
OS Server: Ubuntu

### Crashlog

- None

**Comment by ratkosrb** [comment]
Can you send the pkt file created upon getting kicked? It will look something like this.

movement_log_ADMIN_1718074728.pkt

**Comment by gajet5** [comment]
[movement_log_GAJET_1718174835.zip](https://github.com/user-attachments/files/15799694/movement_log_GAJET_1718174835.zip)

Additional information.
I get the error on 1.14.0 client.

**Comment by ratkosrb** [comment]
Please tell me if the error happens with 1.12. The core is made for the vanilla client, its not a 1.14 core.

**Comment by gajet5** [comment]
I need time for testing. However, I want to say that other anti-cheat checks work correctly with 1.14 client.

**Comment by ratkosrb** [comment]
The anticheat checks are made for 1.12 specifically and I don't test them with 1.14 because the core is not for 1.14, you can only connect to it through Hermes, which lies to the core that its 1.12 client. If the issue exists only with 1.14, then simply disable this check in the config if you want to play on it with 1.14 client.

**Comment by gajet5** [comment]
Ok, I checked again on the 1.12 client and couldn't catch the kick. It turns out that the problem exists only in the 1.14 client in combination with the proxy.
Lowering the priority.

Yes, I disabled this option in the configuration on my server.
Thank you.
