### ISSUE TITLE
Player Animation gets cancled

### ISSUE THREAD

**Issue by Schmoha** [vmangos/core#266]
This issue is taken from Symmetry WoW and i have made a ticket but i did not get a response since a few days.
(Last Server Update 20th July. Shown in their Discord)

**Current behavior**: 
Some player animation gets cancled when using "Turn Left" or "Turn Right".
(Some Ability Animation gets cancled too but it will take to long for me to find proof for it)

**Expected behavior**: 
Shouldnt cancel animations when using "Turn Left" or "Turn Right".

Video proof:
https://youtu.be/szsudt5ze3Y?t=30

**Steps to reproduce**:
1. Try any Voice Emotes or Emotes.
2. Press "Turn Left" or "Turn Right".

**Client version**: 1.12

**Comment by ratkosrb** [comment]
Pretty sure this is not a server issue. The client decides to cancel the animation.

**Comment by Schmoha** [comment]
Aww thats sad, that means we will never see this work?
