### ISSUE TITLE
🦂 [Bug]In the battle against Heigan the Unclean, there is no damage from terrain venom spraying

### ISSUE THREAD

**Issue by leechunlung** [vmangos/core#2661]
### Steps to reproduce

1.In the battle against Heigan the Unclean, there is no damage from terrain venom spraying
2.The team does not need to make any movements to avoid damage
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by ratkosrb** [comment]
![WoWScrnShot_061724_130418](https://github.com/vmangos/core/assets/35845488/4ff6bf6d-126b-4a0c-8196-5610a1a05cfa)

It's damaging me in my tests.

**Comment by leechunlung** [comment]
I tested again and there was still no Nature damage, but I used the Build from June 10th.
From the beginning of the battle until the end, the effect of the Venom Fountain is not even visible on the field.
Is it because I translated the BOSS word?

**Comment by leechunlung** [comment]
I tested again and using the latest build without any modifications, and the problem still exists
