### ISSUE TITLE
🐝 [Bug] Cannot Complete quest The Human Ras Frostwhisper

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2664]
## 🐝 Bug report - Quest
Using https://www.wowhead.com/classic/item=13585/keepsake-of-remembrance on Ras does not turn him into a human and thus doesn't let you loot his head

### Expected behavior
https://www.wowhead.com/classic/quest=5461/the-human-ras-frostwhisper
Using and fully channeling https://www.wowhead.com/classic/item=13585/keepsake-of-remembrance on Ras should turn Ras into a human and then you should be able to loot his head for the quest.

### Version & Environment

Client Version:  1.12.1

**Comment by ratkosrb** [comment]
![WoWScrnShot_061724_114500](https://github.com/vmangos/core/assets/35845488/8c354685-9e58-486b-b687-f03f59ed015b)
![WoWScrnShot_061724_114517](https://github.com/vmangos/core/assets/35845488/d04491bc-dc90-4896-8d8c-1d022535174a)

I cannot reproduce the issue. The item worked, and I looted his head. Why do you not mention the commit hash in your issue? Are you using some other source, not the official one?

**Comment by ShiyoKozuki** [comment]
I'm on the official repo.
I deleted spawns from scholomance(the ones that should despawn once rattlegore dies, but they aren't properly coded, there's already a big bug report on it with lots of details).
Would that be the cause of this issue somehow?

**Comment by ratkosrb** [comment]
I don't know because it works for me. He transforms into a human and i loot his head.
