### ISSUE TITLE
🐞 [Bug][1.7.1] Spirit of Redemption immortal

### ISSUE THREAD

**Issue by Daribon** [vmangos/core#2665]
## 🐞 Bug report - Spell

If you put a talent point into Spirit of Redemption in 1.7.1, you become unable to die.

I believe its bugged on every version before 1.10.0 since it used to work differently, but I have thus far only tested on 1.7.1.

[Patch 1.10.0](https://warcraft.wiki.gg/wiki/Patch_1.10.0) (2006-03-28): Redesigned. Upon death, the priest becomes the Spirit of Redemption for 10 sec. The Spirit of Redemption cannot move, attack, be attacked or targeted by any spells or effects. While in this form the priest can cast any healing spell free of cost. When the effect ends, the priest dies.

    Previous effect: Upon death, summons a Spirit of Redemption that heals nearby friendly targets for 318 to 360 and another 343 over 21 seconds.

### Expected behavior

Upon death, the talent should summon a Spirit of Redemption that heals nearby friendly targets for 318 to 360 and another 343 over 21 seconds.

See video from pre 1.10: https://youtu.be/AgNion-cGRE?si=_74k64tzn3-NH4mR&t=20

### Steps to reproduce

1. Create a priest
2. .level 60
3. Attempt to kill yourself.
4. You cannot die.

### Version & Environment

Client Version: 1.7.1.4695

Commit Hash:  https://github.com/vmangos/core/commit/8819ab130e84900538888185f29a2d8164863101

OS Client: Windows 11 Pro N 10.0.22631 Build 22631
OS Server: Windows 11 Pro N 10.0.22631 Build 22631

### Crashlog

- None

**Comment by ratkosrb** [comment]
Any idea about the spell ids of the heals it casts?

**Comment by ratkosrb** [comment]
Oh i think it's just this spell that also summons the mob that should be cast on death, and the npc doesn't actually cast anything.

https://classicdb.ch/?spell=20713

**Comment by Daribon** [comment]
> Oh i think it's just this spell that also summons the mob that should be cast on death, and the npc doesn't actually cast anything.
> 
> https://classicdb.ch/?spell=20713

ye that seems correct.
![QSW_8rAH2A2jAc](https://github.com/vmangos/core/assets/6137576/ccae6533-bf9a-45a0-b201-66ee6e699ce5)

NPC 12904:
![WoW_iT0TNUAOzn](https://github.com/vmangos/core/assets/6137576/5d158bee-b560-462d-b126-26b41603075c)

**Comment by Daribon** [comment]
Actually, I think I figured it out.
Player cast 20713 which heals the party, the NPC Spirit Of Redemption is spawned. Player dies.

Spirit Of Redemption casts 20723:
![WoW_fkxrdt1wKh](https://github.com/vmangos/core/assets/6137576/2b81f3cd-ba23-41da-8633-5a110968cc1f)
Spirit Of Redemption casts: 20721:
![WoW_ssW3FLrJyL](https://github.com/vmangos/core/assets/6137576/7a8c8389-0261-4f2d-9279-f7071ad8694e)

Both of those spells at the same time:
![WoW_Ta4eIsVOqw](https://github.com/vmangos/core/assets/6137576/60fa6f91-c3c6-49c6-a248-77b8071117a6)

This matches the Swifty video that I posted previously.
