### ISSUE TITLE
🐛 [Bug] I test  ( 2024/4/17 22:41:43) update  can  High CPU usage >15%

### ISSUE THREAD

**Issue by gaosheng136** [vmangos/core#2678]
Commit hash:	79c5f503df39cd92eccc399443f8502eb8f9c248 
Commit date:	 (2024/4/17 22:41:43)
I test  ( 2024/4/17 22:41:43) update  can  High CPU usage
CPU usage>15%   no player online

**Comment by ratkosrb** [comment]
Do you believe the problem is caused by the commit you linked?

**Comment by ratkosrb** [comment]
I have reverted all the readline commits and the issue seems to be solved for me.
