### ISSUE TITLE
🐛 [Bug] GM commands ,  add new Item ( bind when picked up) could be traded.

### ISSUE THREAD

**Issue by william19831103** [vmangos/core#2698]
a. use gm comands, additem,  Add one new item to me,  this item is seted to be binded when picked up 
b. dont move this item ,and  put this new item into trade solt, I could trade this item to another player.
c. if move this item to another solt, item can not be traded.

**Comment by Gamemechanicwow** [comment]
That's intentional. It allows GMs to add items to their inventory and trade them to players.

It's useful for item restoration.
