### ISSUE TITLE
🐝 [Bug]The Only Prescription task cannot be obtained Chapter 7 Draconic for Dummies

### ISSUE THREAD

**Issue by yybss** [vmangos/core#2704]
When the player completes the Gates of Ahn'Qiraj mission: The Only Solution, Chapter 7 The Dragon Language Tutorial for Dummies will appear on the table in Blackwing Lair, but the player cannot obtain it correctly. The page appears blank after opening, but after I use the GM account to enable GM permissions, it becomes normal and other players cannot obtain it.
![微信截图_20240720233124](https://github.com/user-attachments/assets/b747f07b-c448-4c44-a603-b5f4f8751bb9)
![微信图片_20240720233144](https://github.com/user-attachments/assets/e79f38bf-81fe-4867-aa94-f064cb8fd5b2)

**Comment by yybss** [comment]
The core is 20240605

**Comment by Daribon** [comment]
It's possible that I might have broken it when I was respawning BWL. On first glance I cannot see anything that would break it, but I will have a deeper look soon:
https://github.com/vmangos/core/commit/e454aeb9396cacad8ab393c115fa298fca8302a0#diff-75302771e9ef7bc9de0d73e8d7c76ce17cabb091e261263c5b08313fe1da66cfR429

**Comment by Daribon** [comment]
Can't reproduce on 1.12.1 enUS:
![WoW_j9aDok0DP2](https://github.com/user-attachments/assets/985799ab-10c3-4a92-81d5-045308ba977b)
It opens without any issue without gm on.

Can't reproduce on 1.12.1 zhCN:
![Wowsad_zdZwqjNCJj](https://github.com/user-attachments/assets/256d0508-a0c9-49cf-93a0-2623ff2a3f45)
The gossip text appears to be wrong, but the gossip option does show up as expected.

Oddly the gossip text does show up in complete draconic for all other languages:
deDE:
![WoW_zoYnNEM4Uw](https://github.com/user-attachments/assets/77e1c524-1998-49e3-b7a8-dd50a407be47)
krKR:
![WoW_IjxZQyBKQa](https://github.com/user-attachments/assets/51e5de85-c2df-4ff6-b823-b928192f296e)
So maybe the gossip text is just a client bug where it cannot do more than a word in draconic when chinese locale.

As for the gossip option not showing up in non gm mode, it works for me on every locale so perhaps try clearning cache.

**Comment by gajet5** [comment]
I also had a player with this problem on my server. 
I couldn't repeat it on another character.

**Comment by FlagFlayer** [comment]
I think the gossip_menu_options are using the wrong conditions:

gossip_menu_option 6669 uses condition 151 (Checks if you have The Only Perscription AND DO NOT have Chapter VII of Draconic for Dummies) and is tied to gossip_script 6669 which uses the spell 25764 which gives you Draconic for Dummies Chapter V (not VII).

Opposite is true for 6668 (gives Chapter VII, checks for not having Chapter V)

Should be a quick fix, I'll open a PR for it.
