### ISSUE TITLE
🦂 [Bug][Naxxramas] The fight does not start with Gothic after his attack.

### ISSUE THREAD

**Issue by gajet5** [vmangos/core#2716]
## 🦂 Bug report - Dungeon
https://youtu.be/VNvX470gX84

### Expected behavior
The fight starts with Gothic after his attack.

### Steps to reproduce

1. Go to Gothic in Naxx
2. Attack him.
3. Profit

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  No

OS Client: Win
OS Server: Ubuntu

### Crashlog

- None

**Comment by ratkosrb** [comment]
It's intended to not start with less than 10 players per side.

**Comment by gajet5** [comment]
Yes, everything is working well. Thanks for the explanation.
