### ISSUE TITLE
Hunter pets cannot learn skills

### ISSUE THREAD

**Issue by amydomi** [vmangos/core#272]
Hunter pets cannot learn skills

**Comment by ratkosrb** [comment]
I cannot reproduce the issue.
https://streamable.com/s612v

You can see I am able to train my pet.

**Comment by amydomi** [comment]
issue:
https://streamable.com/3qnp9

client version:
1.12.3  (6141)  

language:
Chinese

server os:
Ubuntu 18.04.1 LTS

Thanks to answer!
