### ISSUE TITLE
The program crash

### ISSUE THREAD

**Issue by wthslw001** [vmangos/core#273]
1 parent 643785a commit 08fbd104768adfb7fc5d9e656e4fe6cdc60a275a

2019-10-01 17:30:25 E:\GitHub\Vmangos\core\src\game\Spells\SpellAuras.cpp:6253: Error: Assertion in SpellAuraHolder::SpellAuraHolder failed: caster->isType(TYPEMASK_UNIT)
2019-10-01 17:30:25 Aura::ComputeExclusive()+0x1a4 [0x21bf64]
GridReference<DynamicObject>::GridReference<DynamicObject>()+0x107e [0x24633e]
PatrolMovementGenerator::Update()+0x119d [0x24528d]
PatrolMovementGenerator::Update()+0x569 [0x244659]
PatrolMovementGenerator::Update()+0x3c9 [0x2444b9]
GridReference<DynamicObject>::GridReference<DynamicObject>()+0xb56 [0x245e16]
ChatHandler::HandleRunTestCommand()+0xdd81 [0x23b2b1]
Map::UpdateCellsAroundObject()+0x21c [0x11babc]
Map::UpdateActiveCellsSynch()+0x9e [0x11af7e]
Map::UpdateCells()+0xa7 [0x11b6a7]
Map::Update()+0x263 [0x119c03]
GetSpellRangeStore()+0x6481 [0x1aeda1]
BarGoLink::step()+0xc2f [0x4c676f]
ACE_OS_Thread_Adapter::invoke()+0x94 [0x6e2e4]
o__realloc_base()+0x60 [0x1f4a0]
BaseThreadInitThunk()+0x14 [0x84d4]
RtlUserThreadStart()+0x21 [0x6e851]

**Comment by ratkosrb** [comment]
Somehow an aura holder is created with a gameobject caster. I will fix it in a few days when I have more time.
