### ISSUE TITLE
🐛 [Bug] A Battered Chest spawn already open in Mulgore

### ISSUE THREAD

**Issue by ghost** [vmangos/core#2769]
## 🐛 Bug report
In Mulgore "Ravaged Caravan" subzone a battered chest can spawn already open preventing the player from looting it.

I think I've found the issue in this commit line https://github.com/vmangos/core/commit/b9258134106800e466d2b61d067995ea872fad5f#diff-6664df0611044e027e8948a635c3df58d0fd26cf928dd874395e1ac38cc24fd1R55 the entry "@CHEST8" (or 60099) in the gameobject table is registered with a 0 in the "state" field while all the others are registered with a 1, and that chest, as mentionned in the comment, spawn in the Ravaged Caravan subzone so this should be the issue.

**Comment by Wall-core** [comment]
Have you confirmed this on classic as being blizzlike? As far as I'm aware, this is intended to be open as it's part of the ravaged caravan scenery, giving the idea that the chest was pilfered.

**Comment by ghost** [comment]
> Have you confirmed this on classic as being blizzlike? As far as I'm aware, this is intended to be open as it's part of the ravaged caravan scenery, giving the idea that the chest was pilfered.

I haven't played Classic for a long time so I can't confirm anything unfortunately, this just seems off to me as it is pooled like all the other chests but as you said maybe it's part of the scenery after all.

**Comment by FlagFlayer** [comment]
that's incorrect, the chest should be lootable https://youtu.be/gLyZ2mEXWyY?si=7MoCsnn_oxefkP4x&t=117

**Comment by FlagFlayer** [comment]
Since it hasn't been mentioned yet, this will be fixed with https://github.com/vmangos/core/pull/2845
