### ISSUE TITLE
[Core]server freeze issue

### ISSUE THREAD

**Issue by coolzoom** [vmangos/core#278]
Hi Bro, this is the step we can repeat the server freeze issue. 
I know this Commit hash may still an ongoing modifications, the crash may or ,may not fixed in the newest commit, but it would be a good case for us to investigate the "server freeze" issue.

**Current behavior**: 
Server freeze when meets a assert inside Object.h

**Expected behavior**: 
Server should crash for assert or null.

**Steps to reproduce**:

1. crate a paladin, .level 59  .learn all_myclass
2,  .go creature 51120
3, attack it until you can use Hammer of Wrath
4, cast hammer of wrath, server freeze

* use mangosd.exe, the console is freeze and ingame content are also freeze,
* use visual studio debug mode, it will stop at Object.h line 385 saying "this" is a null value
* modify the GetUInt32Value to below and add a crash intentially,
        const uint32& GetUInt32Value( uint16 index ) const
        {
			if (this)
			{
				MANGOS_ASSERT(index < m_valuesCount || PrintIndexError(index, false));
			}
			else
				*((int*)NULL) = 42; // Crash 
            return m_uint32Values[ index ];
        }
  compile a new mangosd.exe and run through that, repeat step 1 to 4 and the server also freeze(it should crash)

**Client version**: 
1.21.1

**Commit hash**: 
643785adee32773d560f22d7c73f0cc0d1fbf216 
Allow moving items in bags while dead.
**Operating system**: 
Windows

**Comment by ratkosrb** [comment]
Closing this as the Hammer of Wrath crash is already fixed.
https://github.com/vmangos/core/commit/062f09fe0ea135c5073df87ecba214f1c1dad5bd
