### ISSUE TITLE
🐛 [Bug] Movement speed not reset

### ISSUE THREAD

**Issue by ghost** [vmangos/core#2781]
## 🐛 Bug report
Movement speed does not seem to be reset on evade/respawn.

### Expected behavior
Movement speed should reset on evade/respawn.

### Steps to reproduce
- `.gm on`
- `.go cr 16181`
- `.gm off`
- get in combat with the creature
- select the creature
- `.aura 7373`
- `.gm on`
- creature evades and resumes WP movement, but very slowly

or

- `.gm on`
- `.go cr 16181`
- `.gm off`
- get in combat with the creature
- select the creature
- `.aura 7373`
- `.die`
- `.respawn`
- creature respawns and starts WP movement, but very slowly

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash: 450073cc58ddd99c9005646198423255b034b775

OS Client: Ubuntu 22.04 (Wine)
OS Server: Ubuntu 22.04

### Crashlog

- None

**Comment by ratkosrb** [comment]
The run speed is restored, but the walk speed seems to get reduced after creature leaves combat.

**Comment by ratkosrb** [comment]
I think it's related to shapeshift auras (the defensive stance they cast).

**Comment by ghost** [comment]
It is not happening for auras anymore, but if you bring down a creature to very low health and it flees with reduced speed it will respawn with reduced walking speed:
- `.gm on`
- `.go cr 16181`
- `.gm off`
- get in combat with the creature and bring it to very low health, so it flees with reduced speed
- kill the creature
- `.respawn`
- creature respawns and starts WP movement, but very slowly
