### ISSUE TITLE
🐝 [Bug] Cycle of Rebirth (quest 6301) - RP event missing

### ISSUE THREAD

**Issue by ghost** [vmangos/core#2785]
## 🐝 Bug report - Quest
If I remember correctly Tammra Windfield (id 11864) should plant one of the Gaea Seeds in the ground after turning in the quest "Cycle of Rebirth". She also refers to this event in the quest text of the next quest.

### Expected behavior
see above

### Steps to reproduce
1. `.q rem 6301`
2. `.q a 6301`
3. `.q c 6301`
4. `.go cr id 11864`
5. turn in the quest

### Version & Environment
Client Version: 1.12.1.5875
Commit Hash: f6da813251cd1ecd08931cc1d928bacf33607ab7

OS Client: Ubuntu 22.04 (Wine)
OS Server: Ubuntu 22.04

### Crashlog
- None

**Comment by ratkosrb** [comment]
There already is a completion script attached to this quest.

**Comment by ghost** [comment]
Yes, but nothing happens:
https://github.com/user-attachments/assets/313c19ab-914b-48dc-b5e6-24bd48fd99b3
