### ISSUE TITLE
🐛 [Bug] Cannot stop server using command "server exit"

### ISSUE THREAD

**Issue by ghost** [vmangos/core#2786]
## 🐛 Bug report

After applying commit f6da813251cd1ecd08931cc1d928bacf33607ab7 it is not possible to stop the world server anymore using command "server exit". The server hangs after writing "Shutting down world..." and has to be killed manually.

### Expected behavior
Command "server exit" should work as before.

### Steps to reproduce
Start server and use command "server exit".

### Version & Environment
Client Version: 1.12.1.5875
Commit Hash: f6da813251cd1ecd08931cc1d928bacf33607ab7

OS Client: Ubuntu 22.04 (Wine)
OS Server: Ubuntu 22.04

### Crashlog
- None

**Comment by Wall-core** [comment]
try .server shutdown {seconds}
or abbreviated, .s s 1

**Comment by ghost** [comment]
Thanks, but this is just a workaround, not a solution. The command "server exit" should work as it did before f6da813251cd1ecd08931cc1d928bacf33607ab7.

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/93bb983d546961e95d67982db174ed18595b672d
