### ISSUE TITLE
The program crash

### ISSUE THREAD

**Issue by wthslw001** [vmangos/core#279]
![image](https://user-images.githubusercontent.com/8679316/66331228-9ce89380-e964-11e9-96c0-7d109aef1819.png)

**Comment by ratkosrb** [comment]
What were you doing when it crashed? Did you cast any spell?

**Comment by wthslw001** [comment]
![image](https://user-images.githubusercontent.com/8679316/66332834-3b2a2880-e968-11e9-9c05-349b26952f42.png)

**Comment by wthslw001** [comment]
I am moving。 
ERROR in here：
![image](https://user-images.githubusercontent.com/8679316/66333089-c73c5000-e968-11e9-8df1-52272ad915b6.png)
