### ISSUE TITLE
🐛 [Bug] No Sagefish schools appear along the coast of The Barrens.

### ISSUE THREAD

**Issue by Florian-2023** [vmangos/core#2805]
## 🐛 Bug report

No Sagefish schools appear ever along the coast of The Barrens. 
### Expected behavior

To my memory and this website https://classicdb.ch/?object=180656 (no info available on Wowhead, sorry) 
the Sagefish schools would appear in turn with the Oily Blackmouth and Floating Wreckage etc.
### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 
1.12.1.5875

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by NickTyrer** [comment]
Sagefish schools only spawn in the river near lake nazferiti (data taken from sniffs)

**Comment by Florian-2023** [comment]
OK, I think you mean the Schools for GREATER Sagefish. 
They do INDEED spawn in the river near Lake Nazferiti
These are different from Sagefish.
I wonder if you even have played this game?

**Comment by ratkosrb** [comment]
Don't act hostile towards others or you'll be blocked by the organization.

**Comment by Florian-2023** [comment]
OK, I agree.
Would it be OK if I remove the last line?
And would the topic be reopened?

**Comment by NickTyrer** [comment]
classicdb.ch data is taken from incorrect private server data. The fishing pools are now blizzlike as they are taken from sniffs. 


https://www.wowhead.com/classic/item=21153/raw-greater-sagefish

https://www.wowhead.com/classic/item=21071/raw-sagefish

**Comment by Florian-2023** [comment]
Thanks for your answer.
I am sorry I wrote that one line.
I hope you have a nice day.
