### ISSUE TITLE
🦂 [Bug] Pathfinding in Uldaman

### ISSUE THREAD

**Issue by ghost** [vmangos/core#2808]
## 🦂 Bug report - Dungeon

Pathfinding in Uldaman is wrong near some of the stairs:
https://github.com/user-attachments/assets/3f3acc9e-ca62-48b3-a1e0-0744dcbd1bc9

### Expected behavior

The pet should follow the player directly over the stairs.

### Steps to reproduce

1. Create a hunter or warlock with pet
2. `.gm on`
3. `.go -87.825821 284.461823 -47.629398 70`
4. run down the stairs

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash: 07af1ae2b93089d71b1a4e8f06fa64c6380c377f

OS Client: Ubuntu 24.04 (Wine)
OS Server: Ubuntu 22.04

### Crashlog

- None

**Comment by Gamemechanicwow** [comment]
I can't reproduce this issue. 

Are you using mmap's from a repack or did you generate them yourself?

**Comment by ghost** [comment]
Extracted the data myself using the following steps:
(this already uses the new tool names introduced in commit 6017bf4d55227cbef8f62eb558697d7504ef3f9e)

- Go to the client directory:

```
cd ~/client
```

- Generate dbc, maps & vmaps:

```
~/vmangos-srv/bin/Extractors/MapExtractor -f 0
~/vmangos-srv/bin/Extractors/VMapExtractor -l
~/vmangos-srv/bin/Extractors/VMapAssembler
```

- Generate mmaps:

```
mkdir mmaps
cp ~/vmangos/core/contrib/mmap/config.json ~/vmangos/core/contrib/mmap/offmesh.txt .
for i in 0 1 13 29 30 33 34 35 36 37 42 43 44 47 48 70 90 109 129 169 189 209 229 230 249 269 289 309 329 349 369 389 409 429 449 450 451 469 489 509 529 531 533
do
  ~/vmangos-srv/bin/Extractors/MoveMapGenerator --silent $i 1>/dev/null 2>&1 &
done
```

- Wait until all `MoveMapGenerator` processes are finished:

```
while [ $(pgrep -f MoveMapGenerator | wc -l) -ne 0 ]; do sleep 1; done
```

- Move data:

```
mkdir -p ~/vmangos-srv/data/5875
mv dbc ~/vmangos-srv/data/5875
mv maps vmaps mmaps ~/vmangos-srv/data
```

**Comment by ghost** [comment]
Tested the maps from Brotalnia's repack (version 23) and the issue does not occur there. So there seems to be something wrong with the extractor tools. Will stick with the maps from the repack for now.

**Comment by ghost** [comment]
Extracted the client data again and the issue does not occur anymore. Seems to have been fixed in one of the recent commits.
