### ISSUE TITLE
🦂 [Bug]Anub'Rekhan's spell Locust Swarm ID28785 will be squeezed out and replaced due to debuffs exceeding 16

### ISSUE THREAD

**Issue by leechunlung** [vmangos/core#2830]
### Steps to reproduce

1.Anub'Rekhan's spell Locust Swarm ID28785 will be squeezed out and replaced due to debuffs exceeding 16
2.When you have many warriors and warlocks in your group, fill up the debuff field
3.The Locust Swarm skill will be excluded
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by NickTyrer** [comment]
No Commit Hash
