### ISSUE TITLE
🐛 [Bug]Gothik the Harvester After starting the battle, automatically leave the battle

### ISSUE THREAD

**Issue by ss958** [vmangos/core#2847]
🐛 [Bug]Gothik the Harvester After starting the battle, automatically leave the battle
![QQ20241209-234028](https://github.com/user-attachments/assets/b3fcd1f4-db28-43a1-89b3-563851c6f06a)

**Comment by gajet5** [comment]
Two groups are required in two rooms.
https://github.com/vmangos/core/issues/2716

**Comment by ss958** [comment]
How do I modify it if I want to do it alone?

**Comment by ratkosrb** [comment]
You have to edit the c++ script for the boss.

https://github.com/vmangos/core/blob/development/src/scripts/eastern_kingdoms/eastern_plaguelands/naxxramas/boss_gothik.cpp

**Comment by gajet5** [comment]
> How do I modify it if I want to do it alone?

This line: https://github.com/vmangos/core/blob/development/src/scripts/eastern_kingdoms/eastern_plaguelands/naxxramas/boss_gothik.cpp#L399
and this:
https://github.com/vmangos/core/blob/development/src/scripts/eastern_kingdoms/eastern_plaguelands/naxxramas/instance_naxxramas.cpp#L831

**Comment by ss958** [comment]
Thank you brother, it has been resolved!
