### ISSUE TITLE
NPC greeting hard coding

### ISSUE THREAD

**Issue by aleigood** [vmangos/core#285]
![snipaste_20191017_144755](https://user-images.githubusercontent.com/3367999/66984389-31818d00-f0ed-11e9-8730-7840ee14ebed.png)
![snipaste_20191017_144809](https://user-images.githubusercontent.com/3367999/66984520-70174780-f0ed-11e9-92ab-6744d5deff48.png)
![snipaste_20191017_140053](https://user-images.githubusercontent.com/3367999/66984528-73aace80-f0ed-11e9-8fc7-d8dd4b49b44e.png)

**Comment by Daribon** [comment]
Greetings are all just placeholder text for missing text.

**Comment by aleigood** [comment]
> Greetings are all just placeholder text for missing text.

Should the missing text be add the NPC data in database?

**Comment by Kittnz** [comment]
if you have it, yeah :)

**Comment by aleigood** [comment]
Could placeholder text replace with localized text? A lot of this data seems to be missing.

**Comment by solo0755** [comment]
@aleigood   are u have any  more Data  for  Chinese locailzed ,i found the current db not completely sinicized ,can u give me you Chinese locailzed data?
