### ISSUE TITLE
Image loading problems in different language clients

### ISSUE THREAD

**Issue by aleigood** [vmangos/core#287]
Faded photo can be loaded normally in English client, but not displayed in Chinese client.
![snipaste_20191019_202043](https://user-images.githubusercontent.com/3367999/67144866-71dc3900-f2ae-11e9-829e-28df2d159758.png)
![snipaste_20191019_202104](https://user-images.githubusercontent.com/3367999/67144872-77d21a00-f2ae-11e9-8853-84c6b763f74e.png)

**Comment by aleigood** [comment]
This is a localized db script bug.

**Comment by solo0755** [comment]
how can i fix it?

**Comment by aleigood** [comment]
Repace all “InterfacePictures” with "Interface\\Pictures\\" in locales_page_text table script.

**Comment by solo0755** [comment]
done,thanks for it.
