### ISSUE TITLE
Bug of training points display

### ISSUE THREAD

**Issue by aleigood** [vmangos/core#289]
For a new tamed pets, there is a problem with the training points:
![Inkedsnipaste_20191020_155218_LI](https://user-images.githubusercontent.com/3367999/67157418-5fb9d380-f35e-11e9-9dff-846e4a351cd4.jpg)

**Comment by ratkosrb** [comment]
This is not a bug. You need to gain loyalty to increase your training points.

Read more here about it here.
https://www.wowhead.com/forums&topic=21067
