### ISSUE TITLE
Creatures that can't get ashore can't get out of combat

### ISSUE THREAD

**Issue by forever2019** [vmangos/core#294]
Creatures that can't get ashore can't get out of combat

1. Find a river or lake creature.
2. Attacking creatures in rivers or lakes.
3. Go ashore at once, run straight ahead, you will find out if you can get out of the battle.

**Client version**: 
1.12

**Commit hash**: 
edeab985d9fd8ced986a827d25c9e48748ca08b5

**Operating system**: 
win10 64bit

**Comment by ratkosrb** [comment]
I can't reproduce the issue. The mobs evade after ~15 seconds and I leave combat.
