### ISSUE TITLE
NPC walk path problem

### ISSUE THREAD

**Issue by aleigood** [vmangos/core#297]
Light's Hope Chapel:
![bug2](https://user-images.githubusercontent.com/3367999/68219306-bc84e180-0020-11ea-87e2-2fa00edc039c.gif)

Feathermoon Stronghold:
![bug3](https://user-images.githubusercontent.com/3367999/68219341-cb6b9400-0020-11ea-9d37-de47413df5ec.gif)

**Comment by alexkulya** [comment]
@aleigood try this:

<pre>
UPDATE `creature_movement` SET `position_x` = -4374.089355, `position_y` = 3288.326416, `position_z` = 13.564932 WHERE `id` = 49969 AND `point` = 4;

DELETE FROM `creature_movement` WHERE `id` = 60003;
INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `wander_distance`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `orientation`, `model1`, `model2`) VALUES
(60003, 1, 2264.13, -5312.18, 81.88, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(60003, 2, 2258.24, -5319.82, 81.66, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(60003, 3, 2254.18, -5324.55, 82.08, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(60003, 4, 2238.68, -5311.63, 82.17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(60003, 5, 2250.41, -5291.89, 82.16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
</pre>

**Comment by aleigood** [comment]
Yeah, it's resolved, thanks!

> @aleigood try this:
> 
> UPDATE `creature_movement` SET `position_x` = -4374.089355, `position_y` = 3288.326416, `position_z` = 13.564932 WHERE `id` = 49969 AND `point` = 4;
> 
> DELETE FROM `creature_movement` WHERE `id` = 60003;
> INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `wander_distance`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `orientation`, `model1`, `model2`) VALUES
> (60003, 1, 2264.13, -5312.18, 81.88, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
> (60003, 2, 2258.24, -5319.82, 81.66, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
> (60003, 3, 2254.18, -5324.55, 82.08, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
> (60003, 4, 2238.68, -5311.63, 82.17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
> (60003, 5, 2250.41, -5291.89, 82.16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

Yeah, it's resolved, thanks!
