### ISSUE TITLE
Weapon specific spells works for all weapon types

### ISSUE THREAD

**Issue by BBCnewstoday** [vmangos/core#299]
ALL +dmg talents that should affect only specific one weapon types works for all weapon types.

eg Two-Handed Weapon Specialization(warrior talent) affects one-handers and ranged weapons, Ranged Weapon specialization affects two-handers and ranged etc.

The effects stack, so you can even take both one-handed and two-handed spec and both bonuses with total +15% dmg for both weapon types.

**Comment by ratkosrb** [comment]
This was only a visual bug. It didn't actually increase the damage for other weapon types.
