### ISSUE TITLE
startup crash with new code Merge

### ISSUE THREAD

**Issue by caicaicai** [vmangos/core#302]
**Current behavior**: 
crash
**Expected behavior**: 
can start up
**Steps to reproduce**:

1. run mangosd.exe
2. crash

**Client version**: 
1.12
**Commit hash**: 
src/game/Database/SQLStorages.cpp
bbc3360de6d069cad695e7c6e960aa91e7cfb8ea
**Operating system**: 
win7

I noticed that this version added a new table(mail_text_template), but my database does not have this table, the database upgrade file did not create this table, the application failed to start.

**Comment by ratkosrb** [comment]
You are using the old database release. You need to drop your current world database, and import from the release.

https://github.com/brotalnia/database/blob/master/world_full_05_october_2019.7z

**Comment by caicaicai** [comment]
ok
