### ISSUE TITLE
Unrecognizable characters and test message in script

### ISSUE THREAD

**Issue by aleigood** [vmangos/core#304]
File path: src/scripts/kalimdor/winterspring/winterspring.cpp

![image](https://user-images.githubusercontent.com/3367999/68871951-33fcf400-0738-11ea-91ee-c2305705e1ed.png)
![image](https://user-images.githubusercontent.com/3367999/68872070-66a6ec80-0738-11ea-83bf-0713449cd9f1.png)

**Comment by Kittnz** [comment]
https://github.com/vmangos/core/blob/development/src/scripts/kalimdor/winterspring/winterspring.cpp#L555

https://github.com/vmangos/core/blob/development/src/scripts/kalimdor/winterspring/winterspring.cpp#L627

**Comment by Daribon** [comment]
All of it appears to be debugging text.
