### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by aleigood** [vmangos/core#307]
`Scanning dependencies of target MoveMapGen
[ 98%] Building CXX object contrib/mmap/CMakeFiles/MoveMapGen.dir/src/IntermediateValues.cpp.o
In file included from /opt/mangos/src/contrib/mmap/src/IntermediateValues.h:23:0,
                 from /opt/mangos/src/contrib/mmap/src/IntermediateValues.cpp:19:
/opt/mangos/src/contrib/mmap/src/TerrainBuilder.h:139:19: error: extra qualification ‘MMAP::TerrainBuilder::’ on member ‘getLiquidType’ [-fpermissive]
             uint8 TerrainBuilder::getLiquidType(int square, const uint8 liquid_type[16][16]);
                   ^~~~~~~~~~~~~~
make[2]: *** [contrib/mmap/CMakeFiles/MoveMapGen.dir/build.make:63: contrib/mmap/CMakeFiles/MoveMapGen.dir/src/IntermediateValues.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:730: contrib/mmap/CMakeFiles/MoveMapGen.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
`

**Operating system**: 
CentOS 7.3 64 GCC 7.3.1

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/0b6009c6f315600a5cab0cde8f2cf2360f8a105f
