### ISSUE TITLE
The hunter's skill, volley, becomes a single attack

### ISSUE THREAD

**Issue by gamelgs** [vmangos/core#309]
The hunter's skill, volley, becomes a single attack

**Client version**: 
1.12 5875
**Commit hash**: 
 a1eaed5643470bb10dbfae75ff75dcd5f5a05dc1
**Operating system**: 
WIN10

**Comment by ratkosrb** [comment]
I cannot reproduce the issue.
https://streamable.com/hrwtu

**Comment by gamelgs** [comment]
Thanks for your reply.
