### ISSUE TITLE
Firelord immune Frostbolt in MC

### ISSUE THREAD

**Issue by gamelgs** [vmangos/core#310]
Firelord immune Frostbolt in MC

**Client version**: 
1.12.1 5875
**Commit hash**: 
df76eff1d379c8765f7ae5eab2dda680b390401a
**Operating system**: 
Win10

**Comment by ratkosrb** [comment]
I am not sure what you are referring to. Please elaborate with more details.

**Comment by gamelgs** [comment]
![123](https://user-images.githubusercontent.com/54333950/69454865-24b62000-0da2-11ea-9574-998ec8e65339.png)  Frostbolt cannot attack this creature
All frost skills immune

**Comment by ratkosrb** [comment]
I cannot reproduce the issue. This mob is not immune to frost damage.
https://streamable.com/1niy5

**Comment by ratkosrb** [comment]
Can anyone else reproduce this issue?

**Comment by coolzoom** [comment]
oh boy, turn off your GM mode.... look at the mob is in yellow
