### ISSUE TITLE
How to re-extract map data？

### ISSUE THREAD

**Issue by wthslw001** [vmangos/core#314]
https://github.com/vmangos/core/pull/303
Excuse me, Do you have the new map data for Win program?

**Comment by ghost** [comment]
Brotalnia said, he will include the new extracted maps in his new repack.
If you cannot wait, try to extract it by yourself.

For further questions join our discord -> https://discord.gg/pUkCm2

**Comment by wthslw001** [comment]
> Brotalnia said, he will include the new extracted maps in his new repack.
> If you cannot wait, try to extract it by yourself.
> 
> For further questions join our discord -> https://discord.gg/pUkCm2

Thank you very much.
