### ISSUE TITLE
a few pet bugs

### ISSUE THREAD

**Issue by gamelgs** [vmangos/core#318]
1. In the dungeon, the hunter attacks one target, but the pet does not attack the same target.

2. The hunter's pet is occasionally in a trance.

**Client version**: 
1.12  5785
**Commit hash**: 
e4dfbe022895892a8ba5db753ead9f45cd7b43fb
**Operating system**: 
win10

**Comment by ratkosrb** [comment]
You will need to provide more details. Record the issue on video so we can see what you are talking about.

**Comment by gamelgs** [comment]
https://youtu.be/0bLsLGjJu7A

**Comment by ratkosrb** [comment]
What is the bug in this video? You did not tell the pet which target to attack. If you want it to attack a specific target, you must select it and click the Attack button on the pet bar.

**Comment by gamelgs** [comment]
Shouldn't pets automatically attack the same target of hunters?

**Comment by ratkosrb** [comment]
No it should not automatically attack your target. You should make a pet attack macro if you want to do that. But now I realize there is indeed a bug in this video, however it's not the one you think. When the pet is in Defensive mode, it should only attack when its owner is attacked. So in this case it should not have attacked at all until one of the mobs you were fighting hit you.

**Comment by ratkosrb** [comment]
Fixed the real issue that was discovered.
https://github.com/vmangos/core/commit/3d6b64e74dd953b8741e6761b06ae7729e8e5036
