### ISSUE TITLE
About the use of playerbot

### ISSUE THREAD

**Issue by ss958** [vmangos/core#32]
How do I use playerbot? How do I fill out the MYSQL playerbot form?

**Comment by Kittnz** [comment]
Playerbot is pretty much broken and only used for tests.

**Comment by ratkosrb** [comment]
The bots are only used to keep your character in the world for 20 seconds when logging out by default. There is a table called `playerbot` in the `characters` database where you can add characters by guid to be used by bots, but they won't do anything unless you assign them an AI script. I have not looked into them much beyond that.

**Comment by wthslw001** [comment]
> The bots are only used to keep your character in the world for 20 seconds when logging out by default. There is a table called `playerbot` in the `characters` database where you can add characters by guid to be used by bots, but they won't do anything unless you assign them an AI script. I have not looked into them much beyond that.

Is there any AI script description?

**Comment by ratkosrb** [comment]
Check the in the source code how it reads the table, and what it does with the ai column. I have not looked into it myself.
