### ISSUE TITLE
Grethok the Controller can jump off the table，not running down the stairs

### ISSUE THREAD

**Issue by solo0755** [vmangos/core#320]
**Current behavior**: 
Grethok the Controller can jump off the table，Not running down the stairs
**Expected behavior**: 

**Steps to reproduce**:

1. When I stand in the middle of the dungeon, slowly approach creature
2. Appear in its LOS，then  the battle begins，
3. “Grethok the Controller“ Just jump off the stage and chase me，not running down the stairs

**Client version**: 
win7  1.12.1（5875）
**Commit hash**: 
5bc955e1bb06b3ac00b03f36f9140b848dced2dd
**Operating system**:

**Comment by ratkosrb** [comment]
I cannot reproduce the issue. He runs down the stairs as he is supposed to do.
https://streamable.com/vxaqd

**Comment by solo0755** [comment]
> I cannot reproduce the issue. He runs down the stairs as he is supposed to do.
> https://streamable.com/vxaqd

sorry，i changed a new map data ，it's work prefect。
