### ISSUE TITLE
Druid Furor Talent Bug

### ISSUE THREAD

**Issue by aleigood** [vmangos/core#323]
Trigger this talent will put Druid enter combat

![bug5](https://user-images.githubusercontent.com/3367999/70056329-3c00d300-1616-11ea-94ae-7b79170df419.gif)

**Client version**: 
1.12.1
**Commit hash**: 
104f167aaf5e09e40481f386dbb28e1515637b6e
**Operating system**: 
CentOS

**Comment by codestothestars** [comment]
Looking at the [2.2.0 patch notes](https://wow.gamepedia.com/Patch_2.2.0), this behavior appears to be Blizzlike for vanilla.

>  Enrage and Furor should no longer initiate combat, though it will prevent rage decay for the duration.

However, I have noted additional issues with Furor on 1.10.2 and below:
1. Furor gets the druid stuck in combat, at which point the only way to get out is `.combatstop`.
1. The generated rage never degrades, even after leaving combat.

If you have 5/5 Furor, this effectively means that `.combatstop` is required after every battle. Neither of these issues is present on 1.11.2+.

I figured I should mention this here, but am happy to open a separate issue if needed.

EDIT: Opened #740.

**Comment by ulfgebhardt** [comment]
closing this since its blizzlike, followup issue was created thanks @codestothestars
