### ISSUE TITLE
Gruk seems to be a little nervous when he delivers more bread

### ISSUE THREAD

**Issue by aleigood** [vmangos/core#324]
![bug5](https://user-images.githubusercontent.com/3367999/70148912-104b1f00-16e2-11ea-9772-1172ac109b4f.gif)

**Comment by Kittnz** [comment]
just some bad generated movement

**Comment by Gamemechanicwow** [comment]
It works better with the current mmaps. He still differs a little to the left in the entrance due to a hole in the mmap.

I think "bigbaseunit" should be the default option. It solves the problem here and in westbrook garrison.

**Comment by NickTyrer** [comment]
Resolved with new maps
