### ISSUE TITLE
Server crash problem。

### ISSUE THREAD

**Issue by solo0755** [vmangos/core#329]
**Current behavior**: 
lt runing on Ubuntu，After a while,I can't log in;
use command “top”，The ‘’mangosd’ process is shown as follows：
### 13027 ubuntu    20   0 1737204 923176   7672 S   0.3 23.8  80:56.31 mangosd    
**cpu ：0.3%,**  Normal operation is displayed 14%.
**memory:23.8%**
i found a log in server.log:
**2019-12-04 08:15:51 RARunnable thread ended**
How to solve this problem?

**Expected behavior**: 

**Steps to reproduce**:

1. 
2. 
3. 

**Client version**: 
ubuntu 2core ,4G MEM
**Commit hash**: 

**Operating system**:

**Comment by ratkosrb** [comment]
Without a crash stack I can't help.

**Comment by solo0755** [comment]
i ge it,sorry， my fault ；
case by the config item “AutoHonorRestart”，server shutdown，but process not exit。
