### ISSUE TITLE
Tarren Mill Holiday NPC Problem

### ISSUE THREAD

**Issue by aleigood** [vmangos/core#331]
![snipaste_20191223_142720](https://user-images.githubusercontent.com/3367999/71340163-d9ee1a80-2590-11ea-8599-df2819558347.png)

**Commit hash**: 
221145d46edf75dd9f0e2e701651b5acd1fbb8f9

**Comment by Kittnz** [comment]
Seems like an model id issue?

**Comment by aleigood** [comment]
In addition, I don't think human NPC should be used in this place

**Comment by duckbutt55** [comment]
I encountered the same issue at the Orgrimmar Inn, as well.

**Comment by ratkosrb** [comment]
The display ids for this npc need to be assigned on a per spawn basis. I am working on it.
