### ISSUE TITLE
Path finder problem

### ISSUE THREAD

**Issue by aleigood** [vmangos/core#333]
![bug5](https://user-images.githubusercontent.com/3367999/71763271-17e62980-2f15-11ea-95a8-a455471837e6.gif)
![bug6](https://user-images.githubusercontent.com/3367999/71763276-292f3600-2f15-11ea-95e6-b1f071adb7e4.gif)

**Comment by aleigood** [comment]
If I use the map data generated by CMangos' map tools, the guard path will be normal, but new problems will appear:  https://streamable.com/6kiva
But there are no such problems on CMagos.

My guess is that many of the recent NPC path issues (which did not exist before) may be caused by the new mmap code.

**Comment by NickTyrer** [comment]
@ratkosrb Can this be closed now?

**Comment by ratkosrb** [comment]
This one we don't know what settings to use to fix, so it shouldn't be closed.

**Comment by NickTyrer** [comment]
Resolved with new maps
