### ISSUE TITLE
Sunder Armor-like spell stack rules between casters(mobs)

### ISSUE THREAD

**Issue by BBCnewstoday** [vmangos/core#337]
All stackable spells reset when 2-nd caster(mob) applies it.

Example:
2x mobs that have Sunder Armor/Flame Buffet = you'll always be affected by only 1 stack.

They should be stackable like regular Sunder Armor.

**Comment by ratkosrb** [comment]
If you have other examples of spells used by mobs that should stack between casters let me know what they are.
