### ISSUE TITLE
Guard's navigation not available

### ISSUE THREAD

**Issue by aleigood** [vmangos/core#340]
Most of the guard's navigation in Stormwind and Ironforge is not available.

**Client version**: 
1.12.1
**Commit hash**: 
aa833ab62523cb28ed88a3a7831dde06ec4944dd
**Operating system**: 
CentOS

**Comment by ratkosrb** [comment]
Please provide further explanation of what you're talking about.

**Comment by aleigood** [comment]
![snipaste_20200109_115332](https://user-images.githubusercontent.com/3367999/72036731-b805cf00-32d6-11ea-8b21-738f7d3be7cb.png)
There is no indication on the minimap.

**Comment by ratkosrb** [comment]
Cannot reproduce the issue.
https://streamable.com/a47w5

**Comment by aleigood** [comment]
Try Class trainer and Profession trainer.

**Comment by ratkosrb** [comment]
https://streamable.com/nbwhf
Do not make fake reports!

**Comment by aleigood** [comment]
Thank you for helping me find the place to upload the video:
https://streamable.com/l5cth

**Comment by ratkosrb** [comment]
There is something wrong with your own db. I always test on clean db and as you can see there is no issue. All options display properly on the map.
