### ISSUE TITLE
May cause coredump when destroy bag in  bag.

### ISSUE THREAD

**Issue by chendh123** [vmangos/core#35]
hi 
int Player::DestroyItem

            for (int i = 0; i < MAX_BAG_SIZE; ++i)
                DestroyItem(slot, i, update);    // Here may cause coredump.
when bag's containerslots > 18   and  destroy bag in your bag.

**Comment by ratkosrb** [comment]
I can't reproduce it. Can you explain in more detail when it crashes? Record a video if you can.

**Comment by chendh123** [comment]
![core](https://user-images.githubusercontent.com/15760697/48242402-00490900-e416-11e8-92f2-b1e0c2c07449.gif)

**Comment by DarkmoonRabbit** [comment]
![timg](https://user-images.githubusercontent.com/21149808/48260742-8d608200-e457-11e8-8369-a2554faca133.jpg)

**Comment by ratkosrb** [comment]
I think i fixed it. Can you test after this commit to confirm?
https://github.com/vmangos/core/commit/6ce5523b674809521bafea388a42617002f7af94

**Comment by chendh123** [comment]
Ok, thanks.
