### ISSUE TITLE
Pet can not follow player when subway car moves

### ISSUE THREAD

**Issue by Druson** [vmangos/core#358]
**Current behavior**: 
Pet can not follow player when subway car moves. Seems system doesn't treat the subway car as a transport.

**Expected behavior**: 
Pet's position can still follows player when subway car moves.

**Steps to reproduce**:

1.  Login a Hunter or Warlock as GM,  go to subway `.go xyzo -23.06 8.20 -4.30 1.48 369`
2.  Once subway car arrives, get onto the subway car.
3.  After the  subway car moves, check the pet's position.

**Client version**: 
1.12.1

**Commit hash**: 
fe44fc0022055b1159594716ed88897c5fff022d

**Operating system**: 
Win10 X64

**Comment by ulfgebhardt** [comment]
There was some recent commits on cmangos regarding pets teleported on trnasports.

**Comment by ratkosrb** [comment]
I am aware, killerwife implemented movement on elevator type transports. I want to port it at some point.

**Comment by NickTyrer** [comment]
@ratkosrb Can this be closed now?
