### ISSUE TITLE
最新core获取角色列表会加载很久

### ISSUE THREAD

**Issue by wthslw001** [vmangos/core#36]
**Current behavior**: 
最新core编译后获取角色列表会加载很久
**Expected behavior**: 

**Steps to reproduce**:

1. 超过100人登陆，获取角色列表加载超过5分钟
2. 
3. 

**Client version**: 

**Commit hash**: 

**Operating system**: 
![tim 20181114131901](https://user-images.githubusercontent.com/8679316/48461699-e2154b80-e80f-11e8-97a7-1a0c63aea082.png)

**Comment by DarkmoonRabbit** [comment]
王乾亨你好，你看一下你mysql日志
你说中文，他们看不懂

**Comment by ratkosrb** [comment]
There are servers with more than 100 people online using the latest core, and there is no such issue there. Must be something wrong with your database, try changing to another mysql version or converting tables to innodb.

**Comment by wthslw001** [comment]
> 王乾亨你好，你看一下你mysql日志
> 你说中文，他们看不懂

谢谢，目前已查到原因，因为编译的时候我自己的代码造成数据查询插入太频繁，数据库又采取了分布式结构。造成游戏服务端获取角色数据库很慢。已处理。十分感谢您的帮助。

**Comment by wthslw001** [comment]
> There are servers with more than 100 people online using the latest core, and there is no such issue there. Must be something wrong with your database, try changing to another mysql version or converting tables to innodb.

The reason has been found, because my own code caused the data query to be inserted too frequently when compiling, and the database has adopted a distributed structure. It is slow to get the game server to get the role database. Processed. Thank you very much for your help. I am very sorry to use GOOGLE translation.

**Comment by wthslw001** [comment]
已处理完成。
It has been fixed
