### ISSUE TITLE
Warrior T2 suit effect is invalid

### ISSUE THREAD

**Issue by gamelgs** [vmangos/core#362]
Battle Shout  No 30 bonus

**Client version**: 
1.12.1 5875
**Commit hash**: 
201ffbeb734763b803bdcd1245a74c36d4db8e8a
**Operating system**: 
win10

**Comment by ratkosrb** [comment]
Fake report!!! Check things before reporting!

Without set and without buff.
![1](https://user-images.githubusercontent.com/35845488/76790068-cb498500-67c6-11ea-8f33-73aeb05cf80d.jpg)

Without set and with buff.
![2](https://user-images.githubusercontent.com/35845488/76790079-d13f6600-67c6-11ea-86c3-a7db2f7c0add.jpg)

With set and without buff.
![3](https://user-images.githubusercontent.com/35845488/76790092-d8ff0a80-67c6-11ea-92d2-964640e520d4.jpg)

With set and with buff.
![4](https://user-images.githubusercontent.com/35845488/76790111-e1efdc00-67c6-11ea-8b36-7bfa570d5108.jpg)

690 - 400 = 290
974 - 654 = 320

Math is hard...

**Comment by gamelgs** [comment]
![123](https://user-images.githubusercontent.com/54333950/76997233-f29e7e80-698d-11ea-919e-1a8b6b240fd2.jpg)
![456](https://user-images.githubusercontent.com/54333950/76997253-fc27e680-698d-11ea-8846-dbca7f6578d4.jpg)

I'm sorry. I found the difference between the two.

**Comment by gamelgs** [comment]
![123](https://user-images.githubusercontent.com/54333950/76998289-cb48b100-698f-11ea-8800-5e29f68ba970.jpg)
![456](https://user-images.githubusercontent.com/54333950/76998383-f6cb9b80-698f-11ea-99ed-52eecdd9367b.jpg)
When there's no equipment

**Comment by GrenderG** [comment]
If I'm not wrong, buff / debuff tooltip doesn't change, it's a client limitation. What matters is to check your character stats. :)
