### ISSUE TITLE
Instance: Blackwing Lair (WIP)

### ISSUE THREAD

**Issue by Kittnz** [vmangos/core#369]
Implementing missing features of Blackwing Lair

- [ ] Add missing npcs and gobs
- [ ] Add missing spells to mobs
- [ ] Blackwing Taskmaster

**Comment by GrenderG** [comment]
I'm pretty sure we have enough info already to fix all of this.

**Comment by ulfgebhardt** [comment]
@GrenderG Whats the status of BWL now? Any developments on that front?

**Comment by GrenderG** [comment]
> @GrenderG Whats the status of BWL now? Any developments on that front?

I haven't touched BWL.
