### ISSUE TITLE
Priests casting Mind Vision should be able to jump between targets.

### ISSUE THREAD

**Issue by GrenderG** [vmangos/core#376]
**Current behavior**: You can't jump between targets.

**Expected behavior**: 
You should be able to jump between targets as long as they are within range (50000 yd).

- Classic Proof: https://www.youtube.com/watch?v=oHjjrboid_A
- Proof from WoTLK (couldn't find video from original Vanilla but it worked the same way): https://www.youtube.com/watch?v=scPR2IcddO0

**Comment by Kittnz** [comment]
Yeah correct, but gonne be a hard one to fix

**Comment by GrenderG** [comment]
> Yeah correct, but gonne be a hard one to fix

Yup, I tried with no luck.
