### ISSUE TITLE
unable to build on centos 7 

### ISSUE THREAD

**Issue by Ann0n** [vmangos/core#38]
**Current behavior**: 
Building the source on centos 7 using devtoolset-7 fails when building game/Camera.cpp
<img width="1787" alt="screenshot 2018-11-18 at 03 27 33" src="https://user-images.githubusercontent.com/45134774/48667939-525af000-eae2-11e8-9ef0-0282ee3b1590.png">

**Expected behavior**: 
The build completes without errors.

**Steps to reproduce**:

1. clone the repo 
git clone https://github.com/vmangos/core.git
2. make a directory for out of source building
mkdir build
cd build
3. call cmake to make the makefiles
cmake3 ../core
4. call cmake to build the project
cmake3 --build .

**Operating system**: 
centos 7 using devtoolset-7

**Comment by ratkosrb** [comment]
It looks like there is something wrong with your version of tbb. Try using another version, or compiling without tbb by selecting USE_STD_MALLOC in cmake.

**Comment by Ann0n** [comment]
Thanks for taking a look. I was able to get to compile 100% by selecting USE_STD_MALLOC.
Do you recommend compiling using tbb, if so which version are you using?

The packaged version available from the distribution is:
tbb-4.1-9.20130314.el7.x86_64
tbb-devel-4.1-9.20130314.el7.x86_64

**Comment by ratkosrb** [comment]
TBB is used by default, but it should work fine without it. The version i have is tbb2017_20161128oss_win.

**Comment by CansecoDev** [comment]
I'm using this
[libtbb-dev/xenial 4.4~20151115-0ubuntu3](https://packages.ubuntu.com/xenial/amd64/libtbb-dev)

**Comment by Ann0n** [comment]
I was not able to find a packaged version for centos 7 that worked.

I downloaded tbb2019_20181010oss_lin.tgz from the ttb release page and was able to compile against it without issues.

Now that I have both versions compiled and running, I noticed you are correct.
I don't really see any noticeable difference at run time.
