### ISSUE TITLE
Animation effect delay of Arcane Missiles

### ISSUE THREAD

**Issue by gamelgs** [vmangos/core#387]
The animation effect of Arcane Missiles is not synchronized with the casting guidance, and the animation is delayed.

![abc](https://user-images.githubusercontent.com/54333950/75464069-a204b880-59c1-11ea-9165-0bac661193f7.gif)

**Client version**: 
1.12.1 5875
**Commit hash**: 
78faaabe157a983249a688fbadfce62af515f4b3
**Operating system**: 
win 10

**Comment by ratkosrb** [comment]
This should be better after https://github.com/vmangos/core/commit/16ef797e2ceff160f47261d1cda970f14ab3c055.
