### ISSUE TITLE
[Crash/Auras] Deleting aura holder 12494 in use (Creature (Entry: 937 Guid: 2220))

### ISSUE THREAD

**Issue by wthslw001** [vmangos/core#388]
[Crash/Auras] Deleting aura holder 12494 in use (Creature (Entry: 937 Guid: 2220))
Unit::Update()+0xde [0x9bb5e]
Creature::Update()+0x5c6 [0xd27b6]
Map::UpdateVisibilityForRelocations()+0x639 [0xba389]
Map::UpdateCellsAroundObject()+0x212 [0xb92b2]
Map::UpdateActiveCellsSynch()+0x92 [0xb8792]
Map::UpdateCells()+0x98 [0xb8e48]
Map::Update()+0x251 [0xb7391]
GetSpellRangeStore()+0x65e1 [0x1abb91]
BarGoLink::step()+0xcba [0x4b31da]
ACE_OS_Thread_Adapter::invoke()+0xa0 [0x6df10]
o__realloc_base()+0x60 [0x1cd70]
BaseThreadInitThunk()+0x14 [0x8364]
RtlUserThreadStart()+0x21 [0x67091]

**Comment by ratkosrb** [comment]
How often does this happen, and does it crash, or just prints the error?

**Comment by wthslw001** [comment]
> How often does this happen, and does it crash, or just prints the error?

Dear author，Is Repeatedly.
Thank you for your reply.

2020-03-06 09:49:57 Unit::Update()+0xde [0x9bd7e]
Creature::Update()+0x39a [0xd27da]
Map::UpdateVisibilityForRelocations()+0x639 [0xba559]
Map::UpdateCellsAroundObject()+0x212 [0xb9482]
Map::UpdateActiveCellsSynch()+0x92 [0xb8962]
Map::UpdateCells()+0x98 [0xb9018]
Map::Update()+0x251 [0xb7561]
GetSpellRangeStore()+0x5f11 [0x1ac381]
BarGoLink::step()+0xcba [0x4aaf5a]
ACE_OS_Thread_Adapter::invoke()+0xa0 [0x6df10]
o__realloc_base()+0x60 [0x1cd70]
BaseThreadInitThunk()+0x14 [0x8364]
RtlUserThreadStart()+0x21 [0x67091]

2020-03-06 09:50:30 [Crash/Auras] Deleting aura holder 122 in use (Creature (Entry: 3267 Guid: 20387))
2020-03-06 09:50:30 Unit::Update()+0xde [0x9bd7e]
Creature::Update()+0x39a [0xd27da]
Map::UpdateVisibilityForRelocations()+0x639 [0xba559]
Map::UpdateCellsAroundObject()+0x212 [0xb9482]
Map::UpdateActiveCellsSynch()+0x92 [0xb8962]
Map::UpdateCells()+0x98 [0xb9018]
Map::Update()+0x251 [0xb7561]
GetSpellRangeStore()+0x5f11 [0x1ac381]
BarGoLink::step()+0xcba [0x4aaf5a]
ACE_OS_Thread_Adapter::invoke()+0xa0 [0x6df10]
o__realloc_base()+0x60 [0x1cd70]
BaseThreadInitThunk()+0x14 [0x8364]
RtlUserThreadStart()+0x21 [0x67091]

2020-03-06 09:50:30 [Crash/Auras] Deleting aura holder 122 in use (Creature (Entry: 3268 Guid: 20397))
2020-03-06 09:50:30 Unit::Update()+0xde [0x9bd7e]
Creature::Update()+0x39a [0xd27da]
Map::UpdateVisibilityForRelocations()+0x639 [0xba559]
Map::UpdateCellsAroundObject()+0x212 [0xb9482]
Map::UpdateActiveCellsSynch()+0x92 [0xb8962]
Map::UpdateCells()+0x98 [0xb9018]
Map::Update()+0x251 [0xb7561]
GetSpellRangeStore()+0x5f11 [0x1ac381]
BarGoLink::step()+0xcba [0x4aaf5a]
ACE_OS_Thread_Adapter::invoke()+0xa0 [0x6df10]
o__realloc_base()+0x60 [0x1cd70]
BaseThreadInitThunk()+0x14 [0x8364]
RtlUserThreadStart()+0x21 [0x67091]

2020-03-06 09:50:30 [Crash/Auras] Deleting aura holder 122 in use (Creature (Entry: 3267 Guid: 20380))
2020-03-06 09:50:30 Unit::Update()+0xde [0x9bd7e]
Creature::Update()+0x39a [0xd27da]
Map::UpdateVisibilityForRelocations()+0x639 [0xba559]
Map::UpdateCellsAroundObject()+0x212 [0xb9482]
Map::UpdateActiveCellsSynch()+0x92 [0xb8962]
Map::UpdateCells()+0x98 [0xb9018]
Map::Update()+0x251 [0xb7561]
GetSpellRangeStore()+0x5f11 [0x1ac381]
BarGoLink::step()+0xcba [0x4aaf5a]
ACE_OS_Thread_Adapter::invoke()+0xa0 [0x6df10]
o__realloc_base()+0x60 [0x1cd70]
BaseThreadInitThunk()+0x14 [0x8364]
RtlUserThreadStart()+0x21 [0x67091]

2020-03-06 09:50:54 [Crash/Auras] Deleting aura holder 122 in use (Creature (Entry: 3267 Guid: 20388))
2020-03-06 09:50:54 Unit::Update()+0xde [0x9bd7e]
Creature::Update()+0x39a [0xd27da]
Map::UpdateVisibilityForRelocations()+0x639 [0xba559]
Map::UpdateCellsAroundObject()+0x212 [0xb9482]
Map::UpdateActiveCellsSynch()+0x92 [0xb8962]
Map::UpdateCells()+0x98 [0xb9018]
Map::Update()+0x251 [0xb7561]
GetSpellRangeStore()+0x5f11 [0x1ac381]
BarGoLink::step()+0xcba [0x4aaf5a]
ACE_OS_Thread_Adapter::invoke()+0xa0 [0x6df10]
o__realloc_base()+0x60 [0x1cd70]
BaseThreadInitThunk()+0x14 [0x8364]
RtlUserThreadStart()+0x21 [0x67091]

2020-03-06 09:50:54 [Crash/Auras] Deleting aura holder 122 in use (Creature (Entry: 3267 Guid: 20390))
2020-03-06 09:50:54 Unit::Update()+0xde [0x9bd7e]
Creature::Update()+0x39a [0xd27da]
Map::UpdateVisibilityForRelocations()+0x639 [0xba559]
Map::UpdateCellsAroundObject()+0x212 [0xb9482]
Map::UpdateActiveCellsSynch()+0x92 [0xb8962]
Map::UpdateCells()+0x98 [0xb9018]
Map::Update()+0x251 [0xb7561]
GetSpellRangeStore()+0x5f11 [0x1ac381]
BarGoLink::step()+0xcba [0x4aaf5a]
ACE_OS_Thread_Adapter::invoke()+0xa0 [0x6df10]
o__realloc_base()+0x60 [0x1cd70]
BaseThreadInitThunk()+0x14 [0x8364]
RtlUserThreadStart()+0x21 [0x67091]

2020-03-06 09:51:41 [Crash/Auras] Deleting aura holder 122 in use (Creature (Entry: 3268 Guid: 20406))
2020-03-06 09:51:41 Unit::Update()+0xde [0x9bd7e]
Creature::Update()+0x39a [0xd27da]
Map::UpdateVisibilityForRelocations()+0x639 [0xba559]
Map::UpdateCellsAroundObject()+0x212 [0xb9482]
Map::UpdateActiveCellsSynch()+0x92 [0xb8962]
Map::UpdateCells()+0x98 [0xb9018]
Map::Update()+0x251 [0xb7561]
GetSpellRangeStore()+0x5f11 [0x1ac381]
BarGoLink::step()+0xcba [0x4aaf5a]
ACE_OS_Thread_Adapter::invoke()+0xa0 [0x6df10]
o__realloc_base()+0x60 [0x1cd70]
BaseThreadInitThunk()+0x14 [0x8364]
RtlUserThreadStart()+0x21 [0x67091]

2020-03-06 09:51:41 [Crash/Auras] Deleting aura holder 122 in use (Creature (Entry: 3267 Guid: 20391))
2020-03-06 09:51:41 Unit::Update()+0xde [0x9bd7e]
Creature::Update()+0x39a [0xd27da]
Map::UpdateVisibilityForRelocations()+0x639 [0xba559]
Map::UpdateCellsAroundObject()+0x212 [0xb9482]
Map::UpdateActiveCellsSynch()+0x92 [0xb8962]
Map::UpdateCells()+0x98 [0xb9018]
Map::Update()+0x251 [0xb7561]
GetSpellRangeStore()+0x5f11 [0x1ac381]
BarGoLink::step()+0xcba [0x4aaf5a]
ACE_OS_Thread_Adapter::invoke()+0xa0 [0x6df10]
o__realloc_base()+0x60 [0x1cd70]
BaseThreadInitThunk()+0x14 [0x8364]
RtlUserThreadStart()+0x21 [0x67091]

2020-03-06 09:51:41 [Crash/Auras] Deleting aura holder 122 in use (Creature (Entry: 3268 Guid: 20405))
2020-03-06 09:51:41 Unit::Update()+0xde [0x9bd7e]
Creature::Update()+0x39a [0xd27da]
Map::UpdateVisibilityForRelocations()+0x639 [0xba559]
Map::UpdateCellsAroundObject()+0x212 [0xb9482]
Map::UpdateActiveCellsSynch()+0x92 [0xb8962]
Map::UpdateCells()+0x98 [0xb9018]
Map::Update()+0x251 [0xb7561]
GetSpellRangeStore()+0x5f11 [0x1ac381]
BarGoLink::step()+0xcba [0x4aaf5a]
ACE_OS_Thread_Adapter::invoke()+0xa0 [0x6df10]
o__realloc_base()+0x60 [0x1cd70]
BaseThreadInitThunk()+0x14 [0x8364]
RtlUserThreadStart()+0x21 [0x67091]

2020-03-06 09:52:47 [Crash/Auras] Deleting aura holder 122 in use (Creature (Entry: 3268 Guid: 20398))
2020-03-06 09:52:47 Unit::Update()+0xde [0x9bd7e]
Creature::Update()+0x39a [0xd27da]
Map::UpdateVisibilityForRelocations()+0x639 [0xba559]
Map::UpdateCellsAroundObject()+0x212 [0xb9482]
Map::UpdateActiveCellsSynch()+0x92 [0xb8962]
Map::UpdateCells()+0x98 [0xb9018]
Map::Update()+0x251 [0xb7561]
GetSpellRangeStore()+0x5f11 [0x1ac381]
BarGoLink::step()+0xcba [0x4aaf5a]
ACE_OS_Thread_Adapter::invoke()+0xa0 [0x6df10]
o__realloc_base()+0x60 [0x1cd70]
BaseThreadInitThunk()+0x14 [0x8364]
RtlUserThreadStart()+0x21 [0x67091]

2020-03-06 09:52:47 [Crash/Auras] Deleting aura holder 122 in use (Creature (Entry: 3267 Guid: 20381))
2020-03-06 09:52:47 Unit::Update()+0xde [0x9bd7e]
Creature::Update()+0x39a [0xd27da]
Map::UpdateVisibilityForRelocations()+0x639 [0xba559]
Map::UpdateCellsAroundObject()+0x212 [0xb9482]
Map::UpdateActiveCellsSynch()+0x92 [0xb8962]
Map::UpdateCells()+0x98 [0xb9018]
Map::Update()+0x251 [0xb7561]
GetSpellRangeStore()+0x5f11 [0x1ac381]
BarGoLink::step()+0xcba [0x4aaf5a]
ACE_OS_Thread_Adapter::invoke()+0xa0 [0x6df10]
o__realloc_base()+0x60 [0x1cd70]
BaseThreadInitThunk()+0x14 [0x8364]
RtlUserThreadStart()+0x21 [0x67091]

2020-03-06 09:52:47 [Crash/Auras] Deleting aura holder 122 in use (Creature (Entry: 3268 Guid: 20399))
2020-03-06 09:52:47 Unit::Update()+0xde [0x9bd7e]
Creature::Update()+0x39a [0xd27da]
Map::UpdateVisibilityForRelocations()+0x639 [0xba559]
Map::UpdateCellsAroundObject()+0x212 [0xb9482]
Map::UpdateActiveCellsSynch()+0x92 [0xb8962]
Map::UpdateCells()+0x98 [0xb9018]
Map::Update()+0x251 [0xb7561]
GetSpellRangeStore()+0x5f11 [0x1ac381]
BarGoLink::step()+0xcba [0x4aaf5a]
ACE_OS_Thread_Adapter::invoke()+0xa0 [0x6df10]
o__realloc_base()+0x60 [0x1cd70]
BaseThreadInitThunk()+0x14 [0x8364]
RtlUserThreadStart()+0x21 [0x67091]

2020-03-06 09:55:01 [Crash/Auras] Deleting aura holder 122 in use (Creature (Entry: 3267 Guid: 20380))
2020-03-06 09:55:01 Unit::Update()+0xde [0x9bd7e]
Creature::Update()+0x39a [0xd27da]
Map::UpdateVisibilityForRelocations()+0x639 [0xba559]
Map::UpdateCellsAroundObject()+0x212 [0xb9482]
Map::UpdateActiveCellsSynch()+0x92 [0xb8962]
Map::UpdateCells()+0x98 [0xb9018]
Map::Update()+0x251 [0xb7561]
GetSpellRangeStore()+0x5f11 [0x1ac381]
BarGoLink::step()+0xcba [0x4aaf5a]
ACE_OS_Thread_Adapter::invoke()+0xa0 [0x6df10]
o__realloc_base()+0x60 [0x1cd70]
BaseThreadInitThunk()+0x14 [0x8364]
RtlUserThreadStart()+0x21 [0x67091]

2020-03-06 09:55:01 [Crash/Auras] Deleting aura holder 122 in use (Creature (Entry: 3265 Guid: 20305))
2020-03-06 09:55:01 Unit::Update()+0xde [0x9bd7e]
Creature::Update()+0x39a [0xd27da]
Map::UpdateVisibilityForRelocations()+0x639 [0xba559]
Map::UpdateCellsAroundObject()+0x212 [0xb9482]
Map::UpdateActiveCellsSynch()+0x92 [0xb8962]
Map::UpdateCells()+0x98 [0xb9018]
Map::Update()+0x251 [0xb7561]
GetSpellRangeStore()+0x5f11 [0x1ac381]
BarGoLink::step()+0xcba [0x4aaf5a]
ACE_OS_Thread_Adapter::invoke()+0xa0 [0x6df10]
o__realloc_base()+0x60 [0x1cd70]
BaseThreadInitThunk()+0x14 [0x8364]
RtlUserThreadStart()+0x21 [0x67091]

2020-03-06 09:55:01 [Crash/Auras] Deleting aura holder 122 in use (Pet (Petnumber: 14 Guid: 8))
2020-03-06 09:55:01 Unit::Update()+0xde [0x9bd7e]
Creature::Update()+0x39a [0xd27da]
Pet::Update()+0x1aa [0xdaf8a]
Map::UpdateVisibilityForRelocations()+0x639 [0xba559]
Map::UpdateCellsAroundObject()+0x2af [0xb951f]
Map::UpdateActiveCellsSynch()+0x92 [0xb8962]
Map::UpdateCells()+0x98 [0xb9018]
Map::Update()+0x251 [0xb7561]
GetSpellRangeStore()+0x5f11 [0x1ac381]
BarGoLink::step()+0xcba [0x4aaf5a]
ACE_OS_Thread_Adapter::invoke()+0xa0 [0x6df10]
o__realloc_base()+0x60 [0x1cd70]
BaseThreadInitThunk()+0x14 [0x8364]
RtlUserThreadStart()+0x21 [0x67091]

**Comment by ratkosrb** [comment]
@wthslw001 Can you try if this branch fixes the crashing?

https://github.com/ratkosrb/core/tree/aura_removal

Please test it and reply!
```
git clone -b aura_removal https://github.com/ratkosrb/core
```
