### ISSUE TITLE
how to use item scriptname??

### ISSUE THREAD

**Issue by ctmwow** [vmangos/core#39]
i dont know how to add the scriptname now

**Comment by ratkosrb** [comment]
This functionality was never used and is redundant, so it was removed. You should assign a dummy spell to the item and script that instead. All item effects are spells.

Example of a dummy spell you can use:
http://classicdb.ch/?spell=18282

Then you add code for this spell id in Spell::EffectDummy in SpellEffects.cpp.

**Comment by ctmwow** [comment]
oh my god!
This change is too much trouble for my code.

**Comment by ratkosrb** [comment]
There is nothing you could do with the ScriptName that you can't do with a dummy spell.
