### ISSUE TITLE
Random movement issue: Wretched Zombie (id: 1502)

### ISSUE THREAD

**Issue by schell244** [vmangos/core#395]
Random movement animation of npc 1502 is broken.
(old issue, I saw this ages ago)

**Steps to reproduce**:
1.  .tele deathknell
2.  watch random movement of Wretched Zombie
3.  sometimes npc does its walking animation, but the npc is not moving.

![npc-1502-broken-movement](https://user-images.githubusercontent.com/9536270/75675021-94cc2000-5c86-11ea-9f54-34c5d98f8314.gif)

**Client version**: 
1.12.1 5875
**Commit hash**: 
645a642
**Operating system**: 
Win 10

**Comment by Marcelo20XX** [comment]
This issue occurs with any NPC in the game that has a special spawn animation, in this case it occurs because this particular NPC spawns from the ground via a special animation, the fix is simple although is more a hack than a fix, just delete the spawn animation on the creature_database...
