### ISSUE TITLE
Ribbly Screwspigot issues

### ISSUE THREAD

**Issue by GrenderG** [vmangos/core#396]
**Current behavior**: You can only kill him if you have the corresponding quest (4136), gossip dialog will not appear if not.

**Expected behavior**:  Apparently you should be able kill him even if you don't have the quest (as you can see in the video the rogue doesn't seem to have the quest since Ribbly didn't drop the head).

Also, he might be using the wrong gossip text and wrong gossip icon.

Current:
![image](https://user-images.githubusercontent.com/8654362/75731549-3d629a00-5cf0-11ea-941e-84a5d309b071.png)
Classic:
![image](https://user-images.githubusercontent.com/8654362/75731562-46ec0200-5cf0-11ea-941a-6b7394f7f375.png)

Video proof: https://www.youtube.com/watch?v=VjV3EQUmoxg

**Comment by NickTyrer** [comment]
If it's any help, looks like its fixed in cmangos https://github.com/cmangos/classic-db/commit/fd66f5eb7501fe7e0165f4c43b3db732d168ba37.
