### ISSUE TITLE
Mobs in caves or tunnels don't work properly.

### ISSUE THREAD

**Issue by Ann0n** [vmangos/core#40]
**Current behavior**: 
If I enter a cave or tunnel, the mobs seem to be glued to the spot. They do not patrol or move at all

I can initiate a ranged attack. This causes damage, however the mob goes into evade and the attack is reset. If I get into melee distance, the mob will attack me, however it will still not move.

**Expected behavior**: 
Mobs in caves will behave like mobs outside of caves.

**Steps to reproduce**:
I am pretty sure it is a problem with my install, but I am not sure how to localise the problem.
I am not sure what is wrong. I tried recreating my database, however that did not seem to help.

**Comment by CansecoDev** [comment]
This may be related to mmap/vmap

**Comment by Kittnz** [comment]
Can you give an example? Map and coordinates?

**Comment by Ann0n** [comment]
An example would be Dun Morogh, Coldridge Pass, 35.7 , 66.5

I can give more locations but so far all indoors areas seem to be affected.

For example the cave in the dwarf starting area or the cave in the troll starting area.

**Comment by Ann0n** [comment]
Here is a [video](https://drive.google.com/file/d/16zt81tCdxFtvTCy1ROM6Ah_hPyc3d4Sn/view?usp=sharing) I made earlier of the problem.

**Comment by Ann0n** [comment]
Something else I noticed, if I am inside and aggro a mob outside. It will not enter. It will move back and forth like there is an invisible wall.

**Comment by Kittnz** [comment]
a .go x y z map command would be great xD

**Comment by CansecoDev** [comment]
Remember .gps gives you the coords

**Comment by Ann0n** [comment]
Coldridge Pass Tunnel:
.go xyz -6060.238770 40.316036 407.935516 0

Troll Mine:
.go xyz -6504.097168 480.302185 387.745636 0

Squealer's Hideout:
.go xyz -3110.000000 -1202.000000 85.199402 1

**Comment by Ann0n** [comment]
Deleting the mmaps directory unglued them. I am recreating those files again.

**Comment by Ann0n** [comment]
I recreated the mmaps. This however did not fix the problem. (A long wait for no improvement.)

I acquired a lh repack to see if the mmaps were different.
The mmaps were different, and I tried running the server using those mmaps.
This didn't fix the problem either.

In the end I checked out the other data files included in the repack.
The entire maps directory I created with the mapextractor locally are the same as those of the repack. So I am guessing that mapextractor works ok.

The contents of the vmaps directory differ greatly. Unfortunately I can not tell which vmap tool is failing as the repack did not include the Buildings folder.

Running the server with the vmaps and mmaps folders from the repack works fine.

**Comment by ratkosrb** [comment]
I don't seem to be able to reproduce the issue you are describing. Pathfinding works fine for me in all of these caves.

https://streamable.com/z3exy

**Comment by Ann0n** [comment]
Did you use the extractors built from the sources in this repo to create your mmaps and vmaps?

I downloaded a different version of the extractors from a different repo and did not have any issues when using those vmaps and mmaps.

**Comment by Ann0n** [comment]
I'm closing the issue since I guess nobody else has the problem with the extractors that I'm having.
