### ISSUE TITLE
Sound: boat taxi to booty bay

### ISSUE THREAD

**Issue by schell244** [vmangos/core#403]
Wrong sound is played when boat enters stranglethorn vale and approaches booty bay.
Currently this sound is played:
https://classic.wowhead.com/sound=5036/moment-stormwind02

**Steps to reproduce**:
1.  .tele ratchet
2.  take boat to booty bay
3.  after loading screen a stomwind sound is played

**Client version**: 
1.12.1 5875
**Commit hash**: 
26addb5
**Operating system**: 
Win 10

**Comment by NickTyrer** [comment]
Can confirm this happens in Classic as well.

**Comment by schell244** [comment]
Thanks @NickTyrer for checking that. It just appeared wrong to me. Issue is closed then.
