### ISSUE TITLE
Onyxia's Lair got some problems,world server will crash

### ISSUE THREAD

**Issue by amydomi** [vmangos/core#406]
When the player does not carry the Dragon Fire amulet or is not in the team, trying to enter Onyxia's lair will cause the server to restart and cause a certain amount of kickback

**Comment by ratkosrb** [comment]
Cannot reproduce.
https://streamable.com/1llbn

**Comment by coolzoom** [comment]
cannot reproduce, and I knew only one crash case due to the aura applied by onyxia but it had been fixed long time ago by bro.
