### ISSUE TITLE
Aggro/Thread - enemys with pets can be pulled through walls

### ISSUE THREAD

**Issue by schell244** [vmangos/core#407]
Enemys which have pets (especially imp) have incorrect aggro radius, and be pulled through walls.

Example 1, Fenris Island, NPC:  https://classic.wowhead.com/npc=1947/thule-ravenclaw
- when imp pet is summond, npc can be pulled through walls
- when imp pet is killed, aggro area is correct. 

Example 2, Durotar, NPC: https://classic.wowhead.com/npc=3199/burning-blade-cultist
1.  visit spawn point of chest (.go object 12547) with a character below level 10
2. (clear enemys which are visible around you)
3.  walk around the chests spawn area until you enter combat 
4.  wait about 1 minute
5.  a group of enemys from Dustwind Cave arrives and attacks you -> attackers have imp pets

![WoWScrnShot_031120_194728](https://user-images.githubusercontent.com/9536270/76455180-cc993d00-63d5-11ea-89f8-e8a4b7d1ee1b.jpg)

**Client version**: 
1.12.1

**Commit hash**: 
16ef797

**Operating system**: 
Win10

**Comment by GrenderG** [comment]
I can confirm that this is happening. Happens in more places too.

**Comment by schell244** [comment]
Happens pretty often, when player is above/below enemys. Enemys behind walls on the same elevation level don't get pulled (at least this never happend to me).

**Comment by schell244** [comment]
I assume something is wrong in PetEventAI.cpp

My c++ skill is pretty bad, so would be nice if someone can check that:

UpdateAI() calls FindTargetForAttack() and if a target is found, it triggers the pet to start combat withouth checking for LOS.

**Comment by ratkosrb** [comment]
Woah, nice find! That appears to be the problem indeed.
