### ISSUE TITLE
Missing NPC Text

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#408]
**Current behavior**: 
Upon completing the warlock quest "Summon Felsteed" no NPC dialogue is displayed
![Untitled1](https://user-images.githubusercontent.com/22723839/76685163-888e7e00-6609-11ea-94a9-1fa9fd409265.png)

**Expected behavior**: 
Dialogue should be:
```So, you've decided to grace my presence again. How kind of you.
My acolytes wondered if you'd ever show up. I told them there was no doubt. When power is concerned, you are drawn in like a moth to the flame.
```

**Steps to reproduce**:
1. Obtain Alliance quest Summon Felsteed from Demisette Cloyce
2. Turn in quest at Strahad Farsan

**Client version**: 
 1.12.1 5875

**Commit hash**: 

**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/65fceeb3fc3371e85ee4fa9736c3ad3217778dec.
