### ISSUE TITLE
Missing Item in Scholomance: Skin of Shadow

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#409]
**Current behavior**: 
Skin of shadow is not present in room after killing Lady Illucia Barov
![Untitled2](https://user-images.githubusercontent.com/22723839/76685296-7d881d80-660a-11ea-87f0-fa0ce09333fd.png)

**Expected behavior**: 
Skin of shadow should be present
![shadowvault3](https://user-images.githubusercontent.com/22723839/76685330-a4465400-660a-11ea-9833-2a28043b08be.jpg)

**Client version**: 
1.12.1 5875
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
I believe this is part of Blizzard's limited loot progression. This item was spawned on the ground before patch 1.10. After that the static spawn on the ground was removed, and mobs in the dungeon started dropping it instead.

From the comments here:
https://web.archive.org/web/20060430102317/http://wow.allakhazam.com/db/item.html?witem=12753

"As of 1.10 there is no longer a Skin on the ground, drops are the sole place to get em."

**Comment by Daribon** [comment]
That's odd because on classic the Skin of Shadow is always spawned on the ground. Mobs do drop it as well inside the instance.

**Comment by Daribon** [comment]
Now that classic has progressed into phase 5, skin of shadow has stopped spawning on the ground. 

Can therefor confirm that patch 1.10 is when skin of shadow stopped spawning on the ground and that's when skin of shadow was added to loot tables of NPCs in Scholomance.

**Comment by ratkosrb** [comment]
So this issue is invalid then?

**Comment by Daribon** [comment]
If it's already set to despawn at patch 1.10 in vmangos DB, then yes, the issue is invalid.

**Comment by ratkosrb** [comment]
The Skin of Shadow in her room has patch_max=7 set in db.
