### ISSUE TITLE
Database update error

### ISSUE THREAD

**Issue by aleigood** [vmangos/core#412]
After executing src/sql/migrations/merge.sh, there was an error upgrading the database file: src/sql/migrations/world_db_updates.sql

console: 
ERROR 1292 (22007) at line 57128: Incorrect datetime value: '0000-00-00 00:00:00' for column 'start_time' at row 1

fb5c193a840fa8062a27f0e62b2414d70921f1a2

**Comment by ratkosrb** [comment]
What version of MySQL are you using? I am not getting any errors.

**Comment by aleigood** [comment]
I have tried to reset the database three times and perform the update, with the same error, including the latest commit.
The error disappears when the update is executed the second time.

Caused by update:
20200301140338_world.sql
The date format is not compatible, which can be solved by modifying MySQL configuration, or using MySQL universal time format.

OS: CentOS
Mysql: 
mysql-community-client-5.7.21-1.el7.x86_64
mysql-community-common-5.7.21-1.el7.x86_64
mysql-community-server-5.7.21-1.el7.x86_64
mysql-community-devel-5.7.21-1.el7.x86_64
mysql-community-libs-5.7.21-1.el7.x86_64
mysql-community-libs-compat-5.7.21-1.el7.x86_64

**Comment by ratkosrb** [comment]
Try using mysql version 5.5 instead.

**Comment by ghost** [comment]
I had the same problem. Try adding the following variable to sql_mode in my.ini: **NO_ZERO_IN_DATE**, like this: 

> sql_mode=NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

**Comment by ratkosrb** [comment]
The error is because the date is all zeroes? That's weird because the other hardcoded events have the same date.
