### ISSUE TITLE
Warlock talent aftermath applies wrong effect

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#414]
**Current behavior**: 
Warlock talent aftermath applies movement slowed effect
![Untitled](https://user-images.githubusercontent.com/22723839/76900732-d3222b80-6891-11ea-9c41-6510f459492b.png)

**Expected behavior**: 
Should daze the target

**Client version**: 
1.12.1 5875
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by GrenderG** [comment]
Seems like the correct spell to me. Aftermath applies https://classic.wowhead.com/spell=18118/aftermath

**Comment by NickTyrer** [comment]
You are right, thanks for clearing that up.
