### ISSUE TITLE
NPC bugs in shadow hold Felwood

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#415]
**Current behavior**: 
When under the influence of shadowy potion the npc rakaiah is unfriendly and the mobs surrounding her are moving.
https://youtu.be/2JhAx0jIZqM

**Expected behavior**: 
The mob rakaiah should be friendly when under the influence of shadowy potion and the mobs surrounding her should be static.
see 4:44 here: https://www.youtube.com/watch?v=Tx8o9vRNlkg

**Client version**: 
 1.12.1 5875
**Commit hash**: 

**Operating system**: 
Wiin 10

**Comment by ratkosrb** [comment]
![WoWScrnShot_032620_151629](https://user-images.githubusercontent.com/35845488/77651082-f5443980-6f74-11ea-918a-b66bf591cda6.jpg)

She is friendly to me when I drink the potion. I tried on both alliance and horde.
