### ISSUE TITLE
In the Wailing Caverns, Deviate Lurker can swim to the land.

### ISSUE THREAD

**Issue by gamelgs** [vmangos/core#417]
In the Wailing Caverns, Deviate Lurker can swim to the land.

![123](https://user-images.githubusercontent.com/54333950/76993713-40b08380-6988-11ea-92be-2bb18d239831.png)

**Client version**: 
1.12.1 5875
**Commit hash**: 
65fceeb3fc3371e85ee4fa9736c3ad3217778dec
**Operating system**: 
win10

**Comment by NickTyrer** [comment]
Tis is no longer happening with lates map fixes
