### ISSUE TITLE
Missing animation

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#419]
**Current behavior**: 
During the final encounter in DM West for the Warlocks epic mount the animation does not appear around the summoning circle to indicate that the process is complete.
see https://youtu.be/Y3SqAUiSLGA

**Expected behavior**: 
When the process is complete and all the glyphs have appeared around the summoning circle an animation appears showing that it is time to summon the dreadsteed.
see 22:55 https://www.youtube.com/watch?v=Tx8o9vRNlkg&t=390s

**Client version**: 
 1.12.1 5875
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
@NickTyrer Can you give me an exact timestamp of when the animation appears in that video? It's hard to figure out what you are talking about exactly.

**Comment by NickTyrer** [comment]
@ratkosrb sure, just after 0:50 (https://youtu.be/Y3SqAUiSLGA) when the mobs despawn the animation seen at 22:55 (https://www.youtube.com/watch?v=Tx8o9vRNlkg&t=390s) should appear around the edge of the summoning circle.

**Comment by ratkosrb** [comment]
This is possibly a gameobject animation but I don't know which object.

**Comment by NickTyrer** [comment]
@ratkosrb if you point me in the right direction I can take a look for it, I have plenty of time on my hands at the moment.

**Comment by ratkosrb** [comment]
Do you know if the animation displays correctly in other cores like cmangos or trinity? If it works there, then we can look at their implementation.

**Comment by NickTyrer** [comment]
Dont know off hand, will take a look to see if cmangos or trinity has it implemented.

**Comment by NickTyrer** [comment]
Combining with #434
