### ISSUE TITLE
[enhancement] Define SUPPORTED_CLIENT_BUILD as a CMake definition

### ISSUE THREAD

**Issue by CansecoDev** [vmangos/core#42]
**Current behavior**: 

To modify the supported client version, you need to edit [SUPPORTED_CLIENT_BUILD](https://github.com/vmangos/core/blob/acaa54ae9da242657474dee544f1f8382dbd5c39/src/shared/Common.h#L181) directly

**Enhancement suggestion**: 

To modify the supported client version, you need to add a cmake definition, ie:
-DSUPPORTED_CLIENT_BUILD=5086

**Comment by ratkosrb** [comment]
Good idea. Added it here -> https://github.com/vmangos/core/commit/200407326d68ab4bfeeff6a80609fa16fa5cdd86

**Comment by CansecoDev** [comment]
Tested and working, I'll close this issue now.
