### ISSUE TITLE
Serpentbloom - Wailing Caverns quest

### ISSUE THREAD

**Issue by schell244** [vmangos/core#426]
Serpentbloom is pretty hard to loot. It seems like the 'click/select area' is to small or incorrect.

https://classic.wowhead.com/item=5339/serpentbloom
https://classic.wowhead.com/quest=962/serpentbloom

1. accept quest 962
2. travel to wailing caverns
3. (try) loot a spawn of serpentbloom

**Client version**: 
1.12.1
**Commit hash**: 
65fceeb
**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
I think this is client side.

**Comment by schell244** [comment]
Ok, in this case issue can be closed?
