### ISSUE TITLE
Unable to start server，program crash。

### ISSUE THREAD

**Issue by wthslw001** [vmangos/core#43]
**Current behavior**: 
Compile the latest code，Unable to start server，program crash。
**Expected behavior**: 

**Steps to reproduce**:

1. 
2018-11-23 11:23:15 ERROR:SQL: SELECT entry, mask FROM spell_elixir WHERE 5875 BETWEEN build_min AND build_max
2018-11-23 11:23:15 ERROR:[1054] Unknown column 'build_min' in 'where clause'
2018-11-23 11:23:15 ERROR:Your database structure is not up to date. Please make sure you have executed all the queries in the sql/updates folders.
2. 
3. 

**Client version**: 

**Commit hash**: 

**Operating system**: 
![tim 20181123112434](https://user-images.githubusercontent.com/8679316/48927920-2a6df100-ef15-11e8-9f9f-3b024cf9b419.png)

**Comment by DarkmoonRabbit** [comment]
full update SQL files.

**Comment by ratkosrb** [comment]
Your world database it outdated. Drop database `mangos`, create it again, run world_full_26_august_2018.sql and then run all migrations after.

**Comment by wthslw001** [comment]
> Your world database it outdated. Drop database `mangos`, create it again, run world_full_26_august_2018.sql and then run all migrations after.

I'm using the latest database and it is not outdated.
I compiled the last update code and the program can run.
![tim 20181123152123](https://user-images.githubusercontent.com/8679316/48931861-93fcf800-ef33-11e8-9d90-9e272d27cc7f.png)
The database is up to date.
![image](https://user-images.githubusercontent.com/8679316/48931894-bee74c00-ef33-11e8-8be6-83a61f51ffa3.png)
This version of the program can run.
![image](https://user-images.githubusercontent.com/8679316/48931950-fb1aac80-ef33-11e8-94d7-4a5d25236c79.png)
This version of the program can’t run.

**Comment by wthslw001** [comment]
Thank you very much for your reply in your busy schedule.

**Comment by ratkosrb** [comment]
You can see there is no issue with clean db.
Video - https://streamable.com/h4b2r

**Comment by wthslw001** [comment]
> You can see there is no issue with clean db.
> Video - https://streamable.com/h4b2r

Thank you very much for your answer, thank you very much for your contribution！
