### ISSUE TITLE
Preist trainers few remaining issues

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#432]
**Current behavior**:

1. Missing trainable spells, the following NPC's are amissing shackle undead (rank 3)

- Dark Cleric Beryl
should teach 149 spells https://classic.wowhead.com/npc=2129/dark-cleric-beryl

- Malakai Cross
should teach 159 spells https://classic.wowhead.com/npc=3045/malakai-cross

- Father Cobb
should teach 159 spells https://classic.wowhead.com/npc=3046/father-cobb

- Miles Welsh
should teach 159 https://classic.wowhead.com/npc=3044/miles-welsh

- Ur'kyo
should teach 159 https://classic.wowhead.com/npc=6018/urkyo

- X'yera
should teach 159 https://classic.wowhead.com/npc=6014/xyera

- Tai'jin
should teach 159 https://classic.wowhead.com/npc=3706/taijin

2. Aelthalyste and Father Lankester missing dialogue:

- When interacting with these NPC's they go straight to the training catalogue (https://youtu.be/IV3CwOzAJRg) they should display the dialogue like the other trainers (see 2:17 here https://www.youtube.com/watch?v=So4qzy16j5g)

3. Missing quests from the following NPC's
- Miles Welsh missing devouring plague (id 5644) and touch of weakness (id 5663)

- Ur'kyo missing devouring plague (id 5646) and touch of weakness (id 5662)

- Tai-jin missing touch of weakness quest (id 5660)

**Client version**: 
 1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
Number 3 is already fixed.

**Comment by NickTyrer** [comment]
@ratkosrb cheers for cleaning the quests up.
