### ISSUE TITLE
NPC movement issue

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#433]
**Current behavior**: 
- **Update**: The bug only occurs once the mob has been pulled or has been respawned (see: https://youtu.be/qoa_Yusqsdc) also the NPC's Bleeding Horror at Balnir farmstead are working correctly 

- In Western Plaguelands Blighted Zombie and Rotting Cadaver walk on the spot (see https://youtu.be/p9KDpAsR5z4) sometimes it takes a while for the bug to appear.

**Client version**: 
 1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by NickTyrer** [comment]
****

**Comment by mikemenasi** [comment]
This is the same issue as #397
