### ISSUE TITLE
Warlock quests a few bugs

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#434]
**Current behavior**: 

1. ~~The quest 'An Imps Request' is incorrectly started by Richard Kerwin, Luther Pickman, Ursula Deline (5495), Sandahl (5496), Thistleheart (5171)  Alexander Calder (5173), Grol'dar and Mirket (see https://classic.wowhead.com/quest=8419/an-imps-request).~~

2. ~~The quest 'Mor'zul Bloodbringer' is incorrectly started by Greshka and should be started by Martha Strain (see https://classic.wowhead.com/quest=7562/morzul-bloodbringer).~~

3. ~~Briarthorn (5172) should start the quests An Imp's Request and In Search of Menara Voidrender (4736)~~

4. ~~Zevrost is offering the alliance version of the quest 'In Search of Menara Voidrender' (4736). He should offer quest id 4737~~

5. ~~Demon trainers Martha Strain and Kurgul are missing the grimoires 'Devour Magic Rank 3'~~

6. ~~Spackle Thornberry (5520) is missing 1 grimoire~~

7. ~~During the final encounter in DM West for the Warlocks epic mount the animation does not appear around the summoning circle to indicate that the process is complete.
(see https://youtu.be/Y3SqAUiSLGA). When the process is complete and all the glyphs have appeared around the summoning circle an animation appears showing that it is time to summon the dreadsteed. (see 22:55 https://www.youtube.com/watch?v=Tx8o9vRNlkg&t=390s)~~

8. ~~Cylina Darkheart (6374) should not sell  Grimoire of Lash of Pain (Rank 6)~~

9. ~~Wren Darkspring (6376) should not sell Grimoire of Soothing Kiss (Rank 2)~~

10. ~~Dane Winslow (6373) should not sell Grimoire of Lash of Pain (Rank 5)~~

11. ~~Warlock trainer Richard Kerwin is missing multiple trainable spells(he should teach them all).~~

12. ~~Warlock trainer Kartosh (988) is missing Hellfire Rank 1.~~

13. Gorzeeki Wildeyes should not sell the items Xorothian Glyphs, lodestone and J'eevee's Jar untill Imp Delivery is completed and you are on the dreadsteed of xoroth quest . Also he should only sell to warlocks. see https://classicdb.ch/?npc=14437#comments

14. ~~When the quest Gakin's Summons is accepted from Lago Blackwrench (6120) the wrong completion text is offered. The correct text can be seen in the link https://classic.wowhead.com/quest=1717/gakins-summons~~

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by NickTyrer** [comment]
@ratkosrb the missing animation mentioned in point 7 is implemented in cmangos tbc (I used this repack for ease of use http://www.ac-web.org/forums/showthread.php?230880-cMangos-TBC-2-4-3-x64-build). The encounter is bugged so you have to turn gm mode on and use the xorothian glyphs to see the effect.

**Comment by ratkosrb** [comment]
Number 7 is fixed now - https://github.com/vmangos/core/commit/4fd6091a3a58d22142e8b8437c556e3321d5a4c6

**Comment by NickTyrer** [comment]
Pull request #452 Fixes 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12 and 14.
