### ISSUE TITLE
Heal over Time spell Bug

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#438]
**Current behavior**: 
1. Rejuvination, Regrowth and Renew spells dont display healed ammount on character potrait or in combat log

2. Sometimes if you cast Renew or Rejuvination on a friendly NPC (not tested on a player) you cant cast any other spells.

see: https://youtu.be/q8tQS6wkSys

**Client version**: 
1.21.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
The first issue is not a bug. Healing auras only appear in combat log when they actually heal something. You were at full health, so there was nothing to heal.

Second issue has been fixed: https://github.com/vmangos/core/commit/c4aa59e4c317dbee082db2f1aa05331a67065ca3
