### ISSUE TITLE
Wastewander Bandit stuck

### ISSUE THREAD

**Issue by tonymmm1** [vmangos/core#439]
![image](https://user-images.githubusercontent.com/20303853/77880665-c652ef80-7222-11ea-8ad4-70a046da0ea4.png)
**Current behavior**: 
Stuck using latest map gen and extractors.

**Client version**: 
1.12.1
**Commit hash**: 
927b0764e23580fda31e983b7157fa1084ab1be8
**Operating system**: 
Linux 64bit

**Comment by Gamemechanicwow** [comment]
Entry 5618 - GUID 23555

**Comment by Gamemechanicwow** [comment]
The issue is that the mmap generator thinks the area below the tent is under terrain - and skips the area for vmap and mmap generation.

Temporary solution is to generate the maptile in quick mode, which disables filtering underground terrain.

`MoveMapGen.exe 1 --tile 40,45 --quick`

**Comment by NickTyrer** [comment]
@ratkosrb Can this be closed now?
