### ISSUE TITLE
Disenchant item

### ISSUE THREAD

**Issue by kuramajssken001** [vmangos/core#44]
**Current behavior**: 
disenchant item
**Expected behavior**: 

**Steps to reproduce**:

1. learn disenchant.
2. disenchant item
Items cannot be picked up, items are automatically acquired into the bag.

Console error log information.
None (Guid: 0) is unsupported for looking. (Player Jack (Guid: 2)

**Client version**: 
1.12.1
**Commit hash**: 
high
**Operating system**: 
win 10

**Comment by kuramajssken001** [comment]
And all areas of magma will not cause damage to the player.

**Comment by CansecoDev** [comment]
> 
> 
> And all areas of magma will not cause damage to the player.

That may be related to #45
