### ISSUE TITLE
Mobs in Lost Rigger Cove, Tanaris are buggy

### ISSUE THREAD

**Issue by tonymmm1** [vmangos/core#440]
**Current behavior**: 
Long out of combat timers as well as line of sight issues when using Blizzard on frost mage.
**Expected behavior**: 
Mobs should reset after a certain timer and or distance and should be attack-able with blizzard
**Steps to reproduce**:
Pulling a pack of mobs then frost nova, blink, and then blizzard sometimes fails with line of sight issue. When running away mobs stagger on docker with some of the mobs walking underwater.

**Client version**: 
1.12.1
**Commit hash**: 
https://github.com/vmangos/core/commit/927b0764e23580fda31e983b7157fa1084ab1be8
**Operating system**: 
Linux 64bit

**Comment by tonymmm1** [comment]
![image](https://user-images.githubusercontent.com/20303853/77990254-7b021500-72e6-11ea-8923-fea241e7cf26.png)

**Comment by tonymmm1** [comment]
Sorry for not being able to show blizzard line of sight issue but its mostly occurs on the dock every couple of pulls.

**Comment by tonymmm1** [comment]
![image](https://user-images.githubusercontent.com/20303853/77990426-e815aa80-72e6-11ea-909b-7f69cd69d4b8.png)
Another example of weird staggering after leaving their proximity.

**Comment by tonymmm1** [comment]
![screenshot_20-04-01_16:57:27-01](https://user-images.githubusercontent.com/20303853/78190690-1f48a080-743a-11ea-87a1-05476c5dfa70.png)

**Comment by NickTyrer** [comment]
Closed in #1467
