### ISSUE TITLE
Rogue quests a few bugs

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#442]
**Current behavior**: 
1. When interacting with trainer Rwag (3155) it goes straight to the training catalogue

2. You can learn certain poisons (Mind-numbing, blinding powder and wound) from a trainer without having any skill in poisons, they should only unlock when you have the poison skill.

3. During the quest Plundering the Plunderers the chests on the ships should be trapped with Frost Nova and Rat-curse surrently there are no traps on them (see https://classic.wowhead.com/quest=2381/plundering-the-plunderers).

4. Smudge Thunderwood (6779) should not sell "Recipe: Thistle Tea" untill the quest Klaven's Tower/Mission: Possible But Not Probable is completed (see https://classic.wowhead.com/npc=6779/smudge-thunderwood#comments). urrently he sells it regrdless. He should only sell to rogues as well.

5. During the quest Mission: Possible But Not Probable (2478) The NPC Grand Foreman Puzik Gallywix (7288) should not drop Cache of Zanzil's Altered Mixture this should be lootable by lockpicking the chest. Also the chest should have a trap that applies an effect Touch of Zanzil. Currently he drops this item and the chest is not lock pickable or boobytrapped. see: 4:00 https://www.youtube.com/watch?v=J5FR8Oq5wSw. Also completing this quest applies Touch of Zanzil which is incorrect.

**Client version**: 
1.12.12
**Commit hash**: 

**Operating system**: 
Win10

**Comment by NickTyrer** [comment]
1. gest
![gest](https://user-images.githubusercontent.com/22723839/80860616-cfd7d900-8c60-11ea-87c6-ae3ce40ca7fd.png)

2. kaplak
![kaplak](https://user-images.githubusercontent.com/22723839/80860627-debe8b80-8c60-11ea-88dd-e2f7ef4e251f.png)

3. ormok
![ormok](https://user-images.githubusercontent.com/22723839/80860631-e5e59980-8c60-11ea-9336-a1d7e190c170.png)

4. rawg
![rawg](https://user-images.githubusercontent.com/22723839/80860640-ee3dd480-8c60-11ea-8543-5d0f4f1bc49b.png)

5. shenthul
![shenthul](https://user-images.githubusercontent.com/22723839/80860648-f72ea600-8c60-11ea-91f9-dc20407a7771.png)

**Comment by ratkosrb** [comment]
Number 7 is fixed here https://github.com/vmangos/core/commit/56ee93f39b9cb134f9e072399f846b28ad87508e

You need to blow on the whistle twice before he becomes friendly according to the quest text.
https://classic.wowhead.com/quest=2458/deep-cover
```
Next time you need to speak with me, blow into this whistle twice and I'll know you are an ally. 
```

**Comment by NickTyrer** [comment]
Combined with #481
