### ISSUE TITLE
Hunter quest a few bugs

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#443]
**Current behavior**: 

**HORDE**
1. ~~Jen'shan (3154) incorrectly starts The Hunter's Path (6069)~~

2. ~~Kali Remik (11814) and Sian'dur (3407) should start The Hunter's Path (6069) but does not.~~

3. During the quest The Hunter's Path the icon for a tamed beast is in the incorrect location see:
![Untitled](https://user-images.githubusercontent.com/22723839/78238141-245a2e00-74d4-11ea-9b68-918d1f4715e5.png)

4. ~~Xor'juul (3406) and Kary Thunderhorn (3038) incorrectly starts The Hunter's Charm (8151)~~

5. ~~Lanka Farshot (3061) should be holding a gun see 5:49: https://www.youtube.com/watch?v=crJwq0xK88E~~

6. ~~Holt Thunderhorn (3039) should start The Hunter's Charm (8151)~~

**ALLIANCE**
1. ~~Einris Brightspear (5515) should start The Hunter's Path (6073) not Dorion (4205)~~

2. ~~Grif Wildheart (1231) should start The Hunter's Path (6722)~~

3. ~~The Hunter's Path (6072) and The Hunter's Path (6722) are missing completion text.~~

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win10

**Comment by brotalnia** [comment]
The client draws the debuff icons, not the server. Number 3 is not a valid issue.
