### ISSUE TITLE
Tendris Warpwood bug

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#445]
**Current behavior**: 

During the encounter with Tendris Warpwood in Dire Maul West his ability Entangle does not immobilise see https://youtu.be/A0mp_OLx1Ek

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by huyi51462** [comment]
It seems that all the enemy'simmobilise  spell are not working properly

**Comment by huyi51462** [comment]
The flesh Hunter in the raq can't correctly cast the Consume.(spellid:25371).
Client version:
1.12.1(5875)
Commit hash:

Operating system:
Win 10

**Comment by ratkosrb** [comment]
I think this happens because of the teleport component of the spell.

**Comment by huyi51462** [comment]
I think this bug seriously affects the game experience. I will do more tests on this issue because I have encountered several similar problems.
I'm a rookie, I don't know C ++, and I don't quite understand how the database works. I just learned by solving this problem.

**Comment by ratkosrb** [comment]
@huyi514262 If you are having an issue with ALL root spells, not just those with teleport, then there is something wrong with your client most likely. I have seen people that don't send any ACK packets to movement changes, but I don't know why and how that happens. Try to re-download the game from somewhere else and running without any addons if you have this problem.

**Comment by huyi51462** [comment]
@ratkosrb Ok i will test and report the result
