### ISSUE TITLE
Teleport command bug

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#446]
**Current behavior**: 

Using the gm command` tele <name> scholomance` teleports you inside the instance

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
What is the bug? That's what teleport command does, it teleports you.

**Comment by NickTyrer** [comment]
It should teleport you just outside the instance

**Comment by ratkosrb** [comment]
Why?

**Comment by NickTyrer** [comment]
Thats just how it works if you teleport to other instances, its always takes you outside the instance. Will close if this is intended.

**Comment by ghost** [comment]
.tele mc teleports you into the dungeon as well.
You can modify your tele points in the database if you like to.

**Comment by NickTyrer** [comment]
@Nolin7777 for Raid instances the tele command should take you inside the instance, however the tele command when used for a dungeon should take you outside. Just tested on cmangos, tele scholo teleports you outside the instance, looks like this behavior was introduced in vmangos by accident.

**Comment by ratkosrb** [comment]
What do you mean "should", based on what? Where is it written down that it should work this way. It's a custom command for GMs, not something based on official servers, so there is no "should".

**Comment by NickTyrer** [comment]
I was basing it on the other tele commands and that this command was an exception. If this was intentional then  fine the issue is closed, I was just pointing out a potential bug.

**Comment by ratkosrb** [comment]
And it doesn't even work the way you claim it does. I just tested and ".tele scholomance" teleports you outside the instance. For some places it's outside, for others it's inside. It doesn't really matter.

https://streamable.com/z5tku3
