### ISSUE TITLE
GM accounts ignore liquid interactions

### ISSUE THREAD

**Issue by CansecoDev** [vmangos/core#45]
I have noticed that when you login with a GM account (gmlevel 3), any interaction with liquids are neglected.

**Current behavior**: 

Any character from a GM account will ignore any kind of liquid interaction, no damage for touching lava neither the need of air while swimming underwater.

**Expected behavior**: 

GM characters should be able to interact with liquids (lava damage and air), I think this behavior should be neglected while on GM mode or GOD mode enabled

**Steps to reproduce**:

1. Login with a GM account, be sure GM mode and GOD mode are disabled.
2. Get into lava, swims without damage.
3. Get into water, swims underwater without time limitation.

**Client version**: 

1.12.1

**Commit hash**: 

006ae16548baa8c7733ed4b46a0554d47386dd0a

**Comment by CansecoDev** [comment]
I cannot reproduce...

Let me explain; I had this issue some time ago and had it documented, then I forgot about it and didn't posted it here, then I remembered it from a comment in #44 so I decided to reproduce it with the latest build, and I cannot reproduce it, everything works as expected.

Some further research may be needed in the future if this issue comes again, since it may not be fixed and could pop again in certain (unknown) circumstances.

**Comment by lwbbdyx** [comment]
I can reproduce.
Steps to reproduce:
1.type .gm fly on
2.jump
3.jump into water
Fix:
type .gm fly off

**Comment by felixq** [comment]
I don't know if it has to do with this, but when using an account with gm, the breathing bar does not appear and you can be underwater as long as you want without drowning.
