### ISSUE TITLE
Warlock - Soulstone Resurrection - spell visuals

### ISSUE THREAD

**Issue by schell244** [vmangos/core#453]
When casting soulstone-resurrection on a friendly player, the spell 'visual animation' will always be shown on caster instead on target. 
(target player gets buff, buff works - just visuals)

https://classic.wowhead.com/spell=20707/soulstone-resurrection#used-by-item
https://classic.wowhead.com/item=5232/minor-soulstone

**Steps to reproduce**:

1. .add 5232
2. select friendly player 
3. use item

**Client version**: 
1.12.1
**Commit hash**: 
680de26
**Operating system**: 
Win 10

**Comment by Daribon** [comment]
This is the correct behavior.
In classic when applying soulstone, the effect is always shown on the warlock himself after spell completed.

Not a bug.

**Comment by schell244** [comment]
Thank you, issue is closed in this case
