### ISSUE TITLE
Untrainable recipies show green in Log

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#456]
**Current behavior**: 

If you click on recipies in vendors list they turn green see https://youtu.be/NYJNYer1-y0

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
I don't think this is a server issue.

**Comment by NickTyrer** [comment]
I will try another client and report back.

**Comment by ratkosrb** [comment]
Unlikely that another client would produce different result. I meant this is probably a blizzlike bug in the client.
