### ISSUE TITLE
MovementAnticheat - kicks player after drowning

### ISSUE THREAD

**Issue by schell244** [vmangos/core#459]
[MovementAnticheat] Player Test:2 [TEST:2@127.0.0.1], Cheat: OverspeedDist(Tick:31), Penalty: Kicked.

**Steps to reproduce**:
1. create character on account with security level 0
2. dive in water -> wait until dead by drowning
3. release spirit, walk a few steps -> disconnect

**Client version**: 
1.12.1
**Commit hash**: 
680de26
**Operating system**: 
Win10

**Comment by ratkosrb** [comment]
I am unable to reproduce the problem.

**Comment by schell244** [comment]
Maybe you have to swim (upwards?) within the last seconds before you die. I will do some more tests on this.

**Comment by schell244** [comment]
I am unable to reproduce the problem as well, I might had a deprecated mangosd.conf file or something.
