### ISSUE TITLE
Chain heal not working

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#461]
**Current behavior**: 
Chain heal does not jump to other targets
https://youtu.be/zo3Cz7sZOvY

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
It doesn't jump to the other player because he is at full health. It picks only injured targets. The spell is working correctly.

https://streamable.com/5319ij

**Comment by mikemenasi** [comment]
@ratkosrb https://github.com/cmangos/mangos-classic/commit/3f0b0986f171387311b0644235654487c86f46df

https://github.com/cmangos/mangos-classic/commit/725706d9989bef7aed86340452c345834c5bb50f

**Comment by ratkosrb** [comment]
If you have videos of it jumping to full health targets from Classic let me know.
