### ISSUE TITLE
NPC loot tables incorrect 

### ISSUE THREAD

**Issue by mikemenasi** [vmangos/core#462]
**Current behavior**: 
-NPC 2184 (Lady Moongazer) loot table is incorrect, see:
Sources: https://classic.wowhead.com/npc=2184/lady-moongazer
https://web.archive.org/web/20060114031736/http://wow.allakhazam.com/db/mob.html?wmob=2184

-NPC 14222 (Araga) loot table is incorrect, see:
Sources: https://web.archive.org/web/20070213211651/http://wow.allakhazam.com/db/mob.html?wmob=14222
https://classic.wowhead.com/npc=14222/araga

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by mikemenasi** [comment]
correct loot tables are here:

https://github.com/cmangos/classic-db/commit/9a6b54ff47c86105a51c88506cdd19454dfef8aa


https://github.com/cmangos/classic-db/commit/4bb4aa001ee4234617bcf7588e7c9b433f8945e6

**Comment by ulfgebhardt** [comment]
@NickTyrer Could you take a look at this? You did a awesome job on `Denalan's Earth`
