### ISSUE TITLE
Program timing crash

### ISSUE THREAD

**Issue by wthslw001** [vmangos/core#47]
**Current behavior**: 

**Expected behavior**: 

**Steps to reproduce**:

1. Thank you very much for your help. Why is the game server always crashing between 12 hours and 22 hours?
2. I have been looking for logs, but I don't know which one is causing the program crash log.I hope I can get your help.
3. 

**Client version**: 

**Commit hash**: 

**Operating system**: 
![tim 20181127104827](https://user-images.githubusercontent.com/8679316/49055335-31a53f80-f232-11e8-8cf8-000c0bbcd9d2.png)

**Comment by ratkosrb** [comment]
Have you disabled GridUnload? It should be 0 otherwise the server crashes after a while.

**Comment by wthslw001** [comment]
> Have you disabled GridUnload? It should be 0 otherwise the server crashes after a while.

No，this GridUnload has been disabled.
GridUnload  = 0
![tim 20181127163227](https://user-images.githubusercontent.com/8679316/49068598-194d1900-f262-11e8-8b27-9182318d9cf7.png)

**Comment by ratkosrb** [comment]
You can try to compile in Debug mode and then choose to Debug in Visual Studio once it crashes. This way it will show you exactly where it crashed.

**Comment by wthslw001** [comment]
> You can try to compile in Debug mode and then choose to Debug in Visual Studio once it crashes. This way it will show you exactly where it crashed.

Ok, I will test it as you teach.

**Comment by ratkosrb** [comment]
@wthslw001 Can you test if the crash still happens with this branch and let me know if it fixes it.

https://github.com/ratkosrb/core/tree/corpseremoval

```
git clone -b corpseremoval https://github.com/ratkosrb/core
```

**Comment by wthslw001** [comment]
> @wthslw001 Can you test if the crash still happens with this branch and let me know if it fixes it.
> 
> https://github.com/ratkosrb/core/tree/corpseremoval
> 
> ```
> git clone -b corpseremoval https://github.com/ratkosrb/core
> ```

OK, I will test it right away. I’ve been busy forgetting to check my message recently.

**Comment by ratkosrb** [comment]
Actually we found 2 crashes on that branch, but I haven't updated it. Try the development branch again.

**Comment by wthslw001** [comment]
> branch

OK，The program crashed to 9 hours and 45 minutes today. I will try the development version again.

**Comment by wthslw001** [comment]
![image](https://user-images.githubusercontent.com/8679316/49558777-41660780-f947-11e8-950b-44b9d83b3f57.png)

Crash Now！！

**Comment by wthslw001** [comment]
But I don't know why this happened.

**Comment by wthslw001** [comment]
> Actually we found 2 crashes on that branch, but I haven't updated it. Try the development branch again.

The program crash still exists in the latest code.

**Comment by wthslw001** [comment]
> Actually we found 2 crashes on that branch, but I haven't updated it. Try the development branch again.

Now the program compiled with whatever version number is still crashing...

**Comment by Kittnz** [comment]
Crash dump?

**Comment by wthslw001** [comment]
> Crash dump?

What would you say is what does this mean?

Program is currently still crashes

**Comment by ratkosrb** [comment]
You must have configured it wrong, because the core currently has almost 7 days uptime on symmetry wow, and can also last several days on ccwow after latest crash fixes.

**Comment by wthslw001** [comment]
> You must have configured it wrong, because the core currently has almost 7 days uptime on symmetry wow, and can also last several days on ccwow after latest crash fixes.
Respectable and selfless ratkosrb:


Hello, I am a pure public service operator of World of Warcraft, https://wow.ymisc.com/ even a private service that does not have sponsorship services.
At present, whether you add your own anti-cheat system or use your original work, it will collapse in about 1 day.
Thank you for the code provided with alexkulya.
