### ISSUE TITLE
Quest: Triage - Horde

### ISSUE THREAD

**Issue by schell244** [vmangos/core#470]
https://classic.wowhead.com/quest=6622/triage

Badly injured soldier -> troll spawns have broken visuals

<img width="461" alt="bug" src="https://user-images.githubusercontent.com/9536270/79685254-a5852500-8237-11ea-80f2-96f7c33d7537.PNG">

**Client version**: 
1.12.1
**Commit hash**: 
11bada3
**Operating system**: 
Win 10

**Comment by Gamemechanicwow** [comment]
Looks fine to me. I did the quest without any broken visuals.

**Comment by schell244** [comment]
I've retested the quest and this time trolls did spawn without any clothing. @Gamemechanicwow can you confirm this? Maybe my client has some issues

<img width="409" alt="troll" src="https://user-images.githubusercontent.com/9536270/104022533-b2301b80-51c0-11eb-810b-06c931960150.PNG">

**Comment by ulfgebhardt** [comment]
Is no clothing wrong here @schell244 ?

**Comment by schell244** [comment]
I just found a video where the 'broken visual' bug also occurs. I don't think that this was on retail classic though
https://www.youtube.com/watch?v=a_lz-cXh5fM

**Comment by Daribon** [comment]
> I just found a video where the 'broken visual' bug also occurs. I don't think that this was on retail classic though https://www.youtube.com/watch?v=a_lz-cXh5fM

video from private server.

----------------

Can't reproduce the bug, Badly injured soldier only has one displayid in creature_template so this was most likely fixed ages ago.
This issue can be closed.

However there are two issue with the Triage that should most likely be put on their own issues. The script is not blizzlike. Its supposed spawn NPCs a lot faster, like 4 times the current vmangos speed. Gossip text is also incorrect, it shows that you have learned everything, even if you got only one skill in first aid.

**Comment by NickTyrer** [comment]
Gossips fixed here #1467

**Comment by schell244** [comment]
Thanks for the update. Missing creature_template could have been the reason 👍 
Closing this.
