### ISSUE TITLE
Banner bug (ironforge)

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#479]
**Current behavior**: 
The banner above both of the entrance to the Forlorn Cavern should only be visible during an event  
![Untitled](https://user-images.githubusercontent.com/22723839/80286640-7b929d80-8724-11ea-8d8e-4c7976457ab5.png)

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by brotalnia** [comment]
Add the guid to `game_event_gameobject` table.

**Comment by NickTyrer** [comment]
All the guid'ss are present in the table with the correct event id's. Could it be a client caching issue? I have tried starting and stopping the relevant events.

**Comment by NickTyrer** [comment]
missing guid is 4771 and 5051 any idia what event it is from?

**Comment by NickTyrer** [comment]
Looks like its event id 1 Midsummer Fire Festival. Looks like the same objects are in the entrance to ironforge. Will create pull request if this evidence is ok?
![Untitled](https://user-images.githubusercontent.com/22723839/80311994-be16b180-87da-11ea-9499-32c29c417490.png)
