### ISSUE TITLE
Incorrect gameobject location

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#482]
**Current behavior**: 
The boxes used for the quest deeprun rat roundup are floating.
![Untitled](https://user-images.githubusercontent.com/22723839/80350340-78082f00-8868-11ea-9161-e0c5832e304f.png)

**Client version**: 
1.12.1

**Comment by alexkulya** [comment]
<pre>
UPDATE `gameobject` SET `position_z` = -4.3 WHERE `guid` IN (20738, 20739, 20740);
</pre>

**Comment by NickTyrer** [comment]
Cheers, will open a PR and close.
