### ISSUE TITLE
NPC bug Millie Featherwhistle

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#484]
**Current behavior**: 
Millie Featherwhistle will opent trade dialogue
![1 5](https://user-images.githubusercontent.com/22723839/80402396-c4c62700-88b5-11ea-9678-d97c4ebdfc88.png)

**Expected behavior**: 
She should not interact untill exhalted
![1](https://user-images.githubusercontent.com/22723839/80402377-bd9f1900-88b5-11ea-9826-dda7f7a3913e.png)

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by brotalnia** [comment]
I don't see trade dialog in the screenshot?

**Comment by brotalnia** [comment]
If you are talking about the quests, those are quests added in 1.4 to exchange your original unarmored mounts for the new version. Since those mounts were never available on Classic, the quests have been removed there.

**Comment by NickTyrer** [comment]
Ah, ok that explains it. Will close
