### ISSUE TITLE
NPC bug wool vendors

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#488]
**Current behavior**: 
The wool vendors seem to all be missing quests.
example:
![5](https://user-images.githubusercontent.com/22723839/80403467-892c5c80-88b7-11ea-9c57-2127d754ffc9.png)

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
It seems the quests are chained in vmangos, each one requires the previous. Silk requires Wool, Maegeweave requires Silk, etc.

**Comment by NickTyrer** [comment]
Shall I seperate them or leave them as is?

**Comment by ratkosrb** [comment]
You have to check how it works on Classic.

**Comment by NickTyrer** [comment]
I will seperate them out then.

**Comment by ratkosrb** [comment]
If they don't require each other and you can get the last one before doing the previous then yes.

**Comment by NickTyrer** [comment]
For future ref in Classic, you need to hand in all 3 (Wool, Silk, Mageweave) before you get the quest for Runecloth.
The first hand in of Runecloth nets you XP the repeatable does not.
