### ISSUE TITLE
NPC bug Vosur Brakthel

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#491]
**Current behavior**: 
He sells the worng items
![vmangos](https://user-images.githubusercontent.com/22723839/80456049-cda21180-8924-11ea-989a-93349dcc3c8a.png)

**Expected behavior**: 
He should only sell 
![classic](https://user-images.githubusercontent.com/22723839/80456062-d692e300-8924-11ea-832e-1971b218229e.png)

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by NickTyrer** [comment]
fixed in #480

**Comment by ratkosrb** [comment]
You are confusing selling with training.

**Comment by NickTyrer** [comment]
I know, figured it out now.
