### ISSUE TITLE
NPC missing greetings

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#496]
**Current behavior**: 
a couple of npc's are missing greeting text
![2](https://user-images.githubusercontent.com/22723839/80511310-dbcb4e80-8973-11ea-9189-fcdafba7ce9f.png)
![3](https://user-images.githubusercontent.com/22723839/80511323-dec63f00-8973-11ea-96fb-4432a8144cbc.png)
![4](https://user-images.githubusercontent.com/22723839/80511331-e0900280-8973-11ea-934c-c9689498d63f.png)
![1](https://user-images.githubusercontent.com/22723839/80528306-a3386e80-898d-11ea-9b84-6318af992f2c.png)
![2](https://user-images.githubusercontent.com/22723839/80528314-a6cbf580-898d-11ea-8d3a-7a9ad9f6ebd2.png)

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by Daribon** [comment]
On the last picture, on classic he changes from between 
('I live only to serve our King.', '', 9497, 0, 0, 0, 1, 0, 0, 1, 2, 0, 0, 0, 0, 31727),
and 
('Behold the might of the Alliance! The dread lady, Onyxia, hangs from the arches! Let the rallying cry of the dragon slayer lift your spirits!', '', 9496, 7, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 31727),
depending on if the onyxia head is hanging or not.

Here is an image what it should show if you have completed the onyxia attunement quest when talking to Squire Row:
![image](https://user-images.githubusercontent.com/6137576/80832339-c14fda00-8bec-11ea-8de2-882ec8b497f6.png)
('Hail, champion. The tale of your deeds will be told throughout the ages. Perhaps one day, a statue of you will stand amongst the heroes of Stormwind.', '', 14390, 0, 0, 0, 1, 0, 0, 1, 1, 66, 0, 0, 0, 31727),

Here is what I got when speaking to the gnome enchanting trainer with no enchanting skill:
![image](https://user-images.githubusercontent.com/6137576/80832745-8601db00-8bed-11ea-857a-67212c46f19f.png)
('Who are you? What do you want from me?', '', 7889, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 31727),

**Comment by ratkosrb** [comment]
Field Marshal Afrasiabi, Major Mattingly and Squire Rowe are fixed now.
