### ISSUE TITLE
LOS check ignores some gameobjects

### ISSUE THREAD

**Issue by schell244** [vmangos/core#499]
Npcs can start attack/cast spells through fence:
https://classic.wowhead.com/npc=2272/dalaran-theurgist

<img width="714" alt="79684398-4c19f780-8231-11ea-8af3-63f9284e64a3" src="https://user-images.githubusercontent.com/9536270/80803144-b7f54c00-8bb1-11ea-8bbd-e7dd3c6fe69d.PNG">

I did some research about LOS checks and found that some gameobjects are (intentionally) ignored.
https://github.com/cmangos/mangos-classic/pull/239

The bug mentioned above does no longer occur, once you remove the following lines at 
MapTree.cpp, line39-42:

```
        // Nostalrius: pas de LoS pour certains models (arbres, ...)
         if (los && prims[entry].flags & MOD_NO_BREAK_LOS)
            return false;
```

I assume that this is also responsible for many incorrect pulls (through house ceilings, etc...)
More testing needs to be done on this.

**Client version**: 
1.12.1
**Commit hash**: 
04a2826
**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
Does this fence cause LoS on Classic?

**Comment by schell244** [comment]
Enemies start attack (see player) through fence ->no
Enemies and player can attack through fence -> yes

**Comment by Daribon** [comment]
Almost all .m2 objects ignore spell LoS in classic. I believe doors are the only .m2 objects which do follow LoS.

**Comment by schell244** [comment]
So I guess the correct way would be to distinguish between attack and enemy detection LOS and then decide whether to ignore .m2 objects?

**Comment by schell244** [comment]
I noticed that sometimes also the cursor does ignore LOS. 
For example player can detect/select an enemy by clicking on a wall:

<img width="510" alt="LOS" src="https://user-images.githubusercontent.com/9536270/92573800-935b6000-f286-11ea-98e0-0baae2144348.PNG">

I compared some of the vmap code to CMangos and noticed that VMangos uses an additional flag (appart from M2) for ignoring LOS:

https://github.com/vmangos/core/blob/d8a1dc68cadba45d03046f469dc5150128898354/src/game/vmap/ModelInstance.h#L35-L41

https://github.com/cmangos/mangos-classic/blob/9b0203a8da00d8eaa3794cacd6cd313072c7625b/src/game/vmap/ModelInstance.h#L35-L40

**Comment by ratkosrb** [comment]
The cursor thing has nothing to do with the server. That's a client issue.

**Comment by schell244** [comment]
> Almost all .m2 objects ignore spell LoS in classic. I believe doors are the only .m2 objects which do follow LoS.

closed

**Comment by ulfgebhardt** [comment]
Are you sure about this @schell244 ? I noticed that static objects do not hinder a mob to aggro - so they aggro through fences and buildings etc. Is that blizzlike? Feels a bit off for me. <3

**Comment by schell244** [comment]
You're right, it feels a bit off for me too. On my local server I've actually commented out the code to ignore m2 object los.
Spells ignoring m2 objects is defintely classic behaviour, but for aggro I think it's wrong. 
I could open a new issue for aggro LOS only, or just reopen this and change the title?

**Comment by ulfgebhardt** [comment]
Can we make ignoring m2 objects a config option?

from there we could develop this feature into having multiple config options - m2 los for spells, for aggro, for pathing etc

Would you be willing to make the los of m2 a config option, since you already found the specific part in the code @schell244 ?

**Comment by schell244** [comment]
With https://github.com/vmangos/core/pull/945 it's now up to the world.conf whether m2 objects are ignored by default or not

**Comment by ulfgebhardt** [comment]
@schell244 Your PR was merged - congrats - but isn't it right that this needs a followup ticket? If you agree would you be willing to open it? <3

**Comment by ratkosrb** [comment]
Liar, liar, pants on fire.
https://streamable.com/exrvc5

Mobs do aggro through M2 objects. Do not report things as bugs if you have not actually verified how it works on official servers!
