### ISSUE TITLE
NPC bug trixie quikswitch

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#500]
**Current behavior**: 
Her training menu is not accessible
![Untitled](https://user-images.githubusercontent.com/22723839/80804849-4ff13680-8bae-11ea-9ab3-3a356a57892f.png)

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by Daribon** [comment]
Her gossip option is only visible if you have reached a certain skill in engineering.
This is working correct as it is atm.

![image](https://user-images.githubusercontent.com/6137576/80898233-6bb92180-8d01-11ea-94ee-8d07192363f3.png)
This is from classic.

**Comment by NickTyrer** [comment]
She wont offer any training regardless of skill. Although you may have uncovered a wider bug, all of the trainers offer their training catalogue regardless of skill.

**Comment by NickTyrer** [comment]
@ratkosrb currently she is assigned gossip_menu_id = 4147 which is incorrect. This is the same in cmangos, in this case is it ok to add a new menu_id?

**Comment by ratkosrb** [comment]
How do you know that gossip menu id is not correct? There can be multiple npc texts per gossip menu.

**Comment by NickTyrer** [comment]
Ah, diddent realise there could me multiple. So is it ok if I add a new gossip menu_id to add the train me option?
