### ISSUE TITLE
NPC missing Alowicious Czervik

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#502]
**Current behavior**: 
he is currently missing
![Untitled](https://user-images.githubusercontent.com/22723839/80860978-6d340c80-8c63-11ea-8799-ce4a37bd422f.png)

he should be here
![d](https://user-images.githubusercontent.com/22723839/80860981-74f3b100-8c63-11ea-937d-765af52d4ddc.png)

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win10

**Comment by Daribon** [comment]
This NPC only spawns during the annual Children's Week event.
Make sure children's week event is activated in your database.
