### ISSUE TITLE
NPC incorrect location Opus

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#504]
**Current behavior**: 
Opus is in incorrect location

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
He is not missing, guid 4567.

Here is how you look for a creature id spawn in the database. Select the `mangos` database in HeidiSQL, click on the Query tab, and run this:
```
SELECT *
FROM creature
WHERE id=10262
```

Also in game you can type this command to get a list of spawns in chat:
```
.list creature 10262
```

**Comment by NickTyrer** [comment]
![Untitled](https://user-images.githubusercontent.com/22723839/80942322-667cd500-8ddc-11ea-9ddf-8e2d569a9afe.png)
