### ISSUE TITLE
Inspect player - missing distance check

### ISSUE THREAD

**Issue by schell244** [vmangos/core#505]
Sometimes 'inspect player' can be triggered from to far -> only empty slots are shown. 
To reproduce: both players must be walking.

CMangos checks IsWithinDistInMap() in HandleInspectOpcode() and HandleInspectHonorStatsOpcode() with a constant value for max inspect distance.

Object.h
```#define INSPECT_DISTANCE  28.0f```

MiscHandler.cpp 
```
if (!_player->IsWithinDistInMap(plr, INSPECT_DISTANCE))
        return;
```

**Client version**: 
1.12.1
**Commit hash**: 
c75005e
**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/5cbd094b93e7044846d15d9055ebf999821f4acc
