### ISSUE TITLE
NPC missing text Ragged John

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#507]
**Current behavior**: 
![asdasfggg4rrrrrrrrrrr](https://user-images.githubusercontent.com/22723839/80950218-59b4ad00-8ded-11ea-9bf9-cf7cbbc7210e.png)

**Expected behavior**: 
![john1](https://user-images.githubusercontent.com/22723839/80950229-60dbbb00-8ded-11ea-9823-3284b73b2355.png)
![john2](https://user-images.githubusercontent.com/22723839/80950244-65a06f00-8ded-11ea-917b-b5e142f27f77.png)
![john3](https://user-images.githubusercontent.com/22723839/80950246-676a3280-8ded-11ea-8cb4-50f82e5d42a6.png)
![john4](https://user-images.githubusercontent.com/22723839/80950250-689b5f80-8ded-11ea-88c8-d3e6a7e84651.png)
![john 5](https://user-images.githubusercontent.com/22723839/80950259-6b965000-8ded-11ea-8223-85ce434dfbb5.png)
![john6](https://user-images.githubusercontent.com/22723839/80950262-6d601380-8ded-11ea-82c0-a5e40c2e25a0.png)
![john7](https://user-images.githubusercontent.com/22723839/80950265-6e914080-8ded-11ea-89a3-ae91de575e1b.png)
![john8](https://user-images.githubusercontent.com/22723839/80950266-6fc26d80-8ded-11ea-827e-2ecbae22df34.png)
![john9](https://user-images.githubusercontent.com/22723839/80950271-718c3100-8ded-11ea-98d5-4ae92f36f0e8.png)
![john10](https://user-images.githubusercontent.com/22723839/80950275-72bd5e00-8ded-11ea-954c-ce39391f7551.png)
![john11](https://user-images.githubusercontent.com/22723839/80950280-751fb800-8ded-11ea-9d4c-386808aa5b73.png)
![john12](https://user-images.githubusercontent.com/22723839/80950281-76e97b80-8ded-11ea-9542-2fae77977427.png)
![john13](https://user-images.githubusercontent.com/22723839/80950285-78b33f00-8ded-11ea-8765-c0b4dc1844b5.png)

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win10

**Comment by alexkulya** [comment]
Should appear when completing the task: https://classic.wowhead.com/quest=4224/the-true-masters

Isn't that right?

**Comment by NickTyrer** [comment]
I don't think so, I am seeing this as a horde player. Is there an equivalent hord quest that unlocks it?

**Comment by ratkosrb** [comment]
I talked to him in Classic and there is no dialog option. I have not done any quests in the zone.
![Untitled](https://user-images.githubusercontent.com/35845488/82128563-d28c0f80-97c4-11ea-8042-98bafd012cb3.jpg)

**Comment by NickTyrer** [comment]
The dialogue is unavailiable for alliance untill a quest chain is complete. A horde the text  should be available from what I have seen

**Comment by ratkosrb** [comment]
Try talking to him on a level 1 character to make sure its not unlocked by another quest for horde.

**Comment by NickTyrer** [comment]
Hung around and asked a fellow hordie to speak to him, looks like I did a quest along the line that unlocked it, not sure which.
