### ISSUE TITLE
How to add anticheat system?

### ISSUE THREAD

**Issue by ghost** [vmangos/core#51]
Hello dude.

Cmake "USE_ANTİCHEAT " enable not working.
core/src/game/Anticheat there are two files.
How we can add?

**Client version**: 1.12

**Commit hash**: f9e8c3d

**Operating system**: Windows 7 Sp1

**Comment by alexkulya** [comment]
Anticheat is not public available as far as I know.

**Comment by ghost** [comment]
Hmm. Thanks. maybe it can help @ratkosrb

**Comment by ratkosrb** [comment]
There is no public anti-cheat included with the core. You can try to get the leaked elysium anticheat from 2017 working.

**Comment by ghost** [comment]
> There is no public anti-cheat included with the core. You can try to get the leaked elysium anticheat from 2017 working.

thank you very much ^_^
