### ISSUE TITLE
quest:310,error

### ISSUE THREAD

**Issue by DarkmoonRabbit** [vmangos/core#52]
quest:310
If the first task fails, this task will never be completed.

**Comment by ratkosrb** [comment]
How can you fail this quest, I don't understand. All you have to do is go to the basement, click on the barrel, then give the dwarf a beer, wait for him to walk away, and click on the barrel again.

**Comment by DarkmoonRabbit** [comment]
Haha, as you said... it is really simple.
But: I followed the NPC and went up...
