### ISSUE TITLE
Missing Teleport command for Chillwind Camp in Western Plaguelands

### ISSUE THREAD

**Issue by tonymmm1** [vmangos/core#525]
**Current behavior**: 
.lookup tele Chillwind Camp
.lookup tele chill
**Expected behavior**: 
Teleport location should match request
**Steps to reproduce**:
.tele Chillwind Camp
**Client version**: 
1.12.1
**Commit hash**: 
ab11bde485814e2161bf8d174ff789035ecae2fe
**Operating system**: 
Linux 64 bit

**Comment by Daribon** [comment]
I have all internal teleports used by blizzard. 1483 teleports used during WoWs development.
Could replace all teleports with it.

**Comment by ulfgebhardt** [comment]
@Daribon would you be interested in making a PR for this? <3

**Comment by NickTyrer** [comment]
.tele Chillwind Camp now working
