### ISSUE TITLE
NPC bug Henry Stern

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#530]
**Current behavior**: 
He offers no training
![stern](https://user-images.githubusercontent.com/22723839/81481798-78220a80-922a-11ea-923c-d335787c8de1.png)

**Expected behavior**: 
He should offer to teach Goldthorn Tea and Mighty Troll's Blood Potion. See https://classic.wowhead.com/npc=8696/henry-stern#comments
https://www.youtube.com/watch?v=vrvGheW9P2c (17:27)

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
He only offers to teach you the recipes if you have enough skill. It's not a normal training menu, it's a gossip option.

**Comment by NickTyrer** [comment]
@ratkosrb The menus are slightly different in classic. This made me think it wasnt working, thanks for checking
![stern 1](https://user-images.githubusercontent.com/22723839/81852198-8d60a700-9552-11ea-95eb-e57fd0483ab7.png)
![stern](https://user-images.githubusercontent.com/22723839/81852261-a49f9480-9552-11ea-9916-c4679d4a6dc3.png)
