### ISSUE TITLE
NPC bug Melnan Darkstone

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#534]
**Current behavior**: 
He is static
**Expected behavior**: 
He should walk a circuit
https://classic.wowhead.com/npc=14842/melnan-darkstone

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
This guy didn't even have a spawn, so interesting how you concluded he is static.

**Comment by NickTyrer** [comment]
I have my ways
