### ISSUE TITLE
Client does not recognize soulbound items as soulbound

### ISSUE THREAD

**Issue by codestothestars** [vmangos/core#536]
**Current behavior**: 
The client never recognizes items as soulbound. For example, when using a bind-on-use item, the player is shown the "Using this item will bind it to you" confirmation on every use. The soulbound flag is still set correctly in the database.

This issue is not present on 1.7.1+.

**Expected behavior**: 
Soulbound items are recognized as soulbound by the client.

**Steps to reproduce**:

1. `.additem 8492`
1. Use parrot cage.
1. Click OK.
1. Use parrot cage again.

**Client version**: 
1.6.1 (4544)

**Commit hash**: 
[7b9dc69](https://github.com/vmangos/core/commit/52552831f4f4a11451544d509fe410e06206cc95)

**Operating system**:
Arch Linux 5.6.11-arch1-1

**Comment by ratkosrb** [comment]
~~It's possible the warning message did not exist before that patch.~~

Edit: nvm i didn't read the issue correctly
