### ISSUE TITLE
NPC bug Zixil

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#538]
**Current behavior**: 
He is static
**Expected behavior**: 
He should walk a circuit
https://classic.wowhead.com/npc=3537/zixil#comments

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
He already has waypoints, so not sure what you are talking about.
```
SELECT *
FROM Mangos.creature_movement
WHERE id=15424
```
