### ISSUE TITLE
Deduction calculation from Rep and Honor bug

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#539]
**Current behavior**: 
The deductions calculation is slightly out see
![Untitled Diagram](https://user-images.githubusercontent.com/22723839/81585358-f35efa00-93ab-11ea-8c00-e081fb6e415b.png)
green is classic

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by ghost** [comment]
Can this be closed now @NickTyrer ?
