### ISSUE TITLE
Dwarven mortar team (dun morogh) event missing

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#548]
**Current behavior**: 
Currently the motar team is static
**Expected behavior**: 
They should be scripted see:
https://www.youtube.com/watch?v=V9gr_12Usj8

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
WIn10

**Comment by Kittnz** [comment]
This was scripted, not sure what happend to this event

**Comment by NickTyrer** [comment]
Ignore, it is there
