### ISSUE TITLE
Grimtotem Tauren have the wrong scale

### ISSUE THREAD

**Issue by mikemenasi** [vmangos/core#559]
**Current behavior**: 
Grimtotem Tauren have the wrong scale
https://github.com/cmangos/classic-db/commit/89ad577ef1c8079b1681fdaedd82bd37423bcf10

**Client version**: 
1.12.1
**Commit hash**: 
1
**Operating system**: 
Win10

**Comment by ratkosrb** [comment]
Fixed.
