### ISSUE TITLE
Feature Request: create mmaps directory with MoveMapGen 

### ISSUE THREAD

**Issue by tonymmm1** [vmangos/core#560]
**Current behavior**: 
Error no mmap directory
**Expected behavior**: 
Continue 
**Steps to reproduce**:
1.  run MoveMapGen

**Commit hash**: 
https://github.com/vmangos/core/commit/22202bb9263e4a019634a88fdb2e4a7cf90a92c7
**Operating system**: 
Linux 64bit

**Comment by ulfgebhardt** [comment]
@tonymmm1 would you be interested in making a PR for this? The other extractors create their respective directories, so you can probl. copy from there. Additional the error-message was improved jsut lately since this is still a problem. <3
