### ISSUE TITLE
NPC Aura bug

### ISSUE THREAD

**Issue by mikemenasi** [vmangos/core#563]
**Current behavior**: 
 NPC 15933 is missing aura 26575 (Toxin)
**Expected behavior**: 
see https://github.com/cmangos/classic-db/commit/f162c49cec1f369a2c4a6129cba59adecbb7884f

**Client version**: 
1.12.1
**Commit hash**: 
1
**Operating system**: 
Win10

**Comment by ulfgebhardt** [comment]
@mikemenasi are you interested in workig on thi issue and provide us with a fix? <3

**Comment by ulfgebhardt** [comment]
@mikemenasi are you closing those issues because they are fixed or because you don't wanna get pinged anymore?
