### ISSUE TITLE
Innkeepers don't set home location

### ISSUE THREAD

**Issue by codestothestars** [vmangos/core#569]
**Current behavior**: 
Asking an innkeeper to "Make this inn your home" does nothing.

This issue is not present on patch 1.7.1+.

**Expected behavior**: 
"Make this inn your home" changes the player's home location.

**Steps to reproduce**:

1. Talk to any innkeeper
1. Click "Make this inn your home"

**Client version**: 
1.6.1 (4544)

**Commit hash**: 
[d5ac534](https://github.com/vmangos/core/commit/d5ac534c57c7204599ad400fa4889768d7de89b7)

**Operating system**: 
Windows 10.0.18363

**Comment by Daribon** [comment]
Can confirm on 1.6.1
