### ISSUE TITLE
Can't register guild charter (You don't have a guild charter)

### ISSUE THREAD

**Issue by codestothestars** [vmangos/core#571]
**Current behavior**: 
Upon attempting to register a guild charter, the guild is not created and the player receives the error message "You don't have a guild charter". The charter remains in the player's inventory.

This issue is not present on patch 1.7.1+.

**Expected behavior**: 
Upon attempting to register a guild charter, the guild is created with no error message and the charter is removed from the player's inventory.

**Steps to reproduce**:

1. Purchase a guild charter
1. Obtain the required signatures
1. Attempt to register the guild charter

**Client version**: 
1.6.1 (4544)

**Commit hash**: 
[d5ac534](https://github.com/vmangos/core/commit/d5ac534c57c7204599ad400fa4889768d7de89b7)

**Operating system**: 
Windows 10.0.18363

**Comment by ratkosrb** [comment]
Make sure the charter is in your main bag.

**Comment by codestothestars** [comment]
I produced this bug using two level 1 characters with `MinPetitionSigns = 1` on a clean database. Using only the steps above on fresh characters, the issue occurs on 1.6.1 but not on 1.7.1.

Edit: That is to say, in both cases the charter was definitely in the Backpack and not another bag.
