### ISSUE TITLE
NPC Bug Thorvald Deepforge

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#574]
**Current behavior**: 
He is a vendor and does not have a faction
![dddd](https://user-images.githubusercontent.com/22723839/82832111-1f9d6f00-9eb2-11ea-9881-646fdc258aa3.png)

**Expected behavior**: 
He should not be a vendor and has a faction
![asdasda](https://user-images.githubusercontent.com/22723839/82832067-04cafa80-9eb2-11ea-80ca-6e0a9e7b2123.png)

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by Oroxzy** [comment]
and the gamobjects around him ? xD

**Comment by Kittnz** [comment]
we still miss a ton of game objects in the world, we got sniffs for it but we need to filter out a lot of objects such as herbs and what not
