### ISSUE TITLE
Knockbacks issue

### ISSUE THREAD

**Issue by BBCnewstoday** [vmangos/core#579]
Any knockback will remove your run mode. If you push your Numlock for auto-run, knockback will remove it. The same goes for "W" key pushing.
It shouldn't be, movement should continue after your landing.

Very annoying in raids, and should be easy fixable (I hope)

**Comment by ratkosrb** [comment]
The knockback packet does not even contain movement flags, so I believe the client is cancelling movement on its own.

**Comment by ulfgebhardt** [comment]
Closing this since it seems unlikely to be a server issue. It appears to be a client side thing.
If you disagree or have further insights feel free to reopen this @BBCnewstoday <3
