### ISSUE TITLE
NPC Bug Bingles Blastenheimer

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#584]
**Current behavior**: 
He can be killed by a wandering mob, when he respwans you are unable to accept his quest. (this may be a wider bug if a quest giver is killed).

**Expected behavior**: 
You should be able to get his quest when he respawns

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
Is it fixed?

**Comment by NickTyrer** [comment]
Wasn't a bug, once I went out of range and went back to him I could get the quest.
