### ISSUE TITLE
Possible dupe method

### ISSUE THREAD

**Issue by BBCnewstoday** [vmangos/core#585]
Seems like group-wide dropped items can be multiple times looted with simple quick looting.
Noticed that with Feathers quest in Sunken Temple and Splinter Log(Natural Minerals Feralas quest).

I just clicked item icon in the loot window multiple times and looted same item twice. 
Most likely this method can be improved with loot macro/high latency.

**Comment by rosen40** [comment]
confirmed. Double clicked Splinter Log and got 2 of it.

**Comment by ulfgebhardt** [comment]
> This only affects quest items. 

![image](https://user-images.githubusercontent.com/1238238/103448058-1e2bf480-4c94-11eb-8aae-bf2df96182c1.png)
