### ISSUE TITLE
NPC bug Eris Havenfire

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#593]
**Current behavior**: 
She is always visible.
**Expected behavior**: 
She should only be visible if you have the eye of divinity equipped

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
Were you in GM mode?

**Comment by NickTyrer** [comment]
@ratkosrb nope, gm is disabled

**Comment by ratkosrb** [comment]
![WoWScrnShot_060620_230759](https://user-images.githubusercontent.com/35845488/83953689-ef0eeb00-a84a-11ea-8a1b-d9efc367c32c.jpg)

**Comment by NickTyrer** [comment]
![sdad](https://user-images.githubusercontent.com/22723839/83953744-bc5cf680-a83a-11ea-80f5-8d6c858ab2bc.png)

**Comment by ratkosrb** [comment]
Seems like a problem with your local server.

**Comment by NickTyrer** [comment]
Maybe, it is a fresh build though. Although I did speak to her before I disabled GM maybe it has cached something?

**Comment by ratkosrb** [comment]
Not sure what happened but I can't see her without GM mode.
