### ISSUE TITLE
Rogue Distract 

### ISSUE THREAD

**Issue by Schmoha** [vmangos/core#596]
**Current behavior**: The ability can be used on targets that are in combat.

**Expected behavior**: The ability should not be able to be casted on a target that is in combat.

Links:
https://youtu.be/XcboEd307HQ?t=207
https://www.warcraftmovies.com/de/movieview.php?id=1631 The players warcraftmovies videolink
https://wow.gamepedia.com/Patch_1.4.0 The video was uploaded in May 10, so thats mostlikely Patch 1.4
 https://www.warcraftmovies.com/movieview.php?id=25584 And another video.
Go to 22:02. Thats atleast patch 1.9 but not after patch 1.11 because he has detect traps and it was changed to passive in 1.11
**Steps to reproduce**:

1. fight a mob
2. use distract

**Client version**: 1.12

**Commit hash**: 

**Operating system**: Win7

**Comment by ratkosrb** [comment]
I just tested this and it is not affecting targets that are in combat. Nothing happens when using Distract on a player or mob that is in combat in latest vmangos version. I cannot reproduce the bug.

**Comment by Schmoha** [comment]
I had tested this on ValorVoid Gaming x15 where it did not work a few weeks ago.
Thanks. so it is working.

**Comment by ratkosrb** [comment]
Do not report bugs from private servers. This issue tracker is about the vmangos project. Make sure there is a problem on the latest vmangos revision before opening an issue.

**Comment by Schmoha** [comment]
It is on 1.12 vmangos, but i cannot tell if its the latest revision. I tried joining another ones vmangos realm but i guess thats generally not a good idea? I think that should be written in the FAQ or something.
