### ISSUE TITLE
NPC Missing Feature Antonio Perelli 

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#603]
**Current behavior**: 
He is missing all of his dialogue

**Expected behavior**: 
He should have different dialogue depending on where he is see:
https://wow.gamepedia.com/Antonio_Perelli

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
But I worked on this npc before and added his texts :confused: 
https://github.com/vmangos/core/blob/58e83ed56bd863c3ad433931a3a08b5f4fac5e76/sql/old_migrations/20180717170429_world.sql

And I just followed him and he is saying all the appropriate texts at the different stops, so why do you claim the dialogue is missing.
![Untitled](https://user-images.githubusercontent.com/35845488/84424894-65379700-ac29-11ea-968b-ce335d681e92.jpg)

**Comment by NickTyrer** [comment]
I must have done something on my install to break him. Cheers for checking.

**Comment by Kittnz** [comment]
@NickTyrer please link the last commit your use (hash) on your test server

**Comment by ratkosrb** [comment]
We need a bot like the one they have on the Trinity repo to automatically close issues without a commit hash linked.

**Comment by NickTyrer** [comment]
@Kittnz not sure how to find that, was using the latest repack.
