### ISSUE TITLE
Spell "Silithyst" has no deceleration effect.

### ISSUE THREAD

**Issue by gamelgs** [vmangos/core#608]
Spell "Silithyst" has no deceleration effect.

Spell ID 29519

**Client version**: 
1.12.1  5875
**Commit hash**: 
7d0ef5388e402d7e0239c691b164dd005bbfeb5a
**Operating system**: 
win10

**Comment by ulfgebhardt** [comment]
Can you elaborate on this @gamelgs ? <3

**Comment by Oroxzy** [comment]
![silithy](https://user-images.githubusercontent.com/357606/103467629-4d546b80-4d51-11eb-8565-c4afe4b91fb0.png)

idk what he mean.

**Comment by NickTyrer** [comment]
@ulfgebhardt I think he means that you should not be able to go faster than 100% when you have the debuf, so things like rocket boots should not work and maybe they do in vmangos?

**Comment by Oroxzy** [comment]
https://www.youtube.com/watch?v=_YpumVmwybc

can anyone test it on classic? on vmangos i can use Swiftness Potion and also rocket boots. Check also if mounting up gets blocked, or does the player just drop the dust on mount up.

**Comment by NickTyrer** [comment]
@Oroxzy just tested on classic, any speed enhancing buff (pot, shapeshifting, engi) does not work. You get the speed buff, but you do not speed up. For example you can still shapeshift but you do not speed up.

**Comment by Oroxzy** [comment]
Ok thanks @NickTyrer. Now if you deliver the dust you get the buff 29534 (Traces of Silithyst). Check if:

- [x] possible to pickup new dust with this buff? (in vmangos you can)
- [ ] speed limited too? (in vmangos it is)
- [x] possible to pickup a mound? (in vmangos you can)

**if we take a closer look to Traces of Silithyst: https://classicdb.ch/?spell=29534**

**Effect 1: (86) Activate Object (5)**
what does it and which object is meant?
- 181617 (Sillithus Flag Stand, Horde)
- 181619 (ToWoW - Flag Cap Counter, Horde)
- 181603 (Sillithus Flag Stand, Alliance)
- 181618 (ToWoW - Flag Cap Counter, Alliance)
- 181598 (Silithyst Geyser) (you can stand near it and .gobj select, .gobj toggle and it disappears, so maybe its this)
- 181597 (Silithyst Mound)

on .cast 29534 console says:
```
Spell entry 29534, effect 0 has EffectImplicitTargetA/EffectImplicitTargetB = TARGET_GAMEOBJECT_SCRIPT_NEAR_CASTER, but gameobject are not defined in `spell_script_target`
Spell entry 29534, effect 0 has EffectImplicitTargetA/EffectImplicitTargetB = TARGET_GAMEOBJECT_SCRIPT_NEAR_CASTER, but gameobject are not defined in `spell_script_target`
```

**Effect 2: (6) Apply Aura 79: Mod Dmg % (127) Value: 5**
This is the dmg buff.

**Effect 3: (64) Trigger Spell**
This triggers spell 31247 wich has a effects:
- Effect 1: (77) Script Effect (not implemented in vmangos) what does it? Should be a honor reward i guess.
- Effect 2: (122)  (609) Value: 10 (gives reputation for Cenarion Circle (faction: 609) this is done manually in the sourcecode:https://github.com/vmangos/core/blob/dfe94c8587788b049b8e4bedf93042bfcbe30678/src/game/OutdoorPvP/OutdoorPvPSI.cpp#L157

**Ok i just might found the bug:**
29534 (Traces of Silithyst) has speed reduction in spell_effect_mod, wich is possibly wrong. It should be 29519 for sure:
```
UPDATE `spell_effect_mod` SET `Id`='29519' WHERE  `Id`=29534 AND `EffectIndex`=0;
```

**Comment by ulfgebhardt** [comment]
Does this `UPDATE `spell_effect_mod` SET `Id`='29519' WHERE  `Id`=29534 AND `EffectIndex`=0;` solve the issue completely?
Could you PR it  @Oroxzy ? <3

**Comment by Oroxzy** [comment]
Need to test first.

**Comment by NickTyrer** [comment]
@Oroxzy here is a video for ref https://youtu.be/CQjoUNw6jnc

**Comment by Oroxzy** [comment]
Ok guys i found something thats unused by the core:

**29895 (Sillithus Flag, Horde, and speed limit (DND))**

- limits the speed as it should be.


**29894 (Sillithus Flag, Alliance, and speed limit (DND))**

- limits the speed as it should be.


**29533 (Sillithus Flag Drop (DND))**

- creates a mound on drop what is currently solved in cpp:
https://github.com/Oroxzy/core/blob/a99a7fae390d73986e308e499c9536ed63fbeb9b/src/game/OutdoorPvP/OutdoorPvPSI.cpp#L180

That means neither 29519 nor 29534 are required in the spell_effect_mod table.
There must be a better fix for this.

**New goals should be for now:**

- [ ] remove speed limit (delete entry 29534 in spell_effect_mod) from Traces of Silithyst wich is wrong?
- [ ] modify the source to use 29533 (Sillithus Flag Drop (DND)) maybe?
- [ ] connect 29519 (dust buff) and 29894  / 29895 (speed limits)) somehow. (maybe ask brot whats the best way without cpp)

**CAN SOMEONE JUST SNIFF THIS SH..! :D**

**Comment by Oroxzy** [comment]
Can be closed
