### ISSUE TITLE
1.6.1 Client Crash in Undercity

### ISSUE THREAD

**Issue by duckbutt55** [vmangos/core#612]
**Current behavior**: 
Client crash on multiple characters approaching the Royal Quarter in the Undercity, resulting in the following output - 

ERROR #132 (0x85100084) Fatal Exception
Exception:	0xC0000005 (ACCESS_VIOLATION) at 0023:005D89F9

The instruction at "0x005D89F9" referenced memory at "0x00000004".
The memory could not be "read".

**Expected behavior**: 

**Steps to reproduce**:

1. Normal behavior, no speed, flying buffs, etc.
2. Occurred on two characters - one with, one without gm privileges. One within the entrance approaching the Royal Quarter, the other outside the entrance, just before entering.

**Client version**: 
1.6.1 Build 4544
**Commit hash**: 

**Operating system**: 
Win 10 64bit

**Comment by Daribon** [comment]
Does it happen when you log back in as well?

**Comment by duckbutt55** [comment]
It does, yes. My only solution, at that point, is to edit the character db (for that toon) to another location.

**Comment by Daribon** [comment]
Can confirm it happening for me as well.
I tried spawning all battlemasters, sylvanas and varimathras elsewhere and they don't seem to crash the client, so it's most likely not some NPC crashing the client.

**Comment by Daribon** [comment]
Doesn't crash anymore on 1.6.1, no idea what made it crash clients before.
The only change I've done to that area is updated Varimathras orientation and scale: https://github.com/vmangos/core/pull/629

**Comment by duckbutt55** [comment]
There doesn't appear to be a `display_scale1` field in the Creature_Template table, but there is a `scale` field.  Anyhow, I made these adjustments to my personal build (that is, the orientation and scale, as cited in #629), and I'm still crashing on two characters. If no one else is experiencing this crash since this commit, should it be made, I will rebuild for another test.

**Comment by Gamemechanicwow** [comment]
> There doesn't appear to be a `display_scale1` field in the Creature_Template table, but there is a `scale` field. Anyhow, I made these adjustments to my personal build (that is, the orientation and scale, as cited in #629), and I'm still crashing on two characters. If no one else is experiencing this crash since this commit, should it be made, I will rebuild for another test.

display_scale was added here: https://github.com/vmangos/core/pull/604

**Comment by duckbutt55** [comment]
Ohhh, ok. Thanks for the clarification! I'll rebuild and reassess.

**Comment by duckbutt55** [comment]
Ok, brand new build. I applied commit #629 to the db, and retraced my steps. Another crash in the same location. Although, I'm now suspicious of the alchemy lab below the royal quarter, rather than the royal quarter itself. Whereas, the crash is sporadic within the royal quarter, it is immediate, and consistent at both entrances to the alchemy lab (at either side of the royal quarter). Makes sense, since they are so close to eachother. Maybe there is a gobject or npc down there that this early client isn't calling for? I can't get close enough to evaluate (without a crash, that is).

Update: The issue is definitely NPC-related. I truncated the creature_template to narrow down the possibilities, and I can now navigate the entire area - without crash.

**Comment by duckbutt55** [comment]
Apothecary Keever - guid: 31870. Wowfreakz says he was added in patch 1.11.1, but I can't cross-reference with wowhead, since their database now says 1.13.2.30406, due to classic. Nevertheless, he is the cause of the issue.

**Comment by ratkosrb** [comment]
Wowhead clones say everything was added in 1.11 because that's when Wowhead was created.

**Comment by duckbutt55** [comment]
Oh, I see. The oldest comment referencing him was on 2005/12/20 (Patch 1.8.4), via Thottbot.

**Comment by Daribon** [comment]
Oh I see the issue.
![WoW_82RFtDAJHY](https://user-images.githubusercontent.com/6137576/85345409-b7629d00-b4f2-11ea-95ff-29f40088edd4.png)
It's probably something in his script which causes the client to crash, not the NPC himself.
This explains why I didn't crash earlier when I was in undercity, his script was probably not running at that time.

**Comment by Daribon** [comment]
Investigated some more, it appears it's the following crashing the client:
 (573402, 6, 2, 138, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Kneel'), 
When I removed it it stopped crashing, however there are more cases of kneel in his script.
After removing the above, it started crashing at:
 (573402, 21, 2, 138, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Kneel'), 
And after removing that, it crashed on the next kneel in the script.
Every single time he does kneel in his script, it crashes the 1.6.1 client.

**Comment by duckbutt55** [comment]
I suspected it has something to do with his ai script aswell. That makes sense, because for the moment I was able to observe him without a crash, he happened to be stuck in a kneeling position. It stands to argue that he should be present, since his name is mentioned in the quest text for 'Errand for Apothecary Zinge', and this quest can be traced via Allakhazam comments all the way back to patch 1.3.1 (likely further).

**Comment by Daribon** [comment]
Now there doesn't seem to be any documentation on events_script table on vmangos. However if the command column works the same way as in Trinitycore then there is a bug in the script.
Since 2 in trinitycore = FIELD_SET. Emote itself in trinitycore is 1 = EMOTE.
If script is trying to change value of an index to 138, no wonder it's crashing. Probably broken in 1.12.1, just not crashing there.

**Comment by ratkosrb** [comment]
Use the vmangos script editor to view or edit scripts. The editor is the documentation, it shows the meaning of all parameters. https://github.com/brotalnia/scripteditor

**Comment by duckbutt55** [comment]
This should do the trick. #631.  That script editor is a life-saver!
