### ISSUE TITLE
1.6.1 incorrect icon on battlemaster menu

### ISSUE THREAD

**Issue by Daribon** [vmangos/core#614]
**Current behavior**: 
Shows a missing texture on battleground menu
![WoW_afxYIiTKYD](https://user-images.githubusercontent.com/6137576/84944202-b215e480-b0e5-11ea-8578-ec78d1fb4047.png)
**Expected behavior**: 
Should show the correct icon.
**Steps to reproduce**:

1. Talk to any battlemaster.

**Client version**: 
1.6.1
**Commit hash**: 
https://github.com/vmangos/core/commit/8cc7a13bdc4d1698e07563d4af7b60b23c1ec51f
**Operating system**: 
Windows 10 x64

**Comment by ratkosrb** [comment]
I thought I had fixed that.

**Comment by ratkosrb** [comment]
I don't get how this happens since invalid gossip option icons are replaced here.
https://github.com/vmangos/core/blob/development/src/game/ObjectMgr.cpp#L9817
https://github.com/vmangos/core/blob/development/src/game/GossipDef.h#L84

**Comment by Daribon** [comment]
I'm on latest revision so if the above fixed 1.7.1 then maybe something changed between 1.6.1 and 1.7.1
