### ISSUE TITLE
Grub & Duhng OOC event

### ISSUE THREAD

**Issue by alexkulya** [vmangos/core#62]
Add OOC event for creatures: [Grub](https://classic.wowhead.com/npc=3443/grub) & [Duhng](https://classic.wowhead.com/npc=8306/duhng)
Data taken from cmangos classic

<pre>
-- Grub & Duhng
UPDATE creature SET MovementType = 2, spawndist = 0 WHERE guid = 14390 AND id = 3443; 
DELETE FROM creature_movement WHERE id = 14390;
INSERT INTO `creature_movement` (`id`,`point`,`position_x`,`position_y`,`position_z`,`waittime`,`script_id`,`orientation`) VALUES
(14390, 1, -534.982, -2982.22, 93.0775, 90000, 344301, 1.3439);
DELETE FROM `creature_movement_scripts` WHERE `id` = 344301;
INSERT INTO `creature_movement_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `target_param1`, `target_param2`, `target_type`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `condition_id`, `comments`) VALUES
(344301, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Grub - Play Emote'),
(344301, 4, 1, 0, 0, 0, 0, 14389, 0, 9, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Grub - Play Emote (Duhng)'),
(344301, 7, 35, 1, 0, 0, 0, 14389, 0, 9, 2, 0, 0, 0, 0, 0, 0, 0, 4.583168, 0, 'Grub - Set Orientation (Duhng)'),
(344301, 10, 1, 1, 0, 0, 0, 14389, 0, 9, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Grub - Play Emote (Duhng)'),
(344301, 14, 35, 1, 0, 0, 0, 14389, 0, 9, 2, 0, 0, 0, 0, 0, 0, 0, 5.91667, 0, 'Grub - Set Orientation (Duhng)'),
(344301, 16, 1, 173, 0, 0, 0, 14389, 0, 9, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Grub - Play Emote (Duhng)');
</pre>

**Comment by ratkosrb** [comment]
I don't think it makes much sense to add a single waypoint, so I changed it to use EventAI.
