### ISSUE TITLE
Fixed two OOC events

### ISSUE THREAD

**Issue by alexkulya** [vmangos/core#624]
Fixed OOC events for creatures:
1. [Smith Slagtree](https://classic.wowhead.com/npc=14737/smith-slagtree)
2. [Mystic Yayo'jin](https://classic.wowhead.com/npc=14739/mystic-yayojin)

<pre>
-- Creature: Smith Slagtree, GUID: 92909, ID: 14737 - orientation, emote, waypoints, movement script
UPDATE `creature_template_addon` SET `emote` = 0 WHERE `entry` = 14737;
UPDATE `creature_movement` SET `orientation` = 3.22886, `script_id` = 14737*100+01 WHERE `id` = 92909 AND `point` = 2;
UPDATE `creature_movement` SET `orientation` = 0.610865, `script_id` = 14737*100+02 WHERE `id` = 92909 AND `point` = 3;
DELETE FROM `creature_movement_scripts` WHERE `id` IN (14737*100+01, 14737*100+02);
INSERT INTO `creature_movement_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `target_param1`, `target_param2`, `target_type`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `condition_id`, `comments`) VALUES
(14737*100+01, 1, 2, 138, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "Smith Slagtree - Set State Kneel"),
(14737*100+01, 4, 2, 138, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "Smith Slagtree - Remove State Kneel"),

(14737*100+02, 2, 15, 23488, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "Smith Slagtree - Cast Spirit Hammer"),
(14737*100+02, 5, 1, 233, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "Smith Slagtree - EMOTE_STATE_WORK_NOSHEATHE_MINING"),
(14737*100+02, 23, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "Smith Slagtree - EMOTE_ONESHOT_NONE"),
(14737*100+02, 24, 1, 69, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "Smith Slagtree - EMOTE_STATE_USESTANDING"),
(14737*100+02, 28, 1, 26, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "Smith Slagtree - EMOTE_STATE_STAND");

-- Creature: Mystic Yayo'jin, GUID: 92911, ID: 14739 - orientation, emote, waypoints, movement script
UPDATE `creature_template_addon` SET `bytes1` = 0 WHERE `entry` = 14739;

UPDATE `creature_movement` SET `orientation` = 100 WHERE `id` = 92911 AND `point` IN (1, 3, 5, 10);

UPDATE `creature_movement` SET `script_id` = 14739*100+01 WHERE `id` = 92911 AND `point` = 2;
UPDATE `creature_movement` SET `script_id` = 14739*100+02 WHERE `id` = 92911 AND `point` = 4;
UPDATE `creature_movement` SET `script_id` = 14739*100+03 WHERE `id` = 92911 AND `point` = 6;
UPDATE `creature_movement` SET `script_id` = 14739*100+04 WHERE `id` = 92911 AND `point` = 11;

DELETE FROM `creature_movement_scripts` WHERE `id` IN (14739*100+01, 14739*100+02, 14739*100+03, 14739*100+04);
INSERT INTO `creature_movement_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `target_param1`, `target_param2`, `target_type`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `condition_id`, `comments`) VALUES
(14739*100+01, 1, 1, 133, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "Mystic Yayo'jin - EMOTE_STATE_USESTANDING_NOSHEATHE"),
(14739*100+01, 7, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "Mystic Yayo'jin - EMOTE_ONESHOT_NONE"),

(14739*100+02, 1, 1, 133, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "Mystic Yayo'jin - EMOTE_STATE_USESTANDING_NOSHEATHE"),
(14739*100+02, 9, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "Mystic Yayo'jin - EMOTE_ONESHOT_NONE"),

(14739*100+03, 1, 1, 133, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "Mystic Yayo'jin - EMOTE_STATE_USESTANDING_NOSHEATHE"),
(14739*100+03, 8, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "Mystic Yayo'jin - EMOTE_ONESHOT_NONE"),

(14739*100+04, 1, 2, 138, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "Mystic Yayo'jin - UNIT_STAND_STATE_SIT"),
(14739*100+04, 39, 2, 138, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "Mystic Yayo'jin - UNIT_STAND_STATE_STAND");
</pre>

**Comment by ratkosrb** [comment]
Please use the proper Set Stand State command in the future, instead of changing update fields directly.
