### ISSUE TITLE
vaelastrasz throne

### ISSUE THREAD

**Issue by Oroxzy** [vmangos/core#625]
the throne at vaelastrasz in bwl is not correct there should be 2 stone chairs
as you can see in most old videos or screenshots.. or from classic

https://www.youtube.com/watch?v=K0m8VNMiE-s

**Comment by Daribon** [comment]
Related issue: https://github.com/vmangos/core/issues/369

**Comment by Oroxzy** [comment]
Yeah sorry my bad
