### ISSUE TITLE
Orb of Command (BWL Teleport) not blizzlike

### ISSUE THREAD

**Issue by GrenderG** [vmangos/core#627]
**Current behavior**:  It teleports right when you click it.

**Expected behavior**:  A gossip dialog should appear.

**Client version**: 
1.12.1

**Commit hash**: 
b28d0ade96d5cdebd298547e42e448f8eacb8296

![image](https://user-images.githubusercontent.com/8654362/85236564-54ec9c80-b41f-11ea-8865-8edf9603cd80.png)

**Comment by Daribon** [comment]
Uses the following broadcast texts:

Gossip text:
`('The orb\'s markings match the brand on your hand.', '', 9858, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 31727),`

Gossip option text:
`('<Place my hand on the orb.>', '<Place my hand on the orb.>', 9859, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 31727),`

**Comment by ulfgebhardt** [comment]
@Daribon would you be willing to PR this?
Or is this fixed already @GrenderG @Kittnz ?

**Comment by Kittnz** [comment]
The weird thing about this gob is, when bwl was released on classic you had to click on the gossip menu, but the next phase of classic they changed it so you don't have to, you auto teleport when you click the gob but it will still send you the gossip and menu.

But no, this isn't fixed.

**Comment by Daribon** [comment]
You sure that's not just part of an addon? iirc nova world buffs auto clicks the bwl orb.

**Comment by ulfgebhardt** [comment]
@Daribon Make a PR pls <3

**Comment by Kittnz** [comment]
@Daribon correct, its from an addon!
