### ISSUE TITLE
Using the GM command will cause the server to crash

### ISSUE THREAD

**Issue by wthslw001** [vmangos/core#63]
**Current behavior**: 
Using the GM command will cause the server to crash, for example: .npc
Use the latest core
**Expected behavior**: 

**Steps to reproduce**:

1. Using the GM command will cause the server to crash, for example: .npc
2. Use the latest core
3. 

**Client version**: 

**Commit hash**: 

**Operating system**:

**Comment by ratkosrb** [comment]
I can't reproduce it. It is not crashing for me.

**Comment by wthslw001** [comment]
> I can't reproduce it. It is not crashing for me.

You can use the command：.add npc

**Comment by wthslw001** [comment]
I don't know if this is helpful for solving the problem of downtime.

**Comment by ratkosrb** [comment]
There is no such command. If you mean .npc add this does not crash the server when i use it.

**Comment by wthslw001** [comment]
> There is no such command. If you mean .npc add this does not crash the server when i use it.

.npc 


![world of warcraft 2018 12 08 - 11 31 50 01 3](https://user-images.githubusercontent.com/8679316/49681536-99834200-fade-11e8-816d-504ea616a8c4.gif)

**Comment by wthslw001** [comment]
Entering the GM command will cause the program to crash.

**Comment by wthslw001** [comment]
Wrong GM command

**Comment by alexkulya** [comment]
- When i entering a command .npc the subcommand menu appears. Example in the screenshot:

![screenshot_1](https://user-images.githubusercontent.com/7693165/49684683-4adaa580-fae8-11e8-90c1-07935c0b463e.png)

- When entering a command .npc add I get an incorrect syntax message:

![screenshot_2](https://user-images.githubusercontent.com/7693165/49684751-eb30ca00-fae8-11e8-91b4-90c9aff01133.png)

- When entering a command .npc add 'EntryID' the requested creature is added to my location.

Used last development branch revision. No crash. In game use gm level 6 access.

**Comment by wthslw001** [comment]
> * When i entering a command .npc the subcommand menu appears. Example in the screenshot:
> 
> ![screenshot_1](https://user-images.githubusercontent.com/7693165/49684683-4adaa580-fae8-11e8-90c1-07935c0b463e.png)
> 
> * When entering a command .npc add I get an incorrect syntax message:
> 
> ![screenshot_2](https://user-images.githubusercontent.com/7693165/49684751-eb30ca00-fae8-11e8-91b4-90c9aff01133.png)
> 
> * When entering a command .npc add 'EntryID' the requested creature is added to my location.
> 
> Used last development branch revision. No crash. In game use gm level 6 access.

Hello, this is the case, if you enter the wrong GM command continuously, it will cause the program to crash.

**Comment by ratkosrb** [comment]
Nothing happens when i spam it.

**Comment by wthslw001** [comment]
> Nothing happens when i spam it.

I am not sure if it is because of the code compilation environment.
Cmake3.11 + VS 2015 X64 +TBB2017

**Comment by kotishe** [comment]
Hello! There are only two commands in the table, so it should be?
![image](https://user-images.githubusercontent.com/29113/49907689-56cbbc00-fe88-11e8-9508-9a50840dd3cd.png)

Levelup also have incorect syntax on debian x64

**Comment by ratkosrb** [comment]
This table is for overriding the required rank set in Chat.cpp. You don't need to add commands there unless you want to change the minimum rank for it.

**Comment by wthslw001** [comment]
此问题已解决。
