### ISSUE TITLE
NPCs inside Champion's Hall using wrong faction

### ISSUE THREAD

**Issue by GrenderG** [vmangos/core#634]
**Current behavior**: 
`12777, 12785, 12780, 12783, 12782` are using Faction 35, which is wrong.

**Expected behavior**: 
Seems like these NPCs should have their corresponding race faction, would be nice to confirm in Classic.

**Client version**: 
1.12.1

**Commit hash**: 
b28d0ade96d5cdebd298547e42e448f8eacb8296

**Comment by Daribon** [comment]
Here are some pictures how it shows in game on classic:

Captain Dirgehammer <Armor Quartermaster>, 12777
![WowClassic_BcGG2WsqyO](https://user-images.githubusercontent.com/6137576/85756393-0a18a080-b70f-11ea-9e68-5a2c610e7157.png)
![WowClassic_LRKQ3khqZ0](https://user-images.githubusercontent.com/6137576/85756450-1997e980-b70f-11ea-895e-7cf9346a7f49.png)

Sergeant Major Clate <Food and Drink>, 12785
![WowClassic_tUhuIGJOb8](https://user-images.githubusercontent.com/6137576/85756799-6a0f4700-b70f-11ea-9661-931bf6a38e36.png)
![WowClassic_oDNwbHcX8f](https://user-images.githubusercontent.com/6137576/85756900-7bf0ea00-b70f-11ea-81f7-5cca4be742f5.png)

Sergeant Major Skyshadow, 12780
![WowClassic_dHLryoYuZU](https://user-images.githubusercontent.com/6137576/85757360-b064a600-b70f-11ea-822f-50f3d4ebef75.png)
![WowClassic_iV4L0qkLUf](https://user-images.githubusercontent.com/6137576/85757367-b35f9680-b70f-11ea-964a-1d3b486a3ae6.png)

Lieutenant Karter <Mount Vendor>, 12783
![WowClassic_JQ9XsKRWOT](https://user-images.githubusercontent.com/6137576/85757595-e86be900-b70f-11ea-997f-00c2f6f19b8d.png)
![WowClassic_29oOATM6gN](https://user-images.githubusercontent.com/6137576/85757609-eace4300-b70f-11ea-80b9-2786282b74d1.png)

Captain O'Neal <Weapons Quartermaster>, 12782
![WowClassic_EQj8hJnqob](https://user-images.githubusercontent.com/6137576/85757780-0afe0200-b710-11ea-8cc0-ec53b699351d.png)
![WowClassic_uJH1UePQnk](https://user-images.githubusercontent.com/6137576/85757785-0b969880-b710-11ea-8a55-f6c17027874a.png)

**Comment by ratkosrb** [comment]
I can't enter the room to check their faction currently since I do not have the required honor rank.

**Comment by GrenderG** [comment]
I'm pretty sure humans are using faction 11, dwarfs 57 and the night elf, 80.

**Comment by Daribon** [comment]
> I'm pretty sure humans are using faction 11, dwarfs 57 and the night elf, 80.

Then why are only some having the faction text visible on tooltip info.

**Comment by GrenderG** [comment]
Hmmm true, it was just a guess anyway, we must wait until we have the data from Classic.

**Comment by ratkosrb** [comment]
From sniffs:
```
id , faction
12777 , 35
12780 , 80
12782 , 35
12783 , 35
12785 , 55
```
