### ISSUE TITLE
[1.6.1] Critical SQL error

### ISSUE THREAD

**Issue by ghost** [vmangos/core#638]
**Current behavior**: mangosd doesn't work because of SQL error
```
>> Loaded 146 SkillRaceClassInfo MultiMap Data
Cleaning up instances...
SQL: SELECT group_instance.leaderGuid, instance FROM group_instance LEFT JOIN characters ON group_instance.leaderGuid = characters.guid LEFT JOIN groups ON group_instance.leaderGuid = groups.leaderGuid WHERE characters.guid IS NULL OR groups.leaderGuid IS NULL
[1064] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups ON group_instance.leaderGuid = groups.leaderGuid WHERE characters.guid IS' at line 1
Error while parsing SQL. Core fix required.

[0x4cf170]
[0x4cebf7]
[0x4c929f]
[0x15f3ce]
[0x15bf8f]
[0x316dd]
[0x1c6cd]
[0x1a7bd]
[0x1a836]
[0x504080]
BaseThreadInitThunk()+0x14 [0x17974]
RtlUserThreadStart()+0x21 [0x6a271]
```

**Expected behavior**: mangosd should work

**Steps to reproduce**:

1. Build VMaNGOS for version 1.6.1 (4544)
2. Start VMaNGOS
3. See error

**Client version**: 1.6.1 (4544)

**Commit hash**: 5cb6957

**Operating system**: Windows Server 2019

**Comment by Gamemechanicwow** [comment]
Thats an mysql syntax error. I just checked the SQL and I can find no errors. 
I would guess this error appears because the tables in your characters db have been altered. 
You could try deleting the characters db and restore the structure by running: https://github.com/vmangos/core/blob/14c4afb4b7b3c9f135d41db04d8e8b0e3e66d252/sql/characters.sql

**Comment by ghost** [comment]
> Thats an mysql syntax error. I just checked the SQL and I can find no errors.
> I would guess this error appears because the tables in your characters db have been altered.
> You could try deleting the characters db and restore the structure by running: https://github.com/vmangos/core/blob/14c4afb4b7b3c9f135d41db04d8e8b0e3e66d252/sql/characters.sql

Doesn't work on clean characters database + 20200316170243_characters.sql. I'm using MySQL 8.0.

**Comment by Gamemechanicwow** [comment]
>  I'm using MySQL 8.0.

Thats the issue. Most of the sql aren't updated for newer mysql versions. It will run on 5.7 - which is also supplied in the repack.

**Comment by Daribon** [comment]
MySQL 8.0 is not supported and probably never will be. Since Mysql 8.0 breaks compatibility with MariaDB there is little reason to upgrade.

If you wanna run VMaNGOS use MySQL 5.7 or MariaDB.

**Comment by ratkosrb** [comment]
This project does not support mysql 8.0.
