### ISSUE TITLE
[< 1.12] Extractors refuse to work

### ISSUE THREAD

**Issue by ghost** [vmangos/core#639]
**Current behavior**: Extractors refuse to work on < 1.12 versions

**Expected behavior**: Extractors should work

**Steps to reproduce**:

1. Install required WoW version
2. Launch extractors
3. See error

**Client version**: only tested on 1.6.1

**Commit hash**: 5cb6957

**Operating system**: Windows Server 2019

**Comment by Daribon** [comment]
Can you post the error?

**Comment by ghost** [comment]
mapextractor.exe
```
Map & DBC Extractor
===================

Opening ./Data/dbc.MPQ
Opening ./Data/terrain.MPQ
Opening ./Data/patch.MPQ
Opening ./Data/patch-2.MPQ
Extracting dbc files...
Extracted 141 DBC files

Extracting maps...
Read Map.dbc file... Done! (42 maps loaded)
Read AreaTable.dbc file...Done! (1045 areas loaded)
Read LiquidType.dbc file...Fatal error: Invalid LiquidType.dbc file format!
```

vmapextractor.exe
```
Extract for VMAP005. Beginning work ....

Game path: Data\
Opening data files from data directory.
Scanning patch levels from data directory.

Opening Data\terrain.MPQ
Opening Data\model.MPQ
Opening Data\texture.MPQ
Opening Data\wmo.MPQ
Opening Data\base.MPQ
Opening Data\patch.MPQ
Opening Data\patch-2.MPQ
Read LiquidType.dbc file...Fatal error: Invalid LiquidType.dbc file format!
```

vmap_assember.exe
```
using Buildings as source directory and writing output to vmaps
Could not read dir_bin file!
exit with errors
```

MoveMapGen.exe
```
'maps' directory is empty or does not exist
Press any key to close...
```

**Comment by Daribon** [comment]
Ah yes, this issue is well known. LiquidType.dbc doesn't exist below 1.10 iirc. Someone has to hardcode the values into the extractor.

Meanwhile if you still wanna run map extractor for < 1.10, simply just use the LiquidType.dbc from the 1.12.1 when extracting.

**Comment by mserajnik** [comment]
I think this can be closed since https://github.com/vmangos/core/commit/a26a28bc2c1e8821a54ebbc2960c1f9aa9aecab4 fixed it.
