### ISSUE TITLE
Billing not implemented

### ISSUE THREAD

**Issue by ghost** [vmangos/core#641]
**Current behavior**: Billing (10-day trial (non-classic), subscription, game time, etc) not implemented

**Expected behavior**: Billing should be implemented

**Commit hash**: 5cb6957

**Comment by ratkosrb** [comment]
This sounds like it goes beyond the scope of this project. We are only recreating the game content. I see no good reason for emulating Blizzard's payment system. I certainly wouldn't want to encourage people to make pay to play servers.

**Comment by ghost** [comment]
> This sounds like it goes beyond the scope of this project. We are only recreating the game content. I see no good reason for emulating Blizzard's payment system. I certainly wouldn't want to encourage people to make pay to play servers.

Without this payment system, the game is not _blizzlike_. Also, IIUC it is not that difficult to implement and I might try to do it (isn't it like a ban with different message sent?), but core takes too much time to build and I don't know is there proper way to update it quickly (please answer in #647 if there is).

Also, were there any warning messages on game time or just disconnection when it ends?

**Comment by ratkosrb** [comment]
Feature request denied. Implementing game time management is tantamount to endorsing for profit servers. If you are going to work on such a thing, then do it in your own fork. This functionality will not be implemented in vmangos.

**Comment by ReynoldsCahoon** [comment]
There could be legitimate reasons to want this outside of implementing a subscription model.

Weren't there 'scheduling' options for accounts? I specifically remember my mother setting this on my younger brother's account. For example if a parent wanted to create a server for their children to play on, and restrict access during certain times or limit the amount of time played per day, would this not be handled through a similar system?

**Comment by ratkosrb** [comment]
go away, ghost
