### ISSUE TITLE
Patch downloading?

### ISSUE THREAD

**Issue by ghost** [vmangos/core#646]
There is some patch downloading opcode in AuthCodes.h:
`    WOW_FAIL_VERSION_UPDATE         = 0x0A,                 ///< Downloading`
IIUC, it is not implemented but was it in vanilla WoW at all? Isn't it related to patchlist/Battle.net which were added in later versions?

**Comment by Daribon** [comment]
No, it was in release client of vanilla.
Here is an image of it when I was testing patch downloading through client about a year ago.
![image](https://user-images.githubusercontent.com/6137576/85927270-40882400-b8a5-11ea-9d5c-7204a1d3d4b0.png)
