### ISSUE TITLE
Cross-compile on GNU/Linux for Windows

### ISSUE THREAD

**Issue by ghost** [vmangos/core#648]
I want to cross-compile VMaNGOS for Windows on a GNU/Linux system. GNU/Linux is my main system and I use Windows only to play World of Warcraft (because running it in Wine in security sandbox is slower and I have more crashes). How can I do it?

**Operating systems**: 
- Arch Linux based distribution
- Windows Server 2019

---

**I cannot use Discord because of their stupid phone verification requirement.**

**Comment by GrenderG** [comment]
I'm being able to run WoW through wine from 0.5.3 to 5.4.8 with no issues at all. You might want to take a look to mingw32, though.

**Comment by NickTyrer** [comment]
If you have the resources try running windows in a vm, I wote a guide setting this up. This is how I run and it works perfectly. https://nickyt8.wordpress.com/2018/07/05/switching-to-linux-part-1-introduction-and-iommu/

**Comment by tonymmm1** [comment]
Running a pass-through vm is a good solution for running native windows applications on linux host and thats what I run personally. That way you can compile server on either vm or linux host and connect to it from Windows guest. But you need adequate hardware for it.

**Comment by ghost** [comment]
> I'm being able to run WoW through wine from 0.5.3 to 5.4.8 with no issues at all. You might want to take a look to mingw32, though.

Maybe `firejail --private` sandbox is slowing/crashing it.

**Comment by tonymmm1** [comment]
Wine works just fine for me with dxvk I am using Lutris wrapper with a 4.6 wine runner version and no issues.

**Comment by tonymmm1** [comment]
![image](https://user-images.githubusercontent.com/20303853/85926278-06e2f900-b864-11ea-8857-59c7e4e6cb49.png)
![image](https://user-images.githubusercontent.com/20303853/85926290-17936f00-b864-11ea-90f5-19189acd4ceb.png)

**Comment by tonymmm1** [comment]
Try it out I am running server on a vm with Docker containers and the game client is on a linux vm with gpu passthrough
