### ISSUE TITLE
playerbot does not work

### ISSUE THREAD

**Issue by acc1122** [vmangos/core#65]
**Current behavior**: 
when I add a playerbot with .bot add or with any .bot command it connects and disconnects repetitively
(google traductor)
**Operating system**: 
windows server 2008r2

**Comment by ratkosrb** [comment]
The playerbots are only for keeping players in the world for 20 seconds after a disconnection. You can't play with them, this is not a singleplayer project.

**Comment by alexkulya** [comment]
That's right. The system is there and working. These bots were used to check stability under load on the server. Fake online bots players (Strees test). Maybe I'm wrong, then I'll be corrected.

**Comment by acc1122** [comment]
Ok, thanks for the clarification
