### ISSUE TITLE
No mail delay when sending mail to alts.

### ISSUE THREAD

**Issue by Daribon** [vmangos/core#652]
**Current behavior**: 
There is currently no mail delay when you send mails to characters within the same account.
**Expected behavior**: 
There should be 1 hour delay when sending mails to characters on your own account. Exactly the same delay that you see when sending mails to anyone.

Source: Classic
**Steps to reproduce**:

1. Send a mail to a character on your own account.
2. Login to the character you sent the mail to.
3. It has already arrived.

**Client version**: 
1.12.1.5875
**Commit hash**: 
https://github.com/vmangos/core/commit/8cc7a13bdc4d1698e07563d4af7b60b23c1ec51f
**Operating system**: 
Windows 10 x64

**Comment by lyn1337** [comment]
There never was any delay when sending mail without any item(s) or money, iirc. Tested on "classic".

**Comment by Daribon** [comment]
After testing on classic I can confirm as well.
If you send mail with only text in it, it will arrive instantly.

**Comment by schell244** [comment]
PR updated
