### ISSUE TITLE
mangosd segfaults on GNU/Linux (64 bit)

### ISSUE THREAD

**Issue by ghost** [vmangos/core#654]
**Current behavior**: mangosd segfaults immediately after starting it without any log

**Expected behavior**: mangosd should not crash of course

**Steps to reproduce**:

1. Build on 64-bit GNU/Linux
2. Start
3. See the crash

**Commit hash**: 062dc60d78

**Operating system**: Arch Linux-based (x64)

**Comment by ellingtonsantos** [comment]
Ghost, look my last pull request: https://github.com/vmangos/core/pull/609/commits/2d3b34338b565648824f1191bfd04e5d34ee71ef

I use Arch Linux as you. I believe it is a GCC bug. 

Another option is compile all code without optimizations (-O0). But pay atention to extractors. They have a hardcoded -O3 in their CMakeLists.txt.

**Comment by ratkosrb** [comment]
@ellingtonsantos Is the mangosd executable crashing for you too, or only extractors?

**Comment by ellingtonsantos** [comment]
Both

**Comment by ratkosrb** [comment]
Have you tried debugging where mangosd crashes?

**Comment by ellingtonsantos** [comment]
Yes. It crashes when it manipulates string::set s
I will get some traces to you.

**Comment by ellingtonsantos** [comment]
Realmd GDB:

Thread 1 "realmd" received signal SIGSEGV, Segmentation fault.
std::_Rb_tree<unsigned int, unsigned int, std::_Identity<unsigned int>, std::less<unsigned int>, std::allocator<
unsigned int> >::_M_insert_<unsigned int const&, std::_Rb_tree<unsigned int, unsigned int, std::_Identity<unsign
ed int>, std::less<unsigned int>, std::allocator<unsigned int> >::_Alloc_node> (                               
    __node_gen=<synthetic pointer>..., __v=<synthetic pointer>: 5875, __p=0x7ffff6f97c80, __x=0x0, 
    this=0x7ffff6f97c78) at /usr/include/c++/10.1.0/bits/stl_tree.h:1816
1816            _Link_type __z = __node_gen(_GLIBCXX_FORWARD(_Arg, __v));

**Comment by ratkosrb** [comment]
Have you tried using a different version of gcc?

**Comment by ellingtonsantos** [comment]
Not yet

**Comment by ellingtonsantos** [comment]
mangosd GDB:

Program received signal SIGSEGV, Segmentation fault.
__static_initialization_and_destruction_0 (__priority=65535, __initialize_p=1)
    at /home/ellton/work/wow-dev/vmangos/core/src/scripts/world/fireworks_show.cpp:566
566     static const std::unordered_map<uint32, std::vector<Position> const&> pos =

**Comment by ratkosrb** [comment]
There has to be something wrong with the compiler.

**Comment by ellingtonsantos** [comment]
Yes. I believe gcc 10 has some issues. I will try to compile with gcc 9.

**Comment by ghost** [comment]
It works when compiled with Clang and there are issues with GCC in many other projects.

**Comment by ulfgebhardt** [comment]
@ghost @necropresto Is it ok to close this since its a compiler issue rather then a mangos issue? <3

**Comment by ellingtonsantos** [comment]
It is ok. GCC 10.2.0 works flawless.
