### ISSUE TITLE
Secret pet codes

### ISSUE THREAD

**Issue by ghost** [vmangos/core#655]
Implement secret pet codes, like some murloc eggs.

**Comment by ratkosrb** [comment]
There is no way to know the codes...

**Comment by ghost** [comment]
> There is no way to know the codes...

IIRC you can find them on the Internet.
It is also possible to create empty table so server admin would add their own codes.

**Comment by ghost** [comment]
Actually, BlizzCon murloc egg codes (the only such item in vanilla) were entered on this page (available in Wayback Machine): http://www.worldofwarcraft.com/misc/pet-redemption.html and then random code was generated, so there should be separate empty table for these codes.

**Comment by ghost** [comment]
Redeeming NPCs should have gossip option with box_coded enabled. [Here](https://github.com/TrinityCore/TrinityCore/issues/12741) is TrinityCore issue.

[Here](https://www.youtube.com/watch?v=TvhSH7UO6ww) is an example how it works.

**Comment by ghost** [comment]
This feature is almost implemented [here](https://github.com/vmangos/core/blob/development/src/game/Handlers/NPCHandler.cpp#L404).

Redeeming NPCs should have coded gossip menu option "I would like to enter the secret code to receive my Murloc pet.".

When code is entered, it should be checked against world database table.

If code is correct, it should be deleted from database, **then** redeeming NPC should cast spell 24863 (Create BlizzCon prize). The code should be logged as correct so gamemasters can help if server crashed when it was created.

If code is incorrect, SMSG_INVALID_PROMOTION_CODE should be sent.

**Comment by ratkosrb** [comment]
You've linked the handler for the gossip option selection opcode. We know gossip options work...
