### ISSUE TITLE
Missing Gameobjects -  Hall of Legends

### ISSUE THREAD

**Issue by mikemenasi** [vmangos/core#657]
**Current behavior**: 
Some objects are missing see https://github.com/cmangos/classic-db/commit/db5b49cae05d0af4046532287f0262a1f6a735df

**Client version**: 
1.12.1
**Commit hash**: 
5a13b14
**Operating system**: 
Windows

**Comment by Daribon** [comment]
All of those gameobjects are already spawned. Please check in game before making report.
