### ISSUE TITLE
[Investigation] Pre 1.4 MC Loot Tables

### ISSUE THREAD

**Issue by GrenderG** [vmangos/core#659]
At this moment MC Loot Tables are wrong in 1.2 and 1.3, vMaNGOS is using 1.4+. I'm creating this Issue for everyone to discuss here and try to find what was the pre-1.4 loot tables. For example, the entire Tier 2 was dropping in MC until 1.4.

**_Patch 1.4.0 (2005-05-05):_**

- Molten Core boss creatures have all received some new items on their loot tables.
- Most of the non-class set items that dropped from Molten Core have had their effective levels increased, resulting in higher DPS     weapons, and/or better stats and effects.
- The loot tables for some of the Molten Core bosses have been improved so they drop an additional epic item per kill.
- Prior to this patch, Molten Core boss creatures could drop items from one of two different tiered sets for every character class. · The loot tables have been changed so Molten Core bosses will now only drop items from the lower tier class sets. However, some of the items from those sets were not previously dropping in Molten Core. These missing class set items will now drop in Molten Core, allowing players to complete their lower tier class sets._

_EDIT: Removed items that already have the correct patch._

**Comment by ratkosrb** [comment]
The items you linked already have correct minimum patch set in item_template and will not drop before patch 1.4.

**Comment by GrenderG** [comment]
True, I only took a look at patch in `*_loot_template`. I'll edit the Issue then, we still need to figure out which bosses dropped with T2 piece. 🙂

**Comment by Daribon** [comment]
That's an easy task, just use Allakhazam and check for bosses.
Baron Geddon pre 1.4:
https://web.archive.org/web/20050412154454/http://wow.allakhazam.com/db/mob.html?wmob=12056
Shazzrah pre 1.4:
https://web.archive.org/web/20050407221230/http://wow.allakhazam.com/db/mob.html?wmob=12264

**Comment by GrenderG** [comment]
Nice!

**Comment by Daribon** [comment]
You can also search by items too, for example on thottbot:
https://web.archive.org/web/20060806081318/http://www.thottbot.com:80/?i=27183
Showing that Bloodfang Gloves used to drop on Magmadar

Only thing to keep in mind when using thottbot, it uses custom entries for everything, so you can't just change copy and paste same entry from wowhead and expect it to show you the same mob.

Here is another example on searching by items, this time on allakhazam:
https://web.archive.org/web/20050318171550/http://wow.allakhazam.com/db/item.html?witem=16832
Bloodfang Spaulders dropping from Sulfuron Harbinger.

**Comment by GrenderG** [comment]
Should be fixed in https://github.com/vmangos/core/commit/1c9726b5277538acd781367957f305a1eb3f0c3c.
