### ISSUE TITLE
Defias Dockworker Wrong Speed

### ISSUE THREAD

**Issue by mikemenasi** [vmangos/core#665]
**Current behavior**: 
I have compared our values with sniffs from Classic and only found 1 creature that is using the wrong speed value, and in fact is faster than intended.

Defias Dockworker is currently running at the default speed (1.14286) and it should run at 0.857143.

See https://forum.gurubashi.org/viewtopic.php?f=8&t=49

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win

**Comment by ratkosrb** [comment]
I correct movement speeds for mobs in bulk, so this will wait until I make another big update.
