### ISSUE TITLE
Incorrect damage stats for two Winterfall Furbolgs

### ISSUE THREAD

**Issue by mikemenasi** [vmangos/core#669]
**Current behavior**: 
The damage stats for   Winterfall Ursa and High Chief Winterfall are incorrect.

**Expected behavior**: 
see https://github.com/cmangos/classic-db/commit/84c51311be881c44c186c0bf610e74f91e2bc1c4 

**Client version**: 
1.12.1
**Commit hash**: 
ea0f0ee
**Operating system**: 
Win

**Comment by ulfgebhardt** [comment]
Would you be willingto PR this @mikemenasi  ? <3
