### ISSUE TITLE
C++14 flags on C, doesn't compile

### ISSUE THREAD

**Issue by ghost** [vmangos/core#670]
**Current behavior**: vmap_extractor and libmpq have -std=c++14 in C flags

**Expected behavior**: C++14 is C++ standard, so just remove them

**Steps to reproduce**:

1. Use Clang compiler
2. Run CMake
3. Try to build it (two errors) 

**Client version**: unknown

**Commit hash**: ea0f0ee

**Operating system**: GNU/Linux

**Comment by ulfgebhardt** [comment]
I believe this is not an issue, closing
