### ISSUE TITLE
[Feature request] Anti-indulgence system

### ISSUE THREAD

**Issue by ghost** [vmangos/core#677]
On Chinese WoW servers, anti-indulgence system is used.

It is explained here: https://vanilla-wow.fandom.com/wiki/API_GetBillingTimeRested (it is not actually related to billing)

There is some anti-indulgence opcode in realmd, but it is not in vanilla so ignore it.

**Comment by NickTyrer** [comment]
Is this not the same issue as #643?

**Comment by ghost** [comment]
> Is this not the same issue as #643?

No. Anti-indulgence system is mandatory for children and unverified adults in China.

Parental controls will just disconnect player when they are not allowed to play. Parents decide whether or not they use it.

Anti-indulgence system will do the following:
> When you reach 3 hours you will get half tired, reducing both the amount of money and experience that you receive by 1/2. If you play for 5 hours or more you won't be able to turn in quests, receive experience or loot. The seconds [used time] will decay as you stay logged out.

**Comment by ghost** [comment]
See #391.
