### ISSUE TITLE
Implement patch downloading (already implemented)

### ISSUE THREAD

**Issue by ghost** [vmangos/core#680]
Implement patch downloading if client patch is lower than server current patch.

Some patch archive torrent is available [here](https://rutracker.org/forum/viewtopic.php?t=3537465) if needed.

**Comment by Gamemechanicwow** [comment]
I have not personally used this feature, but afaik its already implemented in realmd.
Have you tested it?

**Comment by ghost** [comment]
No. How do I test it?

**Comment by ghost** [comment]
Looks like it is implemented.
