### ISSUE TITLE
[realmd] Add account flags

### ISSUE THREAD

**Issue by ghost** [vmangos/core#685]
[AuthSocket.cpp](https://github.com/vmangos/core/blob/development/src/realmd/AuthSocket.cpp) from realmd defines some AccountFlags.

[This file](https://github.com/TrinityCore/WowPacketParser/blob/master/WowPacketParserModule.BattleNet.V37165/Enums/GameAccountFlags.cs) defines more.

**Comment by ratkosrb** [comment]
This is not a valid issue.

**Comment by ghost** [comment]
Why? How is _valid_ issue defined?

**Comment by ratkosrb** [comment]
To actually report something that is broken and is important to fix. Linking some flags enum from another project does not constitute an issue.
