### ISSUE TITLE
Add Script for Death Knight Darkreaver

### ISSUE THREAD

**Issue by alexkulya** [vmangos/core#70]
- Add Combat Abilities for Death Knight Darkreaver
- Add Spawn Text for Death Knight Darkreaver
- Core Script moved to Database EventAI (Core Script can be deleted)

Since the boss is combat grade and has no mana, the spell control and shadow bolt are set with flag triggered. I don't know if that's right?

<pre>
-- Death Knight Darkreaver
UPDATE `creature_template` SET `spells_template` = 145160, `AIName` = "EventAI", `ScriptName` = "" WHERE entry = 14516;
DELETE FROM `creature_ai_events` WHERE `creature_id` = 14516;
INSERT INTO `creature_ai_events` (`id`, `creature_id`, `condition_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_script`, `action2_script`, `action3_script`, `comment`) VALUES
(1451601, 14516, 0, 6, 0, 100, 0, 0, 0, 0, 0, 1451601, 0, 0, 'Death Knight Darkreaver - Start Script On Death'),
(1451602, 14516, 0, 11, 0, 100, 0, 0, 0, 0, 0, 1451602, 0, 0, 'Death Knight Darkreaver - Start Script On Just Spawn');

DELETE FROM `creature_spells` WHERE `entry` = 145160;
INSERT INTO `creature_spells` (`entry`, `name`, `spellId_1`, `probability_1`, `castTarget_1`, `targetParam1_1`, `targetParam2_1`, `castFlags_1`, `delayInitialMin_1`, `delayInitialMax_1`, `delayRepeatMin_1`, `delayRepeatMax_1`, `scriptId_1`, `spellId_2`, `probability_2`, `castTarget_2`, `targetParam1_2`, `targetParam2_2`, `castFlags_2`, `delayInitialMin_2`, `delayInitialMax_2`, `delayRepeatMin_2`, `delayRepeatMax_2`, `scriptId_2`, `spellId_3`, `probability_3`, `castTarget_3`, `targetParam1_3`, `targetParam2_3`, `castFlags_3`, `delayInitialMin_3`, `delayInitialMax_3`, `delayRepeatMin_3`, `delayRepeatMax_3`, `scriptId_3`, `spellId_4`, `probability_4`, `castTarget_4`, `targetParam1_4`, `targetParam2_4`, `castFlags_4`, `delayInitialMin_4`, `delayInitialMax_4`, `delayRepeatMin_4`, `delayRepeatMax_4`, `scriptId_4`, `spellId_5`, `probability_5`, `castTarget_5`, `targetParam1_5`, `targetParam2_5`, `castFlags_5`, `delayInitialMin_5`, `delayInitialMax_5`, `delayRepeatMin_5`, `delayRepeatMax_5`, `scriptId_5`, `spellId_6`, `probability_6`, `castTarget_6`, `targetParam1_6`, `targetParam2_6`, `castFlags_6`, `delayInitialMin_6`, `delayInitialMax_6`, `delayRepeatMin_6`, `delayRepeatMax_6`, `scriptId_6`, `spellId_7`, `probability_7`, `castTarget_7`, `targetParam1_7`, `targetParam2_7`, `castFlags_7`, `delayInitialMin_7`, `delayInitialMax_7`, `delayRepeatMin_7`, `delayRepeatMax_7`, `scriptId_7`, `spellId_8`, `probability_8`, `castTarget_8`, `targetParam1_8`, `targetParam2_8`, `castFlags_8`, `delayInitialMin_8`, `delayInitialMax_8`, `delayRepeatMin_8`, `delayRepeatMax_8`, `scriptId_8`) VALUES
(145160, 'Scholomance - Death Knight Darkreaver', 22644, 100, 1, 0, 0, 0, 10, 12, 20, 25, 0, 15284, 100, 1, 0, 0, 0, 3, 4, 3, 6, 0, 7645, 100, 5, 0, 0, 2, 15, 17, 30, 40, 0, 17393, 100, 4, 0, 0, 2, 7, 9, 7, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

DELETE FROM `creature_ai_scripts` WHERE `id` IN (1451601, 1451602, 1451603, 1451604, 1451605, 1451606);
INSERT INTO `creature_ai_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `target_param1`, `target_param2`, `target_type`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `condition_id`, `comments`) VALUES
(1451601, 0, 15, 23261, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Death Knight Darkreaver - Cast Spell \'Summon Darkreaver\'s Fallen Charger\''),
(1451602, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 9784, 0, 0, 0, 0, 0, 0, 0, 0, 'Death Knight Darkreaver - Say Text');
</pre>

**Comment by ratkosrb** [comment]
I fixed his mana based on cmangos value and removed the triggered flag from the cast.
