### ISSUE TITLE
Weird behavior with wrapped items

### ISSUE THREAD

**Issue by blipblopium** [vmangos/core#705]
**Current behavior**: Try to wrap some items and they will eventually start being a "?" with no name. If you try to trade them the other person will become invisible.

**Expected behavior**: Wrapped items should properly work.

**Steps to reproduce**: Keep wrapping items until the bug appears.

**Comment by Daribon** [comment]
Most likely related to https://github.com/vmangos/core/commit/69d58a773da95c0b6ca3480a15367a31213f26e1

**Comment by GrenderG** [comment]
I have been told about this issue before, I discussed it with @ratkosrb already but I can't find a proper way of reproducing it in my local build. The issue was _apparently_ happening before that commit too, @Daribon.

Have you done anything more specific to reproduce the bug @blipblopium?

**Comment by blipblopium** [comment]
not really, sorry

**Comment by blipblopium** [comment]
and yes I tried with this commit: https://github.com/vmangos/core/commit/d994cb14222b8abae54e5494d1ff2f29165964e2 so it was before that one

**Comment by ratkosrb** [comment]
@Daribon It's not related.

**Comment by NickTyrer** [comment]
The issue does not happen in 1.12, tested in 1.6 and the bug appears.

**Comment by GrenderG** [comment]
Well it definitely happened in 1.12 before, I remember the bug being present in Gurubashi WoW.

**Comment by NickTyrer** [comment]
Did Gurubashi get to 1.12?

**Comment by GrenderG** [comment]
> Did Gurubashi get to 1.12?

Nope, I meant the client.

**Comment by NickTyrer** [comment]
ok, I saw the bug with 100% replicability using 1.6 and the 1.12 client.

**Comment by GrenderG** [comment]
Ah I thought you were talking about client too! Yeah seems like it only happens in lower content patches for some reason.
