### ISSUE TITLE
The Chinese name of the character will become “????"

### ISSUE THREAD

**Issue by taciturne7** [vmangos/core#707]
Whatever create a new character with Chinese name or use existing Chinese name character enter the game. Character's name will become "???"

After creating a new character with Chinese name, it will become "???" before entering the game, and if you try to enter the game with the "???" name , the connection will be disconnected when the progress bar is finished, and you will be prompted to change the name when you log in again.

But if you choose an existing character with a Chinese name to enter the game, the Chinese name will be displayed in the game correctly. Only when you exit the game, the Chinese name will becom to ”???“

In server.log and char.log, the character's Chinese name is displayed correctly.

The character set of the database is UTF8, the server is a new version that has been upgraded recently, and there was no such problem before.

Please help me, thank you all

**Comment by luolingjun** [comment]
中文乱码问题,应该看看mysql数据库编码问题,设置编码utf8 -- UTF-8 Unicode,utf8_general_ci,不过VS2019编译的时候确实会提醒编码有问题- -,估计cmake转码有些代码没转换成格式utf8,导致vs2019简体版本不识别

**Comment by ulfgebhardt** [comment]
[Chinese garbled problem, you should look at the mysql database encoding problem, set the encoding utf8-UTF-8 Unicode, utf8_general_ci, but when VS2019 is compiled, it will remind you that there is a problem with the encoding--, it is estimated that some codes of cmake transcoding have not been converted into format utf8, The simplified version of vs2019 is not recognized](
https://translate.google.de/?sl=auto&tl=en&text=%E4%B8%AD%E6%96%87%E4%B9%B1%E7%A0%81%E9%97%AE%E9%A2%98%2C%E5%BA%94%E8%AF%A5%E7%9C%8B%E7%9C%8Bmysql%E6%95%B0%E6%8D%AE%E5%BA%93%E7%BC%96%E7%A0%81%E9%97%AE%E9%A2%98%2C%E8%AE%BE%E7%BD%AE%E7%BC%96%E7%A0%81utf8%20--%20UTF-8%20Unicode%2Cutf8_general_ci%2C%E4%B8%8D%E8%BF%87VS2019%E7%BC%96%E8%AF%91%E7%9A%84%E6%97%B6%E5%80%99%E7%A1%AE%E5%AE%9E%E4%BC%9A%E6%8F%90%E9%86%92%E7%BC%96%E7%A0%81%E6%9C%89%E9%97%AE%E9%A2%98-%20-%2C%E4%BC%B0%E8%AE%A1cmake%E8%BD%AC%E7%A0%81%E6%9C%89%E4%BA%9B%E4%BB%A3%E7%A0%81%E6%B2%A1%E8%BD%AC%E6%8D%A2%E6%88%90%E6%A0%BC%E5%BC%8Futf8%2C%E5%AF%BC%E8%87%B4vs2019%E7%AE%80%E4%BD%93%E7%89%88%E6%9C%AC%E4%B8%8D%E8%AF%86%E5%88%AB&op=translate)

**Comment by ulfgebhardt** [comment]
@taciturne7 any update on this? Is this a configuration/compilation issue or is it still a problem?

**Comment by yjfyy** [comment]
MySQL can be resolved by using utf8 encoding, and this issue should be closed.
