### ISSUE TITLE
NPC's should stop wandering when players are interacting

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#709]
**Current behavior**: 
If an npc has a movement type of wander they continue to wander when a player interacts

**Expected behavior**: 
When they are being interacted with they should stop wandering

**Client version**: 
1.12.1
**Commit hash**: 
c89abc4
**Operating system**: 
Win 10

**Comment by ulfgebhardt** [comment]
@NickTyrer @ratkosrb I think this is fixed, right? The patrol in the Nelf Start area stops its movement when talked to. Additionally the two follower Patrols stop aswell.

**Comment by NickTyrer** [comment]
@ulfgebhardt the issue is when npc's have wander movement type not pathfinding

**Comment by ulfgebhardt** [comment]
Oh ok - my bad! I mistook wandering for pathing
