### ISSUE TITLE
Ranged Weapon: visual problem

### ISSUE THREAD

**Issue by alexkulya** [vmangos/core#71]
Faced with the problem of displaying ranged weapons in their hands.
Take the creature as an example: Sergeant Major Skyshadow (Entry: 12780).

Result with vmangos:
![screenshot_3](https://user-images.githubusercontent.com/7693165/49728855-eacd3600-fc84-11e8-8246-1d921802792d.png)
Result with wowhead classic:
[Link](https://classic.wowhead.com/npc=12780/sergeant-major-skyshadow)

Data from table 'creature_template_addon' is correct.
![screenshot_1](https://user-images.githubusercontent.com/7693165/49728997-47c8ec00-fc85-11e8-8a20-133ce01970d3.png)
Interrupting data from the table 'creature_addon' no.

The Equipment table 'creature_equip_template' is present.
![screenshot_2](https://user-images.githubusercontent.com/7693165/49729167-c0c84380-fc85-11e8-9e49-e63073c08b09.png)
And tied to the creature itself.

This problem is present in all creatures with the sheath flag '2'.

**Comment by ratkosrb** [comment]
Same issue seems to be present on cmangos too. Maybe classic client does not support showing ranged weapon slot on idle creatures? I made .npc info show the result of GetSheathe() and it shows as 2 for her, so the value gets set correctly server side.

**Comment by alexkulya** [comment]
It seems so. Client.

**Comment by Daribon** [comment]
It is likely that this function never existed in vanilla.
Appears to be something added in TBC.

From November 14, 2006:
![Image](https://vignette.wikia.nocookie.net/wowwiki/images/e/e9/Roon_Wildmane.jpg/revision/20100313163908)
From December 18, 2006 (patch 2.0.1):
![Image](https://wow.zamimg.com/uploads/screenshots/normal/9554-roon-wildmane.jpg)

August 15, 2006:
![wowscrnshot_081506_200150](https://user-images.githubusercontent.com/6137576/49825142-fd7a6480-fd83-11e8-81c8-c4c3934a815d.jpg)

August 23, 2009;
![Image](https://vignette.wikia.nocookie.net/wowwiki/images/5/59/Sergeant_Major_Skyshadow.jpg/revision/latest?cb=20090823223748)

Unknown date, vanilla:
![vanishian](https://user-images.githubusercontent.com/6137576/49824690-f010aa80-fd82-11e8-81b8-aa604983cace.jpg)

December 14, 2005:
![wowscrnshot_121405_083221](https://user-images.githubusercontent.com/6137576/49824809-37973680-fd83-11e8-9546-3e94061ed11f.png)

May 3, 2005:
![champhall1](https://user-images.githubusercontent.com/6137576/49824913-74632d80-fd83-11e8-9017-5705bdf086a9.jpg)

September 6, 2007:
![Image](https://wow.zamimg.com/uploads/screenshots/normal/50586-kaja.jpg)

May 31, 2006:
![Image](https://vignette.wikia.nocookie.net/wowwiki/images/b/bc/Kaja.jpg/revision/latest/scale-to-width-down/229?cb=20100819030328)

March 23, 2008:
![Image](https://wow.zamimg.com/uploads/screenshots/normal/76756-landria.jpg)

April 29, 2006:
![Image](https://vignette.wikia.nocookie.net/wowwiki/images/0/0c/Landria.jpg/revision/latest?cb=20060429070408)
