### ISSUE TITLE
Caer Darrow not blizzlike

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#710]
**Current behavior**: 
Here is a video for reference: https://youtu.be/kVNuVSdCJBg
could do with sniffing.
**Client version**: 
1.12.1
**Commit hash**: 
c89abc4
**Operating system**: 
Win 10

**Comment by Daribon** [comment]
Oh yeah, I looked into it and it appears all ghosts Caer Darrow has currently been spawned by hand on vmangos.
Not a single ghost spawn that requires Spectral Essence is spawned correctly.

**Comment by NickTyrer** [comment]
Yeh, missing mobs, waypoints, gossips and events. A few creatures have wrong faction and the ghosts are missing a blue aura. Def a negelcted area.

**Comment by ratkosrb** [comment]
Do you need a buff to see the ghosts and how to get it?

**Comment by NickTyrer** [comment]
You need the item spectral essence, a reward from the scholomance quest chain https://classic.wowhead.com/item=13544/spectral-essence#reward-from-q.
