### ISSUE TITLE
[Gossip] Orphan Matron Nightingale

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#712]
**Current behavior**: 
She opens a trade window
![gggh](https://user-images.githubusercontent.com/22723839/88461375-c4c8c980-ce9a-11ea-833c-56d46457d9fd.png)

**Expected behavior**: 
She should open a diologue window
![asddddd](https://user-images.githubusercontent.com/22723839/88461387-e6c24c00-ce9a-11ea-8b9b-cf630975ee2e.png)

**Client version**: 
1.12.1

**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
The items she sells were added in patch 1.11. Lets wait and see if she starts selling them in Phase 6.

**Comment by ratkosrb** [comment]
Noticed a comment for this npc, who sells the same things as her.
https://classicdb.ch/?npc=16543#comments

```
By Anonymous on 12/23/2006 (Patch 2.0.1)
What many people fail to notice is that, unless you got one of the letters, none of these people will sell you anything. They only offer their wares to those who turned in their appropriate letters to the Argent Dawn. I thought I had gotten all the letters, but I apparently missed Garon's, so he won't sell me anything. Nothing more than a task for completionists and a cute alternative to normal food/drink.
```

**Comment by ratkosrb** [comment]
Daribon discovered whats up with these npcs. There are letters that drop from the Scourge Invasion, and if you turn them in to these npcs, you can buy stuff from them.

https://wow.gamepedia.com/Friendship_Bread

**Comment by NickTyrer** [comment]
Phase 6 is live and her gossip is still the same atm,

**Comment by ratkosrb** [comment]
You have to do the quest from the letter to see the new gossip option.
