### ISSUE TITLE
Pink Murloc Egg is not from vanilla

### ISSUE THREAD

**Issue by ghost** [vmangos/core#714]
Pink Murloc Egg (with Gurky) is not from vanilla, but Gurky itself (as NPC near Garel Redrock) is.

[Wowpedia](https://wow.gamepedia.com/Pink_Murloc_Egg) and [retail Wowhead](https://www.wowhead.com/item=22114) say it was added in patch 2.1.0.

This egg, however, is available in [Classic Wowhead](https://classic.wowhead.com/item=22114/pink-murloc-egg), but this is most likely a bug since Gurky is Christmas 2006 pet and TBC was already released.

**Comment by GrenderG** [comment]
Not a bug. Not available for players != Not present in the database.

**Comment by ratkosrb** [comment]
We have the entire 1.12.0 item database because it was included in the Classic Blizzcon Demo's client files. We do not have any custom items in `item_template` that were not part of the client database.
