### ISSUE TITLE
Prevent GMs from creating guild or joining existing one by default

### ISSUE THREAD

**Issue by ghost** [vmangos/core#716]
**Current behavior**: GMs are not restricted from creating a guild or joining an existing one

**Expected behavior**: GMs should be restricted from doing this because they're not 'players'

**Steps to reproduce**:

1. Try to create a guild as GM
2. Try to join a guild as GM

**Client version**: any

**Commit hash**: c89abc4

**Operating system**: any

**Comment by GrenderG** [comment]
I don't see this as something useful to implement. **Maybe** implement the blocking of guild invites to GM characters from player accounts, but that's all.

**Comment by ratkosrb** [comment]
Not going to be implemented, seems like a pointless restriction.
