### ISSUE TITLE
GMs are able to use custom public channels

### ISSUE THREAD

**Issue by ghost** [vmangos/core#717]
**Current behavior**: GMs are not allowed to speak in default public channels but they can /join some channel and speak here

**Expected behavior**: GM should not be able to speak any public channels. Most likely this should also apply to /say, /emote and /yell.

**Steps to reproduce**:

1. Create account with non-player security level
2. /join some channel
3. Try to speak here

**Client version**: any

**Commit hash**: c89abc4

**Operating system**: any

**Comment by ratkosrb** [comment]
This is intentional design. Preventing GMs from speaking altogether is idiotic.
