### ISSUE TITLE
Are WOW_FAIL_INCORRECT_PASSWORD issues real?

### ISSUE THREAD

**Issue by ghost** [vmangos/core#719]
AuthCodes.h say WOW_FAIL_INCORRECT_PASSWORD is not used because client rejects next login attempts after its use.

However, I tested it on 1.6.1 and next login attempt with correct password was successful.

Why isn't WOW_FAIL_INCORRECT_PASSWORD used then? Comment below it should be fixed or removed.

**Comment by ratkosrb** [comment]
It causes non-vanilla clients to reject subsequent login attempts, and since the realmd is meant to work with tbc and wotlk clients too, we can't use that error message.
