### ISSUE TITLE
[Question/feature request; realmd] OS X patching

### ISSUE THREAD

**Issue by ghost** [vmangos/core#723]
VMaNGOS supports XFERring MPQ patches to client but they're currently same for both Windows and OS X (currently macOS).

Were such patches available for OS X? Were they different from Windows ones?

If yes, I am able to implement this by adding operating system to patch names (1234enUSWin.mpq/1234enUSOSX.mpq).

**Comment by ulfgebhardt** [comment]
Have you come across any more information regarding this @ghost ?

**Comment by Gamemechanicwow** [comment]
> Have you come across any more information regarding this @ghost ?

The ghost has stopped haunting us. Don't bring him back :>

**Comment by ratkosrb** [comment]
Ghosts are not welcome in this castle. May the holy light protect us from the wicked spirits.
