### ISSUE TITLE
Profession Trainers Bug

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#728]
**Current behavior**: 
You can access the training menu of many profession trainers.

**Expected behavior**: 
You should only be able to access the menu of expert, artisan and master trainers once you have a specified skill in that profession. (note: it is only worth implementing when a trainer has the correct gossip menu and not a placeholder).

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
I thought we fixed that issue already?

**Comment by NickTyrer** [comment]
No I only did alchemists, forgot about the other professions. Just posting it here to remind me to do the others at some point.
