### ISSUE TITLE
Apothecary Keever OOC Event

### ISSUE THREAD

**Issue by alexkulya** [vmangos/core#74]
Add OOC event for creature - Apothecary Keever (Entry: 5734)
Add Random OOC Emotes for creatures: Caged Human Female & Caged Dwarf Male

<pre>
-- Apothecary Keever
DELETE FROM `creature` WHERE `guid` = 45216 AND `id` = 5739;
DELETE FROM `creature` WHERE `guid` = 45218 AND `id` = 5736;
DELETE FROM `creature_addon` WHERE `guid` IN (45216, 45218);

DELETE FROM `creature_ai_events` WHERE `creature_id` = 5734;
INSERT INTO `creature_ai_events` (`id`, `creature_id`, `condition_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_script`, `action2_script`, `action3_script`, `comment`) VALUES
(573401, 5734, 0, 4, 0, 100, 0, 0, 0, 0, 0, 573401, 0, 0, 'Apothecary Keever - Summon Deathguard Elite on Aggro'),
(573402, 5734, 0, 1, 0, 100, 1, 0, 0, 240000, 240000, 573402, 0, 0, 'Apothecary Keever - OOC Event Say Text & Stand'),
(573403, 5734, 0, 1, 0, 100, 1, 3000, 3000, 240000, 240000, 573403, 0, 0, 'Apothecary Keever - OOC Event Cast Spell'),
(573404, 5734, 0, 1, 0, 100, 1, 6000, 6000, 240000, 240000, 573404, 0, 0, 'Apothecary Keever - OOC Event Kneel & Spawn Creature'),
(573405, 5734, 0, 1, 0, 100, 1, 9000, 9000, 240000, 240000, 573405, 0, 0, 'Apothecary Keever - OOC Event Stand'),
(573406, 5734, 0, 1, 0, 100, 1, 12000, 12000, 240000, 240000, 573406, 0, 0, 'Apothecary Keever - OOC Event Say Text'),
(573407, 5734, 0, 1, 0, 100, 1, 21000, 21000, 240000, 240000, 573407, 0, 0, 'Apothecary Keever - OOC Event Say Text & Kneel'),
(573408, 5734, 0, 1, 0, 100, 1, 23000, 23000, 240000, 240000, 573408, 0, 0, 'Apothecary Keever - OOC Event Update Entry'),
(573409, 5734, 0, 1, 0, 100, 1, 32000, 32000, 240000, 240000, 573409, 0, 0, 'Apothecary Keever - OOC Event Say Text'),
(573410, 5734, 0, 1, 0, 100, 1, 45000, 45000, 240000, 240000, 573410, 0, 0, 'Apothecary Keever - OOC Event Say Text'),
(573411, 5734, 0, 1, 0, 100, 1, 46000, 46000, 240000, 240000, 573411, 0, 0, 'Apothecary Keever - OOC Event Stand'),
(573412, 5734, 0, 1, 0, 100, 1, 54000, 54000, 240000, 240000, 573412, 0, 0, 'Apothecary Keever - OOC Event Say Text & Kneel'),
(573413, 5734, 0, 1, 0, 100, 1, 56000, 56000, 240000, 240000, 573413, 0, 0, 'Apothecary Keever - OOC Event Update Entry'),
(573414, 5734, 0, 1, 0, 100, 1, 60000, 60000, 240000, 240000, 573414, 0, 0, 'Apothecary Keever - OOC Event Say Text'),
(573415, 5734, 0, 1, 0, 100, 1, 73000, 73000, 240000, 240000, 573415, 0, 0, 'Apothecary Keever - OOC Event Say Text'),
(573416, 5734, 0, 1, 0, 100, 1, 74000, 74000, 240000, 240000, 573416, 0, 0, 'Apothecary Keever - OOC Event Stand'),
(573417, 5734, 0, 1, 0, 100, 1, 82000, 82000, 240000, 240000, 573417, 0, 0, 'Apothecary Keever - OOC Event Say Text & Kneel'),
(573418, 5734, 0, 1, 0, 100, 1, 86000, 86000, 240000, 240000, 573418, 0, 0, 'Apothecary Keever - OOC Event Update Entry'),
(573419, 5734, 0, 1, 0, 100, 1, 95000, 95000, 240000, 240000, 573419, 0, 0, 'Apothecary Keever - OOC Event Say Text'),
(573420, 5734, 0, 1, 0, 100, 1, 108000, 108000, 240000, 240000, 573420, 0, 0, 'Apothecary Keever - OOC Event Say Text'),
(573421, 5734, 0, 1, 0, 100, 1, 109000, 109000, 240000, 240000, 573421, 0, 0, 'Apothecary Keever - OOC Event Stand'),
(573422, 5734, 0, 1, 0, 100, 1, 117000, 117000, 240000, 240000, 573422, 0, 0, 'Apothecary Keever - OOC Event Say Text & Kneel'),
(573423, 5734, 0, 1, 0, 100, 1, 121000, 121000, 240000, 240000, 573423, 0, 0, 'Apothecary Keever - OOC Event Update Entry'),
(573424, 5734, 0, 1, 0, 100, 1, 130000, 130000, 240000, 240000, 573424, 0, 0, 'Apothecary Keever - OOC Event Say Text'),
(573425, 5734, 0, 1, 0, 100, 1, 131000, 131000, 240000, 240000, 573425, 0, 0, 'Apothecary Keever - OOC Event Stand'),
(573426, 5734, 0, 1, 0, 100, 1, 143000, 143000, 240000, 240000, 573426, 0, 0, 'Apothecary Keever - OOC Event Say Text & Kneel'),
(573427, 5734, 0, 1, 0, 100, 1, 147000, 147000, 240000, 240000, 573427, 0, 0, 'Apothecary Keever - OOC Event Cast Spell'),
(573428, 5734, 0, 1, 0, 100, 1, 148000, 148000, 240000, 240000, 573428, 0, 0, 'Apothecary Keever - OOC Event Despawn'),
(573429, 5734, 0, 1, 0, 100, 1, 151000, 151000, 240000, 240000, 573429, 0, 0, 'Apothecary Keever - OOC Event Say Text'),
(573430, 5734, 0, 1, 0, 100, 1, 152000, 152000, 240000, 240000, 573430, 0, 0, 'Apothecary Keever - OOC Event Stand'),
(3001553, 5734, 458, 10, 0, 100, 1, 1, 50, 3000, 3000, 3001553, 0, 0, 'Love is in the Air Event - Cast Love aura and turn on gossip NPC\_FLAG');

DELETE FROM `creature_ai_scripts` WHERE `id` BETWEEN 573402 AND 573430;
INSERT INTO `creature_ai_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `target_param1`, `target_param2`, `target_type`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `condition_id`, `comments`) VALUES
(573402, 0, 2, 138, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Stand'),
(573402, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2061, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573403, 0, 15, 7794, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Cast Spell \'Teleport\''),
(573404, 0, 2, 138, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Kneel'),
(573404, 0, 10, 5736, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 5, 1400.85, 363.242, -84.868, 1.11701, 0, 'Apothecary Keever - Spawn Creature \'Caged Human Male\''),
(573405, 0, 2, 138, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Stand'),
(573406, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2062, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573407, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2075, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573407, 0, 2, 138, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Kneel'),
(573408, 0, 27, 5742, 1, 0, 0, 5736, 2, 8, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Update Entry (Creature Entry: 5736)'),
(573409, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2064, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573410, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2063, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573411, 0, 2, 138, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Stand'),
(573412, 0, 2, 138, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Kneel'),
(573412, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2065, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573413, 0, 27, 5739, 1, 0, 0, 5742, 2, 8, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Update Entry (Creature Entry: 5742)'),
(573414, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2066, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573415, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2067, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573416, 0, 2, 138, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Stand'),
(573417, 0, 2, 138, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Kneel'),
(573417, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2068, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573418, 0, 27, 5741, 1, 0, 0, 5739, 2, 8, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Update Entry (Creature Entry: 5739)'),
(573419, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2069, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573420, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2070, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573421, 0, 2, 138, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Stand'),
(573422, 0, 2, 138, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Kneel'),
(573422, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2071, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573423, 0, 27, 5743, 1, 0, 0, 5741, 2, 8, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Update Entry (Creature Entry: 5741)'),
(573424, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2072, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573425, 0, 2, 138, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Stand'),
(573426, 0, 2, 138, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Kneel'),
(573426, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2073, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573427, 0, 15, 7670, 6, 0, 0, 5743, 2, 8, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Cast Spell \'Explode\' (Creature Entry: 5743)'),
(573428, 0, 18, 0, 0, 0, 0, 5743, 2, 8, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Despawn (Creature Entry: 5743)'),
(573429, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2074, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573430, 0, 2, 138, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Stand');

UPDATE `broadcast_text` SET `EmoteId0` = 1 WHERE `ID` IN (2061, 2062, 2063, 2067, 2070, 2072);
UPDATE `broadcast_text` SET `EmoteId0` = 11 WHERE `ID` = 2074;

-- Caged Human Female
DELETE FROM `creature_ai_scripts` WHERE `id` = 573501;
INSERT INTO `creature_ai_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `target_param1`, `target_param2`, `target_type`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `condition_id`, `comments`) VALUES
(573501, 0, 1, 18, 0, 0, 0, 0, 0, 0, 0, 20, 1, 0, 0, 0, 0, 0, 0, 0, 'Caged Human Female - Random Emote');

-- Caged Dwarf Male
UPDATE `creature_template` SET `AIName` = "EventAI" WHERE `entry` = 5738;
DELETE FROM `creature_ai_events` WHERE `creature_id` = 5738;
INSERT INTO `creature_ai_events` (`id`, `creature_id`, `condition_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_script`, `action2_script`, `action3_script`, `comment`) VALUES
(573801, 5738, 0, 1, 0, 100, 1, 6000, 13000, 29000, 45000, 573801, 0, 0, 'Caged Dwarf Male - Random Emotes');
DELETE FROM `creature_ai_scripts` WHERE `id` = 573801;
INSERT INTO `creature_ai_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `target_param1`, `target_param2`, `target_type`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `condition_id`, `comments`) VALUES
(573801, 0, 1, 18, 0, 0, 0, 0, 0, 0, 0, 20, 1, 0, 0, 0, 0, 0, 0, 0, 'Caged Dwarf Male - Random Emote');
</pre>

**Comment by ratkosrb** [comment]
If you added all these OOC EventAI events with a slightly longer initial delay because the script that should play should have multiple delayed action, then you should use an `event_script` instead and start that with SCRIPT_COMMAND_START_SCRIPT from a single EventAI OOC event.

**Comment by ratkosrb** [comment]
![script_example](https://user-images.githubusercontent.com/35845488/49912558-2fc6b780-fe93-11e8-9aeb-7e8881f53442.jpg)

**Comment by alexkulya** [comment]
Rewrited

<pre>
-- Apothecary Keever
DELETE FROM `creature` WHERE `guid` = 45216 AND `id` = 5739;
DELETE FROM `creature` WHERE `guid` = 45218 AND `id` = 5736;
DELETE FROM `creature_addon` WHERE `guid` IN (45216, 45218);

DELETE FROM `creature_ai_events` WHERE `creature_id` = 5734;
INSERT INTO `creature_ai_events` (`id`, `creature_id`, `condition_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_script`, `action2_script`, `action3_script`, `comment`) VALUES
(573401, 5734, 0, 4, 0, 100, 0, 0, 0, 0, 0, 573401, 0, 0, 'Apothecary Keever - Summon Deathguard Elite on Aggro'),
(573402, 5734, 0, 1, 0, 100, 1, 0, 0, 240000, 240000, 573402, 0, 0, 'Apothecary Keever - Start OOC Event'),
(3001553, 5734, 458, 10, 0, 100, 1, 1, 50, 3000, 3000, 3001553, 0, 0, 'Love is in the Air Event - Cast Love aura and turn on gossip NPC\_FLAG');

DELETE FROM `creature_ai_scripts` WHERE `id` = 573402;
INSERT INTO `creature_ai_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `target_param1`, `target_param2`, `target_type`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `condition_id`, `comments`) VALUES
(573402, 0, 39, 573402, 0, 0, 0, 0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Start OOC Event');

DELETE FROM `event_scripts` WHERE `id` = 573402;
INSERT INTO `event_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `target_param1`, `target_param2`, `target_type`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `condition_id`, `comments`) VALUES
(573402, 0, 2, 138, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Stand'),
(573402, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2061, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573402, 3, 15, 7794, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Cast Spell \'Teleport\''),
(573402, 6, 2, 138, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Kneel'),
(573402, 6, 10, 5736, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 5, 1400.85, 363.242, -84.868, 1.11701, 0, 'Apothecary Keever - Spawn Creature \'Caged Human Male\''),
(573402, 9, 2, 138, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Stand'),
(573402, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2062, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573402, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2075, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573402, 21, 2, 138, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Kneel'),
(573402, 23, 27, 5742, 1, 0, 0, 5736, 2, 8, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Update Entry (Creature Entry: 5736)'),
(573402, 32, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2064, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573402, 45, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2063, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573402, 46, 2, 138, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Stand'),
(573402, 54, 2, 138, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Kneel'),
(573402, 54, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2065, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573402, 56, 27, 5739, 1, 0, 0, 5742, 2, 8, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Update Entry (Creature Entry: 5742)'),
(573402, 60, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2066, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573402, 73, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2067, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573402, 74, 2, 138, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Stand'),
(573402, 82, 2, 138, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Kneel'),
(573402, 82, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2068, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573402, 86, 27, 5741, 1, 0, 0, 5739, 2, 8, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Update Entry (Creature Entry: 5739)'),
(573402, 95, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2069, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573402, 108, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2070, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573402, 109, 2, 138, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Stand'),
(573402, 117, 2, 138, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Kneel'),
(573402, 117, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2071, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573402, 121, 27, 5743, 1, 0, 0, 5741, 2, 8, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Update Entry (Creature Entry: 5741)'),
(573402, 130, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2072, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573402, 131, 2, 138, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Stand'),
(573402, 143, 2, 138, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Kneel'),
(573402, 143, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2073, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573402, 147, 15, 7670, 6, 0, 0, 5743, 2, 8, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Cast Spell \'Explode\' (Creature Entry: 5743)'),
(573402, 148, 18, 0, 0, 0, 0, 5743, 2, 8, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Despawn (Creature Entry: 5743)'),
(573402, 151, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2074, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Say Text'),
(573402, 152, 2, 138, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Apothecary Keever - Stand');

UPDATE broadcast_text SET EmoteId0 = 1 WHERE ID IN (2061, 2062, 2063, 2067, 2070, 2072);
UPDATE broadcast_text SET EmoteId0 = 11 WHERE ID = 2074;

-- Caged Human Female
DELETE FROM `creature_ai_scripts` WHERE `id` = 573501;
INSERT INTO `creature_ai_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `target_param1`, `target_param2`, `target_type`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `condition_id`, `comments`) VALUES
(573501, 0, 1, 18, 0, 0, 0, 0, 0, 0, 0, 20, 1, 0, 0, 0, 0, 0, 0, 0, 'Caged Human Female - Random Emote');

-- Caged Dwarf Male
UPDATE `creature_template` SET `AIName` = "EventAI" WHERE `entry` = 5738;
DELETE FROM `creature_ai_events` WHERE `creature_id` = 5738;
INSERT INTO `creature_ai_events` (`id`, `creature_id`, `condition_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action1_script`, `action2_script`, `action3_script`, `comment`) VALUES
(573801, 5738, 0, 1, 0, 100, 1, 6000, 13000, 29000, 45000, 573801, 0, 0, 'Caged Dwarf Male - Random Emotes');
DELETE FROM `creature_ai_scripts` WHERE `id` = 573801;
INSERT INTO `creature_ai_scripts` (`id`, `delay`, `command`, `datalong`, `datalong2`, `datalong3`, `datalong4`, `target_param1`, `target_param2`, `target_type`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `condition_id`, `comments`) VALUES
(573801, 0, 1, 18, 0, 0, 0, 0, 0, 0, 0, 20, 1, 0, 0, 0, 0, 0, 0, 0, 'Caged Dwarf Male - Random Emote');
</pre>
