### ISSUE TITLE
Implement blizzlike sub-servers #2

### ISSUE THREAD

**Issue by Simplaf234-ghost** [vmangos/core#747]
Just a duplicate of #741 if you don't like deleted accounts. Then I will just leave my account and most likely never return because I decided to quit World of Warcraft.

If duplicated issue was closed for other reason, please comment it before closing.

---

**Current behavior**:

>  …the core is built very differently than blizzard's servers… We have a standalone realm server that runs all of the maps and manages the whole world and all characters by itself, and does not interact with other realms in any way.

**Expected behavior**:

> They [Blizzard] are able to run individual maps on a separate server, and these map servers are able to talk to each other so that the player can be smoothly transferred from one server to the other, which is what makes the cross realm battlegrounds possible. Even the character selection screen is a separate entity that runs independently of the actual world.

**Commit hash**: [c89abc4](https://github.com/vmangos/core/commit/c89abc4f026f0cd13919d10443b22d512adb3e4f)

**Source**: #722

**Comment by Gamemechanicwow** [comment]
In my opinion it was closed because it was dumb. There is no reason to implement it.

Like most of the issues you posted, you seem to missinterpret blizzlike as blizzclone.

**Comment by Simplaf234-ghost** [comment]
Do I really _misinterpret_ it? How are blizzlike and blizzclone different?

**Comment by ratkosrb** [comment]
It was closed because it was an useless issue. The whole project would have to be remade, and nobody is going to do that. All currently active wow server emulation projects are descendent from mangos and inherit this standalone realm design. Go start your own project from scratch and design it with individual map servers in mind if you are so obsessed with the topic.
