### ISSUE TITLE
run mangosd and realmd faild,looks sql problem but i dont know how fix it,please help me.

### ISSUE THREAD

**Issue by chenps10** [vmangos/core#75]
Database `world` is missing the following migrations:
        20181118215622
        20181119025556
        20181124131732
        20181129085153
        20181130092710
        20181130093715
        20181204124508
        20181204141631
        20181204152456
        20181205145532
        20181205151128
        20181205153049
        20181205160926
        20181205161158
        20181206122951
        20181206123749
        20181206124915
        20181206125450
        20181206131938
        20181206182045
        20181207174430
        20181207180315
        20181209183704
        20181209184505

**Comment by chenps10** [comment]
i do try to run the *.sql in migrations but it is error

**Comment by ratkosrb** [comment]
I am not getting any errors, make sure you are applying them to the newest world db.
https://github.com/brotalnia/database/blob/master/world_full_26_august_2018.7z

**Comment by chenps10** [comment]
yes,i use  this db,i use centos linux and compiling from this git

**Comment by ratkosrb** [comment]
1. Delete database `mangos`.
2. Make it again.
3. Run world_full_26_august_2018 on it.
4. Go to sql/migrations folder and run merge.sh.
5. Run the newly created world_db_updates.sql file on the `mangos` database.

**Comment by chenps10** [comment]
ok,i try,no matter what,just very thank you

**Comment by chenps10** [comment]
it works! thank you very mach.an on more thing:my centos firewall open 8085 and 3724 port but always can't logon game?what port else should i open?

**Comment by chenps10** [comment]
i fix it，ok now。thanks agan
