### ISSUE TITLE
[Quest] Guardians of the Altar

### ISSUE THREAD

**Issue by mikemenasi** [vmangos/core#756]
**Current behavior**: 
The npc (Ranshalla) doesn't get attacked nor does she attacks mobs. 
The quest can't be completed because you can't interact with the altar at the end
**Expected behavior**: 
see: https://forum.gurubashi.org/viewtopic.php?f=31&t=97

**Client version**: 
1.2
**Commit hash**: 
c464712
**Operating system**: 
Windows

**Comment by ratkosrb** [comment]
She is not supposed to aggro mobs on her own. She only fights if the mob attacks her first. She will not assist if the player is attacked first. I know because I did this quest on Classic a week ago and this is how it worked.

**Comment by ulfgebhardt** [comment]
So this leaves the second Issue mentioned here:
`The quest can't be completed because you can't interact with the altar at the end`

**Comment by Gamemechanicwow** [comment]
just took her for a walk..

> She only fights if the mob attacks her first.

To avoid any misunderstanding. She should be attacked by mobs in range? Currently the mobs ignore her.

>The quest can't be completed because you can't interact with the altar at the end

I had no issues interacting with the altar.
