### ISSUE TITLE
[Quest] Watcher Callahan

### ISSUE THREAD

**Issue by mikemenasi** [vmangos/core#757]
**Current behavior**: 
"Watcher Callahan" (236) seems to not work properly

**Expected behavior**: 
see: https://forum.gurubashi.org/viewtopic.php?f=31&t=88

**Client version**: 
1.2
**Commit hash**: 
c464712
**Operating system**: 
Windows

**Comment by ratkosrb** [comment]
I don't see how it can be done twice. The end texts for both is missing and I don't know where we can find it, because both quests were removed in patch 1.4 and the ids were reused for Children's Week quests.

**Comment by NickTyrer** [comment]
According to https://web.archive.org/web/20040706014742/http://wow.allakhazam.com/db/quest.html?wquest=236 the quest was called Awaiting Word. Don't know if that makes any difference?

**Comment by ratkosrb** [comment]
Nice catch, corrected it.
