### ISSUE TITLE
[Spell] Water Walking Bug

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#759]
**Current behavior**: 
The buff applied by the Shaman spell Water Walking should be removed when ghost wolf is cast. Currently it isnt removed
https://youtu.be/LbW_KFe6q6I

**Expected behavior**: 
classic:
https://youtu.be/hy5ag078BdY

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
Can you test if you can cast water walking on players who are mounted and on shapeshifted druids.

**Comment by NickTyrer** [comment]
Note: does this bug effect the spell Levitate?

**Comment by ratkosrb** [comment]
Levitate is a self cast spell.
