### ISSUE TITLE
Characters cannot die

### ISSUE THREAD

**Issue by ghost** [vmangos/core#761]
**Current behavior**: 

So, I've had a vmangos core for about a year.  I built from scratch, imported the database from scratch, all is well.  Then about a month ago something odd happened; one of my chars was being hammered by a level ?? horde town protector grunt and he should have died, but didn't.

Then a day or two ago, when I made a new char to experiment with something, I noticed this char could not die.  So to be exact : I make a new dwarf, run down into the wolves, pull a bunch of them by hitting them with the axe, and then let them hit me.  My health gets down to 2 (two), but I simply don't die.

**Expected behavior**: 

Death!

**Steps to reproduce**:

1. Make a dwarf
2. Pull lots of mobs
3. Wait

**Client version**: 

1.12.1

**Commit hash**: 

Sorry - no clue - I did a successful "git pull --rebase" on 2020-08-08.

**Operating system**: 

Debian 10.

**Screenshots**:

A brand-new dwarf.

![WoWScrnShot_081020_193023](https://user-images.githubusercontent.com/69477744/89813320-caccd480-db41-11ea-8ad7-7e82f6e281e3.png)

An immortal dwarf.

![WoWScrnShot_081020_193105](https://user-images.githubusercontent.com/69477744/89813372-dcae7780-db41-11ea-89e8-497cab6f8a54.png)

**Comment by ratkosrb** [comment]
You have god mode enabled. Type this in chat:
.cheat god off

**Comment by ratkosrb** [comment]
You have god mode enabled. Type this in chat:
.cheat god off

**Comment by ratkosrb** [comment]
You have god mode enabled. Type this in chat:
.cheat god off

**Comment by ratkosrb** [comment]
You have god mode enabled. Type this in chat:
.cheat god off

**Comment by ratkosrb** [comment]
You have god mode enabled. Type this in chat:
.cheat god off

**Comment by ratkosrb** [comment]
You have god mode enabled. Type this in chat:
.cheat god off

**Comment by ratkosrb** [comment]
You have god mode enabled. Type this in chat:
.cheat god off

**Comment by ghost** [comment]
Good grief - yes, it is god mode, and turning it off solved the problem.

However, and I need to be *absolutely* clear about this - I have never, NOT ONCE, turned on God mode.

I've not known until know even HOW to turn on God mode!

**Comment by ratkosrb** [comment]
God mode is enabled by default when playing on a GM account. You need to manually turn it off every time you login.

**Comment by ghost** [comment]
Holy cow...

But I'm certain I've had character die before now, and I've never turned God mode off.

Anyways, I'll close this issue now.

Thankyou very much for your help!

**Comment by ratkosrb** [comment]
You can die if you use .die on yourself. That will turn off god mode.
