### ISSUE TITLE
[Gossip] NPC Argent Quartermaster Hasana

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#762]
**Current behavior**: 
She is not offering the dialogue option to aquire another Argent Dawn Commission (note: the corresponding alliance npc may also be missing this option).

**Expected behavior**: 
![asdasd](https://user-images.githubusercontent.com/22723839/89922242-ac74e080-dbf6-11ea-8c9d-e4ec697ec92b.png)

**Client version**: 
1.12.1
**Commit hash**: 
9eef1bd
**Operating system**: 
Win 10

**Comment by Daribon** [comment]
I think Brotalia has tons of gossip data that he is waiting to commit.

**Comment by NickTyrer** [comment]
She now has the gossip option however, clicking the option does nothing. The corresponding alliance quartermaster, Argent Quartermaster Lightspark's gossip is working correctly.
