### ISSUE TITLE
[Gossip] Strange Fronded Plant

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#764]
**Current behavior**: 
The plant has the wrong gossip 
![ccvx](https://user-images.githubusercontent.com/22723839/89943493-32545400-dc16-11ea-803d-1b04b095a255.png)

**Expected behavior**: 
![dfdd](https://user-images.githubusercontent.com/22723839/89943515-3aac8f00-dc16-11ea-846f-67bb199a6e64.png)

**Client version**: 
1.12.1
**Commit hash**: 
9eef1bd
**Operating system**: 
Win 10

**Comment by alexkulya** [comment]
<pre>
-- Object ID: 6752 - add gossip text
DELETE FROM `gossip_menu` WHERE `entry` = 542 AND `text_id` = 1059;
INSERT INTO `gossip_menu` (`entry`, `text_id`, `condition_id`) VALUES
(542, 1059, 0);

-- Object ID: 6751 - add gossip text
DELETE FROM `gossip_menu` WHERE `entry` = 543 AND `text_id` = 1060;
INSERT INTO `gossip_menu` (`entry`, `text_id`, `condition_id`) VALUES
(543, 1060, 0);
</pre>

**Comment by NickTyrer** [comment]
@alexkulya Thanks added to #763.

**Comment by alexkulya** [comment]
@NickTyrer No problem.
