### ISSUE TITLE
Line of Sight Bug

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#769]
**Current behavior**: 
You can access various things through walls:
vmangos: https://youtu.be/SoHrYYuStKk

**Expected behavior**: 
They should not be accessible:
classic: https://youtu.be/dxMJFJYRcAk

**Client version**: 
1.12.1
**Commit hash**: 
4c57295
**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
The mouse cursor changing is a difference in how the clients work.

**Comment by NickTyrer** [comment]
ok, closing
