### ISSUE TITLE
how many is the maximum number of guilds ?and  how to change it?

### ISSUE THREAD

**Issue by chenps10** [vmangos/core#77]
i run it whit my server for our people and now our members is rapid growth。
so，I have a question in mind.
how many is the maximum number of guilds ?
and  how to change it?

Thank you for your patient advice.

**Comment by ratkosrb** [comment]
There is no limit on how many guilds can exist, but there is a limit on 321 players per guild. I think the limit exists to prevent the guild roster from bugging out in the client.

https://github.com/vmangos/core/blob/development/src/game/Guild/Guild.h#L43

**Comment by chenps10** [comment]
ok,tks for answer,
