### ISSUE TITLE
[BUG] Thaddius script is not completely working 

### ISSUE THREAD

**Issue by eugeniosegala** [vmangos/core#770]
**Current behavior**: 
After killing Feugen and Stalagg, Thaddius does not activate.

**Expected behavior**: 
After killing Feugen and Stalagg, Thaddius activates and the fight begins.

**Steps to reproduce**:

1. Kill  Feugen and Stalagg at the same time.
2. Jump into the Thaddius area and the fight should begin.

**Client version**: 
1.12.1

**Operating system**: 
Windows/Mac

**Comment by alexkulya** [comment]
The instance is fully working. Taddius for effect needs to be killed as part of a group, not alone.

**Comment by eugeniosegala** [comment]
I tried alone and with a group of 2 players (still not working), but I'll give it another try, just to be sure. I was checking the code and I saw several commented line inside multiple phases of the fight. I'll try to perform some tests. Thanks.

**Comment by Gamemechanicwow** [comment]
The script intercepts a killing blow, and makes the add appear dead. 
If you kill an add with a gm command, that part of the script wont be executed.

**Comment by ratkosrb** [comment]
The script works. Stop using gm accounts or commands. Do it in a raid group with normal accounts and no cheats, and things will work correctly.
