### ISSUE TITLE
[Quest] The Only Prescription

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#778]
**Current behavior**: 
The wrong item is looted from the library in Stormwind 
![image](https://user-images.githubusercontent.com/22723839/91639852-559e4200-ea11-11ea-9406-38ff282bedb4.png)

**Expected behavior**: 
Item "Draconic for Dummies chapter 5" should be looted from Stormwind Library not chapter 7
See: https://classic.wowhead.com/quest=8620/the-only-prescription#comments

**Client version**: 
1.12.1
**Commit hash**: 
cd74c2c
**Operating system**: 
Win 10

**Comment by schell244** [comment]
Confirmend with 16902fe. Chapter 7 and Chapter 5 should be switched.
Stormwind Library : currently chater 7  -> should be chapter 5
BWL: currently chapter 5 -> should be chapter 7

https://classic.wowhead.com/item=21107/draconic-for-dummies
https://classic.wowhead.com/item=21109/draconic-for-dummies
