### ISSUE TITLE
The server crashed after attacking Ragnaros for a period of time.

### ISSUE THREAD

**Issue by wowspy9527** [vmangos/core#789]
molten_core Ragnaros

2020-09-08 11:09:01 Next game event check in 120 seconds.
2020-09-08 11:10:52 ERROR:[MoltenCore.Ragnaros] Magma Blast failed with reason <1>.
2020-09-08 11:10:52 ERROR:[MoltenCore.Ragnaros] Magma Blast failed with reason <1>.
2020-09-08 11:11:00 Next game event check in 121 seconds.

**Client version**: 
1.12.1
**Commit hash**: 
0cc5c1d8b2f0c04f3431f60bdd0e3a6b1408ff99
**Operating system**: 
win10 ltsb

**Comment by Kittnz** [comment]
We need a crash log for this one.

**Comment by wowspy9527** [comment]
> We need a crash log for this one.

Where can i find it？I just found server.log~

**Comment by wowspy9527** [comment]
![456](https://user-images.githubusercontent.com/70317238/92683901-bcebb880-f366-11ea-81db-157499919696.png)

**Comment by ratkosrb** [comment]
You need to compile core in Debug mode, then when it crashes you press the option to Debug in Visual Studio, and you show us the call stack window at the bottom.

**Comment by wowspy9527** [comment]
![123](https://user-images.githubusercontent.com/70317238/92688734-726f3980-f370-11ea-8f89-1654ce8255a8.png)

**Comment by wowspy9527** [comment]
>	mangosd.exe!Object::GetTypeId() 行 345	C++
 	mangosd.exe!boss_ragnarosAI::CheckForMelee() 行 565	C++
 	mangosd.exe!boss_ragnarosAI::UpdateAI(const unsigned int diff) 行 517	C++
 	mangosd.exe!Creature::Update(unsigned int update_diff, unsigned int diff) 行 880	C++
 	mangosd.exe!TemporarySummon::Update(unsigned int update_diff, unsigned int diff) 行 203	C++
 	mangosd.exe!WorldObject::UpdateHelper::UpdateRealTime(unsigned int now, unsigned int time_diff) 行 718	C++
 	mangosd.exe!MaNGOS::ObjectUpdater::Visit(GridRefManager<Creature> & m) 行 55	C++
 	mangosd.exe!VisitorHelper<MaNGOS::ObjectUpdater,Creature>(MaNGOS::ObjectUpdater & v, ContainerMapList<Creature> & c) 行 54	C++
 	mangosd.exe!VisitorHelper<MaNGOS::ObjectUpdater,Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > >(MaNGOS::ObjectUpdater & v, ContainerMapList<TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > & c) 行 61	C++
 	mangosd.exe!VisitorHelper<MaNGOS::ObjectUpdater,GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > >(MaNGOS::ObjectUpdater & v, ContainerMapList<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > & c) 行 62	C++
 	mangosd.exe!VisitorHelper<MaNGOS::ObjectUpdater,TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > >(MaNGOS::ObjectUpdater & v, TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > & c) 行 69	C++
 	mangosd.exe!TypeContainerVisitor<MaNGOS::ObjectUpdater,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > >::Visit(TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > & c) 行 84	C++
 	mangosd.exe!Grid<Player,TypeList<Player,TypeList<Creature,TypeList<Corpse,TypeList<Camera,TypeNull> > > >,TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > >::Visit<MaNGOS::ObjectUpdater>(TypeContainerVisitor<MaNGOS::ObjectUpdater,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > > & visitor) 行 84	C++
 	mangosd.exe!NGrid<16,Player,TypeList<Player,TypeList<Creature,TypeList<Corpse,TypeList<Camera,TypeNull> > > >,TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > >::Visit<MaNGOS::ObjectUpdater,TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > >(const unsigned int & x, const unsigned int & y, TypeContainerVisitor<MaNGOS::ObjectUpdater,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > > & visitor) 行 160	C++
 	mangosd.exe!Map::Visit<MaNGOS::ObjectUpdater,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > >(const Cell & cell, TypeContainerVisitor<MaNGOS::ObjectUpdater,TypeMapContainer<TypeList<GameObject,TypeList<Creature,TypeList<DynamicObject,TypeList<Corpse,TypeNull> > > > > > & visitor) 行 1097	C++
 	mangosd.exe!Map::UpdateCellsAroundObject(unsigned int now, unsigned int diff, const WorldObject * object) 行 612	C++
 	mangosd.exe!Map::UpdateActiveCellsSynch(unsigned int now, unsigned int diff) 行 725	C++
 	mangosd.exe!Map::UpdateCells(unsigned int map_diff) 行 775	C++
 	mangosd.exe!Map::Update(unsigned int t_diff) 行 894	C++
 	mangosd.exe!DungeonMap::Update(unsigned int t_diff) 行 2146	C++
 	mangosd.exe!Map::DoUpdate(unsigned int maxDiff) 行 865	C++
 	mangosd.exe!MapAsyncUpdater::run() 行 254	C++
 	mangosd.exe!ACE_Based::Thread::ThreadTask(void * param) 行 200	C++
 	[外部代码]

**Comment by ratkosrb** [comment]
Should be fixed now.
