### ISSUE TITLE
Dranei and Blood Elves are included in allowable_race

### ISSUE THREAD

**Issue by mikemenasi** [vmangos/core#790]
**Current behavior**: 
SELECT * FROM item_template WHERE allowable_race IN (1101, 690) hows results 

**Expected behavior**: 
Dranei and Blood Elves should not be set in this field.
see: 
https://github.com/mangoszero/database/commit/a6568eab7f915ad5540df3aa9538ec18c743c1a4
https://github.com/mangoszero/database/commit/807ee67c1bf0f1583b1cf68374ceca4421728583

**Client version**: 
1.12.1
**Commit hash**: 
150d3d7
**Operating system**: 
Windows 10

**Comment by ratkosrb** [comment]
Those values come from the Classic's ItemSparse.db2, so we are not changing this. Do not suggest changes that contradict the client db.
https://wow.tools/dbc/?dbc=itemsparse&build=1.13.5.35753#page=1&search=1041
