### ISSUE TITLE
[Talent] Preist Talent Mental Agility

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#792]
**Current behavior**: 
The talent isnt reducing the mana cost of instant cast spells

**Client version**: 
1.12.1
**Commit hash**: 
150d3d7
**Operating system**: 
Win 10

**Comment by T1ti** [comment]
The effectitemtype1 for mental agiltiy in spell_template DB is wrong.
In DBC it is 2185347403 which should affect 
- 1
- 2
- 4
- 7
- 9
- 15
- 16
- 17
- 23
- 26
- 32

But in the DB it is 2147483648 which only returns 32.
