### ISSUE TITLE
Missing mob leash behavior

### ISSUE THREAD

**Issue by rosen40** [vmangos/core#793]
**Expected behavior**: On Classic when you aggro a mob there is about 1.5 seconds delay before other nearby mobs also start attacking you. When this happens, all of the mobs that you aggroed at the same time become "linked" and now hitting even only 1 of them updates the leash range on ALL of them. This does not happen on vmangos at all. I have recorded videos on both Classic and Vmangos demostrating the differences.

**Current behavior**:  On vmangos if you aggro multiple mobs at the same time you can hit only 1 mob and run away and eventually other mobs will unleash and reset and you will remain in combat only with the mob that you are hitting which NEVER would happen on classic (granted you did actually pull the mobs at the same time).

This is a MAJOR missing feature and nerfs the whole game.

**Steps to reproduce**: 
https://youtu.be/SZR9wh8LZBo - Expected behavior

https://youtu.be/hsPxDm9krvs - Current behavior

As you can see on Classic both mobs followed me WAY past the leash range and when i stopped attacking them both of them reset at the same time. On the vmangos video the second mob reset before i even killed the first mob.

**Client version**: 1.12.1

**Commit hash**:  150d3d7

**Operating system**: Windows

**Comment by rosen40** [comment]
https://youtu.be/BiasPgXc93Q

https://youtu.be/9p4nXzVZQag

2 more reference videos from Classic

**Comment by Zarant** [comment]
**How it's supposed to work:**
1. Hostile NPCs should check if an attackable unit is nearby on a global server tick that happens every 1.5s
2. That global tick will look for hostile units if the NPC is out of combat
3. When a creature is in combat, the periodic aggro tick will keep happening but this time will look for nearby friendly units of the same faction to assist it.
4. Inside instances, NPCs will keep checking for hostile units nearby during their periodic aggro pulse, regardless if they are on evade mode or already in combat.
5. In open world, creatures won't do periodic aggro pulses if they are on evade mode.
6. If a NPC sucessfully manage to call another creature to assist, both creatures should be linked, meaning that any action that puts you on the threat list of one mob should immediately put you on the threat list of all other mobs linked.
7. Any hostile actions towards any given mob should refresh the leash timer on all other linked mobs


About leashing (this is mostly anecdotal evidence from the 1.13 client):
Mobs should reset if leash timer goes over 10s
Threat radius seems to be 35yd for most mobs, and it's considerably smaller on starter zones (about 10-15yd)
Timer is the main condition for a mob to reset, found that out by running in circles around a mob and then running away from it's original location
If the timer reaches 10s and that mob is within the threat radius, mob won't go back, leash timer is rest, timer starts again
If a mob stand still for about 5s, the 10s timer is reset
Any hostile action should refresh leash, even if that does no damage


Research:
(1) I Did several tests that shows that npc aggro can happen anywhere between 0 to 1.5s: https://youtu.be/NbWMmAE0Hi0

(2,3,6,7) Creature assist always happens 1.5s after the first NPC is pulled, using a hostile ability will refresh the leash timer on all linked mobs: https://youtu.be/T8Qq4-6b2DM

(6,7) Pulling mobs at the exact same time will prevent the assist mechanic from happening allowing you to split pull mobs of the same faction: https://www.youtube.com/watch?v=W-pXh-qawTU

(4,5) Boss is pulled and the mage enters combat only when he gets close enough to it https://www.youtube.com/watch?v=CS2ZRWzujpo
(4,5) Mobs on evade mode in DM north can aggro players on their way back: https://youtu.be/hA8eMj8KwzY?t=1094
