### ISSUE TITLE
Server restart is initiated without knowing the cause. 

### ISSUE THREAD

**Issue by tonymmm1** [vmangos/core#811]
**Current behavior**:  After starting up server server restart in 15 min declared. 

**Expected behavior**:  No random restart

**Steps to reproduce**: Start up server and let it run for a few minutes. 

**Client version**:  1.12.1

**Commit hash**:  https://github.com/vmangos/core/commit/16902fea8691cdfeded056413a6c97127f3c68e3

**Operating system**:  Linux 64bit

**Comment by tonymmm1** [comment]
I am going to rebuild my deployment stack and then see if the error is repeatable.

**Comment by ghost** [comment]
Maintenance restarter?

**Comment by tonymmm1** [comment]
I am not certain and have checked logs.

**Comment by tonymmm1** [comment]
Ok i have completely recompiled and made sure everything is new but I have still have the restart warning.

**Comment by tonymmm1** [comment]
Do I need to edit config file and or database for the maintainer if that is what is causing the restarts?

**Comment by ghost** [comment]
https://github.com/vmangos/core/blob/development/src/mangosd/mangosd.conf.dist.in#L1073

**Comment by tonymmm1** [comment]
I just dont get why its triggering every boot. I am fine with the preset default timer is it an issue of the core not being able to use system time or somehow is not able to keep track?

**Comment by tonymmm1** [comment]
Yeah I have not noticed this issue in the past but I guess I can disable autohonor for now.

**Comment by ratkosrb** [comment]
Change AutoHonorRestart in config.

**Comment by tonymmm1** [comment]
@ratkosrb what is the purpose of autohonorrestart if it starts on launch? Isnt it a weekly timer.

**Comment by ratkosrb** [comment]
It restarts when there are more calculations to be done. It only calculates 1 week worth of honor on each restart. So if you have not started your server for a long time, you might need dozens of restarts to catch up.

**Comment by tonymmm1** [comment]
ok ty

**Comment by coolzoom** [comment]
or if you still need the auto honor restart, you could clean the saved variable table in characters database, it contains the honor maintenance time.
