### ISSUE TITLE
Naxxramas Bosses don't respawn properly with GM command.

### ISSUE THREAD

**Issue by Dasharius** [vmangos/core#815]
**Current behavior**: 
Trying to respawn for example Patchwerk in Naxxramas only despawns the corpse. Also seems to apply to all other Naxx Bosses. (Killed and respawned half of them -> same behaviour) 

**Expected behavior**: 
Patchwerk should spawn at the Grobbulus Gate. (All Bosses should spawn properly after using .respawn)

**Steps to reproduce**:

1. .gm on
2. .instance unbind all (optional)
3. .tele Naxx
4. Killing all Konstruct Quarter Trash with "Weapon of Massive Destruction (test) until you reach Patchwerk (otherwise the server crashes because the trash is linked to Patchwerk)
5. Target Patchwerk
6. .die
7. Target Patchwerk corpse
8. .respawn
9. Go to the respawn position of Patchwerk

**Notes**:
I also tried to pull him with .gm off, used .damage to kill him and so on ... nothing works

I did not have this problem in AQ40 for example. There you can kill for example Huhuran and respawn her without any problems.

**Why do I need this?**
I'm using this core as an PTR were we try to practice Bosses multiple times.

**Server Info**:
"16902fea8691cdfeded0" / 2020-10-02 18:28:15 +0300 / Linux_x64 (little-endian)
Server uptime: <10 Minutes

**Client Operating system and Version**: 
Windows 10 and 1.12.1 (5875)

**Comment by ratkosrb** [comment]
The instance script prevents respawns within the same raid lockout. This is probably intentional behavior. You can reset the entire raid to do the encounter again.

**Comment by caicaicai** [comment]
then .how to reset the entire raid...?

**Comment by ulfgebhardt** [comment]
Do we close this @ratkosrb ?
