### ISSUE TITLE
[Quest] The Challenge

### ISSUE THREAD

**Issue by schell244** [vmangos/core#818]
https://classic.wowhead.com/quest=9015/the-challenge
https://classic.wowhead.com/item=21986/banner-of-provocation 
https://classic.wowhead.com/npc=16059/theldren

When using Banner of Provocation within Ring of the Law in Blackrock Depths, player gets attacket by an invisible enemy (which does ~2 dmg to lvl 60 player). 
Theldren does not spawn - quest can't be completed.

**Client version**: 
1.12.1
**Commit hash**: 
4288692
**Operating system**: 
Win10

**Comment by ratkosrb** [comment]
Theldren does spawn and the quest is completable. The only problem was the trigger npc would aggro.
