### ISSUE TITLE
Two minor visual flaws

### ISSUE THREAD

**Issue by alexkulya** [vmangos/core#82]
1. There are no visual effects when you call the class mounts from the paladin and warlock.
[TC - Warlock Mounts](https://github.com/TrinityCore/TrinityCore/issues/14413)
[TC - Paladin Mounts](https://github.com/TrinityCore/TrinityCore/issues/14427)

2. The visual effect of drinking disappears after ~2-3 seconds of use. Food effects are displayed correctly.
[Video](https://www.youtube.com/watch?v=cboL6vEDetw#t=19m00s)

**Comment by ratkosrb** [comment]
Both drinking and eating works the same for me, not sure what you are referring to. You need to be a class with mana for the drinking emote to play.

**Comment by ratkosrb** [comment]
Fix for the mount visuals -> https://github.com/vmangos/core/commit/3be2738db4dedc28ff8b36d0e30e14e6f306ee95

**Comment by alexkulya** [comment]
Well, that's not such a big trouble. But still. At the moment vmangos, it looks like I have:
1. Eating - remaining 12 sec. Animation (Emotion) is normal. Bread visual effect is normal.
![screenshot_1](https://user-images.githubusercontent.com/7693165/50398355-ed9d5000-0787-11e9-9da7-0ff06dc3d4af.png)
2. Eating - remaining 2 sec. Animation (Emotion) is normal. Bread visual effect is normal.
![screenshot_2](https://user-images.githubusercontent.com/7693165/50398394-4967d900-0788-11e9-9105-3aa69d1ef441.png)
3. Drinking - remaining 12 sec. Animation (Emotion) is normal. Visual effect mugs is normal. (The character has mana and is currently restoring it.)
![screenshot_3](https://user-images.githubusercontent.com/7693165/50398421-86cc6680-0788-11e9-8c3a-ac5ff7486cd9.png)
4. Drinking - remaining 4 sec. Animation (Emotion) is normal. Visual effect mugs gone (A character drinks in hand). (The character has mana and is currently restoring it).
![screenshot_4](https://user-images.githubusercontent.com/7693165/50398496-11ad6100-0789-11e9-9d2f-ce5fe3445e4c.png)
The visual effect disappears earlier, after 2~4 seconds.

Apologies for the meticulousness.

**Comment by ratkosrb** [comment]
I think it's the client that decides what visual to display when a spell is cast, so I am not sure what we can do about that server-side. The mug disappears after a few seconds on cmangos too.

**Comment by alexkulya** [comment]
All right. It's small.
