### ISSUE TITLE
[Paladin] Greater blessings doesn't fade on leaving group

### ISSUE THREAD

**Issue by Daribon** [vmangos/core#823]
**Current behavior**: 
If you a paladin buffs you with any greater blessing, it stays on after you leave the paladins raid/group.
**Expected behavior**: 
All greater blessing should fade if you leave raid/group.
Only exceptions is if you are a paladin and buffed yourself with a greater blessing.
**Steps to reproduce**:

1. Buff any greater blessing on alt account raid/party member.
2. Leave group with alt account
3. Greater blessing will still be applied.

**Client version**: 
1.12.1.5875
**Commit hash**: 
https://github.com/vmangos/core/commit/30597d6db890f4b9401e5566046941d220e8ce34
**Operating system**: 
Windows 10 x64

**Comment by NickTyrer** [comment]
@ratkosrb Can this be closed now?
