### ISSUE TITLE
[Quest] The Battle of Darrowshire

### ISSUE THREAD

**Issue by schell244** [vmangos/core#828]
https://classic.wowhead.com/quest=5721/the-battle-of-darrowshire
https://classic.wowhead.com/item=15209/relic-bundle

**Steps to reproduce**:
1. Accept quest The [Battle of Darrowshire]
2. Use [Relic Bundle] at the Darrowshire town square, to start quest script

**Current behavior**: 
Quest scripts starts (player enters combat), some npcs are spawned. 
Tested 2 screnarios:
- not moving player 
- moving player to spawned npcs and kill enemies
In both cases, the script did not progress (no further spawns), and the quest log was not updated (complete/incomplete).

**Expected behavior**: 
Script should not interrupt and work as in:
https://youtu.be/ShUMVh0kudY?t=64

**Client version**: 
1.12.1
**Commit hash**: 
3d73832
**Operating system**: 
Win 10

**Comment by LEO33SoFo** [comment]
Me too encountered this exact bug, I hope this gets fixed one day.

**Comment by ratkosrb** [comment]
@LEO33SoFo Are you using an old version? I fixed this quest not starting months ago.
https://github.com/vmangos/core/commit/1743a8c314e6c18c9ad9f1faac0cd38d5a3eaca4

**Comment by LEO33SoFo** [comment]
@ratkosrb Nope. Using the current latest one.
f702e293580cb66529a42312966ee0aa05d084da

> fixed this quest not starting

The quest starts but does not progress, the event ending abruptly (no further spawns, as OP described).
