### ISSUE TITLE
Patch1.4,45level max，but 60level equipment out of the box in Stranglethorn Arena。

### ISSUE THREAD

**Issue by chenps10** [vmangos/core#83]
Patch1.4,45level max，but 60level equipment out of the box in Stranglethorn Arena。

for example：
the “Arena Vambraces”  supposed to :blue，50itemlevel、45level can use、+6 stamina；
but now it is：purple，60level can use、+38 stamina...;

 all the equipment out of box in Stranglethorn Arena is like this

how to fix it？

tks for help

**Comment by ratkosrb** [comment]
![untitled](https://user-images.githubusercontent.com/35845488/50380526-83df5200-0672-11e9-9eca-c305b6ae5bd9.jpg)

**Comment by chenps10** [comment]
how  stupid me!!
lol;
its player client problem，he use 1.12.3 and chang wow.exe version 1.12.1
delete wdb and relogin is fine；
close this issue and tks for patience
