### ISSUE TITLE
[Hallows End] Misc Bugs

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#832]
**Current behavior**: 
1. Various Apple Bob objects are unusable as the object is always in use
![Untitled](https://user-images.githubusercontent.com/22723839/96467676-132fff00-1223-11eb-949d-a4c19bfcdb1d.png)

2. Chicken Clucking for a Mint (8353) is missing RequestItemsText

3. Crashing the Wickerman Festival (1658) is missing RequestItemsText

4. The Power of Pine (8373) is missing RequestItemsText

5. Chicken Clucking for a Mint (8354) is missing RequestItemsText
 
6. The Wicker Man gameobject is missing along with the surrounding undercity flags.

7. The Power of Pine (8373) you can use the item Stink Bomb Cleaner without a stinkbomb being near to just complete the quest. Also using the cleaner when a stinkbomb is near doesnt remove it.

8. Stinking Up Southshore (1657) is not completable as the game does not register when you have planted a stinkbomb in southshore.

9. The ash piles around the wicker man should give the buff Invocation of the Wickerman https://wowwiki.fandom.com/wiki/Wickerman_Festival

10. A few pumpkin gameobjects in brill are floating

11. Gameobject 331066 is a duplicate

12. All Hallows End gameobjects are missing from Aerie Peak

13. The lighting of the wickerman event is not present.

14. The gossip formatting is slightly out where it says 8:00
![fd](https://user-images.githubusercontent.com/22723839/96631808-b90c6800-130e-11eb-9f5a-df5340663bce.png)

**Client version**: 
1.12.1
**Commit hash**: 
d062e86
**Operating system**: 
Win 10

**Comment by alexkulya** [comment]
1. <pre> UPDATE `gameobject` SET `state` = 1 WHERE `guid` IN (332880, 332864) AND `id` = 180523; </pre>
2. <pre> UPDATE `quest_template` SET `RequestItemsText` = "I'm waiting..." WHERE `entry` = 8353; </pre>
3. <pre> UPDATE `quest_template` SET `RequestItemsText` = "Have you gone up to Tirisfal Glade and checked things out? They usually hold the festival close to the Undercity..." WHERE `entry` = 1658; </pre>
4. <pre> UPDATE `quest_template` SET `RequestItemsText` = "Those blasted Forsaken... it's already bad enough that they're undead, but then they get all riled up and start causing trouble in MY village!" WHERE `entry` = 8373; </pre>
5. <pre> UPDATE `quest_template` SET `RequestItemsText` = "I'm waiting..." WHERE `entry` = 8354; </pre>

**Comment by alexkulya** [comment]
6.
<pre>
UPDATE `creature` SET `position_x` = 1760.689941, `position_y` = 510.542999, `position_z` = 36.015301, `orientation` = 6.259000 WHERE `guid` = 160014 AND `id` = 15197;
UPDATE `creature` SET `position_x` = 1732.310059, `position_y` = 520.874023, `position_z` = 36.332600, `orientation` = 1.309420 WHERE `guid` = 85634 AND `id` = 15195;

DELETE FROM `gameobject` WHERE `guid` BETWEEN 131140 AND 131150;
INSERT INTO `gameobject` (`guid`, `id`, `map`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecsmin`, `spawntimesecsmax`, `animprogress`, `state`, `spawn_flags`, `visibility_mod`) VALUES
(131140, 180432, 0, 1749.28, 507.611, 39.2312, 1.49635, 0, 0, 0.680301, 0.732933, 300, 300, 0, 1, 0, 0),
(131141, 180432, 0, 1712.63, 507.05, 38.2495, 1.58824, 0, 0, 0.713246, 0.700914, 300, 300, 0, 1, 0, 0),

(131142, 180433, 0, 1734.04, 504.05, 42.2861, 1.4131, 0, 0, 0.649213, 0.760607, 300, 300, 0, 0, 0, 0),

(131143, 180434, 0, 1758.89, 513.276, 35.8655, 1.28897, 0, 0, 0.600788, 0.799409, 300, 300, 0, 1, 0, 0),
(131144, 180434, 0, 1704.48, 518.689, 35.4045, 1.30704, 0, 0, 0.607984, 0.793949, 300, 300, 0, 1, 0, 0),
(131145, 180434, 0, 1739.78, 473.238, 61.6565, 1.59371, 0, 0, 0.71516, 0.698961, 300, 300, 0, 1, 0, 0),
(131146, 180434, 0, 1717.32, 472.723, 61.6566, 1.59371, 0, 0, 0.71516, 0.698961, 300, 300, 0, 1, 0, 0),

(131147, 180437, 0, 1744.62, 504.954, 40.8518, 1.23403, 0, 0, 0.578603, 0.81561, 300, 300, 0, 1, 0, 0),
(131148, 180437, 0, 1729.13, 510.378, 40.8719, 1.23403, 0, 0, 0.578603, 0.81561, 300, 300, 0, 1, 0, 0),
(131149, 180437, 0, 1721.77, 503.938, 41.1381, 1.23403, 0, 0, 0.578603, 0.81561, 300, 300, 0, 1, 0, 0),
(131150, 180437, 0, 1744.96, 496.25, 41.44, 1.24581, 0, 0, 0.583397, 0.812187, 300, 300, 0, 1, 0, 0);

DELETE FROM `game_event_gameobject` WHERE `guid` IN (131140, 131141, 131142, 131143, 131144, 131145, 131146, 131147, 131148, 131149, 131150) AND `event` = 12;
INSERT INTO `game_event_gameobject` (`guid`, `event`) VALUES
(131140, 12),
(131141, 12),
(131142, 12),
(131143, 12),
(131144, 12),
(131145, 12),
(131146, 12),
(131147, 12),
(131148, 12),
(131149, 12),
(131150, 12);
</pre>

**Comment by ratkosrb** [comment]
I am working on it.

**Comment by ratkosrb** [comment]
Numbers 10 and 11 are not bugs. It's the same on Blizzard servers.

![WoWScrnShot_102220_125445](https://user-images.githubusercontent.com/35845488/96856080-3696bc00-1466-11eb-956c-ce519396fe89.jpg)

![WoWScrnShot_102220_125532](https://user-images.githubusercontent.com/35845488/96856106-3b5b7000-1466-11eb-826b-4f620ccd3de5.jpg)

![WoWScrnShot_102220_125613](https://user-images.githubusercontent.com/35845488/96856125-3f878d80-1466-11eb-9082-df4012af2716.jpg)

**Comment by ratkosrb** [comment]
Number 14 is also not a bug.
