### ISSUE TITLE
How to add the Eluna function to Light's Hope Vanilla V17?

### ISSUE THREAD

**Issue by dxgmbz123** [vmangos/core#833]
How to add the Eluna function to Light's Hope Vanilla V17?

**Comment by dxgmbz123** [comment]
I am noob

**Comment by Daribon** [comment]
you can't, v17 is a repack.

**Comment by dxgmbz123** [comment]
Can the core of vmangos be added?

**Comment by dxgmbz123** [comment]
Or add the source code of Light's Hope Vanilla V15?

**Comment by ghost** [comment]
Use VMaNGOS Discord for questions. This one here is a bugtracker if you didn't notice..

**Comment by ratkosrb** [comment]
We do not support Eluna.
