### ISSUE TITLE
[NPC] Rimblat Earthshatter Missing Event

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#836]
**Current behavior**: 
The Event is Missing

**Expected behavior**: 
Here is a video for reference:
https://youtu.be/VAd1H8Mmgj8

**Client version**: 
1.12.1
**Commit hash**: 
d062e86
**Operating system**: 
Win 10

**Comment by alexkulya** [comment]
The text part of the event has already been done, you need to add an action with a kneel and a script for the DND spell:
[click for view this spell](https://classic.wowhead.com/spell=27824/rimblat-grows-flower-dnd)
