### ISSUE TITLE
Windows XP compatibility?

### ISSUE THREAD

**Issue by LEO33SoFo** [vmangos/core#840]
**Current behavior**: 

The program does not run on _Windows XP_, with the error "**_The procedure entry point GetThreadId could not be located in the dynamic link library KERNEL32.dll._**"

**Expected behavior**: 

If _Windows XP_ is supposed to be compatible, it should run with no problems, like the older (May 2020) versions of _vMaNGOS_ contained in [Light's Hope Vanilla Repack](http://www.ac-web.org/forums/showthread.php?230227-Light-s-Hope-Vanilla-Repack).

**Steps to reproduce**:

1. Compile _vMaNGOS_ in _Visual Studio Community 2015 Update 3_ with _Windows XP Support for C++_ component installed, and changing the Platform Toolset to _Visual Studio 2015 - Windows XP (v140_xp)_.
Compiling with the default Platform Toolset will result _vMaNGOS_ not starting at all (**_mangosd_** and/or **_realmd is not a valid Win32 application._**)

**Client version**: 

1.12.2

**Commit hash**: 

3d738329f6a867a86ed5d10ff23e89c4fe1cf5df

**Operating system**: 

_Windows 7 Enterprise_ SP1 64bit for compiling, _Windows XP Professional_ SP3 32bit for testing.

**Comment by ratkosrb** [comment]
I can't reproduce the issue. I just compiled the latest version and it ran fine on XP.

**Comment by ratkosrb** [comment]
![vmangosxp](https://user-images.githubusercontent.com/35845488/97066356-7cb26380-15bd-11eb-8298-e44ec4433044.JPG)

**Comment by ratkosrb** [comment]
Maybe its caused by the version of ACE or TBB you are using.
I compile with:
ACE-6.4.2
tbb2017_20161128oss_win

**Comment by LEO33SoFo** [comment]
@ratkosrb Thank you. It seems the current latest versions of these tools don't work with *Windows XP*.
It worked with **ACE-6.5.6** and **tbb2019_20191006oss_win** though.

**Comment by LEO33SoFo** [comment]
@ratkosrb FYI, the definitive last versions of working _ACE_ and _TBB_ on _Windows XP_ are **ACE-6.5.6** and **tbb-2020.3-win**.
Perhaps you should mention this in the [Wiki](https://github.com/vmangos/wiki/wiki/Compiling-on-Windows) page?

**Comment by ratkosrb** [comment]
The versions that I use and have linked in the wiki are even older, so they will still work on XP.
