### ISSUE TITLE
Item flags pre 1.7

### ISSUE THREAD

**Issue by barncastle** [vmangos/core#841]
Just to let you know that for pre-1.7 you have an overflow in your item flags.

Pre 1.7 `ITEM_STATIC_FLAGS` (ItemPrototypeFlags) and `ITEM_DYNAMIC_FLAGS` were both 16 bit fields and were both sent in the `SMSG_UPDATE_OBJECT` packet -  the `ITEM_FIELD_FLAGS` update field was a union of them. From 1.7 these increased to 32 bit so they dropped the static flags as they're already known from the item query packet. 

This is why you've currently got `ITEM_DYNFLAG_UNK16 = 0x00010000, // soulbound pre 1.7` when it should still be 0x1.

Also official flag names (validated to 1.6 but probably correct for the duration of Vanilla):

```
enum ITEM_STATIC_FLAGS
{
  ITEM_FLAG_NO_PICKUP = 0x1,
  ITEM_FLAG_CONJURED = 0x2,
  ITEM_FLAG_HAS_LOOT = 0x4,
  ITEM_FLAG_EXOTIC = 0x8,
  ITEM_FLAG_DEPRECATED = 0x10,
  ITEM_FLAG_OBSOLETE = 0x20,
  ITEM_FLAG_PLAYERCAST = 0x40,
  ITEM_FLAG_NO_EQUIPCOOLDOWN = 0x80,
  ITEM_FLAG_INTBONUSINSTEAD = 0x100,
  ITEM_FLAG_IS_WRAPPER = 0x200,
  ITEM_FLAG_USES_RESOURCES = 0x400,
  ITEM_FLAG_MULTI_DROP = 0x800,
  ITEM_FLAG_BRIEFSPELLEFFECTS = 0x1000,
  ITEM_FLAG_PETITION = 0x2000,
  MAX_ITEM_FLAG = 0x8000,
  ITEM_FLAG_NUM = 0xE,
};

enum ITEM_DYNAMIC_FLAGS
{
  ITEM_DFLAG_BOUND = 0x1,
  ITEM_DFLAG_TRANSLATED = 0x2,
  ITEM_DFLAG_UNLOCKED = 0x4,
  ITEM_DFLAG_WRAPPED = 0x8,
};
```

**Comment by ratkosrb** [comment]
Thank you for this information. I have updated the implementation.
https://github.com/vmangos/core/commit/e2e2b85710aaa7c31bca9095de6c5eedda203d13
