### ISSUE TITLE
Hidden farms

### ISSUE THREAD

**Issue by alexkulya** [vmangos/core#845]
Added creatures spawns, wps, gobs spawns in:
- Arathi coast dwarven farm [gamepedia link](https://wow.gamepedia.com/Arathi_coast_dwarven_farm)
- Wetlands farm [gamepedia link](https://wow.gamepedia.com/Wetlands_farm) (Closes: #843)

Thanks: cmangos (big data part), @NickTyrer (video)

<pre>
DELETE FROM `creature` WHERE `guid` BETWEEN 285020 AND 285069;
INSERT INTO `creature` (`guid`, `id`, `map`, `display_id`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecsmin`, `spawntimesecsmax`, `wander_distance`, `movement_type`) VALUES
-- Dwarven Farmer (Hidden farm #1)
(285020, 12998, 0, 0, 0, -1853.19, -4122.06, 11.1314, 4.76928, 60, 60, 0, 2),
(285021, 12998, 0, 0, 0, -1853.49, -4091.65, 9.81663, 4.70644, 60, 60, 0, 0),
-- Ram (Hidden farm #1)
(285022, 2098, 0, 0, 0, -1813.51, -4155.14, 9.89494, 1.82635, 60, 60, 0, 0),
(285023, 2098, 0, 0, 0, -1818.03, -4142.99, 9.89494, 4.68913, 60, 60, 0, 0),
-- Cat (Hidden farm #1)
(285024, 6368, 0, 0, 0, -1855.72, -4117.62, 13.0457, 5.2373, 60, 60, 0, 0),
(285025, 6368, 0, 0, 0, -1839.99, -4245.72, 2.13572, 1.15007, 60, 60, 0, 0),
-- Rat (Hidden farm #1)
(285026, 4075, 0, 0, 0, -1818.5, -4149.38, 9.89524, 0.0426621, 60, 60, 5, 1),
(285027, 4075, 0, 0, 0, -1853.79, -4149.49, 9.74445, 5.99991, 60, 60, 5, 1),
(285028, 4075, 0, 0, 0, -1832.93, -4231.47, 2.13493, 4.15422, 60, 60, 5, 1),
(285029, 4075, 0, 0, 0, -1765.09, -4228.05, 2.06121, 3.92646, 60, 60, 5, 1),
(285030, 4075, 0, 0, 0, -1685.3, -4200.7, 1.99848, 0.324622, 60, 60, 5, 1),
(285031, 4075, 0, 0, 0, -1720.4, -4190.35, 1.99845, 2.78763, 60, 60, 5, 1),
(285032, 4075, 0, 0, 0, -1953.66, -4080.47, 2.03243, 1.65973, 60, 60, 5, 1),
(285033, 4075, 0, 0, 0, -1981, -4082.81, 2.06496, 2.00923, 60, 60, 5, 1),
(285034, 4075, 0, 0, 0, -1952.94, -4118.76, 2.0329, 5.26471, 60, 60, 5, 1),
(285035, 4075, 0, 0, 0, -1933.78, -4107.02, 2.0329, 5.249, 60, 60, 5, 1),
(285036, 4075, 0, 0, 0, -1898.76, -4155.48, 2.0329, 6.10665, 60, 60, 5, 1),
(285037, 4075, 0, 0, 0, -1773.96, -4198.48, 1.99868, 5.41943, 60, 60, 5, 1),
(285038, 4075, 0, 0, 0, -1748.44, -4205.78, 1.99868, 5.91973, 60, 60, 5, 1),
(285039, 4075, 0, 0, 0, -1702.71, -4252.72, 1.99827, 2.49775, 60, 60, 5, 1),
(285040, 4075, 0, 0, 0, -1728.17, -4279.38, 1.99826, 4.70708, 60, 60, 5, 1),
-- Ironforge Mountaineer (Hidden farm #2)
(285041, 727, 0, 0, 0, -3972.82, -1513.31, 169.195, 5.53077, 60, 60, 0, 0),
(285042, 727, 0, 0, 0, -3985.24, -1508.53, 168.705, 4.14848, 60, 60, 0, 0),
-- Dwarven Farmer (Hidden farm #2)
(285043, 12998, 0, 0, 0, -4029.86, -1453.53, 167.187, 4.37309, 60, 60, 5, 1),
(285044, 12998, 0, 0, 0, -4101.77, -1261.85, 149.042, 4.86947, 60, 60, 0, 0),
(285045, 12998, 0, 0, 0, -4074.56, -1256.74, 146.399, 0.106011, 60, 60, 0, 2),
(285046, 12998, 0, 0, 0, -4110.72, -1068.8, 168.909, 4.87338, 60, 60, 5, 1),
(285047, 12998, 0, 0, 0, -4147.28, -1106.97, 168.917, 0.341632, 60, 60, 0, 0),
-- Ram (Hidden farm #2)
(285048, 2098, 0, 0, 0, -4144.93, -1058.98, 167.925, 0.057233, 60, 60, 0, 0),
(285049, 2098, 0, 0, 0, -4131.62, -1063.01, 167.925, 4.41786, 60, 60, 0, 0),
-- Chicken (Hidden farm #2)
(285050, 620, 0, 0, 0, -4126.41, -1091.58, 168.916, 4.29377, 60, 60, 5, 1),
(285051, 620, 0, 0, 0, -4117.23, -1101.1, 168.953, 3.54764, 60, 60, 5, 1),
(285052, 620, 0, 0, 0, -4137.29, -1102.33, 168.916, 3.74399, 60, 60, 5, 1),
(285053, 620, 0, 0, 0, -4080.96, -1256.69, 146.684, 3.85709, 60, 60, 5, 1),
(285054, 620, 0, 0, 0, -4074.13, -1268.01, 146.158, 4.99592, 60, 60, 5, 1),
(285055, 620, 0, 0, 0, -4091.94, -1279.57, 146.18, 3.76912, 60, 60, 5, 1),
(285056, 620, 0, 0, 0, -4039.9, -1446.43, 166.2, 4.68177, 60, 60, 5, 1),
(285057, 620, 0, 0, 0, -4022.11, -1449.52, 165.607, 5.71378, 60, 60, 5, 1),
(285058, 620, 0, 0, 0, -4017.85, -1460.55, 168.343, 4.69512, 60, 60, 5, 1),
(285059, 620, 0, 0, 0, -4001.15, -1502.53, 169.703, 5.06818, 60, 60, 5, 1),
(285060, 620, 0, 0, 0, -3964.18, -1526.38, 169.163, 5.06818, 60, 60, 5, 1),
-- Mounted Ironforge Mountaineer (Hidden farm #2)
(285061, 12996, 0, 0, 0, -4025.61, -1404.07, 155.248, 3.81547, 60, 60, 0, 2),
-- Rabbit (Hidden farm #2)
(285062, 721, 0, 0, 0, -3971.98, -1494.18, 169.931, 2.12686, 60, 60, 5, 1),
(285063, 721, 0, 0, 0, -3994.42, -1376.7, 150.124, 1.10741, 60, 60, 5, 1),
(285064, 721, 0, 0, 0, -4026.06, -1270.89, 146.802, 1.82841, 60, 60, 5, 1),
(285065, 721, 0, 0, 0, -4096.43, -1088.23, 170.199, 1.84097, 60, 60, 5, 1),
(285066, 721, 0, 0, 0, -4166.11, -998.81, 168.036, 1.097012, 60, 60, 5, 1),
-- Cow (Hidden farm #2)
(285067, 2442, 0, 0, 0, -4053.71, -1187.58, 146.314, 4.69747, 60, 60, 5, 1),
(285068, 2442, 0, 0, 0, -4041.5, -1230.92, 146.314, 3.80212, 60, 60, 5, 1),
(285069, 2442, 0, 0, 0, -4055.91, -1247.15, 146.314, 4.19089, 60, 60, 5, 1);

DELETE FROM `gameobject` WHERE `guid` IN (325550, 325551, 325552);
INSERT INTO `gameobject` (`guid`, `id`, `map`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecsmin`, `spawntimesecsmax`, `animprogress`, `state`) VALUES
(325550, 123215, 0, -4020.33, -1407.01, 155.454, 1.57952, 0, 0, 0.710184, 0.704016, 180, 180, 255, 1),
(325551, 123216, 0, -4020.05, -1407.16, 155.463, 3.14159, 0, 0, 1, 0.00000126759, 180, 180, 255, 1),
(325552, 123217, 0, -4020.05, -1407.01, 155.437, 0.008724, 0, 0, 0.00436199, 0.99999, 180, 180, 255, 1);

DELETE FROM `creature_addon` WHERE `guid` IN (285021, 285024, 285025);
INSERT INTO `creature_addon` (`guid`, `mount`, `bytes1`) VALUES
(285021, 0, 3),
(285024, 0, 1),
(285025, 0, 1);

DELETE FROM `creature_movement` WHERE `id` IN (285020, 285045, 285061);
INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `waittime`) VALUES
(285020, 1, -1851.5, -4161.39, 8.0422, 100, 5000),
(285020, 2, -1849.24, -4170.83, 6.40288, 0, 0),
(285020, 3, -1843.77, -4176.64, 5.19335, 0, 0),
(285020, 4, -1827.66, -4188.65, 3.6245, 0, 0),
(285020, 5, -1821.43, -4200.03, 3.37323, 100, 5000),

(285045, 1, -4056.62, -1257.13, 146.314, 0, 0),
(285045, 2, -4022.13, -1239.04, 146.314, 0, 0),
(285045, 3, -4027.52, -1197.61, 146.314, 0, 0),
(285045, 4, -4073.56, -1205.96, 146.314, 0, 0),
(285045, 5, -4074.82, -1234.27, 146.481, 0, 0),
(285045, 6, -4071.62, -1244.78, 146.406, 0, 0),
(285045, 7, -4073.64, -1253.11, 146.433, 0, 0),

(285061, 1, -4032.54, -1410.32, 156.721, 0, 0),
(285061, 2, -4074.89, -1407.43, 166.031, 0, 0),
(285061, 3, -4121.2, -1392.13, 186.617, 0, 0),
(285061, 4, -4139.65, -1392.91, 194.53, 0, 0),
(285061, 5, -4160.59, -1400.4, 197.085, 0, 0),
(285061, 6, -4139.07, -1393.15, 194.301, 0, 0),
(285061, 7, -4120.76, -1392.22, 186.412, 0, 0),
(285061, 8, -4074.23, -1407.58, 165.77, 0, 0),
(285061, 9, -4032.55, -1410.22, 156.712, 0, 0),
(285061, 10, -4020.63, -1397.18, 153.371, 0, 0),
(285061, 11, -4017.04, -1356.28, 148.046, 0, 0),
(285061, 12, -4009.14, -1314.06, 146.624, 0, 0),
(285061, 13, -4018.54, -1285.38, 146.625, 0, 0),
(285061, 14, -3993.26, -1242.82, 146.911, 0, 0),
(285061, 15, -3994.51, -1185.12, 154.931, 0, 0),
(285061, 16, -4020.88, -1159.39, 157.864, 0, 0),
(285061, 17, -4044.1, -1151.67, 160.279, 0, 0),
(285061, 18, -4067.39, -1109.54, 166.369, 0, 0),
(285061, 19, -4087.61, -1099.67, 168.504, 0, 0),
(285061, 20, -4128.91, -1098.02, 168.917, 0, 0),
(285061, 21, -4136.27, -1079.66, 168.917, 0, 0),
(285061, 22, -4128.58, -1098.3, 168.916, 0, 0),
(285061, 23, -4086.78, -1099.88, 168.434, 0, 0),
(285061, 24, -4066.85, -1110.06, 166.183, 0, 0),
(285061, 25, -4043.64, -1151.81, 160.212, 0, 0),
(285061, 26, -4020.62, -1159.42, 157.841, 0, 0),
(285061, 27, -3994.12, -1185.26, 154.956, 0, 0),
(285061, 28, -3992.99, -1243.2, 146.901, 0, 0),
(285061, 29, -4018.42, -1285.85, 146.623, 0, 0),
(285061, 30, -4008.84, -1314.12, 146.627, 0, 0),
(285061, 31, -4016.71, -1356.63, 148.065, 0, 0),
(285061, 32, -4020.15, -1397.47, 153.434, 0, 0);
</pre>

**Comment by ratkosrb** [comment]
The gameobjects were already spawned.
