### ISSUE TITLE
[Battlebots] - reward mark via mail

### ISSUE THREAD

**Issue by schell244** [vmangos/core#847]
When running the server with battlebots for a while, the inventory of battlebots will fill up with battleground reward marks.
When battlebots reach full inventory, the server will send reward marks via mail to battlebots character guids.
Since the guids are not saved to db.... restart the server, create a new character and you can expect some post :D

-> to prevent that, battlebots should not receive reward marks

**Client version**: 
1.12.1
**Commit hash**: 
88e3304
**Operating system**: 
Win 10

**Comment by Kittnz** [comment]
Ha, thats not intended 👍
