### ISSUE TITLE
Enchants don't apply until reloging or re equipping item

### ISSUE THREAD

**Issue by T1ti** [vmangos/core#850]
**Current behavior**: 
When you enchant an item, it won't apply until the item is reequiped or you relog.
The bug seems to only happen with primary stats, not with AP, spell power... Also other players cannot see your gear is enchanted

**Expected behavior**: 
It should refresh on enchant application

**Steps to reproduce**:

1. equip an item
2. enchant it with a primary stat
3. see if stats update

**Client version**: 
1.12

**Comment by ratkosrb** [comment]
I cannot reproduce the issue. My stats update immediately when i enchant an item.

**Comment by T1ti** [comment]
My bad, it only happens with the GM island enchanters. normal enchants work properly.
