### ISSUE TITLE
Healing over time effects don't work at full health

### ISSUE THREAD

**Issue by T1ti** [vmangos/core#854]
**Current behavior**: 
Wen you use a HoT on someone(or self) with full health, they don't get healed by it until they are damaged.

**Expected behavior**: 
On classic HoTs always heal, even at full health. This bug allows to precast HoTs on tanks without the healer generating aggro until the tank is damaged. (not sure about the aggro part, not tested on classic, but currently in vmangos it deosn't do any threat as it doesn't heal)

**Steps to reproduce**:

1.  HoT someone at 100% health on classic and vmangos
2. compare

**Client version**: 
1.12

**Comment by Gamemechanicwow** [comment]
Overhealing doesn't cause any threat.

I dont have an active subscription atm, but i guess what you are describing is a difference between how the classic and 1.12 client visually displays overheals.

**Comment by T1ti** [comment]
Yes I am not sure if the client just doesn't display it, or if it's a core bug
But even the combat log doesn't even show any healing done  so I am unsure

**Comment by ulfgebhardt** [comment]
Any updates on this @Gamemechanicwow @T1ti ? Is it a bug or can we close?

**Comment by NickTyrer** [comment]
Here are the differences:
classic: https://youtu.be/HxcNMbEaZBw
vmangos: https://youtu.be/Z3-hTPfe_3g

**Comment by Gamemechanicwow** [comment]
> Here are the differences:
> classic: https://youtu.be/HxcNMbEaZBw
> vmangos: https://youtu.be/Z3-hTPfe_3g

Your videos are set to private.

**Comment by NickTyrer** [comment]
fixed

**Comment by Gamemechanicwow** [comment]
I still thinks this is a case of Classic not being blizzlike. Here is what i could find:

https://wow.gamepedia.com/Patch_3.0.2
> Overhealing is now reported in the combat log.

https://wow.gamepedia.com/Overhealing?direction=next&oldid=1660424
> Heal over time spells (HoTs) will only heal if the target is not already at full health, but they cost the same amount of mana regardless of how much they end up actually healing for. Because of this, HoTs will almost always show as having done very little overhealing, which is not necessarily true.

https://www.wowhead.com/forums&topic=113259
> It's an intended change. It also makes Valanyr work properly for druids. Apparently previous to this hotfix, the game did an overhealing check for hot ticks and didn't even apply them if it was completely overheal. Now, it applies each hot tick regardless and the combat log reflects the 0 (n Overheal) for each full overheal tick.

edit: hots where the tick is 100% overheal wasn't reported in the combatlog before wotlk.

**Comment by ratkosrb** [comment]
Well that settles it then.
