### ISSUE TITLE
[Quest] Vorsha the Lasher

### ISSUE THREAD

**Issue by Siid9741** [vmangos/core#857]
**Current behavior**: 
Muglash helps us once out of 2 and at the end of the escort he doesn't help us, and bug move.

**Expected behavior**: 
https://www.youtube.com/watch?v=4v-V-0S7gMA&feature=emb_title

**Steps to reproduce**:

1. .go xyz 3348 1007 4
2. .q add 6641
3. look at the pnj's behaviour

**Client version**: 
1.12.1

**Commit hash**: 

**Operating system**: 
WIN

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/39960c4fcc45a5796d4c105f2800403c28298157
