### ISSUE TITLE
noggenfogger effects chances

### ISSUE THREAD

**Issue by T1ti** [vmangos/core#864]
**Current behavior**: 
Each effect has 33% chance (1/3 each)
**Expected behavior**: 
On classic, you have 60% chance to have the skeleton effect, 20% slow fall, 20% mini
https://www.reddit.com/r/classicwow/comments/jwycmc/noggenfogger_1000_consumes_593_skellies_210_minis/
**Steps to reproduce**:

1. current code : "uint32 spellId = PickRandomValue(16595, 16593, 16591);"

**Client version**: 
1.12

**Comment by ratkosrb** [comment]
https://github.com/vmangos/core/commit/784d5d348b0cadbbafa12fc45e889bd0af5518aa
