### ISSUE TITLE
Tree wolf

### ISSUE THREAD

**Issue by T1ti** [vmangos/core#867]
**Current behavior**: 
Tree wolf is still riding the tree in northshire
GUID 80134
![tree wolf](https://user-images.githubusercontent.com/40864460/99762126-148d6980-2af8-11eb-9312-9b197cab8a77.png)

**Expected behavior**: 
tree wolves don't exist

**Client version**: 
1.12

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/c1db8e8f625ba5dbba3c03a11eafb4411e1557db
