### ISSUE TITLE
Missing group UI update after loading screen

### ISSUE THREAD

**Issue by schell244** [vmangos/core#871]
**Steps to reproduce**:
1. player1 and player2 are in a group
2. player1 has loading screen, meanwhile player2 leaves group

**Current behavior**: 
player2: has successfully left group (no issues)
player1: will still see the group UI after loading screen, but UI does not work 
(leave group has no effect, UI does not disappear - issue can be fixed by relogging)

**Expected behavior**: 
both players have successfully left group, UI should be updated after loading screen. 

**Client version**: 
1.12.1
**Commit hash**: 
7682131
**Operating system**: 
Win10

**Comment by ratkosrb** [comment]
So the issue happens if the other player leaves group while you are in the middle of a loading screen?

**Comment by schell244** [comment]
Correct.

**Comment by schell244** [comment]
Did not see this happening again ever since. Closing.
