### ISSUE TITLE
wrong visual NPC orientation on client

### ISSUE THREAD

**Issue by Oroxzy** [vmangos/core#872]
**Current behavior**: 

this is: https://github.com/vmangos/core/commit/7e461e0d6e03d57618d8c59a389f22dcac274615

https://youtu.be/zVMCZc483xg?t=68

watch at 1:10 in slower motion.

- The target has back against rogue. (Expected behavior)
- after the cheap shot the npc faces the rogue to hit him. (Expected behavior)
- after gouge the npc turns around (just visual cause orientation is correct, unexpected behavior)
- same with kidney shot the npc turns around (just visual not from server side cause can't backstab)

i did the same with the .gps orientation check. the npc orientation is correct (reason why i can't backstab although he looks in a different direction) so its maybe a client bug.

**Expected behavior**: 

npc should not turn i guess?

**Steps to reproduce**:

Do the same like i do in the video.. if you do it fast enough..  in my video i use a macro todo this i can just spam one button.

**Comment by Kittnz** [comment]
Can you try this one a clean client?

**Comment by Gamemechanicwow** [comment]
> Can you try this one a clean client?

I also thought it was client bug when i experienced on my rogue on lh. But seems like that I was wrong.

![image](https://user-images.githubusercontent.com/2223066/99887250-19aaff80-2c43-11eb-9288-6ae44792b087.png)

**Comment by ratkosrb** [comment]
If it's blizzlike and happens on classic too, then we should not "fix" it.

**Comment by ratkosrb** [comment]
Closing since it happens on blizzard servers too.
