### ISSUE TITLE
[NPC] Gubber Blump MIssing Gossip

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#876]
**Current behavior**: 
He is missing a gossip menu option and he should be a vendor

**Expected behavior**: 
Here is a video for ref: https://youtu.be/RnLNLaw-6qw
Also I think he has an additional gossip menu option if you dont have the fishing as wowhead has 2 text id's listed
 ```Gubber Blump says: Fishing is real easy. Just take a pole with a line on it, maybe put some bait on it, and cast it out in the water. Sure enough, them fish will start biting.```
https://classic.wowhead.com/npc=10216/gubber-blump#comments.

**Client version**: 
1.12.1
**Commit hash**: 
9a75b6b
**Operating system**: 
Win 10

**Comment by ratkosrb** [comment]
![Untitled](https://user-images.githubusercontent.com/35845488/100003925-70454480-2dcf-11eb-8159-3f30f88de067.jpg)

He already has 2 gossip options.

**Comment by ratkosrb** [comment]
In vmangos the gossip options show up once you accept his quest.
![Untitled](https://user-images.githubusercontent.com/35845488/100004362-11cc9600-2dd0-11eb-9fc7-6a79a49ed3f8.jpg)

**Comment by ratkosrb** [comment]
Gubber, I don't know how to fish. - Shows up after you accept the quest.

Gubber, I don't have a fishing pole. - Shows up if you have learned fishing.
