### ISSUE TITLE
Moonkins skinnable

### ISSUE THREAD

**Issue by Gamemechanicwow** [vmangos/core#885]
**Current behavior**: 
Moonkins are skinnable on every patch.

**Expected behavior**: 
On classic moonkins aren't skinnable.

I haven't been able to dig up any information if moonkins where skinnable in earlier patches. Maybe someone else can provide information on that? 
 
**Steps to reproduce**:

1. 
2. 
3. 

**Client version**: 
1.12

**Commit hash**: 

**Operating system**:

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/c1db8e8f625ba5dbba3c03a11eafb4411e1557db
