### ISSUE TITLE
[Spell] Spirit of Redemption

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#889]
**Current behavior**: 
When you exit spirit of redemtion no death animation is played
https://youtu.be/GME6lB-w8YY

**Expected behavior**: 
The death animation should play (also the casting animation should play when entering the spirit of redemption)
https://youtu.be/IByonxXP_PI

**Client version**: 
1.12.1
**Commit hash**: 
fdd11c7
**Operating system**: 
Win 10

**Comment by Daribon** [comment]
Not only that, it seems to be lacking the big holy light effect when you transform into Spirit of Redemption.

**Comment by NickTyrer** [comment]
cmangos has made a few corrections for this spell, see:
https://github.com/cmangos/mangos-classic/commit/23781edca640baf89f5e387bf47f5cad5660b24d
https://github.com/cmangos/mangos-classic/commit/e1a00a43a9f8ae1deadda1f986b92aba3a8e66e3
https://github.com/cmangos/mangos-classic/commit/9e2acb57fae07cdc779c8c554169e46a1e39a83d

**Comment by Daribon** [comment]
So I looked more into this today.

The spells that spirit of Redemption uses does the following:
27827 transforms you into Spirit of Redemption and sets your HP to 1.
27792 locks you into position so you can't move.
27795 also sets your HP to 1? Disables HP regen.
25100 casts the holy light effect.

Below most of it can be seen in classic sniff:
ServerToClient: SMSG_SPELL_HEAL_LOG (0x2C1D) Length: 39 ConnIdx: 1 Time: 01/10/2022 22:19:28.656 Number: 932013
TargetGUID: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
CasterGUID: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
SpellID: 27827 (27827)
Health: 1
OriginalHeal: 1
OverHeal: 0
Absorbed: 0
Crit: False
HasCritRollMade: False
HasCritRollNeeded: False
HasLogData: False
HasContentTuning: False

ServerToClient: SMSG_AURA_UPDATE (0x2C22) Length: 94 ConnIdx: 1 Time: 01/10/2022 22:19:28.656 Number: 932014
UpdateAll: False
AurasCount: 2
[0] Slot: 0
[0] HasAura: True
[0] CastID: Full: 0xBC516803C01B2CC3006D6C00055CA2E0 Cast/3 R5210/S28012 Map: 30 Low: 89957088
[0] SpellID: 27827 (27827)
[0] SpellXSpellVisualID: 0
[0] Flags: 263 (NoCaster, Positive, Duration, MawPower)
[0] ActiveFlags: 6
[0] CastLevel: 53
[0] Applications: 0
[0] ContentTuningID: 0
[0] HasCastUnit: False
[0] HasDuration: False
[0] HasRemaining: False
[0] HasTimeMod: False
[0] PointsCount: 0
[0] EstimatedPoints: 0
[0] HasContentTuning: False
[1] Slot: 1
[1] HasAura: True
[1] CastID: Full: 0xBC516803C01B2407006D6C00005CA2E0 Cast/7 R5210/S28012 Map: 30 Low: 6071008
[1] SpellID: 27792 (27792)
[1] SpellXSpellVisualID: 0
[1] Flags: 513 (513)
[1] ActiveFlags: 7
[1] CastLevel: 53
[1] Applications: 0
[1] ContentTuningID: 0
[1] HasCastUnit: False
[1] HasDuration: False
[1] HasRemaining: False
[1] HasTimeMod: False
[1] PointsCount: 0
[1] EstimatedPoints: 0
[1] HasContentTuning: False
UnitGUID: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269

ServerToClient: SMSG_AURA_UPDATE (0x2C22) Length: 52 ConnIdx: 1 Time: 01/10/2022 22:19:28.656 Number: 932015
UpdateAll: False
AurasCount: 1
[0] Slot: 2
[0] HasAura: True
[0] CastID: Full: 0xBC516803C01B24C7006D6C0000DCA2E0 Cast/7 R5210/S28012 Map: 30 Low: 14459616
[0] SpellID: 27795 (27795)
[0] SpellXSpellVisualID: 0
[0] Flags: 513 (513)
[0] ActiveFlags: 7
[0] CastLevel: 53
[0] Applications: 0
[0] ContentTuningID: 0
[0] HasCastUnit: False
[0] HasDuration: False
[0] HasRemaining: False
[0] HasTimeMod: False
[0] PointsCount: 0
[0] EstimatedPoints: 0
[0] HasContentTuning: False
UnitGUID: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269

ServerToClient: SMSG_SPELL_GO (0x2C39) Length: 136 ConnIdx: 1 Time: 01/10/2022 22:19:28.672 Number: 932019
(Cast) CasterGUID: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
(Cast) CasterUnit: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
(Cast) CastID: Full: 0xBC516803C0188303006D6C0005DCA2E0 Cast/3 R5210/S28012 Map: 30 Low: 98345696
(Cast) OriginalCastID: Full: 0xBC516803C01B2CC3006D6C00055CA2E0 Cast/3 R5210/S28012 Map: 30 Low: 89957088
(Cast) SpellID: 25100 (25100)
(Cast) SpellXSpellVisualID: 250313
(Cast) CastFlags: 17161
(Cast) CastFlagsEx: 16
(Cast) CastTime: 1172061220
(Cast) (MissileTrajectory) TravelTime: 0
(Cast) (MissileTrajectory) Pitch: 0
(Cast) DestLocSpellCastIndex: 7
(Cast) (Immunities) School: 0
(Cast) (Immunities) Value: 0
(Cast) (Predict) Points: 0
(Cast) (Predict) Type: 0
(Cast) (Predict) BeaconGUID: Full: 0x0
(Cast) HitTargetsCount: 0
(Cast) MissTargetsCount: 0
(Cast) MissStatusCount: 0
(Cast) RemainingPowerCount: 0
(Cast) HasRuneData: False
(Cast) TargetPointsCount: 0
(Cast) HasAmmoDisplayId: False
(Cast) HasAmmoInventoryType: False
(Cast) (Target) Flags: 64 (DestinationLocation)
(Cast) (Target) HasSrcLocation: False
(Cast) (Target) HasDstLocation: True
(Cast) (Target) HasOrientation: True
(Cast) (Target) hasMapID : True
(Cast) (Target) Unit: Full: 0x0
(Cast) (Target) Item: Full: 0x0
(DstLocation) Transport: Full: 0x0
(DstLocation) Location: X: 674.771 Y: -292.4943 Z: 30.57972
(Cast) (Target) Orientation: 4.212881088256835937
(Cast) (Target) MapID: 30
(Cast) (Target) Name:

**Comment by ratkosrb** [comment]
I see in cmangos they cast spell 27965 once it expires, do you see that in your sniff?

**Comment by Daribon** [comment]
Yes, here is the ending of Spirit of Redemption from the same guid during two occasions:

> ServerToClient: SMSG_MOVE_SPLINE_UNROOT (0x2E1A) Length: 9 ConnIdx: 1 Time: 01/10/2022 22:19:31.000 Number: 932497
> MoverGUID: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
> 
> ServerToClient: SMSG_AURA_UPDATE (0x2C22) Length: 15 ConnIdx: 1 Time: 01/10/2022 22:19:31.000 Number: 932498
> UpdateAll: False
> AurasCount: 2
> [0] Slot: 0
> [0] HasAura: False
> [1] Slot: 1
> [1] HasAura: False
> UnitGUID: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
> 
> ServerToClient: SMSG_AURA_UPDATE (0x2C22) Length: 13 ConnIdx: 1 Time: 01/10/2022 22:19:31.000 Number: 932499
> UpdateAll: False
> AurasCount: 1
> [0] Slot: 2
> [0] HasAura: False
> UnitGUID: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
> 
> 
> ServerToClient: SMSG_CANCEL_AUTO_REPEAT (0x26D5) Length: 9 ConnIdx: 1 Time: 01/10/2022 22:19:31.000 Number: 932504
> Guid: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
> 
> ServerToClient: SMSG_SPELL_CHANNEL_UPDATE (0x2C35) Length: 13 ConnIdx: 1 Time: 01/10/2022 22:19:31.016 Number: 932505
> CasterGUID: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
> TimeRemaining: 0
> 
> ServerToClient: SMSG_ON_MONSTER_MOVE (0x2DD4) Length: 63 ConnIdx: 1 Time: 01/10/2022 22:19:31.016 Number: 932506
> MoverGUID: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
> Position: X: 674.771 Y: -292.4943 Z: 30.57972
> (MovementMonsterSpline) Id: 163928
> (MovementMonsterSpline) Destination: X: 0 Y: 0 Z: 0
> (MovementMonsterSpline) CrzTeleport: False
> (MovementMonsterSpline) StopDistanceTolerance: 2
> (MovementMonsterSpline) (MovementSpline) Flags: 0 (None)
> (MovementMonsterSpline) (MovementSpline) Elapsed: 0
> (MovementMonsterSpline) (MovementSpline) MoveTime: 0
> (MovementMonsterSpline) (MovementSpline) FadeObjectTime: 0
> (MovementMonsterSpline) (MovementSpline) Mode: 0
> (MovementMonsterSpline) (MovementSpline) TransportGUID: Full: 0x0
> (MovementMonsterSpline) (MovementSpline) VehicleSeat: 0
> (MovementMonsterSpline) (MovementSpline) Face: 0 (None)
> (MovementMonsterSpline) (MovementSpline) PointsCount: 0
> (MovementMonsterSpline) (MovementSpline) VehicleExitVoluntary: False
> (MovementMonsterSpline) (MovementSpline) Interpolate: False
> (MovementMonsterSpline) (MovementSpline) PackedDeltasCount: 0
> (MovementMonsterSpline) (MovementSpline) HasSplineFilter: False
> (MovementMonsterSpline) (MovementSpline) HasSpellEffectExtraData: False
> (MovementMonsterSpline) (MovementSpline) HasJumpExtraData: False
> (MovementMonsterSpline) (MovementSpline) HasAnimTierTransition: False
> (MovementMonsterSpline) (MovementSpline) CalculatedSpeedXY: NaN
> 
> ServerToClient: SMSG_SPELL_INSTAKILL_LOG (0x2C33) Length: 22 ConnIdx: 1 Time: 01/10/2022 22:19:31.016 Number: 932507
> Target: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
> Caster: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
> SpellID: 27965 (27965)
> 
> ServerToClient: SMSG_SPELL_GO (0x2C39) Length: 109 ConnIdx: 1 Time: 01/10/2022 22:19:31.016 Number: 932508
> (Cast) CasterGUID: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
> (Cast) CasterUnit: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
> (Cast) CastID: Full: 0xBC516803C01B4F43006D6C00065CA2E2 Cast/3 R5210/S28012 Map: 30 Low: 106734306
> (Cast) OriginalCastID: Full: 0x0
> (Cast) SpellID: 27965 (27965)
> (Cast) SpellXSpellVisualID: 250783
> (Cast) CastFlags: 265
> (Cast) CastFlagsEx: 1048592
> (Cast) CastTime: 1172063558
> (Cast) (MissileTrajectory) TravelTime: 0
> (Cast) (MissileTrajectory) Pitch: 0
> (Cast) DestLocSpellCastIndex: 0
> (Cast) (Immunities) School: 0
> (Cast) (Immunities) Value: 0
> (Cast) (Predict) Points: 0
> (Cast) (Predict) Type: 0
> (Cast) (Predict) BeaconGUID: Full: 0x0
> (Cast) HitTargetsCount: 1
> (Cast) MissTargetsCount: 0
> (Cast) MissStatusCount: 0
> (Cast) RemainingPowerCount: 0
> (Cast) HasRuneData: False
> (Cast) TargetPointsCount: 0
> (Cast) HasAmmoDisplayId: False
> (Cast) HasAmmoInventoryType: False
> (Cast) (Target) Flags: 2 (Unit)
> (Cast) (Target) HasSrcLocation: False
> (Cast) (Target) HasDstLocation: False
> (Cast) (Target) HasOrientation: False
> (Cast) (Target) hasMapID : False
> (Cast) (Target) Unit: Full: 0x0
> (Cast) (Target) Item: Full: 0x0
> (Cast) (Target) Name: 
> (Cast) [0] HitTarget: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
> 

And yet again some minutes later:

> ServerToClient: SMSG_MOVE_SPLINE_UNROOT (0x2E1A) Length: 9 ConnIdx: 1 Time: 01/10/2022 22:22:05.016 Number: 953424
> MoverGUID: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
> 
> ServerToClient: SMSG_AURA_UPDATE (0x2C22) Length: 15 ConnIdx: 1 Time: 01/10/2022 22:22:05.016 Number: 953425
> UpdateAll: False
> AurasCount: 2
> [0] Slot: 0
> [0] HasAura: False
> [1] Slot: 1
> [1] HasAura: False
> UnitGUID: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
> 
> ServerToClient: SMSG_AURA_UPDATE (0x2C22) Length: 13 ConnIdx: 1 Time: 01/10/2022 22:22:05.016 Number: 953426
> UpdateAll: False
> AurasCount: 1
> [0] Slot: 2
> [0] HasAura: False
> UnitGUID: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
> 
> ServerToClient: SMSG_ON_MONSTER_MOVE (0x2DD4) Length: 63 ConnIdx: 1 Time: 01/10/2022 22:22:05.016 Number: 953427
> MoverGUID: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
> Position: X: 659.19965 Y: -303.76505 Z: 30.25431
> (MovementMonsterSpline) Id: 194010
> (MovementMonsterSpline) Destination: X: 0 Y: 0 Z: 0
> (MovementMonsterSpline) CrzTeleport: False
> (MovementMonsterSpline) StopDistanceTolerance: 2
> (MovementMonsterSpline) (MovementSpline) Flags: 0 (None)
> (MovementMonsterSpline) (MovementSpline) Elapsed: 0
> (MovementMonsterSpline) (MovementSpline) MoveTime: 0
> (MovementMonsterSpline) (MovementSpline) FadeObjectTime: 0
> (MovementMonsterSpline) (MovementSpline) Mode: 0
> (MovementMonsterSpline) (MovementSpline) TransportGUID: Full: 0x0
> (MovementMonsterSpline) (MovementSpline) VehicleSeat: 0
> (MovementMonsterSpline) (MovementSpline) Face: 0 (None)
> (MovementMonsterSpline) (MovementSpline) PointsCount: 0
> (MovementMonsterSpline) (MovementSpline) VehicleExitVoluntary: False
> (MovementMonsterSpline) (MovementSpline) Interpolate: False
> (MovementMonsterSpline) (MovementSpline) PackedDeltasCount: 0
> (MovementMonsterSpline) (MovementSpline) HasSplineFilter: False
> (MovementMonsterSpline) (MovementSpline) HasSpellEffectExtraData: False
> (MovementMonsterSpline) (MovementSpline) HasJumpExtraData: False
> (MovementMonsterSpline) (MovementSpline) HasAnimTierTransition: False
> (MovementMonsterSpline) (MovementSpline) CalculatedSpeedXY: NaN
> 
> ServerToClient: SMSG_CANCEL_AUTO_REPEAT (0x26D5) Length: 9 ConnIdx: 1 Time: 01/10/2022 22:22:05.016 Number: 953428
> Guid: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
> 
> ServerToClient: SMSG_SPELL_CHANNEL_UPDATE (0x2C35) Length: 13 ConnIdx: 1 Time: 01/10/2022 22:22:05.016 Number: 953429
> CasterGUID: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
> TimeRemaining: 0
> 
> ServerToClient: SMSG_ON_MONSTER_MOVE (0x2DD4) Length: 63 ConnIdx: 1 Time: 01/10/2022 22:22:05.016 Number: 953430
> MoverGUID: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
> Position: X: 659.19965 Y: -303.76505 Z: 30.25431
> (MovementMonsterSpline) Id: 194011
> (MovementMonsterSpline) Destination: X: 0 Y: 0 Z: 0
> (MovementMonsterSpline) CrzTeleport: False
> (MovementMonsterSpline) StopDistanceTolerance: 2
> (MovementMonsterSpline) (MovementSpline) Flags: 0 (None)
> (MovementMonsterSpline) (MovementSpline) Elapsed: 0
> (MovementMonsterSpline) (MovementSpline) MoveTime: 0
> (MovementMonsterSpline) (MovementSpline) FadeObjectTime: 0
> (MovementMonsterSpline) (MovementSpline) Mode: 0
> (MovementMonsterSpline) (MovementSpline) TransportGUID: Full: 0x0
> (MovementMonsterSpline) (MovementSpline) VehicleSeat: 0
> (MovementMonsterSpline) (MovementSpline) Face: 0 (None)
> (MovementMonsterSpline) (MovementSpline) PointsCount: 0
> (MovementMonsterSpline) (MovementSpline) VehicleExitVoluntary: False
> (MovementMonsterSpline) (MovementSpline) Interpolate: False
> (MovementMonsterSpline) (MovementSpline) PackedDeltasCount: 0
> (MovementMonsterSpline) (MovementSpline) HasSplineFilter: False
> (MovementMonsterSpline) (MovementSpline) HasSpellEffectExtraData: False
> (MovementMonsterSpline) (MovementSpline) HasJumpExtraData: False
> (MovementMonsterSpline) (MovementSpline) HasAnimTierTransition: False
> (MovementMonsterSpline) (MovementSpline) CalculatedSpeedXY: NaN
> 
> ServerToClient: SMSG_SPELL_INSTAKILL_LOG (0x2C33) Length: 22 ConnIdx: 1 Time: 01/10/2022 22:22:05.016 Number: 953431
> Target: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
> Caster: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
> SpellID: 27965 (27965)
> 
> ServerToClient: SMSG_SPELL_GO (0x2C39) Length: 109 ConnIdx: 1 Time: 01/10/2022 22:22:05.016 Number: 953432
> (Cast) CasterGUID: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
> (Cast) CasterUnit: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
> (Cast) CastID: Full: 0xBC516803C01B4F43006D6C000A5CA37C Cast/3 R5210/S28012 Map: 30 Low: 173843324
> (Cast) OriginalCastID: Full: 0x0
> (Cast) SpellID: 27965 (27965)
> (Cast) SpellXSpellVisualID: 250783
> (Cast) CastFlags: 265
> (Cast) CastFlagsEx: 1048592
> (Cast) CastTime: 1172217558
> (Cast) (MissileTrajectory) TravelTime: 0
> (Cast) (MissileTrajectory) Pitch: 0
> (Cast) DestLocSpellCastIndex: 0
> (Cast) (Immunities) School: 0
> (Cast) (Immunities) Value: 0
> (Cast) (Predict) Points: 0
> (Cast) (Predict) Type: 0
> (Cast) (Predict) BeaconGUID: Full: 0x0
> (Cast) HitTargetsCount: 1
> (Cast) MissTargetsCount: 0
> (Cast) MissStatusCount: 0
> (Cast) RemainingPowerCount: 0
> (Cast) HasRuneData: False
> (Cast) TargetPointsCount: 0
> (Cast) HasAmmoDisplayId: False
> (Cast) HasAmmoInventoryType: False
> (Cast) (Target) Flags: 2 (Unit)
> (Cast) (Target) HasSrcLocation: False
> (Cast) (Target) HasDstLocation: False
> (Cast) (Target) HasOrientation: False
> (Cast) (Target) hasMapID : False
> (Cast) (Target) Unit: Full: 0x0
> (Cast) (Target) Item: Full: 0x0
> (Cast) (Target) Name: 
> (Cast) [0] HitTarget: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
> 
> ServerToClient: SMSG_UPDATE_OBJECT (0x27C3) Length: 333 ConnIdx: 1 Time: 01/10/2022 22:22:05.031 Number: 953434
> NumObjUpdates: 3
> MapID: 30 (30)
> HasRemovedObjects: False
> Data size: 322
> [0] UpdateType: Values
> [0] Object Guid: Full: 0x0851D8000000000000000000012F01E3 Player/0 R5238/S0 Map: 0 Low: 19857891
> [0] UNIT_FIELD_POWER: 360/5.04E-43
> [1] UpdateType: Values
> [1] Object Guid: Full: 0x20516803C00D4C40006D6C00005C9FFE Creature/0 R5210/S28012 Map: 30 Entry: 13617 Low: 6070270
> [1] UNIT_FIELD_HEALTH: 27848
> [1] UNIT_FIELD_HEALTH + 1: 0
> [2] UpdateType: Values
> [2] Object Guid: Full: 0x0851DC00000000000000000001319B6D Player/0 R5239/S0 Map: 0 Low: 20028269
> [2] UNIT_FIELD_HEALTH: 0
> [2] UNIT_FIELD_HEALTH + 1: 0
> [2] UNIT_FIELD_POWER: 0/0
> [2] UNIT_FIELD_FLAGS: 67371016
> [2] UNIT_FIELD_BOUNDINGRADIUS: 0.208
> [2] UNIT_FIELD_COMBATREACH: 1.5
> [2] UNIT_FIELD_DISPLAYID: 50
> [2] UNIT_FIELD_BYTES_2: 0/1/0/0
> [2] PLAYER_FLAGS: 0/0
> 
>

**Comment by Daribon** [comment]
You can see the suicide spell going off at this point in the video: https://youtu.be/IByonxXP_PI?si=vsMXMASnI-VvF5dj&t=39
It is what causes the blood effect.
