### ISSUE TITLE
Elemental Invasion boss can't be killed

### ISSUE THREAD

**Issue by hyphenz** [vmangos/core#89]
creature 14461 Baron Charr can't be killed.
when player get close to Baron Charr,  start combat, and auto stop combat...
and the same problem with creatures in 14454, 14457, 14464 by entry.
they are all Elemental Invasion boss.
another question: why i can't find creature 14464 in map. it should be in Azshara Crater.

**Comment by ratkosrb** [comment]
Fixed the evade bug -> https://github.com/vmangos/core/commit/8b8742110f9e3533ba77d8209ce051135687ef6f

Avalanchion spawns in Azshara once you have killed enough elemental invaders. Nothing wrong with him.
![wowscrnshot_123018_151900](https://user-images.githubusercontent.com/35845488/50547649-becf2000-0c46-11e9-9e85-d54c5cb39700.jpg)

**Comment by hyphenz** [comment]
thx for fixed :)
