### ISSUE TITLE
"A Little Slime Goes a Long Way" quest

### ISSUE THREAD

**Issue by T1ti** [vmangos/core#899]
**Current behavior**: 
Using the Empty Pure Sample Jar on the Oozes in Un'goro doesn't despawn the corpse after use. so players can just up all 10 of the items to get the Filled version. 
**Expected behavior**: 
Corpse should despawn

**Client version**: 
1.12
version : latest
**Operating system**: 
windows

**Comment by ghost** [comment]
Expected behavior:
https://youtu.be/MoxXqZKI2DY?t=602

**Comment by ratkosrb** [comment]
This was fixed.
https://github.com/vmangos/core/commit/c1db8e8f625ba5dbba3c03a11eafb4411e1557db
