### ISSUE TITLE
I have an idea...

### ISSUE THREAD

**Issue by DarkmoonRabbit** [vmangos/core#90]
After Blizzard released Vanilla Warcraft in 2019, can we use Blizzard's HD client?

**Comment by ratkosrb** [comment]
No, it's not possible. The new Classic client is based upon the Legion 7.3.5 client, which is absolutely incompatible with original Vanilla emulators. You won't even be able to login to the account, because the new clients only support Battle.Net authentication.

**Comment by Kittnz** [comment]
It's gonne be a new core project.
