### ISSUE TITLE
[NPC] 4 Missing NPCs in Azshara

### ISSUE THREAD

**Issue by ghost** [vmangos/core#900]
**Current behavior**: 
There are 4 NPCs currently missing in vmangos Azshara: Second Mate Shandril, Roland Geardabbler, Horizon Scout Cook, Horizon Scout Engineer, and Horizon Scout First Mate.

**Expected behavior**: 
All 4 of these NPCs should exist, stationary, with no functionality or objectives. Roland Geardabbler has a visual mana shield and bubbles around him, unsure what spell he uses for that effect.

Screenshots from Classic WoW 1.13.6:

![Azshara Unused NPC](https://user-images.githubusercontent.com/4321583/101313260-d2686580-3823-11eb-9df2-90d7dd6874bb.png)
![Azshara Unused NPCs 2](https://user-images.githubusercontent.com/4321583/101313341-f6c44200-3823-11eb-885d-b31183a64fc2.png)

**Steps to reproduce**:

1. Head to Azshara, off the southern coast to find these NPCs. I'll update with exact coordinates later
2. Check the same location on the other client (Classic or Vmangos).

**Client version**: 
1.12.1

**Operating system**: 
Windows 10

**Comment by klltm** [comment]
.npc spawn add

**Comment by alexkulya** [comment]
<pre>
INSERT INTO `creature` (`guid`, `id`, `map`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecsmin`, `spawntimesecsmax`, `wander_distance`, `movement_type`) VALUES
(160359, 8387, 1, 1747.24, -5859.6, -90.3817, 3.98543, 300, 300, 0, 0),
(160360, 8388, 1, 1747.62, -5862.27, -90.9249, 3.17332, 300, 300, 0, 0),
(160361, 8389, 1, 1748.87, -5863.46, -90.2665, 2.83088, 300, 300, 0, 0),
(160362, 8394, 1, 1746.45, -5861.29, -91.4165, 3.20841, 300, 300, 0, 0),
(160363, 8478, 1, 1916.44, -5733.37, 10.1936, 4.10397, 300, 300, 0, 0);

UPDATE `creature_template` SET `inhabit_type` = 1 WHERE `entry` IN (8387, 8388, 8389, 8394);

INSERT INTO `creature_addon` (`guid`, `stand_state`, `sheath_state`, `auras`) VALUES
(160363, 8, 1, "");
</pre>

**Comment by T1ti** [comment]
> .npc spawn add

You don't do that, you sniff it from classic instead to have accurate data

**Comment by ulfgebhardt** [comment]
@alexkulya Could you make a PR for your Contribution? <3

**Comment by NickTyrer** [comment]
I have added the fix to my PR so it doesnt get lost in the comments.
fixed in #1036

**Comment by alexkulya** [comment]
Оne feature, the gnome's shield is missing. I have not found information about ID.

**Comment by NickTyrer** [comment]
@alexkulya thanks, will see if I can find out more.
