### ISSUE TITLE
Stats error for undead mage

### ISSUE THREAD

**Issue by T1ti** [vmangos/core#902]
**Current behavior**: 
![udmage](https://user-images.githubusercontent.com/40864460/101847910-95b6aa00-3b54-11eb-8b2e-fdd43c469f4f.png)
Spirit and intellect values are wrong for level 1

**Expected behavior**: 
It should be 21 int and 27 spirit https://www.warcrafttavern.com/wow-classic/tools/raceclass/ (also verified on classic)

**Client version**: 
1.12
**Commit hash**: 
latest

**Comment by NickTyrer** [comment]
Similar bug is noted in #237

**Comment by T1ti** [comment]
Also regarding gnome mage, I noticed the intellect racial bonus is added to base stats directly instead of being a bonus stat like on classic, I think this was done because that's how wikis did it and private servers just copied wikis I guess. 
![gnome mage](https://user-images.githubusercontent.com/40864460/101938661-078a0480-3be4-11eb-9764-8cef31de00bf.png)

Back to the topic, the stat error for the undead is clearly just a typo, inversed spirit and int. It actually causes the tooltip to bug and not update until you relog, because the base stat reduce when you level up and the client/core doesn't understand it

**Comment by Daribon** [comment]
![WowClassic_Bqi9dEVRMG](https://user-images.githubusercontent.com/6137576/101971107-0c27da80-3c2f-11eb-8465-e6e13627a8bf.png)
Level 1 gnome mage in classic

**Comment by magicstone4** [comment]
Tauren Druids (not sure if Night Elves too) also have wrong stats, they start with absolutely no mana compared to Classic and Vanilla.

**Comment by Daribon** [comment]
Can confirm that stats are different compared to classic.
I don't have any proof from vanilla.

Mage level 1 on vmangos:
![WoW_kliFJyOBz2](https://user-images.githubusercontent.com/6137576/192128159-ef46e6bb-562c-417b-b6f5-38d2eecfafac.png)

Mage level 1 on classic:
![WowClassicT_0eoFl09GA8](https://user-images.githubusercontent.com/6137576/192128168-0840d369-1376-4344-bbfe-cc9354929afb.png)

**Comment by NickTyrer** [comment]
CLosed in https://github.com/vmangos/core/pull/1630
