### ISSUE TITLE
[Event] Winter Veil a Few Issues

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#907]
**Current behavior**: 
1. Mistletoe gameobject missing from:
    - Stonetalon Peak Inn (also  Winter Revelers missing)

**Client version**: 
1.12.1
**Commit hash**: 
7954585
**Operating system**: 
Win 10

**Comment by Oroxzy** [comment]
also missing at some spots (178437, 178556, 178649):
![WoWScrnShot_121620_114614](https://user-images.githubusercontent.com/357606/102339762-f0f1fd80-3f95-11eb-8ab7-fc0d8c6b9251.jpg)

**Comment by NickTyrer** [comment]
This is how the gifts under the tree work on and after the 25th https://youtu.be/nSCknht-4KE
