### ISSUE TITLE
Error messages with gameobjects

### ISSUE THREAD

**Issue by darkmord1991** [vmangos/core#91]
**Current behavior**: 
Gameobject (GUID: 4000590) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8876.853516 Y: 593.677124 Z: 161.039902) ang: 0.139625 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000593) not created: Entry 180851 does not exist in `gameobject_template`. Map: 0  (X: -8919.748047 Y: 552.298584 Z: 166.045303) ang: 3.996807 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000598) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8943.316406 Y: 516.019104 Z: 145.943802) ang: 5.846854 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000599) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8883.328125 Y: 579.673584 Z: 162.191193) ang: 0.628317 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000601) not created: Entry 180851 does not exist in `gameobject_template`. Map: 0  (X: -8919.692383 Y: 482.909698 Z: 175.647095) ang: 3.735006 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000603) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8919.748047 Y: 552.298584 Z: 166.045303) ang: 3.996807 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000607) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8898.135742 Y: 566.423584 Z: 176.528198) ang: 6.091200 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000610) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8882.171875 Y: 574.421875 Z: 171.712402) ang: 6.091200 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000611) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8881.462891 Y: 592.391418 Z: 110.883751) ang: 0.464518 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000614) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8951.743164 Y: 611.494812 Z: 175.302704) ang: 3.630291 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000616) not created: Entry 180851 does not exist in `gameobject_template`. Map: 0  (X: -8952.892578 Y: 629.274292 Z: 178.272202) ang: 0.942477 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000621) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8878.850586 Y: 583.177124 Z: 156.149002) ang: 3.700105 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000622) not created: Entry 180851 does not exist in `gameobject_template`. Map: 0  (X: -8843.524414 Y: 481.786499 Z: 169.664001) ang: 0.925024 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000628) not created: Entry 180851 does not exist in `gameobject_template`. Map: 0  (X: -8938.404297 Y: 511.885406 Z: 169.513199) ang: 0.471238 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000629) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8951.743164 Y: 611.494812 Z: 175.302704) ang: 3.630291 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000631) not created: Entry 180851 does not exist in `gameobject_template`. Map: 0  (X: -8854.853516 Y: 503.411499 Z: 184.633606) ang: 3.630291 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000633) not created: Entry 180851 does not exist in `gameobject_template`. Map: 0  (X: -8874.944336 Y: 575.500000 Z: 165.774597) ang: 0.907570 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000634) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8871.923828 Y: 609.732727 Z: 141.636398) ang: 0.855210 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000637) not created: Entry 180851 does not exist in `gameobject_template`. Map: 0  (X: -8888.692383 Y: 571.265015 Z: 120.368858) ang: 0.601966 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000641) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8874.944336 Y: 575.500000 Z: 165.774597) ang: 0.907570 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000643) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8848.866211 Y: 488.828094 Z: 174.977707) ang: 3.961899 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000645) not created: Entry 180851 does not exist in `gameobject_template`. Map: 0  (X: -8972.651367 Y: 531.079895 Z: 166.674393) ang: 4.886924 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000646) not created: Entry 180851 does not exist in `gameobject_template`. Map: 0  (X: -8957.122070 Y: 517.701416 Z: 151.322601) ang: 3.630291 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000651) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8961.319336 Y: 533.333313 Z: 152.537201) ang: 3.961899 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000661) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8839.778320 Y: 576.800415 Z: 153.287292) ang: 0.855210 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000665) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8859.801758 Y: 567.184021 Z: 152.990906) ang: 3.473210 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Next game event check in 120 seconds.
Gameobject (GUID: 4000678) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8894.599609 Y: 556.861877 Z: 145.843689) ang: 2.113046 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000681) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8873.700195 Y: 570.241821 Z: 139.338882) ang: 0.762973 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000695) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8878.850586 Y: 583.177124 Z: 155.572601) ang: 3.700105 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000696) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8856.230469 Y: 573.789795 Z: 131.861237) ang: 5.707060 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000702) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8983.513672 Y: 659.492981 Z: 188.624802) ang: 3.630291 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000710) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8839.778320 Y: 576.800415 Z: 153.287292) ang: 0.855210 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000711) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8887.023438 Y: 594.304077 Z: 132.571243) ang: 5.306580 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000713) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8883.004883 Y: 590.192688 Z: 153.126404) ang: 0.977383 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000718) not created: Entry 180851 does not exist in `gameobject_template`. Map: 0  (X: -8968.125000 Y: 525.128479 Z: 171.930405) ang: 3.054327 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000724) not created: Entry 180851 does not exist in `gameobject_template`. Map: 0  (X: -8849.722656 Y: 624.133728 Z: 134.035706) ang: 0.855210 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000725) not created: Entry 180851 does not exist in `gameobject_template`. Map: 0  (X: -8872.734375 Y: 573.338440 Z: 117.723770) ang: 1.831103 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000726) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8954.138672 Y: 507.569489 Z: 168.860992) ang: 3.595379 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000728) not created: Entry 180851 does not exist in `gameobject_template`. Map: 0  (X: -8887.629883 Y: 582.026123 Z: 170.218994) ang: 3.787367 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000731) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8872.734375 Y: 573.338440 Z: 117.723770) ang: 1.831103 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000733) not created: Entry 180851 does not exist in `gameobject_template`. Map: 0  (X: -8965.388672 Y: 525.890625 Z: 160.266403) ang: 2.199115 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000740) not created: Entry 180851 does not exist in `gameobject_template`. Map: 0  (X: -8861.381836 Y: 574.741272 Z: 152.157501) ang: 3.473210 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000744) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8878.850586 Y: 583.177124 Z: 156.301804) ang: 3.700105 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000746) not created: Entry 180851 does not exist in `gameobject_template`. Map: 0  (X: -8980.363281 Y: 546.793396 Z: 170.468597) ang: 4.660030 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000748) not created: Entry 180851 does not exist in `gameobject_template`. Map: 0  (X: -8843.524414 Y: 481.786499 Z: 169.664001) ang: 0.925024 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000749) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8961.998047 Y: 640.185791 Z: 178.279800) ang: 0.628317 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000752) not created: Entry 180851 does not exist in `gameobject_template`. Map: 0  (X: -8836.876953 Y: 574.164917 Z: 158.050598) ang: 0.855210 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000753) not created: Entry 180851 does not exist in `gameobject_template`. Map: 0  (X: -8843.524414 Y: 481.786499 Z: 169.664001) ang: 0.925024 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000757) not created: Entry 180851 does not exist in `gameobject_template`. Map: 0  (X: -8843.524414 Y: 481.786499 Z: 169.664001) ang: 0.925024 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000760) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8884.809570 Y: 576.020081 Z: 110.489868) ang: 0.621592 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000765) not created: Entry 180851 does not exist in `gameobject_template`. Map: 0  (X: -8815.911133 Y: 460.204895 Z: 169.458496) ang: 3.926996 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000768) not created: Entry 180851 does not exist in `gameobject_template`. Map: 0  (X: -8851.988281 Y: 486.562500 Z: 169.663498) ang: 4.258607 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
Gameobject (GUID: 4000770) not created: Entry 180858 does not exist in `gameobject_template`. Map: 0  (X: -8961.319336 Y: 533.333313 Z: 152.537201) ang: 3.961899 rotation0: 0.000000 rotation1: 0.000000 rotation2: 0.000000 rotation3: 0.000000
**Expected behavior**: 

**Steps to reproduce**:

1.  Let server run some days with low population

**Client version**: 
1.12.1
**Commit hash**: 
Core revision: d2c7a65f212f50886ebd / 2018-12-26 13:17:35 +0200 / Win64 (little-endian)
**Operating system**: 
Win Server 2016

Maybe you can take a look.

**Comment by ratkosrb** [comment]
Seems like two gameobjects spawned by the holiday fireworks npc were deleted by mistake.

**Comment by ratkosrb** [comment]
Fixed here -> https://github.com/vmangos/core/commit/a14c2d9564e0da57126ee5b72ec993c982853729
