### ISSUE TITLE
[Quest] Missing Quest Script - Ursal the Mauler (486)

### ISSUE THREAD

**Issue by NickTyrer** [vmangos/core#913]
**Current behavior**: 
see:
https://github.com/the-hyjal-project/bugtracker/issues/60

**Expected behavior**: 
see:
https://youtu.be/vSyTQxPJ-rg?t=61

cmangos script:
https://github.com/cmangos/classic-db/commit/32c89f4d2d37777e654093b272455d21b1f75ca0

**Client version**: 
1.12.1
**Commit hash**: 
250e528
**Operating system**: 
Win 10

**Comment by ulfgebhardt** [comment]
@NickTyrer Can you PR the cmangos commit? <3

**Comment by NickTyrer** [comment]
@ulfgebhardt brotalnia has a tool that can script it using the sniff data to make it 100% blizlike. Better waiting for that.

**Comment by ulfgebhardt** [comment]
kk! But I would assume the cmangos team did the same - thats where they are quite reliable at ;)

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/f7e05b063cb778c471152387f561410aed4de97c
