### ISSUE TITLE
BIG ISSUE - you can get out of range on mobs in moonkin form to become unattackble![ALLIANCE ONLY]

### ISSUE THREAD

**Issue by jaywalker15262** [vmangos/core#914]
**Current behavior**: 
If you move backwards carefully whilst in moonkin form, you can get just out of melee ranges of mob to make them not close the gap to you. THIS DOES NOT WORK ON ALL MOBS. I tested and it doesnt appear to work on smaller mobs in Elwynn forest. It also is not an issue for Taurens. I assume because they have a longer bounding radius while unmorphed. The issue might be that the bounding radius is not increased when Night Elfs morph in to Boomkins.

THIS WORKS ON BOSSES TO! I can effectively avoid Naxxrammas bosses's auto hits in moonkin form.

**Expected behavior**: 
Not to become unattackable. This is obviously a huge bug and so easily abuseable.

**Steps to reproduce**:

1. Went to winterspring or un'goro or other place with big mobs.
2. Found a mob.
3. Attacked mob in Moonkin form and stepped out of its melee range.

**Client version**: 1.12

**Commit hash**: same both for older and newer versions of the core.

**Operating system**: windows 10

[Screenshot proof, visual representation](https://i.imgur.com/3GXfEL5.png)

**Comment by ratkosrb** [comment]
Sounds like a bug in ChaseMovementGenerator, perhaps it does not calculate max distance correctly.

**Comment by jaywalker15262** [comment]
No the distance calculated is correct, why I say this because it is keeping the same distance to me in moonkin form as Nelf as it does when im in moonkin form as a Tauren. Otherwise the bug would have been present for both moonkin taurens and moonkin nelfs. But Taurens have naturally a longer melee range. Means u can both attack them from a longer distance, and they can also hit you from a further distance.

When I transform as Nelf into Boomkin I see the big red circle beneat my feet get larger, indicating that I probably would have a bigger bounding radius? I do not know if this is correct. But I do not notice that I am able to attack from a further distance regardless of this. Maybe the range from which you can attack or cannot get attacked is not updated to be in accordance to the bounding radius of moonkin form, or vice versa. which the creature uses to decide if it can attack u. It assumes it can attack you from that range, which is why it is not closing the distance. And that very distance, is a distance which it can attack me from while in Moonkin Form as a Tauren! That is just my guess, because it hasnt calculated the distance incorrectly b4, I wouldnt like to think this very specific case is a bug in the general logic and math behind the max distance calucation, otherwise it wouldnt bug out only for Moonkin Nelfs. This is something specifically wrong with Moonkin Form, I like to believe at least.

**Comment by jaywalker15262** [comment]
UPDATE `creature_display_info_addon` SET `bounding_radius` = '1.5', `combat_reach` = '1.5' WHERE (`display_id` = '15374') and (`build` = '4878');

There you go, I set it to the same values as the displayid for taurens. For some reason the nelf one had a bounding of 2.0 and a combat_reach of 1.0. LOL!

Can you check if these values were the same in a super old world db? Maybe someone made a mistake or something.

Either that or these are the values the display id needs to have cuz of some mob with this display_id, but I doubt it.
