### ISSUE TITLE
coredump 2

### ISSUE THREAD

**Issue by chendh123** [vmangos/core#92]
Next game event check in 120 seconds.
Received SIGSEGV
./mangosd(_ZNK14dtNavMeshQuery15getPortalPointsEmPK6dtPolyPK10dtMeshTilemS2_S5_PfS6_+0x233) [0xe5dc33]
./mangosd(_ZNK14dtNavMeshQuery27findRandomPointAroundCircleEmPKffPK13dtQueryFilterPFfvEPmPf+0x4c4) [0xe5e2a4]
./mangosd(_ZNK3Map21GetWalkRandomPositionEP9TransportRfS2_S2_fj+0x39e) [0x808b3e]
./mangosd(_ZNK11WorldObject14GetRandomPointEffffRfS0_S0_+0xbe) [0x8b3dfe]
./mangosd(_ZN23RandomMovementGenerator18_setRandomLocationER8Creature+0x235) [0x85f555]
./mangosd(_ZN23RandomMovementGenerator11UpdateAsyncER8Creaturej+0xa5) [0x85f755]
./mangosd(_ZN12MotionMaster17UpdateMotionAsyncEj+0x45) [0x855dd5]
./mangosd(_ZN4Unit6UpdateEjj+0x779) [0x96b599]
./mangosd(_ZN8Creature6UpdateEjj+0xa9) [0x890ba9]
./mangosd(_ZN3Map5VisitIN6MaNGOS13ObjectUpdaterE16TypeMapContainerI8TypeListI10GameObjectS4_I8CreatureS4_I13DynamicObjectS4_I6Corpse8TypeNullEEEEEEEvRK4CellR20TypeContainerVisitorIT_T0_E+0x1a7) [0x81d217]
./mangosd(_ZN3Map11UpdateCellsEj+0x506) [0x820b76]
./mangosd(_ZN3Map6UpdateEj+0x144) [0x816ea4]
./mangosd(_ZN15MapAsyncUpdater3runEv+0x37) [0x82b127]
./mangosd(_ZN9ACE_Based6Thread10ThreadTaskEPv+0x27) [0xcd5e87]
/home/mangos/lib/libace.so(_ZN21ACE_OS_Thread_Adapter6invokeEv+0x86) [0x7f248093e336]
/lib64/libpthread.so.0(+0x7a51) [0x7f2480617a51]
/lib64/libc.so.6(clone+0x6d) [0x7f247fb3d93d]

**Comment by ratkosrb** [comment]
No idea why it would crash there. I don't believe anything about this code has been changed in a long time.

**Comment by w5860363** [comment]
> No idea why it would crash there. I don't believe anything about this code has been changed in a long time.

https://github.com/LightsHope/server/issues/888 Maybe it's related, but it's closed

**Comment by w5860363** [comment]
Maybe it's because of game event.

**Comment by ratkosrb** [comment]
I don't think it has anything to do with game events, the crash is in the Detour code. Have you enabled mmap preloading btw? It should be enabled for a production server.

```
Terrain.Preload.Continents = 1
Terrain.Preload.Instances  = 1
```

**Comment by chendh123** [comment]
It may have been repaired.
