### ISSUE TITLE
[Gameobject] Dolanar - Foodcrate Invalid Target

### ISSUE THREAD

**Issue by ulfgebhardt** [vmangos/core#921]
## [Gameobject] Dolanar - Foodcrate Invalid Target
![image](https://user-images.githubusercontent.com/1238238/103232968-2a365000-493c-11eb-9d6f-4bc34eb50bac.png)

This food crate in Dolanar gives `Invalid target` when trying to open it.

### Steps to reproduce

1. Go to Dolanar
2. Try to open Foodcrate in the Inn
3. ...
4. Profit

### Client version

1.12.1

### Commit hash

Latest

**Comment by Gamemechanicwow** [comment]
1. Go to your wow folder
2. Delete WDB
3. ...
4. Profit

Your clients cache contains data from a different patch.

**Comment by ulfgebhardt** [comment]
You are 100% correct @Gamemechanicwow <3
