### ISSUE TITLE
Ah Bot using higher bid price, than buyoutprice

### ISSUE THREAD

**Issue by darkmord1991** [vmangos/core#93]
**Current behavior**: 
![image](https://user-images.githubusercontent.com/811881/50584931-b9eeb400-0e72-11e9-84d8-1abd0cb4d7d3.png)

**Expected behavior**: 
Buyoutprice should be always higher

Other Feedback to AH Bot:
-No settings for items available
-in 15k items there are only 20 types of items or so

My idea:
Implement the one from trinitycore, would be the best thing. But i do not know how much work it is.
**Steps to reproduce**:

1. Use AH Bot and take a look.
2. 
3. 

**Client version**: 
1.12.1
**Commit hash**: 
Core revision: d2c7a65f212f50886ebd / 2018-12-26 13:17:35 +0200 / Win64 (little-endian)
**Operating system**: 
Win Server 2016

**Comment by ratkosrb** [comment]
Both the items it sells and the price are defined in the database. Check table `auctionhousebot` and add whatever items you want there.

**Comment by ratkosrb** [comment]
Fixed the reversed prices for the leather. https://github.com/vmangos/core/commit/12d76342c973e0a740135e1dbe383588cdd659a2

**Comment by darkmord1991** [comment]
Worked as it should. Thank you!
