### ISSUE TITLE
💬 [Discussion] Reenable Tests

### ISSUE THREAD

**Issue by ulfgebhardt** [vmangos/core#943]
## 💬 Discussion

One of the main Problems of PServers nowadays is the instability. One fix is supplied to fix an issue and 10 new issues appear for it. Automated testing is an approach to deal with those. Sadly no current core implements testing, but `Nostalrius` did :pray: .

As stated in the linked commit removing those test since they slow down compilation. Maybe we can make them optional via CMake and run them on CI to ensure everything is still working as expected.

Commit removing the tests: https://github.com/vmangos/core/commit/5d5cb48e443108db00b2df36d6910b664bdab310

From the [Nostalrius RIP Document](http://bfrontz.net/Nostalrius_post_mortem.pdf):

![image](https://user-images.githubusercontent.com/1238238/103421956-5e5d7b00-4b9f-11eb-8d51-0f152c4ee180.png)
![image](https://user-images.githubusercontent.com/1238238/103421989-8baa2900-4b9f-11eb-9041-5a94815651ae.png)

The [linked Video](https://www.youtube.com/watch?v=JozAj-wrBWw&feature=youtu.be&list=PLPgrywi0V6Q0h5HFZyHzia4W7nHkbrEp8&ab_channel=Nostalrius) showing how it works

**Comment by ratkosrb** [comment]
Nobody ever used this since Nostalrius closed. It didn't do anything useful. If somebody wants it, they can revert that commit on their fork, but I find that highly unlikely.

**Comment by ulfgebhardt** [comment]
Is there someone I can talk to to obtain the lua tests `Nostalrius` used according to the document linked above?
The tests included in the old Core are apparently still the c++ tests.
