### ISSUE TITLE
🐞 [Bug] Spell 29519 (Silithyst) should create Silithyst Mound (181597) on Cancel Aura.

### ISSUE THREAD

**Issue by Oroxzy** [vmangos/core#946]
https://github.com/Oroxzy/core/commit/d89feb7891673cd862ff5da530a7bff31045f032
https://github.com/Oroxzy/core/commit/a99a7fae390d73986e308e499c9536ed63fbeb9b

https://youtu.be/_YpumVmwybc?t=160

**Comment by Oroxzy** [comment]
I also remember where we all farmed dust and put it in front of the machine for people who grinded their ranks.

**Comment by ulfgebhardt** [comment]
As I see you have a fix ready in those two Commits you linked - is that correct @Oroxzy ?
Would you be willing to PR this?
