### ISSUE TITLE
Wrong code:void CharacterDatabaseCache::LoadPetAura(uint32 singlePetId)

### ISSUE THREAD

**Issue by chendh123** [vmangos/core#95]
![image](https://user-images.githubusercontent.com/15760697/50626254-21d2f680-0f68-11e9-8fa3-9ebb4858d2f1.png)

After field caster_guid , the value is wrong.

**Comment by ratkosrb** [comment]
Thank you, fixed it here -> https://github.com/vmangos/core/commit/03183cbcbbee1fe4e1633e209cf381e6530cb36c

**Comment by chendh123** [comment]
Thanks.
