### ISSUE TITLE
Polymorphe will break if the npc use shapeshift/transform

### ISSUE THREAD

**Issue by ghost** [vmangos/core#96]
**Current behavior**: 
When you polymorph a creature that has a transform/shapeshift spell, his shapeshift/transform will ignore the polymorph(change display model to the new tranform while keeping the polymorph debuff)

https://cdn-b-east.streamable.com/video/mp4/z2yxh.mp4?token=YuOf03wr40eIbEa-mrroQA&expires=1546545189

**Expected behavior**: 
Creature should not override polymorph

**Steps to reproduce**:

1.  Find a creature with a shapeshift/transform( e.g druid of the fang)
2.  polymorph him until he decide to use the spell
3. 

**Client version**: 
1.12.1

**Commit hash**: 
f371a194ce9204d35777baf127f181e5469bb6e0

**Operating system**: 
Ubuntu

**Comment by WobLight** [comment]
I guess AI shouldn't use shapeshift if it doesn't remove polymorph in first place.

**Comment by ratkosrb** [comment]
Happens because it casts it as Triggered which skips all checks.

**Comment by ghost** [comment]
I'll try with other check later, I might have fucked up

**Comment by ghost** [comment]
I wasn't used to the new event ai system so it took a bit of time but confirmed it was because of Triggered cast flag, Fix below

`UPDATE `creature_spells` SET `castFlags_1`='1' WHERE  `entry`=38400;`

**Comment by ratkosrb** [comment]
You should use the Script Editor when working with EventAI or the creature_spells system, it will make your life much easier. The system and the editor are designed together.

https://github.com/brotalnia/ScriptEditor/releases/tag/v7.0

**Comment by ghost** [comment]
Thanks i'll definitely use it, looks way easier, i'll close the issue now feel free to use the SQL if you need it

**Comment by ratkosrb** [comment]
Removed the triggered flag from that spell here https://github.com/vmangos/core/commit/cc9f80733b5ce66277147942af339dbac81b09a8
