### ISSUE TITLE
Incorrect Ouro Submerge timer 🐜 [Bug]

### ISSUE THREAD

**Issue by Velite12** [vmangos/core#963]
## 🐜 Bug report - AQ40 Progression

In the file  at https://github.com/vmangos/core/blob/development/src/scripts/kalimdor/silithus/temple_of_ahnqiraj/boss_ouro.cpp, 
SUBMERGE_TIMER is stated to be 60000(ms) (60 seconds), but below in the function void Submerge(bool isReset = false), the comment states that "Ouro has a chance to submerge every 1.5minutes", which will not happen if the timer is set to 60 seconds.

### Expected behavior

According to the comment, Ouro should decide to submerge every 1.5 minutes. But he is making that decision at 1 minute. 

Proof:
Source : http://wowwiki.wikia.com/wiki/Ouro

https://www.youtube.com/watch?v=hJXUVjlFNqQ&feature=emb_title

In this video, The fight starts at 0:15, and the first submerge is at about 3:20. So ouro skipped the first submerge due to a sand blast at 1:45, and he decided to at this point, 1.5 mins later. Possibly a delay calculated after he sandblasted, which is currently reflected in the code, but this decision happened at about a 1.5 minute interval.

### Steps to reproduce

1. Start ouro encounter
2. Wait 1 minute
3. He will submerge
4. ...
5. Profit

### Version & Environment

Client Version: 1.12.1.5875

**Comment by ulfgebhardt** [comment]
Could you make a PR for this @Velite12 ? <3

**Comment by Velite12** [comment]
> 
> 
> Could you make a PR for this @Velite12 ? <3

Sorry, can you clarify what a PR is? Thanks.

Oh you mean pull request, sure.
