### ISSUE TITLE
🐞 [Bug] Lightning Shield triggers on ranged attack

### ISSUE THREAD

**Issue by ulfgebhardt** [vmangos/core#967]
## 🐞 Bug report - Spell

As to be seen in combat log the `Lightning Shield` is triggered when the mobs shoots an arrow. I believe that this is incorrect.

![image](https://user-images.githubusercontent.com/1238238/103504989-4d3f9300-4e59-11eb-9ea0-b30bb4f4e75b.png)

### Expected behavior

`Lightning shield` should not trigger on ranged attacks.

This might be due to the mob attacking with ranged melee attack (aka shoot). Might be reproducabale with a hunter aswell

### Steps to reproduce

1. Make a Troll Shaman
2. Lvl 8
3. Learn & Cast`Lightning Shield`
4. Attack Razormane Scout up the hills near `Razor Hill`, stay at range
5. ...
6. Profit

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  https://github.com/vmangos/core/commit/dfe94c8587788b049b8e4bedf93042bfcbe30678

OS Client: Arch Linux
OS Server: Debian Linux

### Crashlog

- None

**Comment by rosen40** [comment]
according to the procs in the default dbc (which are also the same in spell_template) it procs on melee attacks, ranged attacks and spells too, you should be able to insert the proper proc mask in spell_proc_event and it will fix it for all ranks too.

INSERT INTO `spell_proc_event` SET `procFlags` = 40 WHERE `entry` = 324;

**Comment by ulfgebhardt** [comment]
Does this mean this is blizzlike behavior? @rosen40

**Comment by ulfgebhardt** [comment]
`
The caster is surrounded by 3 balls of lightning.  When a spell, melee or ranged attack hits the caster, the attacker will be struck for 13 Nature damage.  This expends one lightning ball.  Only one ball will fire every few seconds.  Lasts 10 min.
`

Apparently it is - sorry then for the fuzz 

https://classic.wowhead.com/spell=324/lightning-shield
