### ISSUE TITLE
quests、npc、creature  in Thousand Needles and Maraudon dungeon and some setiing has some problem（bug？）

### ISSUE THREAD

**Issue by chenps10** [vmangos/core#97]
its almost fixed，tks for help，closed this issue

**Comment by chenps10** [comment]
![qq20190104-0](https://user-images.githubusercontent.com/39617409/50673928-b9921c80-101c-11e9-96f3-b83c64ce4a69.jpg)

After taking the quest, NPC flew away in the sky  - -！

**Comment by chenps10** [comment]
and more one：
quest in Stonetalon Mountains：Protect Kaya
Kaya always was killed by creature at the quest beginning anytime
![5e73a49081fc91cb399e644142f6e1f5](https://user-images.githubusercontent.com/39617409/50681510-bc096c00-1046-11e9-8e0f-26cc56e032fa.jpg)

**Comment by chenps10** [comment]
and one more bug:
my setting is disable twosidewholist,but when the player number is higher than a certain number like about 50+，it is always can see twosidewholist

my setting like this：
<img width="278" alt="wx20190104-174850 2x" src="https://user-images.githubusercontent.com/39617409/50682237-2cb18800-1049-11e9-806b-39cbae2848cc.png">

**Comment by ratkosrb** [comment]
Kaya should no longer get attacked before the escort starts. https://github.com/vmangos/core/commit/96eaf9d8b071163858a505790337a852fb4e26a6

**Comment by chenps10** [comment]
> Kaya should no longer get attacked before the escort starts. [96eaf9d](https://github.com/vmangos/core/commit/96eaf9d8b071163858a505790337a852fb4e26a6)

Ok, I recompile and fix the problem with Kaya first. Thank you very much for your patience and kindness。

Looking forward to fixing other issues。

**Comment by DarkmoonRabbit** [comment]
你确定你是使用development分支吗？

**Comment by chenps10** [comment]
> 你确定你是使用development分支吗？

非常确定
