### ISSUE TITLE
🐛 [Bug] Copper vein not present despite being there on minimap

### ISSUE THREAD

**Issue by ronaldofenomeno** [vmangos/core#974]
## 🐛 Bug report
a copper node in westfall shows as a bright yellow dot above jangolode mine but its not there.

### Expected behavior
it should be there

### Steps to reproduce
![image](https://user-images.githubusercontent.com/33092150/103708620-002b0080-4fc2-11eb-9df8-ce9b8f6118f5.png)

### Version & Environment

<!--
  Client Version:
  - 1.12.1.5875

**Comment by NickTyrer** [comment]
Combined with #1026
