### ISSUE TITLE
Sunken Temple - Dragons immune to Hibernate🦂 [Bug]

### ISSUE THREAD

**Issue by Victorino76** [vmangos/core#979]
## 🦂 Bug report - Dungeon

The dragonkin mobs in Sunken Temple are completely immune to hibernate. This was not the case on previous private servers. They've always had a really high Nature Resist but have never been immune to Hibernate.
https://streamable.com/id0jhk
### Expected behavior

They should have a high chance to resist nature spells, but not be immune to Hibernate
### Steps to reproduce

1. Spawn a Nightmare Scalebane, Suppressor, Wanderer, Whelp, or Wyrmkin.
2. Cast Hibernate on any of them
3. 
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by ratkosrb** [comment]
We need somebody with a druid to test this on classic and record a video.

**Comment by ulfgebhardt** [comment]
I do not have an active account anymore, but I can confirm: It was possible to sleep them, but chances of resist were very high

**Comment by Gamemechanicwow** [comment]
Found a classic video where you can see a Nightmare Wanderer being hibernated.
https://youtu.be/VGtKRUTk8WA?t=1733
