### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by guyaqq** [vmangos/core#98]
Received SIGSEGV
./mangosd(_ZN3Map6RemoveI6CorpseEEvPT_b+0x1fe) [0x821e0e]
./mangosd(_ZN3Map14RemoveOldBonesEj+0xd0) [0x813850]
./mangosd(_ZN3Map6UpdateEj+0x2d3) [0x817653]
./mangosd(_ZN21ContinentAsyncUpdater3runEv+0x1a) [0x829d7a]
./mangosd(_ZN9ACE_Based6Thread10ThreadTaskEPv+0x27) [0xcca727]
/usr/local/lib/libACE.so.6.5.0(_ZN21ACE_OS_Thread_Adapter6invokeEv+0x86) [0x7f7190a65dd6]
/usr/lib64/libpthread.so.0(+0x7dd5) [0x7f718f8aadd5]
/usr/lib64/libc.so.6(clone+0x6d) [0x7f718e927ead]

Segmentation fault

**Comment by ratkosrb** [comment]
This crash happens when you enable GridUnload. Open your mangosd.conf and change GridUnload to 0!

**Comment by ratkosrb** [comment]
It should be fixed by https://github.com/vmangos/core/commit/0ce4fce089763065057ec8dda953b29c1dd97a50
