### ISSUE TITLE
🐞 [Bug] Feign Death not killing player after 6 min.

### ISSUE THREAD

**Issue by Daribon** [vmangos/core#987]
## 🐞 Bug report - Spell

If you wait 6 min in feign death your character will just stand up.

### Expected behavior

In entire vanilla, if you spent the entire 6 min in feign death your character would die at the end.
This wasn't fixed until [2.0.1](https://wow.gamepedia.com/Patch_2.0.1).
>  You will no longer die when Feign Death is finished channeling.

[You can see the behavior on wow classic as well.](https://us.forums.blizzard.com/en/wow/t/died-while-in-feign-death/319820)
### Steps to reproduce

1. Creater hunter
2. .learn all_myclass
3. Cast feign death
4. Wait 6 min
5. Don't die after 6 min.

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  https://github.com/vmangos/core/commit/7d2f1e2923734ea1b983eeaa0208cfd158d4af02

OS Client:  Win 10 x64
OS Server: Win 10 x64

### Crashlog

- None

**Comment by Gelori** [comment]
Tested feign death  as commit "b00b1f4ca4fac047be4fecfb8500f888540bf928", Fri Jun 17 15:32:44 2022 +0300

Working as intended:
1) has channeling bar
2) killing the player at the end of channeling. 

Was already working or somebody shadowfixed it. nothing seen in commit logs )

Video of test:
https://www.youtube.com/watch?v=lhPaHq6m9Ss

Bug not actual, we can close!
