### ISSUE TITLE
🐛 [Bug] Feign Death no channeling bar.

### ISSUE THREAD

**Issue by Daribon** [vmangos/core#988]
## 🐛 Bug report

When casting Feign Death you currently have no channeling bar.
### Expected behavior

There should be a channeling bar whenever hunter uses feign death.

Here is from a [video](https://youtu.be/36EnwyDJ004?t=226) from vanilla:
![firefox_ozJEvirQ0x](https://user-images.githubusercontent.com/6137576/104110489-87d18180-52d8-11eb-8a8d-64f7e49b93d0.png)

Here is from a [video](https://youtu.be/NuCk1P1TXM0?t=478) from classic:
![firefox_ebg7eGLnCC](https://user-images.githubusercontent.com/6137576/104110513-b8192000-52d8-11eb-8ecc-281c7bd9da24.png)

### Steps to reproduce

1. Create a hunter
2. .learn all_myclass
3. Cast Feign Death
4. Watch as it has no channeling bar.

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  https://github.com/vmangos/core/commit/7d2f1e2923734ea1b983eeaa0208cfd158d4af02

OS Client: Win 10 x64
OS Server: Win 10 x64

### Crashlog

- None

**Comment by magicstone4** [comment]
You also died when the 6 minute timer ran out. If I remember correctly that was not changed until TBC.

**Comment by Gelori** [comment]
Tested feign death  as commit "b00b1f4ca4fac047be4fecfb8500f888540bf928", Fri Jun 17 15:32:44 2022 +0300

Working as intended:
1) has channeling bar
2) killing the player at the end of channeling. 

Was already working or somebody shadowfixed it. nothing seen in commit logs )

Video of test:
https://www.youtube.com/watch?v=lhPaHq6m9Ss

Bug not actual, we can close!

**Comment by Daribon** [comment]
Closing since feign death channel bar is nowadays working.
