### ISSUE TITLE
Strength of Earth(rank 5) totem does not spawn🐞 [Bug]

### ISSUE THREAD

**Issue by Victorino76** [vmangos/core#989]
## 🐞 Bug report - Spell

The totem does not appear when used. Other earth totems including lesser ranks of Strength of Earth totem do appear and function correctly.
https://streamable.com/cvkobu
### Expected behavior

The totem should appear normally.
### Steps to reproduce

1.add spell (Strength of Earth(rank 5))
2.cast Strength of Earth(rank 5)
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by ratkosrb** [comment]
What patch did you set the server to? Strenght of Earth Totem Rank 5 was added in patch 1.9, so the totem does not exist when server is set to an older version. That is not a bug, it is correct for the patch.
