### ISSUE TITLE
Grace of Air(rank 3) totem doesn't spawn🐞 [Bug]

### ISSUE THREAD

**Issue by Victorino76** [vmangos/core#990]
## 🐞 Bug report - Spell

Grace of air(rank 3) does not spawn correctly despite other air totems spawning correctly.
https://streamable.com/gur09n
### Steps to reproduce

1. add spell Grace of Air(rank 3)
2. cast Grace of Air(rank 3)
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by ratkosrb** [comment]
This spell and the totem it summons were added in patch 1.9. What patch is your server set to?
