### ISSUE TITLE
🐛 [Bug] Looting and casting at the same time.

### ISSUE THREAD

**Issue by Daribon** [vmangos/core#992]
## 🐛 Bug report

You can currently cast abilities while looting and you are able to loot while casting.

If you cast while looting, it should cancel the looting.
If you loot while casting, it should interrupt the cast.

### Expected behavior

You should not be able to loot while casting and you should not be able to cast while looting.

Tested on classic and is obviously a bug in vmangos.
### Steps to reproduce

1. Create a paladin
2. Kill any mob
3. Cast Holy Light
4. Loot
5. You will still be casting the heal.
5. Cast Holy Light
6. You will still be looting.
### Version & Environment

Client Version: 1.12.1.5875

Commit Hash: https://github.com/vmangos/core/commit/7d2f1e2923734ea1b983eeaa0208cfd158d4af02

OS Client: Win 10 x64
OS Server: Win 10 x64

### Crashlog

- None

**Comment by ratkosrb** [comment]
What are the exact errors shown when you try to do those things?

**Comment by Daribon** [comment]
No error shown when you begin cast while looting, it just cancels the looting.
If you begin looting while casting, it will say interrupted.
