### ISSUE TITLE
🐛 [Bug] x4 peacebloom

### ISSUE THREAD

**Issue by Undersong-Belarus** [vmangos/core#996]
While i was gathering peacebloom in Elvin Forest i've picked x4 flowers at once
Sorry for russian interface in the screenshot
![image](https://user-images.githubusercontent.com/74359351/104507121-5c5fd700-55f7-11eb-8286-24d058b4d7d8.png)
As i know flowers must be picked x1-x3 at once
https://classic.wowhead.com/object=1618/peacebloom#herbalism

**Comment by NickTyrer** [comment]
Closed in https://github.com/vmangos/core/pull/1097
